### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by benvddriessche** [wavebox/waveboxapp#1]
* Which version of Wavebox are you using? 3.1.0
* Which Operating System are you using? Windows 10

I'm getting the following error when trying to add a Google account (tried with 3 different accounts, 2 Inbox, 1 GMail, two of which are G Suite domains, 1 is a personal account):
![image](https://cloud.githubusercontent.com/assets/20052906/24517591/3639e2d0-157f-11e7-902c-8c121e05252b.png)
The error occurs after entering credentials (after password or after 2FA, depending on the account).

Other than that, looks great! 👍

**Comment by Dazzel** [comment]
Working fine on macOS.

**Comment by khilts** [comment]
I'm experiencing exactly the same issue as benvddriessche.

**Comment by Joothly** [comment]
Same for me.
![AboutPC](https://cloud.githubusercontent.com/assets/5357930/24520173/d3ee620a-1587-11e7-9398-6a12a354aba0.jpg)

**Comment by Thomas101** [comment]
Thanks for reporting everyone! We've located the issue and just uploading the new release now so should be live shortly...

**Comment by Dazzel** [comment]
Can confirm it's working with 3.1.1 👍

**Comment by benvddriessche** [comment]
Confirmed!

**Comment by Thomas101** [comment]
Hi everyone the uploads are available on https://wavebox.io/download or if you want restart Wavebox and wait a few minutes it will auto-download the new version. Thanks for reporting and holding tight in there! (First release bugs!)
