### ISSUE TITLE
Default Slack Icon Being Displayed

### ISSUE THREAD

**Issue by angoodkind** [wavebox/waveboxapp#100]
* Which version of Wavebox are you using? 3.1.5

* Which Operating System are you using? Mac OSX 10.11.6

When I added my first Slack team, it just used the default Slack icon. When I added a second Slack team, it used that team's icon. Is there a way to get the icon for the first team?

**Comment by Thomas101** [comment]
Hi, it depends how the team has been setup on slack as to where and if it can get the icon. You can however change the icon to be any image that you like...
* In Wavebox, right click on your account in the sidebar and go to `Account Settings`
* Press the `Change Account Icon` button and pick an image from your computer
