### ISSUE TITLE
Gmail unread count since last focused

### ISSUE THREAD

**Issue by gaberad** [wavebox/waveboxapp#1002]
* Wavebox Version: 4.9.1
* Operating System & Version: Windows 10

**Is your feature request related to an account type?**
gmail

**Describe the solution you'd like**
I'd like to have the unread count (taskbar badge specifically) only to show up when new emails have arrived since Wavebox was last focused. I'm not concerned with knowing how many unread emails I have in total, only that new emails have arrived since I last opened/viewed Wavebox. If you get what I mean.

I think it might be possible with custom JS (when the window is focused set the badge count to 0 or setHasUnreadActivity=false or something), but as far as I can tell the Wavebox API isn't available for gmail accounts?

**Comment by Thomas101** [comment]
> as far as I can tell the Wavebox API isn't available for Gmail accounts?

It isn't at the moment, but you could try adding Gmail with the Any Website button. From here you'll need to enable the API under Account Settings for that account...

![Screenshot 2019-04-03 at 15 51 53](https://user-images.githubusercontent.com/103586/55488698-7437b800-5628-11e9-9ea8-cc6206f1cac7.png)

Once you've got that setup you could set the badge with `wavebox.badge.setHasUnreadActivity(true)` and use the [document visibility api](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to clear it when bringing the window into focus.

<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> will bring up the developer tools for the open tab, and will let you play about on the console :)

**Comment by gaberad** [comment]
Yeah, got the first part working. I had to add the listener to window focus.

Just have to figure out how to listen for new email now.

thanks
