### ISSUE TITLE
Counts broke after upgrade to Mac v4.9.3

### ISSUE THREAD

**Issue by EvHaus** [wavebox/waveboxapp#1007]
* Wavebox Version: 4.9.3
* Operating System & Version: Mac OSX 10.14.4
* Account type (if applicable): Gmail

**Expected & actual behavior**
After Wavebox upgraded to 4.9.3 Wavebox isn't showing unread counts for Gmail anymore on my Mac application. I've tried restarting the app and tried pressing the "Resync" button but nothing is working.

**Steps to reproduce**
Use v4.9.3 on Mac. Connect a Gmail account. Send yourself an email message so that there's at least 1 unread message in your inbox. Note that Wavebox doesn't show any unread counters.

**Is the bug persistent or intermittent?**
Happens consistently. Computer and Wavebox restarts don't help.

**Screenshots**
N/A

**Additional information**
N/A

**Comment by nmat** [comment]
Can you see if this might help: https://wavebox.io/kb/gmail-inbox-type

has it worked before the 4.9.3? also if the knowledge base does not help can you share how you have setup the unread count and also gmail settings for the unread counters?

**Comment by EvHaus** [comment]
Thanks for that link. This was my issue:

<img width="902" alt="Screen Shot 2019-04-04 at 4 33 34 PM" src="https://user-images.githubusercontent.com/226640/55595150-6ac95100-56f7-11e9-9bb2-767e3d420bf7.png">

I've set the type to "Unread First" and all is good now.
