### ISSUE TITLE
Twitter is added instead of Refind

### ISSUE THREAD

**Issue by ferenczy** [wavebox/waveboxapp#1008]
* Wavebox Version: 4.9.3
* Operating System & Version: Windows 7 Ultimate 64-bit
* Account type: Refind

**Expected & actual behavior**
When I add Refind (an integrated app), Twitter is added instead.

**Steps to reproduce**
1. Click _Add Account_
2. Select _Refind_ from the list of integrated apps
3. Click _Next_ and _Finish_
4. An account with Refind icon is added, but Twitter's log in page is loaded

**Is the bug persistent or intermittent?**
Persistent.

**Comment by Thomas101** [comment]
Thanks! Looks like it was trying to take you to Twitter login for Refind. I've put a fix out. If you try and add it again it should work :)
