### ISSUE TITLE
Password and 2FA on Startup

### ISSUE THREAD

**Issue by Nycticebus** [wavebox/waveboxapp#1012]
* Wavebox Version: 4.9.3
* Operating System & Version: Ubuntu 18.04

**Describe the solution you'd like**
Upon startup of Wavebox, I believe there should be a password prompt to access this many accounts. 2FA should be included in this as well. 

Upon waking Wavebox after an extended period, the requirement to enter a password should be an option also.

**Comment by nmat** [comment]
Hello @Nycticebus,

Do you mean something like: https://github.com/wavebox/waveboxapp/issues/716

**Comment by Nycticebus** [comment]
@nmat Yes! But also with a 2FA option upon startup.

**Comment by Thomas101** [comment]
This is something we're working on adding and have got a semi-working development version of but unfortunately, it's been pushed back a few times and hasn't made it out into beta channel yet. I'm hoping to get the first version out over the next month or so.

I'll close this off in favour of #716, so we can continue tracking the feature there :)
