### ISSUE TITLE
[Feature request] A keyboard shortcut to focus Wavebox window

### ISSUE THREAD

**Issue by ferenczy** [wavebox/waveboxapp#1013]
I would like to have a global keyboard shortcut to focus the Wavebox window. Currently, I have to press the toggle window shortcut twice (because I have the window permanently open) to focus it.

**Comment by nmat** [comment]
There is a shortcut section in preferences for this already:

In Keyboard Shortcuts -> Toggle App

If you set this it can be used for both focus and Toggle App.

**Comment by nmat** [comment]
![image](https://user-images.githubusercontent.com/383031/56038440-40e4df80-5d32-11e9-876b-5c9a4b269e31.png)

**Comment by Thomas101** [comment]
I think the toggle app code needed a bit of love. I've changed it now so it checks if there's a window in focus - this will bring it to the front on toggle, or if already in the front hide it

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.9.5. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
