### ISSUE TITLE
Okta / Duo - Chrome is out of date

### ISSUE THREAD

**Issue by Fuzzwah** [wavebox/waveboxapp#1015]
* Wavebox Version: 4.9.3
* Operating System & Version: Windows 10 & Mac OSX 10.14.3
* Account type (if applicable): Gmail

**Expected & actual behavior**
Successful Duo login

**Steps to reproduce**
Attempt to log into Duo secured account

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**

![image](https://user-images.githubusercontent.com/658935/56266681-25157b00-6130-11e9-8734-1ac81a113280.png)

**Comment by Thomas101** [comment]
Thanks. The latest beta version (4.9.5) shouldn't have this problem. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Fuzzwah** [comment]
Success! Thanks.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
