### ISSUE TITLE
GMail unread count stuck

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#1018]
* Wavebox Version: 4.9.6 beta
* Operating System & Version: linux openSUSE Tumbleweed 20190420
* (Linux only) Install method: rpm (zypper)
* Account type (if applicable): Gmail

**Expected & actual behavior**
Wavebox should show the unread count in the account badge

**Steps to reproduce**
Always happens

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![image](https://user-images.githubusercontent.com/5107224/56685729-e43ed880-66d2-11e9-9c5f-1d5e2193dbbf.png)

**Additional information**
Unread count is stuck at 6 (see screenshot) even though I have no unread email. Reload, resync, reauthenticate... all are ineffective. Unread count even stays across reboots.

**Comment by nmat** [comment]
@Cris70 there is a knowledge base about the unread count on the main website.

https://wavebox.io/kb/gmail-inbox-type

Please check that to see if it helps with the unread counts

**Comment by Cris70** [comment]
Hi @nmat and thank you for your reply. Unfortunately the problem here is quite different: the read count is not only wrong, it is completely stuck. I mean, it's always at 6. 
Even if I get new messages, the unread count does not increase. When I read them, it does not decrease.
BTW I have checked out the KB and verified that the inbox type is in sync between the gmail configuration and Wavebox's.

**Comment by Thomas101** [comment]
@Cris70 which Inbox type are you using in Gmail & Wavebox? If you're using the `Default` Inbox type in Gmail, which Categories do you have enabled?

**Comment by Cris70** [comment]
@Thomas101 I am using default inbox type with all five categories enabled.

**Comment by Thomas101** [comment]
Thanks! There are a couple of other quick things that might clear it...

* If you click on the Tray Icon and use the menu's to navigate to your Gmail account, does clicking through any of the emails clear the count at all or does it still remain stuck?
* I know you've re-authenticated the account, but if you add it a second time and set it to `Default Inbox` as well does that show a different count, or still stuck on the 6?

**Comment by Cris70** [comment]
Hi @Thomas101 

> * If you click on the Tray Icon and use the menu's to navigate to your Gmail account, does clicking through any of the emails clear the count at all or does it still remain stuck?

This is where it gets even weirder: both the tray icon and the mini-window show the number 6, but then they do not show any message. See the screenshots:
![image](https://user-images.githubusercontent.com/5107224/57044956-7a8f7300-6c6c-11e9-9a7d-aa44ecb4eb95.png)

![image](https://user-images.githubusercontent.com/5107224/57045003-a3b00380-6c6c-11e9-800f-755e4684c6a9.png)



> * I know you've re-authenticated the account, but if you add it a second time and set it to `Default Inbox` as well does that show a different count, or still stuck on the 6?

I'm not sure I understand correctly here. Do you want me to add my google account to Wavebox a second time? Is it even possible?

Cris

**Comment by Thomas101** [comment]
Thanks for sending the info! I have to be honest, I wasn't expecting that at all. My initial suspicion is that the feed is returning something that we're not expecting. It would be great to get an eye on that. The current logging stack is a little weak here, but you should be able to get an idea of what's sent back by doing the following...

1. Right-click in a blank area in the Gmail window. In the popup menu pick `Inspect`
2. In the window that appears click on the console tab and paste the following...

```
window.fetch('https://mail.google.com/mail/feed/atom/%5Esq_ig_i_personal', { credentials:'include'}).then(r=>r.text()).then(r=>console.log(r))
```

3. You should end up with something like the following, can you send a screenshot of this (feel free to blank out any personal info)...
![Screenshot 2019-05-02 at 09 18 15](https://user-images.githubusercontent.com/103586/57063460-442d1480-6cbb-11e9-8d33-4e7cade5e4bd.png)

---
> I'm not sure I understand correctly here. Do you want me to add my google account to Wavebox a second time? Is it even possible?

In terms of adding the google account a second time, you can do this. Just click the plus button in the bottom-left of the app, pick Gmail, follow the on-screen wizard to sign in and you'll get a second entry for your Gmail which is completely isolated from the first :)

**Comment by Cris70** [comment]
Hi @Thomas101. I followed your instructions and got a surprise: the server tells me I'm not authorized (see screenshot below). I tried again to reauthorize and to reload, but it still tells me I'm unauthorized.
![image](https://user-images.githubusercontent.com/5107224/57112213-5486d300-6d3f-11e9-9274-7d7aa9742c7a.png)

So I followed the second part of your instructions and added my gmail account a second time. And it is actually working correctly, showing no unread messages.

**Comment by Cris70** [comment]
@Thomas101, I've been using the newly created account in Wavebox since yesterday. Meanwhile, the old one has been showing the usual "6" badge.
Ten minutes ago, I noticed that the badge had changed to an exclamation mark:

![Screenshot_20190504_000135](https://user-images.githubusercontent.com/5107224/57168111-a8a5bc00-6e00-11e9-9480-8496c878a8da.png)

So I clicked on the old account: it showed a page asking for reauthentication. I did it and - voila - the "6" badge is gone and the account is now correctly synced. 

The only difference I noticed, with respect to when I was forcing reauthentication, is that this time it asked me which Google account I wanted to use. I don't remember having to do this step the other times.

Hope this helps!
I'm still keeping the old account in case you need more investigation.

Cris

**Comment by Cris70** [comment]
@Thomas101 unfortunately today I had problems with the new account, too.
When I started Wavebox I found that the new account was asking for reauth. But when I tried to reauthorize, it was stuck in a loop: look at this animated capture
![peekM5LD1Z](https://user-images.githubusercontent.com/5107224/57409864-a6b96f80-71e9-11e9-9bfc-fba83765d5fa.gif)

I tried again and again without any success. Then I went to the account settings, where I chose "remove credentials" and also (just to be sure) I chose "Clear all browsing data". That allowed me to regain control of the account.

**Comment by Thomas101** [comment]
@Cris70 how are you connected to the web, are you behind a proxy or vpn server?

**Comment by Thomas101** [comment]
@Cris70 4.9.7beta should handle this a little bit better now - let me know if you see the same issue again!

**Comment by Cris70** [comment]
@Thomas101 I'm directly attached to the web (no proxy or vpn in between).
BTW I'm now on v4.9.8beta. I'll report back to you if I experience any more issues of this type.
Thank you!

**Comment by Thomas101** [comment]
Thanks @Cris70 these fixes have gone out into the stable version. I'll close this off for now, but if you see it get stuck again just re-comment and I'm happy re-open the issue and take another look :)

**Comment by Cris70** [comment]
Thank you very much for your help @Thomas101 !

**Comment by Thomas101** [comment]
No worries, that's what we're here for :)
