### ISSUE TITLE
feature: support native slack calls

### ISSUE THREAD

**Issue by BertLamb** [wavebox/waveboxapp#102]
* Which version of Wavebox are you using? 3.1.5

* Which Operating System are you using? Windows 10

Currently using `/call` from slack will open a call uri in the operating system browser, this is great in that it works at all, but chrome (my default browser) doesn't give good control over microphone and speaker settings for slack calls conducted this way.  Making calls from the Windows Slack app allows for much better control over microphone/speaker options for the call.  If wavebox could support this slack calling feature in the same way that the windows slack app does that would be amazing.  

Currently because I like to use a headset for slack calls, if I want to make a slack call I am forced to open the slack desktop app and make the call from there.

**Comment by Thomas101** [comment]
Thanks, we'll look to see if this is possible

**Comment by nmat** [comment]
I tested to do a call recently through slack using /call. and it seems to use the wavebox browser connection now.

@BertLamb do you mean to integrate it more or can you test this in: 3.5.0?

**Comment by Thomas101** [comment]
Looks like this works with the latest versions, going to close this off for now

**Comment by trollfred** [comment]
Does not work for facebook messenger. the page asks for access to microphone, but no there's no way to allow it
