### ISSUE TITLE
Hard Error message, crashed app when browsing web with Google Chrome

### ISSUE THREAD

**Issue by Ymetro** [wavebox/waveboxapp#1020]
* Wavebox Version: 4.9.3
* Operating System & Version: Windows 10 64-bit build 17758.1

**Expected & actual behavior**
Expected: apps in Wavebox keep running in memory
Actual behavior: when loading a media filled page in Google Chrome tab, Wavebox gives a not further specified message: "Hard Error" and then fails to load the app or it just crashed. If I click the Reload button in the middle of the Wavebox app page, the browser page in Chrome crashes. The PC has 32 GB of RAM in it and it does not even uses only half of it (last time 42%). 
Mostly a PC reboot fixes this for a while. It seems to be alternating on each system boot. 
Has this to do with memory allocation? Or is it a hardware failure and I could check my RAM modules/controller with Memtest? The memory modules are brand new and complete system freezes and BSODs almost never occur. I remember it happening only once. 

**Steps to reproduce**
I do not know how to reproduce. It mostly just happens after a while or at Windows start at earlier versions of Wavebox. Since 4.8.3 if I recall correctly. 

**Is the bug persistent or intermittent?**
On my PC it seems to do this after a while or directly at loading Wavebox at Windows 10 starting the app.

**Comment by Thomas101** [comment]
Is this something that happens regularly or has it been difficult to reproduce on a reocurring basis?

Looking around the web, the general suggestion for "Hard Error" is to run a disk scan. Might be worth giving this a try to see if it throws anything up.

**Comment by Ymetro** [comment]
Sorry, I no longer intend to use Wavebox.
