### ISSUE TITLE
WhatsApp Web no longer works with 4.9.7beta [broken]

### ISSUE THREAD

**Issue by wishx** [wavebox/waveboxapp#1024]
* Wavebox Version: 4.9.7beta
* Operating System & Version: Linux Mint 19.1
* (Linux only) Install method: .deb
* Account type (if applicable): WhatsApp Web

**Expected & actual behavior**
WhatsApp worked in the last beta, but is now broken in 4.9.7beta. 
Page says the following:
WhatsApp works with Google Chrome 36+
To use WhatsApp, update to CHrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.
[download goodo chrome button]

**Steps to reproduce**
Simply try to use a WhatsApp account. Reproducible with account, or by removing and creating new account.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
Attached

**Comment by wishx** [comment]
http://i.imgur.com/jNPZoJo.png

**Comment by Thomas101** [comment]
Thanks for reporting! Looks like the production build contained a double space in the UserAgent which borked WhatsApp's super sensitive UserAgent parsing.

I've just pushed 4.9.8beta which contains a fix for this :)
