### ISSUE TITLE
Gmail - Cannot drag emails to labels (folders)

### ISSUE THREAD

**Issue by Mooz80** [wavebox/waveboxapp#1028]
* Wavebox Version: 4.10.1
* Operating System & Version: Windows 10
* Account type: Gmail

When I try to drag an email from the inbox into a label (folder) it's always denied. 
It does work in Chrome. 

![image](https://user-images.githubusercontent.com/18400396/57930286-89d50a00-7883-11e9-98ec-78051667b665.png)

**Comment by nmat** [comment]
I tested quickly here on windows 10 to drag and drop without any problems in gmail.

**Comment by Mooz80** [comment]
Problems seems to happen when I've used the application for a while and not right after start-up. 
I will try to be more clear to reproduce the problem, do not spend time on this for now.
