### ISSUE TITLE
feature: right click "Search with Google"

### ISSUE THREAD

**Issue by BertLamb** [wavebox/waveboxapp#103]
* Which version of Wavebox are you using? 3.1.5

* Which Operating System are you using? windows 10

In Slack or in Chrome you can select text and then have an option to search with Google (I believe in Chrome the search provider is configurable, but just having Google would be a great first start).

This would be great to have everywhere in wavebox as well

![image](https://cloud.githubusercontent.com/assets/1178153/25200423/4588dc44-251c-11e7-8752-07c3717d8984.png)

**Comment by Thomas101** [comment]
Thanks, we'll add this in

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which adds this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!
