### ISSUE TITLE
[feature-request] Preserve URL state for apps in "sleep mode"

### ISSUE THREAD

**Issue by nesterow** [wavebox/waveboxapp#1031]
* Wavebox Version: 4.10.1 (deb)
* Operating System & Version:  Ubuntu 18.04

**Is your feature request related to a problem? Please describe.**
When an app is going into "sleep mode" it doesn't save last visited URL. So when I launch a "sleeping" application I open "home page" instead of the page I last visited. It is most annoying when an app is scheduled for sleep in 10min inactivity and I have to pick up work I left. 

**Is your feature request related to an account type?**
JIRA

**Describe the solution you'd like**
Preserve URL state in "sleep mode"

**Comment by Thomas101** [comment]
Under Account Settings you can enable `Restore last page on load` which will ensure it takes you back after sleep :)

<img width="530" alt="Screenshot 2019-05-23 at 08 41 52" src="https://user-images.githubusercontent.com/103586/58234541-b632cf80-7d36-11e9-9fb4-271998719707.png">

**Comment by nesterow** [comment]
Thank you ;)
