### ISSUE TITLE
Cannot open Wavebox

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [wavebox/waveboxapp#1033]
4.10.1 - this is the latest version number AppData\Local\wavebox
After finally updating my Windows 10 I Wavebox no longer opens.
I've tried opening it from file location and selecting it from latest version folder, opening update, but nothing works.

**Comment by My-Name-Is-Adam** [comment]
Resolved by redownloading Wavebox with it still on my machine, no data loss :D

**Comment by Thomas101** [comment]
Great to hear that worked! Let me know if you have any more problems :)
