### ISSUE TITLE
WhatsApp notifications in systray icon missing

### ISSUE THREAD

**Issue by nicolafarina** [wavebox/waveboxapp#1036]
* Wavebox Version: 4.10.1
* Operating System & Version: Windows 10

WhatsApp new messages are not displayed anymore in systray icon counter since some days (last week more o less).

Thanks.

**Comment by Thomas101** [comment]
Thanks! I've just put a patch out for this to fix it. The app will fetch the new config automatically, but if you want to force it, just restart the app :)

**Comment by nicolafarina** [comment]
Works great again, thanks!
