### ISSUE TITLE
Feature request: custom icons in notifications

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#104]
* Which version of Wavebox are you using? [ 3.1.5]

* Which Operating System are you using? [Mac OSX 10.12.4, Ubuntu 17.04]

It would be really great if instead of just having the wavebox icon in the system notifications a user could have differentiated icons according to the source service. E.g. Slack icon, Gmail icon, etc. 

I think this has more to do with the way notifications are implemented in the OS, but if you can have a look at this, it'd be great.

**Comment by MoxmiNu** [comment]
Wavebox pro 3.1.5 on Fedora 25 + Gnome:
System tray icon only shows notifications for new emails, would like it to also show notifications for new slack messages.
Not sure if it shows them on Mac / WIndows

**Comment by Thomas101** [comment]
We'll have a look see if we can add it in!

**Comment by Thomas101** [comment]
Hi in 3.1.8 the account icon shows in the notifications. This isn't completely cross platform yet, but when we take a look at #83 to hopefully bring notification parity across platforms this will make its way out then too. Thanks!

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
