### ISSUE TITLE
Gmail custom unread mode missing

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#1043]
I don't know if this is a bug or the some "new" feature but from the Wavebox beginnings, there always was an option to have a custom unread mode where user can set up which folders to watch and notify upon received email. In the latest version, I've noticed that this option is gone.

* Wavebox Version: 4.10.1
* Operating System & Version: ElementaryOS 5.0 (Ubuntu 18.04 based distro)
* (Linux only) Install method: Debian installer from the apt repository
* Account type (if applicable): GMail

**Comment by Thomas101** [comment]
There's been quite a bit of change around the Gmail API recently, so we've had to remove the old API call which gave us the ability to support this and have moved to an alternative method which allows us to support the majority of uses cases, but unfortunately not this one. We're actively working on bringing it back, but some of this is dependent on Google

**Comment by WebShapedBiz** [comment]
Thank you, Thomas, for your quick reply. It's funny to see that all the folders I've previously set up to watch for new emails are still working, I just cannot edit those settings anymore to add a new folder. Hope to see this resolved quickly.

Cheers.

**Comment by WebShapedBiz** [comment]
I know it's an annoyance but is there any news on this? It was added for 4.11 milestone but now on 4.11.4 is nowhere to be found.

Cheers.
