### ISSUE TITLE
Gmail Unverified Apps will have limited access after 8 July

### ISSUE THREAD

**Issue by pauby** [wavebox/waveboxapp#1044]
* Wavebox Version: 4.10.1
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail

I've received an email from Gmail explaining that I have Unverified Apps in my domain and due to the authentication used they _may_ be limited as of 8 July. The Unverified App is Wavebox:

![image](https://user-images.githubusercontent.com/12760779/59496993-7caf3900-8e8a-11e9-9302-705299ff8502.png)

I've not had anything from Wavebox around this. The email explains what I need to do / not do but this only applies because I installed the app before 8 July. If I (or a new user) installs it after 8 July there may be other steps needed before Wavebox will work.

I am happy to add the text of the email here, but it's long so I don't want to do unless you guys have no idea what I'm talking about. Happy to forward it onto somebody in Wavebox if need be.

**Comment by Thomas101** [comment]
Thanks for reporting. This will not impact your use of Wavebox in any way and relates to a historic API token that is no longer in use.

If you installed Wavebox before version 4.0.0, you will have this old API token in your account, hence the email to some Gsuite admins from Google. Version 4.0.0 onwards already has the latest Google update and will continue working as normal beyond July the 8th.

If you've got any more questions, I'm more than happy to help :)

**Comment by pauby** [comment]
@Thomas101 Just to clarify I can remove that 'Unverified App' listed in the email?

While this has proved to be a moot issue hopefully it helps somebody else!

**Comment by Thomas101** [comment]
@pauby if you want to remove the Unverified App, you can. There are two ways of doing it...

#### From the Gsuite Admin screens
1. From the Gsuite Admin screens, go to your User Management and then the Security section.
2. Locate `Connected Applications` and you should see a set of entries for `Wavebox App`. You can either remove just the entry that Google has emailed you about (this will have `access to Gmail` listed in the `Access level` field) or remove all three.
![Screenshot from 2019-06-14 10-53-55](https://user-images.githubusercontent.com/103586/59501368-4924dc80-8e93-11e9-8301-037904773dd2.png)
3. If you Sign back into Wavebox, or re-add your Gmail account the unaffected `basic account info` entries for Wavebox App` will be added back in.

#### From your account
1. Visit https://myaccount.google.com/permissions
2. From there, locate Wavebox (which will have the historic permission set) and click `remove access` 
<img src="https://user-images.githubusercontent.com/103586/59500405-43c69280-8e91-11e9-81d8-282c3a98d537.png" width="400px" />

3. The app will continue to work without the API access, but if you sign into you Wavebox account using Google, or re-add the Gmail account to the app, the Wavebox app will be reauthorized with the new permission set
<img src="https://user-images.githubusercontent.com/103586/59500450-5a6ce980-8e91-11e9-955d-f09f864245a6.png" width="400px" />

Just as a side note, the Gsuite admin screens seem to take a while to update, so in our case the user counts remain whether you remove the app or not.

**Comment by stefanocrosta** [comment]
Great! You should make a blog post about this!!! took me a while to find the info, and was about to submit a support ticket!
