### ISSUE TITLE
Disable account mouse over

### ISSUE THREAD

**Issue by chrisblossom** [wavebox/waveboxapp#1046]
* Wavebox Version: `4.10.1`
* Operating System & Version: `macOS 10.14.5`

**Is your feature request related to a problem? Please describe.**

Maybe this is already possible (I don't know how if so), but I would like to be able to disable the mouse-over informational window of gmail accounts. In my experience it is always a mistake when it is shown and gets in the way of what I am trying to do.

**Is your feature request related to an account type?**

Gmail (but probably applicable to all account types)

**Describe the solution you'd like**

Be able to disable mouse-over information window.

**Additional info**

<img width="478" alt="Screen Shot 2019-06-07 at 9 02 41 AM" src="https://user-images.githubusercontent.com/1595871/59787475-5e787d00-927e-11e9-97f3-9bc277bef9ce.png">

**Comment by Thomas101** [comment]
Under settings UI, there's a tooltips section...
<img width="557" alt="Screenshot 2019-06-20 at 08 00 37" src="https://user-images.githubusercontent.com/103586/59827839-896fd900-9331-11e9-8117-7207dc21761e.png">

You can selectively disable them in the sidebar/toolbar/both, not show the Recent, Pinned & Tasks and also change the timeout if they're appearing too quickly :)
