### ISSUE TITLE
Mixmax seems broken.

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#1048]
* Wavebox Version: [e.g. 3.0.0]
![2019-06-27_14h59_33](https://user-images.githubusercontent.com/689204/60303780-35926080-98ec-11e9-9a85-2d7d92979fa7.png)

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
![2019-06-27_15h00_31](https://user-images.githubusercontent.com/689204/60303825-52c72f00-98ec-11e9-962e-5ca3a60fac34.png)

* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
Google

**Expected & actual behavior**
Mixmax doesn't work when initially enabled.
It seems to work (the M menu in the top right lights up) but opening an email displays "Click here to enable Mixmax for your Gmail".
Also, restarting Wavebox, Mixmax is completely disconnected.

This has been happening for at least 2 months I just haven't got around to reporting.
Thanks! 👍

Jeremy

**Comment by Thomas101** [comment]
Hey, thanks for reporting. I've pushed a fix out which I think should solve this. The app will grab the updates in the background, but if you want to force it do run right away, here's how

1. Go to Settings > Extensions and press the check for updates button
2. Wait for the spinner under Mixmax to disappear and change to `Restart to update`
3. Restart the app
4. You'll probably have to sign in to Mixmax at this point, but you should be good from there

Let me know if this works for you too :)

**Comment by GollyJer** [comment]
All fixed up! Thanks! 👍
