### ISSUE TITLE
Google Chat notifications not coming through

### ISSUE THREAD

**Issue by kcinman11358** [wavebox/waveboxapp#1049]
* Wavebox Version: 4.10.1
* Operating System & Version: Windows 10

* Account type (if applicable): Google Chat

**Expected & actual behavior**
When I get a message through Google Chat, there is no desktop notification. Also, it is just a dot, not how many messages. It works fine for Google Hangouts

**Steps to reproduce**
Get a message from someone and view it in Google Chat

**Is the bug persistent or intermittent?**
Everytime

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**

**Comment by kcinman11358** [comment]
bump.

Anyway to bump this in priority? We as a company switched to Gmail and are really missing the outlook type interface of having an application dedicated to email, calendar, chat, etc. I've been using wavebox since the day we switched and love it. But really need a better notification system so that I know when I get pinged.

Thanks

**Comment by Thomas101** [comment]
Have you made sure that notifications are enabled in your Google Chat Settings? You may need to click this to grant access first.

![Screenshot 2019-11-21 at 11 00 23](https://user-images.githubusercontent.com/103586/69332333-5cac4e80-0c4e-11ea-9682-4bdcd639c64b.png)

Also in Wavebox make sure that the account isn't sleeping by going to Account Settings & disabling sleep

**Comment by kcinman11358** [comment]
@Thomas101 yes all enabled
![image](https://user-images.githubusercontent.com/7409848/69448407-12929e00-0d1e-11ea-8cc4-5f25997f3425.png)

**Comment by Thomas101** [comment]
After clicking the `enable desktop notifications` button do you get any notifications? The conversation that you want to receive the notifications on will have to be inactive (i.e. not the one you're currently viewing)

**Comment by kcinman11358** [comment]
Nope. I've had this enabled since the start and haven't gotten a notification with google chat. I get it with google hangouts though :/

**Comment by kcinman11358** [comment]
After testing a little more, the notification only comes through when focused on the google chat. I would consider this to be a bug since the point of wavebox is to notify the user for many different apps in one spot

**Comment by Thomas101** [comment]
If you right-click on chat and go to account settings, can you check if sleep is disabled?
![Screenshot 2019-11-26 at 11 04 29](https://user-images.githubusercontent.com/103586/69624449-9ad5b380-103c-11ea-9c01-77ceb3665428.png)

**Comment by kcinman11358** [comment]
yes, sleep is disabled (always have been)
![image](https://user-images.githubusercontent.com/7409848/69651958-80004080-1036-11ea-93d1-7e84d73769ad.png)

**Comment by kcinman11358** [comment]
not sure if anything changed, but it has been working for me recently. Thanks if something was done :) closing
