### ISSUE TITLE
Missing services

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#105]
* Which version of Wavebox are you using? [e.g. 3.0.0]
v3.1.5
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
ElementaryOS Loki

With the free account, I was using few Google services. Without any notice or blog post or new release, those services are now missing from my Wavebox.
I'm not complaining, I just wanna check if there is something wrong with my Waverbox or is that a new price policy from developers.

Thank you for your time and effort put into Wavebox.

Cheers.

**Comment by DFelten** [comment]
In the first days you get the premium version of Wavebox. As soon as this has expired, the premium features disappear. Unfortunately, the features like the calendar are part of it.
