### ISSUE TITLE
Opening Gmail settings causes tab to crash

### ISSUE THREAD

**Issue by signe** [wavebox/waveboxapp#1055]
* Wavebox Version: 4.1.2beta
* Operating System & Version: macOS 10.15 Beta (19A501i)
* Account type (if applicable): Gmail

**Expected & actual behavior**
Attempting to open the Gmail settings (to adjust filtering, etc.) is causing the tab to crash.  I see this behavior on multiple accounts.

**Steps to reproduce**
* Add Gmail account
* Click the gear
* Click settings

![image](https://user-images.githubusercontent.com/249456/61001887-5065cb80-a315-11e9-8409-d617cb493fa6.png)

![image](https://user-images.githubusercontent.com/249456/61001917-5e1b5100-a315-11e9-8a9f-408f04e2482e.png)

**Is the bug persistent or intermittent?**
Completely persistent across multiple accounts

**Screenshots**
See above

**Additional information**

Uninstalled the one Extension I had loaded.  No change.

Enabled Metrics Log before causing the crash.  Doesn't seem to contain anything of interest.

```
Wed Jul 10 2019 13:21:10 GMT-0700 (Pacific Daylight Time) : 1562790070509 : [{"cpu":{"percentCPUUsage":0,"idleWakeupsPerSecond":0},"pid":25419,"type":"Tab","memory":{"pid":25419,"bytes":45522944}},{"cpu":{"percentCPUUsage":0,"idleWakeupsPerSecond":0},"pid":25418,"type":"Tab","webContentsInfo":[{"webContentsId":20,"pid":25418,"description":"Gmail: Google","url":"https://mail.google.com/mail/u/0/#inbox"}],"memory":{"pid":25418,"bytes":267644928}},{"cpu":{"percentCPUUsage":0.0007504707226696591,"idleWakeupsPerSecond":1},"pid":670,"type":"Tab","webContentsInfo":[{"webContentsId":1,"pid":670,"url":"chrome-extension://elifhakcjgalahccnjkneoccemfahfoa/chrome/background.html"}],"memory":{"pid":670,"bytes":10596352}},{"cpu":{"percentCPUUsage":0.015386490128216572,"idleWakeupsPerSecond":5},"pid":693,"type":"Tab","webContentsInfo":[{"webContentsId":4,"pid":693,"description":"Gmail: Google","url":"https://mail.google.com/mail/u/0/#inbox"}],"memory":{"pid":693,"bytes":219799552}},{"cpu":{"percentCPUUsage":0.34729834335095217,"idleWakeupsPerSecond":91},"pid":672,"type":"Tab","webContentsInfo":[{"webContentsId":2,"pid":672,"description":"Main Wavebox Window"}],"memory":{"pid":672,"bytes":156209152}},{"cpu":{"percentCPUUsage":0.16375170370327694,"idleWakeupsPerSecond":2},"pid":673,"type":"Tab","webContentsInfo":[{"webContentsId":3,"pid":673,"description":"Wavebox Tray Popout"}],"memory":{"pid":673,"bytes":90660864}},{"cpu":{"percentCPUUsage":0.4475566232600852,"idleWakeupsPerSecond":248},"pid":610,"type":"Browser","memory":{"pid":610,"bytes":235442176}},{"cpu":{"percentCPUUsage":0.1923053192803377,"idleWakeupsPerSecond":77},"pid":665,"type":"GPU","memory":{"pid":665,"bytes":67432448}}]
```

**Comment by Thomas101** [comment]
Thanks for reporting. This is something that we're seeing with macOS beta at the moment. As a workaround, if you go to Settings > Advanced and disable `Process Sandboxing` it should stop the crashes. We'll push a permanent fix out shortly.

**Comment by signe** [comment]
Thanks!  This appears to be fixed in the beta that was pushed today.  I didn't make any settings changes.

**Comment by Thomas101** [comment]
Whoops sorry, forgot to message and say I'd pushed a patch in the beta :)
