### ISSUE TITLE
Fedora with Deepin Desktop

### ISSUE THREAD

**Issue by jjworld** [wavebox/waveboxapp#1057]
* Wavebox Version: 4.10.1 and confirmed on 4.10.3beta
* Operating System & Version: Fedora 30 with Deepin Desktop
* (Linux only) Install method: rpm
* Account type (if applicable): n/a

Been using 4.10.1 on Fedora 30 with Gnome for some time without issue. When switching to Deepin Desktop, the Wavebox icon disappears from the list of installed applications. Reinstalling has no effect. Switching back to Gnome, the icon is back.

While using Deepin, running /opt/wavebox/Wavebox from a terminal does launch Wavebox. It may be an electron thing, not really into it enough to determine the origin of the problem.

**Comment by Thomas101** [comment]
Thanks for reporting, when you ran `/opt/wavebox/Wavebox` from the terminal did it bring up any errors? There's also a `/opt/wavebox/wavebox.sh` script that might be worth running; Piping output to `/dev/null` fixes issues on a few platforms and this script does that

**Comment by jjworld** [comment]
I did get an error with the fonts but it looked more like a warning than an error. I tried running the .sh and it didn't seem to want to execute. (or at least I didn't see anything visible happen)

I've also tried adding the icon to the Favorites while it is open. The icon appears in favorites, but when I click on it, nothing happens (same effect as the .sh execution).

The most notable issue seems to be the missing icon, though. I've not had time to test this but I see reports of other Electron apps having similar problems when changing the desktop in Fedora.

**Comment by Thomas101** [comment]
> The most notable issue seems to be the missing icon, though. I've not had time to test this but I see reports of other Electron apps having similar problems when changing the desktop in Fedora.

Do you have any links for this or a list of apps - might help me narrow down where the issue is

**Comment by bsquizz** [comment]
It looks like deepin doesn't like something about the `wavebox.desktop` file. This solved the problem for me:

Edit the `/usr/share/applications/wavebox.desktop` file and change the `Exec` line from this:
```
Exec=/opt/wavebox/Wavebox --mailto=%u \> /dev/null
```
to this:
```
Exec=/opt/wavebox/Wavebox
```

**Comment by jjworld** [comment]
That seemed to do the trick, thank you. Deepin is an extraordinary desktop for Fedora. I'm not sure how to get this desktop file tweak into the distro for other users, but it would be a good idea. I'd hate to see folks drop Wavebox if they think it won't work with Deepin.
