### ISSUE TITLE
Feature Request: Resizable Icons on left scrollbar. 

### ISSUE THREAD

**Issue by patrickcurl** [wavebox/waveboxapp#106]
It'd be nice if you could allow resizing the ... Sidelist-Item Main Avatar icon, when you have a lot of slack channels it gets busy would be nice if maybe having a 20px 30px and 40px option. 
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Arch Linux

**Comment by Thomas101** [comment]
Do you think shrinking the width of the sidebar would go along with this too or would you keep that the same width?

**Comment by patrickcurl** [comment]
I personally like the width, but it does add a little extra padding when resizing icons so might be better to also take out that padding or add resizing.

Currently to get the desired effect I open developer and just add this to the last style element: 
.ReactComponent-Sidelist-Scroller > div > div > img {
    height:28px !important; 
    width: 28px !important;
}

**Comment by Thomas101** [comment]
Thanks! I'll try and schedule this in!

**Comment by nmat** [comment]
Tested on git commit on macOS and Windows 10: https://github.com/wavebox/waveboxapp/commit/520684e581a6d8ba23e0acbf4c1f50e45f619288

resize works good and icons change. However I noticed that:

1. The left side mini marking on active service gets cut so it looks a bit odd:

Tiny:
![image](https://user-images.githubusercontent.com/383031/42930755-295e4eee-8b3e-11e8-9d70-417391a6bb9b.png)

Regular:
![image](https://user-images.githubusercontent.com/383031/42930779-3c4d5806-8b3e-11e8-9aeb-77c7481ed84a.png)

2. Click 1 icon and drag in towards wavebox main window and let go. The icon will not move on the click and drag but once you let go it locks the icon and you move the mouse around it will move the icon without holding mouse clicked.

GIF video below shows diff on tiny and regular size and moving:
![2018-07-19_10-30-29](https://user-images.githubusercontent.com/383031/42931050-efd8e110-8b3e-11e8-8e12-a7e7de6bfca5.gif)

**Comment by nmat** [comment]
@Thomas101 

1. Alright, thats understandable. I guess that in my head it breaks the overall consistency of how to see the dot. (of course running out of space is a problem). It might just be me but I would still consider that left side of app should be static and not be able to get things behind it. But its just me. :)

2. Ah yes, of course I can recreate it by clicking on the edge of the icon like you said. But works a lot better now. thank you :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can change the sidebar size under settings. It has now has 3 settings...

* Regular (the current setting) 70px
* Compact 55px
* Tiny 40px

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
