### ISSUE TITLE
Slow sync

### ISSUE THREAD

**Issue by lestevam** [wavebox/waveboxapp#1064]
* Wavebox Version: 4.10.4
* Operating System & Version: Linux KDE NEON 5.16
* (Linux only) Install method: Debian installer
* Account type (if applicable): Gmail, Outlook, Trello....

**Expected & actual behavior**
For example, in Gmail after reading the messages the notification count is not updated, just click "resync". This always happens with Outlook and Trello, but at the moment I have no example.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![print1](https://user-images.githubusercontent.com/917757/61388092-bf02d600-a88d-11e9-96a0-cfe0dfd65317.png)
![print2](https://user-images.githubusercontent.com/917757/61388094-bf02d600-a88d-11e9-9e8e-ff33de666839.png)
![print3](https://user-images.githubusercontent.com/917757/61388095-bf9b6c80-a88d-11e9-85ac-3e746f5c0caf.png)

**Comment by Thomas101** [comment]
Hey thanks for reporting and for the screenshots - those are really helpful.

It looks like the observer that watches the count for changes was only taking into account the first part of the split count. So `0:4` and `0:2` would both read as `0`, whereas `1:2` would read as `1`.

I’ve pushed an update out to fix this. The app should automatically grab the latest config in the background - but if you want to force it, a quick restart normally makes it grab the latest config right away :)
