### ISSUE TITLE
Outlook 365 - problem with height of right add-on bar

### ISSUE THREAD

**Issue by NullpointerForever** [wavebox/waveboxapp#1066]
* Wavebox Version: 4.10.6beta
* Operating System & Version: Windows 10
* Account type (if applicable): Office 365

**Expected & actual behavior**
After opening right bar with add-on (OneNote, Template phrases), height with content is too small.

**Steps to reproduce**

1. Enable a new Outlook layout style.
2. Use send to OneNote.

**Is the bug persistent or intermittent?**
That didn't happened when I open Outlook in Chrome or when I use an old Outlook layout style.

**Screenshots**
![outlook](https://user-images.githubusercontent.com/16589346/61779636-570a3d80-ae01-11e9-88cc-f1298a0208eb.png)

**Comment by Thomas101** [comment]
Thanks for reporting. We've got a fix that we'll be pushing out for this shortly, in the meantime if you are affected then there's a quick workaround...

1. Right-Click on the account and go to Account Settings
2. Scroll down to the Outlook section and in there, under Advanced you will find a 'Custom CSS' button
![Screenshot 2019-07-23 at 09 11 30](https://user-images.githubusercontent.com/103586/61779923-7309e100-adf9-11e9-8248-f4ce80e7424a.png)

3. Click this and paste the following line...

`.ms-Panel-main>.ms-Panel-contentInner>.ms-Panel-scrollableContent[data-is-scrollable="true"] { height: 100%; }`

4. Hit save and it should make the box larger until the release heads out

**Comment by NullpointerForever** [comment]
Thanks, that works.

**Comment by Thomas101** [comment]
This has just been released in the latest version of Wavebox (v4.11.0) which should fix the issue without the css workaround. Thanks!
