### ISSUE TITLE
Slack Introducing a snappier! #question

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#1067]
Today I read a new article from slack team 

<img src="https://user-images.githubusercontent.com/9933516/61810745-331a1c80-ae40-11e9-8b52-00e649010916.png" width="130">

https://slackhq.com/introducing-a-more-efficient-slack-desktop-experience

Is it take some effect for WaveBox integration?

**Comment by Thomas101** [comment]
Hi Alex. Wavebox loads in the most recent slack web client that's configured for your account, this means that you will see the benefits of the new Slack update when it is enabled by them for your Slack account :)

**Comment by reatlat** [comment]
@Thomas101 Great, TY
