### ISSUE TITLE
GMail Notifications Not Coming Through

### ISSUE THREAD

**Issue by moorecp** [wavebox/waveboxapp#1068]
* Wavebox Version: 4.10.5 and 4.10.6 Beta
* Operating System & Version: Mac OSX 10.14.5
* Account type (if applicable): Gmail

**Expected & actual behavior**
When new emails arrive, a notification should be generated and activity/unread counts should appear in the sidebar. This is not occurring for any of my GMail accounts. I read [this KB article](https://wavebox.io/kb/gmail-inbox-type) and have ensured my Inbox Type in Wavebox matches my actual Inbox type in GMail. The 2 accounts I'm trying this with use `Starred First` and `Priority Inbox`. Neither works. I have tried removing and re-adding the accounts, going from stable to beta, and changing Inbox types.

I ran the JS snippet in the console from Issue #1018 when I had unread messages in my Inbox and the output from that showed the correct unread count. (I also ran it without the explicit `sq_ig_i_personal` label and got the correct count back)

```<?xml version="1.0" encoding="UTF-8"?><feed version="0.3" xmlns="http://purl.org/atom/ns#"><title>Gmail - Label &#39;^sq_ig_i_personal&#39; for myusername@gmail.com</title><tagline>New messages in your &#39;^sq_ig_i_personal&#39; label</tagline><fullcount>2</fullcount>```

Both of my accounts are set up to never sleep, so the Sync Interval is Immediate.

**Steps to reproduce**

1. Add a GMail account that utilizes `Starred First` Inbox type
1. Send yourself an email from another account

**Is the bug persistent or intermittent?**
This bug always happens for me.

**Screenshots**
![GMail Notifications](https://user-images.githubusercontent.com/293433/61887799-4f659a00-aed0-11e9-99b1-53d6da947a6d.png)

**Comment by Thomas101** [comment]
Hi, thanks for reporting. It's a bit lame, but probably the fastest thing to try is...
1. Restart the app
2. Re-add one of the affected accounts

...just to see if it's some stale config data or something.

If that doesn't work, we can look to see if there are any errors pushed out to the logs.

**Network errors**
You can turn on network logging for a specific Gmail account to see anything looks wrong there. To do this...
1. Right-click on the account in the sidebar and go to Account Settings
2. Scroll down to the Gmail section and click on the `Log Sync network requests` button
![Screenshot 2019-07-26 at 09 01 04](https://user-images.githubusercontent.com/103586/61936222-29013680-af84-11e9-940e-dfab84e98c3f.png)

3. This brings up the log file that will be written out to
4. Right-click on the account in Wavebox and pick Sync
5. You should see some log entries outputted to the file

... do you get any log entries coming up in there and are they ending with `200:OK` or something else?

**Sync errors**
You can also attach to the output of the app - this should log out any errors it encounters. To do this...
1. Quit Wavebox and open Terminal
2. Run `/Applications/Wavebox.app/Contents/MacOS/Wavebox`

... if there are any errors, I'd expect to see them pretty quickly after launch. More than likely there will be one about `Class NotificationCenterDelegate` pretty immediately, this is expected.

**Comment by moorecp** [comment]
Everything in the sync log was coming back with a 200. The only non `Class NotificationCenterDelegate` error in my terminal was
`2019-07-26 10:57:51.451 Wavebox Helper[11794:7136648] +[MTLIOAccelDevice registerAcceleratorService:]: Failed to find bundle for accelerator bundle named: AppleIntelHD5000GraphicsMTLDriver errno: 1`
so that doesn't seem related.

What did seem odd was the sync request to GMail being made. I sent myself an email from another account and saw the sync request immediately in the logs:
`GET https://mail.google.com/mail/feed/atom/%5Eiim OK true 200:OK`

I didn't receive a notification and clicked on my GMail account and opened the developer console and ran:
`window.fetch('https://mail.google.com/mail/feed/atom/%5Eiim', {
credentials:'include'}).then(r=>r.text()).then(r=>console.log(r))`

That came back with 0 new messages. If I changed the request URL to check different labels (no label, `^sq_ig_i_personal`, and `^i`), it came back with the expected new message counts. I'm not sure why this account is checking `^iim` since that is Priority Inbox, unless that's supposed to be how you check `Starred first` inboxes.

<img width="566" alt="Screen Shot 2019-07-26 at 11 06 38 AM" src="https://user-images.githubusercontent.com/293433/61961596-b26d3480-af95-11e9-9745-d0dca626673c.png">

I have a second GMail account in my Wavebox that *is* `Priority Inbox` and also isn't receiving notifications, so I'll do some digging into that one, as well.

**Comment by moorecp** [comment]
For my `Priority Inbox` account, its issue seems to be that only messages that land in the `Important` bucket get noticed. If a message lands in `Everything Else`, it doesn't get noticed. Wavebox is performing the same sync request (`^iim`).

Armed with that knowledge, I flagged one of my `Important` messages in my `Starred first` account as Unread and immediately got a `1` badge on my sidebar icon.

I just changed my Inbox type on my `Starred first` account to `Default` and sent myself another email. I got a notification this time. It looks like the problem is `Starred first` is checking the `^iim` label which means if an email isn't flagged important, it won't pick it up. For my `Starred first` inbox, the `^sg_ig_i_personal` label seems good enough.

The `Priority Inbox` inbox type in Wavebox is having the same problem. It will only pick up emails that are flagged Important. I have changed them both to `Default` inbox type in Wavebox and will see if they work consistently, now.

**Comment by moorecp** [comment]
Of course, having now changed the Wavebox inbox type to `Default`, it means that if an email would fall into one of those categories (`Social`, for instance), I don't get the notification, since `^sq_ig_i_personal` doesn't catch that. I feel like I just need a choice in Wavebox that checks `^i`.

**Comment by Thomas101** [comment]
@moorecp you're right on the starred one. It should be using just the `unread inbox` under the hood (`^i`). I've changed this on the wire config, so whichever version of the app you're running will automatically update soon, it's also been pushed out in 4.10.7 beta if you want to grab it right away.

As for the priority inbox, I've not been able to reproduce that, would you be able to send a screenshot of your Gmail Inbox settings? E.g. 

![Screenshot 2019-07-29 at 12 09 12](https://user-images.githubusercontent.com/103586/62043960-b7322280-b1f9-11e9-8fcf-1b3d986b2d65.png)

**Comment by moorecp** [comment]
I think the issue with `Priority Inbox` is I have mine in GMail configured to show an Inbox unread count to `Unread items in the inbox`. Otherwise, GMail itself only shows an Unread count matching that of `Important and unread`. Based on my usage, I think if I just set that account up in Wavebox to use the newly modified `Starred first` that uses `^i`, I should be good.

<img width="1003" alt="Screen Shot 2019-07-29 at 8 32 57 AM" src="https://user-images.githubusercontent.com/293433/62048766-abcffe80-b1db-11e9-89ba-a6bc42df5f07.png">

Thanks for looking into this @Thomas101 .

**Comment by Thomas101** [comment]
@moorecp yeah, starred first or unread first should do the same thing. I've updated the special cases in our [KB article](https://wavebox.io/kb/gmail-inbox-type) to take this one into account, so it should help anyone else with the same config :).

Am I okay to close?

**Comment by moorecp** [comment]
@Thomas101 Yup, I'm good to close. Thanks for the quick fix and the KB update.
