### ISSUE TITLE
Gmail account images became VERY blurry after last updates

### ISSUE THREAD

**Issue by ToLive** [wavebox/waveboxapp#1069]
* Wavebox Version: 4.10.6b
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail

**Expected & actual behavior**
As I remember, the account pictures was added automatically but after recent updates they became very blurry. Repaired by manual adding pictures.

**Screenshots**
![Ticket20190729_0921_2792](https://user-images.githubusercontent.com/2019736/62018341-809ddd00-b1e4-11e9-8543-c9d46f27751c.png)

**Comment by Thomas101** [comment]
I've pushed a fix out for this. It's available in 4.10.7 beta. Thanks!

**Comment by ToLive** [comment]
Wow, fast! Thank you!
