### ISSUE TITLE
Ubuntu 17.04: tray icon missing

### ISSUE THREAD

**Issue by johanvanhelden** [wavebox/waveboxapp#107]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.04

I freshly installed Ubuntu 17.04 today, and Wavebox was one of the first programs I installed. I used WMail before on 16.04 - and that worked fine. But now, on Ubuntu 17.04, Wavebox is not giving me a tray icon. The setting is enabled tho:

![wavebox](https://cloud.githubusercontent.com/assets/19389981/25293603/eaa3da4c-26db-11e7-9d7e-3de593cda43c.png)

**Comment by Thomas101** [comment]
Hi this is a known issue that we're working on at the moment. Unity has changed a few things in Ubuntu 17 which is why this is failing. Issue #76 is already open for this, you can continue tracking progress & info from there. Thanks
