### ISSUE TITLE
Mixmax broken again.

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#1072]
I'm having this problem again. https://github.com/wavebox/waveboxapp/issues/1048

**Comment by Thomas101** [comment]
Thanks for reporting. Try removing the extension and adding it again. Once it's installed check the version is "4.2.0-1.0.5" and this should be better.

Just as a side note, we are working on shipping a more stable version of our extension framework in a couple of months which should see a big reduction in these type of issues :)

**Comment by GollyJer** [comment]
OK, re-enabled. We'll see how it goes. 

I've missed a few important emails to track so had to go back to the browser for email accounts. 😢

**Comment by zpyoung** [comment]
I have the same issue, but my MixMax requires re-authenticating with Google many times a day sometimes just a few minutes apart (before Gmail can even sleep). I've had this issue on-and-off with both Windows and Linux devices and on multiple Gmail accounts.

- **OS:** Ubuntu 19.04
- **Wavebox:** 4.11.3
- **MixMax Extension:** 4.2.0-1.0.5

I look forward to the extension framework update!

**Comment by GollyJer** [comment]
Yeah. I gave up on it. I had to go back to using gmail in the browser.
