### ISSUE TITLE
Notification history in KDE 5.16.x seems broken

### ISSUE THREAD

**Issue by felipelutz** [wavebox/waveboxapp#1073]
* Wavebox Version: 4.10.5 and 4.10.7beta
* Operating System & Version: Fedora 30 (with KDE 5.16.3 and KDE 5.16.4 packages)
* (Linux only) Install method: DNF Repository for stable version / RPM provided in github for beta version

**Expected & actual behavior**
As expected, the messages are displayed for the user, but they're not persisted in the notifications center's history list (the plasmoid that you can add in the task bar, next to the clock and etc)
Also, the notification counter stays unchanged.
The notification provided used is "Default".

**Steps to reproduce**
Using KDE 5.16.3/KDE 5.16.4, receive a message from an account.
You can use the Wavebox built-in notification test too.

**Is the bug persistent or intermittent?**
Persistent.

**Additional information**
There is people talking at reddit about changes in the notifications system in KDE 5.16.x.
Someone, I'm assuming he is a KDE developer, said that we should file a bug report in the applications that are not working as expected.

Funny enough, the "notify-send" command has the same problem.
The system notifications do work correctly though (aka, "file deleted", "usb devices can be ejected safely" and so on).

You can read the discussion here: https://www.reddit.com/r/kde/comments/c7w6u5/no_plasma_notifications_history_after_update_to/

**Comment by Thomas101** [comment]
Thanks for reporting & the link to the discussion. Wavebox uses `libnotify` in the background, which I think is the same as what `notify-send` uses.

There is quite a lot of work underway our end in overhauling the notification framework, which I suspect will fix this, but I'll add it to the list to specifically check. Hopefully we can get them back in there

**Comment by felipelutz** [comment]
Maybe this can shed some light on the problem:

https://bugs.kde.org/show_bug.cgi?id=408866

https://bugs.kde.org/show_bug.cgi?id=407716

**Comment by darthmooguy** [comment]
I have the same problem using KDE 5.12.x !

**Comment by felipelutz** [comment]
@darthmooguy in your case I think it's a problem within KDE itself..
Have you tried the plasmoid "Full Notifications KD5 Applet"? I believe it'll solve your problems, or at least some of them.
I have been using it with KDE 5.15.5 and I can say that with this plasmoid, Wavebox and others applications correctly display the notification counter and history.

You can find the plasmoid here: https://store.kde.org/p/1227099/
You can also download it using KDE's Software Centre by searching using the terms: "full notifications".

Good luck!

**ATTENTION: THIS PLASMOID WILL NOT WORK WITH KDE 5.16.x.**

**Comment by darthmooguy** [comment]
@felipelutz I think I misunderstood your bug! My problem is with the Wavebox tray icon that never changes even if I have unread emails. But thanks for the plasmoid, it will help keep track of new messages!

**Comment by felipelutz** [comment]
With a new version (31) of Fedora being released next month, I have decided to come back to this issue and try again.

I have updated my system with some packages from Fedora's test repository, that will soon be released as production ready packages.

After doing this, the notifications are working again, and without surprises, also `libnotify`/`notify-send`.

Maybe we can close this issue? I don't know if anybody else is currently having the same problem as me, so... it's your call @Thomas101 to close it or not.

Additional info:
![image](https://user-images.githubusercontent.com/6907493/65715343-4d0bf180-e073-11e9-9b69-79c26ed2d007.png)

Operating System: Fedora 30
KDE Plasma Version: 5.16.90
KDE Frameworks Version: 5.62.0
Qt Version: 5.12.4

**Comment by Thomas101** [comment]
@felipelutz if you're happy that it's fixed it, I'll close it off

@darthmooguy have you tried looking at https://wavebox.io/kb/gmail-inbox-type ? If that doesn't help open up a new issue and I'll see if we can get to the bottom of it

**Comment by darthmooguy** [comment]
Hi @Thomas101 ,

My inbox is the default inbox, and I have the same setting in Wavebox. I don't know if it's a KDE bug or a wavebox anymore :stuck_out_tongue: 

I just don't get desktop notifications for new emails and the tray icon never shows the number of unread emails. I'll open a new issue!
