### ISSUE TITLE
PDFs not opening in Office365 email

### ISSUE THREAD

**Issue by rdwilliams3** [wavebox/waveboxapp#1075]
* Wavebox Version: 4.11.0
* Operating System & Version: Mac OSX 10.3.6
* Account type (if applicable): Office 365

**Expected & actual behavior**
When opening a pdf attachment within Office365 window, preview of the pdf opens.

**Steps to reproduce**
Open any email with a pdf attachment

**Is the bug persistent or intermittent?**
Always happens

**Screenshots**
![image](https://user-images.githubusercontent.com/53830723/62556275-8168eb80-b842-11e9-9618-63ffad1da757.png)

**Additional information**
This was an old problem (2017 I think) that was fixed.  Seems to have resurfaced in the updated version.

**Comment by Mooz80** [comment]
Same problem here!

**Comment by Thomas101** [comment]
Thanks for reporting! A fix has just gone out in 4.11.1
