### ISSUE TITLE
”Multiple accounts” not working properly

### ISSUE THREAD

**Issue by andrushka80** [wavebox/waveboxapp#1076]
* Wavebox Version: 4.11.0
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail

I have two GMail accounts. repeatedly, the second one gets disconnected. More recently, it cannot even reconnect - gets stuck without prompting me the password for the account. See attached screenshots. Going through the browser works just fine.
![Printscreen2](https://user-images.githubusercontent.com/15683004/62695943-10f7d100-b9e0-11e9-8e7c-a7a113ffa78c.JPG)
![Printscreen1](https://user-images.githubusercontent.com/15683004/62695945-10f7d100-b9e0-11e9-9a13-d91fb42c13dd.JPG)

**Comment by Thomas101** [comment]
Rather than re-authenticating the account, does trying to add it afresh using the add button let you go through the process?

**Comment by andrushka80** [comment]
No, it does not work. After pressing the add button, configuring the
services (step 1), it goes on forever, never takes me to the next step
(step 2).

Here is a snapshot.

**Comment by Thomas101** [comment]
Thanks. That would normally point to one of three problems. Would you be able to give the following a try...

1. **GPU/driver problem**: Try going to Settings > Advanced and disabling `Hardware Acceleration` then try adding the account again to see if this work
2. **Sandboxing:** Go to Settings > Advanced and disable `Process Sandboxing` and try again
3. **Network problem**: Are you behind a firewall or VPN of any kind? Are you connected using a home network or corporate network?

**Comment by andrushka80** [comment]
Keep in mind that my primary GMail account works just fine. Also, this
second GMail account had been working for months/years before experiencing
this issue.

1. Disabled acceleration. Still does not work.
2. Disabled sandboxing. Still does not work.
3. There should not be a network issue, since this works just fine with the
primary account. Yes, this is a corporate network, behind a firewall. But
even when I am home, on the same laptop, not using a VPN, I am still facing
the same issue.

Andrei

**Comment by Thomas101** [comment]
Thanks. I'm struggling to reproduce this here. When the window appears does it just appear blank (i.e. nothing ever renders in it) or are you prompted to pick your account first, then it fails before getting to the password screen?

During the signin process, the app calls out to few domains, so it's worth checking these haven't been blocked by your firewall `wavebox.io`, `waveboxio.com` and `wavebox.pro`.

Can you also check which version of Windows 10 you're running. You can find this out by typing `winver` into cortana. You should come up to a screen such as [this one](https://en.wikipedia.org/wiki/Ver_(command)#/media/File:Winver_output.png) and see something along the lines of `Version 1703`

**Comment by andrushka80** [comment]
Window is blank, nothing ever renders.

So... funny thing. I access wavebox.io and it says that page cannot be
reached. Do you think this may be a firewall issue?

**Comment by Thomas101** [comment]
That would be why it's failing. The first step on the login is to wavebox.io then off to accounts.google.com.

When you tried wavebox.io in your browser, was there any additional info about why it couldn't load.

**Comment by andrushka80** [comment]
So just right now, I tried to access the wavebox.io page and it worked
fine. I re-added the second e-mail account and it worked for now.

So probably the issue can be closed though I don't have a good sense of
what the root cause was yesterday.

Andrei
