### ISSUE TITLE
Unread counter does not update accurate

### ISSUE THREAD

**Issue by DFelten** [wavebox/waveboxapp#108]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

The unread counter needs a lot time to update. Sometimes it does not update at all. Especially if the application is minimized, the counter does not update. 

In the moment for example there is still a 4 even when there are no unread messages:
![image](https://cloud.githubusercontent.com/assets/1169185/25303590/d27b8c5a-2756-11e7-90e8-692a9c1695fe.png)

The number disappears only when I change the mode in accounts. Only then there is sometimes an update.

**Comment by JReinhold** [comment]
Same problem on mac aswell

**Comment by Thomas101** [comment]
@DFelten I wonder if this is related to #82. I'll take a look. When your count gets stuck, if you right click on the account and then go to `Resync` does this update?

@JReinhold would you be able to try the steps in this [KB Article about Google Unread Counts](https://github.com/wavebox/waveboxapp/wiki/KB:-Google-Unread-Counts) to make sure your account is setup correctly.

**Comment by JReinhold** [comment]
> would you be able to try the steps in this KB Article about Google Unread Counts to make sure your account is setup correctly.

I've now set the Unread Mode to "Unread Unbundled Messages", and it seems to report 0 unreads now, which is correct. However, I didn't have any unreads at all before, even those in bundles were read. So in "Unread Messages" mode it should still have shown 0, but it showed 2. I will report if it's still an issue.

**Comment by DFelten** [comment]
@Thomas101 Could be possible. But it needs also sometimes a lot of time to set the counter to the correct value. 

I've checked it with the latest mail, I need to keep the program open for about 20 seconds to keep the value updated. This is only possible if the program is open and not minimized.

**Comment by Thomas101** [comment]
@DFelten This sounds like it could be related to #82 then, there should be a fix coming in the next release

**Comment by DFelten** [comment]
Thanks, then I will wait for this update. As soon as it works correctly, I will order the premium version.

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which should fix this. Can you give it a try and see if you still have the problem? You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by DFelten** [comment]
It seems to update also when it's minimized, but it still takes a relatively long time.

**Comment by Thomas101** [comment]
Have you noticed if it's any different to when open? There is sometimes a delay receiving the info about notifications from Google depending on how much latency their API is showing. It shouldn't be any more than a few seconds though

**Comment by DFelten** [comment]
It takes very long if I delete a mail only and not directly mark as read (30 seconds?). On the web it switches directly to no unread messages.

**Comment by Thomas101** [comment]
@DFelten there's been some really bad latency from google this week. Going to look into grabbing updates from the browser window as well as when Google tells us. Hopefully when you're actioning emails the count should update much fast.

Also related #170

**Comment by amig** [comment]
My issue is the unread count tag in taskbar as well as in the app sidebar do not refresh. Ubuntu 16.04. Wevebox 3.1.7.

**Comment by Thomas101** [comment]
Hi, we've added a fix into 3.1.8 that listens to the Gmail & Inbox UI for changes in the unread count and tries to re-sync based on this as well as what Google tells us. This should improve the responsiveness of unread counts in the majority of cases. Let us know if you have any more trouble

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
