### ISSUE TITLE
Bug: Paste without formatting (Option+Shift+Command+V) doesn't work

### ISSUE THREAD

**Issue by muesliq** [wavebox/waveboxapp#1082]
* Wavebox Version: 4.11.2
* Operating System & Version: MacOS 10.14.6
* Account type (if applicable): Gmail

**Expected & actual behavior**
Paste without formatting (Option+Shift+Command+V) should work. Nothing is pasted. The shortcut else works systemwide (with the notable exception of Word).

**Is the bug persistent or intermittent?**
persistent

**Comment by Thomas101** [comment]
<kbd>Shift</kbd>+<kbd>Command</kbd>+<kbd>V</kbd> is the default mapped in Wavebox, (we stuck with the default Chromium mapping for this one).

If you want to change it, head into Settings > Keyboard Shortcuts > Edit and change `Paste and Match Style` to be `Cmd+Option+Shift+V`

**Comment by muesliq** [comment]
Thanks a lot! That solved it for me.

You may want to consider a new default mapping for all users though. The Chromium default isn't intuitive for Mac users.
