### ISSUE TITLE
Duplicate icons in tray

### ISSUE THREAD

**Issue by nipnull** [wavebox/waveboxapp#109]
Version: 3.1.5

OS: Win 7 x64, Debian Stretch

Tray icons are duplicating after some time of using OS without restarting. After exit from Wavebox and start it again, all is good and there's is only icon. But it repeats again and again.

Detalazied situation on Windows from screenshot: icon with 1 unread message has popup menu, but i can't exit from wavebox or open it (and do anything else) from menu of this icon, looks like bug. And popup menu from icon with 3 unread message is working good. When i choose "exit" from popup menu form icon with 3 unread messages, both icons disappeared.

And i have 3 different icons in Control Panel menu in "Notification Area Icons": one with 4 messages, one with 3 and one more with one unread message. Maybe it's caused by updating Wavebox (and windows thinks that they are different programs), i don't know. It looks like #89 issue.

I attach screenshot from Windows 7.
![wavebox_icons](https://cloud.githubusercontent.com/assets/6099864/25304293/3a7571de-276d-11e7-8cb3-2c176e52b020.PNG)

**Comment by nipnull** [comment]
Debian situaton: it appears when i update the page with google inbox (by pressing ctrl+r)
![wavebox_icons](https://cloud.githubusercontent.com/assets/6099864/25305215/e70ebf42-277f-11e7-882c-b3644ad94a24.png)

**Comment by Thomas101** [comment]
If you use ctrl+r you can end up with more than one icon if it's not able to tear-down cleanly. Do you only see the duplicates when using ctrl+r?

**Comment by MichaelTunnell** [comment]
I disabled the icon and enabled it a couple of times once I noticed this happening . . . by doing the disable and enable actions repeated I got it up to 5 entries before I restarted the app to stop it. After restarting it was fine.

**Comment by Thomas101** [comment]
@MichaelTunnell thanks for the info. I'll double check to see why it's not being destroyed correctly

**Comment by Thomas101** [comment]
@MichaelTunnell which os are you using? Just tried on ubuntu 16.04 and not seeing the same behaviour

**Comment by MichaelTunnell** [comment]
> @MichaelTunnell which os are you using? Just tried on ubuntu 16.04 and not seeing the same behaviour

KDE Neon which uses KDE Plasma 5.9 on top of Ubuntu 16.04. Unity might not have this issue because of how it handles the system tray differently.

When you disable the Icon in Plasma, it doesn't remove the icon, it hides it into the system tray overflow feature so by doing this over and over the overflow contained a many. This is likely more due to Plasma than Wavebox itself.

**Comment by nipnull** [comment]
@Thomas101, as i see, more than one icon appears only if i update mail with ctrl+r.

About OS: Win 7 x64, Debian Stretch with i3wm (and i3bar as bar).

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
