### ISSUE TITLE
Lost Notifications in Mac OS Catalina

### ISSUE THREAD

**Issue by themiguelamador** [wavebox/waveboxapp#1090]
* Wavebox Version: 4.11.2
* Operating System & Version: Mac OS Catalina 10.15 Beta (19A536g)
* Account type (if applicable): All

**Expected & actual behavior**
Notifications appear. No notifications are shown on Mac or on the badge after upgrade to Catalina

**Steps to reproduce**
Go to settings at test Notifications - Nothing happen
Receive a notification in any app - Nothing happens

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
No relevant screenshots.

**Additional information**

**Comment by Thomas101** [comment]
Thanks, I see the same here. It's down to how macOS has changed notification handling slightly.

If you head into `Settings` > `Notifications` and change the `Notification Provider` to `Default` then press test, macOS should present a permission request notification which you can press allow on.

<img width="391" alt="Screenshot 2019-08-28 at 09 30 34" src="https://user-images.githubusercontent.com/103586/63839138-98e55100-c976-11e9-857a-2443fe65d686.png">

If that doesn't happen, there a couple of additional things to try...
1. After changing the provider, restart the app and try the `Test` button again
2. Open `System Preferences` > `Notifications`. Check that Wavebox is listed and the permission is turned to on...
<img width="780" alt="Screenshot 2019-08-28 at 09 48 27" src="https://user-images.githubusercontent.com/103586/63840529-20cc5a80-c979-11e9-92cb-211cddd5e8cc.png">

**Comment by Thomas101** [comment]
Fix: https://github.com/wavebox/waveboxapp/commit/a5d1e022c5fcf2b7ee6ed9245015942a1239d505

**Comment by themiguelamador** [comment]
Solved!

*Miguel Amador*
