### ISSUE TITLE
Slack couldn't load page is daily occurence now

### ISSUE THREAD

**Issue by zbhoy** [wavebox/waveboxapp#1092]
* Wavebox Version: [4.11.2]
* Operating System & Version: [Win10]
* Account type (if applicable): [Slack]

**Expected & actual behavior**
Slack loads to my workspace

**Steps to reproduce**
Open slack

**Is the bug persistent or intermittent?**
Happens here and there but becoming more frequent

**Screenshots**

![image](https://user-images.githubusercontent.com/1595366/63611519-a3cc6a00-c5a1-11e9-960d-b40f517dcfc4.png)

**Comment by Thomas101** [comment]
Slack was having some intermittent service issues [yesterday](https://status.slack.com/2019-08-23). Those should be resolved now. Are you still seeing the issue?

If that doesn't work, are you able to add a second slack account to wavebox, and does this work?

**Comment by Thomas101** [comment]
Thanks, if it's still happening, it would be good to have a little more info...

* Is this something that's always happened, or is it a new issue you've just started seeing?
* Do you have any extensions installed in Wavebox?
* How many Slack accounts do you have added to Wavebox?
* Is it the same one or two workspaces that show this, or can it be any of the ones you have added?
* How are you connected to the internet, e.g. home network, office network, VPN, Firewall etc...
