### ISSUE TITLE
clicking on Slack notifications doesn't open proper channel/person

### ISSUE THREAD

**Issue by cachrisman** [wavebox/waveboxapp#1094]
* Wavebox Version: 4.11.2
* Operating System & Version: macOS 10.15 Beta 6
* Account type (if applicable): Slack

**Expected & actual behavior**
I have notifications turned on for my company Slack account and I see a native macOS notification when someone sends me a message or on a channel according to my Slack settings, and when I click on the notification it shows the Wavebox window and shows my company Slack account, but it does not switch to the person or channel for which the notification was triggered.

I tested the behavior of the Slack web app in Chrome (v76.0.3809.100) and it does properly navigate to the person or channel for which the notification was triggered.

**Steps to reproduce**
I don't have any special settings or anything. To reproduce this behavior, do the following:
1. have a Slack account setup and be in any channel (maybe bring another application window on top of the Wavebox window as well...)
2. then have someone send you a direct message or `@here` or `@channel` in a channel you've joined.
3. see and click on the macOS notification from Wavebox

You'll see that Wavebox becomes active, but the channel doesn't change to the one from which the notification was triggered. You'll stay in the channel you were in for step 1.

**Is the bug persistent or intermittent?**
The happens for every Slack notification I get and is not intermittent.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I've just pushed a fix out for this in the latest version, 4.11.3.

**Comment by cachrisman** [comment]
@Thomas101 this was fixed with the release you mentioned, but I've since upgraded to Wavebox 10 and it still has this exact issue. Could the fix implemented in v4 be used in v10 as well? I also reported this via a support ticket a month ago but haven't heard any updates since then.

**Comment by anshulpratap** [comment]
Same issue occurs on Ubuntu 20.04 focal fossa....Since I upgraded my box the notifications received on slack are unclickable.
