### ISSUE TITLE
Workflowy integration has wrong URL, fails to load

### ISSUE THREAD

**Issue by scottbilas** [wavebox/waveboxapp#1096]
* Wavebox Version: 4.11.2
* Operating System & Version: Windows 10 (1903)
* Account type (if applicable): Workflowy

**Expected & actual behavior**
I expect that the Workflowy app integration loads Workflowy and remembers my login. What actually happens is when I visit the page, I get a "The page you're looking for doesn't exist" (https://workflowy.com/accounts/login/).

There is a link on their error page, "Go to the home page". I can do this and then log in, and then it's fine until sleep. Then it loses my login and I have to go through this again.

**Steps to reproduce**

1. Add the Workflowy app
2. Connect to it, get the error page (this is the first error - not a deal-breaker if it was one-time)
3. Click the link to go to the home page
4. Log in there
5. Sleep the app
6. Wake it up
7. Go to step 2 above (this is the deal-breaker)

**Is the bug persistent or intermittent?**

Repros 100%

**Screenshots**

![image](https://user-images.githubusercontent.com/964720/64081862-1d352c80-cd07-11e9-82d6-b47db29d9893.png)

**Comment by Thomas101** [comment]
Thanks for reporting, I've just pushed a fix for this. The app will update automatically, or if you want to make sure you've got the latest config just re-add Workflowy :)

**Comment by scottbilas** [comment]
Confirmed, thanks for fast fix @Thomas101 !
