### ISSUE TITLE
Notification badge

### ISSUE THREAD

**Issue by fdelahaie** [wavebox/waveboxapp#1097]
* Wavebox Version: [4.11.2]
* Operating System & Version: [ Windows 10]
*Install method: [installer]
* Account type : [Gmail, .]

**Expected & actual behavior**
Notification badge is expected when new email is in the email box

**Steps to reproduce**
Just add a new email

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![wavebox](https://user-images.githubusercontent.com/25150461/64150690-0d156e00-ce29-11e9-8eb5-c166a3c54a26.jpg)

**Additional information**
i've 3 mail box, for the 2 first i've the notification badge, for the last one it never appear.
The option is activated, i've try to delete and add again the account but nothing.

**Comment by nmat** [comment]
did you check this: https://wavebox.io/kb/gmail-inbox-type

There are some information on the knowledgebase that can help to check what happens in wavebox with the unread count. Maybe you can check that out and see if you get any further with the badge.

**Comment by fdelahaie** [comment]
thx it's work
