### ISSUE TITLE
Automatic zoom-in on one of my mailboxes

### ISSUE THREAD

**Issue by andrushka80** [wavebox/waveboxapp#1098]
* Wavebox Version: 4.11.2
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail

**Expected & actual behavior**
Until a few days ago, I had normal experience with my two GMail mailboxes. Then, all of a sudden (I don't recall changing any settings) one of my mailbozes had a huge 200% zoom-in. This prevents me from reading my e-mail since messages do not show up fully in the window. The other mailbox + plugins (e.g. calendar) have normal zoom-in.
![Capture](https://user-images.githubusercontent.com/15683004/64156855-368cc480-ce3e-11e9-819b-5eeca973ea2a.JPG)

**Is the bug persistent or intermittent?**
Persistent. No matter if I exit and enter again or if I reinstall or if I restart laptop.

**Screenshots**
Attached

**Comment by Thomas101** [comment]
It looks like you might have hit the zoom controls (<kbd>Ctrl</kbd>+<kbd>Plus</kbd>) at some point. If you hit <kbd>Ctrl</kbd>+<kbd>0</kbd> it should return to normal

**Comment by andrushka80** [comment]
Done. Resolved.
