### ISSUE TITLE
Feature Request: Add Google Voice?

### ISSUE THREAD

**Issue by amancevice** [wavebox/waveboxapp#11]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.2

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS 10.12.4

Adding Google Voice to the included services would be excellent!

**Comment by Thomas101** [comment]
We'll have a look to see what we can do. Hopefully the voice & video will work in the same way that it does on hangouts :)

**Comment by amancevice** [comment]
I don't think it can do video -- so that's one fewer thing to worry about. Even if it was just the messages features, that would be so good.

**Comment by Thomas101** [comment]
Hi, we're collapsing all the new Google Service requests into a single issue so we can keep track of them more closely. You can find and continue tracking progress from #131. Thanks!
