### ISSUE TITLE
Update key bindings

### ISSUE THREAD

**Issue by gravis** [wavebox/waveboxapp#110]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS 10.12.4

Hi,

I have an issue I didn't have with wmail): when I need to enter the € sign, I press alt-shift-2 on my us qwerty keyboard. Apparently this binding changes the pane of the current account, and thus I can't put euros anymore (or any sign with this kind of combination).

Thanks

**Comment by Thomas101** [comment]
Thanks, I'll look into this Also related #98 #92

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which removes some of the conflicting keyboards shortcuts and also has support for setting your own. If you do find any that conflict or that you want to change, open up the Settings and then go to Advanced. From there you can change or disable keyboard shortcuts

You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!
