### ISSUE TITLE
Email notifications to SMS

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#1104]
* Wavebox Version: [e.g. 3.0.0]
Current
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows 10

**Is your feature request related to a problem? Please describe.**
Some information about what the problem is.
This is not a technical problem but a use problem.

**Is your feature request related to an account type?**
For example, a Gmail account or Trello account.
GMail.

**Describe the solution you'd like**
Information about what you want to happen or like to see.

In addition to the email arrival notification message, I would like to have the ability to also send the same notification message as an SMS message to defined recipients.  This would be based upon a filter (the sender's email address) and potentially the text in the Subject line.

My specific Use case (although there are probably others)

Using the ability to forward an email feature of my provider (GMail) certain filtered emails are forwarded to other parties.  It would be nice to be able to notify them by SMS message that this has occurred.  The exact same notification message would be fine or optionally one that replaces the subject line with specific text would be even better. 

**Additional info**
Although I receive an SMS notification that this same email was sent to me, attempting to forward that same SMS messages using various SMS Forwarding applications (android based) has been unsuccessful.

Any other information or screenshots that might help us.

**Comment by nmat** [comment]
Sorry, but I do not see how wavebox would be the tool for this. In this case it would mean you need to see if there is a extension or some other third party software that is connected to gmail that would do this for you.

Wavebox in general just interprets the html5 notification that is being sent from the gmail notifications to show that as a notification on desktop. 

So wavebox does not create the notifications for you but just send them through to the desktop.

Do you know of other software/extensions that does this already?

**Comment by MichaelLeeHobbs** [comment]
I stumbled on to this while looking for something else and have not used "Wavebox" yet. You could just create a rule to send an EMAIL to defined recipients SMS email address. See "https://en.wikipedia.org/wiki/SMS_gateway#Email_clients" Example: 5550501234@txt.att.net I'm not sure if this is something Wavebox could do but there are many tools out there that could let you do this. That said you will need the cell number of your "defined recipients."

**Comment by CheechGe** [comment]
Hello:

thank you for the info, however, I investigated most of those and unfortunately, they don't allow you to apply rules to what gets to be forwarded, at least not the free ones.  the other problem is that they forward the entire message while I just want the subject of the email not all of the text. 

Given that WB already provides that information  in the Notification it would "only" require being able to support SMS and the appropriate filtering mechanism

**Comment by CheechGe** [comment]
Hello nmat,:
 
sorry I do not know of an extension that does this, hence the request.  I suppose if WB sees the notification it could be possible to do somehow this although as you mention it may not be the best place.

**Comment by Thomas101** [comment]
The Wavebox desktop client isn't always running so it wouldn't be suitable to use for reliably pushing messages out. We don't sync your emails out to a server so there wouldn't be any kind of hook there either.

Although you haven't had much success so far, it would probably be best provided by something such as an Android app or a dedicated online service. For something like this, you may need to look into paid services, carriers normally charge a per-message feed in fee (varying on region, network etc) so it's not a low cost service to run in the first place.

**Comment by CheechGe** [comment]
Hi Thomas

Understood.  I appreciate that you did look at the r34equest and give it
consideration

Regards,

Frank
