### ISSUE TITLE
Feature: IMAP and MS Exchange

### ISSUE THREAD

**Issue by hassec** [wavebox/waveboxapp#111]
Hi,   

interesting project 👍 
Are IMAP or even more Important MS Exchange sync planned for the near future?

**Comment by Thomas101** [comment]
We're looking at IMAP for a future release although there is quite some work involved in this!

**Comment by Thomas101** [comment]
Hi, we're collapsing all the new Account/Service requests into a single issue so we can keep track of them more closely. You can find and continue tracking progress from #130. Thanks
