### ISSUE TITLE
Clicking 

### ISSUE THREAD

**Issue by VarunAgw** [wavebox/waveboxapp#1111]
* Wavebox Version: [e.g. 3.0.0]
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]

**Expected & actual behavior**
Some information about what you expect to happen and what actually happens.

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**

**Comment by nmat** [comment]
This report looks empty. What is the problem exactly?

**Comment by VarunAgw** [comment]
@nmat Seems like a duplicate post accidentally 

https://github.com/wavebox/waveboxapp/issues/1112
