### ISSUE TITLE
Wavebox doesn't use native file picker on KDE Plasma

### ISSUE THREAD

**Issue by NoSync** [wavebox/waveboxapp#1114]
* Wavebox Version: 4.11.3
* Operating System & Version: Manjaro Linux, Plasma 5.16.4
* (Linux only) Install method: wavebox-bin from AUR

**Expected & actual behavior**
When file picker pops out native one is expected, while GTK3 picker is used

**Steps to reproduce**
Attach a file from any web app

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
This is most likely an upstream problem, but there's a simple downstream solution: https://www.npmjs.com/package/native-kde-file-open

**Comment by Thomas101** [comment]
Thanks we've got a fix coming for this soon!

**Comment by NoSync** [comment]
Fixed in Wavebox 11.
