### ISSUE TITLE
Selecting custom browser changes to "Deleted Provider" and acts as if "Ask" is selected

### ISSUE THREAD

**Issue by signe** [wavebox/waveboxapp#1115]
* Wavebox Version: 4.11.3
* Operating System & Version: macOS 10.15 Beta (19A578c)
* (Linux only) Install method: dmg
* Account type (if applicable): n/a

**Expected & actual behavior**
Selecting a custom browser ("link provider") in account settings automatically switches to an extra entry labeled "Deleted Provider"

Global settings:
![image](https://user-images.githubusercontent.com/249456/66157796-6368fe80-e5d9-11e9-8364-07abe88c8f9a.png)

Before selecting:
![image](https://user-images.githubusercontent.com/249456/66157813-69f77600-e5d9-11e9-95e5-a7d033ca2afe.png)

After clicking "Firefox":
![image](https://user-images.githubusercontent.com/249456/66157822-71b71a80-e5d9-11e9-94bd-4aeb0d7bf12c.png)

**Steps to reproduce**
Add a custom link provider to the global settings.  (I used Firefox)
Open account settings, click the radio button for "Firefox"
Selection changes to "Deleted Provider" automatically.  There is no way to select Firefox.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
See above

**Comment by Thomas101** [comment]
Thanks for reporting. That looks like a bug there, I'll have a look at fixing it.

There's a bit of a workaround which will let you select firefox...
1. Under Account Settings, Select `Ask each time`
2. In that account click on a link that opens in a new window
3. In the `Where would you like to open this link?` dialog, make sure you change the `What do you want to do next time` dropdown to be `Remember this for every link in this account`.
4. Select `Firefox` from the list of actions

![Screenshot 2019-10-07 at 08 47 01](https://user-images.githubusercontent.com/103586/66293708-2a81a000-e8df-11e9-9510-985a30c0f124.png)

This will make the link correctly, but changing it through settings will probably put you back in the `deleted provider` state. I'll get a proper a fix out for this
