### ISSUE TITLE
Slack authentication hangs with (enterprise, usually) workspaces that use SSO

### ISSUE THREAD

**Issue by CharlesWiltgen** [wavebox/waveboxapp#1116]
* Wavebox Version: 4.11.3
* Operating System & Version: macOS 10.14.6 (happens on any version)
* Account type (if applicable): Slack

**Expected & actual behavior**
Wavebox seems to require Slack re-authentication quite often (more often than the official client). That part is fine, but the problem is that Wavebox hangs forever when doing so, requiring me to delete and re-add Slack to Wavebox. I've now had to do this 10+ times this year, which is disappointing as a paying customer.

**Steps to reproduce**
My guess is: Use with a Slack corporate workspace that uses the company's SSO. https://slack.com/help/articles/203772216-saml-single-sign-on

**Is the bug persistent or intermittent?**
Persistent—I see it every time I'm required to log in.

**Screenshots**
![image](https://user-images.githubusercontent.com/6807178/66413838-0b514400-e9ad-11e9-8a5b-44e2bc0c522c.png)

**Comment by CharlesWiltgen** [comment]
Using a third-party (SAML?) identity provider for SSO:

![image](https://user-images.githubusercontent.com/6807178/66414551-79e2d180-e9ae-11e9-959f-808a018b50e0.png)

![image](https://user-images.githubusercontent.com/6807178/66414604-9d0d8100-e9ae-11e9-9241-9cca06ea8c83.png)

**Comment by Thomas101** [comment]
Thanks for reporting. Would you be able to try this with the latest version (4.11.4)? It should detect this state and bring the sign-in window back up rather than just hiding away. Thanks

**Comment by CharlesWiltgen** [comment]
Wow, I appreciate the incredible responsiveness! I forced the "Reauthenticate" process, and it seemed to work fine. (Visually there's a lot of extraneous window stuff happening that I can't recall seeing with Slack's client, but I'm very happy that it works.)
