### ISSUE TITLE
Unable to open on macOS Catalina10.15

### ISSUE THREAD

**Issue by ajt44** [wavebox/waveboxapp#1118]
* Wavebox Version: 4.11.3
* Operating System & Version: MacOS Catalina10.15

**Expected & actual behavior**
Should open

**Steps to reproduce**
Install on Catalina and attempt to open
**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?

**Screenshots**
<img width="428" alt="Screen Shot 2019-10-10 at 9 47 59 AM" src="https://user-images.githubusercontent.com/56368691/66519350-a1b76e00-eb43-11e9-8b71-f3de52edf6c7.png">

**Additional information**

**Comment by Thomas101** [comment]
Hi, thanks for reporting. This should be fixed in the latest version 4.11.4. If you try re-downloading and installing it should work
