### ISSUE TITLE
Autofill Password Requires Snap Permission

### ISSUE THREAD

**Issue by maroc81** [wavebox/waveboxapp#1119]
* Wavebox Version: 4.11.3
* Operating System & Version: Ubuntu 18.04
* Install method: Snap Package

I have not been able to get autofill password support to work until I discovered today that it requires the snap permission "password-manager-service".  I've searched the knowledge base and github issues a few times but never turned up anything.

Please consider adding info to https://wavebox.io/kb_embedded/autofill-passwords.  I've been using wavebox for a couple of years now so it's possible a new install will request this permission.

If anyone needs to setup the permission by hand use the command:
`snap connect wavebox:password-manager-service`

**Comment by maroc81** [comment]
Of course, immediately after creating this issue I discovered this:

https://wavebox.io/kb/connect-snap-plugs

**Comment by Thomas101** [comment]
Unfortunately, there are a few snaps plugs we can't connect automatically. We also don't explicitly get told that the plug is not connected, just that the library doesn't exist.

This means with the snap install there are a few things you have to do manually :(. Glad you got it working though!
