### ISSUE TITLE
Add services like buttons under Trello for the Starred Boards

### ISSUE THREAD

**Issue by MiguelTVMS** [wavebox/waveboxapp#112]
### Add buttons below the trello account just like google service.
Those buttons could be the "Starred Boards" or even manual boards that the user can select at the settings. For the button background you can use the board background the The icon can be the first letter of the Board name.

* Which version of Wavebox are you 
3.1.5
* Which Operating System are you using?
Windows 10

**Comment by Thomas101** [comment]
That's an interesting idea! We'll have a look at how this might work

**Comment by Thomas101** [comment]
Hi, this can now be achieved in two ways...
1. By adding multiple Trello tabs to a single account. You can do this by right-clicking on an existing account in the toolbar/sidebar and using the `Add another service` button.
2. By using the new recent & pinned items in the tooltips when you hover over an account. There's some [more info about these in the blog](https://blog.wavebox.io/pinned_recents_tasks/)

I'm going to close this off for now, but if you still feel like there's something missing or that needs improvement, feel free to re-comment or open another issue and we'll take another look.
Thanks!
