### ISSUE TITLE
Adding another Slack freezes at sign-in screen

### ISSUE THREAD

**Issue by corpetty** [wavebox/waveboxapp#1122]
* Wavebox Version: antergos/wavebox 4.9.3-2
* Operating System & Version: Antergos (Arch)
* (Linux only) Install method: `yay (pacman)`
* Account type (if applicable): Slack

**Expected & actual behavior**
Expected behavior: 
- Addition of slack server completes and is available for use

Actual behavior: 
- Sign-in prompt box appears and allows me to enter credentials.  After entering creds it goes back to waiting screen (attached image) and sits indefinitely  Minimization is available and works but the slack is never added. 

**Is the bug persistent or intermittent?**
This bug exists every time I attempt to add a specific slack group.  I have yet to try a different slack community as I don't participate in any more of them. 

**Screenshots**
![gscreenshot_2019-10-15-160015](https://user-images.githubusercontent.com/2460145/66865275-e8063600-ef64-11e9-94a1-8b803152a189.png)

**Additional information**

**Comment by Thomas101** [comment]
@corpetty a fix went out for this in the latest version (4.11.4). If you update and try to add again it should work

**Comment by corpetty** [comment]
Looks like arch repos aren't up to date on that one yet.

**Comment by Thomas101** [comment]
It's a community member that's been maintaining that package and it sounds like they've stopped updating it.

I'm not overly familiar with yay, would you be able to use the archlinux repo, that one's been kept up to date https://aur.archlinux.org/packages/wavebox-bin/. If not you could download the rpm from https://wavebox.io/download and install it manually

**Comment by corpetty** [comment]
I'll figure out how to get it done and report back afterwards... I'm on antergos arch anyway, which needs to be ported to vanilla arch since they've discontinued it.  Maybe I'll just wholesale go back to debian. 
/shrug

**Comment by corpetty** [comment]
Removed antergos packages, updated from AUR.  All is good
