### ISSUE TITLE
Linux+Gnome: no tray icon

### ISSUE THREAD

**Issue by RidgeA** [wavebox/waveboxapp#1123]
* Wavebox Version: 4.11.4
* Operating System & Version: Arch Linux
* (Linux only) Install method: Pacman
* DE - Gnome 3.34

There is no icon in tray

**Comment by corpetty** [comment]
I had to add some extensions to get tray icons back.  I'm currently using Arch Vanilla, gnome 3.34 and `aur/wavebox-bin 4.11.4-1` with a tray icon.

**Comment by RidgeA** [comment]
> I had to add some extensions to get tray icons back

Could you say which one?

**Comment by corpetty** [comment]
I'm currently using AwesomeWM so I'm not sure which ones did it, but these
are the ones I have installed in gnome.

mprisindicatorbutton@JasonLG1979.github.io
appindicatorsupport@rgcjonas.gmail.com
taskbar@ttux.net
TopIcons@phocean.net
