### ISSUE TITLE
Audio does not play

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#1124]
* Wavebox Version: 4.11.4
* Operating System & Version: openSUSE Tumbleweed 20191016 (rolling)
* (Linux only) Install method: yum repo
* Account type (if applicable): Gmail and Whatsapp web (at least)

**Expected & actual behavior**
When audio files are attached to emails, or audio messages arrive through Whatsapp web, I would expect to be able to play them. GMail (and Whatsapp web) act as if audio was playing, but no sound is heard.

**Steps to reproduce**
Just try to play an audio attachment from GMail

**Is the bug persistent or intermittent?**
Always

**Comment by Thomas101** [comment]
Thanks, is this something new that's started recently or something from previous versions?

If you add this url (https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_audio) as an Any weblink are you able to play the audio file from there?

**Comment by Cris70** [comment]
Hi @Thomas101 

> Thanks, is this something new that's started recently or something from previous versions?

It's been like this for a long time now.

> If you add this url (https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_audio) as an Any weblink are you able to play the audio file from there?

No, it's completely silent.

**Comment by Thomas101** [comment]
Thanks! It sounds like we could be missing one of the dependencies for playing audio. I'll set up a VM here and see if I can reproduce the same problem.

Do you have Chrome installed by any chance? This has pretty much the same dependencies and any missing ones normally fix themselves if Chrome is installed. If not, no worries, I'll see if I can reproduce here

**Comment by Cris70** [comment]
@Thomas101 I tried [this](https://github.com/wavebox/waveboxapp/issues/1124#issuecomment-546284242) on my work laptop and sound works (same OS as my home desktop PC).
Chromium is installed on the laptop. 
I'll verify if Chrome/Chromium is installed at home and I'll let you know.

**Comment by Cris70** [comment]
mmmh, I have Chromium installed at home too...

**Comment by Thomas101** [comment]
Thanks, that's really helpful. I wonder if it's down to different versions of ALSA on the two machines. Would you be able to check what the output from the following is...

`cat /proc/asound/version`
`aplay --version`

I also seem to remember someone having a similar issue on Suse, but I can't find the original Github issue. For them checking `System Settings` > `Audio & Video` > `Device Preference` seemed to help. I think maybe one of the audio output channels was set to the wrong device/Wavebox was sending audio out in the wrong category which was unmapped...

![Screen Shot 2019-10-30 at 09 41 47](https://user-images.githubusercontent.com/103586/67846902-d9d61f00-faf9-11e9-870c-bc3b5b965187.png)

Also in the same System Settings, if you've got multiple audio profiles, it's worth checking that the test buttons there produce sound from the speakers for each profile, just in case Wavebox is picking up a disabled profile for some reason...
![Screen Shot 2019-10-30 at 09 41 08](https://user-images.githubusercontent.com/103586/67846992-ff632880-faf9-11e9-9e6b-4e09ccd24541.png)
![Screen Shot 2019-10-30 at 09 40 48](https://user-images.githubusercontent.com/103586/67847061-215cab00-fafa-11e9-8471-1558a1588090.png)

**Comment by Cris70** [comment]
Hi @Thomas101 and sorry for the late reply.
I just wanted to let you know that it is working now.
I did not have time to investigate more, so now I don't know if it's due to something I inadvertently did or if it's just due to a new release.
Thank you anyway for your help!
