### ISSUE TITLE
Highlighted/selected text is not *actually* highlighted until changing focus to another window

### ISSUE THREAD

**Issue by wgordon17** [wavebox/waveboxapp#1129]
* Wavebox Version: 4.11.4
* Operating System & Version: macOS Catalina 10.15.1
* (Linux only) Install method: dmg
* Account type (if applicable): All

**Expected & actual behavior**
Anything that I highlight in the UI gives no user feedback (actually selecting the text), until after I switch focus to another window

**Steps to reproduce**
1) Select text in Wavebox
2) Click another window, like Chrome
3) Finally see my text highlighted

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
https://www.youtube.com/watch?v=MPxjnL__TIE

**Additional information**
I noticed this happening right after my upgrade to macOS Catalina

**Comment by Thomas101** [comment]
Thanks for reporting! It's down to an incompatibility with dark mode the graphite color scheme on macOS.

I've pushed a fix out to the beta channel of Wavebox in version 4.11.5 which should fix this. You can give it a try using the instructions [here](https://wavebox.io/kb/beta-channel)

**Comment by wgordon17** [comment]
Beta fixed it perfectly! Thanks so much for the quick response 🙏
