### ISSUE TITLE
No icon from slack notifications - (Wavebox X)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#1134]
* Wavebox Version: 10.0.25
* Operating System & Version: Windows 10
* Account type (if applicable): Slack

**Expected & actual behavior**
Get either slack or wavebox icon during notification from new message

**Steps to reproduce**
Just get a new message from a private chat. Message appears but icon is not there. Only empty space on the left side of the message.

**Is the bug persistent or intermittent?**
Persistent

**Comment by nmat** [comment]
Tested on a few more services:
MS Teams - Shows the images

**Comment by Thomas101** [comment]
Thanks, I'll take a look into this

**Comment by nmat** [comment]
Thank you.

I also noticed the same thing in the notifications of the dashboard. They are missing there also in notification tab.

**Comment by Thomas101** [comment]
Thanks, This should be in 10.0.27 :)
