### ISSUE TITLE
Icon for position wrong in settings of bars - (Wavebox X)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#1135]
* Wavebox Version: 10.0.25
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail, outlook

**Expected & actual behavior**
Icon should show right position in icon but shows the same position on both left and right (See screenshot below)

To the eye it looks confusing.

**Steps to reproduce**
Go to service and right click and go to Move All To =>

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/69805893-f7be9e80-11e1-11ea-8fa1-51c2f8e7e476.png)

**Comment by Thomas101** [comment]
Thanks. Fixed in the next version
