### ISSUE TITLE
+Apps in dashboard, takes wavebox out of maximize - (Wavebox X)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#1136]
* Wavebox Version: 10.0.25
* Operating System & Version: Windows 10
* Account type (if applicable): Wavebox Dashboard

**Expected & actual behavior**
Do not go out of maximized

Opens new apps frame but takes wavebox out of maximized

**Steps to reproduce**
Click +Apps in dashboard when wavebox is maximized.

**Is the bug persistent or intermittent?**
Persistent

**Comment by Thomas101** [comment]
Thanks. Fixed in the next version
