### ISSUE TITLE
Windows Notification - Activity Area - Always opens a new wavebox window on click or does nothing - (Wavebox X)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#1138]
* Wavebox Version: 10.0.25
* Operating System & Version: Windows 10
* Account type (if applicable): All

**Expected & actual behavior**
On notification click in Win+A menu, should open service for that specific notification and the message.

Instead either it opens a completely new window or if another window for example chrome is in front of wavebox nothing happens. It does not even focus the app.

**Steps to reproduce**
Get notification and let it go to list of notification in windows sidebar for notifications.
Click on that notification.

It seems random how it behaves.

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
Odd that it behaves different depending on the state of wavebox main window.

**Comment by Thomas101** [comment]
What type of account did this come from? e.g. Gmail, Slack, Teams etc?

**Comment by nmat** [comment]
I tested it with the notification for office365 and for slack both are on different apps in wavebox

**Comment by Thomas101** [comment]
I think I've got a fix for this in 10.0.27 :)

**Comment by nmat** [comment]
This works now but always opens in a new window instead of the main window is this intentional?

**Comment by nmat** [comment]
Ok some extra feedback here.

If wavebox window is open with lets say "MS Teams" and you click the notification in action center - new window is created

if in another service in wavebox - clicking on notification in action center - goes to the tab for the service where the notification comes from

It seems that it depends on the focus in wavebox.

**Comment by Thomas101** [comment]
So from what I've found, this was actually 3 separate bugs hence the kind of flakey behaviour. 10.0.33 has a new notification framework which should address these :)

**Comment by nmat** [comment]
oh yes, sorry about that. I should have reported it in 3 different issues.

I will try to remember to do it properly in the future :)

**Comment by Thomas101** [comment]
> oh yes, sorry about that. I should have reported it in 3 different issues.
> 
> I will try to remember to do it properly in the future :)

It was only really when I looked into the actual behaviour and causes that I found it was three. Probably just the one would still be fine ;-)
