### ISSUE TITLE
Badge counter almost unreadable on Ubuntu 17.04

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#114]
* Which version of Wavebox are you using? [e.g. 3.1.5]

* Which Operating System are you using? [Ubuntu 17.04]

NVIDIA Driver Version: 381.09

The font in the badge counter is pretty hard to read in Ubuntu, it's really thin and not even a bright white. 

![wavebox_badge_counter](https://cloud.githubusercontent.com/assets/26086997/25373657/303fbb7e-29a3-11e7-8be2-5e482a17010d.png)

On Mac the digits stand out much better. Can we have some way to tweak the font/contrast/color in the badge? Or is there already?

**Comment by Thomas101** [comment]
It could be that the font isn't installed by default on linux. I'll take a look. Thanks!

**Comment by MichaelTunnell** [comment]
I have the same problem on KDE Neon which is Ubuntu 16.04 based. I would actually prefer the background color to not be red. In fact, it would be fantastic if the color would match the icon tray color I chose.

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which fixes this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by MichaelTunnell** [comment]
This is certainly better and more easier to read.

Preview:
![unread-badge-text-fix](https://cloud.githubusercontent.com/assets/1056731/25717390/e8873344-30c7-11e7-9440-aa8b028456f2.png)
