### ISSUE TITLE
Cannot use multiple integrated slack with same profile

### ISSUE THREAD

**Issue by VarunAgw** [wavebox/waveboxapp#1142]
Wavebox Version: 10.0.25.2 stable
Operating System & Version: Windows 10 1909 x64

When I try to force multiple slacks to use same profile, both of them will start showing the same workspace instead of assigned one.

I solved it by created multiple apps using "Add any website" -> https://a.slack.com, https://b.slack.com

I think if integrated slack uses such urls, it will solve this problem.

**Comment by Thomas101** [comment]
Normally we'd recommend using different profiles for different apps of the same type. This will ensure that there's no cross-over between them and give each one its own set of cookies and identity.

The Wavebox profiles are a lot lighter than chrome profiles and allow you to mix-and-match different cookie stores in the same app [more info](https://kb.wavebox.io/wavebox-profiles-vs-chrome-profiles/)

If you're trying to add them both into the same group, there's a step-by-step guide for adding them [here](https://kb.wavebox.io/adding-multiple-apps-to-one-group/)
