### ISSUE TITLE
Corporate Slack session doesn't stay logged-in on the main Wavebox window

### ISSUE THREAD

**Issue by rfgamaral** [wavebox/waveboxapp#1154]
* Wavebox Version: 4.11.5beta
* Operating System & Version: Windows 10
* Account type (if applicable): Slack

**Expected & actual behavior**
When my corporate Slack expires I get this screen:
![image](https://user-images.githubusercontent.com/96476/70540964-11ef6980-1b5e-11ea-9a2c-174dd1f41c66.png)
After clicking "Sign In", I have to sign back into my workspace so I'm presented with this:
![image](https://user-images.githubusercontent.com/96476/70541016-2a5f8400-1b5e-11ea-8622-a45e025d59fe.png)
I enter my workspace name, click "Continue" and I enter my credentials to login (I have 2 choices here, OAuth with Microsoft Sign-in or user/password, the problem exist with both). After this, I'm properly logged into my corporate Slack workspace but **in a pop-up window** instead of the main Wavebox window. This pop-up window quickly closes itself and the following screen is displayed continuously until I click anywhere or the "Minimize" button:
![image](https://user-images.githubusercontent.com/96476/70541208-832f1c80-1b5e-11ea-9e2a-19d47f07df82.png)
And then I'm brought back to this screen:
![image](https://user-images.githubusercontent.com/96476/70540964-11ef6980-1b5e-11ea-9a2c-174dd1f41c66.png)

**Steps to reproduce**
I have no idea...

**Is the bug persistent or intermittent?**
This happens every time my corporate Slack session expires and sometimes, after logging in multiple times, eventually, one of those work correctly and the main Wavebox window displays my Slack window, a lot of the times, it doesn't.

**Comment by Thomas101** [comment]
Thanks - should be a fix heading out for this tomorrow :)

**Comment by rfgamaral** [comment]
> 
> 
> Thanks - should be a fix heading out for this tomorrow :)

Is that fix coming to the Slack service or to Wavebox itself?

**Comment by Thomas101** [comment]
It's been fixed in Wavebox 4.11.6 which is now available

**Comment by rfgamaral** [comment]
Currently using Wavebox v4.11.11 and I started having this issue again today...

**Comment by Thomas101** [comment]
Thanks for reporting. It looks like this is down to the third party cookie shakeup that's happening with Chrome.

We launched [Wavebox 10](https://github.com/wavebox/waveboxapp/issues/1133) at the end of last year, which is built directly on Chromium so doesn't have some of the same issues that the Wavebox 4 (based on Electron) has in its network architecture. 

I'd recommend giving it a try, there's so more info on how to switch [here](https://blog.wavebox.io/wavebox-10-migration-wizard-for-pro-users/) and some info about the underlying changes [here](https://blog.wavebox.io/wavebox-is-evolving-electron-chromium/).

You can [download the latest version here](https://wavebox.io/download)

**Comment by rfgamaral** [comment]
I'm sorry but I don't like Wavebox 10, it doesn't allow me to customize everything as the current Wavebox does. Until feature parity is completed, Wavebox 10 is not for me. I've mentiond this in the Wavebox 10 issue in the past.

Is there nothing that can be done with the current Wavebox version to solve this? It's only happening with Slack and the corporate version.
