### ISSUE TITLE
Slack memory leak

### ISSUE THREAD

**Issue by hiperlouro** [wavebox/waveboxapp#1160]
* Wavebox Version: 4.11.6
* Operating System & Version: Windows 10
* Account type (if applicable): Slack

**Expected & actual behavior**
After v4.11.6 I notice that there's a memory leak on the Slack app and also the CPU is always around 100%!

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?
Configure the slack application and open the Wavebox Task Monitor. Select advanced mode.

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?
Always

**Screenshots**
Screenshots often help us narrow down a bug more easily.
Screenshot **before** writing this issue:

![image](https://user-images.githubusercontent.com/3466596/70639656-b04cff00-1c32-11ea-8e13-2d4f5d28f701.png)

Screenshot **after** writing this issue:

![image](https://user-images.githubusercontent.com/3466596/70639910-0e79e200-1c33-11ea-8c88-405889ac6e67.png)

**Additional information**
N/A

**Comment by hiperlouro** [comment]
As a workaround, I removed the slack app and added it as a webpage and seems to keep the memory and CPU low.

![image](https://user-images.githubusercontent.com/3466596/70641659-da53f080-1c35-11ea-871a-a7a34e27f561.png)

**Comment by Thomas101** [comment]
Hey, thanks for reporting. I've just pushed a beta version out (4.11.8) which should be much much better. It would be great if you could give it a try! Downloads are available on the releases page https://github.com/wavebox/waveboxapp/releases/tag/v4.11.8

**Comment by hiperlouro** [comment]
I've installed the beta and things seem to be stable now.

![image](https://user-images.githubusercontent.com/3466596/70664330-1ef58100-1c62-11ea-9834-35f0b198eb50.png)
![image](https://user-images.githubusercontent.com/3466596/70664494-6714a380-1c62-11ea-9484-e9e157084a81.png)

Thanks for the quick fix!

**Comment by bkuri** [comment]
@Thomas101 I'm having an issue creating the `4.11.8` AUR package. Seems like `libnode.so` is not included in the tar file.

Output below:

```
$ makepkg -i                                
==> Making package: wavebox-bin-beta 4.11.8-1 (Wed 11 Dec 2019 06:35:00 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found wavebox.desktop
  -> Found Wavebox_4_11_8_linux_x86_64.tar.gz
==> Validating source files with sha512sums...
    wavebox.desktop ... Passed
==> Validating source_x86_64 files with sha512sums...
    Wavebox_4_11_8_linux_x86_64.tar.gz ... Passed
==> Extracting sources...
  -> Extracting Wavebox_4_11_8_linux_x86_64.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
chmod: cannot access '/home/bk/source/wavebox-build/pkg/wavebox-bin-beta/usr/share/wavebox/libnode.so': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```
Any idea where I can get a copy of that file? Thanks in advance!

**Comment by Thomas101** [comment]
@bkuri not sure it should be in there. Checked 4.11.8, 4.11.7, 4.11.6 and even an older one of 4.10.7 and there's no `libnode.so` :-/

**Comment by Thomas101** [comment]
Thanks @hiperlouro this has just gone out to stable in 4.11.9 :)

**Comment by bkuri** [comment]
@Thomas101 I can definitely spot that file on my current installation (`4.11.5beta`):
```
/usr/share/wavebox >>> ls
total 173004
drwxr-xr-x 2 root root      4096 Nov  8 17:49 vendor-licenses
drwxr-xr-x 2 root root      4096 Nov  8 17:49 swiftshader
drwxr-xr-x 2 root root      4096 Nov  8 17:49 resources
drwxr-xr-x 2 root root      4096 Nov  8 17:49 locales
-rw-r--r-- 1 root root      4214 Nov  8 17:49 blink_image_resources_200_percent.pak
-rw-r--r-- 1 root root    167930 Nov  8 17:49 chrome_100_percent.pak
-rw-r--r-- 1 root root    250097 Nov  8 17:49 chrome_200_percent.pak
-rw-r--r-- 1 root root        18 Nov  8 17:49 content_resources_200_percent.pak
-rw-r--r-- 1 root root   7474447 Nov  8 17:49 content_shell.pak
-rw-r--r-- 1 root root  10219152 Nov  8 17:49 icudtl.dat
-rwxr-xr-x 1 root root    255912 Nov  8 17:49 libEGL.so
-rwxr-xr-x 1 root root   3152384 Nov  8 17:49 libffmpeg.so
-rwxr-xr-x 1 root root   6058008 Nov  8 17:49 libGLESv2.so
-rw-r--r-- 1 root root  22202064 Nov  8 17:49 libnode.so
-rwxr-xr-x 1 root root    308888 Nov  8 17:49 libVkICD_mock_icd.so
-rw-r--r-- 1 root root     16725 Nov  8 17:49 LICENSE
-rw-r--r-- 1 root root    125011 Nov  8 17:49 natives_blob.bin
-rw-r--r-- 1 root root    164181 Nov  8 17:49 pdf_viewer_resources.pak
-rw-r--r-- 1 root root   8855505 Nov  8 17:49 resources.pak
-rw-r--r-- 1 root root    641676 Nov  8 17:49 snapshot_blob.bin
-rw-r--r-- 1 root root    112102 Nov  8 17:49 ui_resources_200_percent.pak
-rw-r--r-- 1 root root   1040440 Nov  8 17:49 v8_context_snapshot.bin
-rw-r--r-- 1 root root     56870 Nov  8 17:49 views_resources_200_percent.pak
-rwxr-xr-x 1 root root 115860520 Nov  8 17:49 Wavebox
-rw-r--r-- 1 root root       254 Nov  8 17:49 wavebox.desktop
-rw-r--r-- 1 root root      9035 Nov  8 17:49 wavebox_icon_128.png
-rw-r--r-- 1 root root     18889 Nov  8 17:49 wavebox_icon_256.png
-rw-r--r-- 1 root root      2095 Nov  8 17:49 wavebox_icon_32.png
-rw-r--r-- 1 root root      3290 Nov  8 17:49 wavebox_icon_48.png
-rw-r--r-- 1 root root     26555 Nov  8 17:49 wavebox_icon_512.png
-rw-r--r-- 1 root root      4455 Nov  8 17:49 wavebox_icon_64.png
-rw-r--r-- 1 root root      6766 Nov  8 17:49 wavebox_icon_96.png
-rw-r--r-- 1 root root     26555 Nov  8 17:49 wavebox_icon.png
-rw-r--r-- 1 root root        22 Nov  8 17:49 wavebox.sh
```
This is the first time I'm getting this error, BTW. Not sure what's going on…

**Comment by Thomas101** [comment]
@bkuri I've just checked back further and randomly picking 4.7.0 and taking a look that does include libnode.so. Looking through the electron issues, the last version that should have been there was electron 3 https://github.com/electron/electron/issues/15974

The version you've got in your install directory is probably just an overhang that was left during updates :)

Safe to assume it's no longer needed!

**Comment by bkuri** [comment]
@Thomas101 thanks! Seems that removing `libnode.so` from `PKGBUILD` did the trick, although I'm still not entirely sure about why it worked up until now. Ah well.  ¯\\\_(ツ)\_/¯
