### ISSUE TITLE
Skype crashing on receiving a message

### ISSUE THREAD

**Issue by VarunAgw** [wavebox/waveboxapp#1164]
* Wavebox Version: [e.g. 3.0.0] Wavebox 10 Stable
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10] Win 10 1909

I cannot confirm for sure if everyone is facing it, but I am. It started happening since yesterday.

Whenever I receive a message on Skype, it fails and refreshes with this error message "Oops, it looks like something went wrong. Click OK to automatically reload Skype for Web."

It doesn't happen in old wave box 4 or browser.

**Comment by Thomas101** [comment]
Thanks for reporting. We've just push a fix to the [beta channel](https://kb.wavebox.io/beta-channel/)(10.0.39) or if you're happy to wait until Monday, it should go out to stable then

**Comment by Thomas101** [comment]
This has now been released. Thanks!
