### ISSUE TITLE
Videos and animated gifs not playing

### ISSUE THREAD

**Issue by sorinsfirlogea** [wavebox/waveboxapp#1165]
* Wavebox Version: 10.0.35
* Operating System & Version: Ubuntu 18.04
* (Linux only) Install method: Debian installer
* Account type (if applicable): not applicable

**Expected & actual behavior**
Animated gifs and videos on Facebook are not playing. Gifs are replaced by a white area, videos are showing a blurred, still image and the loading icon that keeps spinning.

**Steps to reproduce**
Not sure.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
Not relevant

**Additional information**
I tried also with all extensions disabled. Chrome is working as supposed.

**Comment by Thomas101** [comment]
Hi, can you drop support@wavebox.io an email, also with the channel you're using (it should be right next to the version number) and we'll take a look

**Comment by sorinsfirlogea** [comment]
Never mind, I've upgraded to 10.0.40 this morning and it's fixed. Thanks.

**Comment by jsobell** [comment]
I'm experiencing the same issue:
Wavebox
Version 10.0.90.1 core
Dev console shows:

![image](https://user-images.githubusercontent.com/834155/75622871-0fe6f500-5bf9-11ea-91f3-dd407318cc18.png)
