### ISSUE TITLE
Wavebox Help opens "page not found" 

### ISSUE THREAD

**Issue by alanhoyle** [wavebox/waveboxapp#1166]
* Wavebox Version: 10.0.40.2 stable
* Operating System & Version: macOX 10.15.2
* Account type (if applicable): n/a

**Expected & actual behavior**
If I go to the menu and select "wavebox help" it tries to load https://wavebox.io/help/chrome/?p=help&ctx=menu

This gives "page not found" which is not particularly helpful

**Steps to reproduce**
Go to menu and select Help:: Wavebox help

**Is the bug persistent or intermittent?**
persistent

**Screenshots**

![Screen Shot 2019-12-17 at 11 37 07 AM](https://user-images.githubusercontent.com/289779/71015427-9479ab00-20c1-11ea-8ff5-ece0659ecccb.png)

**Additional information**

**Comment by Thomas101** [comment]
Thanks! We've put a fix out for those :)
