### ISSUE TITLE
Add "Check for Updates" to the menu

### ISSUE THREAD

**Issue by alanhoyle** [wavebox/waveboxapp#1168]
* Wavebox Version: 10.0.42
* Operating System & Version: macOS 10.15.2

**Describe the solution you'd like**

Many macOS applications have a "Check for Updates..." item in their application menu.  This would be nice to have as opposed to having to bring up the Settings view, click or scroll to Updates, and then clicking the "Check for update now" button.  

On the Mac version, I'd put it right below the "About Wavebox" item in the Wavebox menu.

**Comment by Thomas101** [comment]
This is shipping in 10.0.49 later today :)

**Comment by alanhoyle** [comment]
I installed 10.0.49 and it's exactly what I was hoping for.  Thanks!
