### ISSUE TITLE
Mac Desktop Notifications show "No Subject" when there is one

### ISSUE THREAD

**Issue by rdwilliams3** [wavebox/waveboxapp#1169]
* Wavebox Version: 10.0.42.2
* Operating System & Version: Mac OSX 10.15.2
* Account type (if applicable): Office 365

Desktop notifications show subject null ("No Subject") when there is a subject on email.  This only happens with O365.

**Notification:**
<img width="325" alt="image" src="https://user-images.githubusercontent.com/53830723/71198923-de4dc700-2262-11ea-9307-754d6f4a8a19.png">

**Email:**
<img width="661" alt="image" src="https://user-images.githubusercontent.com/53830723/71199064-20770880-2263-11ea-9652-57ca25e481f0.png">

**Comment by Thomas101** [comment]
Thanks! Managed to get to the bottom of this and get a fix. If you want to try it out, it's live in 10.0.47 on the [beta channel](https://kb.wavebox.io/beta-channel/)
