### ISSUE TITLE
Stop the "Time to switch to the Pro channel of Wavebox" popup from displaying on load?

### ISSUE THREAD

**Issue by joshskidmore** [wavebox/waveboxapp#1171]
* Wavebox Version: 10.0.42
* Operating System & Version: Arch linux (kernel: 5.4.3)
* Install method: tarball

I cannot get the "Time to switch to the Pro channel of Wavebox" popup to stop displaying when starting Wavebox. I'm on the latest version. I am able to close it, but it will reappear the next time I open Wavebox.

**Comment by Thomas101** [comment]
Which channel are you currently on? It should show this under Settings > About

**Comment by joshskidmore** [comment]
@Thomas101 - I *think* stable. I downloaded directly from the main site. With that said I think I was on the beta channel with Wavebox Classic and imported settings into Wavebox 10. This is my "Settings > About": http://josh.sh/MGq2.png

**Comment by Thomas101** [comment]
If you use the download links from the update dialog and download you'll get the stable channel and the pro update won't appear again ;-)

Or if you want to try the Wavebox 10 beta https://kb.wavebox.io/beta-channel/

**Comment by joshskidmore** [comment]
@Thomas101 - That was it. It would be really helpful if you could append/prepend the channel to the tarball itself. The filenames are identical and that was where my confusion was stemming from.


http://download.wavebox.app/latest/core/linux/tar <-- what I initially downloaded
https://wavebox.io/download/stable
http://wavebox.io/download/beta

Also - are you planning on managing the Arch AUR package for this or are you open to me creating one for v10 stable / beta? These are the packages available in AUR as of now:

```
2 aur/wavebox-bin-beta 4.11.8-1 (+3 0.56%)
    The next generation of web-desktop communication
1 aur/wavebox-bin 4.11.11-1 (+20 0.71%) (Installed)
    The next generation of web-desktop communication
```

**Comment by Thomas101** [comment]
> It would be really helpful if you could append/prepend the channel to the tarball file name

That's a good point. I'll look at getting that into the build system

> Also - are you planning on managing the Arch AUR package for this or are you open to me creating one for v10 stable / beta?

We've been working on adding more distribution methods for the new Wavebox. Hopefully, we'll have this ready shortly/early in the new year. I'll drop a note here when they're available :)

**Comment by joshskidmore** [comment]
Thanks! 

> We've been working on adding more distribution methods for the new Wavebox. Hopefully, we'll have this ready shortly/early in the new year. I'll drop a note here when they're available :)

Thanks! For Arch users, AUR is the best method for maintaining a package. As you add more packaging methods for linux, I ask  of you to please at least continue providing a pre-built tarball and not go the route of _only_ providing a snap/appimage/flatpak/etc image.

**Comment by Thomas101** [comment]
> I ask of you to please at least continue providing a pre-built tarball

Yep, the tar isn't going anywhere. It's great for anyone using a distro that we don't have an update mechanism for just yet, or for anyone who wants to just give it a try without adding the repo :)
