### ISSUE TITLE
Kicked out of two different GSuite accounts.

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#1178]
* Wavebox Version: 10.0.42-2 stable
* Operating System & Version: Windows 10

Two of my GSuite accounts won't log in and they give different errors. **I can log into both of them using Chrome.**

![image](https://user-images.githubusercontent.com/689204/71611069-1ef2ed80-2b4b-11ea-9bc2-9b9f90f4b473.png)
![image](https://user-images.githubusercontent.com/689204/71611068-17334900-2b4b-11ea-9ba3-04064348aec8.png)

**Comment by Thomas101** [comment]
Hi, thanks for reporting. Can you try quitting Wavebox completely and then try signing in again?

Just a couple of things that might have triggered this, which would be good to know
- Have you been signing in and out from different locations over the last few days
- Have you used any of these accounts to set up any new devices

**Comment by Thomas101** [comment]
Also do you have any extensions installed or JavaScript disabled?

**Comment by GollyJer** [comment]
Hi @Thomas101. Thanks for the reply.

I ended up deleting the account/profile and adding again. That worked.
