### ISSUE TITLE
Incognito mode presents itself as Chrome

### ISSUE THREAD

**Issue by jmfederico** [wavebox/waveboxapp#1179]
* Wavebox Version: 10.0.42.2
* Operating System & Version: macOS 10.15.2 (19C57)

When opening a new incognito mode with Wavebox, it presents itself as Chrome instead of Wavebox.

See attached screenshot.

<img width="1280" alt="Screen Shot 2020-01-04 at 11 36 17" src="https://user-images.githubusercontent.com/237977/71768718-ea828700-2ee6-11ea-96d5-909f5ed5bf95.png">

**Comment by Thomas101** [comment]
Thanks a fix for this will go out in 10.0.50

**Comment by Thomas101** [comment]
This is now fixed & released in 10.0.54
