### ISSUE TITLE
CTRL+R keybinding stolen by Wavebox

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#118]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.04 / Unity 7

I've noticed that Wavebox steals the CTRL+R binding, making me unable to reload pages on browsers, history searches on bash and generally anything else that CTRL+R is bound to on apps not wavebox.

The weird thing is that this doesn't happen immediately upon Wavebox startup, but after a few hours. Closing Wavebox makes CTRL+R available to other apps again, and reopening Wavebox doesn't steal the shortcut away.

**Comment by usoban** [comment]
This one happened to me too (noticed I could not reload Chromium), but I experience it only if Wavebox is minimized in tray. If I open it up, then CTRL+R works fine.

Wavebox: version 3.1.5
OS: NixOS 17.03 (xfce+openbox)

**Comment by luispabon** [comment]
^ Also applies to unity, happens with wavebox minimised to tray, but not when the main window is open.

**Comment by Thomas101** [comment]
Thanks for reporting, it should be releasing the bindings when not active, but it looks like that's failing.

Have you noticed that if you minimize/switch away from Wavebox in a certain way it always happens (e.g. keyboard shortcut, or something else)? Next time it happens could you see if the `Ctrl+{` keyboard shortcut switches mailbox when not in focus?

**Comment by luispabon** [comment]
I usually just close the window by clicking on the window close button.

**Comment by MichaelTunnell** [comment]
that's a really weird issue that hopefully will be fixed but a workaround for the time being, use F5 for basic refresh and Ctrl+F5 for full cache refresh. I think the Ctrl+R refresh in browsers is obsolete when compared to F5 and Ctrl+F5.

**Comment by luispabon** [comment]
Ctrl r is accessible with your left hand, which is handy for right handed users who use a mouse in that hand. This was never an issue with wmail btw.

**Comment by MichaelTunnell** [comment]
I'm not saying it shouldn't fixed, just something in the meantime. I think F5 is very easy access to because it's just one button with no modifier so either hand can be used regardless which hand is used on the mouse.

**Comment by Thomas101** [comment]
This is a bit of a weird issue. It seems to work on most OSes but for some reason the un-binding fails on others. The reason for being so aggressive with Ctrl+R is Outlook captures that shortcut and does something different.

To be honest it's better to have Ctrl+R not reloading the main window in Wavebox under some circumstances as it's such an infrequent thing to do. I've removed it in the upcoming 3.1.6 release (https://github.com/wavebox/waveboxapp/commit/af9321b65f7a517cdcba5d809c5708f2fb607b0a#diff-b78eb7e65a87c5cf3dd3fc90617b9a71) which should released early next week

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which fixes this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!
