### ISSUE TITLE
Allow notifiactions from mini and drawer to be cleared

### ISSUE THREAD

**Issue by Ash258** [wavebox/waveboxapp#1181]
* Wavebox Version: 10.0.47.3 beta
* Operating System & Version: Windows 10 10.0.18363.0

**Describe the solution you'd like**
Drawer notifications (and wavebox mini notifications) should have option to clear all of them like in old Wavebox.

**Additional info**
https://github.com/wavebox/waveboxapp/issues/829#issuecomment-441202879

**Comment by Thomas101** [comment]
Thanks, this will ship in 10.0.50

**Comment by Thomas101** [comment]
This is now fixed & released in 10.0.54
