### ISSUE TITLE
Changing the profile of a tab moves it to the end

### ISSUE THREAD

**Issue by jmfederico** [wavebox/waveboxapp#1184]
* Wavebox Version: 10.0.49.1
* Operating System & Version: macOS Catalina

**Expected & actual behavior**
- Actual: When one is using Wavebox as a browser and changes the profile used by a tab, the tab will be re-opened at the end of all other tabs.
- Expected: When one is using Wavebox as a browser and changes the profile used by a tab, the tab should be re-opened in the same position as it was.

**Steps to reproduce**
- Create more than 1 profile
- Open a new Wavebox window
- Open two tabs
- Change the profile of the first tab
- It will be opened at the end

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/237977/71914016-aab9da80-3146-11ea-903c-e7219686e2c7.gif)

**Comment by Thomas101** [comment]
Thanks, there's a fix for this coming in 10.0.52+

**Comment by Thomas101** [comment]
This is now fixed & released in 10.0.54
