### ISSUE TITLE
Cannot link Google Drive to Trello account

### ISSUE THREAD

**Issue by sethcasana** [wavebox/waveboxapp#119]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OS X El Capitan 10.11.6

I am attempting to link my Google Drive to my Trello account through Wavebox. I need to be able to do this to enable the Google Drive Power-Up. However, when I attempt to click the "Link Google Drive Account" button, the link always opens in a browser, thereby preventing Wavebox from capturing the authentication request. See screenshots for reference.

<img width="828" alt="screen shot 2017-04-26 at 5 00 26 pm" src="https://cloud.githubusercontent.com/assets/173278/25457005/b9d02086-2aa2-11e7-8d64-b2b092de201a.png">

**Comment by Thomas101** [comment]
Thanks! We'll need to capture this in Wavebox and post the auth back to trello. In the meantime if you open trello in your browser and link Drive are you able to get running by going the long way round?

**Comment by sethcasana** [comment]
Yes, I was able to connect my accounts using a standard browser. Once I did that, I could successfully access Google Drive via Trello using Wavebox. Thanks for asking!

**Comment by Thomas101** [comment]
Hi, there's a few issues around about linking Google Drive & Dropbox into Trello using Wavebox. We're currently waiting on an upstream fix for this. I've merged all the issues into one central place so we can continue tracking them from there (https://github.com/wavebox/waveboxapp/issues/187) and hopefully push a fix out soon.

I'm going to close this off for now so we can continue tracking in one place. Thanks!
