### ISSUE TITLE
Reloading app

### ISSUE THREAD

**Issue by NullpointerForever** [wavebox/waveboxapp#1190]
* Wavebox Version: 10.0.54-2 stable
* Operating System & Version: Windows 10
* Account type (if applicable): Office 365

After some time I want to switch to my other app on my tab bar (i.e. to Teams). And that tab it looks like it was disabled or in sleep mode (I have disabled sleep) - it's reloading. On Teams there is a new messages, but there is no unread count on icon.

**Comment by Thomas101** [comment]
Does this happen sporadically or all the time? Are you able to tell if the page actually reloads (i.e loses any state that you currently have on the page) or is it just like a white flash before re-appearing?

**Comment by NullpointerForever** [comment]
It happen sporadically. Today (after my Windows 10 update) I haven't noticed the problem and notifications looks good.
The page actually looks like reloading. For now you can close this issue. If I notice it again I can reopen this issue.

**Comment by Thomas101** [comment]
Okay thanks! Just let me know if you see it again
