### ISSUE TITLE
WhatsApp keeps signing out

### ISSUE THREAD

**Issue by victorbrca** [wavebox/waveboxapp#1198]
* Wavebox Version: 10.0.54-2
* Operating System & Version: Windows 10
* Account type (if applicable): WhatApp

**Expected & actual behavior**
I would expect to stay signed in to WhatsApp

**Steps to reproduce**
It looks like after WhatsApp is idle for a while, it looses the sign in authentication. I can still see it as an authorized device on my phone, but in Wavebox it's asking me to scan the code again.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![](https://snipboard.io/NZLv0H.jpg)

**Additional information**
I upgraded and migrated from the previous version this week.

**Comment by Thomas101** [comment]
If you try restarting Wavebox does it keep signing you out? Are you using WhatsApp Web on any other devices/browsers/apps, as this will automatically sign you out from the previous session

**Comment by victorbrca** [comment]
Hi Thomas,

I have tried re-starting Wavebox and even removing the apps and profiles
and re-adding them. It's not happening on Whatsapp only. It also happens on
other apps (like Microsoft Teams). It seems that if I manually put the app
to sleep and then wake it my session is restored.

And for WhatsApp is not the 'you are logged in in another device' message.
It actually takes me back to the setup page.
--
Victor Mendonça
http://victormendonca.com/

**Comment by victorbrca** [comment]
Hi Thomas,

Any updates on this? Any idea on what it could be?

I recorded a couple of videos showing the issue.

 VID_20200129_100447_lowrez.mp4
<https://drive.google.com/file/d/1wRpkNbkt_gmq6SKEHN8oZuaF7bqVOTx3/view?usp=drive_web>

 VID_20200203_104710.mp4
<https://drive.google.com/file/d/1wP2ZWNGzKUjtyBujBcKWi1Fh8Z6GXZVu/view?usp=drive_web>

Thanks,
--
Victor Mendonça
http://victormendonca.com/

**Comment by Thomas101** [comment]
I wonder if it's some kind of permission issue, which means the app isn't able to write to disk (it's a bit of a stab in the dark). If you sign in to WhatsApp, then restart Wavebox are you still signed in or do you get signed back out?

**Comment by victorbrca** [comment]
When I open the app in the morning it's usually ok. It seems that the issue
happens when I had the app open for a while.
--
Victor Mendonça
http://victormendonca.com/

**Comment by Thomas101** [comment]
This isn't something we've seen with any other users and something we've been unable to reproduce here, after talking with the team here and also considering the trouble you've had with https://github.com/wavebox/waveboxapp/issues/1199 we're starting to wonder if it's a corrupt install.

Would you be able to try removing Wavebox from Add & Remove Programs, then downloading the latest version from https://wavebox.io/download and running the installer again? Hopefully, that will yield better results

**Comment by victorbrca** [comment]
Hi Thomas,

My apologies I didn't get back to you before. I think you are onto
something because I don't have permission to uninstall Wavebox.

You can close the ticket for now. Thanks for the help.
--
Victor Mendonça
http://victormendonca.com/

**Comment by nmat** [comment]
So this can be closed?

**Comment by victorbrca** [comment]
Yep. It looks like the issue was because I installed this on my work computer without admin rights. It allowed me to install the app, but it presented this weird behaviour with the accounts.

**Comment by nmat** [comment]
thanks for the response
