### ISSUE TITLE
Multiple Google profiles not working

### ISSUE THREAD

**Issue by victorbrca** [wavebox/waveboxapp#1199]
* Wavebox Version: 10.0.54-2 stable
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail

**Expected & actual behavior**
Show my secondary Gmail account when I click on it's icon (instead of showing my primary account)

**Steps to reproduce**
Wait for Wavebox to idle and then click on a secondary or tertiary Google account. 

**Is the bug persistent or intermittent?**
Persistent 

**Screenshots**
![](https://snipboard.io/leakiH.jpg)

**Additional information**
I upgraded from a previous version this week and imported my configuration. After having the app idle for a while, when I click on the second or third Gmail accounts it actually loads my primary account. The account icon in the tray also changes.

All Google accounts are configured with different profiles and all 3x Gmail apps are configured with **no idle**.

**Comment by Thomas101** [comment]
Hey, it looks like something might have gone wrong during the import process. Can you drop support a message (https://wavebox.io/support) and we can dig a little deeper into what's gone wrong

**Comment by victorbrca** [comment]
Spoke to support and got it fixed.
