### ISSUE TITLE
Feature Request: Add Settings Accounts/Import Wizard from WMail

### ISSUE THREAD

**Issue by Arithmomaniac** [wavebox/waveboxapp#12]
* Which version of Wavebox are you using? 3.1.2

* Which Operating System are you using? Windows 10

**Comment by Thomas101** [comment]
Yeah, great idea! Will add this in!

**Comment by Thomas101** [comment]
Hi a fix for this has just been release in 3.1.3. Wavebox will autoupdate shortly or if you want to get it sooner you can either re-launch Wavebox to trigger an autoupdate or redownload from https://wavebox.io/download Thanks!

**Comment by Arithmomaniac** [comment]
What will happen if you want to import GDocs/Keep, or more than two GMail accounts? (Personally, I think they should be grandfathered, but I could understand the risk of abuse.)

**Comment by Thomas101** [comment]
When you choose import it will bring all 11 accounts across. You can use all of these unrestricted for the duration of the trial period. After this the top two will remain accessible. If you decide you want to upgrade, none of the accounts aren't removed automatically so you can get up and running right away.

We also have our [20% affiliate scheme](https://blog.wavebox.io/wavebox-affiliates/) which rewards you with 20% of the pro membership any referrals pay.

**Comment by andjosaus** [comment]
Is there still an affiliate program in place for wavebox?

I'd love to help spread the word on its great abilities!
