### ISSUE TITLE
Danish spell checking not working

### ISSUE THREAD

**Issue by braffas** [wavebox/waveboxapp#120]
* Which version of Wavebox are you using? [3.1.5]

* Which Operating System are you using? [Windows 10]

When i install and enable Danish spell checking nothing happens. Red line is gone, and there is no context menu for spell check when right clicking a word

English spell checking works fine.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. If you restart Wavebox does it start working again?

If this doesn't work, it could be that the dictionary files failed to download. If quit Wavebox and open `C:\Users\<User>\AppData\Roaming\wavebox\wavebox\user_dictionaries\` you should find `da_DK.aff` and `da_DK.dic`. Try deleting those, re-starting Wavebox and re-installing the dictionary

**Comment by braffas** [comment]
That did not work. The files were in the location. I closed Wavebox, deleted the files, opened Wavebox and redownloaded the files.

**Comment by Thomas101** [comment]
Thanks. Seeing the same my end now

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which fixes this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by braffas** [comment]
It's working perfectly now :)

I love Wavebox, i will sign up for the pro version now

Best regards
Kasper

2017-05-04 14:17 GMT+02:00 Thomas Beverley <notifications@github.com>:
