### ISSUE TITLE
No functionality after upgrade AUR v10

### ISSUE THREAD

**Issue by schmunk42** [wavebox/waveboxapp#1200]
* Wavebox Version: 10
* Operating System & Version: Arch Linux
* (Linux only) Install method: AUR (manual download before)
* Account type (if applicable): all

**Expected & actual behavior**
Open application, see applications in sidebar or show settings.
I see just a "normal" browser.

**Steps to reproduce**
Open application....

**Is the bug persistent or intermittent?**
always

**Screenshots**
![Bildschirmfoto von 2020-01-31 11-00-57](https://user-images.githubusercontent.com/649031/73530766-61913980-4419-11ea-8dde-168a693206a0.png)

**Comment by nmat** [comment]
Are you still seeing this issue and if so can you please explain how you got the package?

**Comment by schmunk42** [comment]
I was able to fix that by closing the app from the burger menu on the top right.

AFAIR installed via download of the package description and then via `pacman`.
