### ISSUE TITLE
Wavebox 10 fails to start on CentOS 7.7

### ISSUE THREAD

**Issue by jubbathejack** [wavebox/waveboxapp#1202]
* Wavebox Version: 10.0.54
* Operating System & Version: CentOS 7.7.1908
* (Linux only) Install method: Stable Yum repository

**Expected & actual behavior**
When trying to launch Wavebox 10 after an upgrade from Wavebox classic, it should launch the application, but fails to.

**Steps to reproduce**
Upgrade from Wavebox classic to Wavebox 10, by installing the stable repo that points at the 10 release. Try to launch Wavebox using the desktop launcher. It won't open.

**Is the bug persistent or intermittent?**
This happens every time, even after a reboot.

**Additional information**
This is the log that journalctl outputs at the same time as trying to launch Wavebox.
```
Jan 31 15:27:05 <HOSTNAME> wavebox.desktop[6153]: [6153:6153:0131/152705.334476:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Jan 31 15:27:05 <HOSTNAME> kernel: traps: wavebox[6153] trap int3 ip:55ef8caad31d sp:7ffc89d2f2a0 error:0
Jan 31 15:27:05 <HOSTNAME> abrt-hook-ccpp[6161]: Process 6153 (wavebox) of user 10018 killed by SIGTRAP - dumping core
Jan 31 15:27:05 <HOSTNAME> abrt-server[6162]: Can't load public GPG key /etc/pki/rpm-gpg/RPM-EFDCEA77.asc
Jan 31 15:27:06 <HOSTNAME> abrt-server[6162]: Package 'Wavebox' isn't signed with proper key
Jan 31 15:27:06 <HOSTNAME> abrt-server[6162]: 'post-create' on '/var/spool/abrt/ccpp-2020-01-31-15:27:05-6153' exited with 1
Jan 31 15:27:06 <HOSTNAME> abrt-server[6162]: Deleting problem directory '/var/spool/abrt/ccpp-2020-01-31-15:27:05-6153'
```

**Comment by jubbathejack** [comment]
I can only assume that maybe CentOS, being an OS that is quite long in the tooth, does not have a kernel with the relevant features. The CentOS kernel, if interested, is 3.10.0-1062.9.1.el7.x86_64.

**Comment by Thomas101** [comment]
Thanks for reporting. I think you might be right there with the Kernel not supporting the relevant features.

Wavebox 10 has a bunch of hardened security features over Wavebox 4, user-space sandboxing being one of those, which is what it looks like is failing here.

The best thing to do is to update to a newer kernel, but you're probably not in a position to do that. There are also some system-wide settings you're able to toggle which will allow the app to launch, but I'd be hesitant to recommend those either, as they have wider security implications.

Probably the best thing to do until you're able to update is to disable the sandboxing in Wavebox 10, so it works in a similar way to Wavebox 4. You can do this in two ways...

1. On a one-off basis, run `/opt/wavebox.io/wavebox/wavebox-launcher --no-sandbox`
2. Edit the Wavebox desktop file to always launch with sandboxing disabled. Edit `/usr/share/applications/wavebox.desktop`. Change the exec line from...
  * **from** `Exec=/opt/wavebox.io/wavebox/wavebox-launcher %U`
  * **to** `Exec=/opt/wavebox.io/wavebox/wavebox-launcher --no-sandbox %U`

**Comment by jubbathejack** [comment]
Many thanks @Thomas101, that's done the trick very nicely :)
