### ISSUE TITLE
Weavebox Authentication flow of Slack is in a strange state, and doesn't work.

### ISSUE THREAD

**Issue by the-simian** [wavebox/waveboxapp#1208]
* Wavebox Version:4.11.11
* Operating System & Version: Mac OSX 10.14.6
* Account type (if applicable): Slack

**Expected & actual behavior**
sign in on Slack causes the window to appear in the wrong place and not 'replace the sign in' fingerprint window.

**Screenshots & Reproduction**

1. A slack account in a sandboxed workspace has been signed out, as it does periodically.
![image](https://user-images.githubusercontent.com/954596/74184242-10006000-4c0c-11ea-95f4-be7240172e76.png)

2. I've tried signing into this account already, and you can see in the pop up it shows it, but also prompts for the space.

![Screen Shot 2020-02-10 at 1 49 24 PM](https://user-images.githubusercontent.com/954596/74184348-4211c200-4c0c-11ea-85e2-995b74ff7b8f.png)

3. if I type in the name or select the 'already authenticated item below' what happens is it shows me signing in in that popup. I cannot really capture this as a screenshot (it happens fast). The window is immediately minimized/dissapears. I am left with this screen.
![image](https://user-images.githubusercontent.com/954596/74184468-76857e00-4c0c-11ea-8f87-64d93879154f.png)

4. All I can do is minimise, or click off the modal. Its like in an endless loop now, never really authenticating
![Screen Shot 2020-02-10 at 1 52 16 PM](https://user-images.githubusercontent.com/954596/74184552-99179700-4c0c-11ea-96c9-ce75e263b6bf.png)
All of the slack services on this email are doing this. Its very strange. Usually they periodically sign me out, but these cannot sign back in through wavebox. I can see that slack itself works (I cna sign in on the website). Its something about how wavebox is handling the authentication flow.

**Comment by the-simian** [comment]
I wanted to add I also use Wavebox on Windows, 64 bit and it works just fine on that platform.

**Comment by Thomas101** [comment]
Thanks for reporting. It looks like this is down to the third party cookie shakeup that's happening with Chrome.

We launched [Wavebox 10](https://github.com/wavebox/waveboxapp/issues/1133) at the end of last year, which is built directly on Chromium so doesn't have some of the same issues that the Wavebox 4 (based on Electron) has in its network architecture. 

I'd recommend giving it a try, there's so more info on how to switch [here](https://blog.wavebox.io/wavebox-10-migration-wizard-for-pro-users/) and some info about the underlying changes [here](https://blog.wavebox.io/wavebox-is-evolving-electron-chromium/).

You can [download the latest version here](https://wavebox.io/download)

**Comment by the-simian** [comment]
@Thomas101 hey thanks for replying, I'll try to migrate when I can. I appreciate you letting me know about the new release as well.

**Comment by Jodything** [comment]
I am on Wavebox v 10.0.69.2 stable MacOS Catalina and am seeing this same issue.

**Comment by Thomas101** [comment]
@Jodything someone reported that clearing browsing data under Settings > Profiles seemed to fix this. It would be great to know if this fixes it for you too.

We're having trouble reproducing this with version 10 our end across lots of different slack accounts, so any extra info you have would be really helpful

**Comment by Jodything** [comment]
Hey @Thomas101 that seemed to do the trick! Thanks for the quick reply

**Comment by Jodything** [comment]
This particular SSO with slack uses google authenticator for logging in if that info helps at all.

**Comment by j0hnm4r5** [comment]
This happens to me every time my Slack account decides to log out — I need to clear the profile to get the app to display in the main window instead of a popup.

I also use a Google SSO to log in, and am currently on Wavebox 10.0.54-1 core on macOS 10.15.

**Comment by Thomas101** [comment]
@j0hnm4r5 it's probably worth updating Wavebox, 10.0.121 is the latest version and has numerous fixes over 10.0.54

**Comment by Kukkerem** [comment]
I have a similar problem, Version 10.0.493.2 stable, 5.10.30-1-MANJARO x86_64. I have 6 Slack accounts, and after clearing browser data, restarting Wavebox, I can log in for 2-3 seconds, and it throws me back to the "Sign back in" page. It started today before I updated Wavebox.

**Comment by robiningelbrecht** [comment]
Can confirm this problem

**Comment by sschaefa** [comment]
Same thing happens since today for all my slack accounts. Clearing cookies & cache did not help.

**Comment by robiningelbrecht** [comment]
For those who are looking for a "workaround". In Wavebox, I hit CTL+T which opens a new chromium tab and then I just navigated to the web based Slack in separate tabs.

**Comment by lskupnjak** [comment]
Some thing for me, and it's really annoying :) Using MacOs.

**Comment by sschaefa** [comment]
> Same thing happens since today for all my slack accounts. Clearing cookies & cache did not help.

Now Slack magically works again for all accounts, but the "!" badge is still there, so I don't see notifications. It's something. :-)

**Comment by Thomas101** [comment]
we've just pushed 10.0.495 out with a fix for this

**Comment by robiningelbrecht** [comment]
Can confirm the update fixes the problem for me.

**Comment by lskupnjak** [comment]
@Thomas101 Thank you, it seems the problem is fixed! :)

**Comment by sschaefa** [comment]
Fixed it for me as well. I am impressed about the response time. Thank you so much!

**Comment by the-simian** [comment]
I'm no longer experiencing this, thank you
