### ISSUE TITLE
Set unread badge through JS [feature request]

### ISSUE THREAD

**Issue by phcyso** [wavebox/waveboxapp#121]
* Which version of Wavebox are you using: 3.1.5
* Which Operating System are you using: MacOS 10.12.4

Is there a way, or can it be added, to be able to set the unread count badge through the custom JS?

I have added https://asana.com/ and https://www.pivotaltracker.com through the 'add any website' function and they work great but i have to open them up to check if i have any notifications.

Being able to inject a function that captures the unread notification webhook/ajax call and send a update to the UI to change the badge and/or the account icon would be very nice.

**Comment by Thomas101** [comment]
We are looking at adding an API into the tab that you can use for doing this

**Comment by mickmel** [comment]
This would be amazing. Two of us at the office are now paying for Wavebox (and love it!), but getting Asana badge support would pull in the rest of the team. While making it a native supported site would be great, this solution could work too.

**Comment by Thomas101** [comment]
We're hoping to start shipping our extension api in September, so isn't too far off :)

**Comment by Thomas101** [comment]
Hi, we've started to move some tooling into the Weblink accounts for this. In version 3.8.0 the API can be enabled through settings... 

![screen shot 2018-01-15 at 15 04 20](https://user-images.githubusercontent.com/103586/34948568-6faf044e-fa05-11e7-8abd-b0ec0bab41f6.png)

Once you've done this, the page or custom JS on the account can use a few APIs to change badges, counts, notifications etc.

```js
window.wavebox.badge.setCount(10)
window.wavebox.badge.setHasUnreadActivity(true)
window.wavebox.tray.setMessages([
    {
        id: 'message_id_1',
        text: 'Bob said: You have a message',
        date: 1516022635099
    }
])

// html5 apis available for notifications
Notification.requestPermission()
new Notfication('test', {})
```

We're looking a putting a more formal mechanism together for loading this in and along with it some documentation, but thought I'd give you heads-up if you want to give it a try :)
