### ISSUE TITLE
Linux: UI regression, content overlapping header bar

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#1215]
* Wavebox Version: 10.0.82-2
* Operating System & Version: elementaryOS 5.1 Linux
* Account type (if applicable): N/A

With the first release of Wavebox 10 there was an issue with UI. It was corrected in all subsequent versions, but it's back with the latest version - the window content is slightly covering window header bar and controls:

![ksnip_20200219-075524](https://user-images.githubusercontent.com/6765137/74809615-e15e4580-52ed-11ea-80d0-4b1ba3e3d8f7.png)
![ksnip_20200219-075545](https://user-images.githubusercontent.com/6765137/74809624-e4f1cc80-52ed-11ea-9763-cc6d5795f7d1.png)

**Comment by Thomas101** [comment]
Thanks for reporting! We've just pushed a fix out in 10.0.86 which fixes this :)

**Comment by WebShapedBiz** [comment]
Cheers @Thomas101
