### ISSUE TITLE
Facebook videos not working

### ISSUE THREAD

**Issue by jsobell** [wavebox/waveboxapp#1221]
* Wavebox Version: 10.0.90.1 core
* Operating System & Version: Windows 10 64
* Account type (if applicable): Facebook

Can't play any videos within Wavebox. Chrome plays them fine.

Dev console shows:
![image](https://user-images.githubusercontent.com/834155/75623102-0fe7f480-5bfb-11ea-9ec8-54bd79e3448a.png)

**Comment by Nastase** [comment]
Same issue here. No vídeos or Gifs are played (Whatsapp, Facebook, Twitter...)

**Comment by Thomas101** [comment]
Hey, the paid-for version of Wavebox has some additional codecs which support a broader range of media playback, including videos on Facebook, WhatsApp etc. Shortly after you sign in with a pro account, or shortly after purchase, you'll be prompted to update. If this hasn't happened yet, you can manually fetch the update by going to Settings > Updates and clicking on check for updates or drop support https://wavebox.io/support if you're still having trouble

**Comment by Nastase** [comment]
Fixed when albeit I had to manually force the update. Thank you

**Comment by jsobell** [comment]
Purchased full version, new version downloaded, and problem is solved.
