### ISSUE TITLE
Widevine CDM is missing

### ISSUE THREAD

**Issue by ToLive** [wavebox/waveboxapp#1223]
* Wavebox Version:  10.0.109.3 beta
* Operating System & Version: Windows 10

Can't play any DRM content like Spotify web player (open.spotify.com).

As I see, WidevineCDM component is missing in chrome://components

Vivaldi, that is also chromium based doesn't have this problem.

![Ticket20200313_1911_3376](https://user-images.githubusercontent.com/2019736/76644071-f5990980-655e-11ea-80f9-639a18693493.png)
![Ticket20200313_1911_3375](https://user-images.githubusercontent.com/2019736/76644076-f631a000-655e-11ea-972f-8c19ed80674c.png)

**Comment by EnorMOZ** [comment]
Still not supported in `Version 10.0.131.3 beta`

**Comment by VarunAgw** [comment]
I think it's because of Chrome abusing their position. They don't make it easy to bundle Widevine.

https://en.wikipedia.org/wiki/Widevine#Criticism

**Comment by EnorMOZ** [comment]
I received the following email from wavebox support back in March 11th....  roughly 2 months ago. Still waiting ......

> Thanks for your message.  I'm afraid that Spotify isn't working just yet.  We've just received approval from Widevine to add-in support for it, so we're working on that now. It should be out in the next couple of releases - so keep an eye out for it. 👀  
​
Thanks in advance for your patience with this. 😅👍Let me know if you've got any questions on this or anything else.

**Comment by ToLive** [comment]
With new update Spotify works fine!
