### ISSUE TITLE
Feature request: OneNote with Outlook account

### ISSUE THREAD

**Issue by usoban** [wavebox/waveboxapp#123]
It would be nice if we had integration with OneNote for Outlook accounts, just like there's integration for Calendar, OneDrive, People and Tasks.

So far I've managed to add it as a Website and it works fine, but it'd be nice to have an official integration (with the small icon below the main Outlook icon in left sidebar).

* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
NixOS Linux 17.03

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
