### ISSUE TITLE
No way to hotkey switch between apps

### ISSUE THREAD

**Issue by jalexvig** [wavebox/waveboxapp#1234]
* Wavebox Version: 10.0.104.2 stable
* Operating System & Version: Mac OSX 10.15.3
* Account type (if applicable): N/A

Previously I could set up a hotkey for cycling through apps (previous and next) on the top bar. This does not appear to exist in v10 (there is an option to cycle through groups on the side bar).

Moreover `Switch to group in position X` and `Switch to tab in position X` appear to do the same thing (switch to group `X` on the side bar).

**Comment by Thomas101** [comment]
You can use <kbd>Ctrl</kbd>+<kbd>Tab</kbd> and <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd> to cycle between running apps. This isn't customizable at the moment.

Switch to group and switch to tab behave differently depending on which window you have open.
* Switch to tab
  * In the main Wavebox window - switch to the group at the given index
  * In a window with tabs along the top - switch to the tab at the given index
* Switch to group
  * In the main Wavebox window - switch to the group at the given index
  * In a window with tabs along the top - bring the main window to the front, and switch to the group at that index

We have had a couple of people report similar confusion, so if you've got any feedback on how we can make this clearer we'd love to hear it

**Comment by jalexvig** [comment]
@Thomas101 Thanks for the intel. Is there is an intractable reason this isn't customizable or might this be added in the future? A lot of people use dedicated leader keys in apps - for example with my current keyboard firmware it's actually not possible to `Ctrl` + `Tab` because my dedicated leader keys are `Ctrl` + `Alt` and other keys are mapped with this assumption. If this is not going to change I will reflash my keyboard firmware to compensate, but it would be great if this was a feature.

I see. Is there a reason for the duplicate functionality? Seems like you can safely eliminate:

* Switch to tab
  * In the main Wavebox window - switch to the group at the given index

Since

* Switch to group
  * In the main Wavebox window - switch to the group at the given index

This would eliminate confusion due to the actual behavior.

Also adding "In a window with tabs along the top, ..." in the hotkey description would be useful. Maybe in a tooltip to avoid extra default verbosity.

**Comment by Thomas101** [comment]
I've added some new shortcuts in, that cycle through the apps in a group. This is slightly different from how Ctrl+Tab works, as that goes through currently running tabs, whereas the new one cycles through the current group waking up apps as required. This shortcut isn't mapped by default, but it lets you map it if required.

We have been working on upgrading to chromium 81, but the Chromium team has postponed the release so we've also modified our upgrade cycle. That means these changes should be rolling out to the Wavebox beta channel shortly and stable not too long after.

As for the switch to tab & group, one thing that you can do with `Switch to group` is map it globally so even when another app is in the foreground you can bring Wavebox back to the front and switch to the tab. This isn't possible with `Switch to tab`. We've updated the hotkey description to be more descriptive :)

**Comment by jalexvig** [comment]
Perfect - in addition to cycling, switching to a specific app (in a group) was also something I used a lot in the previous version of wavebox.
Thanks for the speedy replies/fixes!

**Comment by jalexvig** [comment]
This is working great - thanks!
