### ISSUE TITLE
Hotkey switching between groups loses app focus

### ISSUE THREAD

**Issue by jalexvig** [wavebox/waveboxapp#1235]
* Wavebox Version: 10.0.104.2 stable
* Operating System & Version: Mac OSX 10.15.3
* Account type (if applicable): N/A

Setup:
Focus in group 2, app 2
Switch (hotkey or click) to group 1
Hotkey switch to group 2

Existing:
Focus in app 1

Expected:
Focus in app 2 (previously focused app for this group)

Note: I get the expected behavior if I click switch to group 2 instead of hotkey switch.

**Comment by nmat** [comment]
It does not save the last state of in app service used right?

I can reproduce this here on wavebox 10 also.

**Comment by jalexvig** [comment]
> It does not save the last state of in app service used right?
> 
> I can reproduce this here on wavebox 10 also.

Correct

**Comment by Thomas101** [comment]
10.0.121 has just gone out, which fixes this. Thanks for reporting!

**Comment by jalexvig** [comment]
@Thomas101 I'm on 10.0.121.2 and this isn't fixed.

**Comment by nmat** [comment]
This seems to happen only on keyboard shortcut change. But I tested it with normal click behaviour and I got back to 2nd service.

**Comment by Thomas101** [comment]
Let me just check I'm trying to reproduce the same thing here...
1. Group 1 (Dashboard), Group 2 (Gmail), app 4 (Google Keep) selected
2. Press Ctrl+Shift+1 and Ctrl+Shift+2 to switch between them. It switches between the dashboard and Google Keep
3. If I'm already in Group 2 and press the keyboard shortcut, it returns me to the first app (Gmail in this case)

Here's a short screen recording...
![Mar-26-2020 11-29-20](https://user-images.githubusercontent.com/103586/77642221-388eb000-6f55-11ea-9d3a-a1048538c49b.gif)

**Comment by jalexvig** [comment]
@Thomas101 weird - I don't get this behavior. To make sure we are in sync, the hotkeys in question are `Switch to the next group` and `Switch to the previous group` right? Below is the behavior I get in Version 10.0.121.2 stable.

![wavebox_app_loses_focus](https://user-images.githubusercontent.com/12684689/77712134-538b0f80-6fa9-11ea-8752-084407fcaece.gif)

**Comment by Thomas101** [comment]
@jalexvig yep different keyboard shortcut! There will a fix for this in the next beta :). Thanks!

**Comment by jalexvig** [comment]
This is working great - thanks!
