### ISSUE TITLE
Arch Linux AUR - failed installation wavebox 10.0.128_3-1

### ISSUE THREAD

**Issue by waldauf** [wavebox/waveboxapp#1237]
I run upgrade Wavebox from AUR which failed with this error:
```
==> Making package: wavebox 10.0.128_3-1 (Tue 14 Apr 2020 11:05:48 AM CEST)
==> Retrieving sources...
  -> Found wavebox-10.0.128_3.tar.gz
  -> Found wavebox.appdata.xml
  -> Found wavebox.menu
  -> Found LICENSE
==> Validating source files with md5sums...
    wavebox-10.0.128_3.tar.gz ... FAILED
    wavebox.appdata.xml ... Passed
    wavebox.menu ... Passed
    LICENSE ... Passed
==> ERROR: One or more files did not pass the validity check!
Error downloading sources: wavebox
```

* Operating System & Version: Arch Linux

**Comment by Thomas101** [comment]
Hi, the AUR package has been added by someone in the arch community. Looking at the package, they're using the latest redirect URL for the AUR which unfortunately breaks when we do a release as the md5 check in the package is then for an older version.

I've reached out to them with some instructions on how to use the fixed URL for each release as opposed to one which changes frequently. This means this problem shouldn't come up. I haven't heard back from them as yet.

The latest official version is available from https://wavebox.io/download/beta , we don't offer an AUR package at the moment, but it's something we may look into in the future

**Comment by waldauf** [comment]
@Thomas101 Thx for the effort to help with the AUR package. Can you send here your instructions on how to fix it? I'll also try to contact the maintainer.

**Comment by Thomas101** [comment]
Yeah sure...

The AUR package currently uses http://download.wavebox.app/latest/beta/linux/tar as the download link. This is a redirect to the always latest version, which means when we push a new version out the checksum fails.

Instead, it needs to reference the URL for the specific version, of writing, 10.0.131 is the latest which would be https://download.wavebox.app/beta/linux/tar/Wavebox_10.0.131-3.tar.gz

**Comment by waldauf** [comment]
Thx!
