### ISSUE TITLE
Can't start Wavebox on Debian Linux (sandbox err.)

### ISSUE THREAD

**Issue by stevenlafl** [wavebox/waveboxapp#1238]
New user here, just downloaded Wavebox from https://wavebox.io/download/ and it will not start.

`dpkg -i wavebox_10.0.128-1_amd64.deb`

```
/opt/wavebox.io/wavebox/wavebox-launcher %U
[10176:10176:0416/115636.608753:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Trace/breakpoint trap
```

https://kb.wavebox.io/no-usable-sandbox-error-on-linux/ My linux distro and kernel are 100% up to date according to apt-get. I would prefer not to run without a sandbox.

* Wavebox Version: 10.0.128-1
* Operating System & Version: Debian 10
* Kernel version: Linux 4.19.0-8-amd64
* Account type (if applicable): N/A

**Comment by stevenlafl** [comment]
https://kb.wavebox.io/no-usable-sandbox-error-on-linux/ I would prefer not to run without a sandbox.

**Comment by stevenlafl** [comment]
Got it. Solution:

```
echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/00-local-userns.conf
service procps restart
```

Explanation:
https://superuser.com/questions/1094597/enable-user-namespaces-in-debian-kernel#1122977

**Comment by Thomas101** [comment]
@stevenlafl thanks for the heads up on that. I've updated the KB article!
