### ISSUE TITLE
Issue with Chromium 81.0.4044.122

### ISSUE THREAD

**Issue by kcinman11358** [wavebox/waveboxapp#1239]
* Wavebox Version: 10.0.142
* Operating System & Version: Windows 10
* Account type (if applicable): Google accounts

In talking with my IT team, we have an issue with the new Chromium 81. Something around ​T​L​S13​Hardening​For​Local​Anchors​Enabled

They said that I need to add something in the registry for this for Wavebox
https://cloud.google.com/docs/chrome-enterprise/policies/?policy=TLS13HardeningForLocalAnchorsEnabled

Is there a way for me to downgrade or add this to the registry?

**Comment by Thomas101** [comment]
Hey, if you open a new tab in Wavebox and navigate to chrome://flags/#tls13-hardening-for-local-anchors you can enable it from here

**Comment by kcinman11358** [comment]
@Thomas101  you are the man! Thanks for your fast response. I'll try this out here shortly.

Is Wavebox10 still open source? I can't find the downloads for the previous versions anywhere

**Comment by Thomas101** [comment]
Great let us know how it goes!

**Comment by kcinman11358** [comment]
It worked! Thanks @Thomas101 

Question though, is there a page to download old versions?

**Comment by Thomas101** [comment]
Old versions are still available - although there isn't a nice page with them listed at the moment.

For the previous version, (10.0.128 of writing) you can grab it here https://download.wavebox.app/stable/win/Install%20Wavebox%2010.0.128.2.exe

Talking to the team, I think we'll be adding a page shortly :)

**Comment by kcinman11358** [comment]
Awesome. Have a great day!
