### ISSUE TITLE
[WBX] Allow dashboard as standalone window

### ISSUE THREAD

**Issue by Ash258** [wavebox/waveboxapp#1245]
Wavebox mini is good status "monitor" as overview of all services, notifications. But since WBX and its dashboard feature I would like to see dashboard standalone window instead of Wavebox mini.

Some user story:
I am a contractor for various companies and I am required to use lots of emails, slacks, msteams, PRTGs,... And for the most critical services, I have a dashboard with groups filled by customers/services/priority and so on.
This is fine, but as soon as I receive notification (slack message, PRTG notification) I have to go to the service itself to handle it, but I lose the dashboard overview because the actual service is now the main window. 
Before WBX (and before I found out the hack) I used Wavebox mini `always on top` feature on my status display (third lifted monitor) and it would be awesome if I could officially switch to the standalone dashboard as a status window.
Because now if I use no hacks and keep the Wavebox on my third screen with dashboard open I need to always move the Wavebox to the different display and handle the notifications, which is not a good workflow

Currently, I am using a hackaround to open a new tab and then use `chrome-extension://ckimpoegidoklmlkmkccfmbdmfigmgfm/ui-dashboard/index.html` as URL, which seems to fully work (even with clicking on items/notifications), but I would rather have the official way.

* Wavebox Version: 10.0.158.3.beta
* Operating System & Version: Microsoft Windows 10.0.18363

**Comment by Thomas101** [comment]
That workaround is perfectly valid - if we added a specific button for this it would just be opening at tab at that endpoint. You can also right click on the dashboard icon and use "Open current page in new window" which basically does the same thing.

Were you thinking about a button on the dashboard to open up in a new window, or did you have something else in mind?

**Comment by Ash258** [comment]
Good. If this behavior is intended and valid then I am fine with the current state.

Thank you!
