### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by max-sixty** [wavebox/waveboxapp#1249]
FYI a typo here — uou
<img width="433" alt="image" src="https://user-images.githubusercontent.com/5635139/84923136-aab9f100-b07b-11ea-9bd1-45607e13176f.png">

* Wavebox Version: Version 10.0.179.2 stable
* Operating System & Version: MacOS

**Comment by max-sixty** [comment]
Also FYI there's one in the issue template too "For dedidcated support"

**Comment by Thomas101** [comment]
Thanks!

**Comment by nmat** [comment]
These seems to be fixed now? Can we close this issue?
