### ISSUE TITLE
Add more Google Services (Voice, G+, Anaylitcs, Adwords, more)

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#125]
* Which version of Wavebox are you using? [e.g. 3.0.0]
**3.1.5**

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
**KDE Neon (Ubuntu 16.04)**

--------

I am really impressed with the differences between Wavebox and WMail so even though I was initially annoyed by the switch (due to no warning), I have become much less bothered by it after testing the trial of Wavebox.

I wish there were more Google Services to use in the (tab bar, my preference) because I now find myself going back to my browser for these and my workflow would be so much more productive if Wavebox handled them.

Here are the following services I'd like to be added that I think make sense for Wavebox:

- Google Voice
- Google+
- Google Analytics
- Google Adwords
- Google AdSense
- Google Allo *
- Google My Business *

* - I think Google Allo & Google My Business are not really that important but it would be nice to have.

------

If Wavebox had support for the above Google Services then I'd be set in terms of the work I do in this regard.

I know I can do this stuff as separate accounts but it would be much nicer if I could do it in my main Wavebox accounts. Google+ could be separate because of the different brand pages and stuff but the rest would be much better connected to the grouped services setup.

**Comment by Thomas101** [comment]
Definately!

**Comment by Thomas101** [comment]
Hi, we're working hard on adding more into Wavebox, with lots of new features coming in the pipeline! :-)

I'm collapsing all the new Google Service requests into a single issue so we can keep track of them more closely. I haven't moved Allo across as this is mobile app only at the moment but we'll continue to monitor if Google release a web based version of this.

You can find and continue tracking progress from #131. Thanks!

**Comment by MichaelTunnell** [comment]
> Have you tried adding these into Wavebox using the Any Web Link account type? The integration isn't as tight as with the normal services but might get you started in the meantime.

Yea, I have tried that but it wastes space and that bothers me, other than that it's fine. I just like being space efficient.
