### ISSUE TITLE
Not getting windows notification for gmail emails

### ISSUE THREAD

**Issue by kcinman11358** [wavebox/waveboxapp#1254]
* Wavebox Version: 10.0.195.2 stable
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail email only. Works fine for Google Calendar notifications and Google Chat notifications

Hello,

I am no longer getting the windows notifications for gmail emails. Google Calendar and Google Chat work fine. I am still hearing the audio though when a notification comes in (i have it set to marimba). I'm looking in the system tray and there is no sign of email there either.

**Comment by Thomas101** [comment]
Hi, it sounds like the Inbox Type that you have set up in Wavebox vs the one you're using in Gmail are different. There are some steps you can take to check they're both the same here https://kb.wavebox.io/gmail-unread-counts/ . It's also worth noting the special cases at the bottom, in case your setup falls into one of these

**Comment by kcinman11358** [comment]
Hi @Thomas101 

Here is my setup
![image](https://user-images.githubusercontent.com/7409848/87552968-01fdb200-c678-11ea-9aa8-1d3e343aa886.png)

No additional accounts or anything setup either

The weird thing is, I am getting the notification sound and i'm seeing the counter go up. I'm just no longer getting the notification in the windows notification tray

**Comment by Thomas101** [comment]
Thanks for checking those, that's not the issue then.

Would you be able to check the following, it could be one of these...

1. Under the settings for that Gmail account, check that `Show Notifications` is Enabled
<img width="1073" alt="Screenshot 2020-07-16 at 08 58 51" src="https://user-images.githubusercontent.com/103586/87643718-1ce92880-c743-11ea-867a-dbadb62e6ab2.png">
2. Under Settings > Notifications, check that notifications aren't muted (it will display that they're muted if this is the case)
<img width="687" alt="Screenshot 2020-07-16 at 09 03 07" src="https://user-images.githubusercontent.com/103586/87643809-3ab68d80-c743-11ea-8551-9b412a7b41b8.png">
3. Finally, can you press the Test Notification button under Settings > Notifications to see if the brings a notification up?

**Comment by kcinman11358** [comment]
Sure

1) 
![image](https://user-images.githubusercontent.com/7409848/87683634-ee6d4c80-c746-11ea-85a4-4c63ece58631.png)
2) 
![image](https://user-images.githubusercontent.com/7409848/87683680-fd53ff00-c746-11ea-91d3-c95db0a1cecc.png)
3) 
![image](https://user-images.githubusercontent.com/7409848/87683713-0644d080-c747-11ea-82ba-f78a51198a65.png)

I know that there used to be a way to test app specific notifications coming in. This helped troubleshoot for me on wavebox 4. Anything like that available?

**Comment by Thomas101** [comment]
Yeah, there are a few extra logs we can get out and some diagnostics we can generate which might help narrow down the problem.

Can you drop support a quick message at http://wavebox.io/support with a reference back to this and I'll pick it up there

**Comment by kcinman11358** [comment]
sure thing. ticket has been created

thanks
