### ISSUE TITLE
Slack doesn't recognize it's logged in

### ISSUE THREAD

**Issue by Lucent** [wavebox/waveboxapp#1255]
Since switching to the beta, Slack does not recognize it's logged in despite being so. Red exclamation mark always appears by its icon. Attempting to log in again does not open a window. Hide allows it to work fine.

* Wavebox Version: 10.0.195.3
* Operating System & Version: Windows 10 2004
* Account type (if applicable): Slack

**Comment by Thomas101** [comment]
Thanks for reporting. We had a couple of reports about this at roughly the same time, but having tested here it seems to work again. Would you be able to give it another try to see if it was just a glitch with Slack?


If it doesn't work, would you be able to try adding the account afresh and during the setup process, pick "Create new cookie profile" and let me know if that works?

**Comment by Lucent** [comment]
I created it in the same cookie profile and had the same problem. Then, I changed the advanced browser setting to allow 3rd party cookies, created it in a new cookie profile, and dragged it back to the original, and it appears to be working for now. I'm not sure which of those two actions resolved the issue.

**Comment by jmicrobe** [comment]
I just had this same issue, and simply using "create a new cookie profile" got it to work 

Wavebox Version: 10.0.283.2 stable
Operating System & Version: MacOS Catalina 10.15.6
Account type (if applicable): Slack

**Comment by tnaseem** [comment]
Not sure, but I seem to be having a similar issue on one of my machines all of a sudden.

Slack keeps signing me out and randomly back in again. I keep getting this message and an exclamation mark on the app icon:

![image](https://user-images.githubusercontent.com/1317345/115804399-06d96880-a437-11eb-87e7-ce52323df1ed.png)

I've tried:
- Remove the app and re-adding it.
- Cleared the app group's cookie container.
- Remove the app and re-add it with its own (new) cookie container.

But this issue keeps coming back.

**Comment by tnaseem** [comment]
Ok, so it's now also happening on my Mac (original issue was on my PC). I'm assuming then this is an issue with Slack itself?

**Comment by Thomas101** [comment]
@tnaseem we've just pushed 10.0.495 out with a fix for this

**Comment by tnaseem** [comment]
That fixed it. Thanks!
