### ISSUE TITLE
Sleep Mode Indication for inactive accounts

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#126]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
KDE Neon (Ubuntu 16.04)

-------

In Issue #80, @TheOddler requested the color ring be removable and that gave me a separate idea that is similar to how the left bar account display works.

Would you be interested in adding a feature to indicate sleep mode?

- a gray indicator on the right side of the account icon
- grayscale overlay on top of icons that are inactive
- gray ring around the account

**Comment by Thomas101** [comment]
I did look at this a little while ago. The thing I tried was a second badge with `zzz` but it looked way too cluttered so I abandoned it. I like the idea of turning the icon grayscale - at least that wouldn't clutter up the UI.

**Comment by MichaelTunnell** [comment]
I had some more thoughts on how this could be done.

- lower the opacity of the icon itself so it becomes darker but doesn't lose color
- overlay a transparent dark bg (#000000 at 50% opacity) with a "zzz" icon centered in the middle.

I think all of the above options would make it work for people who want indication, of course this would need a toggle to disable because some might be bothered by the changing of the icon.

**Comment by Thomas101** [comment]
Hi, this has just been added in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). By default the setting is disabled, to enable it open settings, find the UI section and toggle the `Allow services to indicate when sleeping` switch to be on. Additionally this can also be customized for each account. Thanks!
