### ISSUE TITLE
Feature request, support screen sharing and video calls via Slack

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#1267]
right now Slack allows for calling, but for a video call or screen sharing it's asked to open the SlackApp on Mac

**Comment by Thomas101** [comment]
Screensharing isn't something that's supported in a browser type environment by slack right now.

Video calling should work. It's worth checking that Slack has camera permission, you can find this in the address bar
<img width="350" alt="Screenshot 2020-07-21 at 12 02 33" src="https://user-images.githubusercontent.com/103586/88047860-31199500-cb4a-11ea-979f-ee8da0470ded.png">

If it does have camera permission, check that Wavebox has access to the Camera in System Preferences > Security & Privacy
<img width="780" alt="Screenshot 2020-07-21 at 12 02 58" src="https://user-images.githubusercontent.com/103586/88047904-442c6500-cb4a-11ea-8b27-6238e0dd0394.png">

**Comment by reatlat** [comment]
@Thomas101 TY, make sense
so only one issue, will be grate have a screensharing as GoogleMeet and hangout have

**Comment by nmat** [comment]
According to what I can see at slack now you should be able to share a screen through the browser.

I have not tested it myself right now but it seems like it according to: https://slack.com/intl/en-se/help/articles/115003501303-Share-your-screen-with-Slack-calls

**Comment by reatlat** [comment]
@nmat yes, you are absolutely right, Slack works just fine, TY
