### ISSUE TITLE
Toolbar icons use different colors since last update

### ISSUE THREAD

**Issue by VarunAgw** [wavebox/waveboxapp#1268]
* Wavebox Version: [e.g. 4.0.0] 10
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.15.0, Ubuntu] Win 10
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]

![update](https://user-images.githubusercontent.com/4201835/88817945-c5839780-d1db-11ea-89bb-7b21551d863a.png)

This has started happening since today. Wavebox team doesn't seem to be interested in fixing bugs these days (I have reported several bugs in past which have got no attention). Anyway, I am trying one more time.

**Comment by Thomas101** [comment]
Hi, have you tried restarting the machine to see if it's just a glitch or something that keeps happening?

Can you also generate diagnostics by going to Settings > Advanced and clicking Generate Diagnostics. They take a few moments to generate, but once they have press send to Wavebox and drop support [at] wavebox.io a message so we can pick it from there. Thanks

**Comment by VarunAgw** [comment]
Ok. So the issue is in some internal settings. Setting a different theme than the current one and then switching back to the original theme fixed it.

Do you want to keep the issue open or should be close it? I suspect there must be more peoples who will experience it.
