### ISSUE TITLE
Feature request: Signal Desktop

### ISSUE THREAD

**Issue by mockturtl** [wavebox/waveboxapp#127]
Wavebox rocks!  I would love to have Signal integration.

They currently ship a [Chrome app](https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk?hl=en), but there seems to be [discussion](https://whispersystems.discoursehosting.net/t/google-to-retire-chrome-apps-what-will-be-with-signal-desktop/469/23) around moving to electron.

**Comment by Thomas101** [comment]
Hi, we're collapsing all the new Account/Service requests into a single issue so we can keep track of them more closely. You can find and continue tracking progress from #130. Thanks
