### ISSUE TITLE
Linux - Quick Switch text isn't visible using dark theme

### ISSUE THREAD

**Issue by joshskidmore** [wavebox/waveboxapp#1270]
When using a dark theme in Wavebox, while using Linux, it appears the quick switch background color is always a gray color. When using a dark theme, it makes the subtext impossible to read because it's white text (from theme?) on the gray background.

### Info
* Wavebox Version: 10.0.228-3
* Operating System & Version: Arch Linux using Xmonad as window manager

### Notes
- this does not happen in Windows; a dark theme displays a dark background in the quick switcher
- I have tried multiple Chrome dark themes and all display the quick switcher with this gray background color
- I have tried switching my GTK themes (both ligher and darker variants), and it doesn't seem to make a difference either.

### Screenshot
![quick-switch](https://user-images.githubusercontent.com/255734/89535629-aa5ced00-d7c4-11ea-82a0-1325c9df3298.png)

**Comment by joshskidmore** [comment]
Resolved in version 10.0.231 beta. **Thank you!**

**Comment by Thomas101** [comment]
Whoops, sorry forgot to post the fix here :)
