### ISSUE TITLE
Allow extension hotkeys and/or icons in account sign-in popups

### ISSUE THREAD

**Issue by signe** [wavebox/waveboxapp#1272]
* Wavebox Version: 10.0.252.3-beta
* Operating System & Version: macOS 11 20A5354i
* Account type (if applicable): Any

When logging into an account (or, more often, re-logging-in in the case of Gmail/Gsuite), extension hotkeys and toolbar icons are disabled.  This causes an issue with some extensions, notably 1PasswordX, which a user distinctly _wants_ to use in that particular window.

![image](https://user-images.githubusercontent.com/249456/91089437-68c3a300-e608-11ea-9a6f-95a4aff8a083.png)

In the example image, 1PasswordX instructs the user to use the hotkey Command-Shift-P to unlock the password database.  This can also be accomplished by clicking the extension icon.

Unfortunately, neither of those options exist or function in the popup.  The user must either close the popup and return to the Wavebox window, activate the extension, and then re-open the window, or switch back to the main Wavebox window, activate the extension, and then switch back to the popup.

**Comment by Thomas101** [comment]
Thanks for reporting. This is really down to 1PasswordX, they haven't accounted for the case where sites open a popup window to sign in. It looks like they're listening for the shortcut, but are then unable to open the popup window.

This also presents itself in off the shelf Chrome (dropbox.com -> sign in with Google) as an example. Might be worth reporting on the 1Password forum as it's not something we're able to globally fix https://discussions.agilebits.com/

**Comment by signe** [comment]
Opened in 1Password forums: https://1password.community/discussion/123936/hotkeys-dont-work-in-popup-windows-windows-with-no-toolbars/p1?new=1
