### ISSUE TITLE
Tray icon is missed

### ISSUE THREAD

**Issue by GrigorijST** [wavebox/waveboxapp#1277]
* Wavebox Version: 10.0.275
* Operating System & Version: Linux Mint 19.3

After the last update a tray icon is missed and doesn't appear anymore.

**Comment by Thomas101** [comment]
Hey, if you turn on "Enable support for indicators" under Cinnamon menu > Preferences > General and restart your machine, the indicator should show again :-)

<img width="817" alt="Screenshot 2020-09-11 at 13 07 26" src="https://user-images.githubusercontent.com/103586/92923819-f2a8a400-f42f-11ea-9628-b1348303276b.png">

**Comment by GrigorijST** [comment]
Hi.

After turned on "Enable support for indicators" a icon appears in the tray.

But the same time we have a strange behavior of the icon in the tray.

- By the left click appear a pop up menu instead of opening the program
- Icon duplicates itself continuously (takes up empty space)

See the attached screenshots.

![pop up menu](https://user-images.githubusercontent.com/28841243/92990336-feea3b00-f4db-11ea-96e7-abc2b2775347.png)
![duplicates - empty space](https://user-images.githubusercontent.com/28841243/92990339-0a3d6680-f4dc-11ea-8e3a-02e2b86d99c8.png)
![duplicates - empty space_02](https://user-images.githubusercontent.com/28841243/92990343-0d385700-f4dc-11ea-8f9e-66e7cd7b683c.png)
![duplicates](https://user-images.githubusercontent.com/28841243/92990344-0f9ab100-f4dc-11ea-9443-73bda8703a7d.png)

**Comment by GrigorijST** [comment]
Hi.

It seems that the problem initially is [this](https://github.com/electron/electron/pull/23674)

> Chromium removed the implementation of Tray icons we were using on Linux (GTK + Appindicator backed) in favour of their new DBUS backed implementation.

Regards.

**Comment by hosler** [comment]
one workaround would be to install and use snixembed for app indicators

**Comment by Thomas101** [comment]
There are fixes in Chromium 86 to the tray when used without the dbus interface. We've confirmed that this fixes the tray on Wavebox in Mint 19 & 20. Unfortunately they're too wide reaching to port into 85, but we're working to get this onto our beta channel quickly :-)

**Comment by Thomas101** [comment]
This means on Mint 19, you won't need to enable the "support for indicators" setting and you shouldn't have any of the duplicates :)

**Comment by GrigorijST** [comment]
Ok, will wait fixed beta :)

**Comment by Thomas101** [comment]
Hey, we've just a pushed a fix out for this on our beta channel. Should be working on mint 19 and 20 now :)

**Comment by GrigorijST** [comment]
Hi.
Now everything works well. Thanks ;)

**Comment by nmat** [comment]
My gues then is that this can be closed?
