### ISSUE TITLE
Adding attachment in Google inbox is not working

### ISSUE THREAD

**Issue by jzoric** [wavebox/waveboxapp#128]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10

I have 2 accounts: 

- Google inbox
- Gmail (regular).

**Issue:** It's not possible to add an attachment in Google Inbox.
**Note:** Attachment does work with regular Gmail account.

Can someone confirm this behavior?
Thanks.

**Comment by Thomas101** [comment]
Hi, how are you trying to add the attachment? Through drag & drop or by pressing the attachment button? What's the file extension of the attachment?

**Comment by jzoric** [comment]
Hi, 

- I'm adding the attachment by pressing the attachment button.
- Drag & drop is working
- File extension is `.zip`

**Comment by Thomas101** [comment]
Unfortunately I'm not seeing the same thing here :-(. Are you able to attach something like a png? If you reload Wavebox does this make any difference?

Thanks

**Comment by jzoric** [comment]
I reloaded Wavebox 2-3 times and in the meantime I upgraded to 3.1.6 version.
Everything is working now.
