### ISSUE TITLE
Feature Request: Disable/Enable Profile

### ISSUE THREAD

**Issue by gustavotrott** [wavebox/waveboxapp#1281]
Hello,

I use to separate my apps into Personal and Work profiles.
Sometimes I want to be focused and it would be great if I could disable my Personal profile during some hours.
Then if the profile is disabled I would not see the apps icons in the sidebar.

I didn't found a way to do that in Wavebox. So I would like to see this option in the future!

Thank you,
Gustavo

**Comment by nmat** [comment]
Do you men turning off the profile completely or does the sidebar dividers do what you expect?

https://blog.wavebox.io/tooltip-thumbnails-sidebar-dividers/

You can hide the icons completely with the dividers or you need more?

**Comment by gustavotrott** [comment]
This issue was opened before collapsible divider option.

I think this new feature solve the problem!
Thank you

**Comment by nmat** [comment]
thats wonderful to hear! Hope you like the feature. :-)
