### ISSUE TITLE
[linux] Unable to Update Keybindings via Settings

### ISSUE THREAD

**Issue by joshskidmore** [wavebox/waveboxapp#1282]
* Wavebox Version: 10.0.335-3 beta
* Operating System & Version: Arch Linux

With the latest beta update, the new changes to keyboard shortcuts doesn't seem to work in linux. In settings, any expansion of the shortcut categories ("Application", "View & Display", "Global", etc) just opens a little whitespace underneat with no options (screenshot below).

<img src="https://josh.sh/PjX1.png" />

Going to [chrome://extensions/shortcuts](chrome://extensions/shortcuts) still works though.

**Comment by Thomas101** [comment]
Thanks for reporting, I'll push a fix out to beta for this later today :)

**Comment by Thomas101** [comment]
This is live in the current beta, thanks again!

**Comment by joshskidmore** [comment]
Working for me! Thank you!
