### ISSUE TITLE
Unread notifications do not disappear even after reading and clicking "x"

### ISSUE THREAD

**Issue by mcsauder** [wavebox/waveboxapp#1283]
Reincarnation of #201,

Basic issue is this, after reading the messages and/or clicking on the "x" in the new messages icon, I expect the browser tab status to change and the unread notifications to change, however this does not take place:
![image](https://user-images.githubusercontent.com/2497951/96942802-5bedef00-1493-11eb-8979-ecbb9ab6dea8.png)

I see this issue weekly in Windows 10 and the Chrome browser as well as weekly in Ubuntu 20.04 and the Firefox browser.  It is most annoying.  Let me know what information you need from me to debug.

-Mark

**Comment by Thomas101** [comment]
Hi @mcsauder , it looks like you're having the problem with vanilla Slack on the web and not Wavebox. You're probably best reporting this to Slack directly via their help centre (https://slack.com/intl/en-gb/help).

By the way, we'd love you to give Wavebox a try, although it won't fix this specific problem :-)

**Comment by mcsauder** [comment]
Thanks @Thomas101 .  Agreed!
