### ISSUE TITLE
Youtube video goes blank if you hover over it

### ISSUE THREAD

**Issue by VarunAgw** [wavebox/waveboxapp#1284]
* Wavebox Version: [e.g. 4.0.0] 10 Latest
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.15.0, Ubuntu] Win 10
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]

I don't remember when it exactly started (prolly in the last 2 weeks). But when I hover my mouse over a youtube video, it turns black. Moving the mouse outside the video area fixes it.

**Comment by nmat** [comment]
I am using windows 10 here with wavebox on 2 different machines and have no problem with youtube at all.

Can I ask if you are using any specific plugin or so?

**Comment by VarunAgw** [comment]
@nmat It was an issue at the time of posting. But one of the recent updates has already seemed to fix it.
