### ISSUE TITLE
duplicate notifications for new email

### ISSUE THREAD

**Issue by Fuzzwah** [wavebox/waveboxapp#129]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Windows 10

* Details:

Whenever I get new emails I'm receiving two notifications. It appears that I get one when wavebox gets the message and then a second one when I bring the wavebox window into focus.

**Comment by Thomas101** [comment]
Hi thanks for reporting. I've just tried it my end and unfortunately not seeing the same.

Do the duplicate notifications always come up (e.g. if you wait a minute or so after the first one and then focus is the behaviour different to focusing right away).

How have you unfocused the app? Is it just that you've put another window in front, or have you closed it and then opened it from the tray icon?

Thanks!

**Comment by Thomas101** [comment]
Thanks, that's really helpful! Is this with Gmail, Google Inbox, Outlook etc?

**Comment by Fuzzwah** [comment]
Google Inbox

**Comment by Thomas101** [comment]
@Fuzzwah are you still seeing this in the latest version (3.1.9)?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
