### ISSUE TITLE
Wavebox 10 beta: 28G in crashpad/pending

### ISSUE THREAD

**Issue by EnorMOZ** [wavebox/waveboxapp#1295]
* Wavebox Version: Version 10.0.389.3 beta
* Operating System & Version: [Mac OSX 10.15.7 ]

Wavebox is constantly creating dmp files in `~/Library/Application Support/WaveboxApp/Crashpad/pending`. Every second it is generating 60 dmp files of 97k each.

**Comment by nmat** [comment]
Hello,

Can you provide what applications you have open in the beta version? Also has this happened in the later releases now?

If you change back to the stable branch will it crash then also?

**Comment by Thomas101** [comment]
You should be able to delete (if you already haven't) without any ill effect. Version 10.0.408 beta has a fix for this and it will be rolling onto the stable channel shortly

**Comment by EnorMOZ** [comment]
Sorry was MIA for a while. I've been running stable for a while and haven't had any issues. Currently on 10.0.407.2. When I was running the beta version I had a script what would delete the files to keep up with the space usage.

**Comment by nmat** [comment]
@EnorMOZ does this mean you feel confident enough we can close this issue?

**Comment by EnorMOZ** [comment]
Yes. No issues after updating.
