### ISSUE TITLE
O365 adfs redirect results in blank page

### ISSUE THREAD

**Issue by manicholls** [wavebox/waveboxapp#13]
* Which version of Wavebox are you using? 3.1.2

* Which Operating System are you using? Ubuntu 16.04

As a result, I can't add my account to try out the product.

if you have any suggestions for workarounds please let me know.  thanks!

**Comment by Thomas101** [comment]
Hi @manicholls we'll get ADFS setup our end and test it out. Thanks for reporting

**Comment by Thomas101** [comment]
Does your setup use two factor auth? Do you know if it's on-site or off-site?

**Comment by manicholls** [comment]
No 2-factor auth on this one.   I believe the adfs service is in the same location as me, but I'm not 100% sure on that.

**Comment by nzcoffeem** [comment]
Any updates? I am encountering the same problem.

**Comment by Thomas101** [comment]
Hi this is because Wavebox only supports Outlook & Office 365 accounts, but not Exchange at the moment. We're working on adding exchange support into Wavebox shortly. I'm going to collapse this and a few other issues in one (#268) to make it easier to track progress and compatibility. Thanks
