### ISSUE TITLE
Slack applet is sign out uncontrollably

### ISSUE THREAD

**Issue by greenduck** [wavebox/waveboxapp#1308]
* Wavebox Version: [10.0.493.2 stable]
* Operating System & Version: [Ubuntu 20.04, Linux 5.8.0-50-generic]
* Account type (if applicable): [Slack]

The Slack account is signed out within ~1min.
Gmail account works fine.
---
https://user-images.githubusercontent.com/2223627/115856227-e6101380-a434-11eb-8856-568d2d372559.mp4

**Comment by Thomas101** [comment]
There's a fix in 10.0.495 fix for this

**Comment by greenduck** [comment]
Fixed indeed.
Thank you !

**Comment by nmat** [comment]
this seems to be fixed can it be closed @Thomas101 ?
