### ISSUE TITLE
Add Services to Google

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#131]
So we can keep track of the requests for Service types on Google Accounts we're keeping this list up to date with those requested so far.

**[To help us prioritise which services to add first please cast your vote here](https://docs.google.com/forms/d/e/1FAIpQLSfD_di7BwwIWbwNOGSGKzCsn9Id342-3MfoZHU-qQv6dXUECg/viewform?usp=sf_link).** | [Results](https://docs.google.com/forms/d/e/1FAIpQLSfD_di7BwwIWbwNOGSGKzCsn9Id342-3MfoZHU-qQv6dXUECg/viewanalytics)

- [x] Google Voice
- [ ] Google Meet
- [x] Google Inbox & Gmail under one Account
- [x] Google Plus
- [x] Google Analytics
- [ ] Google Adwords
- [ ] Google Adsense
- [ ] Google My Business
- [x] Custom URL Service
- [x] Google Classroom
- [x] YouTube
- [x] Google Music
- [x] Google Allo
- [x] Google Docs
- [x] Google Sheets
- [x] Google Slides

If you think we've missed one, comment and we can add it to the list

**Comment by MichaelTunnell** [comment]
Having these per Google account would be fantastic, especially Analytics, Adwords, and Voice.

**Comment by Stanzilla** [comment]
+ Hangouts.com would be nice

**Comment by MichaelTunnell** [comment]
> @Stanzilla: Hangouts.com would be nice

Hangouts.com is not a website and Google Hangouts is already included in Wavebox as a service to Google accounts.

**Comment by MichaelTunnell** [comment]
> maybe that should just be renamed to "Google Account" then the other Google services be decoupled from Gmail.

They Gmail and Inbox accounts are currently separated so calling it a Google account wouldn't work right now. They have mentioned in other issues that they are looking into merging them and when that happens your suggestion will likely happen.

**Comment by MichaelTunnell** [comment]
YouTube might be something to reconsider in the way it works in Wavebox right now.

I would love YouTube support in general but I don't think YouTube accounts should be connected to each Google account. The reason is that some people have multiple YouTube accounts they manage but doing so through a single Google account. Having YouTube connected to a Google Account would limit the flexibility of various controls.

What I would love to have is a single YouTube account entry that connects to my YouTube Google account and then add each account as an subaccount like how Calendar and Drive are done with Gmail accounts now.

**Comment by wizpig64** [comment]
With Google Hangouts dropping SMS support soon I'd love to have a proper desktop voice client, thanks!

**Comment by Thomas101** [comment]
@MichaelTunnell definitely see the value in this, will need to put some thought in about how best to do it

**Comment by Thomas101** [comment]
I've added a [voting form](https://docs.google.com/forms/d/e/1FAIpQLSfD_di7BwwIWbwNOGSGKzCsn9Id342-3MfoZHU-qQv6dXUECg/viewform?usp=sf_link) to the original comment. It would be great to know how much demand there is for each service so we can start to prioritise. Thanks!

**Comment by wizpig64** [comment]
It looks like hangouts has now dropped SMS support when using your device's phone number, but still lets you text using your google voice/project fi number. Only a matter of time before they kill this version of hangouts altogether though, judging by Google's track record.

**Comment by amancevice** [comment]
Is it possible to post a link to the real-time results of the polling?

**Comment by Thomas101** [comment]
@amancevice there is a [link](https://docs.google.com/forms/d/e/1FAIpQLSfD_di7BwwIWbwNOGSGKzCsn9Id342-3MfoZHU-qQv6dXUECg/viewanalytics) once you've answered, but I've added it separately too

**Comment by knocktwice** [comment]
I'd really like to see support for Google Cast, if possible. Primarily for audio.

**Comment by Thomas101** [comment]
Hi we've just added support for some of the services above in the latest beta (3.3.4). There's some information on how to switch to the beta channel and download the latest version [here](https://wavebox.io/kb/beta-channel)

**Comment by nmat** [comment]
https://github.com/wavebox/waveboxapp/issues/461

Adding the feature request in here to show classroom implementation from feature and pull request

**Comment by animalphase** [comment]
Regarding Inbox vs Gmail: (came in via this thread: https://github.com/wavebox/waveboxapp/issues/115)

I thought I would like using Inbox more if it was a standalone app… but the folder organization isn't very useable for me. So I'd like to switch over to Gmail. It would be cool to have a way to switch over without having to re-add another account, going through 2-step authentication again, etc.

**Comment by ChaddPortwine** [comment]
I have Gmail _settings_ to enable **Inbox**. Whenever I open a browser to Gmail, I'm taken to Inbox.

**Wavebox: Gmail or Inbox - Flip a Coin**
When I open Wavebox, sometimes Inbox loads, sometimes Gmail loads. Once Gmail loads, I cannot get Inbox to display again (well, sometimes I can navigate back, but not always)

I would like Wavebox to **always** open Inbox. Within Inbox there is a link to Gmail I can use. So I don't see the need for two accounts or a Wavebox/Gmail button (if I open Gmail in a new window)

BTW.... love this product.

**Comment by nmat** [comment]
@ChaddPortwine this sounds a bit like https://github.com/wavebox/waveboxapp/issues/482

Wavebox at the moment does not save last used index/service in that way unfortunately. Of course this is "from what I know" going to be worked on. But at the moment does not save last used.

If this is something else then last used then please tell me. Do you mean last used label inside the gmail account or something? :)

**Comment by ChaddPortwine** [comment]
@nmat I'm not sure what's happening behind the scenes.  Maybe this extra info will help:

When I type `www.gmail.com` into a browser, google looks me up and forwards me to `https://inbox.google.com/u/0/` automagically, because of my Gmail settings.

In Wavebox Settings\Accounts I have that Gmail account (G Suite really) added. Wavebox (like my browser) sometimes shows Inbox, e.g., google redirected to inbox. Other times Wavebox shows traditional Gmail, like it didn't get the redirect.

Sometimes, when I click on Wavebox Gmail and **do not** get Inbox, I can View\Navigate Back, which might load Inbox.

Maybe `save last used index/service` will help. Not sure.

**Comment by Thomas101** [comment]
It sounds like you might have added the account as a gmail account and are now trying to use it as an inbox account. The best thing to do is remove the account and re-add it again to Wavebox, but this time picking Google Inbox from the add screen.

When you tell gmail to always redirect you to inbox, the only thing we can do is ask gmail not to by using a query on the end of the url, e.g. `https://mail.google.com?ibxr=0`. This mostly works, but if you ever end up navigating back or reloading gmail the query on the end wont be added which is why it forces you back to inbox.

**Comment by ChaddPortwine** [comment]
This is **USER ERROR** on my part.

@Thomas101, you are correct. I missed the Inbox option when setting up the account. Adding a Wavebox Gmail account that has Inbox enabled is not recommended (and is dumb :).

Thank you for suggesting to delete the account and start over.

**Comment by Thomas101** [comment]
Google Voice coming in the next beta

**Comment by Thomas101** [comment]
Google Voice has just gone out in the beta channel of Wavebox in version 3.13.1

**Comment by ammmze** [comment]
Any chance of getting media keys support for Google Play Music? To invoke play/pause, prev/next track from the keyboard?

**Comment by nmat** [comment]
@ammmze does the media keys work in the browser version of google play music?

I mean if you use for example chrome?

**Comment by wizpig64** [comment]
@ammmze @nmat I use this chrome extension to add media keys to GPM and other sites: https://chrome.google.com/webstore/detail/media-keys-by-swayfm/icckhjgjjompfgoiidainoapgjepncej

Also, [GPMDP](https://www.googleplaymusicdesktopplayer.com/) supports media keys on the desktop.

**Comment by ammmze** [comment]
Yea... i've been using GPMDP, but lately its been crashing on me after running for a bit, and i've seen the extensions. So I figured I'd look into running it in wavebox since there's an app for that and would allow me to run fewer independent apps.

**Comment by silfreed** [comment]
Would this be the right ticket to request something like Youtube Music be added as a "google service"?

**Comment by Thomas101** [comment]
In newer versions of Wavebox, you can add an account to a group by right-clicking on the account or in the top toolbar and picking `Add another service`. This twinned with the ability to add any web URL to the mix, makes the current version of Wavebox more flexible for configuring accounts that work for you.

Because of this, this issue is less relevant, so I'm going to close this off for now, but if you still feel like there's something missing or that needs improvement, feel free to re-comment or open another issue and we'll take another look.
Thanks!
