### ISSUE TITLE
No notifications showing in ubuntu gnome.

### ISSUE THREAD

**Issue by pkgodara** [wavebox/waveboxapp#132]
version of Wavebox : 3.1.5(latest)
Operating System: Ubuntu (Gnome) 4.8.0-51

Notifications not showing when new emails arrive in ubuntu gnome but works in unity. I installed it using .deb package.

**Comment by MichaelTunnell** [comment]
- Do you have libnotify installed?
- Is the issue at all times or just when in sleep mode?

**Comment by pkgodara** [comment]
I have installed it but didn't help. Along with it, icon is also missing
from top right bar. It happens all the time. I don't get any notifications.

**Comment by MichaelTunnell** [comment]
which GNOME extensions do you have installed and which version of Ubuntu GNOME is it?

**Comment by Thomas101** [comment]
If you go to View > Developer Tools and click on the console tab then paste...

```js
new Notification("test")
```

do you see a notification show up?

**Comment by pkgodara** [comment]
I reinstalled the app and it started working out of nowhere..... Working good.
