### ISSUE TITLE
resume downloads crash webflow

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#1346]
macOS 11.4
latest wavebox 10.0.548.3.beta

to reproduce
1. disconnect Internet to brake downloads, 
2. reconnect internet
3. click on downloaded file to resume download,
4. wavebox crash instantly

![image](https://user-images.githubusercontent.com/9933516/121957973-63844000-cd63-11eb-8e58-899320c87e71.png)

**Comment by Thomas101** [comment]
Thanks, there's a fix in the next beta!

**Comment by reatlat** [comment]
@Thomas101 in new Beta the issue is resolved, TY
