### ISSUE TITLE
Extension HubX (by Neambo) not work

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#1347]
the extension HubX (by Neambo) not work on wavebox but works ok on chromium or chrome

- https://chrome.google.com/webstore/detail/hubx-by-neambo/dmgpiodabbkeicgkhpokecnlpjddjmah?hl=en

**Comment by Thomas101** [comment]
It might be that the extension struggles with the cookie containers. You can lock it into a single container which might help.

1. Open chrome://extensions
2. Locate HubX
3. Disable "Run in all cookie containers"
4. Change the container to the one you want to use it on

If that doesn't work, is it that the button doesn't appear in hubspot, or is it when you click on it, it doesn't copy the groups/modules across?

**Comment by reatlat** [comment]
@Thomas101 TY, your solution works for me,

Just in case its return me this error on front end after I try to copy element

<img width="741" alt="Design Manager | HubSpot 2021-06-16 03-17-58" src="https://user-images.githubusercontent.com/9933516/122143291-7d03b580-ce51-11eb-8213-69885dab5411.png">

and this  report I got on web console

<img width="841" alt="Design Manager | HubSpot 2021-06-16 03-16-35" src="https://user-images.githubusercontent.com/9933516/122143255-68272200-ce51-11eb-884d-8f56afedfb6a.png">

In case this is not a temporary solution, I think we can close issue :)

TY so much

**Comment by Thomas101** [comment]
Thanks! It's probably making requests to Hubspot from the extensions background page and expecting it send the cookies along with it. By default, this will be out of the default cookie container, but if Hubspot is in a different container, then these won't be present.

Setting the cookie container for the extension, scopes the it to just that container, so any requests from background pages, content scripts etc should be sent as expected :)
