### ISSUE TITLE
Any chance to enable a ppa for ubuntu?

### ISSUE THREAD

**Issue by arooni** [wavebox/waveboxapp#135]
That way I wouldn't have to download each release manually.

Keep up the great work!

**Comment by Thomas101** [comment]
Hi, I was really hoping to put some time into the updates for linux in the 3.1.6 release but have had to let it slip back a release. It's top on my priority list now though and really hoping to get something into the 3.1.7 or 3.1.8 release! 

Also #48 #27

**Comment by Thomas101** [comment]
Hi, we've just added support for distributing Wavebox through snap packages and an apt-repository. You can find instructions on how to get this on the download page http://wavebox.io/download.

**Comment by MichaelTunnell** [comment]
> Hi, we've just added support for distributing Wavebox through snap packages and an apt-repository. You can find instructions on how to get this on the download page http://wavebox.io/download.

VERY NICE!

I am very happy to see a Snap release for Wavebox.

I'd also suggest considering an AppImage though that doesn't solve the updating issue but it does solve ease of use for people on non-snap enabled distros. Either way, Snap is a great thing to have and with or without an AppImage this is a welcomed improvement. Thanks.

**Comment by Thomas101** [comment]
AppImage is on the list #34, I think there is squirrel-like support for updates with that too!

**Comment by akashnimare** [comment]
@Thomas101 I'm looking to set up an apt repo for one of my electron desktop client. I have already built a .deb installer using electron-builder. Could you please link a good blog post or something to achieve the same?
