### ISSUE TITLE
Outlook 365 Notifications - HTML Parsed Please

### ISSUE THREAD

**Issue by davedew** [wavebox/waveboxapp#1350]
Notifications from Outlook 365 get a bunch of raw HTML in them and appear poorly formatted much of the time.  Anyway we can get these cleaned up or parsed?  Could also maybe just strip all HTML tags from notifications.

**Comment by Thomas101** [comment]
Thanks for reporting, it would be good to get some more info so we can try to reproduce it...
1. Which version of Wavebox are you using?
2. Which OS are you using?
3. Do you have an example email you can send to support [at] wavebox.io, or a newsletter we can sign up to that exhibits this behaviour?

**Comment by davedew** [comment]
Thanks for the reply.  I'll get a sample as soon as I can, here are answers to your other questions:

1. Version: 10.0.554-2 stable / Install Method: deb / Wire Config: 1.2.14 / Chromium: 91.0.4472.114
2. Ubuntu (Presents in both Gnome and KDE Plasma)
3. As soon as I see one I'll send.

**Comment by davedew** [comment]
Ok well I guess its not HTML, my bad on that... Outlook wraps its text in brackets...  Anyhow, Here are some screen shots of what a standard Outlook notification comes in like, then what Wavebox does.  Is there a way I can turn off Wavebox notifications but still get the Outlook browser notifications and the tray icon?

Email:
![wavebox-email](https://user-images.githubusercontent.com/3160839/125122043-749e4380-e0ba-11eb-9ee4-81583b1d0a3e.jpg)

Wavebox Default Notification:
![wavebox-notification-outlook-full](https://user-images.githubusercontent.com/3160839/125122045-749e4380-e0ba-11eb-9604-3672f4e58d80.jpg)

Outlook Browser Notification:
![wavebox-notification-outlook-simple](https://user-images.githubusercontent.com/3160839/125122047-7536da00-e0ba-11eb-9a3a-613e9df1808d.jpg)

**Comment by Thomas101** [comment]
You can turn off notifications from Wavebox under App Settings > Badges & Notifications. You can also turn on outlook desktop notifications in the outlook settings. Although this isn't really a configuration we fully support.

Is there anything we can do to improve the notifications Wavebox generates? The next version will strip out the <email@address> portion of the title as I don't think is needed

**Comment by davedew** [comment]
Thanks for the reply.  I'm not seeing that option.  I see the option to mute all notifications, but not turn them off.  In my settings I have separate **Notifications** and **Tray** sections not a **Badges & Notifications**.  Am I in the wrong place?

Muting the notifications changes my tray icon to the crossed out bell icon.  :(

I think for the future, it would be really nice to have a toggle between rich notifications and simple.  Maybe even on a per app basis if possible.  Would love for the notifications to look simple like the default Outlook notification.  Sometimes I get 4 or more emails at the same time, and with the large/long notifications from Wavebox, it takes up the whole screen.

Thanks for the help and consideration!

![Screenshot_20210714_082029](https://user-images.githubusercontent.com/3160839/125629398-5091b7b0-566b-4545-96f2-8e15236da280.png)

**Comment by Thomas101** [comment]
Notifications there are global for the whole of Wavebox, each app within it has its own set of notification settings. If you click on "Groups and apps" along the top, locate your outlook app, there's an option there where you can turn notifications off just for outlook

**Comment by davedew** [comment]
Got it, thank you very much!!
