### ISSUE TITLE
Trying to create new mail from Contacts preview results in chrome windows

### ISSUE THREAD

**Issue by ToxMox** [wavebox/waveboxapp#137]
* Which version of Wavebox are you using? 3.1.6

* Which Operating System are you using? Windows 10 x64

I go to Google Contacts (New preview version). I click on one of my contact groups. I select all the contacts in the group then click the email button on top. This creates two new Google Chrome tabs outside of Wavebox instead of starting a new Email in Wavebox.

**Comment by Thomas101** [comment]
Thanks! I'll look at capturing the url

**Comment by twistedspur** [comment]
I get something similar if I try to click on an email address in the body of an email. (eg someone has sent me an email address - "email this guy at xxx@xxx.xx")

Wavebox v3.1.7 and Windows 10 x64

When I click on the email address within the body text, the entire email opens in a new window. Then, when I click again on the email address, the first time I was offered a dialogue box asking which application I wanted to use to click the link (Chrome default, Wavebox as an option). I checked the Wavebox option and everything worked fine, including offering me which account I would like to send the email from.

But I chose the wrong account, so started again. Again, I get the email opening in a new window. But when I click the email address, I instead get automatically sent to Chrome, which just opens a blank window.

**Comment by Thomas101** [comment]
Hi, this should be fixed in 3.1.8. Thanks for reporting!

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
