### ISSUE TITLE
Shortcut key for Global search (in app)

### ISSUE THREAD

**Issue by nadavl** [wavebox/waveboxapp#1397]
* Wavebox Version: 10.108.19.2 stable

### Bug/Feature description
I would love an option to set a keyboard shortcut to open the global search (magnifier on top right corner) while in the app.

Tnx!

**Comment by Thomas101** [comment]
Hi, Alt+S (Linux & Windows) and Ctrl+S (macOS) are mapped by default for this. You can also change the keyboard shortcut under Settings > Keyboard shortcuts > Wavebox features > Open global search

**Comment by nadavl** [comment]
Thanks! You're a lifesaver :) 
I was trying the find bar in the settings for "global" and "search", but somehow this field isn't searchable :)

**Comment by Thomas101** [comment]
Yeah, the search in settings is a bit... rubbish at the moment. The beta channel of Wavebox has a completely new search framework and is so much better. It should be shipping out next week :)
