### ISSUE TITLE
Feature Request: Go-to specific account from menubar

### ISSUE THREAD

**Issue by andersodt** [wavebox/waveboxapp#14]
* Which version of Wavebox are you using? 3.1.2

* Which Operating System are you using? Mac

It would be very convenient for me to be able to click on my e-mail address in the menubar menu and go to that account, without having to click a specific message or the generic "Show/Hide"

**Comment by Thomas101** [comment]
Hi there is access from the window menu and cmd+number shortcuts but not the tray at the moment. I don't think I can add a click event to the menu item, but could certainly add an open option at the top of the list. Would that work?

**Comment by andersodt** [comment]
I suppose that would work! I've always been a fan of MailPlane's approach (to avoid drilling into menus, clicking on "Personal" would bring me to the proper mailbox), but I understand how that might get overwhelming if there were a lot of accounts/emails. 

<img width="382" alt="screenshot 2017-04-06 12 02 18" src="https://cloud.githubusercontent.com/assets/1243035/24766445/f9cc7960-1ac0-11e7-9578-908a01c6c666.png">

**Comment by jacksarick** [comment]
I'd be willing to implement this, it seems like good idea.

**Comment by Thomas101** [comment]
Would happily accept a pull request if you want to speed it up! `renderContextMenu` in [Tray.js](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/mailboxes/src/Components/Tray/Tray.js) is where it all happens :)

**Comment by Thomas101** [comment]
Hi this has just been released in 3.1.3. Wavebox will autoupdate shortly or if you want to get it sooner you can either re-launch Wavebox to trigger an autoupdate or redownload from https://wavebox.io/download Thanks & thanks again @jacksarick for the pull request!

**Comment by andersodt** [comment]
Thank you very much @jacksarick, this is great!
