### ISSUE TITLE
Moving up a tab to Nth position places it on N-1th, when N>2 and using webdock Explorer

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1401]
* Wavebox: 10.110.18-2 stable
  * Install Method: rpm
  * Wire Config: 1.2.14
  * Chromium: 110.0.5481.97
* Operating System & Version: Fedora Workstation 37

### Bug/Feature description

[Screencast from 2023-02-17 10-14-57.webm](https://user-images.githubusercontent.com/28209361/219524878-bd246e2b-e36c-437f-a1c0-e34065ccd122.webm)

### Steps to reproduce (if applicable)

1. Turn on 'Webdock Explorer' mode
2. Open three tabs
3. Move the third tab to the second position.

**Comment by lens0021** [comment]
This is happening when moving across groups too.

[Screencast from 2023-02-17 11-35-02.webm](https://user-images.githubusercontent.com/28209361/219535109-d249ce54-0756-497e-ba25-49724b285e78.webm)

**Comment by Thomas101** [comment]
Thanks, I've put some fixes in for this that will go in the next release 👍
