### ISSUE TITLE
Moving an app from horizontal bar to a group on Webdock explorer results placing it the belew group

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1402]
* Wavebox: 10.110.18-2 stable
  * Install Method: rpm
  * Wire Config: 1.2.14
  * Chromium: 110.0.5481.97
* Operating System & Version: Fedora Workstation 37

### Bug/Feature description

[Screencast from 2023-02-17 10-29-25.webm](https://user-images.githubusercontent.com/28209361/219526514-4d8aa01a-1948-4f24-a427-62a817fc0d93.webm)

### Steps to reproduce (if applicable)

1. Create two groups.
2. Add an app to a group.
3. Turn on Webdock List view
4. Activate the group has an app
5. Drag the app from the horizontal bar to another group on the Webdock list.

And you can see the user experience is not on the very good state on the video I attached.

**Comment by Thomas101** [comment]
Thanks for reporting, there are some fixes going out for this in the next version 👍
