### ISSUE TITLE
The word is missing when searching in address bar, but the search engine app is sleeping

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1403]
* Wavebox: 10.110.18-2 stable
  * Install Method: rpm
  * Wire Config: 1.2.14
  * Chromium: 110.0.5481.97
* Operating System & Version: Fedora Workstation 37

### Bug/Feature description

[Screencast from 2023-02-17 10-40-49.webm](https://user-images.githubusercontent.com/28209361/219528132-620acaea-090b-41b3-9eeb-32765ec2d51b.webm)

### Steps to reproduce

1. Create an app for the search engine. In my case, it is Google.
2. Create another app.
3. Create a link opening rule, for opening a google link on the google app. ![image](https://user-images.githubusercontent.com/28209361/219528112-f42492f9-eca2-4135-afe5-c057a06b5118.png)
4. Make the app created on the step 1 (Google) sleeping.
5. Type any word/sentence in the address bar.
6. Press Alt + Enter.
7. The word/sentence is gone.

**Comment by Thomas101** [comment]
I'm having a little bit of trouble reproducing the same here, all be it my setup is a bit simpler.


https://user-images.githubusercontent.com/103586/219652929-e06f22fc-d0da-42d8-8a7e-020e032c0a6b.mov

<img width="1162" alt="Screenshot 2023-02-17 at 12 24 06" src="https://user-images.githubusercontent.com/103586/219653016-aebdffc7-2b44-416a-a2dc-c392626fe4eb.png">

It would be good to know a little bit more about your setup to see if I can reproduce here...

* I noticed that your Google app is on GitHub, have you just navigated away? Does hitting the home button on this and trying again give a different result?
* When you added the Google app, did you use the Google App in the app store, or did you create a custom web app?
* What's your search engine set to under Settings > Search?
* Do you have any search based extensions installed?

**Comment by lens0021** [comment]
> I noticed that your Google app is on GitHub, have you just navigated away? Does hitting the home button on this and trying again give a different result?

I can reproduce it when the Google app is on google.com:

[Screencast from 2023-02-17 21-48-25.webm](https://user-images.githubusercontent.com/28209361/219657515-bf522e0b-2011-4382-b38d-b2ada0220d63.webm)

> When you added the Google app, did you use the Google App in the app store, or did you create a custom web app?

It seems I am using Google App in the app store. As a result, adding another Google App is not possible:

![image](https://user-images.githubusercontent.com/28209361/219658104-0065fbc0-1b03-4a91-9bd8-1a08156c34aa.png)

> What's your search engine set to under Settings > Search?

![image](https://user-images.githubusercontent.com/28209361/219658284-f1eeb601-cb6f-4930-be63-b3d1232a0bda.png)

>Do you have any search based extensions installed?

I turned off my all installed extensions and it has reproduced:

[Screencast from 2023-02-17 21-57-53.webm](https://user-images.githubusercontent.com/28209361/219659232-5ca31070-6124-4b4f-887e-1b54efff4d6b.webm)

But in my another profile it is not reproduced:

[Screencast from 2023-02-17 22-04-21.webm](https://user-images.githubusercontent.com/28209361/219660416-da1c915b-1c23-4029-ae20-df8867914bb3.webm)

Could you tell me more possible scenarios to try?

**Comment by lens0021** [comment]
I will test this on my MacBook later...

**Comment by Thomas101** [comment]
I've managed to reproduce it here. It's when you're not in the default partition. I'm just looking into a fix now

**Comment by Thomas101** [comment]
Fix in the next version 👍
