### ISSUE TITLE
Divider deleted when a group is moved above it on Webdock Explorer

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1404]
* Wavebox: 10.110.18-2 stable
  * Install Method: rpm
  * Wire Config: 1.2.14
  * Chromium: 110.0.5481.97
* Operating System & Version: Fedora Workstation 37

### Bug/Feature description

[Screencast from 2023-02-17 11-21-57.webm](https://user-images.githubusercontent.com/28209361/219533328-7924ac13-55aa-4a9b-b384-cf1b264d413a.webm)

### Steps to reproduce (if applicable)

1. Create a group and a divider.
2. Place the group below the divider.
3. Switch to Webdock Explorer mode if not.
4. Move the group above the divider.
5. The divider is removed.

**Comment by Thomas101** [comment]
Thanks, fix going in the next version 👍
