### ISSUE TITLE
A new unpinned tab can locate above a pinned tab when link clicked on Webdock Explorer

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1405]
* Wavebox: 10.110.26-2 stable
  * Install Method: rpm
  * Wire Config: 1.2.14
  * Chromium: 110.0.5481.104
  * OS: linux/undefined
* Operating System & Version: Fedora Workstation 37

### Bug/Feature description

[Screencast from 2023-02-23 20-13-09.webm](https://user-images.githubusercontent.com/28209361/220890715-2eecd575-b06c-421e-bc8a-9b0dc970ab4c.webm)

* Expected behavior: I think all unpinned tabs should be under the pinned tabs.

### Steps to reproduce

1. Pin tabs.
2. Select a pinned tab, but not the last one.
3. Open link in new tab.

If this is normal, feel free to close this issue.

**Comment by Thomas101** [comment]
Thanks, fix in the next version!
