### ISSUE TITLE
Dragging & dropping apps of a group makes random movement in webdock explorer

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1406]
Wavebox: 10.110.26.2 stable
Install Method: dmg/universal
Wire Config: 1.2.14
Chromium: 110.0.5481.104
OS: darwin/undefined
```console
% sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
```

### Bug/Feature description

![Kapture 2023-02-24 at 14 23 44](https://user-images.githubusercontent.com/28209361/221099470-71a9af26-e52d-42b6-a87c-ac88142ceb8a.gif)

### Steps to reproduce

- Create a group
- Add apps to the group
- Drag & drop an app

**Comment by Thomas101** [comment]
From the looks of it when you drag Notion down, it doesn't show the drop area (the dotted box), which means it thinks you're trying to drop Notion into Slack. This isn't allowed so it just places it back where it was.

Admittedly this could be much better, but it's one of the limitations of the drag-drop library we're using at the moment

**Comment by lens0021** [comment]
Apologies for the video. I've missed the bug. Retry:

[Kapture 2023-02-24 at 19.09.48.webm](https://user-images.githubusercontent.com/28209361/221152091-ff6c859b-11c8-4053-98a6-63ff84722473.webm)

**Comment by Thomas101** [comment]
Oh yeah, thanks I see what you mean. Fix in the next version :)
