### ISSUE TITLE
'Opening the previous page in new tab' triggers the rule for current page

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1407]
* Wavebox Version:
```
Wavebox: 10.110.26-2 stable
Install Method: rpm
Wire Config: 1.2.14
Chromium: 110.0.5481.104
OS: linux/undefined
```
* Operating System & Version: Fedora Workstation 37

### Steps to reproduce (if applicable)

1. Create two apps, for example, GitLab and GitHub. (I have chosen marketplace apps).
2. Create a link open rule between them.
3. Prepare a link across the sites. For instance, https://gitlab.com
4. Click the link. Then the current tab turns to GitLab, as expected.
5. Press the middle button of the mouse on the back button of the browser.
6.
    - Expected behavior: A new GitHub tab should be opened in the GitHub app.
    - Actual result: A new GitHub tab opens in the GitLab app.

**Comment by Thomas101** [comment]
Hi, what does the link open rule look like under Settings > Link opening > Customize link open rules? From all the combinations I've tried here, the back button should be disabled after clicking the link

**Comment by lens0021** [comment]
I had a bad rule. I am sorry for wasting your time.
