### ISSUE TITLE
[Explorer Layout] Tabs from other devices are not clickable

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1411]
* Wavebox: 10.111.36-3 beta
* Install Method: rpm
* Wire Config: 1.2.14
* Chromium: 111.0.5563.64
* OS: Fedora workstation 37

### Bug/Feature description

[Screencast from 2023-03-29 12-10-43.webm](https://user-images.githubusercontent.com/28209361/228417091-80e7b6b0-f3f3-4eca-94b6-c3576ea39521.webm)

**Comment by Thomas101** [comment]
Thanks! Fix in the next version 👍
