### ISSUE TITLE
Strange notification count (ms teams)

### ISSUE THREAD

**Issue by jeka** [wavebox/waveboxapp#1417]
* Wavebox Version: 10.114.7-3
* Operating System & Version: Ubuntu 22.04 (KDE neon)

### Bug/Feature description
The notification count shown for some chats in MS Teams is strange.

I am attaching screenshots taken from wavebox, google-chrome, and an unofficial  MS Teams client for Linux (electron app)
I've noticed it multiple times and I believe it always happens in a 'meeting' chat window (marked on the screenshots)

Electron app:
![teams-electron-app](https://github.com/wavebox/waveboxapp/assets/181360/75103f42-d15c-4fa7-aa60-392e0abc8848)

Google Chrome:
![teams-google-chrome](https://github.com/wavebox/waveboxapp/assets/181360/5e582302-c68b-43a4-8e4b-bad89d8573ea)

Wavebox:
![teams-wavebox](https://github.com/wavebox/waveboxapp/assets/181360/18a357c3-9339-4f3d-aafb-97668846b78b)

**Comment by jeka** [comment]
I forgot to mention that this count is shown only if that particular chat window is focused. If I move away from it the count is cleared.

**Comment by jeka** [comment]
I just realized that this count on the badge (3020k) maybe is because of wrongly parsing the number in the chat title (03020609) as a notification count.

**Comment by jeka** [comment]
After 2 weeks and a couple of wavebox updates, the problem described above still persist.

**Comment by Thomas101** [comment]
It would be helpful to generate some diagnostics so we can find out why it's not fixed for you. Can you send support@wavebox.io an email and we'll see if we can get to the bottom of it
