### ISSUE TITLE
[Feature Request] Options to Tab/App Quit behavior

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1422]
### Feature description

I want to choose the behavior when I closed a tab. Currently, it seems:

* When closing a tab which belongs to an app with multiple open/sleeping tabs, another recent tab is opened/resumed.
* When closing a tab which is an only tab in the app,
	* the below app is open
	* if the app is at bottom, the latest app is open
	* or 'This app is sleeping' page is shown. I don't know when this happens

Here is a list of example behavior:

- When closing all tabs in an app
	- Open the recent app
	- Show 'This app is sleeping' page
	- Open below app
	- Open above app
	- etc
- When closing a tab in an app:
	- Open the recent tab
	- Open another tab in an app (if exist)
	- Open the app itself.
	- etc

Thank you.

**Comment by Thomas101** [comment]
This can already be changed under Settings > Advanced > Advanced Flags > When closing a tab what should be selected next

**Comment by lens0021** [comment]
Oh, I didn't know that. Thank you!
