### ISSUE TITLE
'As tabs in the current window' option of workspace shortcut is broken

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1423]
Wavebox: 10.115.27-2 stable
Install Method: rpm
Wire Config: 1.2.17
Chromium: 115.0.5790.171
OS: Fedora workstation 38

### Bug/Feature description

This is happening since someday.

The option 'As tabs in the current window' of a shortcut on workspace is not working, and the workspace tap is replaced. 

[Screencast from 2023-08-10 14-45-36.webm](https://github.com/wavebox/waveboxapp/assets/28209361/0d08f934-9add-4f7e-be0e-2a9ddae99a54)

**Comment by Thomas101** [comment]
Thanks for reporting, there's a fix for this on the beta channel and it will be going out to stable with the next version 👍

**Comment by lens0021** [comment]
Fixed. Thank you!
