### ISSUE TITLE
Bug: Address bar is still partially displayed  when set to "off" in Wavebox settings

### ISSUE THREAD

**Issue by maerteijn** [wavebox/waveboxapp#1431]
* Wavebox Version:10.116.8.2 stable
* Chromium: 116.0.5845.111
* OS: MacOS 12.6.8

### Bug/Feature description
When you choose to hide the address bar in the wavebox settings, the address bar including some icons is still partially showed:

![image](https://github.com/wavebox/waveboxapp/assets/121401/f724ee9a-3fb2-45ff-adbb-c666275f23db)

### Steps to reproduce (if applicable)
Go to the settings -> appearance and deselect "Show address bar".

**Comment by maerteijn** [comment]
I just downgraded to `Wavebox: 10.115.27.2` where this issue is not the case.

**Comment by Thomas101** [comment]
There's also a fix for this on the [beta channel](https://wavebox.io/beta) which will be rolling out in the next release

**Comment by maerteijn** [comment]
This was fixed in `10.116.10`
