### ISSUE TITLE
[Feature request] Navigator and Global Search on compact title bar

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1432]
* Wavebox Version: 
```
Wavebox: 10.116.10-2 stable
Install Method: rpm
Wire Config: 1.2.17
Chromium: 116.0.5845.141
OS: linux/undefined
```
* Operating System & Version: Fedora Workstation 38

### Bug/Feature description

The Navigator and Global Search icons are not shown on the compact title bar. Would thoes be added, at least an opt-in option?

Not compact title bar:
![image](https://github.com/wavebox/waveboxapp/assets/28209361/9dc125ba-bf00-48d5-a434-bcf62da92ac4)

Compact title bar:
![image](https://github.com/wavebox/waveboxapp/assets/28209361/a9981fd1-f5e0-415f-8618-30c40006cad6)

**Comment by Thomas101** [comment]
Global search is already there (it's the 3rd from the right in your screenshot).

We didn't want to crowd the toolbar too much with all the icons as it quickly starts to eat the screen space taken by the addressbar and extensions. Navigator is available under the menu button to the right and also in the bottom-left of the main Wavebox window.

**Comment by lens0021** [comment]
I understand, thank you!
