### ISSUE TITLE
Widgets on workspace are not clickable

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1447]
Wavebox: 10.119.8-2 stable
Install Method: rpm
Wire Config: 1.2.17
Chromium: 119.0.6045.124
OS: Fedora Workstation 38

### Bug description

[Screencast from 2023-11-14 18-37-01.webm](https://github.com/wavebox/waveboxapp/assets/28209361/b04bbd8d-832c-40df-81e2-3e856c19d780)

**Comment by Thomas101** [comment]
Thanks for reporting 👍. It looks to be an issue with just the single app/link widget. I have a build running with a fix and this should go out to our beta channel later on today.

**Comment by lens0021** [comment]
Hi, is there a plan for the next stable release? I am not using the beta version at work, since https://www.reddit.com/r/waveboxapp/comments/12tr5qi

**Comment by lens0021** [comment]
Confirmed that the issue disappeared in the latest stale version. Thank you!

**Comment by Thomas101** [comment]
👍
