### ISSUE TITLE
Pinch zoom on fedora

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1449]
* Wavebox Version: 10.120.10-2 stable
* Operating System & Version: Fedora Workstation 38

### Bug/Feature description

Wavebox does not seem to support the pinch zoom on Fedora, while Firefox and [Gnome Web](https://wiki.gnome.org/Apps/Web) do.
(Chrome doesn't)

### Steps to reproduce (if applicable)
Using Laptop, try pinch zoom.

**Comment by Thomas101** [comment]
Some other Chrome users have reported that this works, it should be the same in Wavebox...

1. Open wavebox://flags in a new tab
2. Search for "Ozone platform" and change it to "Auto" or "Wayland"
3. Restart and see if it works after this

**Comment by lens0021** [comment]
It works, thank you!
