### ISSUE TITLE
Option to not sleep when there's sound playing in a tab

### ISSUE THREAD

**Issue by l4kr** [wavebox/waveboxapp#1450]
Hi!
I think it's pretty common that people open up a YouTube (or any streaming service) tab and play one of these long playlists with music on background.

However, I have the default 15 min timeout for sleep. It can be a bit inconvenient when music stops playing "out of nowhere".

Of course, I could prevent YouTube from sleeping (either by having it boosted as an app and disabling sleep or exclude the URL in settings. But most of the time I do want it to sleep, just not when I'm playing videos in background.

**Comment by Thomas101** [comment]
Hi, it shouldn't sleep tabs when there's sound playing, it should auto-extend the sleep time until it's stopped. Can you reach out to support@wavebox.io, so we can generate some diagnostics to see if there's anything else at play and also see if can put some reproducible steps together here so we can try to debug the issue? Thanks!

**Comment by l4kr** [comment]
Hi!
I haven't been able to reproduce the issue for now. I will contact support@wavebox.io if I come across these issues again.
Closing.
