### ISSUE TITLE
Extension Fails to Change Titlebar Color of Installed App as Expected

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [wavebox/waveboxapp#1452]
I attempted to install it both as an app and by creating a shortcut, but there was no noticeable change. The extension in question is ColorfulPWA, and it successfully alters the titlebar color when used in the Edge Browser.

![image](https://github.com/wavebox/waveboxapp/assets/44755101/a69248fa-4565-4480-be5a-a6082e8294c2)

**Comment by Thomas101** [comment]
Hi, you can already do this in Wavebox, without the need for an extension.

1. Open wavebox://apps in a new tab
2. Right-click on the app you want to change > settings
3. Change the app color

<img width="1199" alt="Screenshot 2024-01-24 at 09 24 48" src="https://github.com/wavebox/waveboxapp/assets/103586/5711610e-f5f1-4df0-b8c5-3069572b74f3">

**Comment by My-Name-Is-Adam** [comment]
Perfect, thank you!
