### ISSUE TITLE
Drag and drop on the original position under the divider of App Group is buggy

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1456]
* Wavebox Version: Wavebox-10.122.18-2.x86_64
* Operating System & Version: Fedora 39

### Bug/Feature description

[Screencast from 2024-02-23 15-16-20.webm](https://github.com/wavebox/waveboxapp/assets/28209361/688e0333-0c48-4e47-948e-08b2f5057bda)

**Comment by Thomas101** [comment]
Thanks, I've reproduced it here, there's a fix in the next version 👍
