### ISSUE TITLE
[Webdock explorer] Cannot change the position of bottom app by drag

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1458]
* Wavebox Version: Wavebox-10.122.24-2
* Operating System & Version: Fedora

### Bug/Feature description

[Screencast from 2024-02-24 12-11-25.webm](https://github.com/wavebox/waveboxapp/assets/28209361/30d2f417-d448-4aa4-bbd4-13f9f2e49840)

**Comment by Thomas101** [comment]
Thanks, I've got a fix for the next version 👍
