### ISSUE TITLE
[Feature request] Pining a group for all spaces

### ISSUE THREAD

**Issue by lens0021** [wavebox/waveboxapp#1464]
* Wavebox Version: 10.125.8-3 beta
* Operating System & Version: Fedora Workstation 40

### Bug/Feature description

I have mainly two spaces: One is Work and other one is Home.
And I've crated a 'GitHub notifications' group, and I am using it on the both spaces.

Also, I've set link opening rules:

![image](https://github.com/wavebox/waveboxapp/assets/28209361/1fd60007-258d-4d26-9ebf-b7a525bca284)

With Spaces Webdock layout, My 'GitHub notifications' group can belong to only one space.
Could this be improved?

**Comment by Thomas101** [comment]
My gut feeling here, would to be continue using the List/Explorer webdocks. These give more tooling for mixing and matching spaces and can allow for more complex setups. The spaces view is supposed to be a simpler view for people working on one project/space at a time
