### ISSUE TITLE
Getting new mail notifications even when it is disabled

### ISSUE THREAD

**Issue by bgreenlee** [wavebox/waveboxapp#15]
Wavebox 3.1.2 on Mac OSX 10.11.6

I have "Show new mail notifications" off, but it still is showing me notifications. I have tried restarting Wavebox.

(I also have "Show app unread badge" turned off, and it is still showing a "1" in the app badge.)

I have it configured with one Gmail account and one Slack account. Notifications & app badges are turned off for both

**Comment by Thomas101** [comment]
Ah yeah I see that too. Thanks for reporting, I'll find out what's gone wrong!

**Comment by Thomas101** [comment]
Hi a fix for this has just been release in 3.1.3. Wavebox will autoupdate shortly or if you want to get it sooner you can either re-launch Wavebox to trigger an autoupdate or redownload from https://wavebox.io/download Thanks!
