### ISSUE TITLE
Better Google Calendar Notifications

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#152]
At the moment Google Calendar brings up an alert box a few minutes before an event is about to start. Would be much better if this was a native notification that also works when the tab is asleep

**Comment by ashokfernandez** [comment]
+1

**Comment by gilles** [comment]
Not sure that's the right ticket but for me the notifications are not working (native or not) when the tab is asleep.

Running on ubuntu 16.04

**Comment by nmat** [comment]
@gilles notifications AFAIK is going to be fixed with the next release or from what I understand there is work for fixing it. (if I read the commits above)

**Comment by Thomas101** [comment]
@gilles at the moment they only work when the tab is not sleeping. We're adding change indicator badges for calendar in 3.3.4 and some better UI to indicate that they only work when sleep is disabled. We've been working on hangouts alongside this and this is what sits in the settings at the moment....

![screen shot 2017-09-27 at 09 09 01](https://user-images.githubusercontent.com/103586/30902608-b7a8451a-a363-11e7-843b-9406346d1bbf.png)

In the long run though we'll be adding support for notifications whilst the account sleeps :)

**Comment by gilles** [comment]
@Thomas101 fantastic!

You said "better UI to indicate that they only work when sleep is disabled" does that mean there is a way to disable sleeping at the moment or is this coming? I can't see anything in the settings. The only thing I can see is "Indicate when services are sleeping" but it's grayed out

**Comment by Thomas101** [comment]
You can disable sleeping already. Right click on your account in the left and then click account settings. Scroll down the Google Calendar service and uncheck the checkbox under "Sleep tab after seconds of inactivity"

![screen shot 2017-09-27 at 17 50 55](https://user-images.githubusercontent.com/103586/30926320-a1c014be-a3ac-11e7-8f9c-0111ada75165.png)

**Comment by gilles** [comment]
Notifications are working now, thanks!

**Comment by Thomas101** [comment]
Hi we've just added some improved support for Google Calendar to the latest beta (3.3.4). There's some information on how to switch to the beta channel and download the latest version [here].

If you'd like us to extend your trial so you can give it a try,
* Make sure you're signed into your Wavebox account by opening settings and then clicking the Wavebox tab. If you're signed in, your email address will be in the top right
* Send a message to [support](https://wavebox.io/support) with the email address you're signed in with and link to this issue.

Thanks
