### ISSUE TITLE
Feature Request: Hook into Chrome desktop notifications for other accounts

### ISSUE THREAD

**Issue by ToxMox** [wavebox/waveboxapp#153]
So a lot of sites have built in desktop notifications via Chrome. It would be cool to integrate this so when we add "Any Website" that we can enable notifications to work for those too. Or does this work already and I'm stupid?

**Comment by Thomas101** [comment]
Notifications should already work - unread counts don't as this isn't part of any HTML spec. Is there a website that you've found that doesn't work? I can take a closer look into that

**Comment by ToxMox** [comment]
So far I'm not getting any kind of desktop notifications from non built in services. WhatsApp is one of them not showing.

I think a good workaround would be to have some visual way of representing that a notification was received for an account. For example. Say I get a new message in my WhatsApp that I've added to Wavebox. It should show the desktop notification then have like an exclamation icon in the tray and the account highlighted/marked in Wavebox until I go into it. Basically flag the whole account as unread until clicked on. Also would be nice to  have a "notifications" button and pane in Wavebox that has a running list of notifications triggered.

**Comment by Thomas101** [comment]
That's a good idea. I could put the dot unread indicator (in a similar way to what slack has) to indicate that something has changed after a notification

**Comment by ToxMox** [comment]
I guess I kind of added a feature request into my bug report on the last reply but want to be clear that I'm not getting desktop notifications for non-built in apps.

**Comment by Thomas101** [comment]
I'll look into that too. Which website was it that you're missing the notifications on?

**Comment by Thomas101** [comment]
Also related #66

**Comment by ToxMox** [comment]
WhatsApp

**Comment by ToxMox** [comment]
Might also be related to #148

**Comment by Thomas101** [comment]
Hi, we've improved support for Notifications in 3.1.8. You may need to enable the notifications with the website though. (For example facebook messenger)
![screen shot 2017-05-23 at 09 31 04](https://cloud.githubusercontent.com/assets/103586/26345949/7a445c2a-3f9c-11e7-8460-03f6b7af31ba.png)

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
