### ISSUE TITLE
"Zoom in" not working after two/three clicks

### ISSUE THREAD

**Issue by fsdias** [wavebox/waveboxapp#158]
Version: 3.1.6/Ubuntu 16.04

Zoom in stops working after two or three clicks. Zooming out to works ok.

**Comment by Thomas101** [comment]
Thanks. I looks like something not quite right there!

**Comment by Thomas101** [comment]
I've just released 3.1.7 which fixes this. You might find that any accounts you changed the zoom on are really zoomed out/zoomed in. If you reset the zoom and readjust it to how you want it it should behave from now on.

Thanks for reporting!

**Comment by fsdias** [comment]
Fix confirmed, thanks
