### ISSUE TITLE
Feature: Service Display Collapsed for unselected accounts

### ISSUE THREAD

**Issue by soyrex** [wavebox/waveboxapp#16]
It would be amazing if (when displayed in the left sidebar) the services underneath the unselected accounts could be hidden.

So that ONLY the services under the account that I'm currently looking at are visible in the sidebar.

* Which version of Wavebox are you using? **Latest**
* Which Operating System are you using? **Windows 10**

**Comment by jacksarick** [comment]
I like having the services displayed. It means I can switch between my calendars at one click. Maybe as an option?

**Comment by soyrex** [comment]
Option would be even better - maybe I should be doing some dev instead of whinging about features :D

I have like 5 accounts and i was testing adding in Slack and Hipchat - but it basically meant my sidebar didn't fit on my screen anymore ;)

**Comment by jacksarick** [comment]
I just submitted my first PR to the repo, I highly suggest contributing. @Thomas101 keeps the code base very clean and organized, so it's great to work with.

**Comment by Thomas101** [comment]
I think this is a good one to add. Handy if you don't want to use the toolbar and make good use of services!

**Comment by Thomas101** [comment]
Hi this has been added in 3.1.3. Wavebox will autoupdate shortly or if you want to get it sooner you can either re-launch Wavebox to trigger an autoupdate or redownload from https://wavebox.io/download

You'll find the setting by right clicking on your account and looking under the appearance sectin
![screen shot 2017-04-10 at 16 06 18](https://cloud.githubusercontent.com/assets/103586/24868385/c66e512a-1e07-11e7-98e1-d606a84a32e6.png)



Thanks!

**Comment by soyrex** [comment]
Nice one. You implemented this while i was still figuring out how to get it to build on my machine ;) :+1:
