### ISSUE TITLE
[Feature Request] Better defaults for "any site"

### ISSUE THREAD

**Issue by Stanzilla** [wavebox/waveboxapp#160]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.6
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 8.1

Would be nice if the app could pre-fill some of the options for `any site` by looking at the page, for example if a `favicon` is set, use it as badge icon, if  `<meta name="theme-color" content="#">` is set, use that as color etc.

**Comment by Thomas101** [comment]
Yeah that's a good idea!

**Comment by Thomas101** [comment]
Hi, we've added this in 3.1.8. Thanks!

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
