### ISSUE TITLE
Feature: Access recent downloads

### ISSUE THREAD

**Issue by ToxMox** [wavebox/waveboxapp#161]
After I download something in Wavebox I have to manually go to the folder I downloaded the item to to open the file. Would like to see recent downloads somewhere so I can immediately open a download or open file location.

**Comment by midimarcus** [comment]
:+1:

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
