### ISSUE TITLE
Gmail Default Zoom Set Too High

### ISSUE THREAD

**Issue by bondydaa** [wavebox/waveboxapp#163]
* Which version of Wavebox are you using? Version: 3.1.6

* Which Operating System are you using? macOS Serria 10.12.4

After updating, when my gmail loaded it was zoomed in too much, hitting command+0 to reset did nothing so it appears the default zoom is set too high. I can zoom in and out just fine.

<img width="1439" alt="wavebox__4_" src="https://cloud.githubusercontent.com/assets/4073354/25751370/03bcbfbc-3172-11e7-91b1-d91b541a5828.png">

My inbox tab zoom seems to be fine.

**Comment by Thomas101** [comment]
Hi, it looks like there is some issues with zoom in this release. If you got to View > Zoom out are you able to get back to something more reasonable?

**Comment by bondydaa** [comment]
I am able to zoom out but it seems the layout doesn't ever want to get back to the "default zoom". 

Here is what gmail in my browser looks like:
<img width="1439" alt="inbox__2__-_dbondy_expensify_com_-_expensify__inc__mail_and_google_hangouts_-_bondydaa_gmail_com" src="https://cloud.githubusercontent.com/assets/4073354/25753191/dbd6c136-3177-11e7-8239-5228703b7334.png">

And about the same zoom level in wavebox:
<img width="1439" alt="wavebox__3_" src="https://cloud.githubusercontent.com/assets/4073354/25753307/37bb7578-3178-11e7-8d93-3a4df7d13801.png">

**Comment by Thomas101** [comment]
I'm seeing something similar. The default zoom level used to be 1, but it looks like this has changed to 0. Not too sure if something has changed in electron or it just wasn't picked up before.

Looking at the behaviour as soon as you zoom in it goes to 1.1 which is obviously 1.0 whole steps too many. You can then zoom in and out from there and go back all the way to 0 which is default zoom. The spanner in the works, is when you restart if the zoom is set at 1.0 it doesn't apply the setting as it doesn't think there's anything to apply.

I'll patch this, thanks!

**Comment by Thomas101** [comment]
I've just released 3.1.7 which fixes this. You might find that any accounts you changed the zoom on are really zoomed out/zoomed in. If you reset the zoom and readjust it to how you want it it should behave from now on.

Thanks for reporting!

**Comment by bondydaa** [comment]
Thanks! I'll keep an eye out for the update. 🎉

**Comment by bondydaa** [comment]
I just updated to `Version: 3.1.7` and looks like something still a little funky:

<img width="1439" alt="wavebox__1_" src="https://cloud.githubusercontent.com/assets/4073354/25859670/79b3767a-349c-11e7-85cd-a9744b9d73e4.png">

It looks appears that the right-hand side of the inbox is just pushing itself as far left as possible and overlapping with the left-hand side of the inbox.

<img width="1439" alt="wavebox__2_" src="https://cloud.githubusercontent.com/assets/4073354/25859798/d7e68278-349c-11e7-98f0-3afc73e5c28b.png">

Thanks!

**Comment by Thomas101** [comment]
That does look weird! If you try restarting does it fix itself?

**Comment by bondydaa** [comment]
Hmm strange, I thought I had quit the app and restarted but I just did so again and it does seem to have corrected itself.

The spacing it a little off when comparing to gmail in the browser but also just realized that since I have the sidebar in wavebox for my accounts that takes up more space than just in a browser tab. Adjusting the browser to be about the same size produces about the same layout.

I'll go ahead and close this back out. Thanks again!
