### ISSUE TITLE
Clicking email addresses in Trello opens external Chrome tab

### ISSUE THREAD

**Issue by ToxMox** [wavebox/waveboxapp#164]
* Which version of Wavebox are you using? 3.1.7

* Which Operating System are you using? Windows 10 x64

When I click an email address inside Trello in Wavebox it opens an external Chrome window when it should prompt me for which email account I want to create a new email with inside Wavebox.

**Comment by Thomas101** [comment]
Hi, I've just taken a look into this. If you open the settings in Wavebox and under the platform section there's an option to `Handle mailto links`, make sure this is toggled to on. This will make Wavebox the default mail handler. Once you've done this the links should open in Wavebox
![screen shot 2017-05-17 at 15 36 21](https://cloud.githubusercontent.com/assets/103586/26159596/e94c3474-3b16-11e7-8f8b-57f8a2079f6c.png)

**Comment by ToxMox** [comment]
Still opening in browser.

**Comment by ToxMox** [comment]
I just went into "Choose a default email app" in Windows settings and chose Wavebox now it works fine.

**Comment by Thomas101** [comment]
Awesome, will close this off then. I noticed you opened the one for Google Contacts too. This should work in the same way, but you'll still get a compose window in chrome too. This will be fixed in 3.1.8

**Comment by ToxMox** [comment]
Not sure this should be completely closed yet. When selecting Handle mailto links shouldn't it trigger that control panel in Windows to open or something? I don't remember how other apps handle that or what the general practice is but I'm sure there is one :)
