### ISSUE TITLE
Dropbox Power-Up issue with Trello

### ISSUE THREAD

**Issue by HistoneH4** [wavebox/waveboxapp#165]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS Sierra 10.12.3

Hi, everytime I try to add a Dropbox file to a Trello card via Wavebox, Trello asks me to sign in to my Dropbox account. When I click on 'Sign in', it opens up a Dropbox Chrome tab that almost immediately closes (after about half a second). 

Signing in to Dropbox on Chrome without going through Wavebox does not resolve the issue.

**Comment by Thomas101** [comment]
Thanks, I'll take a look into this

**Comment by Thomas101** [comment]
Hi, we've been looking into this and found that it's an upstream issue with electron. We've reported it to them and also opened a consolidated issue for wavebox (#187) which contains some work arounds for the different places it fails.

As a temporary work around, if you login to trello using your web-browser, add the dropbox power-up and then relaunch Wavebox you should be able to add files. There's some more info on how to do this in the #187 issue.

Going to close this off for now, so we can continue tracking all the instances in once place. Thanks for reporting!
