### ISSUE TITLE
Inbox Gmail

### ISSUE THREAD

**Issue by butchewing** [wavebox/waveboxapp#167]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.12.4

The Gmail link in the Inbox left navigation does not open a new browser tab. Contacts is working perfectly, though.

![screen shot 2017-05-07 at 7 33 27 pm](https://cloud.githubusercontent.com/assets/405072/25786527/8e0f478e-335c-11e7-8598-eb5e362fa3db.jpg)

**Comment by Thomas101** [comment]
Thanks I'll take a look

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox and can be enabled by using the experimental window opener. There’s some instructions on [how to do that here](https://blog.wavebox.io/testing-the-new-window-opener/). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
