### ISSUE TITLE
In Trello can't attach from Google Drive

### ISSUE THREAD

**Issue by ToxMox** [wavebox/waveboxapp#168]
* Which version of Wavebox are you using? 3.1.7

* Which Operating System are you using? Windows 10 x64

In Trello if I click on attachments and try to attach from Google Drive it opens a window in chrome where I need to choose an account and allow access but no matter what I do this has no effect inside Wavebox and can never attach from Google Drive as it keeps opening the same auth window in Chrome.

**Comment by Thomas101** [comment]
Thanks I'll take a look!

**Comment by Thomas101** [comment]
Hi, we've been looking into this and found that it's an upstream issue with electron. We've reported it to them and also opened a consolidated issue for wavebox (#187) which contains some work arounds for the different places it fails.

As a temporary work around, if you login to trello using your web-browser, add the google drive power-up and then relaunch Wavebox you should be able to add files. There's some more info on how to do this in the #187 issue.

Going to close this off for now, so we can continue tracking all the instances in once place. Thanks for reporting!
