### ISSUE TITLE
Trello PDF preview doesn't work

### ISSUE THREAD

**Issue by ToxMox** [wavebox/waveboxapp#169]
* Which version of Wavebox are you using? 3.1.7

* Which Operating System are you using? Windows 10 x64

For cards with PDFs attached the built in preview is blank whereas it works in Chrome.

**Comment by Thomas101** [comment]
This could be related to #51 but I will double check and update the upstream bug report too

**Comment by Thomas101** [comment]
This looks like an upstream issue with the PDF renderer. I've raised it in electron and will continue looking for a fix. https://github.com/electron/electron/issues/9531

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
