### ISSUE TITLE
Out of sync unread badge count

### ISSUE THREAD

**Issue by iammart** [wavebox/waveboxapp#170]
Notification badge for Gmail in application sidebar remains the same after unread messages have been deleted. After a delay of 10s+ it eventually syncs and removes the badge as expected.

Similar issue when client is open and in focus new mail is received, badge can take up to 10s to catchup and apply the unread message count.

Pressing the refresh mail in Gmail has no effect on the count

* Which version of Wavebox are you using? 3.1.7
* Which Operating System are you using? OSX 10.11.6

**Comment by adioni** [comment]
Noticing the same behavior. Will the 'Scrape unread count directly from UI' option in WMail be brought over to Wavebox? That seemed to help things in the last of the WMail releases.

**Comment by Thomas101** [comment]
We've seen a particularly high latency on receiving updates from Google this week. I'm going to look into getting updates from the browser window too so that when you're actioning emails the counts will resync more promptly (@adioni a little bit like the scraping behaviour from WMail).

If you see this again, could you right click on your account in the left hand side and pick `Resync`? Does this correct the unread count immediately?

**Comment by ToxMox** [comment]
I'm seeing the same thing as OP. To answer your question, when I hit resync it immediately corrects the count.

**Comment by adioni** [comment]
Just tested this out, selecting `Resync` does correct the unread count immediately.

**Comment by Thomas101** [comment]
Thanks for the info! It does sound like google is just being slow in telling us about the updates. I'll add something in to watch the gmail window for changes and resync based on those

**Comment by Thomas101** [comment]
Hi, we've added a fix into 3.1.8 that listens to the Gmail & Inbox UI for changes in the unread count and tries to re-sync based on this as well as what Google tells us. This should improve the responsiveness of unread counts in the majority of cases. Let us know if you have any more trouble

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
