### ISSUE TITLE
Add ability to copy URL of page

### ISSUE THREAD

**Issue by ashokfernandez** [wavebox/waveboxapp#171]
It would be great if there was a keyboard shortcut or right click option to copy the current URL of the tab you're on. For instance if I have trello or some other generic site open, it would be cool if I could copy the URL of where I was to my clipboard to share with colleagues.

**Comment by Thomas101** [comment]
Probably only applies to trello & generic (unless you think others?) but easy to add in for the next release. Thanks!

**Comment by ashokfernandez** [comment]
Yeah mostly for trello and generic sites. Thanks for the awesome product by the way, have been telling my colleagues about it all week!

**Comment by Thomas101** [comment]
Hi, we've added this in 3.1.8. Thanks!

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
