### ISSUE TITLE
Inbox will not reload

### ISSUE THREAD

**Issue by TheSeanBrady** [wavebox/waveboxapp#172]
* Which version of Wavebox are you using? 3.1.7

* Which Operating System are you using? Ubuntu 17.04

Inbox will often not reload, I just get the spinning wheel for over an hour.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. How are you trying to reload? (Right click reload, restart Wavebox etc...)

**Comment by Thomas101** [comment]
Going to close this off for now due to inactivity, but if you're still seeing the problem re-comment and I'll take another look. Thanks
