### ISSUE TITLE
Feature Request: Make clicking OS X notification banner bring you to originating account

### ISSUE THREAD

**Issue by adioni** [wavebox/waveboxapp#175]
Currently when Wavebox generates a banner on the OS X desktop and you click on it, it simply brings the program into focus to whatever view you were previously on. 

It would be nice if in addition, it also switched to the originating gmail, office 265, slack, etc. account.

* Which version of Wavebox are you using? 3.1.7

* Which Operating System are you using? Mac OSX 10.12

**Comment by Thomas101** [comment]
Hi, it should be doing this already. Have you noticed if it's any specific account type that doesn't get switched to. I've tested by sending an email to my gmail account and it switched right to it.

**Comment by adioni** [comment]
Ah, apologies, you are right this is working as intended for gmail accounts. I currently have too many accounts configured in wavebox to keep track of.

In the midst of a workplace transition from Zimbra Collaboration suite to G Suite. It is the zimbra web interface setup as an 'add any website' entry that is experiencing the behavior. 

That will be going away very soon. The Gmail accounts I have setup switch as expected.

**Comment by Thomas101** [comment]
Awesome, thanks for the extra info! There's some improvements we're adding to the notifications in the Any Web Link account type, so I'll take a look at this when I work through them! Thanks

**Comment by Thomas101** [comment]
Hi, we've added this in 3.1.8. Thanks!

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
