### ISSUE TITLE
Place top bar icons to the left instead of right

### ISSUE THREAD

**Issue by astraldragon** [wavebox/waveboxapp#178]
* Which version of Wavebox are you using? 3.1.7
* Which Operating System are you using? Mac OSX 10

On widescreen monitors the icons go so far to the right, it'd be nice if they were on the left close to the accounts

![screen shot 2017-05-12 at 10 06 10 am](https://cloud.githubusercontent.com/assets/846931/25999225/a56ebf30-36fa-11e7-9c09-396a830e0373.png)

**Comment by Thomas101** [comment]
Should be easy enough for me to add an option in!

**Comment by Thomas101** [comment]
Hi, we've added this in 3.1.8. You can change the alignment by right clicking on your account in the sidebar and going to Account Settings. Then you can switch between left and right alignment under the services section.  Thanks!
![screen shot 2017-05-23 at 09 46 41](https://cloud.githubusercontent.com/assets/103586/26346044/e07103ae-3f9c-11e7-9bfe-c41cc5e66012.png)

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
