### ISSUE TITLE
NoSpam

### ISSUE THREAD

**Issue by warp4** [wavebox/waveboxapp#179]
Is it possible to add NoSpam/DeSpam function or is this omision a Google "feature"?

V 3.17 on Linux Mint 17.3

**Comment by Thomas101** [comment]
Hi, this is something in Google Inbox that's missing. Google have an [Inbox product forum](https://productforums.google.com/forum/#!forum/inbox) which might be a great place to report it. 

On a side note from this though, we are looking at extension support soon. I'm not sure there's one that adds NoSpam functionality in right now, but if Google are slow moving on this it would be a great place that we could add it in.
