### ISSUE TITLE
Add Google Voice 

### ISSUE THREAD

**Issue by t-kitsune** [wavebox/waveboxapp#180]
Please add Google Voice, and don't put it behind a pay wall. I don't have access to a cellular service & Google Voice is the only way I can talk to my kids

**Comment by Thomas101** [comment]
Hi, we have plans to add Google Voice to Wavebox. There's an issue open (#131) for adding extra services (Voice being one of them) so I'm going to close this off for now so we can continue tracking it from there. Thanks!
