### ISSUE TITLE
O365 download attachment links don't work

### ISSUE THREAD

**Issue by caldwed** [wavebox/waveboxapp#182]
* Which version of Wavebox are you using? 3.1.7
* Which Operating System are you using? Ubuntu 16.04

Using an O365 account, when trying to use the link in an email to download all attachments as a zip a new browser tab is opened but the files will not download. The dialog box for where to save the file does not appear.

**Comment by Thomas101** [comment]
Thanks, I'll see what's up with this and add it in

**Comment by Thomas101** [comment]
Hi, I've been looking into this, but haven't been able to find the button to download all attachments. How do you normally bring this up (I tried sending two images and a pdf)?

**Comment by caldwed** [comment]
It's a "Download all" text link below the list of files.

It looks like this like is re-directing to a browser window. If I'm logged-in there, the OS dialog for save works. If I logout in the browser, the save fails as I originally described.

![downloadscreenshot](https://cloud.githubusercontent.com/assets/27022154/26256763/fcf5ea58-3c8b-11e7-8729-ef5ec0f01f1c.png)

**Comment by Thomas101** [comment]
Ah yes, I see as well now. I'll take another look

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
