### ISSUE TITLE
Links in Wavebox not Working

### ISSUE THREAD

**Issue by bigjay517** [wavebox/waveboxapp#183]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version: 3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Arch Linux

When I click on a link in any of my emails in Wavebox my browser does not open a new tab.  Nothing seems to happen.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. If you go to View > Developer Tools (Or Press Ctrl+Shift+J) and click on the console tab. Then paste the following...
```js
require('electron').remote.shell.openExternal('https://wavebox.io')
```
...does your browser open?

**Comment by bigjay517** [comment]
No, I get the response `true` but a new tab does not open.

**Comment by bigjay517** [comment]
I fixed my problem.  It seems that Electron needs xdg-utils installed in order to open web links.  I have installed the package and everything is working.

Hopefully you didn't waste time on this.

**Comment by Thomas101** [comment]
Thanks for the extra info! :-)

**Comment by linfopage** [comment]
* Which version of Wavebox are you using?
Wavebox 3.1.8

* Which Operating System are you using? 
Ubuntu 16.04

I have the same issue. 
I have xdg-utils already the newest version. 

Please Help.

**Comment by Thomas101** [comment]
@linfopage how did you install Wavebox? Was it through the snap package?

**Comment by linfopage** [comment]
@Thomas101 , Yes. I have installed through snap.

**Comment by Thomas101** [comment]
Okay, I think this may be related to https://github.com/wavebox/waveboxapp/issues/204

**Comment by linfopage** [comment]
thanks for the info, I tried installing the deb package. It look fine.
