### ISSUE TITLE
Tray icon problem in Kde Plasma 5.9.5

### ISSUE THREAD

**Issue by saikatbsk** [wavebox/waveboxapp#184]
The tray is just a blue square (see screenshot).
I am using Wavebox 3.1.7 on Arch Linux with Plasma 5.9.5
![screenshot_20170517_020511](https://cloud.githubusercontent.com/assets/2530074/26127152/f6bd16f8-3aa5-11e7-9207-5145bf58471e.png)

**Comment by Thomas101** [comment]
Hi, do you know if you have libappindicator installed?

**Comment by saikatbsk** [comment]
I didn't have that. Got libappindicator-gtk2 installed and now this is how it looks like (screenshot). There are white pixels around the four corners.
![screenshot_20170517_142633](https://cloud.githubusercontent.com/assets/2530074/26146268/2fe0993e-3b0d-11e7-9dbb-e13f6d6341a4.png)

**Comment by Thomas101** [comment]
I think that may be related to #64. I doubt it will make any difference, but in the settings under the menu bar section there's a DPI Multiplier dropdown. Does changing this make any difference?

**Comment by saikatbsk** [comment]
Changed DPI to 2x. This is how it looks now:
![screenshot_20170518_144533](https://cloud.githubusercontent.com/assets/2530074/26195295/e7b435f4-3bd8-11e7-83a4-d5aa09706b46.png)

**Comment by Thomas101** [comment]
Thanks, looks like it is the same as 64. I'll take a look into it

**Comment by Thomas101** [comment]
Hi, after looking into this, it looks like KDE uses a different icon size to gnome and unity. I've added an option in to change the icon size manually. When I tried it 28px worked well for the kubuntu instance I was running, but you may find a different size works best for you. Thanks!

 
![screen shot 2017-05-23 at 09 26 45](https://cloud.githubusercontent.com/assets/103586/26345178/fab12f9e-3f99-11e7-9c14-e1148172edbd.png)

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download

**Comment by saikatbsk** [comment]
Thanks. That worked. Awesome work with Wavebox.
