### ISSUE TITLE
[Request] User Agent Per Account

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#185]
I'd like to request the ability to set the User Agent on a per account basis.

* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
KDE Neon (Ubuntu 16.04)

**Comment by Thomas101** [comment]
Is this only for Any Web Link accounts or across any account type? I know for example Google uses the UserAgent to customise some code for different browsers which means you get some odd behaviour when telling Google that you're using Firefox.

**Comment by MichaelTunnell** [comment]
I am really only asking about using it for the **Any Web Link** accounts. I was going to setup an instagram account but there is a limitation that only works on mobile specific user-agents. I have a different solution but it might be nice to use Wavebox for this.

**Comment by Thomas101** [comment]
Thanks, I've added this in

**Comment by Thomas101** [comment]
Hi, we've added this into 3.1.8. Thanks!

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download

**Comment by MichaelTunnell** [comment]
any chance to add this to the new Instagram account?

I only wanted it for the Instagram option.

**Comment by Thomas101** [comment]
It's auto-configured by default when adding the linked accounts. I can add an option in to overwrite this though - as per the weblink accounts

**Comment by MichaelTunnell** [comment]
Just to clarify, the reason I want this added to Instagram is because Instagram allows for you to upload from a web-browser but they restrict that option to "Mobile Browsers". If you can add a custom user agent to the Instagram module then a mobile browser user agent could be used instead which would make it possible to use Wavebox Instagram Module to upload to Instagram. :)

If the Instagram module had the ability I described in #592 then it would be pretty much the perfect desktop solution for Instagram.

Alternatively, just replacing the user agent for the Instagram module would work as well because if that was made to be the Android version of Chrome then the custom user agent option wouldn't be needed.

**Comment by Thomas101** [comment]
We've added the userAgent overwrite in as a quick get started. That's due in the next beta.
![screen shot 2018-02-22 at 09 22 13](https://user-images.githubusercontent.com/103586/36530021-ea2d9158-17b1-11e8-9d8d-970613db95f4.png)

We should be looking at promoting Instagram to an Integrated App. A quick test shows that there are a couple more things to do with this - for example as well as change the UA, the screen size needs to portrait etc.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by MichaelTunnell** [comment]
Thank you very much! I have been using it in the beta releases since it was added and it is working great. Thank you very much! :+1:

**Comment by Thomas101** [comment]
Great to hear :)
