### ISSUE TITLE
3rd Party OAuth

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#187]
There's an issue with Wavebox which means some 3rd Party OAuth authentication dialogs fail. The underlying issue with this is electron does not pass the full window context between new windows. Newer versions of electron are adding support for this, but there is an issue with contexts not being passed cross domain causing authentication to fail. This has been reported in https://github.com/electron/electron/issues/8100

Here's a list of services / environments that it affects and temporary work arounds that can be used whilst we fix this issue.

## Trello Accounts
* Adding the Google Drive Power-up (#168)
  **Work around:** Add the power up in your web browser, relaunch Wavebox and from here-on you will be able to add google drive documents
* Adding the Dropbox Power-up (#165)
  **Work around:** Add the power up in your web browser, relaunch Wavebox and from here-on you will be able to add dropbox documents

## Any Web Link Accounts
* Signing into asana (https://app.asana.com) (#99)
  **Work around:** Sign in with username & password rather than Google Account. If you've only ever signed in with Google you can set a password by using the forgotten password option and entering your email address. The reset email will allow you to set your a new password

We're continually tracking progress on this issue and working on a more permanent solution

**Comment by tomaslundborg** [comment]
this one is still not working.... any updates on when it will be fixed? (cannot use other than google login on Asana)

**Comment by Tahini-123** [comment]
Still not working properly at least for Google authentication on Jira and Confluence
[https://imgur.com/a/t8Ew3](url)

**Comment by Thomas101** [comment]
@Tahini-123 which version of Wavebox are you using? We've added support for Jira in the latest beta through the add screen which should be working. I'll take a look at Confluence

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
