### ISSUE TITLE
Send to Mail Recipient doesn't work!

### ISSUE THREAD

**Issue by JeremyWW** [wavebox/waveboxapp#189]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Sorry if this has been raised elsewhere. How very disappointing to install an email client that is correctly registered as the default email client but then fails to use the context menu 'Send to... Mail Recipient'  option in Windows 10. Using it just results in the standard Windows error panel 'There is no email client....blah blah...' I'm using Wavebox with one 'Inbox' account. This is a primary reason for using an email client rather than webmail.

**Comment by Thomas101** [comment]
I think this could be related to #181. I'll take a look to see if I can get it registered

**Comment by JeremyWW** [comment]
Yep, appears to be the same thing. Have you had any joy with it?

**Comment by Thomas101** [comment]
#181 has been moved into the next release milestone. We're currently tracking progress from there. Thanks
