### ISSUE TITLE
Email notification - click on "view" does not open email

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#190]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.04 (unity 7)

When new email arrives, Wavebox fires up a notification that has a "view" button which doesn't do anything, like so:

![image](https://cloud.githubusercontent.com/assets/6388823/26156007/d684ae2a-3b0c-11e7-8bd7-fef95ad39041.png)

I reckon it should open wavebox, on the right account and email.

**Comment by Thomas101** [comment]
This is down to the notification server on linux not providing click handler support. I am looking at alternative ways to present notifications and hopefully bring the functionality on linux up to speed with macOS and Windows (#83). Going to close this off for now, so we can continue tracking from one place.

Thanks
