### ISSUE TITLE
Tray icon > account > unread email list does not open email

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#191]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.04 (unity 7)

When there are unread emails, clicking on the tray icon shows a list of accounts with a drop down showing all the different unread messages. Clicking any of these messages opens wavebox, but not the email in question.

I would expect wavebox to open on the right account and showing the relevant email.

**Comment by Thomas101** [comment]
Is this with Google Inbox accounts?

**Comment by luispabon** [comment]
Yes.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by luispabon** [comment]
Great, just installing the beta.Will report back.

**Comment by luispabon** [comment]
Been trying this and it is already a big improvement, but not quite there yet. 

Upon clicking on the menu item, I get taken to the right account, and a search is run at Inbox that shows a single email (the right one though), instead of actually displaying the email.

**Comment by Thomas101** [comment]
the latest beta 3.2.5 has just been released. This should open the message shown up in search :)
