### ISSUE TITLE
Notification only shows email subject

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#192]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.04 (unity 7)

When a new email arrives, a notification pops up that contains only the email subject, like so:

![image](https://cloud.githubusercontent.com/assets/6388823/26155914/a70d78c0-3b0c-11e7-8734-405193685b20.png)

It would be great if it could also say the account email was received in, and also the name/email of the sender.

**Comment by Thomas101** [comment]
This could also be along with #83. It should show a snippet of the email message. I'll take a look though to see what's happening

**Comment by Thomas101** [comment]
Hi we've added a new notification provider to Wavebox for linux. This has support for enhanced formatting. It's still experimental so has to be enabled to use it...

1.) Open settings
2.) Enable the new Enhanced notifications (these aren't enabled by default in this version)
![screen shot 2017-06-22 at 10 11 24](https://user-images.githubusercontent.com/103586/27427298-65254e38-5736-11e7-8b39-8284468b69d0.png)

It would be great to get some early feedback on this! Thanks

**Comment by luispabon** [comment]
I've just updated & enabled it, I'll report back :+1: 

Thank you @Thomas101
