### ISSUE TITLE
[Bug] YouTube backspace controlling page navigation

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#193]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
KDE Neon -> Ubuntu 16.04

I realize this is not really in scope and that YouTube support is being considered for specific feature but I thought it was worth reporting just because it's so annoying and it might affect other account structures.

If you create a YouTube account with the Any Web Link account  option it works very very good for the most part but there is one bug that is increasingly infuriating.

If you type a comment in your Creator Studio and press backspace, it works as expected. However, if you press backspace while commenting on a video page the page ignores the key and uses it as a back navigation button. I have only had this happen to me through YouTube as the account but it may happen in other places so it might be worth addressing.

**Comment by Thomas101** [comment]
Thanks for reporting! I'm not seeing the same behaviour my end. Can I just double check I'm trying in the right place?

* First tried on a random video in the comment box...
![screen shot 2017-05-18 at 09 05 04](https://cloud.githubusercontent.com/assets/103586/26192320/1bcf9c96-3ba9-11e7-9148-fca956e766cc.png)

* Then tried My Account > Creator Studio > Opened one of my videos and tried in the comment box...
![screen shot 2017-05-18 at 09 07 57](https://cloud.githubusercontent.com/assets/103586/26192437/8a5527d0-3ba9-11e7-8b5c-8ec09f22677f.png)

Both seemed to delete okay :-/

**Comment by MichaelTunnell** [comment]
I'll record a video to show it happening but might have to wait until tomorrow for testing. The comments in Creator Studio are fine to me, just in regular video comments that I experience the issue.

**Comment by Thomas101** [comment]
@MichaelTunnell are you still seeing this with 3.1.9?

**Comment by MichaelTunnell** [comment]
I am still seeing this issue occur with all versions up to 3.1.12.

Here is a video I created to demonstrate where and when it happens.

https://youtu.be/JmOz0mei12U

*note: I didn't mention that the backspace happens regardless of making a comment, just in any section of any page on normal YouTube browsing.

**Comment by Thomas101** [comment]
Perfect! I see that too now. I'll see where it's gone wrong in the capture chain

**Comment by Thomas101** [comment]
Hi, we've put a fix out for this in the beta channel. There's some instructions [here](https://wavebox.io/kb/beta-channel) on how to switch across so you can give it a try

**Comment by MichaelTunnell** [comment]
I just tested this in 3.1.16 Beta and can confirm this backspace issue has been resolved. Thank you!
