### ISSUE TITLE
ADFS with Office365

### ISSUE THREAD

**Issue by rmtilson** [wavebox/waveboxapp#195]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Fedora 25

I see that office365 is supported and ADFS works, however on a non windows machine SSO does not work with office365. When using chrome get a username and password prompt from our ADFS server when redirected from login.microsoftonline.com.  Any chance that support for non sso access be provided, or catch the secondary password prompt. 

Looking around and does not appear to be away for me to bypass ADFS and get access to office365.

**Comment by rmtilson** [comment]
On a follow up used nativefier to create an electron based app and was able to catch the second auth request. However didn't support notifications for Office365. I assume that since you can support notifications with outlook.com, office365 should also receive desktop notifications?

**Comment by Thomas101** [comment]
Hi, if you login using your web browser do you see an authentication popup similar to the one below? If so I'm thinking this could be waiting on #141 
![basic_auth_prompt](https://cloud.githubusercontent.com/assets/103586/26346734/1569dc46-3f9f-11e7-99b5-e8b614a9038c.png)

**Comment by rmtilson** [comment]
Yes, the example you provided is similar to what I get in chrome.

**Comment by Thomas101** [comment]
Okay, thanks for the extra info. I'll try to get this added into the next release!

**Comment by Thomas101** [comment]
Hi, we've been looking a little bit more into this and the way that Wavebox needs to talk to Exchange  servers is slightly different to how it does with Outlook & Office 365. There's quite a few related issues going around as regards this so I'm going to collapse this and a few other issues into one (#268) to make it easier to track progress and compatibility. Thanks
