### ISSUE TITLE
Application > About reads "3.1.5" on installed .deb of 3.1.7; prompts update

### ISSUE THREAD

**Issue by flipsasser** [wavebox/waveboxapp#197]
* **Which version of Wavebox are you using?** Either 3.1.5 or 3.1.7 but I *downloaded* 3.1.7 from the website.

* **Which Operating System are you using?** Ubuntu 16.04

Whenever I open Wavebox, I get a "Newer version available" dialogue. I've removed Wavebox and reinstalled from the latest download, but it always re-prompts me to update. The file name I download is `Wavebox_3_1_7_linux_x86_64.deb` but the "About" screen in the app reads "3.1.5".

But thanks for Wavebox! I love it!

**Comment by Thomas101** [comment]
It definitely sounds like something's gone wrong with the install/uninstall process. I'm guessing you're using the software centre on Ubuntu to install this. You could try uninstalling using `dpkg --remove wavebox` from the terminal to remove it and then try installing through the software centre again.

Alternatively the 3.1.8 release has snap packages and an apt repository available which might be an easier way to keep Wavebox up to date.

**Comment by flipsasser** [comment]
@Thomas101 I'd already tried the `dpkg --remove` approach. This morning I paired that with `sudo rm -rf /opt/wavebox` and re-installed - and everything worked!

Thanks for the help and for Wavebox!
