### ISSUE TITLE
Ctrl + R intermittently fails with Wavebox in system tray

### ISSUE THREAD

**Issue by flipsasser** [wavebox/waveboxapp#198]
* Which version of Wavebox are you using? 3.1.5

* Which Operating System are you using? Ubuntu 16.04

I've noticed that other apps running in Ubuntu _intermittently_ refuse to respond to a `CTRL + R` keystroke. Closing Wavebox entirely (click on icon in system tray > Quit) always resolves the issue.

**Comment by flipsasser** [comment]
I should be about "intermittently:"

- When the `CTRL + R` bug manifests itself, *every app* supporting a `CTRL + R` keystroke fails to register until I completely quit Wavebox
- The bug does not always manifest itself

**Comment by Thomas101** [comment]
Hi, this was fixed in 3.1.6, but it sounds like you're stuck on 3.1.5 as per #197. Thanks!
