### ISSUE TITLE
(Possible regression) Unwanted new mail notification when marking message unread

### ISSUE THREAD

**Issue by deeplypuzzled** [wavebox/waveboxapp#199]
* Which version of Wavebox are you using? 3.1.7

* Which Operating System are you using? OSX 10.11.6

To reproduce:

1. In Wavebox's Gmail Inbox, open an unread message.

2. From the "More" menu, or from the top-right "arrow" dropdown, choose "Mark as unread".

3. After a few seconds (it can be up to 15s), a desktop notification appears for the message, as if it is a new email. Multiple notifications are listed in the Notifications (top right of MacOS menu bar).

I think this was fixed in Wmail some months ago, so it may be a regression?

Best wishes

Jeremy

**Comment by Thomas101** [comment]
Thanks I do remember fixing it, but will take a look to see what Wavebox is doing differently

**Comment by deeplypuzzled** [comment]
Appears to be fixed in 3.1.8. Thanks.

**Comment by Thomas101** [comment]
I don't think I changed anything around this between 3.1.7 and 3.1.8, so if it comes back up let me know. It could have been Google pushing something odd down the api.
