### ISSUE TITLE
Zoho Support

### ISSUE THREAD

**Issue by vmosoti** [wavebox/waveboxapp#20]
Could this be supporting Zoho Mail as well? is one of the features I wished WMail could support

**Comment by vmosoti** [comment]
Just confirmed: Added Zoho mail as a web link, no notification indicator when mail arrives. Could you consider adding support for Zoho Mail?

**Comment by Thomas101** [comment]
We'll take a look and see what's possible. Weblinks don't support notification indicators etc at the moment, these need a little bit of work to add in

**Comment by Thomas101** [comment]
Hi, we're collapsing all the new Account/Service requests into a single issue so we can keep track of them more closely. You can find and continue tracking progress from #130. Thanks
