### ISSUE TITLE
[Request] Manual Invoking of Sleep Mode

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#200]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
KDE Neon -> Ubuntu 16.04

----------

I'd like to be able to manually invoke sleep mode on accounts. I really like the automatic sleep mode feature but sometimes I find myself wanting to look at an account for 30 seconds and then wanting to turn it back off but having to wait 5 minutes (default).

I'd like to be able to right click account icons and put to sleep while on a different active account.

**Comment by Thomas101** [comment]
I put some groundwork into sleeping in preparation for #126 but haven't got around to finish it off yet. With that in mind though, this shouldn't be too difficult to add and with the addition of 126 should make a pretty nice feature.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
