### ISSUE TITLE
[Slack] Unread Notifications Never Disappear

### ISSUE THREAD

**Issue by rawkode** [wavebox/waveboxapp#201]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.7

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Linux

**Comment by Thomas101** [comment]
If you open the slack window and then try pressing <kbd>shift</kbd>+<kbd>esc</kbd> a couple of times does this make them disappear? Is it an unread count or an unread indicator (the little dot) that sticks around?

**Comment by rawkode** [comment]
<kbd>shift</kbd>+<kbd>ESC</kbd> doesn't help. It's the little dot that won't go away.

I've tried "Resync" and "Reload"

**Comment by Thomas101** [comment]
Are you able to go to View > Developer Tools and then click on the console tab. Paste the following...

```js
window.waveboxDebug.flags.slackLogUnreadCounts = true
```
then do a resync. You should get a long log of all the unread info for each channel. One item should look like the following as an example...

![screen shot 2017-05-23 at 15 11 22](https://cloud.githubusercontent.com/assets/103586/26358342/25b2fddc-3fca-11e7-8e08-577b8b967afa.png)


The items with an `unread_count` which isn't 0 are what create the dot indicator. Are there any channels with the non zero unread count which shouldn't be indicating a change?

**Comment by rawkode** [comment]
```
window.waveboxDebug.flags.slackLogUnreadCounts = true
VM929:1 Uncaught TypeError: Cannot read property 'flags' of undefined
    at <anonymous>:1:20
```

**Comment by rawkode** [comment]
OK, that's because I right clicked and selected inspect. Using view I get

```
[SLACK:UNREAD] start 9d169ce1-731d-4aa2-bcc1-80391e113035
mailboxes.js:61 Objecterror: "invalid_auth"ok: false__proto__: Object
(anonymous) @ mailboxes.js:61
```

**Comment by Thomas101** [comment]
It looks like somethings gone wrong with the auth there! I'll need to double check if I'm capturing that.

If you try restarting Wavebox does that fix the issue? Failing that, if you add you slack account again does the newly added one sync correctly?

**Comment by rawkode** [comment]
This is fixed now.

I'm assuming the repeatable steps are:

- Trial expired
- Slack accounts were blocked
- Paid for upgrade
- Slack accounts notification wouldn't disappear, but they did update with chat

**Comment by scadeg** [comment]
Having just installed wavebox on a new laptop, I immediately saw this issue. While Thomas101's devtools/resync solution worked, I thought I'd provide my findings on which messages were causing this for me.

I had four channels (across two slacks) with unread_counts > 0. Once I went to each of those channels, the bright red circles cleared.

- 1 channel had a new members notification.
- 1 channel had a single unread thread comment.
- 1 channel had four unread thread comments.
- 1 channel on the second slack with a new member notification.

All of these events occurred prior to installation.

**Comment by Thomas101** [comment]
@rawkode thanks for the info, I'll give that flow a try here and see if I get the same behaviour

@scadeg were the channels in question highlighted in bold in the slack UI?

**Comment by scadeg** [comment]
They were not highlighted in bold.

**Comment by SegersIan** [comment]
I have the same issue. I installed yesterday Wavebox on my personal laptop and today on my office laptop (Both MacOs). In both use cases I added the same Slack Group, right after adding the red dot appeared on the Slack Group badge. While there were zero unread notifications at that time in slack itself.

MacOs 10.12.5 (Both machines)
Wavebox v 3.1.8

**Comment by lassebn** [comment]
I've seen the same issue today on a new install. No unread notifications in the Slack app, but a persistent red dot in Wavebox. I debugged with `window.waveboxDebug.flags.slackLogUnreadCounts = true` and a resync and saw the same "triggers" as @scadeg.

Now I'm down to a single channel causing the red dot, which is a channel with 4 members and a single file being shared with a comment. After the file was shared the channel was archived, then un-archived, then renamed and then archived again. This all happened within 5 minutes if that might matter. This all happened before installation, and the unread count is not set to 0 even though I've seen all activity.

The unread count is as follows
```
 {
      "name": "<channel-name>",
      "is_archived": true,
      "is_muted": false,
      "mention_count": 0,
      "unread_count": 1
    }
```

Wavebox 3.1.8
MacOS 10.12.5

**Comment by lassebn** [comment]
Un-archiving the channel, reading it and then archiving the channel again helps.

**Comment by Thomas101** [comment]
@SegersIan did the <kbd>Shift</kbd>+<kbd>ESC</kbd> trick work for you?

@lassebn perfect I'll give that a try!

**Comment by SegersIan** [comment]
@Thomas101 The shortcut doesn't seem to do anything, I also tried Resynch and Reload.

**Comment by worbunkel** [comment]
I was having this same issue. Turned out to be around Slack threads... I had read the notification in the "All Threads" bucket at the top. However, I hadn't read the message in the channel it was originally written in.

Hope this helps with debugging or with someone's issues! @Thomas101

**Comment by lassebn** [comment]
It seems that new messages in threads that I'm not following will trigger the red dot as well. It can be hard to track down the unread messages, as Slack don't provide a nice way to see these messages, if you're not following the thread already.

**Comment by SegersIan** [comment]
@worbunkel I went through the `All Threads` tried to click everywhere so slack would mark it as 'Done', but didn't work for me. 

@Thomas101 
BTW: I noticed that the red dot shows an actual correct value when I do have a notification. Someone messages me, I get the value `1` in that dot. But when I read that notification, it resets again to a `dot`.

I don't get btw how I can run `window.waveboxDebug.flags.slackLogUnreadCounts = true` in the `console` after doing `RIGHT CLICK + INSPECT`. I just get the following error:
```
VM664:1 Uncaught TypeError: Cannot read property 'flags' of undefined
    at <anonymous>:1:20
```
And I don't understand the solution of @rawkode 
```
OK, that's because I right clicked and selected inspect. Using view I get
```
Using View? Can anyone elaborate this?

**Comment by worbunkel** [comment]
@Segerslan If you're on macOS and have wavebox open you should see a view tab at the very top of your screen. It's the thin grey menu bar that appears when your mouse hovers at the very top. I'm not sure what apple actually calls it.

**Comment by SegersIan** [comment]
@worbunkel : Got it! Now I managed to make it work. Much appreciated !

@Thomas101 
After setting the flag is discovered that it was caused by not "reading" all threads within a channel. So now I don't have this round pop up anymore. It's exactly like @lassebn said.

**Comment by Thomas101** [comment]
Hi,

We’ve got a fix together for this which is due to land in the next release. If you want to try it out beforehand I’ve put a early build of  Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_35a1425_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* When the next version is released this version will update automatically
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Thanks!

**Comment by lassebn** [comment]
@Thomas101 💪 !
I just installed the fix, and it looks like it works as I would suspect.

**Comment by worbunkel** [comment]
@Thomas101 I installed it as soon as you mentioned it, and used it most of the day yesterday. I still have to resync every time to make the notification bubble go away. Seems like it should just go away automatically. But thanks for the quick response! 👍

**Comment by Thomas101** [comment]
@worbunkel do you know if you're behind a corporate proxy server? Do you get popup notifications about when someone DM's you?

**Comment by worbunkel** [comment]
@Thomas101 No, I'm not behind any kind of proxy server. And yes I do get popup notifications for DM's.

If you want me to test or post screenshots or anything to help debug, I'm more than happy to help.

**Comment by Thomas101** [comment]
@worbunkel thanks. If you have someone DM you does the count increase? Then if you open that DM does it come down again? It may take a few seconds depending on the delay for slack updating the client.

If you restart Wavebox and then go to View > Developer Tools and click the console tab do you see any errors?

**Comment by worbunkel** [comment]
@Thomas101 There aren't any errors in the console on restart. I do have 3 different slack channels open. It acts the same in all 3. 

And when I get a DM it doesn't increment my notification until I resync. Actually right now when I'm not in the channel, it doesn't appear to even give me a notification at all that I've gotten a DM. Then when I resync it shows the number. Then I can go to the DM and it still shows the number. It doesn't seem to ever go away until I resync.

I'm not sure how clear that was. Essentially my notification bubble doesn't change at all until I resync.

**Comment by worbunkel** [comment]
@Thomas101 I dropped two of the slack channels. Everything seems to work perfectly with only one open. Unfortunately I need all 3.

**Comment by Thomas101** [comment]
@worbunkel out of the 3 accounts, if you add say just account number 2 does this work? What I'm trying to figure out is if the problem lies with one of the accounts or the fact that there is more than one account.

I've also put a build [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_7cb64a8_osx.dmg) with some additional logging. If you download and open it and get Wavebox back into the not-working state, then go to View>Developer Tools and the console tab again, then paste the following...

```js
waveboxDebug.flags.slackLogWSMessages=true
```

If you visit a channel and paste a message you should some logs come out as slack reports the changes. If you have someone message you do you get any logs out? You should see something like this....

![screen shot 2017-06-21 at 12 18 49](https://user-images.githubusercontent.com/103586/27381763-f3e11af0-567b-11e7-86be-ee6fd7ab9a51.png)

**Comment by Thomas101** [comment]
Hi, the fix that was put in to the preview build above has now made out in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). I'll keep the issue open for now whilst we continue to diagnose the issue that @worbunkel is having. Thanks!

**Comment by scadeg** [comment]
Didn't use Wavebox yesterday, so expected it to be crazy today. With the new version, though, it worked as I'd expect Slack to: It showed dots for only those slacks that had new messages, and they disappeared as soon as I'd gone through the unread channels. No updated threads or new members, though, so I'll reserve that part for later.

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks

**Comment by rawkode** [comment]
Sorry @Thomas101, I'm still getting this issue with 3.2.0

**Comment by Thomas101** [comment]
@rawkode do you see the issue appearing after sleeping your laptop/changing network connection or is it always there. The 3.2.1 and 3.2.2 beta versions of Wavebox have some additional fixes for slack notifications. If you want to give these a go there's some instructions on how to switch channel [here](https://wavebox.io/kb/beta-channel)

**Comment by gilles** [comment]
I have the same issue on 3.10.0

Seems this call `URL:https://slack.com/api/users.counts?token=<EDITED>&simple_unreads=true&mpim_aware=true` is not working anymore

```
Request URL:https://slack.com/api/users.counts?token=<EDITED>&simple_unreads=true&mpim_aware=true
Request Method:GET
Status Code:200  (from disk cache)
Remote Address:<EDITED>
Referrer Policy:no-referrer-when-downgrade```


```
accept-ranges:bytes
content-length:27169
content-type:text/html
date:Fri, 05 Jan 2018 20:48:51 GMT
etag:"c32746ad89cda7fc5fda5ebbde75b3cb"
last-modified:Fri, 05 Feb 2016 23:46:05 GMT
server:AmazonS3
status:200
via:1.1 5ea17ec24e220cfd5bc26fea52e3a29c.cloudfront.net (CloudFront)
x-amz-cf-id:<EDITED>
x-amz-id-2:<EDITED>
x-amz-request-id:<EDITED>
x-cache:Error from cloudfront
```

The response is 200 and always (from disk cache) I cleared all caches to no avail. Even thought the code is 200 the response is a generic HTML Server Error page.

**Comment by Thomas101** [comment]
@gilles it should be working, however there have been a few reports around this over the last few days. Other users have reported that re-adding the account appears to fix the issue. Would you be able to give this a try?

**Comment by gilles** [comment]
@Thomas101 yup, that worked. thanks

**Comment by geahaad** [comment]
re-adding worked for me, too.
not the most convenient way, but well... :-)

**Comment by mcsauder** [comment]
Not closed. Fix this crap, pretty please. :) Thank you.

**Comment by mcsauder** [comment]
![image](https://user-images.githubusercontent.com/2497951/94510384-e49aa780-01d3-11eb-86d2-e761b5693b66.png)

**Comment by mcsauder** [comment]
No unending amount of clicking on the "x" will make any of the notifications go away, no refresh, no clicking on the "x", nothing, nada.  Isn't everyone experiencing this every day this year?

**Comment by Thomas101** [comment]
Hey, @mcsauder it would be great to know which version you're using so we can help diagnose the issue. Also, do the badges in the sidebar (i.e. next to Alex and Jacob) ever disappear?

**Comment by mcsauder** [comment]
Hi @Thomas101 , thanks.  The issue is not always the same, but crops up the most in Windows using the Chrome browser:
![image](https://user-images.githubusercontent.com/2497951/96942543-ade24500-1492-11eb-99f9-1626704ba730.png)

I see this in Linux using Firefox weekly as well.  Reloading the page, closing and restarting the browser, nothing I do seems to have much impact aside from allowing time to pass.

**Comment by mcsauder** [comment]
I'll start a new issue to quit necro-bumping this one.
