### ISSUE TITLE
3.18 installed as a snap app - different cursor

### ISSUE THREAD

**Issue by fsdias** [wavebox/waveboxapp#204]
Wavebox 3.18/Ubuntu 16.04

I installed it as a snap app and:

- font type is different from that of wavebox installed with a .deb

- cursor is shown as a small hand instead of an arrow

- if the user clics on a hyperlink nothing happens

**Comment by rmtilson** [comment]
I tested the snap install too and noticed the same. Plus the notification icon looked normal but when right clicking had a windows 95 feel about it. 
I wasn't sure if it was the app or how snap is implemented in Fedora.

**Comment by Thomas101** [comment]
Thanks. It's probably down to the bundled libraries. I'll take a look!

**Comment by tbraeutigam** [comment]
Looks like a xdg-open bridge is missing for links...
See:
https://github.com/snapcore/snapd-xdg-open
https://askubuntu.com/questions/831666/xdg-open-from-within-a-snap
https://www.mail-archive.com/snapcraft@lists.snapcraft.io/msg00076.html

And might be good to look at: https://insights.ubuntu.com/2017/06/09/ubuntu-desktop-weekly-update-june-9-2017/ 
It mentions a gnome 3.24 platform snap in the edge-channel.

PS: Not quite sure where I can find the snapcraft.yaml file for wavebox?

**Comment by Thomas101** [comment]
Thanks @tbraeutigam !

The link-open issue is due to fall next week in the 3.1.9 release.

* Font type looks like an [upstream issue](https://bugs.launchpad.net/snappy/+bug/1621568)
* Cursor looks like an [upstream issue](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1579268)

**Comment by Thomas101** [comment]
Hi, the link issue has been fixed in the latest version of Wavebox. To make the link opening work you'll need to install `snapd-xdg-open` which can be done though `sudo apt install snapd-xdg-open`. Thanks!

**Comment by fsdias** [comment]
Another note: the add attachment dialog looks like this o Ubuntu 16.04

![screenshot from 2017-08-22 10-14-30](https://user-images.githubusercontent.com/5689181/29558032-d5876410-8722-11e7-8b6d-18711909a4e4.png)

**Comment by nmat** [comment]
Tested this on 17.10 of ubuntu on snap package and deb package.

Snap package (as mentioned before does use wrong font and cursor which seems also to be reported in upstream)

Deb package seems to work just fine.

Regarding the dialog for attach files. @fsdias do you mean the theme is wrong? or what seems to be the exact problem there?

**Comment by bearhagen** [comment]
Running Ubuntu 17.10 with Wavebox 3.4.0.

Links are not working, I also get the weird hand cursor and context windows looks like windows 95.
The latter issues which are upstream doesn't really matter too much, links however, is more important.

Any idea how I can get them working?
I have xdg-utils and snapd-xdg-open installed.

**Comment by nmat** [comment]
@bearhagen the cursor problem is from snap packaging and links I can imagine also is part of it. See below:

https://bugs.launchpad.net/snappy/+bug/1621568
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1579268

**Comment by Thomas101** [comment]
As an update to this, the latest beta (3.5.2) no longer needs `snapd-xdg-open` installed. Links should just open as you'd expect

**Comment by Thomas101** [comment]
Version 3.7.0 has some improved font support, so should look a little better than previously

**Comment by Thomas101** [comment]
The lack of native cursor support with Snap packages, is something that affects all snaps and is down to the way that Snaps isolate the app on the operating system. The snap team are aware of this [issue](https://forum.snapcraft.io/t/electron-pointer-cursor/1970) but until they provide a fix, this isn't something that Wavebox is able to work around.

If the native mouse icon is something you need, we recommend installing with one of the repositories we offer on our [download page](https://wavebox.io/download) which don't have this issue.

If you are moving from a Snap version to a different one, there's some helpful information about restoring your data in this [KB article](https://wavebox.io/kb/data-when-reinstalling-wavebox).

Fonts and link opening was fixed some time ago, so I'm going to close this off for now, but if you still feel like there's something missing or that needs improvement, feel free to re-comment or open another issue and we'll take another look.
Thanks!
