### ISSUE TITLE
[Request]: Backup. Import / Export

### ISSUE THREAD

**Issue by theeluddite** [wavebox/waveboxapp#207]
Request to add a feature to backup account settings so I can quickly add my accounts to a secondary computer or re-add my accounts after a re-installation.

* Which version of Wavebox are you using? [3.1.8]
* Which Operating System are you using?[Ubuntu 16.04 primary Desktop Windows 10 secondary laptop

**Comment by Thomas101** [comment]
Thanks, we'll take a look

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox, you can find the tools under settings. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
