### ISSUE TITLE
[feature-request] be able to have invisible helper running in background checking mail

### ISSUE THREAD

**Issue by Evertt** [wavebox/waveboxapp#209]
First of all I want to say I love your app and I think it is definitely worth the price! I'm going to buy the first year of the full version when the trial expires.

Just for the record, I'm on macOS.

I always want to be able to get notified of new email coming in. And yet I don't always want to have the mail app open, because that pollutes my dock and app switcher. So I would love it if I could run an invisible helper in the background that regularly checks for new mail and notifies when I have one and when I click on the notification the mail app would open.

Maybe you could even make it so that the menubar icon would be part of the invisible helper so I could still have that one while the actual mail app is off. (For some reason I don't mind pollution in my menubar, so I would really like the icon to stay there.)

**Comment by Thomas101** [comment]
Looks like there's support for this (https://github.com/electron/electron/blob/master/docs/api/app.md#apphide-macos) I'll look at adding it in!
