### ISSUE TITLE
Printing doesn't work

### ISSUE THREAD

**Issue by alex-figge-schuster** [wavebox/waveboxapp#21]
Wavebox 3.1.2
Windows 10 64 bit

When you try to print from within Wavebox, e.g. printing an email in Inbox, the print dialog opens and you can choose your printer. The print job is sent to the print spooler but hangs in the print queue. You even can't delete it from the print queue without a restart.
This bug already existed in WMail and as far as I know it concerns the mac version too.

I often need to print some emails (e.g. invoices I got via email) and have to go to the browser version of inbox in order to print mails, which is not efficiently as using Wavebox only.

**Comment by Thomas101** [comment]
Hi, is this with Gmail or Google Inbox accounts?

**Comment by alex-figge-schuster** [comment]
With Google Inbox (didn't test with Gmail)

**Comment by jacksarick** [comment]
Just tested from Gmail, Google Inbox, and Outlook, with no problem. Any chance it could be your printer that's having an issue?

**Comment by alex-figge-schuster** [comment]
I don't think that my printer is the problem because I respectively we have the same problem on a Windows PC (Win10) and on a Mac (which both use a Sharp network printer).
Additionally I've been able to reproduce the issue on another Windows PC which is not on the same Network. On this Windows PC I used "Adobe PDF" as printer and had the same issue. That's why I think my printer is not the problem.

**Comment by Thomas101** [comment]
Hi @alex-figge-schuster it would be good to know which print button you're using (e.g. the three dots on an email and print, or printing an attachment etc). Would you be able to try printing to PDF on Mac? This normally uses the built in Mac printing support and it would be good to know that works/doesn't work. Thanks!

**Comment by Thomas101** [comment]
Looks like there was an upstream electron issue. The release that went out on friday had a fix for `Fixed an issue where print jobs would stay in the spooling state indefinitely
and selected page ranges would not print correctly` which sounds suspiciously like this. I've updated and this will be going out with the next release shortly :)

**Comment by Thomas101** [comment]
Hi a fix for this has just been release in 3.1.3. Wavebox will autoupdate shortly or if you want to get it sooner you can either re-launch Wavebox to trigger an autoupdate or redownload from https://wavebox.io/download Thanks!

**Comment by alex-figge-schuster** [comment]
Works in 3.1.3. Thank you for the fix.

**Comment by twistedspur** [comment]
When I try to print attachments (Win 10, Wavebox 3.15), all that happens is a File Explorer window opens (at Quick Access, which is my default). 

This happens from Gmail when I'm trying to print a PDF, Word Doc, or Excel spreadsheet, 

but not a .png or jpeg.

Obviously I only usually need to print a PDF or Word doc.

**Comment by Thomas101** [comment]
@twistedspur I'm seeing the same. Have opened a separate issue to track this #136. Thanks

**Comment by suzerovideo** [comment]
This is still an issue for me on Wavebox Version: 3.1.8, Mac OS Sierra. Gmail.
Clicking an attachment opens a preview (with dark background). At the top right there is a print icon. If I click it nothing happens. Doing the same in GMail via web-browser works fine.
<img width="198" alt="screen shot 2017-06-12 at 11 03 06" src="https://user-images.githubusercontent.com/29371426/27026638-bcd39124-4f5e-11e7-9981-7c51ef365962.png">

**Comment by Thomas101** [comment]
@suzerovideo is it a PDF attachment? #136 is covering this issue at the moment
