### ISSUE TITLE
Can't log into Feedly

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#211]
* Wavebox 3.1.8
* Windows 10

I added feedly.com as a website but am unable to log in.  A separate login window pops up, let's me successfully log in, but Wavebox never refreshes with the login token.

It seems others are using feedly based on the fact that there's a custom CSS styling. 

What am I doing wrong?

Thanks!

**Comment by Thomas101** [comment]
This was working, but it looks like something has changed on feedly itself. I'll try to dig through what's happening. Thanks!

**Comment by adrianaoun** [comment]
i can also repro - 3.1.8 on mac

**Comment by maltejanosch** [comment]
- Wavebox 3.1.8
- macOS Sierra

I also have this problem.
I am getting a small popup next to the login popup, that tells me to disable the popup blocker. This may be helpful in finding the issue! --> https://maltegrapentin.com/wavebox-feedly.png

--
Thanks for the hard work!

**Comment by Thomas101** [comment]
@maltejanosch thanks!

**Comment by joslemmons** [comment]
I am also experiencing this problem, the exact same way.
• macOS 10.12.5
• Wavebox 3.1.8

**Comment by mickmel** [comment]
Same issue here. Windows 10, Wavebox 3.2.0.

**Comment by mickmel** [comment]
I should add that I have the same issue with any site that does a pop-up to authenticate with Google. With Asana, for example, I can't get in using Google, but if I just enter name/password directly on the site it works fine. Not sure why it has issues with that, but I hope that's helpful for you.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by maltejanosch** [comment]
@Thomas101  
With the beta channel, I tried signing in to Feedly with my google credentials. That failed. 
I then signed in with Feedly directly and that worked! Thanks 😄 and Happy Holidays!

- Wavebok 3.7.1 beta
- MacOS 10.13.1

**Comment by Thomas101** [comment]
@maltejanosch did you use Feedly from the account list or add as a Weblink account type?

**Comment by maltejanosch** [comment]
@Thomas101 
I did it with the Weblink, but I just tried it through the account list and there it worked with the google log in!

**Comment by GollyJer** [comment]
Feedly working great in 3.7.1.

Thank you!!

**Comment by yochananmarqos** [comment]
I had this issue with 3.7.0 so I tried 3.7.1 beta and still have the same issue. I built it from the AUR on Manjaro Linux.
