### ISSUE TITLE
Is there a way to open a Trello account to a specific board?

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#212]
I have three Trello accounts and they all open to the generic 'boards' list when Wavebox opens.  Then I have to go to each one and open the correct board.  I just paid for Wavebox to have Trello functionality but this isn't pretty painful. :-(

**Comment by Thomas101** [comment]
Not at the moment. Are these boards all on the same account or different accounts? There's been some discussion here about running the boards out as services (in a similar way that Google accounts have drive, contacts etc...). I'm wondering if that would also work for you?

**Comment by GollyJer** [comment]
Hi Thomas. Thanks for following up.

They're all on the same account. Running them out like Google accounts would be awesome.  There is an extra challenge with notifications in Trello though.  They send notifications at the account level.  This caused a separate issue with Wavebox in that if you have two Trello's set up in Wavebox you get duplicate notifications.

In the end I decided to forgo notifications and add each board as a website.  This way they always open to the correct board.

Then I installed a separate Windows 10 Trello client just to get notifications so I know when to go look at Wavebox.

I follow the exact same procedure for Facebook Messenger. 
Love Wavebox but need notifications! 😄

**Comment by MichaelTunnell** [comment]
It is technically possible if you add them as Custom Web Links accounts instead of Trello accounts and that way the link can be directly to a board.

It would be better to be able to do it in a single Trello account structure but that is a possible workaround if you want to try it.

**Comment by GollyJer** [comment]
> In the end I decided to forgo notifications and add each board as a website. This way they always open to the correct board.

😃

**Comment by Thomas101** [comment]
Hi this has just been released to the latest version (3.3.0 & 3.3.1beta). Once downloaded, if you right click on your account and go to Account settings. In there you will find a `Home board` option where you can pick which board opens by default.
