### ISSUE TITLE
MacOS Text Shortcuts Doesn't Work in WaveBox

### ISSUE THREAD

**Issue by fatihturan** [wavebox/waveboxapp#213]
Hi,

I've set some [text shortcuts](https://i.stack.imgur.com/kqXfv.png) on System Preferences/Keyboard/Text section in MacOS. But these shortcuts doesn't work in Wavebox. So, is there anyway to fix this issue?

Thanks. 

[Weavebox Version: 3.1.8 / MacOS 10.12.5]

**Comment by Thomas101** [comment]
We will need to add support in for these

**Comment by Thomas101** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MacOS Autocomplete](https://trello.com/c/MgxCcBcy/230-macos-autocomplete)

**Comment by Thomas101** [comment]
Hi, I'm folding this into issue #248 so we can track progress in one location
