### ISSUE TITLE
Linux Debian Stretch: "Incorrect distribution/InRelease" during repo update

### ISSUE THREAD

**Issue by keypey** [wavebox/waveboxapp#216]
Hi.

* Which version of Wavebox are you using? [e.g. 3.0.0]
- 3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
Linux  4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux
--
Problem updating wavebox repository:
"W: Invalid distribution: https://wavebox.io/dl/client/repo x86_64 / InRelease (expected x86_64 /, and received)"
--
This is not a problem with the wavebox, but a problem with the repository update.

Please check that https://wavebox.io/dl/client/repo/x86_64/ InRelease contains the appropriate packages.

Regards,
kp.,

**Comment by Thomas101** [comment]
Does the package still install correctly after the warning? It did when I tried it...

**Comment by keypey** [comment]
Yes.
kp.,

**Comment by Thomas101** [comment]
Thanks this has now been fixed

**Comment by keypey** [comment]
It works.  Thanks!
