### ISSUE TITLE
Google Calendar Invitations

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#217]
In Google inbox you're able to accept a calendar invitation without opening the email. This keeps it unread but marks the bundle as read in Inbox - results in a phantom unread item

**Comment by vvviiimmm** [comment]
Any chance this issue being fix in the near future?

**Comment by Thomas101** [comment]
We are looking into ways we can fix this. There's some more discussion in #269 around the root of the problem and some different solutions if you're interested

**Comment by Thomas101** [comment]
Goingto merge this into #269 so we can continue tracking from there
