### ISSUE TITLE
Feature Request: Provide a way to get the URL of an open tab

### ISSUE THREAD

**Issue by mimshwright** [wavebox/waveboxapp#218]
I'd like to be able to access (see or copy the URL or open in a browser) of whatever page is currently open in my main view. That would make it easier to move work over to a browser window for example or to update a tab's starting url to the current view.

* Which version of Wavebox are you using? 3.1.8

* Which Operating System are you using? Mac OSX 10.12.4

**Comment by Thomas101** [comment]
Hi, on Trello, Slack & Any Web Link accounts and also in Wavebox popup windows you can right click and copy the current page url or open it directly in the browser. Is this what you're after or do you have use for it on other accounts too?

![screen shot 2017-06-02 at 09 52 39](https://cloud.githubusercontent.com/assets/103586/26718541/3e6a56ca-4779-11e7-85ab-3fcbcb590e8b.png)

**Comment by mimshwright** [comment]
Opps! That is what I wanted. Sorry for the extra ticket!
