### ISSUE TITLE
Cannot download file from outlook email

### ISSUE THREAD

**Issue by huangv22** [wavebox/waveboxapp#219]
* Which version of Wavebox are you using? 3.1.8
* Which Operating System are you using?Mac OSX 10.12.5,

Using Outlook to check email.
Try to download file
Launches a new email

Expected: Download to commence
Actual: Blank Screen
![https___outlook_office365_com_owa_service_svc_s_getfileattachment_id_aamkagfioty0njjlltjjntytndlmns05odczltu2ymfhzgq5mge4zqbgaaaaaabicqyac94vq4jouwoqzgeebwchypnpgtbjs4dkixospnghaaaaaaemaachypnpgtbjs4dkixospnghaaaxokpmaaabegaqahwm6h8qdtxhr4f](https://cloud.githubusercontent.com/assets/4745333/26685473/1b35b134-469f-11e7-90cb-e600167ed6db.png)

**Comment by Thomas101** [comment]
Thanks I'll take a look. Possibly related #182

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
