### ISSUE TITLE
Unread count not showing on account icon

### ISSUE THREAD

**Issue by JohnOz66** [wavebox/waveboxapp#22]
* Which version of Wavebox are you using? [e.g. 3.0.0] - 3.1.2

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] - Windows 10

Accounts have 'Show unread badge' and 'Add unread messages to app ..' enabled but the account icons don't show any unread messages when there is a number of them.

Also, when hovering on the account icon of the sidebar the pop out shows 'no unread messages' when there are messages not yet read in the account.

![image](https://cloud.githubusercontent.com/assets/27000049/24794052/8811a928-1bc7-11e7-87ee-fc95d123149b.png)

**Comment by Thomas101** [comment]
Hi, if you right click on the account and go to settings, which unread mode is selected?

**Comment by JohnOz66** [comment]
It's currently set to "Unread Messages in Primary Category' for Gmail.

**Comment by Thomas101** [comment]
Judging by your screenshot it looks like you're using the priority inbox. I think switching to "Unread Important Messages" should work

**Comment by JohnOz66** [comment]
Sweet, that worked. Thanks :)

**Comment by Thomas101** [comment]
Awesome! Glad to help!
