### ISSUE TITLE
Feature Request - Bitbucket / Github Native Support

### ISSUE THREAD

**Issue by mindfullsilence** [wavebox/waveboxapp#220]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX Sierra 10.12.5

Add native support for Bibucket/Github.

**Comment by Thomas101** [comment]
Hi we've got an issue with new account type requests (#130) along with a voting form to help us prioritize new services. I've added Bitbucket and Github to the list! Thanks
