### ISSUE TITLE
Error attachment with Gmail/Gsuite account (restriction from Google)

### ISSUE THREAD

**Issue by renaudManda** [wavebox/waveboxapp#221]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.11.6

* Description:
Since today when I try to add an attachment to an outgoing email (using Gsuite email account) I see an error message.

When I open the console I see error from Google due to some restriction

![capture d ecran 2017-06-06 a 11 27 43](https://cloud.githubusercontent.com/assets/1856326/26822707/534426cc-4aab-11e7-9a05-7ba963ec02cc.png)

**Comment by Thomas101** [comment]
Hi, Thanks for reporting. It would be great to know the following so I can reproduce it my end...

* Is this with Gmail / Google Inbox
* Was this when adding the attachment through drag & drop or by using the attachment button?
* What file format was the attachment?

If you try reloading Wavebox do you still see the same issue?

Thanks!

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
