### ISSUE TITLE
Allow to share sessions between accounts

### ISSUE THREAD

**Issue by tvvf** [wavebox/waveboxapp#223]
* Which version of Wavebox are you using? 
3.1.8

* Which Operating System are you using? 
MacOS Sierra 10.12.5

My company has a custom Single Sign-On provider with 2-Factor Auth integrated with Google Apps and some internal systems. I bought WaveBox Pro to get them all into one application window separate from the normal browser. But currently, I have to authenticate in all of them separately, which is a hassle. 

Can you please add a way for multiple accounts to use the same session? I imagine it to be something like an option in the account preferences: "Share session with account: {dropdown from which I can choose _one_ other account}".

**Comment by Thomas101** [comment]
Is it just one Google Mail account you have and then multiple Any Web Link Accounts? We're looking at adding Any Web Links as an account service which also share the same session with the parent account. I wonder if this might work for what you're trying to do?

**Comment by tvvf** [comment]
That might work, I think.

Let me get back to my setup: In our company, the company itself operates 
an SSO solution. This solution is also used for GMail/GApps and some 
internal services. So it's not that they all share the GMail 
authentication but rather that they all share the same authentication 
that's also used for GMail.
That being said, except for GMail they are all configured as additional 
Web Links, so Web Links sharing the session with GMail would still work.

The same goes for the Skype web app as a Web Link sharing the 
outlook.com account.


Thanks,
Thomas


------ Originalnachricht ------
Von: "Thomas Beverley" <notifications@github.com>
An: "wavebox/waveboxapp" <waveboxapp@noreply.github.com>
Cc: "Thomas" <tvf@home.a4net.de>; "Author" <author@noreply.github.com>
Gesendet: 12.06.2017 16:02:53
Betreff: Re: [wavebox/waveboxapp] Allow to share sessions between 
accounts (#223)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account by right-clicking on one of the tabs and picking `Add another service`. This will allow all the services in the same group to share the same sandbox.

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
