### ISSUE TITLE
Spellchecker multi-language support

### ISSUE THREAD

**Issue by Filip0** [wavebox/waveboxapp#224]
* Which version of Wavebox are you using? [3.1.8]
* Which Operating System are you using? [Ubuntu 17.04]

As a non native English speaker I use multiple languages daily, therefore it would be nice to easily switch which language the spellchecker is using. Something like chrome has today, where spellchecker language is an option in the context menu.

**Comment by Thomas101** [comment]
I think this should be easy enough to add in. I'll take a look

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by Filip0** [comment]
Just checked out the new version. It works great!
