### ISSUE TITLE
No notifications after network loss

### ISSUE THREAD

**Issue by rmtilson** [wavebox/waveboxapp#227]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Fedora 25

I have noticed that when i drop network connectivity or switch between wireless and ethernet the notifications for email stop working. I try reloading and resyncing but the only thing that resolved is to close out and relaunch.

**Comment by Thomas101** [comment]
Hi, when the network drops are you still able to use Google/Microsoft/Slack etc? E.g. by sending a message or email? Would you also be able to try the following...
* Go to View > Developer Tools and click on the console tab
* Change network/disconnect & relaunch etc
* Right click on one of the accounts and pick resync
Does this result in any new errors coming up in the console?

**Comment by rmtilson** [comment]
When network drop it is intentional on part, as i am mostly switching between wireless and wired.

I received no errors when trying to resync, but here is the output from the console.

[cid:457ced64-dcf1-4326-b9e9-c185ce0af565]




________________________________

**Comment by Thomas101** [comment]
The output got chopped off the end of the issue. Could you try resending it? Thanks

**Comment by rmtilson** [comment]
![screenshot from 2017-06-12 10-33-20](https://user-images.githubusercontent.com/28509039/27040634-9ac56d36-4f5f-11e7-8110-fdd14c3d6ef0.png)

**Comment by Thomas101** [comment]
Thanks for resending that. Next time it happens if you try <kbd>Ctrl</kbd>+<kbd>R</kbd> does it start working after that?

**Comment by rmtilson** [comment]
When hitting CTrl+R it takes the currently selected mail message into draft for reply.


________________________________

**Comment by Thomas101** [comment]
That sounds like Outlook capturing that shortcut. If you go to View > Reload it should have the same affect.

Which account types do you have on the machine?

**Comment by Thomas101** [comment]
Managed to find the bug! Thanks

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
