### ISSUE TITLE
Ctrl+Tab kills Wavebox.

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#229]
On Windows 10...

I was searching for a keyboard command to cycle through Most Recently Used order of Wavebox windows.  I discovered a couple things.

1.  `Ctrl+Tab` **kills Wavebox**.
1. ``Ctrl+` `` does nothing.
1. `Alt` should toggle the menu, not `Ctrl+\`

**Comment by Thomas101** [comment]
Hi, I've just checked my end and they seem to work as expected. Have you tweaked any of the keyboard shortcuts under advanced? The problems with the keyboard shortcuts above, is this when you're trying to customize them or just use them? Thanks

**Comment by GollyJer** [comment]
Hi Thomas.  It's really weird.  Today nothing is killing Wavebox but none of the *Window Shortcuts* are working except the `Ctrl+<number>` combos.

I guess it's on my end... thanks for taking a look.

**Comment by Thomas101** [comment]
That's weird. Is it none of the window shortcuts or just a few?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks

**Comment by GollyJer** [comment]
Hi @Thomas101
I Upgraded to 3.2.1 and am still seeing the same issue.

The oulined green work and the red do not work.
Although, looking at the descriptions in more detail I'm not sure what to expect... 
Windows? Mailbox? Service?  What are these in reference to?
![image](https://user-images.githubusercontent.com/689204/28876301-bd7d1e30-7766-11e7-97ba-f7eef674c65d.png)

**Comment by Thomas101** [comment]
**Cycle Windows** if you have more than one Wavebox window open (e.g. the main Wavebox window and maybe a window with a google doc in it), this will swap between them.

**Previous, Next Mailbox** if you have more than one mailbox in the left hand side (e.g. one Gmail an Outlook and a Slack) this will swap between each one.

**Mailbox at Index** same as above, but <kbd>Ctrl</kbd>+<kbd>1</kbd> will go to the very top one, <kbd>Ctrl</kbd>+<kbd>2</kbd> the next one down and so forth.

**Service at Index** in a Mailbox that has multiple services (e.g. you have a Gmail account, with Google Drive, Google Contacts and Google Keep enabled) pressing <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>1</kbd> will open Gmail, <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>2</kbd> will open Google Drive and so-forth

**Comment by GollyJer** [comment]
Ha! OK.  That explains a lot.  I didn't understand how it's meant to work.

What is a top level node?  Account I think?
I have Google Inbox, Trello, and then 5 websites set up and no way to use the keyboard to navigate between them.

![image](https://user-images.githubusercontent.com/689204/28885018-348e19aa-7782-11e7-925d-f2f091f88cb3.png)

Actually, I can `ctrl + number` to get directly to an Account.  _But given your explanation this is a bug because I only have one **Mailbox**._

It's pretty confusing UX.
If you don't mind, here are some suggestions for clarity and functionality...

1. Get rid of **Minimize** and **Cycle Windows**.  The operating system's have those built in.
1. Instead of the concept of **Mailbox** line up with **Accounts**.
**Account Shortcuts**
    `CmdOrCtrl + Tab` - Cycle between Accounts
    `CmdOrCtrl + <` - Previous Account
    `CmdOrCtrl + >` - Next Account
    `CmdOrCtrl + Number` - Jump to Account
**Service Shortcuts**
    `CmdOrCtrl + Alt + Tab` - Cycle between Services in the Active Account
    `CmdOrCtrl + Alt  + <` - Previous Service 
    `CmdOrCtrl + Alt  + >` - Next Service 
    `CmdOrCtrl + Alt  + Number` - Jump to Service in the Active Account

**Comment by Thomas101** [comment]
From your screenshot it looks like you have 8 mailboxes, be them trello, github etc. We should definitely look to rename these to Account though as it is confusing.

> Get rid of Minimize and Cycle Windows. The operating system's have those built in.

Removing these isn't really an option. Although they're common across the OS, they're not implemented by default so have to be included explicitly as shortcuts

As regards some of the shortcuts, using tab has quite a few conflicts with built in OS actions so I would be weary of making this the default.

---

That said I definitely think we should be changing/adding...
- [ ] Change wording of **Mailbox** to **Account**
- [ ] Add Previous & Next Service Shortcuts `CmdOrCtrl + Alt + <` and `CmdOrCtrl + Alt + >` will probably work well here

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
