### ISSUE TITLE
Cannot Add Outlook Nor Office 365

### ISSUE THREAD

**Issue by DennisFaucher** [wavebox/waveboxapp#230]
* Which version of Wavebox are you using? [e.g. 3.0.0] 3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] MacOS 10.12.5

I cannot add Outlook nor Office365 accounts.  I authenticate, the authentication window disappears, no account is added.  I have tried this twice.  TIA.

**Comment by 33b5e5** [comment]
I have this issue on 1 of 2 corporate Exchange/Office365 accounts. I suspect the issue is that one of my organizations hasn't enabled (or has blocked) access to this type of client. Even if that's the case though, the messaging needs to be improved. I had the same experience as the OP, where the authentication seems to be accepted but the account isn't added.

**Comment by Thomas101** [comment]
We should be bringing up some kind of message on failure. If you go to View > Developer Tools and click on the console tab and then try to add one of the failing accounts again do you see an error message come up?

**Comment by ericmorrisbloom** [comment]
This is Wavebox 3.1.8, tested on both Mac OSX 10.11.6 and Windows 10.

I'm having a similar issue. I am redirected to my company's ADFS login, but once logged in the primary window asks me to log in to a generic Microsoft account.

The strangest part is that I'll receive notifications for the work address, but have no way to access them.

**Comment by bradleyjames** [comment]
> I'm having a similar issue. I am redirected to my company's ADFS login, but once logged in the primary window asks me to log in to a generic Microsoft account.

I'm having the same issue on 3.1.8 free version.

**Comment by Thomas101** [comment]
Hi this is because Wavebox only supports Outlook & Office 365 accounts, but not Exchange at the moment. We're working on adding exchange support into Wavebox shortly. I'm going to collapse this and a few other issues in one (#268) to make it easier to track progress and compatibility. Thanks

**Comment by perfecto25** [comment]
Thanks Thomas, looking forward to exchange integration ability. Loving this app so far!

**Comment by dolphinspirit9** [comment]
Any update on this.  I won't even start using it if it doesn't support Exchange.  That's the whole reason I found it is because it was supposed to. Not all universities are using office365 mailboxes, they still use Exchange.

**Comment by dolphinspirit9** [comment]
Would love to recommend this product to our students to help pool their accounts together since they are always trying to pop into Gmail or forward, which causes issues.

**Comment by Thomas101** [comment]
@dolphinspirit9 depending on your setup, there's [some steps you can take](https://wavebox.io/kb/office-365-admin-permission) with your sysadmin to allow Wavebox to work with your accounts.
