### ISSUE TITLE
Websites need to be able to return to Account URL ("Home")

### ISSUE THREAD

**Issue by Mobilizr** [wavebox/waveboxapp#234]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac 

I am using the Website accounts a lot in Wavebox. But as I navigate through the website, I often need to return back to the main URL of the account. This is not always a websites main home page. Or sometimes the website or web app does not have a logo to return home quickly. If you could add a menu option or keyboard shortcut to return to the Websites Account defined URL as "Home" that would be great.

**Comment by Thomas101** [comment]
We're planning on adding toolbar along the top of these accounts with some options to navigate home/back/forward/refresh etc. As you say with these not being so tightly integrated you can quite easily get lost!

**Comment by Mobilizr** [comment]
I love the fact that the UI is so minimal so please make the toolbar optional. At the moment all I need is a way to return home via a right-click or View menu option. But a minimal toolbar might be useful in some cases.

Thanks for your help and a great tool.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. Context menu items have been added for navigation and additionally under account settings you can toggle `Show Navigation Toolbar` to show the controls on screen permanently.

You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by Mobilizr** [comment]
Works absolutely perfectly. Thank you 👍

**Comment by bradjc** [comment]
Did this get removed in a later release? I can't find that option.

**Comment by Thomas101** [comment]
@bradjc  No still there. Depends which account you've added as to whether it has the navigation bar or not. If it's gmail/microsoft/slack/trello these don't have it. For all other account types the navigation bar should either be enabled by default or can have it enabled through their account settings
