### ISSUE TITLE
"1 unread message" when there are none

### ISSUE THREAD

**Issue by jtmellen** [wavebox/waveboxapp#235]
Version 3.1.8

Mac 10.12.5

There are no unread emails being displayed.  But it shows "1 unread message".  After closing and reopening, still appears.

**Comment by mjspeck** [comment]
I have a similar problem. One of my slack channels says it has "new unseen notifications" which is incorrect. I've tried reloading, resyncing, and removing the account and the issue persists.

**Comment by SandiKingPCO** [comment]
Same. 2 of my Slack accounts are fine, it only persists in this one. Have reloaded, re-synced as well as deleted account and re-added it. Notification persists. 
![image](https://user-images.githubusercontent.com/29376445/27036050-a1585676-4f51-11e7-9cc4-41f024b3e1f6.png)

Version 3.1.8

**Comment by Thomas101** [comment]
If you try opening the account and then pressing <kbd>Shift</kbd>+<kbd>ESC</kbd> does this remove the unread message? If not, if right click on the Wavebox button in the Tray, go down the affected slack account, which channel is it showing there? If you go to that channel does it clear the badge?

**Comment by SandiKingPCO** [comment]
Hi, thanks for you quick response! It does not :(

When I right click on the Wavebox button in the try, I see no options to
"go down the affected slack account"

Here's a link to a gif showing what options I do have.

http://pics.pco.bz/3k2H3N0b3b1A

**Comment by Thomas101** [comment]
Whoops Sorry I meant from the bar along the top

![screen shot 2017-06-13 at 08 38 00](https://user-images.githubusercontent.com/103586/27071175-bfd81cc2-5013-11e7-9252-73dfa99e5c9f.png)

**Comment by SandiKingPCO** [comment]
Nope.

From toolbar:

[image: Inline image 1]

It says "No messages" but in the app's sidebar, it says there is one, but
as you can see, there is not:

[image: Inline image 2]

**Comment by Thomas101** [comment]
Hi,

We’ve got a fix together for this which is due to land in the next release. If you want to try it out beforehand I’ve put a early build of  Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_35a1425_osx.dmg). Just a couple of things to bare in mind:
* To install just drag over the previous version of Wavebox.
* When the next version is released this version will update automatically
* If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Thanks!

**Comment by SandiKingPCO** [comment]
Woo hoo! It works! Thanks for the responsiveness. I'll be a pro user, for
sure.

**Comment by mindfullsilence** [comment]
Wanted to mention for anyone stumbling across this - this was happening to me as well for my outlook account. This build fixes also fixes outlook - the only commonality I see was the position of my outlook account and @SandiKingPCO slack account (both being first in the list). Thanks guys.

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by thanosgatos** [comment]
I am having the same issue with Gmail on Windows 10, running Wavebox 3.14.5. Any way to fix this?

**Comment by iobarak** [comment]
i am seeing this issue now with google inbox.
i have an unread message bubble and there are 0 messages in my inbox
