### ISSUE TITLE
Badge and Menu Bar Notifications not working

### ISSUE THREAD

**Issue by sbbeebe** [wavebox/waveboxapp#240]
* Which version of Wavebox are you using? 3.1.8

* Which Operating System are you using? MacOS 10.12.5

Noticed that I had a new message but there was no indication of it in the Menu Bar icon or the Account Badge in the app. In fact, hovering over the Account Badge gives the message - No New Messages, when you can plainly see in the main app panel that there is 1 new message.

Screenshot attached.
![screen shot 2017-06-12 at 12 12 25 pm](https://user-images.githubusercontent.com/4040034/27048444-17664744-4f69-11e7-8f50-a760a6bc70f6.png)

**Comment by Thomas101** [comment]
Hi, it might be that unread mode isn't configured correctly. Can you try the steps in [this KB article](https://github.com/wavebox/waveboxapp/wiki/KB:-Google-Unread-Counts)?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
