### ISSUE TITLE
Opening app leaves me with blank window

### ISSUE THREAD

**Issue by Hadr619** [wavebox/waveboxapp#245]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version: 3.1.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS Sierra 10.12.5
Have been using the app for a little bit when I opened it up and then I saw this.
<img width="1680" alt="screen shot 2017-06-13 at 11 16 02 am" src="https://user-images.githubusercontent.com/9592858/27097650-b969977e-5029-11e7-8104-33f5017685bf.png">

Tried rebooting and reinstalling with no luck. I really hope this is resolved because this was what I was looking for in a a mail app, but it is currently unusable.

**Comment by Thomas101** [comment]
Hi, sorry about this. When you launch it, if you try going View > Developer Tools and click on the console tab do you see an error?

**Comment by Hadr619** [comment]
Looks like its throwing a few errors

<img width="556" alt="screen shot 2017-06-15 at 8 45 57 am" src="https://user-images.githubusercontent.com/9592858/27189809-53328e46-51a7-11e7-81ab-99901d598892.png">

**Comment by Thomas101** [comment]
Wow it looks like something has gone really wrong there. It could be that the data on disk has corrupted somehow. Could you try the following...

1.) Quit Wavebox completely
2.) Open `~/Library/Application Support/wavebox/` and move the following files somewhere safe
 * app_db.json
 * avatar_db.json
 * mailboxes_db.json
 * settings_db.json

3.) Try re-opening Wavebox. If it does launch correctly the accounts you had added will have gone but we can work to restore those from the files you've moved out

**Comment by Hadr619** [comment]
Awesome, that allowed me to get the app open and set things up again. I do know it all stemmed from trying to switch mailboxes when one mailbox was superimposed on top of the next. An didn't look like they were changing. So I quit and reopened and was greeted with that glorious blank window. Thank you for helping it get back to a working start

**Comment by Thomas101** [comment]
It would be great to find out what went wrong with the underlying data. Could you contact me through the [contact page](https://wavebox.io/contact)?

**Comment by fdrouet** [comment]
Any news here ? I have the same problem this morning

**Comment by Thomas101** [comment]
@fdrouet does following the above steps resolve it for you? Did the problem occur when switching mailboxes for you too?

If you export the files it would be great to see what's happened to them and what's gone wrong with them. Could you also message me through the [contact page](https://wavebox.io/contact)? Thanks

**Comment by fdrouet** [comment]
sorry but too late for me, I recreate all my accounts from scratch.

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. The root issue should be fixed in 3.1.12 and 3.2.0. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks

**Comment by trenaudin** [comment]
I had the same issue with Wavebox 4.4.0 but I cannot find ~/Library/Application Support/wavebox/ There is not a wavebox folder. Also I am using macOS Mojave 10.14.1

**Comment by Thomas101** [comment]
@trenaudin if you launch the app and go to `View` > `Developer` > `Wavebox Developer Tools` a window will popup. In there click on the console tab. Can you send a screenshot of that? It should point to what the underlying error is

**Comment by trenaudin** [comment]
<img width="549" alt="screen shot 2018-11-30 at 8 57 46 am" src="https://user-images.githubusercontent.com/45399332/49296487-0adb4900-f47e-11e8-8c87-66191eba0ecd.png">
<img width="548" alt="screen shot 2018-11-30 at 8 57 38 am" src="https://user-images.githubusercontent.com/45399332/49296488-0adb4900-f47e-11e8-9652-d1a6fdf36733.png">
<img width="552" alt="screen shot 2018-11-30 at 8 57 26 am" src="https://user-images.githubusercontent.com/45399332/49296489-0adb4900-f47e-11e8-8865-6fc7e20397c6.png">
<img width="280" alt="screen shot 2018-11-30 at 8 57 14 am" src="https://user-images.githubusercontent.com/45399332/49296490-0adb4900-f47e-11e8-8c5d-98a2f020ef95.png">

**Comment by Thomas101** [comment]
@trenaudin thanks for sending those across. It looks like an issue with some incorrectly formatted data. I've got a fix together, but this isn't out for general consumption as yet.

Until the fix goes live, there are two things you can try to get back up and running...

1. Remove some of the generated Wavebox data and hopefully the app will recover gracefully. To do this...
    * Open finder in your home directory
    * Press <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd> to show hidden files
    * From your home directory locate `Library` > `Application Support` > `wavebox`
    * Remove or move `acservicedata_db.json`
    * Press <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd> to hide hidden files
    * Restart Wavebox
2. I've uploaded an early release of the app, which you can use until the fix goes live. To use this...
    * Download the app from https://wavebox.io/dl/builds/Wavebox_4_4_2_1261d11_osx.dmg
    * To install just drag over the previous version of Wavebox.
    * When the next version is released this version will update automatically as usual
    * If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

Let me know if this helps!

**Comment by trenaudin** [comment]
Number 2 worked! Thank you!
