### ISSUE TITLE
How to start on reboot

### ISSUE THREAD

**Issue by krash1220** [wavebox/waveboxapp#247]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Wavebox_3_1_8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Linux Mint 18.1

I've tried  /opt/wavebox/Wavebox --mailto=%u and /opt/wavebox/Wavebox  in startup applications and it will not start. It needs to be an option in preferences.
Okay, I did get it to restart with /opt/wavebox/Wavebox but everytime it says oops and retry and I have to click retry.

**Comment by Thomas101** [comment]
Hi, I think it may because it needs to be detached from the terminal process. If you try adding `&` at the end of the command like `/opt/wavebox/Wavebox &` this should work

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
