### ISSUE TITLE
Keyboard shortcut for switching services

### ISSUE THREAD

**Issue by carr** [wavebox/waveboxapp#25]
* 3.1.2
* Mac OSX 10

Question - I'm currently using the cmd+1/2 shortcut to flip between accounts (e.g. 2 separate Gmail accounts).

Is there something similar to that to flip between services (e.g. Gmail and Google Calendar in the same Google Account)?

Couldn't locate a list of keyboard shortcuts anywhere.

Thanks!

**Comment by Thomas101** [comment]
Hi, we just added this in 3.1.2. If you're in an account you can use cmd+alt+1, cmd+alt+2 etc to switch between the services in your current account. If you click on the window menu at the top of the screen this shows you the current shortcuts for switching accounts etc...
![screen shot 2017-04-07 at 11 00 21](https://cloud.githubusercontent.com/assets/103586/24795554/969937e0-1b81-11e7-8883-e193ebca2ec6.png)

**Comment by carr** [comment]
That's it, thank you!

**Comment by carr** [comment]
@Thomas101 btw.after using this for a day, I feel that cmd+shift+1/2 would be a better choice, because it's easier to press with one hand than cmd+alt+1/2.

Just a suggestion.

**Comment by Thomas101** [comment]
I would agree with you, however osx eats up cmd+shift+1 through to cmd+shift+4. 3&4 are used for screenshots. Not 100% sure what 1&2 are used for

**Comment by carr** [comment]
Damn. How does alt+shift+1/2 work?

**Comment by Thomas101** [comment]
That might work. I'll have a look and see what happens

**Comment by huangv22** [comment]
Hey guys, I'm a fan of the cmd / option. Given that moving between accounts use cmd, it's intuitive to add another key for services within the account. Just my two cents!

**Comment by Thomas101** [comment]
Thanks @huangv22 my plan is to keep the current `cmd+option+n` and then try to add the other shortcuts in as hidden global shortcuts. Reason being is if I use `alt+shift+1` the shortcut in the dropdown shows `alt+shift+!` and then `@` for 2, etc..

**Comment by Thomas101** [comment]
Added this in! Support for both `cmd+option+1` and `alt+shift+1` depending on which way you prefer it :)

**Comment by Thomas101** [comment]
This has been added into 3.1.4 which is now live. Thanks!

Wavebox should update automatically after a while, but if you want to hurry it up, just restart the app and it will re-check

**Comment by fvugec** [comment]
Hello @Thomas101, 

unfortunately, this caused that some users (like me) can't write some symbols like "@" or "€".

I'm using Mac and _Croatian - PC_ keyboard, shortcut for "@" is alt+shit+2. I guess there are other keyboards and symbols which are affected by this.

Wavebox v3.1.5, macOS 10.12.4

**Comment by Thomas101** [comment]
@fvugec thanks. We've got another couple of open issues for this #98 and #110. It should be fixed in the next release

**Comment by MichaelTunnell** [comment]
Please change the keybinding for service switching for Linux and Windows users.

Alt+Shift+1,2,3 isn't that bad on MacOS because of the location but the location of PC keyboards is very very awkward. I'd prefer something else like Ctrl+Shift+1,2,3 which would also solve the issue with the custom symbol conflicting as described by @fvugec

**Comment by Thomas101** [comment]
Some of the key combos have conflicting actions depending on OS & keyboard layout. 3.1.6 has support for remapping all the keyboard shortcuts so you can change them to whatever suits best. All being well, hoping to release 3.1.6 beginning of next week


![screen shot 2017-05-04 at 09 28 00](https://cloud.githubusercontent.com/assets/103586/25695689/04329fa0-30ac-11e7-8cd4-89c9a020ee22.png)

**Comment by MichaelTunnell** [comment]
> 3.1.6 has support for remapping all the keyboard shortcuts

Perfect!
