### ISSUE TITLE
Bug? Drag link to Google Keep > full screen

### ISSUE THREAD

**Issue by suzerovideo** [wavebox/waveboxapp#250]
If I drag a link from an e-mail onto the Google Keep icon in the Wavebox sidebar, the link target opens full screen within Wavebox and I can't get back to my inbox without Quitting and restarting Wavebox.

Am I doing something wrong or this a known issue?

Wavebox 3.1.8
Mac OSX 10.12.5

**Comment by Thomas101** [comment]
Thanks. I've fixed this in the upcoming release!

**Comment by Thomas101** [comment]
Hi, this has been fixed in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
