### ISSUE TITLE
Unable to click links in drafts

### ISSUE THREAD

**Issue by nlenkowski** [wavebox/waveboxapp#251]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.12.5

Once a link has been created it cannot be clicked. I encountered the same bug with WMail awhile back and filed an issue, which was resolved. It appears this may be a regression.

Here is a short screencast of the issue:
https://youtu.be/RhUoNCLZ38M

And here is a screenshot of the link UI element that is not responding:

![image](https://user-images.githubusercontent.com/1290235/27138058-e9a56110-511f-11e7-81ad-5cfa5f9d12f5.png)

**Comment by Thomas101** [comment]
Thanks, I'm seeing the same in 3.1.8. Just tested in our development build (which includes an update to chromium) and it works there. If you want to try it out beforehand I’ve put a early build of  Wavebox macOS [here](https://wavebox.io/dl/builds/Wavebox_3_1_8_35a1425_osx.dmg). Just a couple of things to bare in mind:
*To install just drag over the previous version of Wavebox.
*When the next version is released this version will update automatically
*If you want to go back to the currently released version of Wavebox, go to the [Downloads Page](https://wavebox.io/download), download and install over the version you’ve updated

**Comment by nlenkowski** [comment]
Thanks for looking into this so quickly. I just tried the pre-release build and am unfortunately still seeing the issue. I've restarted both Wavebox and Chrome, and even rebooted just to be sure. I've also tried setting Firefox as my default browser to no affect. As an aside, right clicking and selecting "Open Link" from the context menu works as expected.

**Comment by Thomas101** [comment]
Would you be able to try the following. It should give me some more info as to what's going on...

1.) Right click on the account in the left side and go to `Inspect`
2.) In the window that appears, click on the console tab
3.) Paste the following code...

```js
window.open = function () {
  // Open message in new window -- old style
  if (arguments[0] === '' && arguments[1] === '_blank') {
    return {
      document: {
        write: function (value) {
          console.log("write>", value)
          const parser = new window.DOMParser()
          const xml = parser.parseFromString(value, 'text/xml')
          if (xml.firstChild && xml.firstChild.getAttribute('HTTP-EQUIV') === 'refresh') {
            const content = xml.firstChild.getAttribute('content')
            const url = content.replace('0; url=', '')
            console.log("url>", url)
          }
        }
      }
    }
  }
}
```

4.) Retry opening the link (it wont open, but will log some more info to the console)

Can you send me the output of what comes up? Should look something like this....

![screen shot 2017-06-16 at 09 26 50](https://user-images.githubusercontent.com/103586/27218415-f6b54760-5275-11e7-9fb7-551ebfa8c060.png)

After you've tried this you'll need to restart Wavebox to make sure other links work.

Thanks!

**Comment by nlenkowski** [comment]
Sure thing. The console output is:

```
VM1297:7 write> <META HTTP-EQUIV="refresh" content="0; url=http://google.com">
VM1297:13 url> http://google.com
```
No errors or uncaught exceptions were reported.

**Comment by Thomas101** [comment]
It looks like it's picking the link out correctly. If you try pasting `window.open` in the same way as before do you see...

```js
function open() { [native code] }
```

or something like

```js
function () {
    // Open message in new window -- old style
    if (arguments[0] === '' && arguments[1] === '_blank') {
      return {
        document: {
          write: function (value) {
            cons…
```

**Comment by nlenkowski** [comment]
The following is logged after pasting the original `window.open = function () {};` snippet:

```js
function () {
  // Open message in new window -- old style
  if (arguments[0] === '' && arguments[1] === '_blank') {
    return {
      document: {
        write: function (value) {
          console.log("wri…
```

Also, not sure if it's relevant, but I enabled "Use experimental window opener" in the Advanced settings to see what it does. Normal links work fine, but the links in the compose window open an empty new window, then Wavebox crashes with "Whoops! Something went wrong with this mailbox and it crashed".

**Comment by Thomas101** [comment]
Thanks for those. I'll do some investigating to see what it might be.

**Comment by nlenkowski** [comment]
No problem. Thanks for looking into it.

**Comment by Thomas101** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gmail create link in email. Click on link to test - fails](https://trello.com/c/k7td6BvD/227-gmail-create-link-in-email-click-on-link-to-test-fails)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.16. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nlenkowski** [comment]
Glad to hear you were able to resolve the issue! I'll give it a whirl when it hits stable. 

As a WMail -> Wavebox Pro user I just want to say that Wavebox is one of my favorite and most useful apps, and your responsive support is much appreciated. Thanks much! 👍

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox and can be enabled by using the experimental window opener. There’s some instructions on [how to do that here](https://blog.wavebox.io/testing-the-new-window-opener/). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
