### ISSUE TITLE
Opening gmail message in new window doesn't work

### ISSUE THREAD

**Issue by knurdle** [wavebox/waveboxapp#252]
* Which version of Wavebox are you using? 3.1.8

* Which Operating System are you using? MacOS 10.12.5

This is for a gmail account. 
When I click the link to open a mail message in a new window, I'm getting the message
"Grrr! A popup blocker may be preventing the application from opening the page. If you have a popup blocker, try disabling it to open the window."

After I click OK, a new window pops up but it's blank.

**Comment by Thomas101** [comment]
Duplicate of https://github.com/wavebox/waveboxapp/issues/202. We're hoping to have a fix out for this in the next release. Thanks
