### ISSUE TITLE
Preview window in ExFlow is not working

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#255]
* Which version of Wavebox are you using? 3.1.8
* Which Operating System are you using? Mac OSX 10.12.5

ExFlow is an invoicing web-based tool. We use it in at my workplace so I added it to Wavebox as a link. 
However Exflow's preview pane is not loading. All I get is an empty grey area where the preview of the document selected in the righthand list should appear. 

See attached screenshot. I know this isnt much to work with but if you need extra info please let me know. 

<img width="1593" alt="screen shot 2017-06-15 at 11 19 03" src="https://user-images.githubusercontent.com/26086997/27172259-41874db0-51bd-11e7-8834-6aa28be0f216.png">

**Comment by Tahini-123** [comment]
EDIT: It appears that in Chrome the preview pane is using x-google-chrome-pdf plugin to display the document. Is that supported in Wavebox?

**Comment by Tahini-123** [comment]
EDIT 2 : Selecting a document on the list causes the pdf to be downloaded instead of being displayed, which is a far less ideal situation.

**Comment by Thomas101** [comment]
I think the core issue affecting this is the same as #169 and #51

Electron has only just started to add support for pdf rendering, unfortunately there's still a few embed environments it doesn't work with - it appears that this is the same problem. We're hoping to get a fix out for this soon as there's numerous account types it affects at the moment

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
