### ISSUE TITLE
Open Link behaviour

### ISSUE THREAD

**Issue by tbraeutigam** [wavebox/waveboxapp#256]
* Which version of Wavebox are you using? [e.g. 3.0.0] -> 3.1.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.04
----------
The 'Open Link' Behaviour seems to be relatively finicky.

Taking a site called page.company.com, which links to company.otherpage.com, clicking the link will open it in a Wavebox-internal Browser Window, while both 'Open Link' and 'Open in Browser' will open it in my external default browser.

What is the supposed definition of when to open windows in the internal browser or external?
Is there a way to influence the behaviour?
Ie. configure policies for opening links on accounts like: "Open anything not from the exact same domain in Browser' or 'Open all links in Browser' etc.

The current behaviour makes wavebox fairly troublesome to use for quite a lot of pages.

**Comment by Thomas101** [comment]
The open link behaviour that's in Wavebox at the moment refers to when the webpage requests that the page is opened in a new window. This is usually from a JavaScript `window.open()` or link with `target="_blank"` attribute. The reason for having the option in behaviour is there are two use cases. For example...

1.) You open a link to somewhere that expects you to be still signed in, for example in Google Drive clicking to open a document/sheet etc
2.) You open a link to somewhere else on the web and using your web browser is preferable. For example you click a link in an email

There is scope to add some kind of policy in for this to configure different rulesets for different urls. Probably restricting to the same domain would be the easiest one to start with. Do you have an example of any pages where the current behaviour presents problems? Would fixing to the same domain resolve this or partially resolve them?

**Comment by Thomas101** [comment]
We've added tools into the latest version of Wavebox to help aid with this. As well as the open link behaviour in settings for pages that request a link be opened in a new window we now also have `Open link in Browser` and `Open link in Wavebox` when you right click on a link. Hopefully this will allow to open links as required

**Comment by EvHaus** [comment]
I'm on v3.3.0 and can't find the "Open link in Browser" option yet. Is this released yet?

**Comment by Thomas101** [comment]
@EvHaus it went out with 3.3.0 and also 3.4.0 (which has just gone live). If you right click on the account in the left and go to `Account Settings` you should find the setting under the `Advanced` section

![screen shot 2017-10-04 at 11 36 41](https://user-images.githubusercontent.com/103586/31171638-54846f50-a8f8-11e7-8ade-f49fff92b443.png)
