### ISSUE TITLE
wavebox + Office 365 account problem

### ISSUE THREAD

**Issue by kelenka** [wavebox/waveboxapp#259]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version: 3.1.8
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I try to connect office365 account to wavebox and get the message
<img width="480" alt="screen shot 2017-06-16 at 4 45 56 pm" src="https://user-images.githubusercontent.com/29484676/27230049-9afb9de8-52b6-11e7-9493-99e6d6a18775.png">

In office 365 I have Exchange Online (Plan 1) license and User (no admin access) role. 
How can I connect my account to wavebox in a simple way?
Thanks in advance.

**Comment by Thomas101** [comment]
Hi this is because Wavebox only supports Outlook & Office 365 accounts, but not Exchange at the moment. We're working on adding exchange support into Wavebox shortly. I'm going to collapse this and a few other issues in one (#268) to make it easier to track progress and compatibility. Thanks
