### ISSUE TITLE
Different notification sounds per account

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#26]
One for gmail, slack, etc...

**Comment by BertLamb** [comment]
Also ability to have some accounts silent

**Comment by Thomas101** [comment]
Good idea!

**Comment by Thomas101** [comment]
Hi we've added this to the latest version of Wavebox. Here's how to use it...

1.) Open settings & Enable the new Enhanced notifications (these aren't enabled by default in this version)
![screen shot 2017-06-22 at 10 11 24](https://user-images.githubusercontent.com/103586/27427298-65254e38-5736-11e7-8b39-8284468b69d0.png)

2.) Open the settings for each account. The notification sound field will be empty, which means it will use the notification sound set in the main settings. Click on the dropdown and pick from the list of sounds to change it for just this account
![screen shot 2017-06-22 at 10 11 32](https://user-images.githubusercontent.com/103586/27427310-6ed63d2a-5736-11e7-8cb8-0956184ec389.png)
