### ISSUE TITLE
Notifications with o365 should only show messages in "focused inbox" 

### ISSUE THREAD

**Issue by huangv22** [wavebox/waveboxapp#260]
o365 has the option to move to a focused inbox. set the notification badging to only show messages in the focused inbox

* Which version of Wavebox are you using? [e.g. 3.1.8]
* Which Operating System are you using? [e.gMac OSX 10]

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.16. You can find the setting to change to focused inbox by right clicking on your account in the left side and picking Account Settings. Under the Mail section there is an unread mode which will let you pick between inbox and focused inbox.

It would be great to get some feedback on how this works for you. If you haven't tried the beta channel before there are some instructions on [how to use it here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
