### ISSUE TITLE
Can't return main window after closing with a side window open

### ISSUE THREAD

**Issue by aurimus** [wavebox/waveboxapp#261]
Reproduce: Open Google docs, open some document, close main window.
Now you can't get the main window back without closing the document (clicking on the icon just focuses the document)

3.1.8
Ubuntu 17.04

**Comment by Thomas101** [comment]
Thanks, I'll take a look

**Comment by aurimus** [comment]
@Thomas101 the bug is not closing the main window, in fact, it's hard to name it as a bug, rather - intended bad behavior. The workaround is to minimize the main window instead of closing.

I guess a fix would be to minimize the main window when pressed on close if there are additional windows open. In fact in current Ubuntu there is a Unity bug and we don't have tray icon (in fact, there might be something you would be able to change for your app specifically to fix it, I can't report it as a bug though because it's a Unity bug in the first place) .. so anyway, I'm happy with Wavebox in that if I close the main window - it opens back ok when I press the (unhighlighted) icon in Plank / Launcher.

**Comment by Thomas101** [comment]
Thanks @aurimus. There's a workaround for the unity bug upstream so we're hoping to filter that down into Wavebox shortly. I think there's some scope here to add options as to what should happen on close too. In the short-term you could try disabling the tray from Wavebox. This will make closing the main window quit the app

![screen shot 2017-06-21 at 12 32 46](https://user-images.githubusercontent.com/103586/27382735-0b897158-5680-11e7-8cb6-1e59a26b44a3.png)

**Comment by Thomas101** [comment]
Just come around to fix this and I think it may have already been fixed in version 3.2.0+
