### ISSUE TITLE
Closing wavebox doesn't stop the process (Linux)

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#263]
It disappears from my dock (running apps) but a process is still running. Launching it again just instantly shows Wavebox as if it was minimized.

* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Ubuntu 17.04

**Comment by Thomas101** [comment]
Normally it gets minimized to the tray icon, but there's an upstream bug in electron (https://github.com/electron/electron/issues/9046) which means the tray icon fails to show on 17.04. It has been fixed upstream but we're waiting for the next electron release before filtering this down.

For the short term, if you disable the tray icon in Wavebox it will quit correctly.


![screen shot 2017-06-21 at 12 32 46](https://user-images.githubusercontent.com/103586/27382197-c9052b4e-567d-11e7-821e-d4d487a0f7e5.png)

**Comment by Naatan** [comment]
Thanks! :)

**Comment by Thomas101** [comment]
Hi we've just released this into the beta channel if you want to give a try. There's some instructions on how to [get the latest beta release here](https://wavebox.io/kb/beta-channel). Thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
