### ISSUE TITLE
Links don't open after transferring config to another computer

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#264]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Ubuntu 17.04

I transferred my config from one linux machine to another, everything seems to work fine except links do not open at all. No error far as I can tell. I assume it has the browser configured somewhere, but I can't find a pref to change it.

**Comment by Thomas101** [comment]
Which links are these? Just any in a page?

Which install method did you use? If it was through a snap package, we've got a fix for this coming out

**Comment by Naatan** [comment]
Any links in any "app". Links that would before open in my browser now just do nothing at all.

**Comment by Thomas101** [comment]
Do you have `xdg-open` installed on the machine? If you try `xdg-open "https://wavebox.io"` does that open a link?

How did you install Wavebox, through the deb installer, apt repository, snap package, or just using the tar?

**Comment by Naatan** [comment]
`xdg-open "https://wavebox.io"` does indeed work.

I installed it via a snap package.

**Comment by Naatan** [comment]
Finally managed to solve this with:

https://askubuntu.com/questions/831666/xdg-open-from-within-a-snap

Perhaps you could add that as a dependency.

**Comment by Thomas101** [comment]
Thanks, 3.1.11 just went out with this. We've still go the download instructions on the website to update with the additional dependency :)
