### ISSUE TITLE
When clicking a slack notification the slack interface reloads

### ISSUE THREAD

**Issue by brad-decker** [wavebox/waveboxapp#266]
* Which version of Wavebox are you using? 3.1.8

* Which Operating System are you using? personally linux, teammate using MacOS

When you click on a slack notification it will cause slack to reload before loading the corresponding notification. Even if you currently have the application focused.

**Comment by Thomas101** [comment]
Thanks. We're looking to see if there's a way to change channel without reloading the window

**Comment by filiplange** [comment]
same issue here.
V3.1.8. @ Win 7

**Comment by yoavf** [comment]
+1

**Comment by Thomas101** [comment]
Hi, we've put a fix out for this in the beta channel. There's some instructions [here](https://wavebox.io/kb/beta-channel) on how to switch across so you can give it a try

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
