### ISSUE TITLE
Unread counter does not work

### ISSUE THREAD

**Issue by MarkaPola** [wavebox/waveboxapp#27]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.2
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.12.4

Configured with two Google Inbox accounts.

The unread count is not managed as expected. The unread count is only updated to the right value when application is launched. After that, the counter remains the same regardless mailbox activity (new messages, messages deleted from another machine, etc...).

Two important information:
* WMail 2.3.1 with the same configuration works like a charm.
* There is one important difference : it is no longer possible to set proxy with Wavebox. And I am using a proxy and manually set it in WMail.

**Comment by Thomas101** [comment]
Hi, we changed the way WMail handles proxies & removed the configuration screen in WMail 2.2.1. It should be automatic. Wavebox uses the same mechanism so that might not be the issue.

If you re-launch Wavebox, then go to View > Developer Tools and click on the console tab do you see any errors/warnings?

**Comment by MarkaPola** [comment]
Hi,

Yes I see a lot of errors regarding WebSocket connections.
I have the following sequence repeated many times:
[21772:0407/134704.490186:INFO:CONSOLE(61)] "WebSocket connection to 'wss://wavebox.io/socket/websocket?clientId=eca9e84e-663c-4fd3-a629-3a86d92a230f&clientToken=704c5d45487148ba925ae420f8ab73cc&vsn=1.0.0' failed: WebSocket opening handshake timed out", source: file:///Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxes/mailboxes.js (61)
[21772:0407/134704.490908:INFO:CONSOLE(30)] "[SYNCS] Error connecting", source: file:///Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxe/mailboxes.js (30)
[21772:0407/134704.490999:INFO:CONSOLE(30)] "[SYNCS][WebSocket] Next retry LongPoll", source: file:///Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailbox/mailboxes.js (30)
[21772:0407/134705.557756:INFO:CONSOLE(30)] "[SYNCS][LongPoll] Socket opened", source: file:///Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxe/mailboxes.js (30)
[21772:0407/135204.526761:INFO:CONSOLE(30)] "[SYNCS] Upgrading to WebSocket", source: file:///Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxe/mailboxes.js (30)

**Comment by Thomas101** [comment]
Thanks for that. It looks like it's connected to the update socket alright using LongPoll. (Probably the proxy server is blocking websockets - but that's okay). If you try re-adding the account or if you have a different google account does that work?

**Comment by arooni** [comment]
Also having same problem as described Mac OS X 10.12.4.  Great software by the way

**Comment by Thomas101** [comment]
@arooni does the unread count update when you launch Wavebox?

**Comment by MarkaPola** [comment]
Hi,

I have two accounts. Both have same problem.
But, after deleting and re-creating one of the accounts, seems to work... ?!
I will continue to monitor the behavior of Wavebox during the day let you know the result.

**Comment by Thomas101** [comment]
Okay thanks. We think something might have gone wrong on Google's end when authenticating some of the accounts. Have been seeing high latency recently

**Comment by MarkaPola** [comment]
After some monitoring and tests, here are my findings:
* Works behind my proxy if, and only if, I am only one account (inbox). If I add a second inbox account, unread mail counter is not updated (only updated when application is launched)
* unread count update is done around 30 seconds after the action. I.e. if I read or delete an unread mail, I have to wait 30s for the counter to be updated, which is a pretty long time

**Comment by Thomas101** [comment]
Thanks for the info. If you use the machine without the proxy do you see both accounts start updating again? I've added some debug into version 3.1.3 to see if we can find out what's happening with this. Would you be able to give the following a try?

* Check you're on version 3.1.3 by going to the about screen. If not, restart Wavebox and wait a couple of minutes it should autoupdate or re-download from wavebox.io/download
* Go to View > Developer Tools and click on the console tab and enter the following `window.waveboxDebug.flags.googleLogServerPings = true`
* Send yourself an email, you should start seeing `[GOOGLE:PING]` logs come out in the console. If you send the email from one Wavebox account to another you'll probably see a few pings from the sender account and then once you're email is received a few from the receiver account. Do these come up or is it all silent?

**Comment by MarkaPola** [comment]
Hi,

here are the results, using proxy. What is curious is the fact that all seems to work correctly now (unread count is correctly managed even with two accounts). May be the new version (3.1.3) solve the problem... Anyway, for now, seems OK for me.

One Account

window.waveboxDebug.flags.googleLogServerPings = true
true

[GOOGLE:PING] unread <1>@gmail.com
mailboxes.js:30 [SYNCS] Upgrading to WebSocket
mailboxes.js:61 WebSocket connection to 'wss://wavebox.io/socket/websocket?clientId=eca9e84e-663c-4fd3-a629-3a86d92a…ken=704c5d45487148ba925ae420f8ab73cc&version=3.1.3&ident=wavebox&vsn=1.0.0' failed: WebSocket opening handshake timed out
value @ mailboxes.js:61
value @ mailboxes.js:30
(anonymous) @ mailboxes.js:30
mailboxes.js:30 [SYNCS] Error connecting
(anonymous) @ mailboxes.js:30
(anonymous) @ mailboxes.js:61
value @ mailboxes.js:61
conn.conn.onerror @ mailboxes.js:61
mailboxes.js:30 [SYNCS][WebSocket] Next retry LongPoll
(anonymous) @ mailboxes.js:30
(anonymous) @ mailboxes.js:61
value @ mailboxes.js:61
conn.conn.onerror @ mailboxes.js:61
mailboxes.js:30 [SYNCS][LongPoll] Socket opened
mailboxes.js:56 [GOOGLE:PING] unread <1>@gmail.com

=============================

Two Accounts

1. external mail to inbox account

window.waveboxDebug.flags.googleLogServerPings = true
true

mailboxes.js:56 [GOOGLE:PING] unread <1>@gmail.com
mailboxes.js:56 [GOOGLE:PING] unread <2>@gmail.com
2 mailboxes.js:56 [GOOGLE:PING] unread <1>@gmail.com


2. from one inbox account <1> to other one <2>

[GOOGLE:PING] unread <2>@gmail.com
3 mailboxes.js:56 [GOOGLE:PING] unread <1>@gmail.com

**Comment by Thomas101** [comment]
We've updated our socket management code in 3.1.3 so it should be more resilient across proxies etc. It looks like you're getting notified about account updates in the logs, if you're happy it's fixed in the latest version am I okay to close this issue off?

**Comment by MarkaPola** [comment]
OK. Issue closed.
