### ISSUE TITLE
Mailto links are not opening to compose email within wavebox

### ISSUE THREAD

**Issue by jwoodard80** [wavebox/waveboxapp#270]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Wavebox 3.1.10
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

From within Wavebox, if I click on a mailto link inside an email. I get a window that pops up showing the email rather than a compose email. Outside links "IE: Chrome, Firefox" seem to give the expected result of opening wavebox and compose email window with email address. 

Hopefully I have explained this correctly.

**Comment by benwgarton** [comment]
I had this issue - work around was to open a new message then drag "to: address" to the new email window. This works for Gmail.

**Comment by Thomas101** [comment]
Thanks, I'll take a look into this

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox and can be enabled by using the experimental window opener. There’s some instructions on [how to do that here](https://blog.wavebox.io/testing-the-new-window-opener/). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
