### ISSUE TITLE
Just updated on Win 10, Now WB won't finish starting up

### ISSUE THREAD

**Issue by kingsinger** [wavebox/waveboxapp#273]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.10
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 pro on Surface Pro 2

Just updated, now WB won't finish starting up. See attached Screenshot. This is where it is stuck.
![screenshot 14](https://user-images.githubusercontent.com/3348356/27455904-cdcf2a90-5753-11e7-9b1b-cf8812639da7.png)

**Comment by kingsinger** [comment]
FWIW, I uninstalled WB 3.1.10, then re-installed WB 3.1.8 64bit and now it's working again.

**Comment by Thomas101** [comment]
Hi, thanks for reporting! Do you know if your computer is behind a proxy server? Would you be able to try the following?

- Re-install the latest version of Wavebox (sorry!)
- Start Wavebox, then go to View > Developer Tools and click on the console tab
- Then go to View > Reload

Do you see any errors there? Would you be able to send me a screenshot of what's come up? Thanks!

**Comment by Thomas101** [comment]
@kingsinger we managed to reproduce this on one of the boxes here. If you download 3.1.12 from the [download page](https://wavebox.io/download) it should be fixed!
