### ISSUE TITLE
I need to sign in everytime, I reopen this app. 

### ISSUE THREAD

**Issue by wasdee** [wavebox/waveboxapp#274]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.8

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX

First, my email account is inbox(Gmail)-based account. It is "@mail.kmutt.ac.th". 
Everything works fine ,but when I close and open wavebox I need to sign in again. it's not remember my account like another normal gmail account(@gmail.com) .

**Comment by wasdee** [comment]
Also if i use this in google chrome. Sometimes, it asks also but, chrome remember my user password. so, i dont need to type. just click login.

**Comment by Thomas101** [comment]
Hi, depending on how your organization has implemented sign-on you might need to tell Wavebox to persist cookies for longer than usual. There's some information on how to do this in this [KB article](https://github.com/wavebox/waveboxapp/wiki/KB:-Staying-Logged-in). Does this work for you?

We're also hoping to add #37 to the next release to save passwords in a similar way to chrome.

**Comment by wasdee** [comment]
Waiting for next release😊  version 3.2
