### ISSUE TITLE
On Linux, cannot open Wavebox if internet not present at startup

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#276]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Wavebox 3.1.12, issue is present from I believe 3.1.9

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Elementary OS 0.4.1 Loki (64bit),Linux 4.4.0-81-generic, GTK+ 3.18.9

Previously, if internet connection was not present on Wavebox startup, while there was no app icon in tray, the app was running and it was possible to call the app again from the launcher and be presented with screen saying no connection or something similar where one could to go online without having to restart Wavebox.

Latest versions of Wavebox must be killed with `sudo killall Wavebox` before running the app again, after internet connection is restored.

**Comment by Thomas101** [comment]
Hi, do you have Wavebox starting on system startup? Once you get into this situation with no connectivity, if you try to re-open Wavebox from the launcher/app list does it open up or does nothing happen?

**Comment by WebShapedBiz** [comment]
Hi.
Yes, I am starting Wavebox on system startup and I always did.
With no connectivity at startup, nothing happens when I try to re-open the app from launcher. Previously this was no issue, apart from having no icon in the systray as Wavebox always opened up with no connection message and from that window I can reconnect and everything was as usual.

**Comment by Thomas101** [comment]
Okay, thanks I'll see if I can reproduce and get a fix out

**Comment by IgorKvasn** [comment]
Hi,
I am experiencing the same problem on both Linux (Mint) and Windows 10.
There is no tray icon and Wavebox does not show up either. However I can see it in the running processes.
When I start Wavebox again (while still running in a "background") it shows up and everything is fine afterwards.

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by WebShapedBiz** [comment]
Thank you Thomas for this fix. I can report that it works now even better
than before when there was no main window present without connection at
startup.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-17 14:00 GMT+02:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
