### ISSUE TITLE
Can't write @ symbol when composing a new mail

### ISSUE THREAD

**Issue by Paxxi** [wavebox/waveboxapp#278]
* Which version of Wavebox are you using?
3.1.2

* Which Operating System are you using?
Windows 10 Pro latest updates

I have Windows display language set to english, swedish regional settings and swedish keyboard. When I try to compose a new email in Inbox whenever I write @ I get a new blank window and have to switch back to the email which now has a broken address

Result when typing @
![image](https://user-images.githubusercontent.com/874927/27539289-363be746-5a7c-11e7-816d-d5d68a70d3e5.png)

Going back to the mail I get this.
![image](https://user-images.githubusercontent.com/874927/27539306-50d285e2-5a7c-11e7-8621-1bab9a7e9655.png)

To write an email address I have to write it in another app and copy paste it into Wavebox.

**Comment by Thomas101** [comment]
Hi, is your @ symbol on the number 2? What's the shortcut that you usually use to access it?

It sounds like the keyboard shortcut for switching mailbox or switching service is conflicting with the one for inputting the @ key. We'll need to check the keyboard layout and adjust the shortcuts accordingly. In the mean time you can re-map the shortcut under Settings and Advanced. I suspect the one to remove/change is `Mailbox at Index` or `Service at Index`. You can either remove what's in the field completely or change it something that works with your layout.

![screen shot 2017-06-27 at 08 42 16 1](https://user-images.githubusercontent.com/103586/27576333-8d77dc3e-5b14-11e7-9e01-f0b9461c81f2.png)

There's also so more in depth instructions on [changing your keyboard shortcuts here](https://blog.wavebox.io/be-a-keyboard-shortcut-master/)

**Comment by Paxxi** [comment]
correct it's at number 2. Shortcut is `Alt Gr + 2` which can sometimes be replaced with `Ctrl+Alt+2` but that's not something in common use and only when apps misbehave and don't recognize the `Alt Gr` key.

Removed the `Service at Index` keybind now and it works as intended, can write the @ symbol again.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Works in beta channel now for me. Tested on macOS and Windows 10

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
