### ISSUE TITLE
Can't paste text without formatting on macOS (Option+Shift+Command+V)

### ISSUE THREAD

**Issue by TrapSam** [wavebox/waveboxapp#279]
Wavebox will only allow me to paste text with formatting. Would be really useful to paste without formatting. One thing making me consider using Gmail is Safari again.

* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS Sierra (10.12.5)

**Comment by Thomas101** [comment]
Hi, the shortcut <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> should do this. We went for the same default that chrome uses, but I've just noticed that Safari uses the one you mentioned.

If you're already used to the Safari shortcut you can remap this and all the other shortcuts in settings. There's some [instructions on how to do this](https://blog.wavebox.io/be-a-keyboard-shortcut-master/) in the blog
