### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by rvillablanca** [wavebox/waveboxapp#28]
I am using Wavebox v3.1.2. Is there any way to disable spell check ? I can not find this option.

If this option doesn't exists, do you have any plans to add it ?

I know this is not a bug,  but improvement.

**Comment by Thomas101** [comment]
Hi, you can disable it. Go to settings and then under the Language section you can disable it. You'll need to restart Wavebox to see this change take effect though

![screen shot 2017-04-07 at 16 11 07](https://cloud.githubusercontent.com/assets/103586/24806467/e420d592-1bac-11e7-9b74-32acc18dc01a.png)

**Comment by rvillablanca** [comment]
Sorry, I didn't see scroll bar :( Thanks @Thomas101
