### ISSUE TITLE
Question: Notifications / Unread Count for Custom Website 

### ISSUE THREAD

**Issue by eatcodeplay** [wavebox/waveboxapp#280]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Most current version

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 Pro

Is it currently possible in any way to add a notification / unread count badge to a custom website via JS? Or is this something we have to wait for when there is an official API? This is currently the only thing holding me back from buying Wavebox and switching from Franz.

**Comment by Thomas101** [comment]
Hi, you can inject some custom CSS and custom JS through the settings at the moment. This will give you access to present notifications and change a few things in the DOM. We're working on adding something a little bit more formalised along with support for setting things like badges etc over the next couple of releases. Do you mind me asking which website you're looking at adding?

**Comment by eatcodeplay** [comment]
Hi Thomas, thanks for your answer.  I'm looking into adding a custom Microsoft OWA for my Workplace ( mail.publicisgroupe.net ), since i hate having all the damn office software installed ;) And all i would like to do is check certain DOM Elements so i can notify of unread mails.

Can you point me to any example code / docs / script / methods reference i can call to set an unread count  badge or whatever is in place at the moment, in my custom JS? I'm pretty sure i can figure it out from there :)

**Comment by Thomas101** [comment]
That sounds perfect for what we've got coming up! Could you drop me a message through our [contact page](https://wavebox.io/contact) there might be some early access stuff that you might want to try out :)

**Comment by eatcodeplay** [comment]
Done. You have me curious now :)

**Comment by eatcodeplay** [comment]
Hi Thomas, i just wanted to let you know i have since switched to Wavebox Pro and i'm absolutely in love with it. Congrats on a great product. Was just wondering if you could give me a status update on the Wavebox API?

I'm sure you have other things that are far more important, just curious what the progress is :)

I've currently just tapped into the existing Notification Class for my custom scripts, so i'm in no rush :)

**Comment by Thomas101** [comment]
@eatcodeplay thanks, it's great to hear you're enjoying it! :)

We have been running a little bit behind on this, sorry! The latest beta has just shipped with the beginnings of some support for chrome extensions ([more info here](https://blog.wavebox.io/extensions-update-from-development/)). Our plan is to start adding some Wavebox api's into this over the next few beta releases as well as widening support for chrome apis.

I have lined this up in our extensions project, so I'll be adding support in for writing to the badge when we start pushing support out :)

**Comment by eatcodeplay** [comment]
Just posting this in case anyone else is trying to get the existing `Notification` Class running in custom Weblinks. In order to be able to actually send the notification it is required to call this first:

```
Notification.requestPermission().then(() => { 
    /* you can send notifications now */ 
});`
```

This doesn't seem to be required for all Weblinks, but it is definitely the sureshot way to get you up and running.

**Comment by Thomas101** [comment]
If you want to do a little more than just bring up notifications, the latest version has some extra tools to write the counts etc. I've added some [docs on how to use this in the KB](https://wavebox.io/kb/js-guest-api). Would be great to get some feedback if you're using it and what you think is missing!

**Comment by Thomas101** [comment]
Going to close this off for now, but feel free to comment or open a new issue if you have any trouble
