### ISSUE TITLE
Increase CPU usage after adding generic webapp

### ISSUE THREAD

**Issue by rhuss** [wavebox/waveboxapp#281]
* Which version of Wavebox are you using? [e.g. 3.0.0] 

3.1.12

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] 

OS X

After I added octobox.io as generic webapp the CPU usage is around 50% if Wavebox is active and peaks over 100% from time to time. There is nothing obvious in the task monitor though (see screenshot) which show a CPU usage of 85%)

![screen shot 2017-06-27 at 12 35 50](https://user-images.githubusercontent.com/99080/27583931-60ec49d0-5b36-11e7-844c-be21eb30447d.png)

**Comment by rhuss** [comment]
If I add a 'sleep if not in use' to the octobox account it calms down quickly.

**Comment by rhuss** [comment]
In facts seems to me that some javascript runs amok for octobox

**Comment by Thomas101** [comment]
Thanks for the info! If you right click on Octobox on the left side and then pick "Account Settings". Then disable `Show navigation toolbar` does that make any change? We have seen some spikes in usage with that enabled.

![screen shot 2017-06-27 at 11 50 07](https://user-images.githubusercontent.com/103586/27584169-e34891de-5b2e-11e7-9502-160ccb4de474.png)

**Comment by rhuss** [comment]
Yes, that helps quite a bit indeed. It then only around 25% when working but then idle even when the window is active.

**Comment by Thomas101** [comment]
Thanks, I've put a fix in for this :)

**Comment by rhuss** [comment]
@Thomas101 that was fast ;-) Thanks a lot !

**Comment by Thomas101** [comment]
Hi we've just released a fix for this into the beta channel if you want to give a try. There's some instructions on how to [get the latest beta release here](https://wavebox.io/kb/beta-channel). Thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
