### ISSUE TITLE
On Linux, cannot open Wevabox from the dock

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#284]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.1.12.
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Elementary OS 0.4.1 Loki (64bit),Linux 4.4.0-81-generic, GTK+ 3.18.9

When new message arrives, Wavebox use two notifications - in tray and in dock (Plank) by showing app icon with new message count. When I click on dock icon to open Wavebox nothing happens. That worked previously.

**Comment by Thomas101** [comment]
I'll look into this. Which install method did you use? snap, deb etc...

**Comment by WebShapedBiz** [comment]
I'm using repo

**Comment by Thomas101** [comment]
Hi, we’ve just released a workaround for this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel).

It would be great to know if the fix works on your install. If you do have any trouble with it though, you can disable the new behaviour by running wavebox with the `--WBLASDisable` flag. E.g. `./Wavebox --WBLASDisable`.

Thanks!

**Comment by WebShapedBiz** [comment]
Hi Thomas.
Thank you for your time and effort but this fix unfortunately does not fix
reported bug. I'm stil not able to run open WaveBox from Plank when the new
message arrives. I can correctly see that there the number of new messages
but clicking on Plank icon does not open the window.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-17 14:05 GMT+02:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment]
Thanks. I think I've found out why that is. I'll put another release out soon

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.16. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by WebShapedBiz** [comment]
Thank you for your effort Thomas, great job. I can confirm that now I can
open a Wavebox window from Plank when new message arrives.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-19 11:03 GMT+02:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment]
Yes! :)

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
