### ISSUE TITLE
App does not remember window size on re-open

### ISSUE THREAD

**Issue by amancevice** [wavebox/waveboxapp#285]
* Which version of Wavebox are you using? [e.g. 3.0.0]

`3.1.12`

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS `10.12.6`

When I open WaveBox the window is larger than I like, so I resize it and move to the portion of the screen I like, then quit. When I re-open the app the previous state is lost (size + location) and I need to resize/move the window again. This seems to have been introduced with the most-recent update.

**Comment by Thomas101** [comment]
Hi, a fix for this is waiting to go out into the next release.

Duplicate https://github.com/wavebox/waveboxapp/issues/277

**Comment by amancevice** [comment]
Ah, sorry for filing a dup

**Comment by Thomas101** [comment]
Hi we've just released this into the beta channel if you want to give a try. There's some instructions on how to [get the latest beta release here](https://wavebox.io/kb/beta-channel). Thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
