### ISSUE TITLE
"npm start" opens app but it just sits on an empty screen with spinner

### ISSUE THREAD

**Issue by jpage4500** [wavebox/waveboxapp#287]
I wanted to try building Wavebox and the instructions were pretty easy to follow. But, starting the app and it just sits there with a spinner - nothing on the screen. I also can't open up the app preferences or anything else.

There's a lot of output in the console when running so not sure you want to see the whole thing.. I do see this at the very end though:
```
objc[56573]: Class NotificationCenterDelegate is implemented in both /Users/jpage/working/external/waveboxapp/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework (0x10f185898) and /Users/jpage/working/external/waveboxapp/bin/app/node_modules/node-mac-notifier/build/Release/Notification.node (0x11495c9f8). One of the two will be used. Which one is undefined.
```

* Which version of Wavebox are you using? [e.g. 3.0.0] 
latest master branch

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
mac OSX (latest production)

**Comment by Thomas101** [comment]
Hi, that warning is expected and should work itself out. Chances are there's an error sitting in the dev console. Hitting <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>J</kbd>will bring it up an probably reveal some additional errors.

**Comment by jpage4500** [comment]
I see - thanks.. 
```
Bootstrap failed Error: The module '/Users/jpage/working/external/waveboxapp/bin/app/node_modules/node-mac-notifier/build/Release/Notification.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/jpage/working/external/waveboxapp/bin/app/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/jpage/working/external/waveboxapp/bin/app/node_modules/node-mac-notifier/index.js:5:44)
Promise.all.then.catch @ mailboxes.html?clientId=a34cfa26-6e93-41e7-9e8e-5859f2cad148&clientToken=2aa38c3……:227
```

I did install using npm install originally. I also installed Node.js version 6.11.0LTS (the recommended version on the website).

I'll try rebuilding and see if that helps

**Comment by Thomas101** [comment]
Ah sorry, I think the build instructions are slightly out of date. We've been moving along quite quickly with releases from electron and the build chain has changed quite a bit.

Build instructions are back up to date. You'll need node 7.9.0. Then run `npm run rebuild:electron` before running `npm start` and you should be good!

**Comment by jpage4500** [comment]
that worked - thanks!
