### ISSUE TITLE
Reset an app to original url

### ISSUE THREAD

**Issue by VincentSC** [wavebox/waveboxapp#288]
When there is a problem with a custom app, I cannot go back one page or reset the app. I can only refresh the current (faulty) page. The current solution is to restart Wavebox.

**Comment by Thomas101** [comment]
Hi, with the Any Web Link type we've added some navigation tools to the context menu which should allow you to go back, forward, home etc...
![screen shot 2017-06-29 at 08 56 52](https://user-images.githubusercontent.com/103586/27677286-f84880f0-5ca8-11e7-8d2e-caeb4415c2ae.png)

Also the latest version has the option to enable the navigation toolbar for these account types which contains the same controls. It's enabled by default on new accounts, but not old ones. You can enable it by right clicking on the account in the left hand side and going to account settings. From there you can enable `Show Navigation Toolbar`

![untitled](https://user-images.githubusercontent.com/103586/27677329-2e30d8a2-5ca9-11e7-8b83-027f5b33e2b5.png)

Does this stop you needing to restart completely?

**Comment by VincentSC** [comment]
I updated, and now see it in the context menu. Thanks!
