### ISSUE TITLE
Experimental notifications: stop working after a while

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#290]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04
Ubuntu 17.04 / Unity 7

I typically never shut down my laptop, simply lower the lid to suspend it at the end of the day and continue where I left it the next day.

I enabled experimental notifications and restarted the app yesterday. Today, I would not receive any more visual notifications until I restarted the app. The notification sound would play though.

Yesterday I was on a double display set up at work (laptop + external), whereas today I'm only on the laptop display. Notifications always show on the laptop display anyhow. Laptop display is marked as primary.

**Comment by Thomas101** [comment]
Thanks! I suspect we're not listening for screen size changes which is why it's disappeared!

**Comment by luispabon** [comment]
:+1:

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
