### ISSUE TITLE
MacOS scrolling swiping desktops - on every desktop Wavebox 

### ISSUE THREAD

**Issue by MarkoBolt** [wavebox/waveboxapp#292]
Wavebox 3.1.12 on MacOS 10.12.5

When Wavebox is started and not in full screen mode, Wavebox is on every desktop where is swipe to.
Sometimes when e.g. Safari is opened not in fullscreen mode but filling the screen, and I swipe to that desktop, Wavebox flashes through the screen and disappears. 

Annoying behaviour of WaveBox and limits the use of Wavebox.

**Comment by Thomas101** [comment]
Hi, this shouldn't be the case. If you restart Wavebox or your machine does it happen every time? If you right click on Wavebox in the dock is it assigned to one or all desktops?
![screen shot 2017-06-30 at 10 11 36](https://user-images.githubusercontent.com/103586/27729141-8843661a-5d7c-11e7-89db-48931715044c.png)

**Comment by MarkoBolt** [comment]
Thomas, thx, I think this setting wil work it does not looks like a bug  :-)
