### ISSUE TITLE
After minimizing, Wavebox is no longer in full screen

### ISSUE THREAD

**Issue by DFelten** [wavebox/waveboxapp#293]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

At the moment there is a relatively annoying behavior from the application. If the fullscreen application is minimized into the info area, and I open it again, it is no longer in full screen. It always appears reduced in size.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I'm having a little trouble reproducing the behaviour. How are you minimizing and restoring the window?

Is it just through the main window controls and from the taskbar? (See attached, 1 to minimize, 2 to restore)
![screen shot 2017-07-04 at 08 40 04](https://user-images.githubusercontent.com/103586/27819998-907cbb9a-6094-11e7-8b49-ab8b37079c84.png)

I had a go with the tray icon (bottom right) too but saw the correct behaviour again. If the problem is when doing it through the tray, could you send a screenshot of the tray section in settings so I can make sure mine is setup the same as yours?
![screen shot 2017-07-04 at 08 43 57](https://user-images.githubusercontent.com/103586/27820080-fc9199d6-6094-11e7-9c38-bc63417c65da.png)

**Comment by DFelten** [comment]
Sorry, maybe fullscreen isn't the correct word. I mean it's maximized.

These are my tray settings:
![image](https://user-images.githubusercontent.com/1169185/27903493-d4ca2994-6239-11e7-9a50-b302f1a63b1e.png)

Before minimize it's maximized:
![image](https://user-images.githubusercontent.com/1169185/27903533-ee2586ea-6239-11e7-92a3-133518d91b08.png)
(I'm able to minimize Wavebox through both buttons)

After re-opening Wavebox using the Tray button
![image](https://user-images.githubusercontent.com/1169185/27903568-0cb9c148-623a-11e7-9986-0a9d468ebf1d.png)

As you can see Wavebox isn't maximized anymore.

**Comment by Thomas101** [comment]
Yep I see the same with those settings! I'll see what it is. Thanks!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by DFelten** [comment]
Thanks! If it is minimized by the button in the tray, maximizing looks good. However, if the window is minimized using the Minimize button, it flickers when reopen it.

Also it's now maximize even if the window isn't maximized when minimize it into the taskbar.

**Comment by Thomas101** [comment]
At the moment, the flicker is unavoidable. On windows we're unable to prevent the default minimize behaviour to make it actually close the window. We can either stick with this behaviour or remove the minimize button all-together when "Hide main window to tray on minimize" is enabled.

>Also it's now maximize even if the window isn't maximized when minimize it into the taskbar.

What's the behaviour flow you're seeing on this? E.g. maximize window, then minimize window, then click the minimize button?

**Comment by DFelten** [comment]
Ok, then it is so useful. It is not a good idea to remove the button. Even if I ask myself how other applications do this.

When maximize the size of the window, then minimize it with the button in the header bar. After reopen it with the button in the tray, it's again in window mode. Apparently, the current size or mode is not saved when the window is minimized with the heade button. It's acting a little strange with the minimize button in the header bar.

**Comment by Thomas101** [comment]
> Ok, then it is so useful. It is not a good idea to remove the button. Even if I ask myself how other applications do this.

It certainly is possible on a technical level, but the electron doesn't seem to have support for this right now.

> When maximize the size of the window, then minimize it with the button in the header bar. After reopen it with the button in the tray, it's again in window mode. Apparently, the current size or mode is not saved when the window is minimized with the heade button. It's acting a little strange with the minimize button in the header bar.

There's a delay of 2 seconds between detecting the change to the window minimize state/position and saving it. I'll tighten this up, but when testing it's worth maximizing, waiting two seconds then minimizing and reopening.
