### ISSUE TITLE
Fails to work at all with macos beta high sierra (spinning color wheel - not responding)

### ISSUE THREAD

**Issue by stevebythebay** [wavebox/waveboxapp#294]
* Which version of Wavebox are you using? 

3.1.12

* Which Operating System are you using? 

macos 10.13 beta (public)

**Comment by Thomas101** [comment]
Hi, Thanks for reporting. Do you know which version of the beta you're using. We've just setup a fresh install with 17A291m and it seems to launch okay. Could you try moving your data out from Application Support (more info on [data location](https://wavebox.io/kb/data-locations)) re-downloading Wavebox and re-launching to see if it launches correctly on your install?

**Comment by stevebythebay** [comment]
Using MacOS High Sierra public beta 17A291m.  THIS IS THE FIRST PUBLIC BETA OF HIGH SIERRA.  You using a developer release???  Any other oddities about the systems you’re testing on???

And after moving the Wavebox folder from the Library to my desktop, downloading the latest version of Wavebox again (from https://wavebox.io/download <https://wavebox.io/download> and installing), it still  does not open.  In Force Quit function it says “Not Responding”.

Sincerely,

Steve Schaffer
(H) 415-578-0413
(M) 415-613-5123

**Comment by Thomas101** [comment]
**Facepalm** thanks for pointing that out. I'll retry on our box :)

**Comment by stevebythebay** [comment]
No problem. I often find that ensuring I have a real user test bed, uncovers quite a bit. Even Apple sometimes fails in this, cutting corners.

Sincerely,

Steve

**Comment by gravis** [comment]
That's weird, I have the same behaviour, but with classic Sierra

**Comment by gravis** [comment]
<img width="1139" alt="capture d ecran 2017-06-27 a 14 29 38" src="https://user-images.githubusercontent.com/12752/27809841-6b1681f6-6021-11e7-80e8-ae52ba9f1c04.png">

**Comment by gravis** [comment]
<img width="785" alt="screenshot 2017-07-03 18 57 01" src="https://user-images.githubusercontent.com/12752/27809845-7627a98a-6021-11e7-9495-c7933849b6d9.png">

**Comment by gravis** [comment]
hmm, sounds like it was a VPN issue on my side, sorry for the noise

**Comment by Thomas101** [comment]
@stevebythebay We've (finally) managed to reproduce the issue our end and hopefully got a fix. It's been released to the beta channel as version 3.1.14 and can be [download from here](https://github.com/wavebox/waveboxapp/releases/tag/v3.1.14). Would be great to know if it fixes for everyone else too

**Comment by stevebythebay** [comment]
Thanks. However, in backing off of the public beta, due to numerous other issues with the code, I ran into some rather odd behavior. I couldn't cleanly reinstall from a Time Machine backup. I had used the APFS option. Seems that it encrypts the disk, yet in installing I was not prompted for any encryption key. That meant the Time Machine process failed since I could not provide a key. So, had to use a network reinstall via the Apple site. And even after that, and then doing a Time Machine restore, I could never get the Apple Store function to work. Luckily I had a SuperDuper! "bare metal" backup that put the system right.

Needless to say, I think I'll wait awhile before trying to move to High Sierra.

I'd copy Apple on this but I never get any feedback from the Beta group, even indicating that they got my information.

Sincerely,

Steve

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
