### ISSUE TITLE
Wavebox Launching New Instance Instead of Restore Existing Instance

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#296]
**Wavebox:** 3.1.12
**OS:** KDE Neon 5.10.3 based on Ubuntu 16.04 (Linux)
**Install Method**: manually with .tar.gz

Wavebox will not open an existing instance anymore and instead just kills the current instance and opens a new one.

Previously, I could close the Wavebox window entirely, while it stays loaded in the system tray, and then click the Wavebox icon from my dock or system main menu to simply reopen the window of the existing instance. However, since the latest updates, I believe started in 3.1.10+, the existing instance is closed and a new one is launched instead. In my case, this also resets the active account to _Account 1_.

I think this may be related to Issue #284 but not totally sure as I use a different dock. elementaryOS uses Plank for their dock and I use "Latte Dock" inside of Plasma.

**Comment by Thomas101** [comment]
Hi, I think it is the same underlying issue. There's a problem with the process re-attachment in the 1.7.* electron builds which means this behaviour comes up. Hoping to put a fix or workaround together ourselves shortly for this

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.16. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by MichaelTunnell** [comment]
I just tested the Beta version of 3.1.16 and can confirm that the single instance issue has been resolved for me.
