### ISSUE TITLE
menubar icon doesn't display unread count - shows black circle instead

### ISSUE THREAD

**Issue by c-lawlz** [wavebox/waveboxapp#299]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
10.12.5

![screen shot 2017-07-05 at 12 01 04 pm](https://user-images.githubusercontent.com/26422600/27875661-ad386e10-6179-11e7-8f52-a5630aa56f3c.png)

**Comment by c-lawlz** [comment]
I want to also note:
- I have 3 digits worth of messages (about 127)
- I've never tried to use this feature before (the menubar icon) so I've never seen it work.

**Comment by Thomas101** [comment]
Hi, we found that as soon as you try to place more than 3 digits into the icon it becomes pretty unreadable. To work around this once you creep over 99 it changes to be an unread dot to just indicate changes which is what you're seeing there

**Comment by c-lawlz** [comment]
Thanks Thomas!

Sounds good - another good reason to keep my inbox count down ;)

Best,
Corey
