### ISSUE TITLE
Feature request: Skype integration

### ISSUE THREAD

**Issue by huangv22** [wavebox/waveboxapp#30]
Our office uses both slack and skype. Skype is used by sales/CS and slack by dev. Looking for a system for my team that can integrate both together.

* Which version of Wavebox are you using? 3.1.2
* Which Operating System are you using? Mac OSX 10

Urgency: High, as it will get more people on my team to try wavebox

**Comment by jacksarick** [comment]
Using my O365 account, I can send and receive Skype messages in Wavebox. I have yet to test notifications, but I'll look into it.

**Comment by Thomas101** [comment]
I've just tried adding `https://web.skype.com` using the generic web url and it does work as far as chat is concerned. They're using a 3rd party plugin for calls through a chrome extension. It might take a little bit of looking at to see how that works, but we'll take a look

**Comment by Thomas101** [comment]
Hi, we're collapsing all the new Account/Service requests into a single issue so we can keep track of them more closely. You can find and continue tracking progress from #130. Thanks
