### ISSUE TITLE
PDF do not open often

### ISSUE THREAD

**Issue by MarkoBolt** [wavebox/waveboxapp#300]
* Which version of Wavebox are you using? 3.1.0
* Which Operating System are you using? Mac OSX 10

Often a .PDF file stored in the Google Drive does not open within Wavebox.

**Comment by Thomas101** [comment]
Hi do you see any error or message? What method are you using to open it, just double click on a pdf?

**Comment by MarkoBolt** [comment]
On the left corner below, i get the message "Kan actie niet starten" translated to English: Can not start action.
<img width="388" alt="screen shot 2017-07-06 at 11 09 08" src="https://user-images.githubusercontent.com/11732640/27904008-8f9d0c04-623b-11e7-9ad0-82b0fd805a49.png">

**Comment by MarkoBolt** [comment]
It is not always the case. In an other account i can open the .pdf.

**Comment by Thomas101** [comment]
I think this is probably related to #301 in the same way...

**Comment by nmat** [comment]
@MarkoBolt does this happen in 3.5?

**Comment by MarkoBolt** [comment]
@nmat No it seems to work not :-)
