### ISSUE TITLE
.docx file can not be opened

### ISSUE THREAD

**Issue by MarkoBolt** [wavebox/waveboxapp#301]
* Which version of Wavebox are you using? 3.1.0
* Which Operating System are you using? Mac OSX 10

A .docx file can not be opened via the open with google docs option.

**Comment by Thomas101** [comment]
Just to check is it by pressing the following that results in a blank window...

![screen shot 2017-07-06 at 10 07 42](https://user-images.githubusercontent.com/103586/27903963-1356f5c2-6233-11e7-9bde-8118f96f19f5.png)

**Comment by MarkoBolt** [comment]
This is how I do it: 

<img width="663" alt="screen shot 2017-07-06 at 11 11 13 2" src="https://user-images.githubusercontent.com/11732640/27904136-f5ba894e-623b-11e7-8360-3a42728047db.png">

In Chrome this function works.

**Comment by MarkoBolt** [comment]
<img width="309" alt="screen shot 2017-07-06 at 11 11 13" src="https://user-images.githubusercontent.com/11732640/27904174-16832b86-623c-11e7-8a75-16b4fba3fa86.png">

**Comment by Thomas101** [comment]
Thanks. I see the same issue. The behaviour is only seen when the experimental window opener is disabled and when enabled it opens a blank window.

**Comment by MarkoBolt** [comment]
Thx, how to enable the experimental window opener?

**Comment by Thomas101** [comment]
You can give it a try by opening Settings & then going to the Advanced tab. You'll find a setting there called "Use Experimental Window Opener". You'll need to restart Wavebox after changing this

**Comment by MarkoBolt** [comment]
Thx!

**Comment by nmat** [comment]
@MarkoBolt do you get the same effect on 3.5?

**Comment by Thomas101** [comment]
I think this is fixed in 3.5.0+, if not feel free to re-comment and I'll take another look
