### ISSUE TITLE
Add image tools to context menu

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#305]
Add `Save Image As...` and `Copy Image Url` to right click context menus

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by redfellow** [comment]
"Copy image" is missing from context menu. URL is there, but actual copying of the image itself (for easy pasteing into another service from clip board) would be nice to have.
