### ISSUE TITLE
Incorrectly told there's no internet connection when first opening Wavebox

### ISSUE THREAD

**Issue by leadowning** [wavebox/waveboxapp#309]
* Which version of Wavebox are you using? 3.1.12

* Which Operating System are you using? Mac OS 10.12.5

When I try to first open Wavebox after downloading the installer, it tells me that there is no internet connection. I am certain that there is (and have tried downloading the installer again and starting over), but it consistently won't make it to the setup screen.

I was able to successfully set it up on another computer in our office, but not on this particular one. I am always taken to this screen: 

<img width="796" alt="screen shot 2017-07-11 at 1 05 09 pm" src="https://user-images.githubusercontent.com/30086437/28083130-07f3d9ec-663a-11e7-9676-0aa0588922aa.png">

**Comment by Thomas101** [comment]
Hi, sorry about this. It looks like something's gone wrong in the first run. If you quit Wavebox, remove `/Library/Application Support/wavebox` and start it again it should startup correctly

**Comment by leadowning** [comment]
Hi @Thomas101,

There isn't a wavebox folder in the Application Support folder...

**Comment by Thomas101** [comment]
Sorry, I missed the tilde from the from. Should be `~/Library/Application Support/wavebox`, e.g `/Users/tom/Library/Application Support/wavebox`

**Comment by leadowning** [comment]
It worked! Thanks @Thomas101!

**Comment by lirender** [comment]
Same problem and environment:

Which version of Wavebox are you using? 3.1.12

Which Operating System are you using? Mac OS 10.12.5

I'm trying to run from source (build using brew with NodeJs 7.9.0 as specified and latest as well) but always get the no internet screen. If I download the pre-built I dont have a problem.

I tried many variations (each time deleting the wavebox folder as described).

**Comment by Thomas101** [comment]
@lirender it sounds like in your instance your api key may be incorrect. Could you re-check that it's been configured correctly as per the [Build Configuration](https://github.com/wavebox/waveboxapp#build-configuration) section?

**Comment by lirender** [comment]
You were right, the credentials.js I created had an issue. Thanks @Thomas101 for all of your contributions to open source!

**Comment by Thomas101** [comment]
@lirender no problem :)

I'm going to close this off, as I think everyone has it working. If not let me know I'll re-open :)
