### ISSUE TITLE
Use only google drive

### ISSUE THREAD

**Issue by huangv22** [wavebox/waveboxapp#31]
Urgency: Nice to have

We use google drive to share docs. When I connect my g-suite account, want the ability to turn on/off all items. Currently, I cannot turn off my google work. 

* Which version of Wavebox are you using? 3.1.2
* Which Operating System are you using? 
Mac OSX 10

**Comment by jacksarick** [comment]
Could elaborate? Would like to be able to control what is in the side bar, because that is already a feature under Settings > Accounts and uncheck everything that you don't want. If I've misunderstood, I'd love to understand so I can help.

**Comment by huangv22** [comment]
@jacksarick , I have the ability to configure everything except turning off gmail. Looks like you guys have a hierarchy. Mail first, then all the other items as child. So with 365, I need to have mail as my first go to place, when I might want calendar or some other service. For gSuite, we only use the drive function, would love only that to be the primary option.

Let me know if that makes sense!

**Comment by jacksarick** [comment]
Oh I see what you mean. Wavebox was initially designed to manage email, so I don't think that case that was considered, but I don't see why it shouldn't be possible. I'll see if I can get that working

**Comment by Thomas101** [comment]
There's been a couple of requests & questions flying around having gSuite services without the mail tab. Wavebox is setup to always have mail at the moment, but I think it's something we're going to add in.

Maybe maintain a similar account structure to what there is now, but have it so you can configure your "primary" access type. Be it email, or drive etc. In the short term you could always add `drive.google.com` using the `Add any Website` button when adding an account, although you might find some of the integration captures like opening docs etc in Wavebox don't work automatically with this.

**Comment by huangv22** [comment]
That's a great hack!

**Comment by Thomas101** [comment]
Google drive can now be added on its own from the add screen, in version 3.7.0 and above
