### ISSUE TITLE
Error on uploading to slack... 

### ISSUE THREAD

**Issue by patrickcurl** [wavebox/waveboxapp#310]
* Which version of Wavebox are you using? [e.g. 3.0.0]
 3.1.13
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Antergos - 4.11.9.1 ARCH

internal/process/warning.js:21 (node:23881) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 openItem listeners added. Use emitter.setMaxListeners() to increase limit

Was trying to upload a file to slack, getting that error above in the dev tools console... reloaded window, but haven't tried rebooting yet... just thought I'd let you know. I have about 10-12 slack channels plus gmail account installed.

**Comment by Thomas101** [comment]
Thanks for reporting and for the log message. Log message isn't anything to worry about. It would be great to know how you uploaded the file (drag & drop, `+` add from your computer) and also which file format it is?

**Comment by patrickcurl** [comment]
Add from computer.. the same file worked about 20 mins earlier via a DM to
someone in another slack team. (we have a corporate/client and a
dev-only/contract slack groups.

**Comment by Thomas101** [comment]
I wonder if it was blip on with slack. If you try reloading and try again has it started working? Would you be able to try the same on a non shared team?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
