### ISSUE TITLE
Option to minimize Window when clicked on close.

### ISSUE THREAD

**Issue by aurimus** [wavebox/waveboxapp#312]
When clicked on close button I expect it to close to tray, but since in Ubuntu there is no tray icon - I expect it to minimize.

3.1.12
Ubuntu 17.04

**Comment by Thomas101** [comment]
Hi, we've got the tray icon working in the beta channel of Wavebox if you want to give that a try. Some info on how to switch [here](https://wavebox.io/kb/beta-channel)

**Comment by Thomas101** [comment]
Hi, this has just been released into version 3.2.0 on the stable channel of Wavebox. Thanks!

**Comment by Jonatino** [comment]
@Thomas101 I don't see the option on Windows 10. Version 3.13.0

![image](https://user-images.githubusercontent.com/1808569/38448691-2928d45a-39d4-11e8-88e9-5558a24f4793.png)

**Comment by Thomas101** [comment]
@Jonatino there's no option for this, it's just the default behaviour. Clicking close will leave the app running in the tray.

On windows, if you want the app to remain in the taskbar, pinning it (via right-click, pin to taskbar) will keep the window visible in the taskbar when clicking close.

**Comment by Jonatino** [comment]
@Thomas101 when I click close, the program is removed from my tray and stops running.

**Comment by Thomas101** [comment]
It may be that the icon has been placed behind the hidden items toggle. If you click on the little up arrow in the bottom right, is the app still running there?

If not, if you start the task manager and then click the `More details` toggle do you see Wavebox listed?

**Comment by Jonatino** [comment]
@Thomas101 I recorded a video for you.

https://dl.dropboxusercontent.com/s/bcqap8s1iuknxff/2018-04-11_11-47-55.mp4

Here is the eventviewer error:
https://dl.dropboxusercontent.com/s/7wphqsmsfmrmxkb/mmc_2018-04-11_11-49-44.png

and the crash log:
https://dl.dropboxusercontent.com/s/suw3jsn223hdns9/AppCrash_Wavebox.exe_f6779e21a47697c5be5a4a29668d974387d563_7443d7c0_540048f6.zip

**Comment by Thomas101** [comment]
Thanks for those @Jonatino. It looks like there's a hard crash there somewhere.

Could you drop support@wavebox.io an email? It would be good to grab a copy of the config you're using in case it's an edge case we don't have a test for right now!
