### ISSUE TITLE
Activating a sleeping service in 4K monitor (DPI multiplier x2 in options)

### ISSUE THREAD

**Issue by nachogo** [wavebox/waveboxapp#313]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Latest stable

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Win 10 latest

Hi, when activating a service tab that has sleep on, while loading wavebox shows a B/N screenshot till the service finish loading. That´s ok but, when using a 4k monitor&resolution in desktop, the BN screenshot don´t apply the DPI x2 magnifier that is set in options, when using 4k, so the B/W screen shot that is shown is BIG (I mean Like been zoom 200%).

Thanks!

**Comment by Thomas101** [comment]
I literally patched that an hour ago :) https://github.com/wavebox/waveboxapp/commit/93b31ef9233c60d8214308e1509464557a6cba48 Will be out in the next release!

**Comment by nachogo** [comment]
Great! Thanks Thomas!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.15. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
