### ISSUE TITLE
For 0365, Reply All does not work when trying to schedule a meeting 

### ISSUE THREAD

**Issue by huangv22** [wavebox/waveboxapp#314]
* Which version of Wavebox are you using? [e.g. 3.1.12]

* Which Operating System are you using? Mac

Wanted to email meeting participants a follow up message.
From the meeting details, clicked on Reply All. 
System opens up new screen, but it is blank.

![https___outlook_office365_com_owa_projection_aspx_and_wavebox__45__and_new_issue_ _wavebox_waveboxapp_and_conversation_flow](https://user-images.githubusercontent.com/4745333/28184029-968ce396-67c6-11e7-9b35-8a84362bc3c9.png)

**Comment by Thomas101** [comment]
Hi, have you tried toggling the experimental window opener so it's enabled under Settings/Advanced? This might be fixed with that enabled.
![screen shot 2017-07-14 at 12 56 25](https://user-images.githubusercontent.com/103586/28211329-ed67d248-6893-11e7-87b9-6ae676542967.png)
