### ISSUE TITLE
Login to sites with already logged in Google accounts

### ISSUE THREAD

**Issue by gkatsev** [wavebox/waveboxapp#315]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.12
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX, Win10

Not sure whether this is possible with the architecture of wavebox but would be cool if we could log into websites that support Google oauth login with the already logged in Google accounts.

**Comment by Thomas101** [comment]
At the moment each account you add in Wavebox is completely Sandboxed from the others.

We have been talking about adding the ability to add custom urls into an account as services. Would that work for what you're trying to do?

**Comment by gkatsev** [comment]
Yeah, I figured the sandboxing might be the issue.

Adding custom urls as a service might be an OK workaround. Though, I'll probably just continue logging in manually.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account by right-clicking on one of the tabs and picking `Add another service`

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
