### ISSUE TITLE
Sensitive Date Returned in Server Response

### ISSUE THREAD

**Issue by coredefend** [wavebox/waveboxapp#316]
* Which version of Wavebox are you using? [3.1.12]

* Which Operating System are you using? [OSX 10]

The client app makes a HTTP GET request to `/client/bbeb1881-8b64-401c-XXXXXXX/init.json` and includes URL parameters such as `token` and `api_key`.  The server responds with the credentials for providers such as Google and Microsoft. This appears to be valid client secrets that Wavebox uses to configure their oauth settings with those providers.

Below is the full request. I've redacted sensitive items:
**Request**
```http
curl -i -s -k  -X $'GET' \
    -H $'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) wavebox/3.1.12 Chrome/58.0.3029.110 Electron/1.7.3 Safari/537.36' \
    $'https://wavebox.io/client/bbeb1881-8b64-401c-babd-XXXXXXX/init.json?token=a6447XXXXXXXXXXX212bff&version=3.1.12&bid=release&ident=wavebox&api_key=XXXXXXXXXXXXXXXXXXXXXXFzZSJ9&protocol=2&_=1499978862993'
```
**Response**
```json
{
  "credentials": {
    "TRELLO_AUTH_RETURN_URL": "https://wavebox.io/auth/stub/trello/success",
    "TRELLO_AUTH_APP_NAME": "Wavebox",
    "MICROSOFT_CLIENT_SECRET": "ZEXXXXXXXXXXX",
    "MICROSOFT_CLIENT_ID": "3e7XXXXXXXXXXXXX",
    "MICROSOFT_AUTH_RETURN_URL": "https://wavebox.io/auth/stub/microsoft/success",
    "GOOGLE_PUSH_SERVICE_SUCCESS_URL": "https://wavebox.io/auth/google/success",
    "GOOGLE_PUSH_SERVICE_FAILURE_URL": "https://wavebox.io/auth/google/failure",
    "GOOGLE_PUSH_SERVICE_AUTH_URL": "https://wavebox.io/auth/google",
    "GOOGLE_CLIENT_SECRET": "OxF_XXXXXXXXXXXXXXXX",
    "GOOGLE_CLIENT_ID": "1050120327908-XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "GOOGLE_AUTH_RETURN_URL": "urn:ietf:wg:oauth:2.0:oob",
    "GOOGLE_ANALYTICS_ID": "UA-91763551-2"
  },
  ....
```

The `CLIENT_SECRET` should be private and not disclosed. I'd recommend to regenerate the secret values and move this api call to wavebox server so that the mac osx client cannot see it.

**Comment by Thomas101** [comment]
Hi, thanks for opening the issue. The `..CLIENT_SECRET`s here are just the app oauth identifiers for Wavebox- nothing to do with the client bearer tokens which control access to the individuals email accounts.

Wavebox is an installed application and you'll find that for example the [official google documentation](https://developers.google.com/identity/protocols/OAuth2#installed) explicitly mentions that the `CLIENT_SECRET` is not treated as such in this use-case...

> The process results in a client ID and, in some cases, a client secret, which you embed in the source code of your application. (In this context, the client secret is obviously not treated as a secret.)

I agree it's confusing calling something a secret that's not a secret, but we've just followed the naming conventions used in the documentation.
