### ISSUE TITLE
Feature Request: Auto start on Login (macOS)

### ISSUE THREAD

**Issue by leocaseiro** [wavebox/waveboxapp#317]
* Which version of Wavebox are you using?
**3.1.2**

* Which Operating System are you using?
**macOS Sierra 10.12.5 (16F73)**

Hi, I would like to set Wavebox app to start on my mac login automatically.
So I won't need to open the app myself, thanks.

**Comment by Thomas101** [comment]
Hi, you can do this from settings. If you open settings under the platform section (top right) there's a System Startup Settings button. If you click on this you have the option to pick `Open at System Startup` or `Open hidden at System Startup`

![screen shot 2017-07-14 at 13 04 36](https://user-images.githubusercontent.com/103586/28211521-01e6f78e-6895-11e7-98ac-56c21ea59018.png)

**Comment by leocaseiro** [comment]
Hi @Thomas101, thanks for that.

I found in Preferences -> General.

I'd never clicked on this button, sorry about it.
