### ISSUE TITLE
Zoom pages > Ctrl plus - zoom out OK but Ctrl plus + don´t do Zoom IN

### ISSUE THREAD

**Issue by nachogo** [wavebox/waveboxapp#318]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Latest released today (15)
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Win 10 latest.

As I write in the post title:

In chrome pressing Ctrl plus sign - zoom out the web page (smaller) and Ctrl plus sign + is zoom in (bigger)

In Wavebox only works the Zoom out keystroke: Ctrl plus sign - is OK but Ctrl plus sign + don´t do zoom in.

With a 4k monitor, using the zoom in web pages is, at least in my case,  an everyday task.

Thanks!

**Comment by nachogo** [comment]
Ok, I just realize that, in config, the default for zoom in is ctrl+0 but can be edited to Chrome´s default, to Ctrl++. So, perfect.

Sorry and thanks again!

**Comment by Thomas101** [comment]
Hi. Ideally the default to zoom-in should be <kbd>Ctrl</kbd>+<kbd>+</kbd> but to make this work it normally needs you to use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>+</kbd>.

In 3.1.15 we changed the shortcut to be <kbd>Ctrl</kbd>+<kbd>=</kbd> so it feels more natural. Do you have a keyboard layout that doesn't have <kbd>+</kbd> and <kbd>=</kbd> on the same key?

**Comment by nachogo** [comment]
Yes Thomas, my keyboard layout (a logitech K810) don´t have the = and +  symbols on the same key.

= symbol share the key with 0 and the + sign share the key with * and ] symbols.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.1.16. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
