### ISSUE TITLE
Apt repo reporting conflict 

### ISSUE THREAD

**Issue by TheSeanBrady** [wavebox/waveboxapp#319]
* Which version of Wavebox are you using? [3.1.12

* Which Operating System are you using? Ubuntu 17.04

There's an issue with the apt repo configuration, apt-get update is reporting a conflict. 

```
➔ sudo apt-get update
[sudo] password for sbrady: 
Hit:1 http://us.archive.ubuntu.com/ubuntu zesty InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease            
Get:3 http://us.archive.ubuntu.com/ubuntu zesty-updates InRelease [89.2 kB]
Hit:4 http://dl.google.com/linux/chrome/deb stable Release   
Get:5 http://us.archive.ubuntu.com/ubuntu zesty-backports InRelease [89.2 kB]
Hit:7 https://wavebox.io/dl/client/repo x86_64/ InRelease      
Get:8 http://security.ubuntu.com/ubuntu zesty-security InRelease [89.2 kB]                                                    
Fetched 268 kB in 10s (24.8 kB/s)                                                                                             
Reading package lists... Done
W: Conflicting distribution: https://wavebox.io/dl/client/repo x86_64/ InRelease (expected x86_64/ but got )
```

**Comment by TheSeanBrady** [comment]
IMHO, if I were the maintainer, I'd fix the issues with the snap (the font and look are atrocious) and discontinue the PPA. My $0.02.

**Comment by Thomas101** [comment]
Thanks, we've fixed the apt repo. [Font](https://bugs.launchpad.net/snappy/+bug/1621568) and [cursor](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1579268) issues are both upstream with snap

**Comment by Thomas101** [comment]
I'm going to close this off for now. The warnings with the apt repo should now be fixed and we're tracking the upstream snap issues in #204. Thanks
