### ISSUE TITLE
Gmail View entire message

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#321]
Gmail will "clip" emails that are very long:

![screen shot 2017-07-19 at 2 31 10 pm](https://user-images.githubusercontent.com/2305088/28390483-1682a0dc-6c8f-11e7-8ec3-26d9ba09ca8d.png)

These "View entire message" links used to work properly, but now it's opening in an external browser instead of staying in Wavebox and opening in a popup like it used to do...

From #306

**Comment by brianlenz** [comment]
As mentioned in #306, your assessment is correct: this issue only occurs when using the experimental opener. Once I disabled that, the full message appears in a Wavebox popup, as expected.

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox and can be enabled by using the experimental window opener. There’s some instructions on [how to do that here](https://blog.wavebox.io/testing-the-new-window-opener/). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
