### ISSUE TITLE
Cmd-comma doesn't always open Preferences

### ISSUE THREAD

**Issue by brianlenz** [wavebox/waveboxapp#323]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.16 Beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS Sierra (10.12.6)

Hitting cmd-comma doesn't open Wavebox preferences as it should. I usually have to manually select it from the Wavebox menu. I did notice that if I hit cmd-comma repeatedly, it will open eventually. If you only hit it once, however, the Preferences don't seem to ever open.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I did have some reports about this ages ago but was never able to get to the bottom of it. If you hit the shortcut does Wavebox flash in the menubar...

![jul-25-2017 10-41-31](https://user-images.githubusercontent.com/103586/28566157-38758376-7126-11e7-9b29-76efe4aa3daf.gif)

Also if you try changing the shortcut to something like <kbd>cmd</kbd>+<kbd>D</kbd> (some instructions on how to do that [here](https://blog.wavebox.io/be-a-keyboard-shortcut-master/)) does that work more reliably?

**Comment by brianlenz** [comment]
No, cmd-comma doesn't cause Wavebox to flash in the menu bar. I tried just now and the first two times did nothing (not even flash), and the third time, it flashed and opened. So, it seems like it only flashes when it actually works.

I changed the shortcut to CmdOrCtrl+D (which I had to do by typing that literal string out), and now the Wavebox menu flashes every time I hit the command. But, the preferences still don't open every time. It's about every other time that it works, it seems like. So, about half the time, it flashes the Wavebox menu, but doesn't open the preferences.

Hope that's helpful!

**Comment by Thomas101** [comment]
Thanks for the extra info. There's a short delay between the modal closing and it actually updating the state which indicates if it's open or not. This could be what's causing the behaviour with the Cmd+D shortcut. I'm not 100% sure if that's the same issue with the default shortcut, but I'll tighten this up the timings and we'll see if that makes a difference!

**Comment by Thomas101** [comment]
Hi, we've just released 3.2.0 which should make this better. It would be great to know if it's fixed it for you.

You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by brianlenz** [comment]
I just upgraded to 3.2.1beta, and it has the same issue. I hit cmd-comma 8 times, 1 second apart, and nothing happened. Only once I hit it repeatedly faster did the preferences open. So, it appears to be working in the same way.

**Comment by nmat** [comment]
Did some testing on this:

**gmail service:**
Opens preferences on the second hit of Cmd+, but not the first hit (also same effect on google calendar)

**slack service:**
Opens the preferences window immediately. No need for second hit on keyboard.

OS: macOS Sierra 10.13.1
wavebox version: 3.6.3beta

**Comment by Thomas101** [comment]
@nmat when you tested with Gmail, was it just Gmail you had or were there other accounts? What was the ordering of those etc? In the Gmail window did anything have focus? (e.g. you'd clicked in a compose window etc...)

I've just tried with one Gmail account and it seemed to work :-/

**Comment by nmat** [comment]
When I tested I had the gmail account at service 1 (sidebar with the indexed services for gmail)

Then slack beneath that. Switched between them and did the test.

In general it seemed that Cmd+, needed a double tap to be able to open preferences.

**Comment by brianlenz** [comment]
FWIW, I'm still experiencing the same issue on 3.6.3beta (macOS High Sierra 10.13.2 (17C88)). Just now, I had to hit `cmd-,` five times for it to open. I've got 4 different Google accounts (some with Calendar, Contacts, and Hangouts services attached).

The issue seems to only happen when Gmail has focus. When Calendar, Contacts, and Hangouts are in focus, `cmd-,` seems to work every time.

It doesn't matter which of the 4 Gmail accounts have focus; the same issue happens with all of them. It also doesn't seem to matter what I'm doing; most often the issue happens when just sitting at the inbox with no cursor in view.

One thing worth mentioning is that I _do_ have Gmail keyboard shortcuts enabled on all of my accounts. Is it possible that is somehow related?

**Comment by Thomas101** [comment]
I might have been able to fix this. Looks like it's something to do with the keyboard shortcuts...

**Comment by nmat** [comment]
Will get wavebox compiled from git tonight and see if I can test it on macOS.

**Comment by nmat** [comment]
Tested in GIT and the preferences window opens all the time now.

Tested in gmail, hangouts, calendar and a few others. Seems to have fixed the issue.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by brianlenz** [comment]
Looks to be working great to me! Thanks, @Thomas101!

**Comment by nmat** [comment]
verified on macOS 10.13.2 and wavebox 3.6.4beta. Works just fine there now. Perfect!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
