### ISSUE TITLE
Add support for retina display (avatars and icons)

### ISSUE THREAD

**Issue by zedix** [wavebox/waveboxapp#325]
Wavebox version: 3.1.16
Platform version: MacOS Sierra 10.12.5
Device: MacBook Pro (retina display)

Mailboxes avatars and every other icons inside vertical navigation bar are not "**retina friendly**" and looks _blurish_ on a Retina display. It make the app a little "un-polished".

Actual:
<img width="71" alt="image" src="https://user-images.githubusercontent.com/27975/28500774-97885d38-6fce-11e7-97c3-91e4082aaec2.png">

_The avatar is blurry (same for the google drive app icon)._

Expected:
<img width="69" alt="image" src="https://user-images.githubusercontent.com/27975/28500780-b446aef2-6fce-11e7-97d6-4448871942fe.png">

_The avatar should be retina friendly ._

Fix: Make every images twice their size (@x2) to support retina display.

Possible source hint: pass an explicit `size={80}` to `<Avatar />` (default: 40) in https://github.com/wavebox/waveboxapp/blob/master/src/scenes/mailboxes/src/Components/Mailbox/MailboxAvatar.js#L123

**Comment by Thomas101** [comment]
Thanks! It looks like Google sends a 50px image back by default. I'll look to see if can request a larger image.

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
