### ISSUE TITLE
Samepage.io notifications now flags an error every time a message is received

### ISSUE THREAD

**Issue by LesterU** [wavebox/waveboxapp#330]
* Which version of Wavebox are you using? 3.1.12

* Which Operating System are you using? Windows 10

This has started to happen since the last update. Every time a message is received it flags the error as shown in the attached screenshot.
![screenshot 2017-07-31 11 50 14](https://user-images.githubusercontent.com/27270261/28760116-6d3270f4-75e7-11e7-883c-8c9aaea9eb4e.png)

**Comment by Thomas101** [comment]
Thanks, I'm seeing the same. I'll take a look into it and put a patch out

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
