### ISSUE TITLE
Window resizing doesn't work correctly with Spectacle on Mac

### ISSUE THREAD

**Issue by igor-makarov** [wavebox/waveboxapp#331]
Wavebox 3.1.12
macOS 10.12.6
[Spectacle](https://github.com/eczarny/spectacle) 1.2 (b. 672)

When I use the "Left Half" or "Right Half" key stroke in Spectacle, the app doesn't resize to the expected size. 

I believe it's due to the window having minimum width. 

If possible, can the minimum width be removed to allow user to select it themselves?

**Comment by Thomas101** [comment]
I'll take a look at reducing it. Does it work with chrome? I think the min width on that is 400

**Comment by igor-makarov** [comment]
Yeah, Chrome can shrink way smaller! (And Spectacle can resize Chrome ok)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by igor-makarov** [comment]
I tried it and it works now! Thanks!
