### ISSUE TITLE
On Linux, cannot print from PDF preview

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#332]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.1.12.

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Elementary OS Loki 0.4.1

If I want to print an email there is no problem but when I preview a PDF attachment and from there want to print I only get a blank new WaveBox window and nothing happens.

**Comment by Thomas101** [comment]
Is this from the print button in the toolbar along the top? I think this is probably related to #232

**Comment by WebShapedBiz** [comment]
Yep, that the one and sorry for duplicate bug report, I'm usually more
cautious

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-08-02 13:28 GMT+02:00 Thomas Beverley <notifications@github.com>:

**Comment by Thomas101** [comment]
No worries! Easily missed. I'll close this off and we can continue tracking from there. Thanks :)
