### ISSUE TITLE
Trying to "pop out" Gmail Tasks Results In Window with Incorrect Content

### ISSUE THREAD

**Issue by ware** [wavebox/waveboxapp#334]
* Which version of Wavebox are you using? 3.1.12

* Which Operating System are you using? Linux Minut 18.2 (based on Ubuntu 16.04).

I've run into an interesting issue trying to get to my task list in Gmail.  As a reminder, any email thread can be made into a task by using "Add to Tasks" in the "More" dropdown.  Gmail will then bring up a little window down at the bottom of the screen which shows your current task list.  The format of this window is similar to (but smaller than) the window that comes up when you click "Compose" to create a new message.  The task window has three "buttons" in the upper right hand corner and the middle of those three is an arrow pointing to the top right representing "pop out".

When logged in to Gmail via Chrome, clicking on this task list pop out button brings up a new window that shows my tasks; essentially a larger version of what's shown by default and in its own window.

When logged in to Gmail via WaveBox, clicking on the task list pop out button brings a very different behavior.  If I click this while I'm just in my inbox, I get a window that pops up with the contents of "The conversation has been deleted".  If I click on this while I have a message open, I get a window with a copy of that message.

Looking at the URLs of the resulting windows, in Chrome I get https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=some_ver and in WaveBox, the URL is https://mail.google.com/mail/u/0?ui=2&view=lg&ik=some_ik&msg=inbox.  (NOTE: I replaced ver and ik with anonymized values).

**Comment by Thomas101** [comment]
Hi, we've been working on adding support for this and you can enable it with the experimental window opener.

There's some instructions on how to enable it [in this blog article](https://blog.wavebox.io/testing-the-new-window-opener/). It might also be worth updating to 3.2.0 which has just come out as this has some additional fixes around this too

**Comment by ware** [comment]
Awesome!  I'll check it out.

**Comment by Thomas101** [comment]
I'll close this off for now, but if you do have any more issues, just re-comment and I'll take another look. Thanks
