### ISSUE TITLE
G Suite accounts can't automatically login when re-open Wavebox

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [wavebox/waveboxapp#336]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.12.6

Used my CMU account to log into Inbox, but can't auto login as my @gmail.com account when restarting the application

**Comment by Thomas101** [comment]
Hi, some accounts that use Single Sign On can have trouble staying signed in.

There's a few steps you can try in [this KB article](https://wavebox.io/kb/staying-logged-in) under the **Accounts using Single Sign on (SSO)** section. If you try that do you stay logged in?

**Comment by xyzzyxyzzy0077** [comment]
Work like a charm, many thanks!

**Comment by Thomas101** [comment]
Awesome. Let me know if there are any more problems :)
