### ISSUE TITLE
Outlook (Office 355) - Can't drag messages from main list to sub-folders

### ISSUE THREAD

**Issue by mikesprague** [wavebox/waveboxapp#337]
* Which version of Wavebox are you using? [e.g. 3.0.0] 
   * v3.2.1-beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] 
    * MacOSX Sierra
    * Ubuntu 17.10

This behavior is working correctly in v3.2.0.

**Comment by Thomas101** [comment]
Hi, if you try restarting Wavebox does this work correctly? Just given it a try on 3.2.1 my end and it seemed to work :-/

**Comment by mikesprague** [comment]
That works for me for 1 message, and only if it's in the main view when the app starts. As soon as the view is changed or that 1st message is moved, doing it again starts to fail.

For what it's worth, it "appears" to be working from a UI standpoint - in other words, you can click/select the message and drag it somewhere but then it stays in its original location when you deselect.

Let me know if there's any other info/logs that would be useful.

**Comment by mikesprague** [comment]
One more note... If you right-click on the message and choose to move it that way it does work. It appears just the drag/drop is affected.

**Comment by Thomas101** [comment]
I think I'm seeing the same here - although quite sporadically. I'm also seeing some messages vanishing. For example I'll move it from inbox to test. The message vanishes from inbox but doesn't appear in test until I reload.

I gave the same a try in chrome and also tried switching between tabs. I was able to see the vanishing behaviour but not the messages staying in the same folder.

I checked out the logs when it failed for me and nothing was reported which is odd. You'd expect a http call or something to fail.

If you try it your web browser do you see any oddities or does it work as expected?

**Comment by mikesprague** [comment]
It's working well for me in Chrome and FF (we access our work email via `https://outlook.office365.com/owa/?realm=domain.name`).

It's also working for me when I revert Wavebox to v3.2.0.

It seems that a change specifically in the v3.2.1 that introduced this.

**Comment by Thomas101** [comment]
Hi, if you try this with 3.3.0 or 3.3.1 do you still see the issue?

**Comment by mikesprague** [comment]
I just tried both versions on my MacBook Pro and I'm still seeing the issue with them.

This seems to be such a weird/obscure issue but for some reason v3.2.0 still works as expected and every newer version since has the issue for me.

I'm going to continue to try using v3.3.1 regardless (using the context menu to move messages when needed) as I don't want to be pinned at a legacy version of the app. 

Happy to continue reporting if this version starts working (even intermittently) or a future version does.

Thanks for your continued work!

**Comment by Thomas101** [comment]
I've had a look at the commits that come after 3.2.0 and can't see anything that would go anywhere near this. I'm trying to scratch my head as to what it might be. I'm still having trouble reproducing the same behaviour which makes it difficult to get to the bottom of it!

Maybe it's something to do with the layout of accounts that I'm not testing. How are your accounts setup, what's their sleepable state and are the services display in the top toolbar or left sidebar? E.g.

1. Office 365 (sleep disabled) - services left sidebar
 1.1 Calendar (sleep enabled)
 1.2 OneDrive (sleep enabled)
2. Gmail (sleep disabled) - services top toolbar
 2.1 Google Drive (sleep enabled)
 2.2 Google Contacts (sleep enabled)
3. Gmail (sleep enabled) - services left sidebar
4. etc...

**Comment by mikesprague** [comment]
Thanks again for continuing to look into this. So, on a whim after reading your last reply, I tried changing the order of my sidebar:

* Before: Office365 was in position 1 with Gmail in position 2
* Now: Gmail in position 1 with Office365 in position 2

After making the above change the drag and drop of messages started working in Office365 again. I tried changing them back to their original order and it stopped working again so that definitely made an impact. 

Unless it's worth it to you to investigate further what's at the root of this issue you can probably close this.

---

🚫 Previous order of all services in left bar (Office 365 NOT working as expected):

  1. Gmail
    1.1 Google Calendar
  2. Office365
  3. Trello
  4. Custom site (gitter.im)
  5. Slack
  6. Slack

---

🚀 New order of all services in left bar (Office 365 dragging WORKS!):

  1. Office365
  2. Gmail
    2.1 Google Calendar
  3. Trello - sleep enabled
  4. Custom site (gitter.im) - sleep enabled
  5. Slack
  6. Slack

**Comment by Thomas101** [comment]
I've given that ordering a go and out of the maybe, 20 times I tried it, it failed once. I have to say I that if I navigate around after dragging, messages come back up in their old folders and sometimes disappear for 10-15 seconds altogether. Not to pass the buck, but it almost feels like an issue on Microsofts end with the client code falling out of sync with the server for some reason.

Thanks for all your help with the debugging. I think I'll close this off for now unless it gets worse. On the plus side though Microsoft have starting trialing a beta version of their outlook ui on some outlook accounts. Fingers crossed that this works a bit better :)

Thanks again for your help!
