### ISSUE TITLE
PDF download loses file name -renames to "Untitled"

### ISSUE THREAD

**Issue by TV-user** [wavebox/waveboxapp#338]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
O365 on 
![screen shot 2017-08-02 at 4 21 23 pm](https://user-images.githubusercontent.com/30671008/28895600-a587268a-779e-11e7-856c-b3173afaf75f.png)
MacOS 10.12.6

**Comment by Thomas101** [comment]
Hi, I'm not seeing this behaviour when I try. I wonder if I'm doing something different to what's happening your end. It would be great to get some more information....

* If you try the same steps in your web browser, does the file get named correctly?
* Do you have an outlook account and do you see the same behaviour here?
* If you try e-mailing yourself a PDF such as [this one](http://www.pdf995.com/samples/pdf.pdf) and then press the download right beneath it does that work?
![screen shot 2017-08-03 at 10 00 28](https://user-images.githubusercontent.com/103586/28914164-a29c4fba-7832-11e7-83d6-d0af7c8adfb5.png)

Thanks!

**Comment by jlappa1000** [comment]
Found this issue on the mac as well.   It happens to the second attachment that you want to download.

**Comment by dsfdscln** [comment]
Same thing happens with me since the latest Wavebox update to 3.2.0. I'm on MacOS Sierra 10.12.6. It occurs with both my gmail accounts and Microsoft Office 365 accounts. If I restart Wavebox the very first download is named the file name but every download after that is Untitled.

**Comment by Thomas101** [comment]
Thanks, I see the same now!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by dsfdscln** [comment]
Thanks Thomas. That fixed the issue for me.
