### ISSUE TITLE
[Request] Beta Download Button Link to GitHub Releases

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#343]
Wavebox 3.2.2
KDE Neon (Ubuntu 16.04)

I would like to request that the "Download" button in the update notification for Beta users be a link to the GitHub releases page instead of the main Downloads page as it would save a little time for making updates to the Beta branch.

**Comment by rhys101** [comment]
Agree - will update the beta download flow in the upcoming release.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by MichaelTunnell** [comment]
tested, confirmed working, closing issue.

Thank you
