### ISSUE TITLE
G Suite apps on different side in header than Gmail account

### ISSUE THREAD

**Issue by scottcorgan** [wavebox/waveboxapp#344]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.12.5

---

Not sure if this is intended, but the icons for G suite apps are on a different side of the window than the default Gmail apps:

**Gmail Apps**

<img width="234" alt="screen shot 2017-08-07 at 10 55 34 am" src="https://user-images.githubusercontent.com/974723/29032383-2fae953c-7b5f-11e7-9aff-ab09786fc6f0.png">

**G Suite Apps**

<img width="1338" alt="screen shot 2017-08-07 at 10 55 39 am" src="https://user-images.githubusercontent.com/974723/29032380-2da190aa-7b5f-11e7-85dc-dde5444ba036.png">

**Comment by rhys101** [comment]
You're right - the default should be right-aligned.  Does this occur for all your G suite apps or just a few? Also, have you set up any custom CSS / JS settings for the accounts?

**Comment by scottcorgan** [comment]
I only have one G suite account, so I can't really test it further. I have nothing custom setup accept a few configuration toggles. But, no custom JS or CSS.

**Comment by Thomas101** [comment]
Hi, this can be configured from the account settings. If you right click on your account and go to `Account settings` you should find a `Services` section. You can switch where you want your services to be displayed, either left or right depending on what works best for you :)

![screen shot 2017-08-14 at 11 04 21](https://user-images.githubusercontent.com/103586/29267392-6125b628-80e0-11e7-919f-8f5ea041ca28.png)
