### ISSUE TITLE
Uninstall Wavebox Manjaro

### ISSUE THREAD

**Issue by stroudmw** [wavebox/waveboxapp#345]
* Which version of Wavebox are you using? [e.g. 3.0.0]
no idea - current as of 08/08/2017. 32 bit deb package installed.
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Manjaro Linux 17.0.2 32 bit 

I downloaded and installed Wavebox on my Linux system this morning. I did the initial setup and found it a bit slow (much slower that Evolution or Thunderbird for my gmail accounts). I've also discovered that I'm on a 14 day free trial! I received no warning that It was demo software that I have to pay for! Also, I can't find it in any of my menus.

So please tell me how I can completely remove it from my system. Thank you.

**Comment by rhys101** [comment]
Information about Wavebox is at https://wavebox.io - regarding the uninstall process, it's dependent on the package tool you used to install. On Manjaro, if you used `yaourt` then you can uninstall (including dependencies) by using the command:
`yaourt -Rsn wavebox-bin`

**Comment by plutoneld** [comment]
@stroudmw You are on a 14 day free trial of the **Pro** version, as stated on the home page: _Use basic for free, or trial Pro for 14 days_. For more information on different versions see this page [https://wavebox.io/pricing](https://wavebox.io/pricing).

Installing deb files under Manjaro doesn't seem to be the standard solution, so I recommend checking the documentation for your OS for how to uninstall it (in case rhys101's solution above didn't work).

**Comment by shubhzgang** [comment]
for **ubuntu** users:
see if it is installed via snap:
`sudo snap list`
then remove it using the command
`sudo snap remove wavebox`
