### ISSUE TITLE
Add ability to make Wavebox the default mail client on Linux

### ISSUE THREAD

**Issue by tonyjames** [wavebox/waveboxapp#347]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.2.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Fedora Workstation 26

**Comment by bkuri** [comment]
I can see the entry in gnome control center, but it doesn't really do anything:

![screenshot at 12-37-48](https://user-images.githubusercontent.com/138886/29085994-a9bcdc94-7c36-11e7-95cf-339f724e028b.png)

I also tried the following command:
```sh
$ xdg-open mailto:test@bkuri.com
[WB_LAS] started 8263
[WB_LAS] 9 processes found. Messaging...
[WB_LAS] Activating 15939
```
... still, no response from Wavebox.

**Comment by Thomas101** [comment]
@tonyjames which install method did you use when installing wavebox (tar/snap/deb)? There is some extra configuration to ensure mailto links get piped to Wavebox

@bkuri if you completely quit Wavebox and try opening a mailto link from your browser does that work? I think this might be related to another bug.

**Comment by bkuri** [comment]
@Thomas101 quitting Wavebox and clicking on a mailto link opened the app, but no compose window was offered (I do have 2 accounts registered, so maybe it couldn't decide which compose window to open?).

BTW, I forgot to add my env details:

```
Wavebox v3.2.0
Arch Linux (using wavebox-bin AUR package)
```

Hope that helps!

**Comment by Thomas101** [comment]
@bkuri there's a fix in the beta channel at the moment (3.2.3). This should be heading out to the stable release channel soon. If you want to give it a try there's some instructions on how to switch here... https://wavebox.io/kb/beta-channel

**Comment by tonyjames** [comment]
@Thomas101 sorry for the delay.  I did see this worked previous but no longer appears to work with Wavebox 3.3.0.  I've tried on both Fedora 26 and CentOS 7.  I've installed Wavebox via tar.

**Comment by Thomas101** [comment]
@tonyjames I'm guessing this is with a Gmail account? In a recent gmail release they broke the autofill functionality that we were using. The latest beta (3.3.3) has a fix for this. More info here: https://github.com/wavebox/waveboxapp/issues/382

**Comment by Lombress** [comment]
I have the same exact issue now, on Kubuntu 17.10 with Wavebox 3.13.0. Mailto links open Thunderbird (which I had previously installed) unless I add x-scheme-handler/mailto=wavebox.desktop to ~/.local/share/applications/mimeapps.list, but then it opens Wavebox without composing window. Then if I edit the file usr/share/applications/wavebox.desktop and replace `Exec=/opt/wavebox/Wavebox --mailto=%u` with `Exec=/opt/wavebox/Wavebox mailto=%U` or `Exec=/opt/wavebox/Wavebox mailto:%U`, then it opens Wavebox and the composing window, but without the address bar filled
