### ISSUE TITLE
Is it possible to introduce protonmail into wavebox?

### ISSUE THREAD

**Issue by sudoyang** [wavebox/waveboxapp#349]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
ubuntu 16.04

**Comment by Thomas101** [comment]
Hi, we're working on adding support for more account types and services. We're currently tracking the requests for this here #130 which also includes a form to vote for the services you'd like to see added to Wavebox. I've added protonmail in to the list so we can start tracking it.

You might be able to add it with the "Any Web Link" account type. It would be great to know if that works!

I'll close this off for now, so we can continue tracking progress in #130
