### ISSUE TITLE
Any way to change the titlebar text based on active service?

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#351]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.12

I would like the titlebar text to change based on which site/service I'm using – rather than just "Wavebox (x)" – so I can track time usage. E.g., "aa@gmail.com | Re: hello" or "whatsapp" or "BBB Slack | general" etc.

Is this possible? If not, dealbreaker for me...

**Comment by Thomas101** [comment]
Should be pretty easy to add in - the unread information is already propagated up! I'll take a look

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.2.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
