### ISSUE TITLE
Crash VM completely in Mint 18.2

### ISSUE THREAD

**Issue by RiaanBurger** [wavebox/waveboxapp#352]
Using Wavebox v3.2.0 on Linux Mint 18.2 in Virtualbox for evaluation to consider adoption for our company as a whole it crashes the VM. 

`--enable-logging --v=1 > log.txt` doesn't result in a file (it crashes even before able to enter the command line in zsh history.

I made a manual entry into syslog with `logger cccc` before running the app and there are no syslog entries after the `cccc` marker and before the next boot entries. Is there some way I can generate some logging data to help find the issue or is this perhaps a known problem for VMs?

**Comment by Thomas101** [comment]
Hi, we've had a few reports of Wavebox crashing when used in Virtualbox. We think it's down to the 3d acceleration and the drivers used in Virtualbox. If you try running it with...

`./Wavebox --disable-3d-apis --disable-gpu --ignore-gpu-blacklist`

does it still crash?

**Comment by RiaanBurger** [comment]
Thanks for the help Thomas. That did the trick.

I'm not sure if it may be related, so will mention it here for now, but let me know if it needs a different issue. The VM has internet (browsers and pings work), but Wavebox shows an error window "Whoops! There seems to be no internet connection."

Log:

```
[6977:0814/130607.487938:VERBOSE1:bus.cc(715)] Requested to remove an unknown filter function: 1 with associated data: 0x35d7e1143000
[6977:0814/130607.666727:VERBOSE1:proxy_config_service_linux.cc(1724)] Detected no-op change to proxy settings. Doing nothing.
[6977:0814/130608.191088:INFO:CONSOLE(227)] "Bootstrap failed", source: file:///opt/wavebox/resources/app.asar/bin/scenes/mailboxes/mailboxes.html?clientId=0153cc09-b09f-443e-a871-10788e7c8bf3&clientToken= (227)
```

Could it be some security configuration / AppArmor on Mint/Ubuntu or my firewall settings or am I speculating too widely?

**Comment by RiaanBurger** [comment]
Also to add, I tried various combinations of the command line options you mentioned and this one alone seems to get the app to run (if that helps):

```bash
/opt/wavebox/Wavebox --disable-gpu
```

**Comment by Thomas101** [comment]
It could be that the launch configuration got corrupted on the first run. Try deleting `~/.local/share/wavebox/`. Failing that are you using a proxy server at all?

@rhys101 mentioned that he had a similar problem with vmware. He said updating `open-vm-tools` and disabling gpu acceleration seemed to fix the original issue too.

Are you planning on using Wavebox in a vm long term, or just for testing?

**Comment by RiaanBurger** [comment]
Deleting `~/.local/share/wavebox/` didn't work, but...

**Success**: That was a great hint, thank you very much! I turned off 3D acceleration for the VirtualBox VM and Wavebox now starts without a problem and connects to the internet (no proxy before or now).

Hopefully we have all the right keywords in this thread for others to find the help in future.

We use Ansible-managed fully configured Linux Mint desktops at the company, so the VM is just for evaluating new software and we will change to using Wavebox on bare metal once it is working well. Primarily we want to use it as a Google Hangouts Video tool. It would be great if it can also handle our G-Suite e-mail, but I've not seen whether one can have the same sort of privacy and security that a browser can provide with plug-ins like uMatrix, uBlock and NoScript.

If you need anything from me in terms of further testing on this matter, please let me know.

**Comment by Thomas101** [comment]
Awesome thanks. I might put a kb article together from this in case anyone else has similar issues

**Comment by Thomas101** [comment]
@RiaanBurger out of curiosity was this a 32-bit or 64-bit virtual machine?

**Comment by Thomas101** [comment]
I've added a [KB article about this here](https://wavebox.io/kb/wavebox-in-virtual-machine) if it helps anyone else

**Comment by RiaanBurger** [comment]
Just wanted to add: Evaluation complete, group licences bought and added to our desktops' automation. Our people will get Wavebox as they run updates this week. Thank you very much!

This was a 64-bit host and guest instance of Linux Mint 18.

**Comment by Thomas101** [comment]
Awesome! Great to hear @RiaanBurger. If you have any trouble, we're here on Github and on https://wavebox.io/support
