### ISSUE TITLE
Add support for new Allo web-service

### ISSUE THREAD

**Issue by codeman6100** [wavebox/waveboxapp#356]
Google has just opened up the web-service for their Allo IM client.  (allo.google.com/web)  As with Hangouts it would be nice if this was added as a service for google accounts.

* Which version of Wavebox are you using? [e.g. 3.0.0] 3.2.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Windows 10 and Ubuntu 17.04

**Comment by Thomas101** [comment]
I'll take a look into adding this in. We have a backlog of Google services to add currently in #131 too
