### ISSUE TITLE
custom notification

### ISSUE THREAD

**Issue by sidewinder13** [wavebox/waveboxapp#357]
version 3.2.0
Kubuntu 17.04
im looking for  a way to  run a simple script with every notification  for a new mail, so i  have a led notification through my  connected arduino . Basically what  i  want is to  run  a python  script or better just  a command.
How can i do  that?

**Comment by Thomas101** [comment]
Hi, sounds like an interesting project! We have some extension stuff in the pipework that might let you do something quite easily along these lines. At the moment though probably the easiest thing is to look at some simple scraping. Do you want it flash constantly when there are new messages, or just flash a couple of times when a new message arrives?

**Comment by sidewinder13** [comment]
hi Thomas101
The code is ready  for the arduino  it actually  does some notification  stuff already.I  just want the option to execute a script on  event...

 the python code is this ..
`pass
import serial # if you have not already done so
ser = serial.Serial('/dev/ttyUSB0', 9600)
ser.write('3') # 51` 
and i run  this with a simple script ...

**Comment by Thomas101** [comment]
Until we start shipping the extension code, probably your best bet is to inject some javascript into the main window and watch the document title for the unread count changing and when it does ping a local webserver.

For example, if you go to View > Developer Tools and press the console tab. Then paste something along the lines of...

```js
let last = undefined
setInterval(() => {
  let changed = false
  if (document.title.startsWith('Wavebox (')) {
    const current = parseInt(document.title.split(')')[0].replace('Wavebox (', ''))
    if (last !== current) {
      changed = true
      last = current
    }
  } else {
     if (last !== 0) { changed = true }
     last = 0
  }

  if (changed) {
    window.fetch('http://localhost/changed?count='+last)
  }
}, 1000)
```

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
