### ISSUE TITLE
Screen Share for Hangouts (not working)

### ISSUE THREAD

**Issue by RiaanBurger** [wavebox/waveboxapp#359]
Using Wavbox 3.2.0 on Linux Mint 18.2 (Cinnamon desktop); For hangouts, when I select share screen it does nothing (so screen sharing doesn't appear to work). I did search the issue queue for "share screen" but did not find any existing issues.

We use Wavebox as a replacement for Chrome, so do not have the browser available as a fallback or external option and Firefox does not support Hangouts video.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. We've been taking a look at what hangouts does behind the scenes for this and it looks like chromium is bundled up with a hangouts extension that provides some additional support for screen sharing.

We're going to releasing extension support for Wavebox in September so we'll look further in depth at what's going on here and look to see if we can add support.

Just so I can find it later, here's the bundled extension: https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/chrome/browser/resources/hangout_services

**Comment by psywolf85** [comment]
Extensionsupport reached beta. I would love to test this feature :)

**Comment by situmam** [comment]
Hello @Thomas101 . Have you guys made any progress on the screen sharing side of things? I think there is a special extension needed

**Comment by Thomas101** [comment]
@situmam you're right, there's a hangouts extension built into chromium. We're still in the midst of expanding our extension support and there's still some API's we haven't implemented as yet. We're working through some of the requested extensions and expanding our coverage at the same time. Once we've ticked off a few more we'll be looking to add the final few that hangouts needs

**Comment by psywolf85** [comment]
This is now the only issue that prevents me from completly replaceing Chrome.
I think many google apps users will switch as soon as this, and google Chat support is implemented.

**Comment by rpietro** [comment]
hey guys, just checking whether you had any news on this extension. it would be awesome to have hangouts fully functional on qutebrowser

**Comment by Thomas101** [comment]
Thanks for taking the time to report, I'm merging this issue and a few others which report the same into #912 so we can track progress there and hopefully add support in. Thanks!
