### ISSUE TITLE
Print Option / Mac OS

### ISSUE THREAD

**Issue by Jul313** [wavebox/waveboxapp#360]
* Which version of Wavebox are you using? 3.2.6

* Which Operating System are you using? Mac OSX 10

Dears,

I have issue printing pdf/image attached file from wavebox directly.

Do you have any fix prepared in that issue?

Many thanks.

**Comment by Thomas101** [comment]
Hi, we're currently tracking this issue on #194 and #232 and looking for a fix/workaround.

The root cause looks to be an upstream issue which prevents this from working, but we're working on some different workarounds that will hopefully give a better experience
