### ISSUE TITLE
Office 365 ADFS Times Out

### ISSUE THREAD

**Issue by etrigan63** [wavebox/waveboxapp#362]
* Which version of Wavebox are you using? 3.2.0

* Which Operating System are you using? Windows 10

I am accessing my day job's ADFS Office 365 site and the pages are timing out due to inactivity. The page is requesting that the browser be closed. This requires a restart of Wavebox which is incredibly annoying at best. I have turned on Artificially Persisting Cookies and Experimental Window Opener. The first had no effect, the second I just applied and will let you know. Is there some way to send a keep-alive to Office 365? No issues with Gmail.

**Comment by Thomas101** [comment]
Hi, there's some fixes gone into the beta channel for this which we hope will resolve the issue. There's some instructions on how to switch channel [here](https://wavebox.io/kb/beta-channel). Would be great to know if that fixes for you

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
