### ISSUE TITLE
Prompted to name Gmail attachment when downloading

### ISSUE THREAD

**Issue by varresa** [wavebox/waveboxapp#363]
When downloading an attachment, Wavebox is prompting me to chose a destination folder and it names the file "Untitled" instead of defaulting to the existing name of the file. 

See screenshots of Wavebox behavior vs Gmail in Chrome. 

![monosnap 2017-08-23 16-57-33](https://user-images.githubusercontent.com/31292583/29638450-5074dcc2-8825-11e7-86d5-37fa5036773a.png)
![draft ec meeting minutes - renee sustainableharvest org - sustainable harvest international mail 2017-08-23 17-01-44](https://user-images.githubusercontent.com/31292583/29638452-51fb43d8-8825-11e7-8db2-fe1cb745450f.png)

* Which version of Wavebox are you using? 3.2

* Which Operating System are you using? Apple OSX Sierra

**Comment by Thomas101** [comment]
Hi, this is a known issue with 3.2.0 at the moment. It's fixed in the beta channel if you want to give that a try ([more info on how](https://https://wavebox.io/kb/beta-channel)) or if you're happy to wait we're planning on pushing the beta out to stable next week

Related #338
