### ISSUE TITLE
Slack overflow-transparent-bg after uploaade a file

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#364]
[3.2.6-beta]
[ArchLinux 4.12.8-1-ARCH x86_64 GNU/Linux]

After uploading a file to slack, the transparent bg still appear,
looks like a conflict with slack js
below screenshot of slack screen and webInspect
![image](https://user-images.githubusercontent.com/9933516/29638579-ee25bebe-8857-11e7-9586-161aec1eeb8d.png)
![image](https://user-images.githubusercontent.com/9933516/29638586-f3183258-8857-11e7-89aa-4e35c04da75c.png)

**Comment by Thomas101** [comment]
Hi, this could be an issue with Slack. If you right click on the account in the left and click reload and try again do you see the same behaviour?

If you do which method did you use to upload (drag & drop, +, then Your Computer, etc...) and which file format is it?

**Comment by reatlat** [comment]
@Thomas101 , Yes, tried to reload view, the error comes every time.
I use copy paste(ctrl+v) method for paste *png* imagefrom screenshot.
This issue comes on 3.2.6-beta
I rolled back to 3.2.2-beta in older version all works perfectly.

**Comment by reatlat** [comment]
@Thomas101 #364 #close 

I don't know why... it was....
I just rebuild package, clean cache, and now slack work correct...
I think it was my mistake,
Sorry :upside_down_face:
