### ISSUE TITLE
Pro version still asking me to upgrade. 

### ISSUE THREAD

**Issue by balloch** [wavebox/waveboxapp#368]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 14.04

Any suggestions?

**Comment by rhys101** [comment]
Will check it out - can you email details to support@wavebox.io

Also worth double-checking that you're logged in ok under Settings ->Wavebox as well.

**Comment by nmat** [comment]
@balloch does this continue to happen after 3.5.0 release? Are you using snap or deb package?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
