### ISSUE TITLE
Unable to mute notification sound on a general account

### ISSUE THREAD

**Issue by jeslen** [wavebox/waveboxapp#369]
I'm using Wavebox pro 3.2.0 on MacOS Sierra 10.12.6

I have a general account set up for https://play.google.com/music/. In the settings for the account, under general, I have the 'Play notification sound' switch turned off (it's grey), but every time a new song comes on it plays the notification sound.

**Comment by Thomas101** [comment]
I think the webpage is able to overwrite the setting at the moment, but this shouldn't be the case. I'll look into fixing

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.3.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
