### ISSUE TITLE
Previewing documents does not work in the app

### ISSUE THREAD

**Issue by andrushka80** [wavebox/waveboxapp#370]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.2.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 7

99% of the time I cannot preview an attached doc in an e-mail in Wavebox. It keeps saying ”Whoops! There was a problem previewing this document”. This happens with simple files such as .pdf, .jpg etc.

When I open the Google Inbox page in Chrome and do the exact same actions, previewing works OK for the same files.

Thanks,
Andrei

**Comment by Thomas101** [comment]
Hi, version 3.3.0 has just been released with some fixes for this. If you try updating and try again do you still see the same issue?

**Comment by andrushka80** [comment]
Yes, it works better. I still have misses, but they replicate in Chrome too.

**Comment by Thomas101** [comment]
Awesome, I'll close this off for now then :)
