### ISSUE TITLE
#feature - add Facebook Messanger

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#374]
It will be great if in next release add notification count for messenger by Facebook

right now I use a webview for this address https://www.messenger.com
It's quite similar like Slack integration

![image](https://user-images.githubusercontent.com/9933516/29888425-3210c632-8dc1-11e7-85db-6bad7389c018.png)

**Comment by Thomas101** [comment]
Hi, we've got an issue setup for new account requests (https://github.com/wavebox/waveboxapp/issues/130) and messenger is already in there. We're also working on an extension api which will make it much easier to add snippets to pull out things like counts from the dom.
