### ISSUE TITLE
Does custom CSS affect sidelist?

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [wavebox/waveboxapp#375]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.3.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS

Not sure whether it is intended so... the large calendar icon is pretty annoying BTW

**Comment by Thomas101** [comment]
Afraid not, custom css is only applied to the guest pages...
