### ISSUE TITLE
feature request: import/export/cloud-sync of Wavebox settings incl. accounts their order, colours, etc.

### ISSUE THREAD

**Issue by GeraldLoeffler** [wavebox/waveboxapp#376]
Wavebox should allow me to import/export from/to a file all my Wavebox settings:

- general layout and notification settings, etc.
- all accounts i've configured incl. all settings for each account
- the Wavebox Pro account
- keyboard shortcuts etc.

With file-based import/export i could put the settings file onto Cloud storage like Dropbox and thereby keep the settings of several Wavebox installations in sync.
But Wavebox could also directly support cloud-sync of these settings.

**Comment by Thomas101** [comment]
Hi, there's a tool to import & export accounts at the moment ([more info here](https://wavebox.io/kb/copying-accounts)), but it's more of an export/import cycle than a continuous sync.

Cloud sync is high on our list and something we're working to adding though!

**Comment by GeraldLoeffler** [comment]
Thank you for that - i had missed the import/export feature and i'm glad to hear that cloud sync will be coming.
