### ISSUE TITLE
Add support for Gitter

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#379]
Gitter can be added as an "Any web link" account, which is something, but having notifications and status badges (like Slack accounts) would be really great.

* Which version of Wavebox are you using? [e.g. 3.0.0]

3.3.2beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Mac OSX 10

**Comment by Thomas101** [comment]
I've added gitter into #130
