### ISSUE TITLE
Feature request: dark theme

### ISSUE THREAD

**Issue by texelate** [wavebox/waveboxapp#38]
Thank you for this - it's just what Linux needs, in my opinion. 

Is there any way to use Stylish themes? Or have a dark them? Like a lot of people, I'm not keen on the standard Google look. 

I'm using Fedora 25.

**Comment by B2D235** [comment]
I found this while exploring the settings, you can set custom CSS to Google Inbox (and others); there are a few examples provided here: https://github.com/Thomas101/wmail-user-scripts

I've not got time to play a lot with it right now, but if stylish themes are CSS perhaps it's as easy as putting the code in there? If not making your own theme (I just tried setting the body background to #222 and it worked :))

**Comment by Thomas101** [comment]
As @B2D235 said, the custom css and js within each account are the way to do this at the moment. It's a little rough around the edges to get setup, but we're looking towards some kind of extension support in the future which should be just click-and-go :)

**Comment by texelate** [comment]
Excellent, thanks @B2D235 and @Thomas101!
