### ISSUE TITLE
Pasting content from Office for Mac results in bitmap, not text

### ISSUE THREAD

**Issue by Webreaper** [wavebox/waveboxapp#380]
Wavebox 3.3.2 beta
OSX 10.12.6
Office for Mac 2016

When I select text from either an MS Word document, or an Excel sheet, and paste into an email, the resulting content is a bitmap representation of that text, not the text or table. I think Wavebox is using the BMP clipboard content, and not the text.

**Comment by Thomas101** [comment]
Is it word/excel online or installed that you're selecting the text from? If you try pasting the text into chrome do you see a image or does the text get pasted in?

**Comment by Webreaper** [comment]
Installed.

Sorry, that was stupid of me, I should have tried it in Chrome first. And yes, you're right - it looks like it's an Inbox bug, not a Wavebox issue. Thanks!

**Comment by Thomas101** [comment]
No problem :). It might be worth raising the issue on the [Inbox Product forum](https://productforums.google.com/forum/#!forum/inbox)
