### ISSUE TITLE
SEP 12 founds virus in the installer file

### ISSUE THREAD

**Issue by hgghyxo** [wavebox/waveboxapp#385]
![image](https://user-images.githubusercontent.com/8234132/30474016-870c8ac0-9a02-11e7-8dd9-f9fa77e5502a.png)

* Which version of Wavebox are you using? [e.g. 3.0.0]
n/a
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Win10

**Comment by Thomas101** [comment]
Thanks for reporting. Not sure why Symantec have flagged this version in particular. There's some more info about the WS.Reputation.1 warning [here](https://community.norton.com/en/forums/clarification-wsreputation1-detection).

I've reported the false positive to Symantec and they say they try to respond within two working days so we'll see what comes out from that.

Thanks!

**Comment by Thomas101** [comment]
Just had a response from symantec, if you update the virus definitions after 24 hours and try again, it should no longer flag it up

**Comment by hgghyxo** [comment]
I can confirm it, SEP 12 no longer detects it as harmful

**Comment by Thomas101** [comment]
Perfect, I'll close this off. Thanks!
