### ISSUE TITLE
Strange search window at bottom of window

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#386]
In google mail.

Keep press tab. You will get to the bottom of the page at some point. Just keep pressing tab all the time. After a while a strange Search window is being shown and you can only get rid of it by reloading the window or restart the app.

Reproduced on both beta and stable on Windows 10 and Mac OS. (only tested in gmail though) (Note also the topbar if using the top bar for other services like contacts gets pushed away.

Version: 3.3.2beta and 3.3.0 
OS: Windows 10, MacOS Sierra 10.12.6

**Comment by nmat** [comment]
![image](https://user-images.githubusercontent.com/383031/30513336-ca787198-9b01-11e7-91a2-ef2da4b946f0.png)

**Comment by Thomas101** [comment]
Thanks! We're seeing the same here

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.3.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
@Thomas101 thank you. I will give this a try when I get home. I am not running beta where I am now so let me get back to you in this ticket.

**Comment by nmat** [comment]
Verified on Windows 10 and MacOS, works fine now. (Had problems upgrading the branch on windows 10 though)

Closing this issue.
