### ISSUE TITLE
Feature request: Display mail sender and subject as the window title

### ISSUE THREAD

**Issue by ehausen** [wavebox/waveboxapp#387]
Feature request: Display mail subject as the window title

Currently Wavebox displays "Wavebox [number]" 
![screen shot 2017-09-18 at 12 31 02](https://user-images.githubusercontent.com/6204129/30536162-6fa00430-9c6d-11e7-97a2-0f1844a080b6.png)

This is not useful for anything.

Better would be to display mail sender and subject as the window title.

**Comment by Thomas101** [comment]
Hi, which account type is this with? We do propagate the page title up to the titlebar, but we don't enhance it anymore than what gmail/inbox/outlook etc sends

**Comment by ehausen** [comment]
It's Inbox.

Well, I have the Wavebox (1234) at the top, that is already extra, so I thought, why not add the active mail subject there too

**Comment by Thomas101** [comment]
It's a little tricker to scrape the current subject out of the UI but I'll have a look to see how easy this might be

**Comment by Thomas101** [comment]
The current version of Wavebox propagates the document title into the main window. With Gmail this means the mail subject is shown at the top of the screen. As [Google is sunsetting Google Inbox](https://techcrunch.com/2018/09/12/say-goodbye-to-inbox-by-gmail/) in March, this isn't something we're going to be adding to Wavebox for Google Inbox.

We are continuing to improve our support for the new Gmail though and will be providing some easy tools before to migrate across before Google Inbox is shut down.

Thanks!
