### ISSUE TITLE
Window opener cuts off titlebar on Mac

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#388]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.3.3beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Mac OSX 10.12

When opening links with the Wavebox window opener, the window's title bar is frequently hidden behind the system menubar.

![screen shot 2017-09-18 at 11 03 16](https://user-images.githubusercontent.com/1042866/30549393-a81c021a-9c62-11e7-93aa-869e408567f1.png)

**Comment by jason0x43** [comment]
Note that this isn't new to v3.3.3; it's been happening since at least v3.1.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. So I can try to reproduce the same behaviour it would be good to know...

* Is `Show Titlebar` in settings disabled or enabled?
* When you see this is Wavebox fullscreen?
* Does it happen everytime or just sometimes?
* Are there any specific links or locations of links that you click that causes this behaviour (e.g. always a Google drive link in an email, etc...)

Thanks!

**Comment by jason0x43** [comment]
* `Show Titlebar` is disabled
* Wavebox is fullscreen (it's actually split screen with Messages)
* Almost every time (but not every time). It looks like it might only happen when the new Wavebox window causes the OS to switch to a new Space (I have two monitors and generally have full screen apps open on both).
* The issue doesn't appear to be confined to specific targets (I've seen it with GitHub, Google Drive, and StatusHero this morning)

More details about my setup:

I have a MacBook connected to an external monitor. I use both the MacBook screen and the monitor. Typically I'll have Wavebox and Messages open in split-screen mode on the MacBook, and other things running in fullscreen on the external monitor. The external monitor is my default screen, so clicking a link in Wavebox (on the MacBook screen) opens a window on the external monitor.

If the external monitor is on a desktop space and I click a link, a Wavebox browser window will open there with a titlebar. If the external monitor is on a fullscreen app when I click a link, the OS will shift to a desktop space and open a Wavebox browser window without a titlebar. In both cases the Wavebox browser window is in the very top left corner of the screen, which seems a bit odd.

If the Wavebox browser window doesn't have a visible titlebar and I open Mission Control, the Wavebox browser window titlebar becomes visible, and it remains visible after closing Mission Control.

**Comment by Thomas101** [comment]
Thanks for the detailed description! I've managed to reproduce and fix it. It will be released in the next beta :)

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.3.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by jason0x43** [comment]
The issue appears to be fixed in beta 3.3.4. Thanks!
