### ISSUE TITLE
Feature Request: Grouping + Social Media (For notifications)

### ISSUE THREAD

**Issue by ghost** [wavebox/waveboxapp#39]
* Which version of Wavebox are you using? [3.1.2]
* Which Operating System are you using? [Arch Linux]

Hi,

First off I love the application and I'm happy to use it as a daily driver for overseeing my accounts; however there are a couple of features I hope could be considered one day, primarily grouping. 

I have three businesses/projects with separate email accounts - The side bar is fine/perfect for this, but becomes messy when I also wish to include (for example), Trello, Twitter (any website), Facebook(any website), Instagram(any website), for each account separately. I think an easy and neat solution would be to allow further use of the topbar/service bar which is currently only being utilised for extended services  (Calendar, Contacts, etc for Google) - By allowing use of the top bar, the side bar can then be treated (if desired by the user) as a profile switcher of sorts, dropping the side bar from 15 icons to 3 (In my example use-case)  

An additional request which would be neat to see, is integration with services like Twitter, Facebook, WhatsApp; to allow notifications through the system. If grouping ever becomes a thing, then the sidebar counter could be representative of the total number of new notifications, or a user selected preference (To notify only on email, or all services under the 'group', for example)

What do you think?

Anyway, thanks again for providing such an awesome tool;

Kind Regards

**Comment by jacksarick** [comment]
I have a similar problem. My current solution is to simply colour-code my accounts (blue is business, green is school, red is personal), but I understand it's not ideal for everyone. I'd be on board for some sort of profile switcher, though I think that some serious thought would need to go into it.

**Comment by Thomas101** [comment]
Hi, this is something we've talked about and something we're struggling a little bit with ourselves. We've been thinking about some kind of profile support, a little bit like chrome has profiles now. This would allow you to switch between 'Personal', 'Work', 'My Project 1', ...etc although thinking about the use case I think you're talking about this wouldn't give notifications across profiles per-say.

The top toolbar is definitely under-utilized at the moment, so there's scope there to do something with it. I think this is something we'll take a look at and play about with a little.

More services like twitter, facebook etc are on the way. There are a few feature requests hanging around already ;-)

**Comment by mikesprague** [comment]
+1 It would be super useful to group accounts (personal, work, etc.). 

The only potential issue I see with Chrome-like profiles is that people might want access to accounts from multiple profiles in the same view.

As opposed to profiles, might be really cool if each group of accounts had a master icon and they expanded/collapsed in the left bar - or something like that.

**Comment by MichaelTunnell** [comment]
I would really like to see this happen. I was willing to use multiple instances of Wavebox to accomplish the same thing but if grouping were done then that would be even better.

I think the top bar method would be a good solution because that is what I already use for the Google accounts.

I do not like the idea of the profile approach though as that would make the notifications and unread info not work. I really like Wavebox but I think profiles would eliminate some of what makes Wavebox useful.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account by right-clicking on one of the tabs and picking `Add another service`

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by logankoester** [comment]
Thank you! Been eagerly waiting for this. Can't wait to get home and try it

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
