### ISSUE TITLE
Input locks up periodically

### ISSUE THREAD

**Issue by tonybyng** [wavebox/waveboxapp#390]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Wavebox 3.3.3beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Linux Mint 18.2 with Cinnamon desktop

After being open for up to a day the UI prevents further input - left side panel options not accessible, emails cannot open, top  menu still functions but wont activate any features on screen. Emails do continue to come in and screen updates to show incoming emails but cant do anything input wise. Killing all processes and restarting solves the problem for a while. Happens on more than one machine (both same OS and version). Notice it on work PC after overnight inactivity and laptop after daytime inactivity

**Comment by Thomas101** [comment]
Hi, which install method have you used to install wavebox? (e.g. snap, deb, tar, etc). If you take a look at the Wavebox data folder (`~/snap/wavebox/current/.local/share/wavebox` for snap installs and `~/.local/share/wavebox/` for others) what's the size of the folder?

**Comment by tonybyng** [comment]
@Thomas101 Thanks for the reply. I actually logged it initially through your web based form and then thought that I should probably log it here instead. Ive had a reply back from Rhys asking similar questions. It was a 64 bit deb download initially, then I added the PPA when I flipped onto the beta system.  The folder is around 260k when i looked the other day so unlikely to be that which causes it.  Ive also confirmed that the mouse wheel does move the scrollbar up and down and emails do still come in but I cant click on any of the emails or the buttons. Ive sent in a private video clip of the issue too. 

Im normally sat on the Inbox by gmail but Ive tried leaving it on outlook.com overnight and it still happened. The only thing "joining" the 2 systems is that i did set things up on the laptop and then exported the config and imported it onto the desktop. I will try removing all the accounts on the laptop and maybe just add one in and see if the problem occurs

**Comment by Thomas101** [comment]
Thanks for the extra info. There doesn't seem to be anything that could be causing it there.

There's a few extra bits we can try. Firstly, let's see if we can find any errors about what's going on. If you open the terminal and cd into `/opt/wavebox/` are you able to run Wavebox using `./Wavebox`. Keep the terminal open and when it locks up see if there are any error messages or logs that have come out. These might give us a clue.

The other thing to try, is turning off a few of the advanced options. If you open Wavebox and go to Settings and then the Advanced tab. Try disabling `Ignore GPU Blacklist` and enabling `Disable hardware acceleration`. You might see a drop in performance whilst hw accel is disabled but if it stops it locking up, it might give us a clue to the root cause

**Comment by caldwed** [comment]
I've got this same issue on a Xubuntu 16.04 installation with the 3.3.3 beta. In my case, the terminal window gave no information the last time I tried it. Is there a way to add logging and parse a log file?

I'll try one of the flags you mentioned...

**Comment by Thomas101** [comment]
Anything that  goes wrong should make it out to the terminal. Just as an odd thought, disabling the spellchecker might be another thing to try

**Comment by tonybyng** [comment]
I removed the outlook.com account and it has started working on both machines. Both have stayed accessible. The desktop had everything removed except Google inbox and the laptop kept all the Google stuff . The only other thing that was removed on both machines was 2 web links. So I'll try adding things back in slowly and see which causes the issue but its looking like outlook.

**Comment by caldwed** [comment]
It locked up for me... with no output.

$ /opt/wavebox/Wavebox 
[WB_LAS] started 2398
[WB_LAS] no other processes found. Allowing run...

I have an O365, Gmail, Hotmail, Evernote (Web), and Google Tasks (Web) accounts... since outlook.com/hotmail.com may be an issue.

This was with:
- Ignore GPU Blacklist enabled (default)
- Disable hardware acceleration enabled (changed from default)

I did not change any spellchecker settings.

Should I try again with the Ignore GPU Blacklist disabled?

**Comment by tonybyng** [comment]
Since removing my outlook.com I hadn't had a lock up so I added it back in again and touch wood, so far I haven't had a lock up since. If this issue stays open for others, then I'll report back if I have any further issues but as I'm now not locking up, I can't do much in the way of further testing.

**Comment by Thomas101** [comment]
@caldwed you could try with Ignore GPU disabled, but I think you'll come out at the same conclusion.

@tonybyng nice find with the outlook account. Which accounts do you have left after removing the outlook one? (e.g. a single gmail, or two Google Inboxes, etc...).

I'll leave one of our test vms on here with a similar setup to see if we get the same

**Comment by tonybyng** [comment]
@Thomas101 My setup is Inbox for gmail (GoogleSuite), Google calendar, hangouts, contacts, keep, photos and drive, outlook.com (an old hotmail account) and  OneDrive.  My outlook account also does a retrieval of my personal email account

Since taking outlook out and adding back in again, Ive had no further problems.  Ive also updated to 3.3.4 beta yesterday and not had a problem this morning

**Comment by Thomas101** [comment]
Thanks @tonybyng I've been running a Linux mint machine with a gmail account and office 365 overnight - let it go to sleep etc and it's not locked up. It's really weird that this seems to be sporadic. Keep me up to date if you start seeing this again! I'll keep using the test box over the next few days to see if I can reproduce

**Comment by caldwed** [comment]
I had a unique lock-up yesterday. Normally the mail window gets "stuck" and then I can't kill the notification icon. I have to kill the processes to totally clean it up. Yesterday, the mail window was working fine, but when I went to shut down, the notification icon was not processing input. The menus seemed to work, but no actions would ever complete. The console still provides no output.

I have just upgraded to the 3.4.1 beta and I will run that now.

I will first make sure that it locks up with my current config... Then I will try removing/replacing my hotmail as @tonybyng suggested.

Has the saved data gone through any recent changes where I'd want to totally re-configure?

**Comment by Thomas101** [comment]
Out of curiosity does anyone have Google Calendar enabled? It looks like Wavebox can end up locking up when Google Calendar tries to bring up an event-alert. Does disabling Calendar or switching to non-interruptive notifications in the Google Calendar settings make any difference?

![screen shot 2017-10-16 at 16 27 50](https://user-images.githubusercontent.com/103586/31622822-5e1afd94-b295-11e7-87a2-03946b082cc7.png)

**Comment by tonybyng** [comment]
I do have google calendar active in Wavebox and Ive not noticed any lockups since my "fix". As and when there is an event I get a little alert box appear telling me of the event. I'm fairly sure the alert comes to the foreground too. 

Are you thinking that maybe the alert is firing but is being hidden somehow so you  then lose control of any input because there is a hidden alert preventing access to things ? If so, would that also prevent access to the menu ? When I had my issue, I could still access the menu although any menu item that was trying to update the main screen wouldn't function but if it was bringing up an alert - like the About box, that did work.

**Comment by Thomas101** [comment]
Thanks @tonybyng. The reason for the question, was someone reported that a Calendar alert came up whilst the laptop was asleep and started chewing cpu and battery until it was dismissed.

From the JavaScript spec, alert should halt execution until it's dismissed. Obviously this caused a few issues and was wondering if it was related. The 3.4.2 beta went out yesterday which has a patch for this. The alert comes up, but it doesn't lock everything up anymore

**Comment by Thomas101** [comment]
@tonybyng are you still seeing this problem? Am I okay to close this off?

**Comment by tonybyng** [comment]
Hi. I'm fine. Not happening to me anymore. I kept it open because of others having the problem but I'm good ta. So I'll close
