### ISSUE TITLE
Spellcheck?

### ISSUE THREAD

**Issue by robdam1001** [wavebox/waveboxapp#391]
I'm currently trialing Wavebox.  Is there spellcheck functionality?  If so, how is it toggled on ? 

* Which version of Wavebox are you using? [e.g. 3.3.0]

* Which Operating System are you using? [e.g. Windows 10,]

**Comment by nmat** [comment]
Hello @robdam1001 did you check in Preferences -> General -> Language?

**Comment by robdam1001** [comment]
@nmat yes, thanks.  I actually have Wavebox Supoport looking into my issue.  My issue only occurs in 1 of 4 Win 10 PC's that I have Wavebox installed on.  Thanks for your reply! 
![2017-09-21 16_32_52-wavebox _ rob robdamiani com _ inbox - rob robdamiani com - personal mail](https://user-images.githubusercontent.com/32176818/30717377-b57c4cc8-9eea-11e7-85b5-2e53dd6632a9.png)

**Comment by nmat** [comment]
ah cool

**Comment by Thomas101** [comment]
@robdam1001 if you right click on one of your accounts in the left side and pick inspect you'll get a new window show up. In here if you click on the Console tab at the top, do you have any red errors? 

You could also try the beta channel of Wavebox to see if it works on there. There's some more info [here](https://wavebox.io/kb/beta-channel)

**Comment by nmat** [comment]
@robdam1001 do you still experience problems with this after the 3.5.0 release?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
