### ISSUE TITLE
Feature Request: Highlight extension when active/not active

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#397]
* Which version of Wavebox are you using?
3.3.3 beta

* Which Operating System are you using?
windows 10

* Description:
Testing the markdown extension and noticed that its hard to see if the extension is active or not. Could be good to have some sort of indicator to if the extension is active or not when clicking it. For example like notificiation icon that would change it to green or something similar that just says its an active extension. (its at the moment grey if it is not working in certain areas but that only goes so far unfortunately)

**Comment by Thomas101** [comment]
Yeah I agree! The icon at the moment is whatever markdown sets at the moment. As chrome has a light toolbar the icon probably works best there, but not so much for us with the dark background. I'll see what chrome does when you apply a dark theme and go from there.

We've got some more work to do on the toolbar, this will probably ship in 3.3.5 as we're nearing the end of our 3.3.4 sprint.

**Comment by nmat** [comment]
Sounds good. Just noticed it and thought it would be a good idea to have a more visible active/not active icon or feature. :) thank you!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
