### ISSUE TITLE
Alternative Search Engines

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#398]
Add support for alternative search engines for `Search with Google` option in context menu. Suggestions...
* duckduckgo
* imdb
* stackoverflow

**Comment by pdp-7** [comment]
What's up with this?

I would like to change my default search engine at least... any way to do that?

**Comment by nmat** [comment]
I tested this on GIT master 2018-11-20 (gmail and slack)

The gmail account is set to be using default browser and not wavebox. After changing the value of which default engine to use the "Search XXXXX for "YYYYY"" did not open it in default browser but in wavebox browser.

The second choice did the same also. So the provider gets correct but it does not follow my setting to use default browser or wavebox browser

**Comment by nmat** [comment]
Hmmm it becomes a bit confusing for me if it does not respect the setting.

Of course this can be discussed. I am not sure what the best way would be. But when I clicked on Google for example I expected it to open in my default system browser and the other one to always open on Wavebox browser, unless I set something different in account/global setting.

**Comment by Thomas101** [comment]
I think there was a bug here which meant it always opened in the Wavebox browser. Could be confusing things. Give `5a681a5` a try to see if it's any clearer or if we still need to look at respecting the account setting/having an additional option that does that

**Comment by nmat** [comment]
awesome I will give it a try later on! thank you!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
