### ISSUE TITLE
Bug: Default mail client (Windows)

### ISSUE THREAD

**Issue by Dazzel** [wavebox/waveboxapp#4]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 64bit

Still not working on windows. Wmail issue: https://github.com/Thomas101/wmail/issues/520

**Comment by Thomas101** [comment]
Thanks @Dazzel, will dig into this and find out what it is

**Comment by Thomas101** [comment]
Just a quick update on this one. Been doing some digging, found an [msdn article here](https://msdn.microsoft.com/en-us/library/windows/desktop/cc144154%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) however it states they've changed the way it works in windows 10 with a link to another post that simply says "it's changing".

It looks like electron is doing similar to what [this post suggests](http://tweaks.com/windows/37085/changing-mailto-defaults/) and [this msdn article](https://msdn.microsoft.com/en-us/library/windows/desktop/dd203067(v=vs.85).aspx) which is applicable for windows xp and probably carries through to 7 and 8.

Oodles of Googling and trial & error turned up no results. I'll raise an issue on Electron to see if anyone over there can shed some more light on this

**Comment by Dazzel** [comment]
Since Windows 8 or 10 it is not possible to set an default program out of the program itself, AFAIK.

Other programs, like Google Chrome or such have to open the system settings panel where you have to set the standard program manually.

The main "problem" here is that Wavebox does not even show up as an program which can handle mails, as you can see here: 
![](https://cloud.githubusercontent.com/assets/24702285/21877734/18e5e456-d85b-11e6-8a77-1a79cd69b511.png)

Hope that helps you a little bit in getting closer to fixing the bug.

**Comment by Thomas101** [comment]
I've just pushed 3.1.2 which should hopefully fix this. Would be good to know if it works for you!

**Comment by Dazzel** [comment]
Seems to work now! 

One thing I had to to in Chrome was to remove the default handler for mailto links in here: chrome://settings/handlers 
But besides that, Wavebox gets properly reported as an mail handling program in Windows now.

**Comment by Thomas101** [comment]
Awesome! I think chrome can be setup to handle mailto links internally which could be what's happened there.

As regards the open tab if you try it in Edge do you see the same behaviour? If you try the [link on this page](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto) does that leave the lingering tab?

**Comment by Dazzel** [comment]
Ah. It does not leave the lingering tab open. Seems I've tested an faulty mailto link.

Working now 100%! 👍

**Comment by Thomas101** [comment]
No worries. Probably a new window that opens the mailto://.

**Comment by Cantello** [comment]
Did this address mailto-links or the default program in Windows? I cannot seem to set Wavebox as the default (Win7 Pro) as WB does not even show up on the list of acceptable programs. Any idea what could cause this?
(using Wavebox 4.0 on Win7 x64)
