### ISSUE TITLE
Unable to Open or Edit Google Drive files

### ISSUE THREAD

**Issue by Nicodemusthewise** [wavebox/waveboxapp#40]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.2
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Fedora 25

When a google sheet or google doc attempts to open the result is a blank Wavebox window.  Should this be opening a new browser tab or is the intent to edit without leaving Wavebox?  Either way neither is happening at the moment.

**Comment by jacksarick** [comment]
It should be opening in a new Wavebox window containing the document. Are you opening it from the Google Drive service, or links in emails?

**Comment by Nicodemusthewise** [comment]
I am opening from the drive tab within Wavebox. The new wavebox window opens, but is blank.

**Comment by jacksarick** [comment]
Odd. I'll try to replicate the issue when I have the time.

**Comment by Thomas101** [comment]
When you get the blank window is it completely blank or does it have a toolbar along the top with back/forwards etc?

If you do have the toolbar, click the button in top right to open in browser does the page open correctly?

**Comment by Nicodemusthewise** [comment]
I reinstalled from the website to try your suggestions and everything is golden now.  Thank you for your feedback and suggestions.

Have a great day!

-Your Fellow Man

**Comment by Nicodemusthewise** [comment]
I was wrong it only opens one google sheet workbook (one I downloaded for food macro calculations).  I am able to send this particular file to a new window and have it open in a firefox tab.  All other sheets I have personally created can not be previewed or sent to a firefox window to be edited.

**Comment by Thomas101** [comment]
Hi, I'm struggling to reproduce this on my end. Would you be able to right click on one of the files you're having trouble with and pick `View Details`. Then in the side-pane that opens pick the details tab and send me a screenshot of the bottom half... e.g.
![screen shot 2017-04-13 at 07 55 25](https://cloud.githubusercontent.com/assets/103586/24993557/cfce0116-201e-11e7-8ef3-0113d399070f.png)

**Comment by Nicodemusthewise** [comment]
Version 3_1_5 seems to have fixed the problem.  Version 3_1_4 was able to open excel sheets but not google sheets or google docs.

**Comment by Thomas101** [comment]
There wasn't any specific fix or change for this between 3.1.4 and 3.1.5 so I don't understand why this would have been fixed :-/
