### ISSUE TITLE
Black screen when closing from fullscreen

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#400]
* Which version of Wavebox are you using? [e.g. 3.3.3]

* Which Operating System are you using? [Mac OSX 10.12]

When the main window is fullscreen, hit the close button. This closes the window and leaves the monitor in a black undefined state.

If in fullscreen and hitting close, quit the app rather than hiding it.

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.3.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Rediwed** [comment]
> If in fullscreen and hitting close, quit the app rather than hiding it.

Please note this is unexpected behaviour in a macOS environment. I urge you to fix this. Issue has been persistent since older "Shift" fork.

**Comment by Thomas101** [comment]
@Rediwed this was fixed in version 3.4.0 and 3.4.1. Are you still seeing the behaviour with those versions?
