### ISSUE TITLE
[Bug]: External view does not load extension

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#401]
* Which version of Wavebox are you using?
3.3.3 beta

* Which Operating System are you using?
Windows 10

* Description:
If you Shift+Click a compose window to be a external window. The extension does not load. Not sure if this is fixed in next release but will report here anyway.

**Comment by Thomas101** [comment]
We haven't added support for displaying the extension in the toolbar as yet. What's the experience are you seeing? When I checked it appeared in the right-click context menu

**Comment by nmat** [comment]
@Thomas101 the toogle is there. However I can't _toogle_ it. What you can do to reproduce is to:

1. Create a new mail in gmail (and dettach it to its own window)
2. Create another new mail inside the main window

Now:
In the main window mail.....add something that would represent a markdown like: ---------
And then toogle markdown. This will change the dashed lines to: ________________________ (or similar)

Do the same in the external window and toogle markdown. You will see that the line does not change or be translated to and from markdown.

At least I get it like that here.

**Comment by Thomas101** [comment]
Awesome thanks for the detailed steps! I'm seeing the same here. Interestingly not on the build version only on the production version

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
verified that it loads on both Mac OS and Windows 10

Closing this issue

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
