### ISSUE TITLE
Spell checker for Wavebox Browser

### ISSUE THREAD

**Issue by troyglancy** [wavebox/waveboxapp#402]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.3.3 BETA

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Windows 10

I noticed on the built in browser for Wavebox that it does not have a spell checker. Is there a way to enable it? I have it enabled in the main Wavebox settings. It works within Gmail just not the internal browser.

**Comment by Thomas101** [comment]
I've added it in! Will be out in the next beta :)

**Comment by troyglancy** [comment]
Awesome! Thank you!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.3.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by troyglancy** [comment]
Works perfect! Thank you!
