### ISSUE TITLE
Unable to purchase pro

### ISSUE THREAD

**Issue by pauldburton** [wavebox/waveboxapp#405]
* Which version of Wavebox are you using? [e.g. 3.0.0] 3.3.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Ubuntu Gnome 16.04

Attempting to upgrade my account to the pro account and when i attempt to buy the pro version the popup closes without giving me the ability to complete the purchase.  
[https://www.dropbox.com/s/aandeizxn3q2k93/out.mp4?dl=0](Video Example)

Is this related to another issue I am having with links not opening in my browser?

**Comment by rhys101** [comment]
Yes, it could well be - if you've installed with snap then the `snapd-xdg-open` package is needed as well, since this manages the outbound url handling from within the snap sandbox.

If you install with:
```
sudo apt-get install snapd-xdg-open
```
it should then allow out-of-sandbox links to be opened.

**Comment by pauldburton** [comment]
that did it, now it opens a browser window with the purchase option.   I must have missed that step in the setup instructions from the ubuntu blog post.  Not sure if there is a way to let them know or not.  But it does now work.  Thank You!

Looking back it seems to be missing [https://insights.ubuntu.com/2017/09/12/wavebox-snap-a-central-hub-for-gmail-outlook-trello-slack-and-more/](ubuntu snap article)

**Comment by nmat** [comment]
hmmm this should maybe be placed in a howto or information somewhere?

**Comment by Thomas101** [comment]
We do have a message on our download page, when downloading snap packages but now that more users are coming through the snap store they're not seeing this. 3.3.4 beta has a dialog message for snap users to help them get setup. This will be heading out to the stable channel shortly
