### ISSUE TITLE
Spellchecker not respecting Settings

### ISSUE THREAD

**Issue by eatcodeplay** [wavebox/waveboxapp#406]
* Which version of Wavebox are you using? [e.g. 3.0.0]
**3.4.1beta**

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
**Windows 10 Pro**

Spellchecker is not respecting my settings anymore and is enabled eventhough i have it disabled in the "General" settings,

Unrelated to this new issue, i've also have seen that secondary windows that open from a main account
will always have spellchecker enabled, thereby also not respecting my settings.

**Comment by Thomas101** [comment]
Thanks for reporting! I've patched this and it will be released in the next beta

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by eatcodeplay** [comment]
Looking good. Spellchecking seems to behave as expected in primary windows and secondary windows. Thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
