### ISSUE TITLE
Boomrang extension doesn't appear in my Inbox/Gmail accounts

### ISSUE THREAD

**Issue by renaudManda** [wavebox/waveboxapp#407]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.1 beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS X 10

I installed the extension and activate the extension experimental support as describe on the blog post. I see the Boomrang icon in the Wavebox toolbar but not in the Gmail UI or Inbox UI.

**Comment by Cris70** [comment]
Same here. I have added a few comments in bug #138 too.

**Comment by Thomas101** [comment]
Thanks for reporting. We're not expecting it to appear in Google Inbox as Boomerang only supports Gmail. There might be some more debugging information that we can grab that might help.

On the Gmail account where it's not appearing, can you right click on the account in the left and go to `Inspect`. A new window will appear, click the console tab. Can you send a screenshot of that? It should look something like this, or may have a bunch of red errors there...
![screen shot 2017-10-05 at 09 35 45](https://user-images.githubusercontent.com/103586/31217976-b002ee7a-a9b0-11e7-9041-3178ae864f5d.png)
Feel free to close this afterwards.

Then can you open Settings and click the extensions tab. If you scroll down to Boomerang, there's a button called `Inspect background page`. Click on this and you should get a similar window to the one you had before. Again click on the console tab and take a screenshot...
![screen shot 2017-10-05 at 09 35 56](https://user-images.githubusercontent.com/103586/31218013-e5f10d8c-a9b0-11e7-9005-6afcd81938cb.png)
Once done, you can close this window too.

Hopefully there will be some more clues as to what's gone wrong there. Thanks!

**Comment by Cris70** [comment]
Here are my screenshots:
![screenshot_20171005_185144](https://user-images.githubusercontent.com/5107224/31239805-a0ab1c6a-a9fe-11e7-8f4a-8b8386a6ff70.png)
![screenshot_20171005_185252](https://user-images.githubusercontent.com/5107224/31239809-a4caf78e-a9fe-11e7-8053-a6dcfa7e9e9b.png)

**Comment by Thomas101** [comment]
Thanks for the screenshots, I think I've got an idea about what underlying issue is. Do you know if have any of the gmail labs enabled?

**Comment by Cris70** [comment]
@Thomas101 in the account where Boomerang does not work I have a few enabled labs:
- auto-advance
- pictures in chat
- preview pane
- unread message icon

But I have a few labs enabled also on the other account, where Boomerang works:
- chat on the right
- unread message icon
- pictures in chat
- canned replies

**Comment by Thomas101** [comment]
thanks for the lists @Cris70. Is one of your accounts a company account (e.g. one email address is @yourcompany.com and the other @gmail.com)?

**Comment by renaudManda** [comment]
@Thomas101 in my case my answer to your last question to @Cris70 is yes.

I've one corporate account (Gsuite) and 2 Gmail accounts

if it could help

**Comment by Cris70** [comment]
@Thomas101 yes I have two accounts: one company account (the working one) and one gmail account (boomerang not working here)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.2. To try it out, you will need to remove boomerang and add it again this time.

If you want to give the beta channel a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Seems to work for me now. One thing I noticed is that I had to uninstall/disable the extension and add it again for it to work. Only tested on Windows 10 though but there it does now load.

**Comment by Cris70** [comment]
Works perfectly now (after upgrading to v3.4.2 and removing/readding Boomerang). Thank you!!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
