### ISSUE TITLE
Menubar Icon becomes invisible after switching menubar theme on OSX

### ISSUE THREAD

**Issue by jottr** [wavebox/waveboxapp#408]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.3.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G29
```

When switching between dark and and light menubar theme on OSX, the wavebox icon does not transition properly, rendering it invisible. 
Steps to reproduce:

- Start with light theme
- Open wavebox -> Menubar icon is visible
- [Switch menubar theme to dark](https://support.apple.com/kb/PH25158?locale=en_US&viewlocale=en_US) -> Wavebox item becomes invisible

This happens also when switching from dark to light theme.

**Comment by Thomas101** [comment]
Hi, Wavebox only picks out the theme on launch at the moment. Restarting Wavebox after changing the theme may update the colours automatically, however if you've customized any menu bar settings these wont be overwritten and the colours wont change.

If you want to customize the menu bar icon, open the Wavebox Settings and there's a `Menu Bar` section which will allow you to customize colours and behaviour. If you're switching theme often, it may be best to set the background colour on the icon so it always remains visible

![screen shot 2017-10-05 at 09 41 43](https://user-images.githubusercontent.com/103586/31218313-e0d2ca74-a9b1-11e7-9b8a-06e2ae09fe79.png)

**Comment by jottr** [comment]
That actually fixed it. Setting the background to white, and the opacity level to something like `0.6` works nicely.
I'd like to suggest to make this the actual standard setting.
