### ISSUE TITLE
Compose New Message modal

### ISSUE THREAD

**Issue by joeoftheforsythe** [wavebox/waveboxapp#409]
* Which version of Wavebox are you using? [e.g. 3.0.0]
  * 3.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
  * Mac OSX 10.12.6

I have multiple email accounts setup. When I push CMD+N to compose a new email it'd awesome if I could select the account using the keyboard instead of selecting with the mouse.

**Comment by Thomas101** [comment]
Fair point! I'll see if I can add arrow commands in

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by joeoftheforsythe** [comment]
Man that's fantastic. Thanks!
