### ISSUE TITLE
Trello Message Indicator stuck.

### ISSUE THREAD

**Issue by raguay** [wavebox/waveboxapp#41]
* Which version of Wavebox are you using? [e.g. 3.0.0] 

3.1.2

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS 10.12.5 Beta (16F43c)

The number of trello messages was 23 this morning when I turned on my system. I've gone through all of them and they no longer appear in Trello, but the bubble on the left on the Trello circle and the total in the Dock still lists the 23 notifications. Closing and reloading the program did not change anything.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. If you reload Wavebox, then go to View > Developer tools. Then in the window that pops up, click on the console tab do you see any errors or warnings coming out?

**Comment by raguay** [comment]
The console shows:

mailboxes.html?clientId=e5f6503d-6539-45f0-b021-5d97561b5097&clientToken=c456d7e……:164
Bootstrap complete 5085
https://www.google-analytics.com/collect?v=1&tid=UA-91763551-2&cid=c2e46f06….0.2924.87%20Electron%2F1.6.5%20Safari%2F537.36&av=darwin-3.1.2&cd2=opened
Failed to load resource: net::ERR_CONNECTION_REFUSED
https://www.google-analytics.com/collect?v=1&tid=UA-91763551-2&cid=c2e46f06….2924.87%20Electron%2F1.6.5%20Safari%2F537.36&av=darwin-3.1.2&cd2=navigate
Failed to load resource: net::ERR_CONNECTION_REFUSED
/Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxes/…39-45f0-b021-5d97561b5097&clientToken=c456d7e6d68a49d39f7e2efc5c1af1fd#/:1
Uncaught (in promise) TypeError: Failed to fetch
/Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxes/…39-45f0-b021-5d97561b5097&clientToken=c456d7e6d68a49d39f7e2efc5c1af1fd#/:1
Uncaught (in promise) TypeError: Failed to fetch
mailboxes.js:56 [Squirrel] checking for updates
mailboxes.js:30 [SYNCS][WebSocket] Socket opened
mailboxes.js:56 [Squirrel] no updates available

**Comment by raguay** [comment]
The console shows:

mailboxes.html?clientId=e5f6503d-6539-45f0-b021-5d97561b5097&clientToken=c456d7e……:164 Bootstrap complete 5085
https://www.google-analytics.com/collect?v=1&tid=UA-91763551-2&cid=c2e46f06….0.2924.87%20Electron%2F1.6.5%20Safari%2F537.36&av=darwin-3.1.2&cd2=opened Failed to load resource: net::ERR_CONNECTION_REFUSED
https://www.google-analytics.com/collect?v=1&tid=UA-91763551-2&cid=c2e46f06….2924.87%20Electron%2F1.6.5%20Safari%2F537.36&av=darwin-3.1.2&cd2=navigate Failed to load resource: net::ERR_CONNECTION_REFUSED
/Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxes/…39-45f0-b021-5d97561b5097&clientToken=c456d7e6d68a49d39f7e2efc5c1af1fd#/:1 Uncaught (in promise) TypeError: Failed to fetch
/Applications/Wavebox.app/Contents/Resources/app.asar/bin/scenes/mailboxes/…39-45f0-b021-5d97561b5097&clientToken=c456d7e6d68a49d39f7e2efc5c1af1fd#/:1 Uncaught (in promise) TypeError: Failed to fetch
mailboxes.js:56 [Squirrel] checking for updates
mailboxes.js:30 [SYNCS][WebSocket] Socket opened
mailboxes.js:56 [Squirrel] no updates available

**Comment by Thomas101** [comment]
I think I know what this is. A fix will be out in the next release. Thanks!

**Comment by Thomas101** [comment]
Hi a fix for this has just been release in 3.1.3. Wavebox will autoupdate shortly or if you want to get it sooner you can either re-launch Wavebox to trigger an autoupdate or redownload from https://wavebox.io/download

Once you've got the latest version can you check if you're stilling this bug? Thanks!
