### ISSUE TITLE
OSX cant open links in browser

### ISSUE THREAD

**Issue by roccolord** [wavebox/waveboxapp#410]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
osx

Clicking on a link in an email launches the browser (Chrome) but without an url. "Open link with wavebox" works.

**Comment by Thomas101** [comment]
Hi, a few users reported this after upgrading to High Sierra, but found that updating chrome fixed the issue. Which version of of macOS and Chrome are you using?

**Comment by roccolord** [comment]
I have High Sierra and Chrome latest, not beta or canary.

**Comment by roccolord** [comment]
Sorry I have 62 Beta....

**Comment by Thomas101** [comment]
Thanks, can you give the following a try...
1. Open macOS System Preferences and go to the General Tab
2. Change your Default web browser to Safari
3. Try opening a link from Wavebox (this should open correctly)
4. Change your Default web browser back to Chrome
5. Restart your machine
6. Try opening a link from Wavebox again
Does it work correctly after that, or are you still seeing the same problem?

**Comment by roccolord** [comment]
The links that where borked looks to be working now, I think since I upgraded to the last Apple High Sierra panic fix.

**Comment by Thomas101** [comment]
Thanks for the update. A few users have reported a similar behaviour and updating either chrome or macOS seems to resolve the issue!

**Comment by steve-ross** [comment]
Having this issue with the latest update 👎

**Comment by Thomas101** [comment]
@steve-ross have you [tried this](https://wavebox.io/kb/high-sierra-chrome-links)

**Comment by steve-ross** [comment]
Ah yeah, this fixed it. Sorry for the late reply
