### ISSUE TITLE
Wavebox can't connect to internet 

### ISSUE THREAD

**Issue by zanewolf** [wavebox/waveboxapp#411]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

For the past several days, wavebox has been unable to open, despite the internet working perfectly. I've tried uninstalling and reinstalling, I updated the version from 3.1.something to 3.4, and of course I tried the ol' turning the computer off and on again. I have no idea what is going on or how to fix it. 

![wavebox_troubleshoot](https://user-images.githubusercontent.com/30910417/31242031-bb3e0f5e-a9d3-11e7-8805-e66c33022d4f.PNG)

Any ideas would help. 
Cheers, 
Z

**Comment by Thomas101** [comment]
Hi, we've seen this a few times with antivirus/firewalls blocking the connection. For the other bug reports, Kaspersky has been particularly bad with this. Do you know which antivirus and firewall you're running? Would you be able to check that Wavebox has been whitelisted?

**Comment by nmat** [comment]
I have not been able to reproduce this unless there is something blocking the connection like a firewall or application rules in for example avast.

Its hard to reproduce unless there is a valid and new testing for it.

**Comment by zanewolf** [comment]
Hi! 

I solved it through my antivirus, ESET. Thank you for pointing me in that direction! 

Cheers, 
Z

**Comment by nmat** [comment]
@zanewolf good to hear that you managed to solve it. Was it blocked or something in ESET?

**Comment by zanewolf** [comment]
Yep. Once I figured out how to add sites manually to ESET's 'green list', wavebox began working again.

**Comment by Thomas101** [comment]
I think 3.5.0 has some info in the connection screen about checking the AV & firewall as well as the test connection button which is a bit more obvious.

Glad to hear you got it working :)
