### ISSUE TITLE
Wavebox unresponsive in dock after Sleep

### ISSUE THREAD

**Issue by rckstflbn** [wavebox/waveboxapp#412]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Wavebox 3.4.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

When my laptop wakes from sleep, if Wavebox was idling in background it never becomes available.   Just a  black window down in the dock.   Have to go to Taskmanager and kill processes then relaunch Wavebox, which runs great until I close lid on laptop again.    Only account in it is one Gmail account.

Been moving toward upgrading beyond free version, but can't until this problem is sorted out.

**Comment by nmat** [comment]
I am on a windows 10 machine and do not have that kind of problem. 

Even had the whole machine in a sleep mode during night and still response. Did this happen after a upgrade from 3.3 -> 3.4 or similar?

**Comment by Thomas101** [comment]
@rckstflbn thanks for reporting. Would be great to know a little bit more...

1. Can you elaborate on what you mean by idling in the background? Just as an unfocused window?
2. Can you send a screenshot of when it goes into a black window?
3. When it does stop responding, does right clicking on the icon in the bottom-right tray have any effect or does it also remain unresponsive?

Thanks!

**Comment by rckstflbn** [comment]
Hi Thomas,

Problem i still happening.   If wavebox is running and I allow laptop to go
to sleep, when I wakeup the Win10 laptop I get the attached screenshot in
dock.    App is there and running, but unresponsive.   Cannot click on it,
 cannot switch to it, cannot Close Window via dock.   Have to go to Task
Manager and kill Wavebox processes.

Been happening since at least the most recent update if not sooner.

[image: Inline image 1]

Rick Stufflebean
email: rckstflbn@gmail.com
615.967.9972
photography: http://501concepts.com   design: http://artdroid.com

**Comment by nmat** [comment]
@rckstflbn are you running any type of antivirus or something similar?

As mentioned before I have 2 machines where 1 is a laptop and running both wavebox on windows 10 and do not have this problem. Does the task manager tell you that wavebox is unresponsive also?

(also....in the ticket it does not seem the image is seen....might have to do with you answering directly in gmail, not sure)

**Comment by rckstflbn** [comment]
Avira free is running,  as well as Malwarebytes.

Re-attaching screenshot.

Rick Stufflebean
email: rckstflbn@gmail.com
615.967.9972
photography: http://501concepts.com   design: http://artdroid.com

**Comment by nmat** [comment]
if possible could you try to turn them off and see if that makes any difference. I mean using no protection at all more then the built in defender and protection from windows 10?

I had problems with avast that the application never started and was not recognized so had to do some fiddling with the antivirus to add it to some sort of ok state.

**Comment by Thomas101** [comment]
Looking at some other issues, this could be related to the alerts that Google Calendar shows, but we're not 100% sure on this. If you've got Google Calendar setup as a service, could you try setting it use browser notifications rather than interruptive alerts? You can do this by opening up your Google Calendar Settings (cog in the top-right) and the enabling the following...

![screen shot 2017-10-16 at 16 27 50](https://user-images.githubusercontent.com/103586/31654009-883970b0-b31c-11e7-80bc-b0e8e393f403.png)

**Comment by nmat** [comment]
hmmmm I still can't reproduce this. :(

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
