### ISSUE TITLE
Unable to right click and reload app icons for weblinks in the sidebar

### ISSUE THREAD

**Issue by jon-heer** [wavebox/waveboxapp#413]
Version 3.4.1
OSX 10.12.5

Like the title says, I'm unable to trigger a reload for a weblink's app icon in the sidebar. I have news.google.com as a weblink, and occasionally it displays like a blank page (which might just be a site issue). Prior to the last update, I was able to reload the page to fix the blank page issue, but now nothing happens when I select reload. The same is true for my facebook weblink. Non-weblink apps reload properly.

**Comment by Thomas101** [comment]
Thanks for reporting. I think I've already patched this in master so will be heading out in the next beta release.

If you've got the toolbar enabled, the reload button there should still be working and also the reload option when right clicking in the page should also still work

**Comment by jon-heer** [comment]
Great, I'll keep an eye out for it! Good idea with the toolbar (haven't had it open); I've just been restarting the application to get around the issue.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by jon-heer** [comment]
Hi Thomas, I have updated to the latest 3.4.2 beta release, and I have verified that the refresh is working properly in the weblink's app icon action menu. I appreciate the quick turnaround - thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
