### ISSUE TITLE
Standard left click on tray icon should be minimize and not close

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#414]
* Which version of Wavebox are you using?
3.4.1beta

* Which Operating System are you using? 
Windows 10

* Desciption:
If setting "Hide main window to tray on closed" is not set, then the application will close on a single left click on the tray icon.

This default behaviour IMO should be a minimize setting by default rather then close. A single click is more of a minimize then a close method especially if the click with mouse is a left click.

Otherwise you might think the application crashes when instead it should minimize to task/tray....

**Comment by nmat** [comment]
Or use a standard focus method as in:

tray.on('click', () => {
  win.isVisible() ? win.hide() : win.show()
})

but not close the app if the setting is not selected

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
seems to work with the settings choosen. perfect!
