### ISSUE TITLE
Drag'n'Drop Account Ordering

### ISSUE THREAD

**Issue by mindfullsilence** [wavebox/waveboxapp#415]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.12.6

Feature request: Allow account icons to be drag/dropped for reordering.

**Comment by Thomas101** [comment]
This can be done with a right-click at the moment, but we should definitely be supporting drag & drop!

![screen shot 2017-10-11 at 08 47 41](https://user-images.githubusercontent.com/103586/31427922-dde0356e-ae60-11e7-8691-b8ebfa30ae84.png)

**Comment by nmat** [comment]
Windows 10: works on services to drag and reorder.

Tested in GIT

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
tested on windows 10 to move things around and seems to work just fine. even with the indexed services.

**Comment by mindfullsilence** [comment]
Works like a charm! I'll keep fiddling with it and see if I can break it, but it works great so far.

**Comment by nmat** [comment]
been testing it on windows 10 and macOS 10.13.2 and had no problems there either

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by mindfullsilence** [comment]
Noticed something odd in the most recent release. Dragging up on a sidebar icon works great. Dragging down causes a reload of the app being dragged. Any ideas?

**Comment by nmat** [comment]
Tested this on windows 10 also and noticed the same behaviour. Odd really. :/

**Comment by Thomas101** [comment]
@mindfullsilence  @nmat  hived into #548
