### ISSUE TITLE
Support for Gnome

### ISSUE THREAD

**Issue by amig** [wavebox/waveboxapp#416]
* Which version of Wavebox are you using? 3.4.0

* Which Operating System are you using? Ubuntu 16.04.3 LTS / GNOME Shell 3.18.5

Would like to see full integration of menu and a native extension.

Thanks.

**Comment by Thomas101** [comment]
Yep! 3.26 changes support for the status icon too so we should be looking at that

[Status Icon Migration](https://wiki.gnome.org/Initiatives/StatusIconMigration)
https://github.com/electron/electron/issues/10427

**Comment by Thomas101** [comment]
The latest beta (3.5.2) has some improved support for Gnome. I've tested these on 17.10 with the latest version of Gnome, would be great to hear how they work on 16.04 too!

**Comment by amig** [comment]
I've installed the beta (3.5.2) on my Ubuntu 16.04 with GNOME shell. It looks ok but I cannot see any differences. What should I look for?

**Comment by amig** [comment]
I noticed that the alert pop-up of the Google calendar changed and it is missing the OK button and text is selected (see image).

I hope this is due to work on having Google calendar use standard OS notifications instead on the current behavior.

![screenshot from 2017-11-22 09-16-35](https://user-images.githubusercontent.com/203434/33114763-fa66958a-cf66-11e7-9d30-ed37f5a6a74b.png)

**Comment by Thomas101** [comment]
Oooh yeah I've come up against that now. I'll make sure the okay option gets added in the next release.

It looks like the upstream fixes for Gnome (the ones that re-add the tray icon etc) are only compatible with 17.10+. I'll look into what we can do for Gnome on Ubuntu 16.*

**Comment by amig** [comment]
Waiting for it

**Comment by nmat** [comment]
Anyone that has tested this in latest beta? And in that case on what OS+Version?

I can test it but need a bit more feedback on what package etc is being used.

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
