### ISSUE TITLE
Option to override all built-in window openers

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#417]
Add an option to override things like Google Drive window openers etc so you can make them always open in the browser

**Comment by drewplaysdrums** [comment]
+1 for this option.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.2. Under your account settings you can find the `Open Google Drive links with Browser` option. Enable this and they'll open up in your default browser.

![screen shot 2017-10-18 at 12 06 19](https://user-images.githubusercontent.com/103586/31715727-d6e9aea6-b3fc-11e7-8e1c-39f5dde1530b.png)


If you want to give the beta channel a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
tested this quickly on windows 10 fall creators edition and seems to work fine.

Also works on macOS High Sierra 10.13

**Comment by prydonius** [comment]
+1 works like a charm for me on macOS El Capitan, thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by kodeebo** [comment]
This still does not work for me, after enabling it in settings and restarting Wavebox. All Google drive documents are still opened in a new Wavebox window. Anything else I need to do?

**Comment by Thomas101** [comment]
@kodeebo there's an open issue for Google Drive docs due to go in the next beta #579
