### ISSUE TITLE
dosent show gmail notifications on ubuntu

### ISSUE THREAD

**Issue by ahmadabd** [wavebox/waveboxapp#42]
* Which version of Wavebox are you using? [e.g. 3.0.0]

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

**Comment by ahmadabd** [comment]
I use 3.1.2 version of wave on ubuntu but it dosent show new email notifications .

**Comment by Thomas101** [comment]
@ahmadabd did you mean to close this off, or are you still having trouble?

**Comment by ahmadabd** [comment]
no i have trouble yet,when i have new email ,waves icon dosent show for example number "1" for new email.

**Comment by Thomas101** [comment]
Would you be able to try the steps in [this KB article](https://github.com/wavebox/waveboxapp/wiki/KB:-Google-Unread-Counts)?

**Comment by ahmadabd** [comment]
yes ,it worked
thank you :)
