### ISSUE TITLE
Bug: Asana tasks cannot be dragged and dropped

### ISSUE THREAD

**Issue by saman325** [wavebox/waveboxapp#421]
Wavebox version: Version 3.4.0
OS: Max OSX: 10.12.3

I'm having an issue with Asana in Wavebox.

Steps to reproduce:
Use Asana in Wavebox. 
Try to drag a task from one spot to another.

Current behavior:
https://cl.ly/1J0Y3l1R1W3a

Expected behavior (in my browser):
https://cl.ly/0933352N3Y1O

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I've just given this a try myself and I'm seeing the behaviour that you see in the browser. If you right click on the account in the left and hit reload does this make any difference? It could just be a broken release from Asana that Wavebox loaded in

**Comment by saman325** [comment]
@Thomas101 I don't see a difference after refreshing. Any other ideas?

**Comment by Thomas101** [comment]
I wonder if a different account is interfering with the click handler for some reason. What's the layout of accounts that you've got at the moment? e.g.

1. Asana
2. Gmail
  2.1 Google Calendar
  2.2 Google Drive
3. Outlook
  3.1 Calendar
...etc

**Comment by andrew-nguyen** [comment]
I have the same issue and I have quite a few accounts:

- tacoapp (weblink)
- Slack
- Asana (weblink)
- Jira (weblink)
- Slack

**Comment by Thomas101** [comment]
Thanks @andrew-nguyen I've tried with that same setup and still not seeing it my end. Which OS are you using? Does it happen as soon as it loads up or is it after a bit of use it breaks?

**Comment by andrew-nguyen** [comment]
@Thomas101 It's never worked - as soon as it load, dragging doesn't work as expected. I'm on a Mac, 10.12.6

**Comment by Thomas101** [comment]
Could you try adding `https://www.w3schools.com/html/html5_draganddrop.asp` as a weblink account type? At the top there's two boxes, one with an image. Can you try dragging the image from one to the other to see if that works?

![untitled](https://user-images.githubusercontent.com/103586/33070135-e16c0faa-ceae-11e7-8e73-d121ff7a4dec.png)

**Comment by andrew-nguyen** [comment]
@Thomas101 Don't know if it's related but it immediately hung after I tried adding the above weblink.  Also, force-quitting and then reopening wavebox results in the following:
![image](https://user-images.githubusercontent.com/901859/33087625-fe19a95a-ce9f-11e7-86ea-86d377372d03.png)

Is there a way to remove an account from outside the app?

**Comment by Thomas101** [comment]
Oh wow, that shouldn't have happend! Which version of Wavebox are you using?

**Comment by Thomas101** [comment]
Are you still seeing this issue with the latest versions of Wavebox?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
