### ISSUE TITLE
New Google Calendar look

### ISSUE THREAD

**Issue by cansi22** [wavebox/waveboxapp#422]
* Which version of Wavebox are you using? 3.4.0
* Which Operating System are you using? Win10 

Adapt the google calendar section to the new look
Put a button to activate the new look with the following link:
https://calendar.google.com/calendar/render?new_calendar_optin=true

Source: https://techcrunch.com/2017/10/17/google-calendar-on-the-web-gets-a-fresh-new-look/

**Comment by Thomas101** [comment]
Thanks for pointing this out! If you want to try it now, navigating to the link in your web-browser will show the button. Once it's been enabled, it's enabled anywhere you login. So if you reload Google Calendar in Wavebox (right click on the icon and reload) it will also appear :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Works here on Windows 10 and Mac OS

**Comment by TheWithz** [comment]
Confirmed to work on Linux Solus OS

**Comment by nmat** [comment]
Tested on ubuntu 17.10 and works just fine also

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
