### ISSUE TITLE
Not receiving notifications for unread messages on Google Inbox

### ISSUE THREAD

**Issue by azamouchi** [wavebox/waveboxapp#423]
* Which version of Wavebox are you using? [3.4.0]

* Which Operating System are you using? [Mac OSX 10.12.6]

Hi,

I don't receive any notifications for my unread emails on Google Inbox, and no unread count is shown over the app icon in the dock, neither on the app extension in the status bar.
My account configuration is set to **Unread Messages** as explained here : https://wavebox.io/kb/google-unread-counts .
When i try to test a notification from the app, it appears and the sound is played, i've also checked my system prefrences to make sure that Wavebox is authorized to display notifications.

What could be the problem ? 

Thank's for your help.

**Comment by Thomas101** [comment]
Hi, thanks for reporting and for the detailed info. There could be some more info in the log. Are you able to open the developer tools by going to View > Developer > Wavebox Developer Tools. In the window that appears can you click on the console tab and send a screenshot?

**Comment by azamouchi** [comment]
Yep sure ! there you go  [-1508402926908.log](https://github.com/wavebox/waveboxapp/files/1397676/-1508402926908.log)
Thank's for your support.

**Comment by Thomas101** [comment]
Wow, lots of 404's there for some reason. Are you behind a corporate proxy or public wifi etc? I'm wondering if the router is returning a 404 page for some reason?

It might sound daft, but does re-adding an account or restarting Wavebox any difference?

**Comment by azamouchi** [comment]
Disconnecting my account, restarted Wavebox and added the account back fixed the problem ! . Thank's for your support.

**Comment by Thomas101** [comment]
No problem, let me know if this comes back up :)
