### ISSUE TITLE
Paste without formatting Mac OSX

### ISSUE THREAD

**Issue by naderby** [wavebox/waveboxapp#424]
* Which version of Wavebox are you using?3.4.0

* Which Operating System are you using? Mac OSX 10

Really do need to have paste without formatting. Very important. I can't get it to work.

Shift + Option + Command and hit V.

**Comment by Thomas101** [comment]
Hi, wavebox uses <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> to do paste without formatting. If you want to use <kbd>Option</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> then you can change the shortcut in settings under advanced. Changing *Paste and Match Style* to `Option+Shift+V` will set this.

There are some further instructions on to change shortcuts [here](https://blog.wavebox.io/be-a-keyboard-shortcut-master/).

**Comment by nmat** [comment]
@naderby where you able to test what @Thomas101 mentioned?

**Comment by naderby** [comment]
Yes it works.

**Comment by nmat** [comment]
Can this ticket be closed? Was this the effect you where looking for? Or do you feel something is missing?
