### ISSUE TITLE
Unable to share location with Weblink

### ISSUE THREAD

**Issue by micahparker** [wavebox/waveboxapp#426]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows

Im trying to add T-Mobile DIGITS as a Weblink and part of registering a Line is sharing your location (presumably for 911 support). Because im not prompted to allow location sharing i cannot register a line making DIGITS on Wavebox unusable.

**Comment by Thomas101** [comment]
It looks like we need to set the api key to allow Wavebox to resolve the current location. I'll get this added in to the next beta

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by micahparker** [comment]
I just switched to beta this morning to see if it was there =) Ill update now and check it out, thank you!

**Comment by micahparker** [comment]
Works like a charm, this is great!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
