### ISSUE TITLE
How to set Wavebox as default mailto link handler on OS X?

### ISSUE THREAD

**Issue by itamaro** [wavebox/waveboxapp#429]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Mac OS X 10.11.6

I'd like to have Wavebox handle all mailto links (if possible, letting me choose which account in Wavebox should be used, but also OK if it uses the active account).

Is it possible to configure it? Maybe just for links in Chrome?

Currently when I click mailto links in Chrome, it tries launching WMail (which I used before Wavebox), and fails. Not sure how to change that...

**Comment by Thomas101** [comment]
If you open settings and turn on or try turning off and on `Handle mailto links` does that work?
![screen shot 2017-10-19 at 09 00 33](https://user-images.githubusercontent.com/103586/31760261-038e3a08-b4ac-11e7-9b54-432294e22920.png)

**Comment by itamaro** [comment]
> If you open settings and turn on or try turning off and on Handle mailto links does that work?

no. weirder still, if I turn it on, and try opening a mailto link, WMail opens and closes, and this setting in Wavebox is suddenly turned off...

**Comment by itamaro** [comment]
OK, that little experience helped me figure it out! :-)

I went into WMail settings, turned off the `Handle mailto link` setting there, turned on the setting in Wavebox, and now it works!

**Comment by Thomas101** [comment]
Glad you got it working! My next suggestion was to try a restart. We have once machine in the office that keeps forgetting its setting for some reason :-/

**Comment by itamaro** [comment]
oy, I was early to rejoice. it seems that my machine also keeps "forgetting the setting" - now it tries using Outlook for mailto links...

**Comment by Thomas101** [comment]
Hmmm, okay. I wonder if something is trying to overwrite the setting. What happens if you give this a try?

1. Restart your machine
2. Launch Wavebox
3. Set Wavebox as the default client
4. Restart your machine again
5. Launch Wavebox
6. Is the setting still enabled or has it been changed again?

**Comment by itamaro** [comment]
so far, after going through this procedure, the setting is still enabled. I'll try to catch it if it changes again, maybe by an overzealous app.

**Comment by nmat** [comment]
@itamaro if possible can you test this in 3.5.0 stable that came out today?

**Comment by itamaro** [comment]
> @itamaro if possible can you test this in 3.5.0 stable that came out today?

sure. upgraded and the setting is still enabled (since the last procedure you suggested). did another restart, and it's still ok.

**Comment by Thomas101** [comment]
Awesome, I'll close this off for now and fingers crossed it should stick :). If it doesn't re-open the issue and we can dig a bit deeper

**Comment by itamaro** [comment]
Great, thanks for everything! :-)
