### ISSUE TITLE
Disable window dragging for sidebar buttons

### ISSUE THREAD

**Issue by jamiestraw** [wavebox/waveboxapp#43]
* Wavebox `v3.1.2`
* macOS `v10.12.4`

I often accidentally move the window when clicking the sidebar buttons to change mailboxes/apps.

Making the buttons so that they do not move the window should be fairly simple by adding the: `-webkit-app-region: no-drag;` style to the buttons.

I will open a PR soon if I get the chance.

**Comment by Thomas101** [comment]
Thanks! I'll take a look as well. I do seem to remember looking into this before, but I don't think the property was respected on children. Once you've set that the area as drag it seems to be it for all child elements as well

**Comment by Thomas101** [comment]
Looks like there must a fix upstream, disabling works now :)

**Comment by jamiestraw** [comment]
Perfect! :)

**Comment by Thomas101** [comment]
3.1.4 has just been released with this fix. Thanks!

Wavebox should update automatically after a while, but if you want to hurry it up, just restart the app and it will re-check
