### ISSUE TITLE
High CPU usage with weblink accounts

### ISSUE THREAD

**Issue by nlenkowski** [wavebox/waveboxapp#430]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS 10.13 High Sierra

When I enable weblink accounts for WhatsApp (https://web.whatsapp.com) and/or Facebook Messenger (https://www.messenger.com) I'm seeing high CPU usage from the Wavebox Helper processes. I have badges and notifications enabled for both.

![wavebox-cpu-with-weblinks](https://user-images.githubusercontent.com/1290235/31770099-a748d106-b4d6-11e7-817e-4b014945609e.png)

When I remove the weblink accounts (Inbox and Hangouts accounts enabled only) CPU usage returns to normal.

![wavebox-cpu-normal](https://user-images.githubusercontent.com/1290235/31770098-a70fde96-b4d6-11e7-9d46-b1e3a39e908c.png)

**Comment by Thomas101** [comment]
Wow, that definitely looks high. If you open your Wavebox settings and then click on task monitor can you send a screenshot of that? It will give a little bit more info about what each helper is actually servicing

**Comment by nlenkowski** [comment]
Well, after a reboot and letting Wavebox run for 3-4 hours this morning it looks like the issue resolved itself.  Here's a screenshot of the task monitor showing all is well. Sorry for the false alarm!

![wavebox-task-monitor](https://user-images.githubusercontent.com/1290235/31819253-2c138d3e-b59c-11e7-8220-c259a6e0839c.png)

**Comment by Thomas101** [comment]
Sounds like it could be a code issue with Messenger itself, maybe with a memory leak or something else. Keep an eye on it, if it it does start eating cpu or ram again then drop another screenshot up, it might give us a better idea! I'll close this off for now but if you see it again re-comment and I'll take another look

**Comment by nlenkowski** [comment]
Sounds good, will do.
