### ISSUE TITLE
Ability to add Services to existing Accounts / Weblinks

### ISSUE THREAD

**Issue by micahparker** [wavebox/waveboxapp#431]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I would love the ability to add my own Weblinks as Services of an existing account (e.g. add Trello board as a Service to my Office 365 Account). It would help me keep related services for personal and work Accounts all nice and tidy.

**Comment by Thomas101** [comment]
We definitely have some more work to do on grouping and management. This being one of the things we're looking at :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account by right-clicking on one of the tabs and picking `Add another service`

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
