### ISSUE TITLE
Problem typing '@' in Wavebox

### ISSUE THREAD

**Issue by KPreal** [wavebox/waveboxapp#432]
* Wavebox version: Version 3.4.0
* OS: Windows 10 Pro, Version 10.0.15063 Build 15063
* Device: Surface Pro 3 i7

When entering an email recipent and pressing (alt gr) +  2, which in a scandinavian keyboard results in @, the screen switches to blank. Also at the top of the window where it says that I'm in my inbox changes to blank. Pressing (alt gr) + 1 switches back to my inbox where I see the email I was typing into.
I assume Wavebox changes tabs to the ones I had in the premium trial. Currently I only have my Google Inbox as the only tab.

**Comment by Thomas101** [comment]
At the core of it, this is the same issue in https://github.com/wavebox/waveboxapp/issues/383. We're not customizing the keyboard shortcuts for different keyboard layouts at the moment - but we are working on this.

In the short term, you can remove the accelerator that's used to switch service. Open Wavebox Settings, go to the Advanced tab and find the `Service at Index` shortcut. Just delete the text that's in the field and you should be able to enter the @ key

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.4.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Works on macOS and windows 10. @ AltGr and Right Alt on macOS is now not locked on EU keyboards.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
