### ISSUE TITLE
[Feature Request] The ability to disable Hangouts

### ISSUE THREAD

**Issue by dep** [wavebox/waveboxapp#433]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.4.2beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS High Sierra

It would be really nice to disable Hangouts, as I and I imagine many others use other solutions for chatting through either hangouts or some other service.  The ability to disable Hangouts would also speed up load times and offer a cleaner UI for those who opt in to it.  I know Boxy has done this, so it should be possible.

**Comment by Thomas101** [comment]
If you want to disable the hangouts tab, you can do this by right clicking on your account in the left and going to account settings. Then scroll down to hangouts service and uncheck it to disable
![screen shot 2017-10-20 at 15 04 11](https://user-images.githubusercontent.com/103586/31824788-036c2204-b5a8-11e7-8519-197bad97d69b.png)

To disable the hangouts pane in Gmail, click the gear icon in the top-right of gmail to open settings, then click the `chat` tab and then select `chat off`. Once you're done click `save` changes

To disable the hangouts popup in Google Inbox click the hangouts button at the top, then the small down arrow next to `New conversation`. In this settings screen, scroll to the bottom and click `Sign out of Hangouts`

**Comment by dep** [comment]
Sensational! Thank you!
