### ISSUE TITLE
gMail "Filter messages like this" closes before being able to edit.

### ISSUE THREAD

**Issue by meoso** [wavebox/waveboxapp#434]
3.4.2 beta

Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

Inside an email message (gMail)>"_Filter messages like this_">The dialog pops-up, but disappears.  Therefore, requiring to open gMail in a browser to add filters.

**Comment by meoso** [comment]
i think this is a default browser back-end issue and not necessarily Wavebox.  Does wavebox use the system default browser? and if so are browser add-ons (plugins) enabled within Wavebox (invisibly)?

**Comment by nmat** [comment]
hmmm this works on windows 10 and macOS here

are you using any specific browser setting in wavebox that could cause this?

**Comment by meoso** [comment]
default install, no custom scripts or launchers.  it is intermittent, sometimes works, but more often doesn't.  no urgency, just an annoyance that may be out of wavebox control.

**Comment by meoso** [comment]
It's definitely NOT a WaveBox issue, this is persisting with Firefox only gMail.  closing case ticket.

**Comment by Thomas101** [comment]
Looks like you're not the only person having this issue -> [gmail product forums](https://productforums.google.com/forum/#!topic/gmail/n7fiaFsPNEg;context-place=topicsearchin/gmail/filter$20messages)
