### ISSUE TITLE
Feature request: office365 service tabs (more)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#435]
General request to add more services in index:

- [x] Word
- [x] Excel
- [x] Powerpoint
- [ ] Planner
- [x] OneNote
- [x] (Teams)
- [ ] (Sharepoint)

Which I think are the most important. Of course (teams) could be in the topic here also if you are not using teams as a service on its own like slack.

Many office365 users would benifit from at least from the above list. Note though that the list is not complete in anyway since office365 has so many other options that can be added.

**Comment by rmtilson** [comment]
I agree it would be nice to have more Office365 services available when an Office365 account is added. For me, the big two are OneNote and Teams (Future Skype Replacement). For me the ability to use Teams and communicate with SFoB users is a huge win on Linux, never really liked using pidgin.  I would be all for more Teams integration. 

Right now native notifications and generic badge work. But I think there is an issue that when the tab is not in focus and a person responds to the active chat the unread badge is not applied to the tab. Makes it tricky when someone responds to the chat and working on another tab.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by SteVwonder** [comment]
Thanks @Thomas101 for adding the additional services!  Are there any plans right now to add support for Planner?
