### ISSUE TITLE
Setting to force Google docs/slides to open in external browser

### ISSUE THREAD

**Issue by prydonius** [wavebox/waveboxapp#436]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX 10.11.6

I have the "Open new windows in which browser" setting set to the Default Browser which opens normal email links in my browser and not in Wavebox. However, this setting is not honoured for Google Docs or other Google Apps links. These seem to always open in Wavebox. Currently I have to right-click and choose "Open link in Browser" for it to open in my external browser. Would it be possible to add a setting to force this?

Sorry if this has already been filed, I wasn't able to find an issue when searching.

**Comment by nmat** [comment]
Please see: https://github.com/wavebox/waveboxapp/issues/417

**Comment by prydonius** [comment]
@nmat thanks, closing!
