### ISSUE TITLE
Chinese not supported when adding new account

### ISSUE THREAD

**Issue by felicitywang** [wavebox/waveboxapp#437]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
16.04

When adding new accounts like Gmail, Outlook, blank boxes show up instead of Chinese characters. Chinese characters are displayed right elsewhere.

**Comment by felicitywang** [comment]
Update:
All Chinese in the Gmail page are blank boxes.

**Comment by Thomas101** [comment]
Hi, do you know which method you used to install Wavebox? (e.g. snap, deb, tar, etc...). If it's from a snap package, it may be that we need to add some more font support

**Comment by yurieuri** [comment]
im also having this problem.. atm im using ubuntu 16.04 LTS and it was downloaded through the ubuntu software app.

**Comment by Thomas101** [comment]
If you try with the [deb or tar](https://wavebox.io/download) installer do you see the same issue?

**Comment by felicitywang** [comment]
Tried tar installer. Worked.
