### ISSUE TITLE
Feature request: Copy URL

### ISSUE THREAD

**Issue by jjegg** [wavebox/waveboxapp#438]
Enable a highlight or copy function to copy the currently webpage url with navigating a website without the weblink option.

**Comment by nmat** [comment]
hmmmm can you provide example of this? Not following on how to reproduce or the need for it.... :/

**Comment by jjegg** [comment]
For example, on my wavebox I have added my company's JIRA Board. So I use
this tab to work on daily tasks. I am sometimes working on something and
need to send a link to my colleage for this. I am unable to copy/highlight
the text on top of the wavebox. Do you understand now?

**Comment by nmat** [comment]
hmmm I am using linkedin and have a "copy current url" when I right click, that is not shown in JIRA or does it become wrong`?

**Comment by jjegg** [comment]
Ahh gotcha. I did not know that the right click feature allowed the copy of
the existing page.  I guess this issue can be resolved then.

**Comment by nmat** [comment]
its probably still good that you can copy and paste from the addressbar.....just that this could be a workaround until it is fixed correctly for the addressbar

If that makes sense :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.5.0) and Wavebox beta (3.5.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
