### ISSUE TITLE
Blank Tabs

### ISSUE THREAD

**Issue by themiguelamador** [wavebox/waveboxapp#440]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.4.3beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.13.1 Beta

Clicking to open a link on wavebox opens a blank tab on Chrome. This issue is reported using any link, from services, to support link.

**Comment by Thomas101** [comment]
Hi, a few people have reported this. It seems to be an issue with chrome/macOS. If you try the following does it make any difference?

* Check chrome is up to date
* Open System Preferences > General. Change your default Web Browser to Safari and then change it back to Chrome again

**Comment by themiguelamador** [comment]
Solved after updating Chrome to last version Version 63.0.3239.18
