### ISSUE TITLE
Rendering problems: ficklering or blocks of screen real estate dissappearing

### ISSUE THREAD

**Issue by Jan-Jan** [wavebox/waveboxapp#445]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.4.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Ubuntu 17.10 

* Replicate

1. Click on Settings
2. Scroll up and down OR click anywhere

Will see parts of the screen turn white. Or flicker badly.

**Comment by nmat** [comment]
@Jan-Jan are you using the .deb package or snap install?

**Comment by Jan-Jan** [comment]
I installed it via the installer. When I click on the details it referencess `Source: Snap Store`

**Comment by nmat** [comment]
there has been some issues regarding rendering in snap packages. There are some bugs on ubuntu regarding it. If possible can you test using the .deb package and see if you get the same effect there?

**Comment by nmat** [comment]
you can find the package for .deb here: https://github.com/wavebox/waveboxapp/releases/tag/v3.4.0

**Comment by Jan-Jan** [comment]
Thank you, this appeared to have solved the problem

**Comment by nmat** [comment]
seems like the snap packages does have lots of issues regarding rendering, sad to see really. Might be that it is reported on launchpad already.

You can always check: https://launchpad.net/snappy if there is something there.
