### ISSUE TITLE
No systray icon (ubuntu / snap)

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#446]
* Which version of Wavebox are you using?
Snap 3.5.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]\
Ubuntu 17.10 / Unity 7

The systray icon is not showing on Unity 7 when Wavebox is installed from a snap instead of a .deb package. This is a from-scratch installation, and the relevant option to show the icon is activated at Wavebox's config, like so:

![image](https://user-images.githubusercontent.com/6388823/32274877-ec55f92a-bf00-11e7-867e-fda2ac6b7b6a.png)

**Comment by Thomas101** [comment]
We're seeing the same here. Only on 17.10 though. I'll take a look into what's happening!

**Comment by luispabon** [comment]
```
XDG_CURRENT_DESKTOP=Unity:Unity7:ubuntu
XDG_SESSION_DESKTOP=unity
```
Could it be this electron bug again?

**Comment by Thomas101** [comment]
I've been playing around with electron to see if I can get to the bottom of this. Looks like it's been fixed in 1.8.2-beta. We're looking to update to the 1.8.* releases shortly, so I'm hoping this will solve the problem

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Tested on 17.10 and the icon is there from the snap package beta release.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
