### ISSUE TITLE
Clicking on links won't open browser

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#451]
* Which version of Wavebox are you using?
3.5.0 / snap

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.10 / Unity 7

Clicking on links seem to have no effect. I do have snapd-xdg-open installed.

**Comment by nmat** [comment]
@luispabon hello, it seems that this is reported on launchpad for snapd packages already:

https://bugs.launchpad.net/snappy/+bug/1580740

I would suggest that if you want to use a working or better version until snapd has fixed it then try the .deb packages. They are located here on github for wavebox and also on wavebox.io

**Comment by Thomas101** [comment]
After a bit more digging, it looks like the Snap team have added support for `xdg-open` without the need for `snapd-xdg-open` in Snap core 2.28 (yay!). The `snapd-xdg-open` workaround seems to keep working on everything we've tested apart from 17.10.

We'll make sure our build boxes are up to date and remove the additional dependency in the next beta so this should start working again

**Comment by maroc81** [comment]
I think I've hit this issue as well and am unable to purchase the pro version since it tries to open inside wavebox.  Is there a way I can do this now with the snap version?  I assume if I install the deb I have to reconfigure wavebox. Or is there another way to purchase pro outside wavebox?

**Comment by nmat** [comment]
If you want to quickly do it. You can always install the .deb package or so. Then use that to purchase and it will reflect to the account of which you did the purchase.

For example if you use the gmail and make the purchase through that.

**Comment by maroc81** [comment]
That did the trick. I installed from deb, used my gmail to upgrade to pro from the deb then from the snap app, I switched to the account mapped to the pro version.

**Comment by nmat** [comment]
@maroc81 perfect! its a workaround until the snap package updates are in place. Hopefully the new release will fix a lot of headaches regarding the opening of URLs from snap packages. :)

**Comment by Thomas101** [comment]
We were hoping to get the fix out to the beta channel last week but have been held up with some technical issues. If you're still using snap we're trying our best to ship asap :)

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by luispabon** [comment]
snap, yes?

**Comment by Thomas101** [comment]
Yeah. `sudo snap refresh wavebox --channel=beta` should get the latest beta, or if you're happy to wait a few more days - with no show stoppers we'll be pushing this out to stable

**Comment by luispabon** [comment]
I'll test this out now :+1:

**Comment by luispabon** [comment]
Works perfectly. Thank you @Thomas101 :+1:

**Comment by nmat** [comment]
Verified here also using release in beta channel.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
