### ISSUE TITLE
npm run install:all errors

### ISSUE THREAD

**Issue by skyborgff** [wavebox/waveboxapp#454]
* Which version of Wavebox are you using? [3.5.1]

* Which Operating System are you using? [Windows 10]

When trying to build it gives me a lot of errors

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install:all' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'preinstall:all', 'install:all', 'postinstall:all' ]
5 info lifecycle wavebox@3.5.1~preinstall:all: wavebox@3.5.1
6 info lifecycle wavebox@3.5.1~install:all: wavebox@3.5.1
7 verbose lifecycle wavebox@3.5.1~install:all: unsafe-perm in lifecycle true
8 verbose lifecycle wavebox@3.5.1~install:all: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\node_modules\.bin;C:\WINDOWS;C:\WINDOWS;C:\WINDOWS;C:\WINDOWS;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\ProgramData\Anaconda3;;C:\Users\Fábio Ferreira\AppData\Local\Microsoft\WindowsApps;C:\Users\Fábio Ferreira\AppData\Roaming\npm
9 verbose lifecycle wavebox@3.5.1~install:all: CWD: C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1
10 silly lifecycle wavebox@3.5.1~install:all: Args: [ '/d /s /c', 'node scripts/installAll.js' ]
11 silly lifecycle wavebox@3.5.1~install:all: Returned: code: 1  signal: null
12 info lifecycle wavebox@3.5.1~install:all: Failed to exec install:all script
13 verbose stack Error: wavebox@3.5.1 install:all: `node scripts/installAll.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wavebox@3.5.1
15 verbose cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "install:all"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
```

**Comment by Thomas101** [comment]
if you try running `npm install` and then `npm run install:all` does that work?

**Comment by skyborgff** [comment]
`npm install` worked, but `npm run install:all` didn't

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install:all' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'preinstall:all', 'install:all', 'postinstall:all' ]
5 info lifecycle wavebox@3.5.1~preinstall:all: wavebox@3.5.1
6 info lifecycle wavebox@3.5.1~install:all: wavebox@3.5.1
7 verbose lifecycle wavebox@3.5.1~install:all: unsafe-perm in lifecycle true
8 verbose lifecycle wavebox@3.5.1~install:all: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\ProgramData\Anaconda3;;C:\Users\Fábio Ferreira\AppData\Local\Microsoft\WindowsApps;C:\Users\Fábio Ferreira\AppData\Roaming\npm
9 verbose lifecycle wavebox@3.5.1~install:all: CWD: C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1
10 silly lifecycle wavebox@3.5.1~install:all: Args: [ '/d /s /c', 'node scripts/installAll.js' ]
11 silly lifecycle wavebox@3.5.1~install:all: Returned: code: 1  signal: null
12 info lifecycle wavebox@3.5.1~install:all: Failed to exec install:all script
13 verbose stack Error: wavebox@3.5.1 install:all: `node scripts/installAll.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wavebox@3.5.1
15 verbose cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "install:all"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error wavebox@3.5.1 install:all: `node scripts/installAll.js`
22 error Exit status 1
23 error Failed at the wavebox@3.5.1 install:all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Thomas101** [comment]
It looks like npm on windows needs to use `npm.cmd` when spawning rather than just plain old `npm`. If you try https://github.com/wavebox/waveboxapp/commit/0656a9722e8ed82f0a399c056956d771d4fb667e does that work?

**Comment by skyborgff** [comment]
didn't worked, same error
'''
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install:all' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'preinstall:all', 'install:all', 'postinstall:all' ]
5 info lifecycle wavebox@3.5.1~preinstall:all: wavebox@3.5.1
6 info lifecycle wavebox@3.5.1~install:all: wavebox@3.5.1
7 verbose lifecycle wavebox@3.5.1~install:all: unsafe-perm in lifecycle true
8 verbose lifecycle wavebox@3.5.1~install:all: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\ProgramData\Anaconda3;;C:\Users\Fábio Ferreira\AppData\Local\Microsoft\WindowsApps;C:\Users\Fábio Ferreira\AppData\Roaming\npm
9 verbose lifecycle wavebox@3.5.1~install:all: CWD: C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1
10 silly lifecycle wavebox@3.5.1~install:all: Args: [ '/d /s /c', 'node scripts/installAll.js' ]
11 silly lifecycle wavebox@3.5.1~install:all: Returned: code: 1  signal: null
12 info lifecycle wavebox@3.5.1~install:all: Failed to exec install:all script
13 verbose stack Error: wavebox@3.5.1 install:all: `node scripts/installAll.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wavebox@3.5.1
15 verbose cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "install:all"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error wavebox@3.5.1 install:all: `node scripts/installAll.js`
22 error Exit status 1
23 error Failed at the wavebox@3.5.1 install:all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
'''

**Comment by Thomas101** [comment]
The install:all scripts just runs through the subdirectories running `npm install`. I wonder if sterr isn't being piped out on Windows or something - hence we're not seeing an error that really tells anything.

If you try moving into the following directories and running `npm install` on each do you get any errors or are they all okay?

`src/app`
`src/guest`
`src/crextensionApi`
`src/scenes/mailboxes`
`src/scenes/content`
`src/scenes/monitor`
`src/scenes/print`

**Comment by skyborgff** [comment]
Some gave an error:

**\src\scenes\print :**
```
PS C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\scenes\print> npm install
npm WARN worker-loader@1.1.0 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

added 234 packages in 208.433s
PS C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\scenes\print>
```

**\src\guest :**
```
PS C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\guest> npm install

> nodehun@2.0.11 install C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\guest\node_modules\nodehun
> node-gyp rebuild


C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\guest\node_modules\nodehun>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\guest\node_modules\nodehun
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodehun@2.0.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodehun@2.0.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fábio Ferreira\AppData\Roaming\npm-cache\_logs\2017-11-11T09_43_24_506Z-debug.log
PS C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\guest>
```

**\src\app :**
```
PS C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app> npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> @nodert-win10/windows.applicationmodel@0.2.96 install C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.applicationmodel
> node-gyp rebuild --msvs_version=2015


C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.applicationmodel>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "" rebuild --msvs_version=2015 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.applicationmodel
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> @nodert-win10/windows.data.xml.dom@0.2.96 install C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.data.xml.dom
> node-gyp rebuild --msvs_version=2015


C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.data.xml.dom>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "" rebuild --msvs_version=2015 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.data.xml.dom
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> @nodert-win10/windows.foundation@0.2.96 install C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.foundation
> node-gyp rebuild --msvs_version=2015


C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.foundation>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "" rebuild --msvs_version=2015 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.foundation
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> @nodert-win10/windows.ui.notifications@0.2.96 install C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.ui.notifications
> node-gyp rebuild --msvs_version=2015


C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.ui.notifications>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "" rebuild --msvs_version=2015 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.ui.notifications
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> @nodert-win10/windows.ui.startscreen@0.2.96 install C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.ui.startscreen
> node-gyp rebuild --msvs_version=2015


C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.ui.startscreen>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "" rebuild --msvs_version=2015 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\ProgramData\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app\node_modules\@nodert-win10\windows.ui.startscreen
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-mac-notifier@0.0.13 (node_modules\node-mac-notifier):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for node-mac-notifier@0.0.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.applicationmodel@0.2.96 (node_modules\@nodert-win10\windows.applicationmodel):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.applicationmodel@0.2.96 install: `node-gyp rebuild --msvs_version=2015`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.data.xml.dom@0.2.96 (node_modules\@nodert-win10\windows.data.xml.dom):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.data.xml.dom@0.2.96 install: `node-gyp rebuild --msvs_version=2015`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.foundation@0.2.96 (node_modules\@nodert-win10\windows.foundation):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.foundation@0.2.96 install: `node-gyp rebuild --msvs_version=2015`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.ui.notifications@0.2.96 (node_modules\@nodert-win10\windows.ui.notifications):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.ui.notifications@0.2.96 install: `node-gyp rebuild --msvs_version=2015`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.ui.startscreen@0.2.96 (node_modules\@nodert-win10\windows.ui.startscreen):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.ui.startscreen@0.2.96 install: `node-gyp rebuild --msvs_version=2015`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 402 packages in 394.71s
PS C:\Users\Fábio Ferreira\Desktop\waveboxapp-3.5.1\src\app>
```

**Comment by nmat** [comment]
I got it to build here using the following:

**OS:** windows 10 Creators Fall Edition (1709 (OS Build 16299.19))
**Node.js:** 8.9.1 LTS
**Python:** 2.7.14 (since python3 is not supported by node-gyp check this: https://github.com/nodejs/node-gyp/issues/193)

1. Installed node.js from website on https://nodejs.org/en/download/

2. In powershell:
`cd C:\`
`mkdir git`
`git clone https://github.com/wavebox/waveboxapp.git`

3. Fetched the api key in wavebox and added the credentials.js

4. Back in powershell:
`cd C:\git\wavebox\`
`npm install`

5. Made sure to set the right python version:
`npm config set python=C:\python27\python.exe`

6. Opened up a NEW powershell with administrator (since I got a different error on compile where it could not fetch build tools): 
Please see: https://stackoverflow.com/questions/32964144/gyp-err-stack-error-c-program-files-x86-msbuild-12-0-bin-msbuild-exe-fail
`npm install -g windows-build-tools`

7. Back to normal powershell
`cd C:\git\wavebox\`
`npm run install:all`
(Some warnings came up but it starts to install the deps)

8. Start the compilation:
`npm run rebuild:electron`

9. Start the app using the new info:
`npm start`

This started the application. Took a bit of time to compile but worked for me here. Hope this might help.

**Comment by nmat** [comment]
Here is my $psversiontable also:

Name                           Value
----                           -----
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

The most important part is to get:
python 2.7 and windows-build-tools installed and it will compile

**Comment by skyborgff** [comment]
@nmat Ah, i see the problem, i'm using python 3. 
What are the advantages to building instead of just installing?

**Comment by nmat** [comment]
@skyborgff nice so it worked now. Well rebuilding would indicate to test some code etc I would think. Not 100% sure how that works but I believe so

**Comment by Thomas101** [comment]
You have to run the `npm run rebuild:electron` to ensure that the native dependencies are built against your os, version of electron, and node install

**Comment by nmat** [comment]
@Thomas101 hmmmm since there is a bit of confusion of the python 2.7 then maybe add a note in the build for windows that you should look at node-gyp to fix the deps of that?

Not 100% sure how you would want to do that but I guess there could come some more questions for it?

**Comment by skyborgff** [comment]
@nmat I did't tried, I need python 3 for uni and i don't want to install 2.7, compatibility issues might occur, but thank you for solving the issue i guess :p

**Comment by Thomas101** [comment]
I've updated the build instructions to include python 2.7, windows-build-tools and also bumped the nodejs version. Okay to close?

**Comment by nmat** [comment]
@Thomas101 I would say that you can close the issue.

**Comment by nmat** [comment]
I give you my blessing to close :)

**Comment by skyborgff** [comment]
I give mine too :p
