### ISSUE TITLE
Fix required: icon name of Wavebox is incorrect on linux

### ISSUE THREAD

**Issue by rhoconlinux** [wavebox/waveboxapp#456]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.5
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

The issue:
After the last update, the .desktop file is referring [wrongly] to the app icon, which is named "icon.png". This  should be corrected since not only is super ambiguous at system level, but also makes impossible to apply different icon themes and make their styles compatible with wavebox. 
By the way, if icons are stored in /usr/share/icons/hicolor then they are universally called from the entire system, is way more accurate to do that, instead of host the icon inside the app folder.
Cheers!

**Comment by Thomas101** [comment]
I'll change the filename to be `wavebox_icon.png` for the next release. Which install method were you using?

**Comment by rhoconlinux** [comment]
I made the install with the .deb from the ppa: `=https://wavebox.io/dl/client/repo/x86_64/Wavebox_3_5_0_linux_x86_64.deb
`
Cheers!

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
