### ISSUE TITLE
Typo: "on of" should be "one of"

### ISSUE THREAD

**Issue by rinopo** [wavebox/waveboxapp#457]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.5.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
mac os sierra 10.12.6

"on of the following modes" should be "one of the following modes"

https://github.com/wavebox/waveboxapp/blob/ff5d9041efcf6a31e888e25df0fd7375ce8e59b4/src/scenes/mailboxes/src/Scenes/MailboxWizardScene/WizardConfigure/WizardConfigureGmail.js#L84
https://github.com/wavebox/waveboxapp/blob/ff5d9041efcf6a31e888e25df0fd7375ce8e59b4/src/scenes/mailboxes/src/Scenes/MailboxWizardScene/WizardConfigure/WizardConfigureMicrosoft.js#L99

**Comment by Thomas101** [comment]
Thanks for pointing that out :)

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
