### ISSUE TITLE
Feature suggestion: Markdown 

### ISSUE THREAD

**Issue by jottr** [wavebox/waveboxapp#458]
I am using [Markdown here](http://markdown-here.com/) when not in Wavebox and find it very useful. 
This would be a very useful feature in wavebox. 
I'd like to kindly request the addition of "Markdown here" to wavebox.

**Comment by TheWithz** [comment]
Markdown here is already implemented is it not... https://github.com/wavebox/waveboxapp/issues/138

**Comment by nmat** [comment]
@jottr as @TheWithz mentioned it is included already. You can also read the blog post on: https://blog.wavebox.io/wavebox-release-news-leaner-faster-plus-more-services-extensions/

**Comment by jottr** [comment]
I see, thx!
