### ISSUE TITLE
Unclear what the difference between the service display modes

### ISSUE THREAD

**Issue by huangv22** [wavebox/waveboxapp#46]
Took me awhile to figure out what the difference means. I had expected when I moved the items to the top that it would no longer show on my left nav. 

I believe the logic is that it is the sub units, that move to the top navi.

I think it's confusing because "Service Display Mode" is not natural language. 

**Potential fixes:**
* Change the copy so it's more clear.
* Move it to another location. The drop down is actually influencing placement of the sub services (calendar, people, tasks, ondrive, etc)
* add a (?) to explain
* in line explanation
* Is this feature even necessary?

**Priority:** low

* Which version of Wavebox are you using? 3.1.2
* Which Operating System are you using? Mac OSX 10.12.4

**Comment by Thomas101** [comment]
Hi,

It's excellent to get feedback like this. I can see how it can be unclear as to what it does. I've used my (very bad) paint skills to throw something together. Do you think this would make it clearer...

* Move the services config options out of appearance and into their own section
* Change display mode to something more human like "Where should these services be displayed?"
* Add a title above the services list with a little bit of explainer

Thanks!

![screen shot 2017-04-11 at 08 57 55](https://cloud.githubusercontent.com/assets/103586/24898710/b1e60a34-1e95-11e7-90d4-7b964f06cb92.png)

**Comment by huangv22** [comment]
Yeah, it could work. You need to explain to the user what a service is. One could infer from the title below ,"Services enabled on this account". What about adding a (?) with a tooltip. A service is XXXXXX, for example. Google services include: gMail, Cal, hangouts, etc.

**Comment by Thomas101** [comment]
Great idea. Lets get this in the next release!

**Comment by Thomas101** [comment]
This has been added into 3.1.4 which is now live. Thanks

Wavebox should update automatically after a while, but if you want to hurry it up, just restart the app and it will re-check
