### ISSUE TITLE
[Feature Request] Google classroom integration

### ISSUE THREAD

**Issue by TheWithz** [wavebox/waveboxapp#461]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.5.1 beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
[Solus 3](https://solus-project.com/)

A friend of mine was wondering if support for Google Classroom was planned?

**Comment by Pear0** [comment]
As a high school student, my school uses Google Classroom extensively so this would be a very nice feature.

**Comment by Thomas101** [comment]
A big thanks to @TheWithz for contributing this! We’ve just released it to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
