### ISSUE TITLE
Grammarly Extension Status?

### ISSUE THREAD

**Issue by jjegg** [wavebox/waveboxapp#464]
When are you going to be focusing on integrating grammarly within wavebox? Amongst the community, this is a high demand ask.

**Comment by nmat** [comment]
Hello @jjegg the work for grammarly is ongoing according to: https://github.com/wavebox/waveboxapp/issues/138

You can follow that thread to see status of extensions.

**Comment by Thomas101** [comment]
yes @nmat is right, we're currently working on Grammarly support, we've got about 75% of the work done so far, but there's a few rough edges that we need to resolve before we'd be happy to push this out. Really appreciate your question, we're big fans of grammarly here too!

**Comment by Thomas101** [comment]
![grammarly](https://user-images.githubusercontent.com/103586/33171828-b0f0f3e8-d045-11e7-8b13-9848b346d7ac.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
