### ISSUE TITLE
System buttons (close/minimize/fullscreen) overlaps tabs — Mac / OSX

### ISSUE THREAD

**Issue by animalphase** [wavebox/waveboxapp#466]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.5.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.13

**Issue:**

With configuration options *tabs in Top Toolbar* and *icon positioning: Left Align*, the OSX system buttons overlap the account app tabs.

<img width="435" alt="screen shot 2017-11-13 at 13 40 05" src="https://user-images.githubusercontent.com/3846271/32745740-315d2f4e-c879-11e7-992a-2b135a35b86c.png">

---

**Possible solutions:**

When this config of *tabs in top toolbar*, *icons left aligned*, and *titlebar hidden* is selected, do one of the following:
- extra padding to the left of the tabs, so they are indented from the system buttons.
- extra padding above the tabs, so that the black bar is taller and provides enough room for the system buttons to be placed above (preferred to the above for alignment reasons?)
- implement custom close/minimize/fullscreen buttons

---

**Additional nice option to have that would coincidentally get around this:**
- option for center-aligning tabs

**Comment by nmat** [comment]
hmmm I do not see this on macOS or windows10 here for gmail.

Does this effect only occur for inbox? Or if there is more notification icons for inbox that I am not aware of?

**Comment by nmat** [comment]
ah! replicated when hiding the sidebar. so hiding the sidebar creates this effect.....

**Comment by Thomas101** [comment]
Yeah - looks like a case we didn't look into there!

**Comment by animalphase** [comment]
right, sorry i didn't include that with my other description! thanks

**Comment by nmat** [comment]
@animalphase well managed to find it so no problem. :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
tested and works fine here. Tested with various different settings and the icons are not overlapping.

**Comment by nmat** [comment]
@animalphase if possible maybe you can test the beta?

This issue I believe can be closed since it worked for me on macOS when testing.

**Comment by nmat** [comment]
Also tested on 10.13.2 now and works fine where the buttons are staying visual and extensions on the side of it. See no problem with this at the moment :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
