### ISSUE TITLE
wavebox.io - wrong link on page for "more reasons"

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#467]
wavebox.io under the "More Reasons" topic this link is used: https://wavebox.io/whywavebox 

but according to other links it should be: https://wavebox.io/why-wavebox

**Comment by Thomas101** [comment]
Thanks! I think @rhys101 is due to release this out today :)

**Comment by nmat** [comment]
@Thomas101 perfect! thank you! Shall I close this then maybe?

**Comment by Thomas101** [comment]
Should be fixed now :)

**Comment by nmat** [comment]
hmmm tested it in a icognito mode in chrome but still got the same error url. (could be a cache on my part also but just wanted to let you know)

**Comment by Thomas101** [comment]
Nope you're right. Ill take a look

**Comment by Thomas101** [comment]
Second time lucky :)

**Comment by nmat** [comment]
confirmed as fixed! :) thanks
