### ISSUE TITLE
Sleeping Account Indication Not Working with Services in Top Toolbar

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#471]
* Which version of Wavebox are you using?
3.5.1beta
* Which Operating System are you using?
KDE Neon (Ubuntu 16.04 / Linux)

Sleeping Indication is not working for accounts that have the sub-Services displayed in the Top Toolbar. If you have them set in the Sidebar it works fine but when changed to the Top Toolbar the normal image/colors are displayed rather than the greyed out version.

It doesn't matter if the Top Toolbar is aligned left or right, it happens either way. (the left align is quite nice btw)

I have toggled the services display location on multiple to test it and it effects any account with the top toolbar selected.

Bright Side: the sleeping functionality is still working so that's good. :)

**Comment by Thomas101** [comment]
Thanks, a fix for this has gone into master - should be making its way out into beta today/tomorrow :)

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this to the beta channel of Wavebox in version 3.5.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by MichaelTunnell** [comment]
Tested the fix with 3.5.2 beta, works great again. Thanks! :)

 . . . closing issue. :)
