### ISSUE TITLE
New google calendar: hangouts links open in browser instead of app

### ISSUE THREAD

**Issue by luispabon** [wavebox/waveboxapp#473]
* Which version of Wavebox are you using? 
3.5.1b

* Which Operating System are you using?
Ubuntu 17.10 / Unity 7

There's a new version of the Google Calendar that just activated in one of my business accounts. Hangouts links in events open in browser instead of Wavebox (which is what happens on the normal style calendar).

My default browser is Firefox where hangouts won't work, I was relying on Wavebox to use hangouts effectively.

![image](https://user-images.githubusercontent.com/6388823/33067083-fb7a11a8-cea4-11e7-9614-bcedc957dba6.png)

**Comment by Thomas101** [comment]
I was just taking a look into this, but wasn't able to reproduce it. I just added hangouts in as a conferencing option...
![screen shot 2017-11-29 at 15 31 33](https://user-images.githubusercontent.com/103586/33383141-74b3345c-d51a-11e7-8b3c-c42d5e5b7ad4.png)

... then clicked on `Join Hangout` from the calendar...

![screen shot 2017-11-29 at 15 31 55](https://user-images.githubusercontent.com/103586/33383166-81362a68-d51a-11e7-8624-08b6efff96d5.png)

...but it seemed to open up okay. If you try that does it work? Is there a different setup that I can run through where this doesn't work?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
