### ISSUE TITLE
Can't install new spell-checker languages

### ISSUE THREAD

**Issue by kofm** [wavebox/waveboxapp#474]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.5.0.

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

OS X 10.12

Hi,
i'm trying to install new spell-checker languages but with no success. Installation seems to have success but then no new dictionaries show up in the menu. 

I've tried disabling and re-enabling the feature and restarting, but nothing worked.

Any help would be appreciated.
Thanks in advance and keep up with your awesome work!

**Comment by Thomas101** [comment]
Hi, which dictionary are you trying to install? It could be an incorrect link for one of the dictionaries

**Comment by kofm** [comment]
I'm trying with Italian dictionary. I also tried Afrikaans (to check if the problem was related to Italian only) also with no success.

**Comment by nmat** [comment]
Tried to reproduce this on:
3.5.2beta

on macOS 10.13.1, windows 10 and snap linux package but do not seem to be able to reproduce this. I get the wizard to install and the dropdown to select. Unfortunately I do not have a 10.12 macOS machine to test on.

**Comment by kofm** [comment]
Should i try 3.5.2?

**Comment by Thomas101** [comment]
There's not really been any change between 3.5.0 and 3.5.2 as regards the spellchecking, but feel free to try it.

Do you know if you're behing a proxy server of any kind? It sounds like the downloads maybe failing, but I'm not 100% sure.

If you want to try installing them manually there's a few steps to do...
1. Open `~/Library/Application Support/wavebox/` (e.g. `/Users/tom/Library/Application Support/wavebox`)
2. If there isn't a folder called `user_dictionaries` create one
3. Download the following two files `https://wavebox.io/dl/dictionaries/it_IT/index.aff` `https://wavebox.io/dl/dictionaries/it_IT/index.dic`.
4 Place the two downloaded files in the `user_dictionaries` folder renaming them to be `it_IT.aff` and `it_IT.dic` respectively.

Your directory structure should look like this...
![screen shot 2017-11-22 at 10 47 21](https://user-images.githubusercontent.com/103586/33123607-8db47d10-cf72-11e7-968d-1c1db724128e.png)
...and you should now see Italian listed as one of the installed dictionaries

**Comment by kofm** [comment]
Installing manually resolved the problem! Thanks!!
I'll try downloading it when under another Internet connection, to see if it's a connection problem.

**Comment by Thomas101** [comment]
Thanks! It would be great to know if that is the underlying issue

**Comment by nmat** [comment]
@kofm did you manage to test this a bit more? would be interesting to see the result. :)

**Comment by kofm** [comment]
> Do you know if you're behing a proxy server of any kind? It sounds like the downloads maybe failing, but I'm not 100% sure.

You were right! Using my home internet connection, the French dictionary successfully downloaded. It seems that Wavebox behaves as if the download is fine even if it can't download anything.

Thanks for the support 👍

**Comment by nmat** [comment]
So the main issue is that spellchecker goes through without it warning that there is no real network connection. Or you had connection but just couldn't download the dictionary?

Trying to see if there might be a possibility that spellchecker download just continues without checking if connection works or not. 🤔

**Comment by kofm** [comment]
I **had** connection but couldn't download the dictionary.

Maybe a little warning if the download fails?

**Comment by nmat** [comment]
The dictionary was not in the directory after the "download" was done correct? In that case I would say yes. A test to see if it can be downloaded + if it has been downloaded should be done. It would ease the use of understanding if something fails.

**Comment by kofm** [comment]
Neither the dictionary files nor the directory were present after a successful download. 
Maybe the issue is related to Wavebox not creating the directory? I manually created it to copy dictionary files. How can i test? 
Can i safely delete directory?

**Comment by Thomas101** [comment]
You can delete or move `user_dictionaries` without any problem. Just make sure Wavebox is closed before you do this otherwise you may see unintended side-effects.

Next time you try downloading there might be some extra info in the console. If you go to `View`>`Developer`>`Wavebox Developer Tools` you'll get a window popup. Click on the console tab and you should see something similar to below...
![screen shot 2017-11-27 at 11 29 08](https://user-images.githubusercontent.com/103586/33264647-5f6bf990-d366-11e7-90cd-9f95a9818d2b.png)

(if you've been online & offline a few times with Wavebox open you may have some error messages there. These are normal)

...try to download and install dictionary again and see if you have any new error messages. I'll take a look at the flow it runs through again to see if there's any edge case that doesn't bring up the error

**Comment by kofm** [comment]
![image](https://user-images.githubusercontent.com/12545394/33270784-7d380dbe-d385-11e7-9961-2a49818486b4.png)

**Comment by Thomas101** [comment]
Nice spot! Can you give it another try?

**Comment by kofm** [comment]
Works now! I managed to successfully download Afrikaans dictionary 👍 
No error messages in Wavebox Developer Tools console

**Comment by Thomas101** [comment]
Awesome! Great to hear you got it working :)
