### ISSUE TITLE
Optimization wizard - not starting on snap package

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#475]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.5.2beta

* Which Operating System are you using?
Ubuntu 17.10 

* Description:
Newly introduced optimization wizard does not start on snap package beta channel. Force ran it from settings and that worked just fine. Should the wizard start on first launch after the upgrade?

**Comment by Thomas101** [comment]
There's two checks that it does before starting automatically
1. You have more than one account added
2. You're on Pro or Trial

If you don't satisfy those two, it shouldn't come up. However if you add more than one account and restart the app it should come up second time

**Comment by nmat** [comment]
Ah that makes sense. Will test it when I get home then.

Its actually the only place where I only have one account/service connected so yes. That does in fact make a difference and does not meet the requirement.

**Comment by nmat** [comment]
tried to reproduce but since I have done the wizard already then I guess it will not ask me again. So can't reproduce it. I will close it for now.

**Comment by nmat** [comment]
tried to reproduce but since I have done the wizard already then I guess it will not ask me again. So can't reproduce it. I will close it for now.
