### ISSUE TITLE
New support icons not showing on windows 10

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#476]
* Which version of Wavebox are you using?
3.5.2beta

* Which Operating System are you using?
Windows 10

* Description:
The new icons for KB, Blog, GitHub and Email Support is not showing on windows 10 release. On macOS 10.13.1 they are working fine and on Linux snap package.

**Comment by nmat** [comment]
Tested on second windows 10 machine and the same effect with no new icons. So this seems to origin to windows 10 system

**Comment by Thomas101** [comment]
Awesome thanks! We missed that one in testing

**Comment by nmat** [comment]
I was afraid I had some crazy cache issue. I can test the git build later on then. :)

**Comment by nmat** [comment]
tested in git latest build. Closing. Thank you @Thomas101
