### ISSUE TITLE
Copy url from wavebox external window copies other items also

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#478]
* Which version of Wavebox are you using?
3.5.2beta

* Which Operating System are you using?
Windows 10

* Description:
Copy the url with double click will copy other items also. (tested on both onedrive and google drive urls)

* Steps to reproduce:

1. Go to google drive
2. Open a item (pdf for example)
3. Select "Open in new window" in the three dotted top right menu
4. Double click the top URL and copy with Ctrl+C
5. Paste the url in a text document

* Result:
It will copy the url + more information:

```
<url>

Find in Pagesearch

Open in Browseropen_in_browser
```

**Comment by Thomas101** [comment]
Thanks, I'll take a look!

**Comment by nmat** [comment]
verified working in GIT on windows 10

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
tested in beta 3.6.2beta

works on both macOS 10.13.2 and windows 10. Closing.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
