### ISSUE TITLE
Start minimized doesn't work.

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#480]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.6.0.
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
ElementaryOS 0.4.1. Loki

Option "Always Start Minimized" enabled in setup but the app doesn't listen.
Previously never an issue.

**Comment by nmat** [comment]
Verified on macOS also.

Even though it is said to use "Always start minimized" the application does start with window showing.

**Comment by Thomas101** [comment]
Thanks for reporting!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by WebShapedBiz** [comment]
Thank you Thomas, I can confirm that the version 3.6.2. beta is fixing this
issue on Linux.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-11-30 11:53 GMT+01:00 Thomas Beverley <notifications@github.com>:

**Comment by nmat** [comment]
Tested on macOS 10.13.2 here and works fine in 3.6.2beta

**Comment by nmat** [comment]
Works on windows 10 and on macOS 10.13.2

I have one question of one scenario I tested.

* Description:
Quit wavebox, click wavebox icon to start it when logged in (having setting start on minimized)

* Result:
The app starts but starts minimized. So if you are logged in already. Click the icon the window does not show. Should this effect occur and be intentional?

Or is it only on login the app should be hidden?

**Comment by Thomas101** [comment]
The start minimized option under settings will always make it start minimized.

For startup there's the startup settings dropdown for macOS and windows...

![screen shot 2017-12-01 at 08 40 13](https://user-images.githubusercontent.com/103586/33474615-542d3ce6-d673-11e7-8110-6bc0c10250cb.png)

... or alternatively...
* macOS you can use the hide flag under sys preferences/login items
* Windows if you add a shortcut under Startup you can add the `--hidden` flag

We don't have an in-built way to set the startup preference on linux at the moment. But if you're adding Wavebox to start script, appending the `--hidden` option will make it startup hidden

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
