### ISSUE TITLE
Disable tooltip for topbar services?

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#481]
* Which version of Wavebox are you using?
3.6.1

* Which Operating System are you using?
macOS 10.13.2, windows 10

* Description:
Tooltip is hidden for sidebar only. But what about the top service bar?

Maybe the disable tooltip could have a dropdown that says something like:
Show all tooltip
Hide all tooltip
Enable for Topbar only
Enable for Sidebar only

Or something like that? 

I have seen the tooltip for extensions, that is why I am wondering.

**Comment by Thomas101** [comment]
I think this could make it in!

**Comment by Tahini-123** [comment]
I was about to put the same in! Quite redundant IMO.

**Comment by nmat** [comment]
Tested on macOS 10.13.2 and windows 10 1709 (OS Build 16299.125)

Waveboxapp: GIT master 3.7.1

Using "Hide All" hides only services but extensions are still showing in tooltip.

Same effect on both systems.

**Comment by Thomas101** [comment]
As regards extensions, the plan was to leave those there at the moment. We could look to disable those separately though. Some extensions use the tooltip to convey useful info, some not so much. It's difficult to place a blanket setting across all of them I think.

We’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Verified working on windows 10 so far. I will close this since if extensions do keep some information then I can imagine it is useful to have.
