### ISSUE TITLE
[Request] Remember last selected service when switching accounts

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#482]
I would like the option to have Wavebox remember which service 'tab' I was in when switching back to an account.

For example, if I am in Google Calendar (Service #2) of Account 1, then switch to my WhatsApp account, then go back to Account 1, it always takes me back to Gmail (Service #1). I would rather it remember that I was in Calendar.

**Comment by nmat** [comment]
Hello @dzg,

I believe this is reported in:
https://github.com/wavebox/waveboxapp/issues/350
and
https://github.com/wavebox/waveboxapp/issues/85

Does those pretty much cover what it is that you where requesting?

**Comment by dzg** [comment]
Hi @nmat 

I read those, and, no, not really what I mean. I don't really care about going to Inbox, or about the default service.

Let's say I have a Google Doc open in my first Account ... this is in the 2nd 'tab' or Service for Account 1.

I am copying/pasting info between that window, and my 5th Account, which is WhatsApp. I am wanting to quickly switch back and forth between these 2 tabs: **Account 1 Service 2** and **Account 5 Service 1**.

I want to do this by keystroke Cmd-1 and Cmd-5.

But whenever I switch back to Account 1 with Cmd-1, it always takes me back to **Account 1 Service 1** which is the Gmail window.

I want Wavebox to remember that I was in Account 1 **Service 2**

Does that make sense?

**Comment by nmat** [comment]
Yeah that makes sense. Like "Remember last used place"....I just think I have heard about it before here but do not know exactly which ticket. Just very familiar to me. And yes you are right. I think the state should be saved if you select an option to use last used service/service index.

**Comment by Thomas101** [comment]
I think this is something we can look to add in. It would certainly make switching a lot easier

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
