### ISSUE TITLE
[Request] Easier re-ordering of services

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#484]
The "move up/down" one-at-a-time function is very cumbersome.

If I add a new account, and it's down at the end as the 9th service, it seems I have to right-click and "move up" **8 times** if I want it to become #2.

I wish I could just drag services around, either in the sidebar or within the prefs.

Ideally I'd like to be able to just Cmd-drag the icons in the sidebar.

**Comment by nmat** [comment]
hello @dzg,

There has been a report about this already in: https://github.com/wavebox/waveboxapp/issues/415

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
