### ISSUE TITLE
Autocomplete on email adresses does not work for Inbox

### ISSUE THREAD

**Issue by rhuss** [wavebox/waveboxapp#486]
* Which version of Wavebox are you using? 

3.6.1 beta

* Which Operating System are you using? 

macOS Sierra 10.12.5

------------------

Since several versions (stable, beta), I have the issue that with one of my two GMail accounts using Inbox, the autocompletion on email addresses when composing a new message fails. It's for my company account (which is also served via GMail), the regular gmail accounts works without issue.

Also when using Inbox from the browser, autocompletion on email addresses works flawlessly in both accounts.

Anything I can help in debugging this very annoying issue ?

**Comment by Thomas101** [comment]
Hi, thanks for reporting. There's a few things that might help us to reproduce this...

* It sounds like you've probably tried this, but does restarting Wavebox make any difference?
* Do you have any extensions enabled in Wavebox?
* Is this with Gmail or Google Inbox? (you mentioned both above, but I assumed Gmail)

Thanks

**Comment by rhuss** [comment]
@Thomas101 thanks for the quick response:

* Yes, I have this issues already since some weeks and the autocompletion fails reproducibly
* I have no extensions installed
* I'm using Google Inbox (see also issue title but I could have been more specific ;-)

**Comment by Thomas101** [comment]
Awesome thanks for the info, sorry, missed the title!

If you try re-adding the account or adding the account as a duplicate do you see any difference with that, or is it just the same? I've had contacts working on both personal and business accounts for some time, so wonder if some kind of caching/localstorage/cookie etc is to blame.

**Comment by rhuss** [comment]
Ok, let me try.

I have to mention that I have to use "Artifically Persist Cookies" option to come over our internal SSO for our business gmal account. 

Also probably worth mentioning is that it used to work with this setup ;-)

**Comment by rhuss** [comment]
Ah, re-adding the account helped, also after a restart with cookies to persists

Thanks a lot, I'm going to delete the old account as I can live with solution. I would reopen the issue if the error comes back ;-)

**Comment by Thomas101** [comment]
Enabling the `Artificially persist Cookies` does come with some caveats - this being one of them. With the setting enabled, you can right click on the account in the left and click `Clear All Cookies`. This will wipe all the ones it's artificially kept.

Just as a sidenote, there's been a few fixes into recent versions which means you might not need to artificially persist them. Depends on the SSO provider though
