### ISSUE TITLE
Lastpass Support

### ISSUE THREAD

**Issue by alexzneff** [wavebox/waveboxapp#488]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.6.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

I have not been able to get the Lastpass desktop application to work with Wavebox. Is support of Lastpass in Wavebox something in the works?

**Comment by TheWithz** [comment]
#138

**Comment by Thomas101** [comment]
Hi, Support for LastPass has been added to the 3.14.14 beta. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel)
