### ISSUE TITLE
Windows 10 - wavebox crash need verification - while getting notification

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#489]
* Which version of Wavebox are you using?
3.6.1beta

* Which Operating System are you using?
Windows 10 Fall creators edition

* Description:
Crash after notification using external link.

* Reproduce:
1. Have gmail, slack, etc but then also have facebook messenger as a weblink
2. Go to the gmail service and keep it in focus
3. Click Ctrl+§ to show the main menu
4. Keep Window menu item open
5. Recieve a message in facebook messenger and get a notification

3 out of 3 times I have gotten a crash in wavebox but do not know what process. Need to have someone to verify if it happens for them also. The important part seems to be to get the notification and having the menu open while getting the notification.

**Comment by Thomas101** [comment]
I've just given a try here, but with no success. Do you click on the messenger notification or does it happen when it launches?

**Comment by nmat** [comment]
Once the notification comes up and the menu is active the crash occurs.

I am using basic notification also if that might make a difference?

**Comment by Thomas101** [comment]
It could do, but I was using the same my end. Out of curiosity does switching to enhanced notifications change anything?

If you open Cortana search and type winver you'll get a box up with the windows product version. Just to check we match (or nearly match) I've got 1709, build 16299.64

**Comment by nmat** [comment]
@Thomas101 I will provide more information later on. At the moment ignore this request until I can reproduce it on another machine. Keep it open and I will close it if I can't reproduce after a few tests. Just need a bit more time. :)

**Comment by nmat** [comment]
I am going to close this issue for now. There are more important tasks that needs to be looked at. If I can somehow reproduce it and create a good guide on recreate I will reopen. Thanks for testing @Thomas101
