### ISSUE TITLE
GNOME Shell Notification Title

### ISSUE THREAD

**Issue by BenJetson** [wavebox/waveboxapp#49]
When I get a Wavebox notification, the lock screen shows it as "Electron" and shows an info icon instead of the Wavebox name and logo. 

![image](https://cloud.githubusercontent.com/assets/10427974/24886311/a819b15a-1e21-11e7-92bf-db0de7e59a68.png)

The GNOME Desktop documentation has more information about how their notification system works here: https://developer.gnome.org/notification-spec/

Hopefully there's some way to pass the `app_name` and `app_icon` parameters using Electron's notification API. 

I thumbed through the Electron documentation and tried to patch `NotificationService.js` to pass these along, but it didn't work. I also edited the `package.json` to include a `productName`, then recompiled, hoping it would correct the name at least. Unfortunately, neither of these worked. Maybe this is a limitation of the Electron framework.

Could you look into this and see if there's a solution? If you want me to test something, let me know. I can make changes and compile my own binaries if provided the relevant source.

#### System Info
Wavebox version 3.1.2
Ubuntu GNOME 16.04.2 (64bits)
GNOME Shell version 3.18.5

**Comment by Thomas101** [comment]
Oooh, that's an odd one. Just to double check does this happen with the precompiled Wavebox binaries as well as the ones you've built?

**Comment by BenJetson** [comment]
Yes, it occurs with the binaries downloaded from [wavebox.io](wavebox.io), any binary I build with `electron-packager`, and from directly running the source in the terminal via `npm start`.

**Comment by BenJetson** [comment]
I received the notification within the app to update to version 3.1.3 today and downloaded it from [wavebox.io](wavebox.io), expecting nothing to change. This problem would appear to have magically fixed itself. Wavebox now presents itself properly on the lock screen.

![image](https://cloud.githubusercontent.com/assets/10427974/24915317/d7b86cde-1ea4-11e7-9868-e257efa9c255.png)

I'm not sure which change between 3.1.2 and 3.1.3 corrected this issue, but thanks! :smiley:

**Comment by Thomas101** [comment]
I did update electron but there wasn't anything mentioned in the changelog. Glad it's fixed itself though :)
