### ISSUE TITLE
Ubuntu 16.04 Chinese word lost

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [wavebox/waveboxapp#491]
* Which version of Wavebox are you using? [e.g. 3.0.0]

version 3.6.0

![image](https://user-images.githubusercontent.com/13602602/33376781-fca29748-d549-11e7-952d-c70d659b2f8d.png)

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

ubuntu 16.04 LTS

When I try wavabox app in ubuntu 16.04, and could not see the Chinese word

![image](https://user-images.githubusercontent.com/13602602/33376880-64084f22-d54a-11e7-9279-1718ace1801c.png)

**Comment by satoshicano** [comment]
- version 3.6.0
- Ubuntu17.10

Japanese word too
![image](https://user-images.githubusercontent.com/7578069/33390063-2415b7f0-d578-11e7-8f64-3ed6cc3539bb.png)

**Comment by Thomas101** [comment]
Hi, have you installed via snap/ubuntu store? If you try with the [deb installer, repository or tar](https://wavebox.io/download) I think chinese & Japanese characters should work properly

**Comment by SuperSuperSuperSuper5** [comment]
@Thomas101 I'm install from the ubuntu software store, actually I was see the ad. in the ubuntu software store first page, so I decide to try this software.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
