### ISSUE TITLE
Links and Chrome Update

### ISSUE THREAD

**Issue by themiguelamador** [wavebox/waveboxapp#493]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.6.1beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS 10.13.2 Beta
Version 63.0.3239.70 (Official Build) beta (64-bit)

I have been noticing a strange error. When opening a link in the background, it open a new blank tab instead. However, when I notice this, I find an update of Chrome waiting to relaunch, and afterward, it is fixed. I thought it was a version problem, but it happened again with the next update. When it did download the update, everything works fine...

If not solved before, I will try to get a console log next time.

**Comment by Thomas101** [comment]
There is some kind of issue affecting High Sierra, Chrome and link opening which is affecting all apps built on electron.

There's a couple of extra things to try [here](https://wavebox.io/kb/high-sierra-chrome-links) such as changing your default browser, then changing it back which seem to help

**Comment by Thomas101** [comment]
I'm going to close this off, but if you're still seeing the issue feel free to re-comment and we can investigate further
