### ISSUE TITLE
[Request] Option to inject CSS/JS into the Wavebox UI

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#494]
Similarly to how we can inject for accounts ... any way to inject for the actual UI, i.e., "Wavebox Window"?

**Comment by Thomas101** [comment]
Not at the moment, but we'll have at look at adding it in. We use material-ui in the back end which is quite CSS unfriendly so not 100% sure how well it would work. Is this to fix #479 ?

**Comment by dzg** [comment]
>  Is this to fix #479 ?
Yes!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.1. You can find the setting under advanced. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
