### ISSUE TITLE
Autoclose download popup(dialog)

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#496]
* Which version of Wavebox are you using? [e.g. 3.6.2beta]

* Which Operating System are you using? [ Mac OSX HighSierra, ArchLinux]

after download file is done the popup window has to be closed manually, can we make it automatically or skip popup windows?

**Comment by Thomas101** [comment]
I'll have a look! Where were you downloading the file from (e.g. gmail, outlook, slack etc...)?

**Comment by reatlat** [comment]
@Thomas101 Just check it... It happened only on Slack

<img width="1338" alt="wavebox 2017-12-01 15-01-55" src="https://user-images.githubusercontent.com/9933516/33486000-c6834f94-d6a8-11e7-87b4-d4a821d2fb4f.png">

**Comment by nmat** [comment]
@reatlat it could be that there was a ghost window showing up during the download. If possible can you test in latest 3.6.3beta to see if the same effect happens there?

Does it happen on macOS and also on archlinux?

**Comment by nmat** [comment]
Tests done:

3.6.3beta - windows 10 - slack has a ghost window still showing
3.6.3beta - macOS Sierra 10.13.1 - slack has a ghost window still showing
GIT (2017-12-06) - windows 10 - slack still has a ghost window showing

This is still a issue with the slack account. Happens when clicking the download button. Even in sidebar of slack.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
wavebox: 3.6.4beta

Tested on windows 10 with slack - no phantom window and the popup goes away.

Same on slack for macOS 10.13.2 seems to fixed the problem. Perfect! :)

**Comment by reatlat** [comment]
wavebox: 3.6.4beta
macOS 10.13.2
Works perfect,
TY
On ArchLinux will test a bit late, but I think also should work perfect :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
