### ISSUE TITLE
Merge Navigation & extension toolbars

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#497]
* Which version of Wavebox are you using? [e.g. 3.2.6beta]

* Which Operating System are you using? [ Mac OSX HighSierra ]

the new green icon from Grammarly looks good on apps, but in webpage integration goes to second line

<img width="1245" alt="wavebox-inbox" src="https://user-images.githubusercontent.com/9933516/33465465-4af3e678-d648-11e7-9172-0bc4c0b97793.png">

<img width="1252" alt="wavebox-proposals-active-upwork" src="https://user-images.githubusercontent.com/9933516/33465469-4f28b5ac-d648-11e7-9f91-a4698033ed10.png">

**Comment by nmat** [comment]
Unfortunately I do not use Grammarly to be able to test this. 

@reatlat is it possible that you can test this quickly in new beta? Once the next stable release is out you can just choose stable in the dropdown again and it won't upgrade to beta on next beta after the stable is out.

**Comment by reatlat** [comment]
@nmat I always use latest BETA release :)
Version 3.6.3beta, gramarly still create new line :(

**Comment by nmat** [comment]
ah yes its in the git repo and not in the beta release.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.6.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
