### ISSUE TITLE
Screen share during meeting in Google Meet or Hangouts doesn't work.

### ISSUE THREAD

**Issue by eoset** [wavebox/waveboxapp#498]
* Which version of Wavebox are you using? 3.5.0

* Which Operating System are you using? Windows 10

The screenshare feature doesnt work while in google meetings. I can see other peoples screens but I cannot share. 

I did not research if anyone else reported same issue before.

**Comment by rajalokan** [comment]
* Which version of Wavebox are you using? 3.7
* Which Operating System are you using? Ubuntu 16.04

I'm also facing same issue. Not able to screenshare.

**Comment by eoset** [comment]
Hey, can’t remember which version it was. But I use windows 10

**Comment by drmikecrowe** [comment]
Confirmed:  New Win10 install same issue
Version 3.9.0
Wire Config Version: 1.2.0

**Comment by drmikecrowe** [comment]
Ditto on dual-booted Linux Mint
Version 3.9.0
Wire Config Version: 1.2.1

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"

Linux mcrowe-XPS-15-9560 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by drmikecrowe** [comment]
Now that Google has rolled out Meet to everybody (G-Suite admins need to enable it in domain settings), we now see this:

![Meet Video](https://www.diigo.com/file/image/rbepedczeoasooqdezdecberac/no+meet+video.jpg)

**Comment by Thomas101** [comment]
@drmikecrowe which OS is that on? If linux, how did you install Wavebox?

**Comment by drmikecrowe** [comment]
@Thomas101: `sudo snap refresh wavebox --channel=beta`

**Comment by drmikecrowe** [comment]
Also, when I run from command line, I see these logs:

```
[22827:0504/054449.170054:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
[22834:0504/054502.676328:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
[22834:0504/054503.042304:ERROR:audio_send_stream.cc(103)] Failed to set up send codec state.
```

**Comment by Thomas101** [comment]
With snap you have to manually connect some interfaces. Give [this a try](https://wavebox.io/kb/connect-snap-plugs) and see if it works afterwards

**Comment by drmikecrowe** [comment]
That definitely got the camera working

**Comment by Thomas101** [comment]
Thanks for taking the time to report, I'm merging this issue and a few others which report the same into #912 so we can track progress there and hopefully add support in. Thanks!
