### ISSUE TITLE
windows 10 - Empty window when loading a URL

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#499]
* Which version of Wavebox are you using?
3.6.2beta + GIT

* Which Operating System are you using?
Windows 10

* Description:
Opening links from gmail subject also open some kind of wavebox loading screen to open it in for example chrome.

On the stable versions I have seen it just flash when opening links but on GIT I can see it open all the time. (the flashy window happens on normal links sometimes also)

Its just a empty window. Couldn't this be in the background of wavebox instead of a flashy window?

* More information:
Winver: 1709 (OS Build 16299.64)

![image](https://user-images.githubusercontent.com/383031/33503777-4ba6d75e-d6e5-11e7-9388-13aee140d554.png)

The links that creates the window:
![image](https://user-images.githubusercontent.com/383031/33503972-f94f4882-d6e5-11e7-8cbf-9c0a82b04413.png)

**Comment by Thomas101** [comment]
Thanks! Managed to find out what this was. Also fixed the windows popping-up and then shutting down :)

**Comment by nmat** [comment]
wow! that was quick. Thank you!

**Comment by nmat** [comment]
tested in GIT and works perfectly. thank you again :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
