### ISSUE TITLE
Unread notifications not showing up for any apps.

### ISSUE THREAD

**Issue by LesterU** [wavebox/waveboxapp#50]
* Which version of Wavebox are you using? [e.g. 3.1.2]

* Which Operating System are you using? [Windows 10]

None of my apps (Office365, Google Inbox, Samepage.io (any website) are showing unread notifications. Any ideas why?

**Comment by Thomas101** [comment]
Hi, have you tried [these steps](https://github.com/wavebox/waveboxapp/wiki/KB:-Google-Unread-Counts) on your Google Account? Do you see any of the unread badges on the accounts in the sidebar?

**Comment by LesterU** [comment]
I have adjusted the Google Inbox settings and I am now getting unread badge for that account. But Im not getting any for my Outlook accounts. Also, is it possible to have unread badges for 'any website' such as Facebook etc?

**Comment by Thomas101** [comment]
If you restart Wavebox then go to View > Developer Tools and click on the console tab do you see any errors come out?

It's not currently possible to add unread counts for any website, they need to be integrated into Wavebox so we know what to display & when. We are working on adding some tools to do this easily and looking at a few other things like checking for a number in the page title, for example facebook sets the page title to be `(10) Facebook`. Is it samepage.io that you're using in the website tab?

**Comment by LesterU** [comment]
There are a few errors there...but they dont mean much to me! see attached screenshot. And yes, it is samepage.io we are using.
![screenshot 2017-04-13 09 55 35](https://cloud.githubusercontent.com/assets/27270261/24984242/8d9afd1a-202f-11e7-8751-6079e4ab3d38.png)

**Comment by LesterU** [comment]
The unread notifications have suddenly started working this morning for my Outlook accounts!

**Comment by Thomas101** [comment]
Thanks, by the looks of that something's not quite right over at Microsoft as it's failing their end. Lets hope they've patched this!
