### ISSUE TITLE
OS X: Restarting app in fullscreen mode does not work

### ISSUE THREAD

**Issue by mrmeku** [wavebox/waveboxapp#502]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.6
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX High Sierra

To reproduce make wave box fullscreen and then kill the app. When you relaunch the app you'll notice that it tries to go into fullscreen mode but instead does something funky where it takes up your entire desktop and doesn't have its resizing buttons

**Comment by nmat** [comment]
Hello @mrmeku,

When you say kill the wavebox. How do you mean you do that?

I want to see if I can reproduce it here. If you have a step by step guide that I can follow where it always occurs for you that would be great. I tried to have the application in fullscreen now using 3.6.3beta and then quit the app and start it but it goes to fullscreen just as normal.

So some more details here would help a lot. Thank you :)

**Comment by Thomas101** [comment]
The fullscreen behaviour on macOS can be different depending on how mission control is configured. Would you be able to send a screenshot of how you have that setup from System Preferences?

**Comment by mrmeku** [comment]
You fixed it with the latest release! Congrats
