### ISSUE TITLE
Linux: Compose New Message doesn't open a Wavebox window

### ISSUE THREAD

**Issue by WebShapedBiz** [wavebox/waveboxapp#503]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.6.2beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
ElementaryOS Loki 0.4.1.

When I click "Compose New Message" on tray icon nothing happens, but afterward, when I click Show/Hide the application window pops up with a modal window asking me to choose the account for sending an email.
This was not an issue in previous versions of Wavebox.

**Comment by nmat** [comment]
@WebShapedBiz Can you please provide how the application is installed? (deb, snap)?

Could you also test to update to version 3.6.3beta? Since there are lots of work going into the window opening features in the latest betas.

**Comment by nmat** [comment]
@WebShapedBiz Can you please test this in the 3.6.4beta? Its released now for testing

**Comment by WebShapedBiz** [comment]
Sorry @nmat, again using a deb file, the issue is still present.

**Comment by Thomas101** [comment]
@WebShapedBiz how many accounts do you have added into Wavebox and what are they? E.g. 1 Gmail, 2 Slack... etc

**Comment by WebShapedBiz** [comment]
@Thomas101 I have two Gmail accounts.

**Comment by andersodt** [comment]
I have this exact same problem -- except on Mac 10.13.1. Additionally, none of the other items will open the Wavebox window either (Open Account, clicking on a specific message, etc).

**Comment by Thomas101** [comment]
Perfect the video really helped! I've patched and it will be in the next beta :)

**Comment by WebShapedBiz** [comment]
Thank you @Thomas101

**Comment by Thomas101** [comment]
A fix for this has just gone out in version 3.6.5 beta :)

**Comment by WebShapedBiz** [comment]
Confirming that fix works on Linux :-)
Thank you @Thomas101

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
