### ISSUE TITLE
Restore file locations wiki page

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#504]
Wiki page: https://github.com/wavebox/waveboxapp/wiki/KB:-Copying-Accounts

It now links to a page instructing you how to import and export data. But I'd like to be able to reference where the data is stored as the new wiki page assumes you used the built-in export function as oppose to backing up your disk manually.

**Comment by Thomas101** [comment]
We're moving off from the Github wiki, but I think the articles you might be looking for are [here](https://wavebox.io/kb/data-locations) and [here](https://wavebox.io/kb/install-locations)

**Comment by Naatan** [comment]
Thanks @Thomas101 !
