### ISSUE TITLE
UI is massive on 166 DPI Display

### ISSUE THREAD

**Issue by hackel** [wavebox/waveboxapp#505]
I just installed the Wavebox snap from GNOME Software on Ubuntu.  The UI is massive.  I'm using a 13" 1920x1080 screen, which means I need to increase font scaling to 2.52x to get proper font sizes (72 pt === 2.54 cm).  It seems that your app must be picking up on this and scaling the entire UI 2x along with it.  The display is only 166 DPI, which I don't think even qualifies as "HiDPI," but the problem is along those same lines.  The in-app zoom feature does not work at all.

![screenshot from 2017-12-13 15-22-24](https://user-images.githubusercontent.com/583677/33963155-e10c14fc-e04b-11e7-9943-4ae171b0678c.png)

* Which version of Wavebox are you using? 3.6.0
* Which Operating System are you using? Ubuntu 17.10

FYI—Chromium exhibits the same issue.  In Firefox, I have to set layout.css.devPixelsPerPx to 1.25.

Edit: I can run `wavebox --force-device-scale-factor=1.25` to make the app display a little more sensibly.

**Comment by Thomas101** [comment]
Ooh, that's not right! If you try with the [tar/deb builds](https://wavebox.io/download) do you see the same thing, or is it just with the snap packages?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
