### ISSUE TITLE
Feature request: Ability to add border in sidebar to divide work and private connections (like macOS borders to divide applications)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#508]
* Which version of Wavebox are you using?
3.6.5beta

* Which Operating System are you using?
Windows 10 and macOS

* Description:
On the bar it would be nice to be able to add some kind of divider or border to divide (these are work connections) and (these are private connections) much like adding borders to divide applications in taskbar on macOS

**Comment by Thomas101** [comment]
That's a great idea actually!

**Comment by GreyCorbin** [comment]
It would be nice if it went a step or two farther and allowed you to name those groupings and then choose to display icons by group.

**Comment by nmat** [comment]
Yeah I think this can be closed. There is so many other things that can be done now. Thank you!
