### ISSUE TITLE
Google Chrome v63 not supported in Wavebox

### ISSUE THREAD

**Issue by pushontom** [wavebox/waveboxapp#509]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.6.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04.3 LTS

![image](https://user-images.githubusercontent.com/6860461/34036899-995359e8-e17e-11e7-9d8b-e9fc3aeb39f9.png)

Chrome has recently updated to v.63. Wavebox app most likely needs an update to stop the above error from occuring. 

Please see same issue that I raised on teams-ubuntu that has now been resolved: https://github.com/leftstick/teams-ubuntu/issues/9
https://github.com/leftstick/teams-ubuntu/commit/1fd4787e4b59dd98e684c8affaa421b950fcffee

**Comment by Thomas101** [comment]
Added a fix for this in the next release. If you want to get it working right away you can try this...

1. Right click on your account and go to `Account Settings`
2. Enable `Use Custom UserAgent`
3. In the `Custom UserAgent String` field paste... `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36`
4. Restart Wavebox

![screen shot 2017-12-15 at 10 40 56](https://user-images.githubusercontent.com/103586/34038521-91881982-e184-11e7-90b2-6537e2730b53.png)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.7.0). You may need to re-add your teams account through the add screen and picking teams from the list.

You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by nmat** [comment]
I updated to version 3.7.0 but that did not solve login it seems.

Also tested to do the custom user agent and still can't sign in. Am I missing something?

**Comment by Thomas101** [comment]
@nmat did you use the "Any Weblink" or "Microsoft Teams" account type?

**Comment by nmat** [comment]
MY BAD! I tested using the account type now and that works perfectly! Thank you! :)
