### ISSUE TITLE
Windows 10 - links opens in wavebox browser no matter what is set

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#513]
* Which version of Wavebox are you using? 
3.7.0

* Which Operating System are you using? 
Windows 10

* Description:
All links open in wavebox browser no matter what is set in the browser under account settings.

Right click and selecting "Open page in Browser" works though.

**Comment by Thomas101** [comment]
Which account type is this with?

**Comment by nmat** [comment]
Interesting......I just chose to use default browser in office365 and gmail and all of a sudden the default browser is used.

(I noticed office365 had wavebox browser as default) seems very random.... :/

**Comment by nmat** [comment]
Closing this. Seems to be random. If I encounter it again I will reopen.
