### ISSUE TITLE
Need verification: #511 - Save state of hide/show on next startup

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#515]
* Which version of Wavebox are you using?
3.7.0 GIT master

* Which Operating System are you using?
Windows 10

* Description:
On hide or show, should the state be saved on next run?

At the moment I only tested to do a quick start from npm and the state of last hide or show is not saved. Instead it goes back to be showing.

**Comment by Thomas101** [comment]
At the moment we've decided not to save the state. Happy to get some feedback on this though!

**Comment by nmat** [comment]
IMO I would like to pick this up again.

From my head and experience with other applications I would say that the last state of hide or show should be used for this part. Mostly because it makes the window a bit more dynamic and user specific.

Else I would say close this issue.

**Comment by nmat** [comment]
Verified working on windows 10 1803 (OS Build 17134.167) and macOS 10.13.6

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Verified on macOS and Windows 10. Looks good. Closing issue.
