### ISSUE TITLE
Feature Request: Skype for Business

### ISSUE THREAD

**Issue by rajalokan** [wavebox/waveboxapp#516]
* Which version of Wavebox are you using? [e.g. 3.7.0]

* Which Operating System are you using? [Ubuntu 16.04]

Would love to have support for Skype For Business. Thanks

**Comment by nmat** [comment]
Hello @rajalokan,

Please see: https://github.com/wavebox/waveboxapp/issues/130

Its a summary ticket of service voting to be implemented.

**Comment by rajalokan** [comment]
Thanks. I see it is there in your plans. Please go ahead and close this issue if it is alright. Else I will close in some time. Thanks again.

**Comment by nmat** [comment]
You can always add a comment for the services you want to vote up. Its always good to see what people want more. :)

Also I do not have rights to close issues. If you feel like this ticket can be closed then please close it. Otherwise let the developers have a look :)
