### ISSUE TITLE
Wavebox : Email Auto-validated + Link not opening in browser

### ISSUE THREAD

**Issue by Jul313** [wavebox/waveboxapp#517]
Hi,

I have some emails arriving in Wavebox/Inbox that get directly in the Validated/Terminated folder not having chance to see it in my inbox. How is that possible? How can we handle this problem?

I also can not open links in email directly in the browser. It just open a new browser white window, not the link address itself.

Thanks for your precious help.

* Which version of Wavebox are you using? [e.g. 3.6]
3.6 Beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OSX10.13

**Comment by Thomas101** [comment]
Hi, there's an issue with High Sierra and Chrome which causes this. Can you try the steps in this [KB Article](https://wavebox.io/kb/high-sierra-chrome-links) they seem to fix the problem for most users

**Comment by Jul313** [comment]
I'll try this one. Tx.

What about my email au-validated?

I also have problem with unopened email counter not reflecting the reality.

Tx Thomas

**Comment by nmat** [comment]
@Jul313 Can you please say what service this is happening too?

If its gmail have you checked: https://wavebox.io/kb/google-unread-counts ?

**Comment by Thomas101** [comment]
As for the email validation, which account type is this with and is the behaviour different when you use gmail/google inbox/outlook etc in the browser?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
