### ISSUE TITLE
notification only show in the left monitor not the right one

### ISSUE THREAD

**Issue by weibo053** [wavebox/waveboxapp#519]
Hi 
The notification only shows in the left monitor not the right one. I cannot anything which can configure this. 
Can you help me out of this? Thanks.

* Which version of Wavebox are you using?  3.6.0
* Which Operating System are you using?Ubuntu 16.04

**Comment by Thomas101** [comment]
Hi, if you go into your Wavebox Settings, under the Notifications section there's a `Notification Provider` dropdown. What do you have selected here?

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
