### ISSUE TITLE
Custom CSS doesn't take precedence

### ISSUE THREAD

**Issue by russtaylor** [wavebox/waveboxapp#520]
* Wavebox 3.7.0
* Running MacOS 10.12.6

I've taken multiple styles from Stylish, which then require heavy modification to take effect in Wavebox. The styles take precedence with Stylish, but using the 'Custom CSS' in Wavebox, each and every rule requires `!important` in order to take effect. 

It would be very nice if the Custom CSS would _override_ existing CSS by taking precedence over it.

**Comment by nmat** [comment]
Hello @russtaylor,

If possible and you can. Then you can test this the git version where the commit: https://github.com/wavebox/waveboxapp/commit/5e035e00782fe47a88ecf4f9e5a32436e72d2bb5

has been deployed. I wonder if that will fix the issue you are reporting here.

**Comment by Thomas101** [comment]
This is a fair point. The custom css styles get injected along with the browser styles which gives it the lowest precedence. For any large amount of customization it's going to make it very `!important` which isn't ideal. I'll see what we can do around this

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by russtaylor** [comment]
I'll give it a go. Thanks so much!

**Comment by russtaylor** [comment]
It's working beautifully! No more need for `!important` on every CSS rule. 

Thanks again. Wavebox is an awesome product, and this just makes it even more so.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
