### ISSUE TITLE
Gitter container loses state on refresh

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#523]
* Which version of Wavebox are you using? 3.7.1

* Which Operating System are you using? macOS 10.13.2

I recently setup Gitter using the new Gitter app link. Once I'm logged in it works fine, but it loses my state any time its container refreshes or WaveBox restarts. I'm not fully logged out; although I end up back at the "Sign in" view, simply clicking "Sign in with GitHub" takes me back to my account (it doesn't actually make me actually sign in again).

My expected behavior (which may or may not be the intended behavior) is that, whenever the Gitter container refreshes or WaveBox restarts, I end up in whatever room I was last in.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I've just pushed an update out which shouldn't drop you at the login screen again. You can get it by just restarting Wavebox, or if you wait a while it will grab the update itself.

As regards remembering the the last room, we'll try to add that into the next release

**Comment by jason0x43** [comment]
Awesome, that's definitely an improvement.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by jason0x43** [comment]
The "Restore last page on load" toggle?

**Comment by Thomas101** [comment]
That's the one. It should be enabled by default on gitter

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (3.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
