### ISSUE TITLE
Wavebox refuses to run if .exe clicked twice by mistake

### ISSUE THREAD

**Issue by Champenoislevrai** [wavebox/waveboxapp#525]
3.7.1b  Which version of Wavebox are you using? [e.g. 3.0.0]
win10, 64bit  Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

This has been happening for months, sometimes I forget that the taskbar program icons need one click to start.
Now and again I do a quick succession double click on wavebox by mistake.
Two processes appear in the task manager and wavebox will not run, clicking the taskbar icon again just results in another process adding to the list.
I can't kill the processes even though I am an admin, something to do with the latest win10 updates I think.
If I use an elevated command prompt and do a force kill using the exe program name, the PID's for the problem processes suddenly appear listed saying "do not exist"

A restart or quick turn off and on results in the stuck PID's still showing.
Finally the only way out is to shut down, turn off the pc, wait a while and restart

**Comment by nmat** [comment]
Is it only wavebox this happens too?

If you need to restart the pc completely it actually sounds very strange.

If possible also can you see if the same thing happens if wavebox is installed on a different account on the PC?

And can you run a: winver on the run command to get the complete windows 10 version?

**Comment by Champenoislevrai** [comment]
only ever wavebox has done this
the last time it happened, the other day (I usually don't restart for weeks
because of this), the PID's kept coming back even after shutdown, it was
only when I left it off for 5 mins that all was clear when I restarted.
It USED to be that when I doubled clicked by mistake, I could go into >
task manager > details and kill the pids ok.
I've even sat there and watched as I click the taskbar icon of wavebox and
watch a new pid appear, up to 8 one day, but nothing will run
But now I can't it says refused or similar.. but that's also where the
elevated CP lists the pids! and says they don't exist (force kill
wavebox.exe)

Truly I'd rather not create another account, I'll just put up with it

Everytime I update win10 lately, more obscure programs disappear and have
to be reinstalled

The only exception to the system is its running under test mode because a
major program I use didn't have an ms certificate for install so I had to
turn that certificate check off.

Thank you for replying

[image: Inline images 1]


Pic attached.

Envy23, 16gb ram

**Comment by nmat** [comment]
Can you test the steps I mentioned before?

I do understand its frustrating and I am trying to help.

**Comment by nmat** [comment]
What I mean with another account is a new login to the PC. If the machine has been upgraded etc several times and even more so if the PC has been upgraded from Win 8 -> 10 without a proper reinstall (as microsoft recommends reinstall on major version) it can cause the login to be bad with appdata.

Also you can try to reinstall wavebox and clear out the appdata information to be able to see if that helps.

**Comment by Champenoislevrai** [comment]
ok, leave it with me please and I'll come back to you, if no-one else is
reporting it then that's good.

I got ahead of that 8 > stuff, I reformatted the drive and did a whole new
setup, it solved problems, the only other thing I now remember is that now
and again I come across a file that is special permissions protected that I
can't delete (which I could before).
Windows... :(

Thank you

**Comment by nmat** [comment]
Please do inform if you do get the issues again. I have been running windows 10 on 2 different machines on 2 different winver's and never had this issue.

There are some issues at some points with electron that for example causes there to be several different items of the same kind in taskbar settings. Not sure why this happens but other apps has that as well.

**Comment by Thomas101** [comment]
I've done a little bit of digging on this. I managed to reproduce it under one set of conditions. I wonder if they match your machine setup?

- Windows 64 bit
- 32-bit version of Wavebox
- Pin Wavebox to the taskbar and keep hitting launch

When I tried with Windows 64 bit and Wavebox 64 bit, I could hit launch as many times as I liked and it seemed to work as you'd expect. It might be worth checking which version you installed. I think if it's 32-bit wavebox all the processes will be listed with (32-bit) after them. Although the 64-bit distro does have a few 32-bit processes too so it can be misleading.

**Comment by Champenoislevrai** [comment]
Thanks for keeping trying on this
The process does not show 32 bit, so i guess it is 64 (there a number of
others that are. so it does list as you describe)
I'm always careful about getting a 64 bit if it's produced.
What you are describing is exactly what happens to me, it's just that all
files are set to 2 clicks so I get a bit confused/habit on the task bar.
Things got a lot worse when I couldn't delete the pid's.

So seeing we are talking about the exact same behaviour, somehow it is also
happening with 64 bit in my environment!

I have 19 accounts and 26 pid's currently running in case that mean
anything, and all is running fine at the moment.

**Comment by Thomas101** [comment]
It might not be the same issue I was seeing. I'll keep digging to see if I can reproduce with 64 & 64.

It might be useful to know which version of windows you're using. If you type `winver` into Cortana Search, a program will come up called winver. Run this, it will bring up a dialog with some more info about the version you are using. In there somewhere there should be something like `Version 1703`. Would be handy to know what this is, I can try and load a test vm with it

**Comment by Champenoislevrai** [comment]
Hi Tom.. we're into a big loong win update now.
I sent you a winver screen pic in the first reply.

Thank you

⁣Sent from Blue ​

**Comment by Thomas101** [comment]
@Champenoislevrai I don't seem to have that in the conversation thread. Not sure the attachments have come through to Github. Can you send again? (You may need to upload from the web interface - sorry!)

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks

**Comment by Champenoislevrai** [comment]
Hello Thomas,

Greetings, sorry, I should have been back to you before.

I've just finished resetting up win 10 clean on a new ssd disk for both my
main pc and my laptop.

It's early days but Wavebox is working many times better, including the
problem I had with a lot of accounts loading slowly at the same time at
startup and then being almost unresponsive until each one was individually
reloaded.

I haven't clicked the wb.exe twice though, so I can't report on whether
that has disappeared, but I suspect it has..

I suspect that although the old hard disk passed all checks, it was so slow
that it was causing the problems.

Regards, John

**Comment by Thomas101** [comment]
Great to hear it's working again and working better with a ssd disk! There's been a bunch of performance fixes that went into the latest releases which may help too :)

**Comment by Champenoislevrai** [comment]
tks, forgot to say that wb is running and loading all accounts ~10x faster;
some pc programs/jobs are as much as 20x faster..
