### ISSUE TITLE
Menu Bar item does not indicate Trello, displays full name and username

### ISSUE THREAD

**Issue by celina** [wavebox/waveboxapp#527]
* Which version of Wavebox are you using? 3.7.2beta

* Which Operating System are you using? Mac OSX 10.12.6

**Issue:** The Menu Bar shows the full name of the Trello profile and username. Trello is not indicated in the list item: 
> (Full Name) username

![wavebox-menu-trello](https://user-images.githubusercontent.com/58040/34415616-59206ffa-ebb5-11e7-99f9-04fcf6096988.png)

**Resolution:** Display the name of the service instead of the full name (it is assumed that I know my full name and my full name will not be unique across multiple Trello accounts):

> Trello username
> (Trello) username

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.7.3. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
