### ISSUE TITLE
Microsoft Teams - add unread count & notification support

### ISSUE THREAD

**Issue by NullpointerForever** [wavebox/waveboxapp#528]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.7.2beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

Hi,

With my Microsoft Teams account, counter of the unread messages from chat is not working.

Regards

**Comment by nmat** [comment]
@NullpointerForever where do you mean exactly it is not working?

Microsoft teams is a integration that has not a 100% support yet with notifications. And services that is a non major service is not going to be visible in the tray icon since it will only get the unread count from major services.

**Comment by Thomas101** [comment]
We're going to be adding teams as an integrated account in the future which will include notification and badge support. There's more info on the difference between the two account types [here](https://wavebox.io/kb/account-types)

**Comment by blakejwc** [comment]
Has this been included in version 3.9?  I'm using 3.10 on Ubuntu 14.04 and haven't seen any changes to Teams notifications.

**Comment by Thomas101** [comment]
Not as yet, aiming to get this out with 3.11 though

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by rajalokan** [comment]
Hi. Thanks for this but I just installed latest ( 3.11.0) and don't think desktop notification for microsoft teams is proper yet. I'm on Ubuntu 16.04. 

I can verify in account settings `show notifications` check is ON. Anyplace else I should look to configure to ensure I have unity desktop notifications for my chat or messages. 

The unread counter in indicator works though. Thanks

**Comment by Thomas101** [comment]
Ah yes, sorry closed this off prematurely. It's just the badge support that's been added in so far

**Comment by rajalokan** [comment]
Hi Guys. Any updates on this? Didn't find this in 3.14.7.

**Comment by nmat** [comment]
Hmmm could this be prioritized in some way? I find the window where the notification is coming up on top of message box really disturb my work a bit. (not to bad, but still annoying having a window covering the message box when typing)

**Comment by nmat** [comment]
I noticed today that I got question from the teams web client using wavebox to turn on desktop notifications. Right now it just says "Wavebox notification" so I guess that the client for the web has turned on notifications much like the messenger to be able to send notifications to user desktop. Which is really great.

**Comment by nmat** [comment]
![image](https://user-images.githubusercontent.com/383031/49431154-134cc000-f7ad-11e8-8ab3-40b5e3971332.png)

This also means that a popup comes on the desktop. This helps in the way that no notification is showing above the conversation line so you do not have to care about text being hidden behind a in window notification. Still its nice in the way that capturing the notification when turned on might be possible. A few things to note:

1. You can't click the notification in order to go to the message
2. No message preview

**Comment by nmat** [comment]
Another screenshot of the question:

![image](https://user-images.githubusercontent.com/383031/49438427-9a566400-f7be-11e8-95e3-47fc9a461430.png)

**Comment by nmat** [comment]
is there any plans on catching the notifications for teams in a more readable and more integrated format? :)

**Comment by Thomas101** [comment]
I've just given this a try and it looks like teams has added html5 notification support. It should be creating sensible notifications...


![Untitled](https://user-images.githubusercontent.com/103586/54935353-0bf62180-4f18-11e9-8144-d315202a9cff.png)
![Untitled 2](https://user-images.githubusercontent.com/103586/54935358-0dbfe500-4f18-11e9-9fc4-e570bce0872c.png)

**Comment by Thomas101** [comment]
Maybe try clearing browsing data for the account to see if it grabs an updated version of the code will help?

**Comment by nmat** [comment]
Windows 10 test.

I tested this now and cleared browse data. Which only gives me the 

"Wavebox"
"New notification"

But no details like you see. Could it be that you are using enchanced notifications of some kind?

**Comment by Thomas101** [comment]
>  Could it be that you are using enchanced notifications of some kind?

I've done nothing more than just add the account :-/. I've had a look around teams settings but can't find anything there either.

Maybe try adding it as a standalone account? It's definitely weird!

**Comment by nmat** [comment]
I tested now to remove and add the teams account again and nothing changed.

I still get a popup saying "New notification" but not any information more inside it. The account is running as its own service in wavebox.

Version of wavebox: 4.8.4

Should I try to clean up everything? like a reinstall of wavebox?

**Comment by nmat** [comment]
Also tested now to clear all browser data and login again. + using latest beta.

Result seems the same though. Not sure what is going on.

**Comment by Thomas101** [comment]
Think I've found it. Teams sends an icon in the format `blob:https://theurl....`. On Windows this causes a failure further down and the end result is `New Notification`. I'll just put a guard in for this :)

**Comment by nmat** [comment]
OF COURSE it does! Doh! haha.....I am willing to test it further when its in place on master :)

**Comment by Thomas101** [comment]
@nmat [4.9.0](https://github.com/wavebox/waveboxapp/releases/tag/v4.9.0) has got a fix for this :).

Am I okay to close this issue off? Notifications & badges should be working now

**Comment by nmat** [comment]
Looks good! I have tested it here and I can also click the notification to get to the conversation.

This is ok for me to close since:
1. I get the notification count
2. I get the notification popup
3. Don't get a popup inside the wavebox that hovers over the text box

So I would say close it.
