### ISSUE TITLE
Hangouts opens in a browser tab

### ISSUE THREAD

**Issue by walgenbach** [wavebox/waveboxapp#53]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.3

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

In wmail, opening a video chat in hangouts used the wmail window. Now it opens the video chat in a new tab in my browser window. Nothing special is done to reproduce this issue, as it happens ever time.

**Comment by Thomas101** [comment]
It looks like google have added a new url which wasn't being picked up. I've added this in so it should work in the next release. Thanks!

**Comment by Thomas101** [comment]
This has been added into 3.1.4 which is now live, thanks!

Wavebox should update automatically after a while, but if you want to hurry it up, just restart the app and it will re-check
