### ISSUE TITLE
Gitter notifications

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#530]
I have Gitter configured to notify me for all messages, and I configured my Gitter account in Wavebox to show the unread activity badge, but Wavebox almost never shows the badge. Is there something I'm missing, or is this not expected to work yet?

* Which version of Wavebox are you using? 3.7.2
* Which Operating System are you using? Mac OSX 10

**Comment by Thomas101** [comment]
As Gitter is only a linked account it uses html notifications to detect activity. The behaviour that you should see, is when Gitter presents a notification an unread dot should appear. This will then be cleared either when you switch to Gitter, or you focus the window.

I'll look to see if we can scrape any info out the UI and display it for this and also #528

**Comment by jason0x43** [comment]
Yes, that's what I would expect to happen, and it has once or twice, but not consistently. Of course, that's assuming Gitter is actually being consistent about emitting desktop notifications. I have the "Show notifications" Wavebox switch turned on, and Gitter is set to notify me for all messages (both in the room and as the default).

One bit of potentially UI data I noticed when using a generic web link for Gitter vs the more specific app link is that Gitter would update its favicon when I had new messages.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by jason0x43** [comment]
Gitter notifications are still seem to be spotty at best. I generally get notifications when someone mentions my name, but not always. The icon badge only rarely updates.

Will my currently installed Gitter container be updated to whatever the latest version of the Gitter container is when I update WaveBox (assuming there's a dedicated Gitter container), or would I need to remove and re-create the account?

**Comment by Thomas101** [comment]
Have you got the account setup to sleep at the moment? Notifications will only come through when it's awake. For the count we've been using `document.title` to grab the current unread - we might need to look at a deeper integration for this as it does seem a bit spotty.

The container accounts (which Gitter is one of) will update automatically. If you right-click on the account in the left and go to `Account Settings`, right in the bottom right it will give the Container version. 5 is the current one for Gitter

**Comment by jason0x43** [comment]
It's not setup to sleep, and it looks like I do have the latest Gitter container, so nothing weird there.

I just woke up my laptop a few minutes ago and resynced Gitter. The popup next to the Gitter icon said "No unread messages". However, upon selecting the Gitter container there were two new messages, and one of which mentioned me.

**Comment by Thomas101** [comment]
I wonder if it's something to do with our parsing then. Next time this comes up can you grab the title of the Gitter page? You can do this by going to View > Developer > Developer Tools (or <kbd>Cmd</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd>) and then typing `document.title`

**Comment by jason0x43** [comment]
This does seem to be the case. I don't get notifications for the focused room regardless of whether Wavebox is focused or not, but I do get notifications for other Gitter rooms I'm subscribed to.

**Comment by Thomas101** [comment]
I think this may be the way that gitter are pushing notifications. As it stands at the moment we use the document title to get the unread count. Notifications are just opened as gitter attempts to present them.

Just to make sure we're on the same page, when you talk about notifications, do you mean the unread count in the red circle, or the desktop notifications that come up with the message content?

When you stopped getting notifications was the room count in gitter itself stll updated?

**Comment by jason0x43** [comment]
The badge only ever seems to update when I get desktop notifications, and I only get those for background rooms, not the one I'm actually in.

I suppose the existing behavior makes some sense -- the Gitter web app can't tell that Gitter has been backgrounded in Wavebox, so it won't know that it needs to emit notifications for the focused room. Ideally there should be some API for telling Gitter that the browser is unfocused.

**Comment by jason0x43** [comment]
Well drat, apparently that wasn't the issue. I just switched to my gitter container. This is the activity in some of the rooms I'm in:

<img width="121" alt="screen shot 2018-06-04 at 11 08 16" src="https://user-images.githubusercontent.com/1042866/40925441-b93670a2-67e7-11e8-956c-2ad147211041.png">

However, I haven't gotten any notifications, and Wavebox's badge didn't update (no badge was added).

**Comment by Thomas101** [comment]
Okay, I think I can see what's happening here. We're using the `document.title` to pull the unread count in these, but Gitter isn't consistently placing the count there. For example...

1. Login, `document.title="Explore - Gitter"`
2. Click *All Conversations* `document.title="Explore - Gitter"`
3. Click into any conversation `document.title="➄ testing123ggg/test2 - Gitter"` - the count is now updated

Now when you navigate around the count sticks in the title, but doesn't get updated.

I'll have a look to see if there's anything else we can pull out or anything in the dom that gives a hint to the count

**Comment by jason0x43** [comment]
There is a decent bit of info in the DOM, specifically in `#room-menu__panel`. That contains the user's room list, with entries having classes `room-item` or `room-item--favourite`. Each of those has an activity indicator div that shows whether the room has activity (via the presence of a `has-activity` class) or has a specific count of unread messages (with a `has-unread` class and contained value).

The panel is always rendered, so it should be easy enough to poll it. Hmmm...is there any way for custom user scripts to manipulate the main UI?

**Comment by Thomas101** [comment]
There are some APIs that let you write into the badge etc. If you want to have a play around, give this a try...

1. Don't add Gitter through the AppStore, but instead through the `Add any website` button
2. Go into the account settings and turn on the `Enabled Wavebox API` setting
3. From there, `window.wavebox` will be exposed to the page. There's some info about what you can do from there in this pdf... [guest_api.pdf](https://github.com/wavebox/waveboxapp/files/2075278/guest_api.pdf)

When you're writing code, you can use <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> to bring up the dev tools for the current tab and the customJS button to inject the code into every page for that account on a more permanent basis

**Comment by jason0x43** [comment]
Oh yes, this works very well:

```js
setInterval(() => {
  const count = getUnreadCount();
  wavebox.badge.setCount(count);
  if (count === 0) {
    wavebox.badge.setHasUnreadActivity(hasActivity());
  }
}, 5000);

function getUnreadCount() {
  const unreads = Array.from(document.querySelectorAll('.room-menu .room-item__unread-indicator.has-unreads'));
  return unreads.reduce((total, node) => total + Number(node.textContent.trim()), 0);
}

function hasActivity() {
  return document.querySelector('.room-menu .room-item__unread-indicator.has-activity') != null;
}
```

**Comment by Thomas101** [comment]
Are you happy to open a PR and contribute that to the [wavebox-user-scripts](https://github.com/wavebox/wavebox-user-scripts) repo? If so I can pull it in from there and add it to the default Gitter app

**Comment by jason0x43** [comment]
I would definitely be happy to do that, but I’m on vacation (and away from a real computer) for the next couple of weeks, so there’ll be a bit of a delay.

**Comment by jason0x43** [comment]
PR created: https://github.com/wavebox/wavebox-user-scripts/pull/22

**Comment by Thomas101** [comment]
Awesome thanks. I've pulled that into the one the in the apps tore so just adding it via the Gitter button should work :). Can you drop me a quick message over on our [contact page](https://wavebox.io/support) when you get a chance 😀

**Comment by jason0x43** [comment]
> Can you drop me a quick message

Sure, what about?

**Comment by Thomas101** [comment]
Just want to send some Wavebox swag your way to say thanks :-)
