### ISSUE TITLE
提两点建议

### ISSUE THREAD

**Issue by SZooo** [wavebox/waveboxapp#532]
version：3.7.0

Operating System：Ubuntu 16.04

1. 希望支持中文。
2. 希望可以设置网络端口，方便“翻墙”。

**Comment by nmat** [comment]
@SZooo regarding the suggestions. Is it that you want the application in chinese or the characters that is not supported in general?

To be able to change the port for firewall, not sure I think that it uses standard ports based on the service if I am not completely wrong. @Thomas101 might be able to shed some light into that?

**Comment by Thomas101** [comment]
We are working on more language support - Chinese being one of those. As for network configuration, Wavebox responds to the same command line arguments as chromium so you can configure a proxy server on launch. There's some more info on how to do that [here](https://www.chromium.org/developers/design-documents/network-settings) but in general, running it as `./Wavebox --proxy-server="foopy:8080"` should do the job

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
