### ISSUE TITLE
3 dots for moving emails don't work with multiple emails selected--3.7.3-1 beta on Ubuntu 17.10

### ISSUE THREAD

**Issue by thanosgatos** [wavebox/waveboxapp#533]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.7.3-1 beta
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 17.10

After the latest update, when selecting multiple emails in Inbox and try clicking on the 3 dots to move them to a different folder, instead of getting the folder menu, the collection you have open (eg. Promos) collapses again, as it originally looks before you click on it.

This is preventing the user from moving multiple emails around at the same time and should be addressed as soon as possible if it is indeed an issue.

**Comment by Thomas101** [comment]
Hi, would you be able to send a screenshot? This is what I tried and it seemed to work as expected....
![screen shot 2018-01-15 at 10 40 54](https://user-images.githubusercontent.com/103586/34938546-a7532846-f9e0-11e7-922b-94534d38014a.png)

A few things that might help...
1. Right click on the Account in the left and then click reload
2. Check to see if you see this issue in the web browser or if it's specific to Wavebox

**Comment by thanosgatos** [comment]
Sorry for not getting back to you earlier. This happens also in Chrome, as you suggested. The 3 dots are not even clickable. I would guess this is not a Wavebox related issue.

**Comment by Thomas101** [comment]
Might be worth posting up on the [Inbox Product Forum](https://productforums.google.com/forum/#!forum/inbox). Someone at Google might not be aware of the issue
