### ISSUE TITLE
Delete account does not prompt for confirmation

### ISSUE THREAD

**Issue by maroc81** [wavebox/waveboxapp#534]
* Which version of Wavebox are you using? 3.7.3

* Which Operating System are you using? Ubuntu 16.04

I accidentally deleted an account when trying to access account settings from the side bar right click menu.  A confirmation before deleting would help with accidental clicks.  Especially since account settings and delete are next to each other.

**Comment by Thomas101** [comment]
Now we've moved some of the buttons from the sidebar it is a lot easier to hit delete by accident. We'll add a confirm

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by maroc81** [comment]
Just gave it a try.  Looks good.  Thanks!
