### ISSUE TITLE
Extensions not appearing in toolbar

### ISSUE THREAD

**Issue by amancevice** [wavebox/waveboxapp#535]
* Which version of Wavebox are you using? [e.g. 3.0.0]

`3.8.0`

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS `10.13.2`

After updating to `3.8.0` the extensions no longer appear in the toolbar. I only have 'Markdown Here' installed, but its gone. Downgrading to `3.7.0` returns it to the toolbar.

**Comment by amancevice** [comment]
<img width="1620" alt="screen shot 2018-01-15 at 3 03 42 pm" src="https://user-images.githubusercontent.com/157711/34959686-9891f466-fa05-11e7-9fff-e6653a73f9a7.png">
<img width="1612" alt="screen shot 2018-01-15 at 3 04 36 pm" src="https://user-images.githubusercontent.com/157711/34959687-98b54574-fa05-11e7-80ad-f05246e612ec.png">

**Comment by Thomas101** [comment]
Thanks for pointing that out! We've just pushed 3.9.0 out which fixes this. If you do the normal check for updates and install it should re-appear
