### ISSUE TITLE
RPM packages

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#536]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.8.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Linux openSUSE Tumbleweed

Please, give us RPM packages for openSUSE.
Thank you in advance,
Cris

**Comment by xenithorb** [comment]
I mean how do they get away with using the RedHat logo without providing at least an RPM or an AppImage or have flathub package it for Flatpak?

Seems dubious at best while using that logo and not providing what we need.

**Comment by FischTank** [comment]
Which version of Wavebox are you using? [e.g. 3.0.0]
3.10.0

Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Fedora 27

An RPM repo would be great, but a Flatpak would be nicer (and reach more platforms).

**Comment by Cris70** [comment]
This is great! Thank you!
