### ISSUE TITLE
Refine Stackedit window behaviour

### ISSUE THREAD

**Issue by wallace11** [wavebox/waveboxapp#537]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.9.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Linux Mint 18.3

**Comment by nmat** [comment]
hello @wallace11,

What is stackedit and how are you trying to login to it?

**Comment by wallace11** [comment]
www.stackedit.io
Simply try to login via the right hand menu (via Google account). They
appear to be using JS callbacks which happen to mess up on Wavebox.

**Comment by Thomas101** [comment]
I'll look into it and see what's going wrong behind the scenes

**Comment by Thomas101** [comment]
We've just added StackEdit to the list of apps. To get it, first open your Wavebox settings and in the bottom right there should be a `Wire Config Version`. Check this is 1.3.4 or higher. If your machine hasn't got the update quite yet, restart Wavebox it will grab the update shortly afterwards.

Then rather than adding through the Any Website link, add through the StackEdit button - it's got some additional fixes...

![screen shot 2018-01-26 at 14 38 54](https://user-images.githubusercontent.com/103586/35444517-b0725e6e-02a6-11e8-9b92-ae971c3aeedb.png)

**Comment by wallace11** [comment]
That's wonderful! Works like a charm! Thank you.

I don't know if I should open another issue for this, but switching workspaces doesn't keep the app in the same window.
Right menu-->Workspaces-->Add Google Drive workspace-->....-->Switch to work space-->Open in a new window

**Comment by Thomas101** [comment]
I guess we can deal with that one here. In the browser, it opens up a new tab when you switch. I guess in Wavebox there's argument to do one of two things...

1. Open the workspace in a new Wavebox Window (so you stay logged in etc)
2. Open the workspace in-situ so it's like navigating in the same app

Would be good to get some feedback on what you think would work best

**Comment by wallace11** [comment]
Changing workspace in StackEdit is probably meant to be a one-time operation for regular users, or at least something that is rarely done, so I think that it should be done in the same window, and not open a new one.

**Comment by milessb** [comment]
I'm running 3.10.4beta, Wire Config Version 1.3.5 and still when I attempt to sign into StackEdit Wavebox crashes (and a tab in Chrome is opened with StackEdit). I've tried adding StackEdit both using the new button and as any website.

**Comment by Thomas101** [comment]
Thanks @milessb we're seeing the same here. Will find out what's causing it!

**Comment by Thomas101** [comment]
@milessb we’ve just released a fix for the crashing in Wavebox 3.10.5. Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
