### ISSUE TITLE
Main window doesn't have enough IDs/Classes on elements to make styling CSS viable.

### ISSUE THREAD

**Issue by alcor** [wavebox/waveboxapp#538]
* Which version of Wavebox are you using? 
3.9.0

* Which Operating System are you using?
Mac OSX 10

I'm trying to use the "Main Window Custom CSS" option under Settings > Advanced, but am running into trouble because there aren't enough identifiers on the HTML elements to be able to style reliably. In particular, "ReactComponent-Sidelist-Mailboxes" appears to be the only real class available, and I'm not able to style the area below the window widgets and the control strip below.

It'd be great if you could add them :)

![image](https://user-images.githubusercontent.com/563095/35001550-e99c543c-fa9b-11e7-887f-b27a8b749b0d.png)

**Comment by Thomas101** [comment]
I totally agree. We use the material-ui lib between the scenes which is pretty css unfriendly. The next major version of it switches from inline styles to css which means we will be too.

In the meantime I'll look to see if I can drop a few classnames into the sidelist. It might help!

**Comment by Thomas101** [comment]
I've started to add a few more classnames into the sidelist & toolbars. Would be good to know if there's anything specific that you're looking for? Here's what I've added so far....

**Sidelist**
![screen shot 2018-01-26 at 11 35 36](https://user-images.githubusercontent.com/103586/35438184-71b1e94c-028d-11e8-9b2a-c13050d1d30c.png)

**Toolbar**
![screen shot 2018-01-26 at 11 36 21](https://user-images.githubusercontent.com/103586/35438192-757c2c36-028d-11e8-80c6-1db46dad9378.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by alcor** [comment]
Cool! Will do :) those additions look great.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
