### ISSUE TITLE
Clicking back on a sleeping account reloads the page. Wasn't this way earlier

### ISSUE THREAD

**Issue by rajalokan** [wavebox/waveboxapp#539]
* Which version of Wavebox are you using? **3.8.0**

* Which Operating System are you using? **Ubuntu 16.04**

Whenever I click back to open an account which is sleeping, the page reloads itself and hence takes some time. I really like to keep very minimum inactivity timeout ( 1 Min) to not waste memory. With this reloading page the page, almost everytime I go back is painful. 

I would also like to add, this wasn't the case at least two or three days back. I really liked this sleep feature with no overhead in awaking services. Please let me know if I've missed out on anything.

**Comment by nmat** [comment]
This happens on windows 10 also.

Seems that its really slow going from sleep -> wakeup on most accounts.

**Comment by nmat** [comment]
if there is anyway to improve the load time between sleep -> active

**Comment by Thomas101** [comment]
At the moment the wake-up cycle does a full page load as we're not able to partially free up memory without tearing the page down. I've had a go with 3.7.0 and 3.9.0 on a couple of websites and see comparable or faster loads with 3.9.0. Which account type or site are you trying this with @rajalokan ?

**Comment by rajalokan** [comment]
I use a Gmail account, office 364 ( calendar and people), slack, MS teams
and a web page (kiwi IRC). I will have to recheck if this is still very
tedious. Thanks for reaching out.

**Comment by Thomas101** [comment]
The next beta version has some improvements for page load and responsiveness, I'm hoping this will help with this issue!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
