### ISSUE TITLE
Global Shortcuts?

### ISSUE THREAD

**Issue by maxim-lian** [wavebox/waveboxapp#540]
Would it be possible to implement shortcuts that could work in MacOS from any application? e.g. `Shift-Cmd-1` could translate into `Wavebox -> Cmd-1`. I've tried doing this in Automator & Services using a script (example below), but have run into some issues around Accessibility permissioning.

```
    tell application "System Events"
        tell process "Wavebox"
            activate
            set frontmost to true
            click menu item "Toggl" of menu "Window" of menu bar 1
        end tell
    end tell
```

* Which version of Wavebox are you using? 3.9.0

* Which Operating System are you using? MacOS 10.13.2

**Comment by nmat** [comment]
Hello @maxim-lian,

AFAIK there is work being put into how the keyboard shortcuts work that will allow for reassign the keys. However the progress and how this will work in the long run I am not 100% sure.

**Comment by Thomas101** [comment]
What's the end goal that you're trying to achieve here? To be able to map onto any shortcut or just some?

From your Automator script, it just looks like you're just trying to toggle the visibility at the moment. If this is the case you can map a shortcut for this under Settings > Advanced. Head all the way down to Global Shortcuts and add the shortcut into *Toggle App*. E.g. `F1` to use the F1 key.

**Comment by Thomas101** [comment]
Yeah, it only does (a) at the moment. What's the issue with the Automator & accessibility problems? Is it Wavebox side or with macOS?

**Comment by maxim-lian** [comment]
I think it's with macOS: clicking menus requires accessibility permissions, and my working hypothesis is the app that's open at the time is required to have them, rather than granting them to the script. So unless every app has them, it doesn't work.

Extending the Global Shortcuts to open apps would be awesome!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by maxim-lian** [comment]
This is brilliant! Thank you so much. Let me know if I can test anything for you (it works so far though!)

**Comment by maxim-lian** [comment]
This is still working great. You're welcome to close this issue...

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
