### ISSUE TITLE
Make desktop icon themable (linux / freedesktop)

### ISSUE THREAD

**Issue by mrmeszaros** [wavebox/waveboxapp#541]
* version of Wavebox: 3.9.0
* Operating System: Ubuntu 16.04

Currently the icon of the desktop entry is hardwired to the bundled icon (eg.: points to /opt/wavebox/wavebox_icon.png when installed via apt).

Make use of the [freedesktop.org icon specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons) for installing icons.

What this basically means:
* install the icon under `$HOME/.local/share/icons/hicolor/size/name.extension`
  * `size` should be the dimensions of the icon (eg. `48x48` or `512x512` or `scalable`)
    * can add multiple sizes
  * `name` must be unique (`wavebox` should be good)
  * `extension` can be `png`, or `svg` (then size should be `scalable`)

After that, the `Icon` line in `wavebox.desktop` can be changed to the previously  chosen `name` **without the extension!**

This will enable icon themes (like [numix](https://github.com/numixproject/numix-core/pull/4159)) to override the default icon that fits the theme.

**Comment by Thomas101** [comment]
Would placing it in `/usr/share/icons/hicolor/256x256/apps/wavebox.png` work rather than under the users HOME dir?

**Comment by mrmeszaros** [comment]
Oh, yes - forgot to mention - `/usr/share/icons/...` is even better :-)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
