### ISSUE TITLE
Unexpected token when looking at slackLogUnreadCounts

### ISSUE THREAD

**Issue by scadeg** [wavebox/waveboxapp#543]
* Which version of Wavebox are you using? 3.9.0

* Which Operating System are you using? Windows 10

Recently one of my slacks got stuck showing 1 new message (1 badge on the icon in left bar). This morning it's now at two. You may recall I was active on one of the wavebox issues last spring regarding slack new message notifications getting stuck and am familiar with the normal methods to resolve.

I turned the slackLogUnreadCounts flag on and performed a resync, expecting to see the list of channels/PMs. Instead, I got an Unexpected Token syntax error. I have attached a screenshot. I blurred the guids since I don't know what they are identifying. I can provide privately if they are personal ids, or publicly if they are not.
![image](https://user-images.githubusercontent.com/11967555/35232450-1a3d2e08-ff61-11e7-8299-d2c84c70c796.png)

**Comment by Thomas101** [comment]
Hey, thanks for reporting. From the error it looks like slack isn't returning valid json which is what's causing the failure. They don't have any specific info on a service outage for this on their status page, but they did have [some problems](https://status.slack.com/2018-01/1d3f190f4ca0fc1e) yesterday. If you try it again now do you still see the same error?

If you do, we can get a little more info about what's being returned and hopefully that will shed some light on what's happening...
1. Open up the Developer tools as you did before
2. This time click on the `Network` tab at the top and leave this window open
3. Right click on the account in the left and pick `Resync`
4. In the network panel you should see a new item appear that starts with `users.counts?token=`
![screen shot 2018-01-23 at 08 39 41](https://user-images.githubusercontent.com/103586/35265842-3deabf24-0019-11e8-946f-78fe559e43cc.png)
5. Click on this new item and then the response tab
![screen shot 2018-01-23 at 08 39 47](https://user-images.githubusercontent.com/103586/35265851-492daa2c-0019-11e8-86f9-cdc0bf310cf2.png)

What's the response that appears in the box below the tab? I'm guessing it wont be anything like `{"ok":true,`.... but probably some HTML based on the fact the string started with a `<`

**Comment by scadeg** [comment]
Yup. It's the html for the "Server Error | Slack" page.

**Comment by scadeg** [comment]
Was just talking to someone in a thread inside a DM. Bit unusual, but yeah. And I watched the counter go from 2 to 8. Yes, there were six messages in that thread (total, from both of us). And now I can't get the count to go down. Wonder if the true problem lies therein.

**Comment by Thomas101** [comment]
Looks like a problem slacks end then. If you try re-adding the account to Wavebox it might start working again. Sometimes if you hit a different server with the access key or grab a new one problems like this seem to work themselves out

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
