### ISSUE TITLE
Okta / Duo - Chrome is out of date

### ISSUE THREAD

**Issue by nzoschke** [wavebox/waveboxapp#545]
* Which version of Wavebox are you using? 3.9.0

* Which Operating System are you using? Mac OSX 10.13.2

I'm trying to use WaveBox at a company where Google is accessed through Okta. I can't log in due to the security policy around allowed Chrome versions.

<img width="402" alt="screen shot 2018-01-23 at 12 01 26 pm" src="https://user-images.githubusercontent.com/147410/35297908-4d9a0b20-0035-11e8-8346-bbeb32f9d750.png">

**Comment by dctucker** [comment]
Same problem here, except I can't sign into Slack due to Chrome being out of date. I emailed support about this a few minutes ago, figured I'd check the Github repo.

**Comment by nmat** [comment]
I tested to signout and signin with a already added account on slack. But I have not got that problem as mentioned above.

**Comment by nzoschke** [comment]
v3.10 works for me. Thank you!

**Comment by Thomas101** [comment]
Awesome, will close off. Thanks!
