### ISSUE TITLE
Feature request: Automatic un-sleep

### ISSUE THREAD

**Issue by pprasquier** [wavebox/waveboxapp#550]
The sleep function is nice as it saves memory. But it defeats the purpose of notifications. What would be nice is we could set, for each service, a delay for waking up, just to catch the missed notifications and then go back to sleep.

**Comment by Thomas101** [comment]
That's a good idea! I'll take a look and see what we can do

**Comment by lens0021** [comment]
There is 'Auto-wake app in background' option in the app setting. Was this issue resolved?

![image](https://user-images.githubusercontent.com/28209361/219530373-99ece4c0-460b-4f75-b60a-01ada0282947.png)

**Comment by Thomas101** [comment]
👍 the auto-wake was added a while ago now
