### ISSUE TITLE
Socket Issues?

### ISSUE THREAD

**Issue by jcarroll-mediafly** [wavebox/waveboxapp#552]
Starting today I've been having issues where my slack account and mail account appear to disconnect occasionally. Slack says it will attempt to reconnect like it normally does (although the number of seconds is really huge, ~3million seconds). And mail will update badge count but I'm unable to interact with any of the actual content.

I also have the slack "native" app from app store and been seeing this too. Not sure if its related to latest version of electron that was released but I'm pretty sure slack app and wavebox both updated to latest version.

I also updated to mac os 10.13.3 recently.

I don't have good steps to reproduce yet, I have developer tools open, so I look for any relevant logs

* Which version of Wavebox are you using? 3.10.0
* Which Operating System are you using? Mac OSX 10.13.3

**Comment by nmat** [comment]
How is the computer connected because this seems to me more of a network issue rather then a application issue. Also how often does the socket connection problems occur?

Can you check the network for any problems also? Or even connect using a different connection? (cable vs wireless) for example.

**Comment by jcarroll-mediafly** [comment]
Will test it out a bit more. Perhaps it was simply a bad day for the network. I now see slack also had some minor issues yesterday

**Comment by Thomas101** [comment]
Thanks for reporting. There's also some more info the Wavebox task monitor. If you open `Settings`, then at the bottom right click `Task Monitor` it will bring up a new window. At the bottom of here there's some additional info about the connected long standing sockets. Might give some more clues as to what's going on...

![screen shot 2018-01-26 at 15 52 48](https://user-images.githubusercontent.com/103586/35448012-08e17a9e-02b1-11e8-84ac-2e5fa9c3ff95.png)

**Comment by jcarroll-mediafly** [comment]
Cool, I checked out that area and currently showing the same thing you are. Setup/connected are checked, while maintenance is an x.

Assuming thats normal

**Comment by nmat** [comment]
@jcarroll-mediafly did you manage to test the network out? :) yeah the X and its green means there are no maintenance at that point in time. :) Well its my best guess anyway. :)

**Comment by jcarroll-mediafly** [comment]
Yet to see any more issues. I'm going to say it was slack having a bad day. Ill reopen if anything more fishy arises or if I see any websocket issues now that I know what to look for.

Thanks
