### ISSUE TITLE
I do not receive notifications on new emails

### ISSUE THREAD

**Issue by simonemazzoni** [wavebox/waveboxapp#553]
* Which version of Wavebox are you using? **3.10.0**

* Which Operating System are you using? MacOS Sierra 10.12.6

Hello, I noticed that I don't receive notifications on new emails when they arrive. I do not receive neither the toast notification, nor the badge on the app icon on the app bar, but if I open the app then the new emails are here.

I already tried to reinstall the app and to reconfigure the notifications, but nothing works.
How can I solve this? The app is good but also pretty useless without notifications.

Thanks

**Comment by Thomas101** [comment]
Which account type are you not receiving notifications for? There are some steps you can run through to check Wavebox is configured correctly for [Google Accounts](https://wavebox.io/kb/google-unread-counts) and [Microsoft Accounts](https://wavebox.io/kb/microsoft-unread-counts).

If neither of those help, it's worth opening your Wavebox settings and then clicking on `Test Notification` to see if that brings anything up.

**Comment by simonemazzoni** [comment]
Hi @Thomas101 , I'm using two inbox accounts.
Notifications used to work in previous versions (I do not recall exactly what is the last working version though)

I already try the notification test button, and all works fine. The notification display correctly.

It looks more like the reception of a new email doesn't trigger the update of the badge and the send on the notification.

Notice also that the behaviour for unread messages set on wavebox is `Unread Messages` that, according to documentations, should send notification on all the unread emails.

**Comment by Thomas101** [comment]
Thanks for the update. It could be that there's some kind of authentication problem with the token that Wavebox is using and Google is rejecting it. If you try re-adding the account does that make any difference?

**Comment by simonemazzoni** [comment]
@Thomas101 I didn't try that before, but tried just now to clear cached data. The app asked me to sign in again in my accounts, but then I received, on both accounts, an email from google saying that some `not secure app` tried to access my account and that google blocked it. Maybe it is related? Notice that I an actually logged in right now and I can read emails, but still I can't receive notifications.

**Comment by Thomas101** [comment]
Wow, we've not seen that before! Can you contact me through our [support page](https://wavebox.io/support) I'll see if we can get to the bottom of it

**Comment by simonemazzoni** [comment]
@Thomas101 contacted you from support page. Actually now the situation evolved. I removed and re inserted one of the two accounts and now it works fine with the notifications. But in the meantime, I don't know why, the app upgraded to trial unlocking all the features for 14 days.
