### ISSUE TITLE
npm run rebuild:electron fails on linux

### ISSUE THREAD

**Issue by ben8p** [wavebox/waveboxapp#554]
* Which version of Wavebox are you using?
Clone from master

* Which Operating System are you using?
Ubuntu 16.04

When running `npm install` and `npm run install:all`, some warning are displayed about optional dependencies being ignored.
For instance : 
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-mac-notifier@0.0.13 (node_modules/node-mac-notifier):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for node-mac-notifier@0.0.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

Next step for building wavebox is to run `npm run rebuild:electron`.
this task will fail with the following error:
```
rebuild: ./waveboxapp/src/app
{ Error: ENOENT: no such file or directory, open './waveboxapp/src/app/node_modules/node-mac-notifier/package.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './waveboxapp/src/app/node_modules/node-mac-notifier/package.json' }
```

This seems to be caused by `./waveboxapp/scripts/rebuildElectron.js` : 
The current configuration is rebuilding `prod` and `optional`. (line 18)

By removing `optional`, we can make the task working, but I wonder if it will not miss something else...

**Comment by Thomas101** [comment]
It should skip over the optional dependencies so I don't understand why it's trying to compile them. I've just tried on a 16.04 box and it skipped right over them. What version of node and npm are you using?

**Comment by ben8p** [comment]
```
ben@xps:~/bin$ node --version
v9.4.0
ben@xps:~/bin$ npm --version
5.6.0
```

**Comment by Thomas101** [comment]
You'll need to use v7.9.0 of node to build the native dependencies. The build version needs to match that of the embedded electron one. [nvm](https://github.com/creationix/nvm) is handy for switching versions on a single machine. Might be worth trying with that one to see if you see the same error?

**Comment by ben8p** [comment]
Will do.
It looks like all is working if I skip the optional.
Also now that I think of it, it might be a bug with the electron updater package

**Comment by ben8p** [comment]
@Thomas101 that's super strange...
I re-installed node using `nvm`.
Now I have : 
```
11:18 $ nvm ls
->       v9.4.0
$ npm -v
5.6.0
```
As you can see, the version of node in use is `9.4.0` and npm `5.6.0`.
Exactly like my previous setup. The only difference is that node is installed using `nvm` instead of using `apt`

Guess what ? `npm run rebuild:electron` works fine now...
Very strange...

anyway, not an issue anymore.
