### ISSUE TITLE
[question]: How to filter and count unread messages properly.

### ISSUE THREAD

**Issue by magicalbanana** [wavebox/waveboxapp#559]
* Which version of Wavebox are you using? [e.g. 3.0.0]
`Version 3.10.0`

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
```
System Version: macOS 10.13.2 (17C205)
Kernel Version: Darwin 17.3.0
```

I've been trying to get the custom filters working but I'm not having much luck. Basically, I want to only be notified or have the unread count messages on `primary`, `updates`, and `forums`. Anything else, I don't want to get.

I've emailed support already and have stated I'm a pro user but after a few replies, I got none anymore.

Here's a screen shot of my config:

![image](https://user-images.githubusercontent.com/7953984/35642169-de7c6d06-0687-11e8-8ec7-f0ef6f4476ab.png)

**Comment by Thomas101** [comment]
What behaviour are you seeing with this configuration?

Looking at the `Custom Unread Watch Labels`, it might be worth trying `INBOX, UNREAD` as you're not really touching the updates, forums or primary labels.

**Comment by magicalbanana** [comment]
@Thomas101 basically, I don't want to get notified or have unread counts for `socials` or `promotions`.

**Comment by Thomas101** [comment]
The following should provide this...
* Custom Unread Query`in:inbox is:unread -category:promotions -category:social`
* Custom Unread Watch Labels `INBOX, UNREAD`

Using that do you still receive updates from promotions and social? If you do receive updates try pasting the unread query into the inbox search bar to see if any emails appear that you're not expecting

**Comment by magicalbanana** [comment]
So does this mean that I should expect that I will not get notifications from `socials` and `promotions` but still get the unread count for it?

**Comment by Thomas101** [comment]
You should not get notifications or an unread badge for anything in `social` or `promotions`

**Comment by magicalbanana** [comment]
@Thomas101 notifications, I don't. However, badge counts I still do.

**Comment by Thomas101** [comment]
what's the badge count being displayed as vs what it should be? E.g. displayed as 10, but should be 0

**Comment by magicalbanana** [comment]
@Thomas101 seems to be OK now. I guess it adjusted itself in a while.

**Comment by Thomas101** [comment]
Let me know if you have any more trouble

**Comment by magicalbanana** [comment]
@Thomas101 I have noticed that if the account or app (Gmail) goes to sleep, it doesn't really work. I have to ensure that the app doesn't go to sleep.

**Comment by Thomas101** [comment]
Notifications may take a little longer to come through when the account is sleeping, but this should be comparable to the speed of the Android or iOS Inbox apps. If it's left a couple of minutes after the email do you get the notification?

Failing that, if you restart Wavebox, then go to View > Developer > Wavebox Ddeveloper Tools and click on the console tab do you see any warnings or errors?
