### ISSUE TITLE
Custom account icons reset to original icons (Office 365)

### ISSUE THREAD

**Issue by mikesprague** [wavebox/waveboxapp#56]
* Which version of Wavebox are you using? [e.g. 3.0.0]
    - v3.1.3

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
    - Mac OS Sierra v10.12.4
    - Ubuntu 16.04

Whenever I change the account icon for one of my Office 365 accounts it resets to the original icon the next time I open the program. It also resets anytime it redraws (presumably when updating the shadow DOM but it could be something else).

It's possible this affects other account types but I've experienced it the most with Office 365.

**Comment by Thomas101** [comment]
I think I might know what this. Thanks!

**Comment by Thomas101** [comment]
This has been added into 3.1.4 which is now live. Thanks!

Wavebox should update automatically after a while, but if you want to hurry it up, just restart the app and it will re-check

**Comment by mikesprague** [comment]
Thank you! 🎆  Just bought my Pro subscription too, great work!

**Comment by Thomas101** [comment]
Awesome! Let us know if you have any more problems :)
