### ISSUE TITLE
[question] Are there shortcut keys?

### ISSUE THREAD

**Issue by esparkman** [wavebox/waveboxapp#560]
* Which version of Wavebox are you using? 3.10.0

* Which Operating System are you using? macOS 10.13

Are there shortcut/hotkeys to navigate the configured accounts?

**Comment by nmat** [comment]
Inside preferences -> advanced -> Keyboard Shortcuts You will find the shortcuts that wavebox has.

You can also read: https://blog.wavebox.io/be-a-keyboard-shortcut-master/

**Comment by nmat** [comment]
@esparkman did this answer your question?

**Comment by esparkman** [comment]
Yes and no. :) I was looking more for hotkeys to quickly bounce between accounts.

**Comment by nmat** [comment]
Ctrl+[number]
Ctrl+Shift+[number]

On Mac

Cmd+[number]

is that not what you mean?

**Comment by esparkman** [comment]
That is exactly it. My apologies I tried it after looking at the docs and it didn't work. It was my error. Thanks for the follow up and an awesome product.
