### ISSUE TITLE
Notifications didn't work on the 31st of January

### ISSUE THREAD

**Issue by Evertt** [wavebox/waveboxapp#563]
* I'm using version 3.10.0
* macOS 10.13.3

On the 31st of January none of my Wavebox notifications worked, because it generated an invalid search query. In the search query it would say something like `from:"info@example.com" to:myaddress@gmail.com subject:"blabla" after:2018/1/31 before:2018/1/32`. And of course there is no 32nd of January so that search query resulted in nothing. When I manually changed the query to `from:"info@example.com" to:myaddress@gmail.com subject:"blabla" after:2018/1/31 before:2018/2/1` it worked.

So uh, please fix that?

**Comment by Thomas101** [comment]
Thanks looks like there was a boundary issue with the search. There's a patch waiting to go into the next release https://github.com/wavebox/waveboxapp/commit/9a623a178ce552bdad6fdd090a5a75cb955f303e

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
