### ISSUE TITLE
Focus stay on previous app when switching to a sleeping account

### ISSUE THREAD

**Issue by hlidotbe** [wavebox/waveboxapp#565]
* Which version of Wavebox are you using?

3.10.0

* Which Operating System are you using? 

MacOS 10.3.3

So, when switching from Slack to a sleeping Gmail account (with CMD+Number), trying to use the keyboard shortcuts to do thing in the mailbox sends the keystrokes to the previous slack window. When switching back to Slack the message field is populated with the key pressed. The only way to give back the focus is to click in the mail window.

If the account is not sleeping then focus works as expected.

**Comment by nmat** [comment]
Tested this on windows 10 and have no problems with the focus. It does take time for the service to wake up but thats all.

Do not have a mac os machine here where I sit now but maybe someone can try to reproduce?

**Comment by Thomas101** [comment]
Sorry about that. I'll take a look to see if I can reproduce this

**Comment by hlidotbe** [comment]
I'm trying to test different situations, waiting more, ... but so far it's pretty consistent: a sleeping app doesn't get the keyboard focus until I click in it. Even from gmail to gmail.

**Comment by nmat** [comment]
I tested it now on mac os and it seems to switch to the sleeping service without any problem. @Thomas101  are you able to reproduce it?

**Comment by Thomas101** [comment]
I've not been able to reproduce it here. Maybe I'm doing something slightly differently though. Which shortcut are you trying when Gmail is focus? I tried <kbd>C</kbd> for compose.

Which other account types do you have setup? I gather Slack and two Gmail, but any others? Perhaps something is stealing focus when it shouldn't be

**Comment by hlidotbe** [comment]
I have: 1 slack, 5 gmails, 1 basecamp.

The focus stay consistently on the last account opened, if it's slack I see the shortcut in the input field, if it's a gmail the shortcut is executed on the other account. Any keystroke is sent to the other account, jk, u, return, ...

I made a quick video to illustrate. Before trying to move around I waited the account to be loaded.
 
[wavebox.mov.zip](https://github.com/wavebox/waveboxapp/files/1698393/wavebox.mov.zip)

**Comment by Thomas101** [comment]
Thanks for the video, that's really helpful! I'm seeing the same behaviour in version 3.10.0, but not in the latest beta (3.10.1). Would you be able to give this a try and see if it's fixed for you too? [Here's some instructions on how to use the beta channel](https://wavebox.io/kb/beta-channel)

**Comment by hlidotbe** [comment]
Seems to have fixed it indeed!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
