### ISSUE TITLE
When Google Drive is Added as Standalone All Links Open With Wavebox Browser

### ISSUE THREAD

**Issue by cbtlr** [wavebox/waveboxapp#566]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.10.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
OSX 10.13.4

My institution only uses a Google Account for Drive. Adding another Google Account just for Drive makes no sense because the account keeps default opening to a GMail when swapping to i.We don't use it but Wavebox makes it so you can't drag and move Gmail in the toolbar or even deactivate it as a service. In lieu of requesting the adding these features I just added the Google Drive standalone option.

With this however, all drive links open in Wavebox browser despite the option to use the OS default browser being chosen differently. Worth noting, when a Google account is added you have a nice little toggle that prevents this with drive links but not so with the standalone.

Screencast: https://d.pr/free/i/Z5UvxG

**Comment by Thomas101** [comment]
Yeah, that's a fair point. I'll see if I can expose the option when added as a standalone account

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
