### ISSUE TITLE
Feature Request: Deactivate Gmail from Added Google Account Suite

### ISSUE THREAD

**Issue by cbtlr** [wavebox/waveboxapp#567]
Other services, like Google Music, can be deactivated however GMail cannot.

My institution only uses a Google Account for Drive and Docs. In the current Wavebox system, adding another Google Account just for Drive makes no sense because the account keeps default opening to a GMail when swapping to it. Wavebox makes it so you can't drag and move Gmail in the toolbar or even deactivate it as a service.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
