### ISSUE TITLE
Notifications for Microsoft Teams

### ISSUE THREAD

**Issue by cbtlr** [wavebox/waveboxapp#568]
Our institution for better or for worse uses Microsoft Teams pretty heavily as our collaboration platform. Messages, however, do not populate as notifications as you would see for other collaboration platforms or like Google Hangouts. If you could scrape any info out the UI and display it for this that would be ideal. 

<img width="271" alt="screen shot on 2018-02-06 at 09 42 35" src="https://user-images.githubusercontent.com/27827468/35865321-347f245c-0b22-11e8-92ae-00c532dedb45.png">

**Comment by nmat** [comment]
@cbtlr this has been reported before in: https://github.com/wavebox/waveboxapp/issues/528

The notifications for all services are being worked on more for all services AFAIK. Just be patient :)

**Comment by cbtlr** [comment]
Apologies, I should have searched. Cheers and thank you for your support.
