### ISSUE TITLE
Microsoft teams - High CPU load

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#569]
* Which version of Wavebox are you using?
3.10

* Which Operating System are you using?
windows 10

* Description:
I am noticing a high CPU load on microsoft teams that ranges between 5-11% and this seems consistent. Have used the app for a while now and the CPU load goes up on these numbers all the time.

System information:
winver: 1709 (OS Build 16299.192)

Completely new machine and new wavebox install. The teams application is used as a indexed service inside office365 connection.

This is the number one process that is using up CPU in wavebox. Others use up about 1-2% (maybe a little more but not much)

Memory used for the indexed teams application is: 320MB

Next highest is Slack that uses about: 308MB memory

**Comment by Thomas101** [comment]
Have you got any metrics on using teams in chrome? It sounds like it's down to what Microsoft are doing.

The only other things I can think of that can cause high cpu usage are...
* Any extensions installed? Maybe there's some kind of conflict with one of those
*  Any gifs/videos visible in teams? These can normally eat cpu, but we should be killing them off when the account is out of focus

**Comment by nmat** [comment]
unfortunately I have not tested it _directly_ in chrome only using awesome wavebox ;)

hehe

However I do agree it probably is something from microsoft I just wonder if there is anything that could cause it based on other things like slack. 

* No extensions are installed
* No gifs/videos are visible as far as I can see

Teams from what I know did get a big update quite recently though and when I am checking now it uses maybe 2-6% CPU.

But I wonder if there are anythings that could help with the CPU usage and/or memory usage for teams. However I am not sure. If else then this ticket can be closed.

**Comment by Thomas101** [comment]
As for memory usage goes, chromium adjusts the amount it uses depending on the amount the machine has available.

As an example, when we test Wavebox on an 8GB machine, Slack, Inbox etc use somewhere between 200-300mb easily. However, when we've tested it on a machine with just 1GB of memory it uses more like 30-80mb. Obviously by using less memory though you see far reduced performance.

In terms of the CPU though, it's kind of down to what the guest page is doing. If the guest page wants to calculate pie then it's going to eat more CPU as opposed to one that shows a few lines of text. We have looked into the electron BrowserView component over the WebView component, to see if that managed consumption on inactive tabs any better, but we didn't see any measurable change.

On the flip side of that though, some of the newer versions of Chrome have some neat features for slowing down JavaScript execution on inactive tabs. This could be something that we can leverage in the future, but we haven't had time to look into it as of yet.

For the time being it's probably a case of closing this off though :-/
