### ISSUE TITLE
oAuth pop-up windows don't work

### ISSUE THREAD

**Issue by mikesprague** [wavebox/waveboxapp#57]
* Which version of Wavebox are you using? [e.g. 3.0.0]
    - v3.1.3

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
    - Mac OS Sierra v10.12.4
    - Ubuntu 16.04

When attempting to add additional sites via Add Any Site I am given the oAuth pop-up but it opens in my browser and once authenticated doesn't pass that authentication back to Wavebox. A good example is logging into Feedly via Google auth.

There are also some web apps that still make use of pop-ups for non-authentication reasons. It might be nice to have them open a new tab within Wavebox or an additional window (as expected).

**Comment by Thomas101** [comment]
I can imagine this is because the generic link just opens all new windows in the default browser. I wonder if I can pick out the common oauth provider urls and open those up in a Wavebox window. I'll have a look and see what's possible!

**Comment by mikesprague** [comment]
Thanks @Thomas101! I'd also be happy with Feedly as an application for Wavebox 😉  if this isn't an easy fix/tweak! 

Love the application and really happy to see it getting continued development. Thanks for your time, keep up the great coding!

**Comment by Thomas101** [comment]
As a heavy feedly user myself it's high on own list ;-)

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which fixes this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by mikesprague** [comment]
Confirmed! Feedly (with custom css styling) working as expected! Thanks much for this! 😄 

<img width="1545" alt="screen shot 2017-05-04 at 12 28 08 pm" src="https://cloud.githubusercontent.com/assets/560705/25714398/dd332f72-30c5-11e7-9d1a-bb434314a90c.png">
