### ISSUE TITLE
Question: Can't get Notifications to work for Outlook and Outlook 365

### ISSUE THREAD

**Issue by bshire** [wavebox/waveboxapp#571]
* Which version of Wavebox are you using? [e.g. 3.0.0] 3.10.1 beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Windows 7 Enterprise

I have two email accounts set up (outlook.com and my work Office 365 email).  I can't get the red badge notification to work on the side bar for the individual accounts, nor have the Wavebox icon in the taskbar change with a red badge, and finally the icon in the system never changes from the Checkmark.

I've change all of the settings for the individual accounts where it's supposed to show those items but doesn't do anything.

I also have a Slack account set up and the red badge notifications work for that individual account and the Wavebox icon in the taskbar (still nothing in the system tray).

**Comment by bshire** [comment]
It was an issue with 3.10 as well, I updated to try to see if the beta solved it but did not work.

I deleted and re-added the accounts and they appear to be working now.  All notification areas (red badges in various places and # in the system tray) seem to be functional!

Let me know if you still want the screenshots but I think my problem is solved.  Really like the product.  Only negative for me is the OWA isn't ideal but I love having everything in one place.

Regards,
Brad Peters
________________________________

**Comment by Thomas101** [comment]
Great to hear you've got it working. Sounds like it was an issue with the access token. I've put a patch into the newer versions to try and handle this :)
