### ISSUE TITLE
Ubuntu 16.04 - It is not possible to add attachments located on the data partition

### ISSUE THREAD

**Issue by fsdias** [wavebox/waveboxapp#572]
* Which version of Wavebox are you using? [e.g. 3.0.0]
Version 3.10.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

I tried to attach a file located on my data partition but was unable to due to permissions. See the attached screenshot.

![image](https://user-images.githubusercontent.com/5689181/36051240-53fd856e-0de1-11e8-93c2-101ee08f58f8.png)

**Comment by nmat** [comment]
Can you please provide a bit more information here:

* What is the filesystem being used on the data partition?
* Is the partition mounted using smb, nfs or something similar?
* Also can you see what type of permission you have to the partition/file in general?

**Comment by fsdias** [comment]
- ext4

-  How can I check that?

- Screenshot with the permissions tab
![ss](https://user-images.githubusercontent.com/5689181/36143632-89a8d5c8-10a3-11e8-9b53-322dfc22941b.png)

**Comment by Thomas101** [comment]
This is probably down to the security sandbox that snap uses. It restricts access to some locations which is what I think you're running into here. I'll report it to the snap team and see what they say, in the meantime though there's a couple of things you can try....

1. Installing the Wavebox snap with classic confinement (you'll need to re-setup your accounts when doing this - [instructions on how to export/import](https://wavebox.io/kb/copying-accounts))
```bash
sudo snap remove wavebox
sudo snap install --classic wavebox
```

2. Use one of the other [distribution methods](https://wavebox.io/download/). We have an apt-repository which includes auto-updates etc and should allow you to attach from your data partition

**Comment by fsdias** [comment]
Installing wavebox with classic confinement solved this issue. Thank you!

**Comment by Thomas101** [comment]
Awesome! I think that's worthy of a [kb article](https://wavebox.io/kb/installing-snap-with-classic-confinement) too
