### ISSUE TITLE
Malware Detected?

### ISSUE THREAD

**Issue by codeman6100** [wavebox/waveboxapp#573]
* Which version of Wavebox are you using? [e.g. 3.0.0] 3.10.2

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Windows 10

Webroot SecureAnywhere detected malware during a reinstall of Wavebox.  Specifically, it was the W64.Worm.Gen and it was in the appdata\local\wavebox\wavebox.exe

**Comment by jbjknt** [comment]
Wavebox Version:3.10.0 Home Version 1709
OS: Win10
Webroot SecureAnwhere Version: 9.0.19.43


Just had a similar issue with Webroot Secure Anywhere identifying wavebox.exe as a W64.Worm.Gen virus (image attached).
![wavebox](https://user-images.githubusercontent.com/25315482/36127950-c72ecd5c-109a-11e8-9842-fc8afcb56dfa.jpg)

**Comment by Thomas101** [comment]
Hi, thanks for reporting. We've reported this to Webroot technical support as a false positive and they've updated their security definitions. They've suggested re-running the scan - Wavebox shouldn't be flagged again

**Comment by jbjknt** [comment]
Cheers, glad all sorted out! :-)

**Comment by Thomas101** [comment]
I'll close this off then, but re-comment if you're still seeing it, I'll follow up again with Webroot security

**Comment by jbjknt** [comment]
Will do. Thanks again.

**Comment by AwesomeTech10** [comment]
This happened with me too.

**Comment by AwesomeTech10** [comment]
Same with Mailspring

**Comment by Thomas101** [comment]
@AwesomeTech10 can you check that the security definitions for Webroot SecureAnywhere are up to date?

**Comment by AwesomeTech10** [comment]
It got fixed.

**Comment by codeman6100** [comment]
I just updated to the latest beta, and this is happening again.

**Comment by Thomas101** [comment]
@codeman6100 can you check that Webroot is up to date and try another scan? If this doesn't fix I'll raise it again with them

**Comment by codeman6100** [comment]
Still seems to be an issue on a new install of Wavebox.  I had to reinstall and the executable was caught again.  I have since set it to allow in Webroot's settings.

**Comment by Thomas101** [comment]
This is a false-positive with Webroot. We're signing all our binaries so they're able to securely check that they are from us and are untampered. The best approach is to raise it with Webroot again (https://www.webrootanywhere.com/servicetalk.asp) and ideally they'll trust the signing source rather than flag up each newly signed binary every time. We've already flagged it with them, but please submit as well so that they are aware of the problem.

We've also put up a new [KB article here](https://wavebox.io/kb/antivirus-false-positive) about this for future reference

**Comment by codeman6100** [comment]
FYI, I submitted a support request.

**Comment by Thomas101** [comment]
Thanks, it looks like the latest version has been cleared with the latest definitions

**Comment by codeman6100** [comment]
So for so good.
