### ISSUE TITLE
Windows: can't change the size of Wavebox app nor move it

### ISSUE THREAD

**Issue by pprasquier** [wavebox/waveboxapp#575]
* Which version of Wavebox are you using? [e.g. 3.0.0] : 3.10.0

* Which Operating System are you using? Windows 10

I need to move Wavebox app from monitor 1 to monitor 2 but can't since the app's window won't allow me to drag it. Pressing the window's middle button doesn't do anything either. 

![capture d ecran 74](https://user-images.githubusercontent.com/25961893/36106154-8d2c1882-0fe4-11e8-8db4-8cbcc7ce263b.png)

**Comment by pprasquier** [comment]
Displaying menu bar doesn't fix anything

**Comment by Thomas101** [comment]
Does restarting the machine make any difference? It could just be a glitch

**Comment by pprasquier** [comment]
Unfortunately, no

**Comment by pprasquier** [comment]
Weird thing: the Wavebox app window also covers my Widows task bar, which comes back to the foreground when I press the "Windows" button

**Comment by Thomas101** [comment]
I wonder if the window isn't having its bounds correctly restrained when moving between monitors.

There's a data file that holds the window positioning data. It's safe to delete this and should only affect the remembered window state. If you quit Wavebox, find the folder location as listed [here](https://wavebox.io/kb/data-locations) and then delete/move the file called `app.json`. Then restart Wavebox, does that make any difference?

**Comment by pprasquier** [comment]
It worked, thanks! But I believe it was due to maximized=true, rather than the numerical bounds.

**Comment by Thomas101** [comment]
Glad you got it sorted! Do you mind if I keep this open? I'll do some testing on one of our test boxes to see if I can reproduce it and hopefully stop it happening again

**Comment by Thomas101** [comment]
If you still have the `app.json` file lying around would you be able to share that? Might make it easier to reproduce

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by pprasquier** [comment]
Please find the file of when I experienced the problem. Obviously, its extension is .json...

[app_db.log](https://github.com/wavebox/waveboxapp/files/1813529/app_db.log)

**Comment by Thomas101** [comment]
Thanks for that. It's when the window enters fullscreen mode, the unmaximize behaviour stops working. I've put a patch in to cope with this and give some additional clues when the app is in fullscreen. In the meantime, next time it happens hit F11 to exit fullscreen mode, you should be able to drag etc thereafter

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by pprasquier** [comment]
Thanks!
