### ISSUE TITLE
Can not load app when adding Medium account

### ISSUE THREAD

**Issue by silver886** [wavebox/waveboxapp#577]
* Which version of Wavebox are you using? [e.g. 3.0.0]

3.10.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

macOS 10.13.3 (17D47)

When I adding the Medium account, right after step 1, the whole app turned white.
It seems like JavaScript can not handle **"defaultColor":"#black"**, which is the default setting of Medium.

**Comment by Thomas101** [comment]
Thanks for reporting! I've patched that so it should work correctly now!
