### ISSUE TITLE
Office 365 Unread Count Stuck at 1

### ISSUE THREAD

**Issue by maroc81** [wavebox/waveboxapp#578]
* Which version of Wavebox are you using? 3.10.3

* Which Operating System are you using? Ubuntu 16.04

The unread count for one of my Office 365 accounts has been stuck at 1 for a few weeks.  I saw in other issues where deleting and adding the account again would fix it.  I never got around to trying that but I noticed in the recent beta there is a new "Reauthenticate" feature.  I just tried that and now the unread count works again.

**Comment by Thomas101** [comment]
There's definitely an issue with some services supplying an incorrect count. For some reason, re-authenticating seems to clear this. We added the reauthenticate button as it's quicker than removing and adding the account again.

We're trying to gather a bit more info about when people see this in the hope that we can get a fix together that doesn't require the user to do anything. It would be great to know....
1. How long ago did you first add the account? (e.g. A week ago, months ago, so long ago you can't remember)
2. Was the count permanently stuck at one, or would it up, just never below 1?

Thanks

**Comment by maroc81** [comment]
I thought that might be why reauthenticate was added.  I had been meaning to delete and readd the account and never got around to it.  When I saw reauthenticate was added, I gave it a try and it did the trick.

1. I first added the account a few months ago.  However, this was the one I accidentally deleted and that's when I created #534 after adding the account back. I think it got stuck a week or so after I added it back.
2.  It was permanently stuck at one and  I stopped getting notifications for new emails in that account.

**Comment by Thomas101** [comment]
Hi, sorry to pick this up so late, I'm just wondering if you're still seeing this issue?

**Comment by maroc81** [comment]
I have seen this only once since opening this issue.  The last time it happened was right after my password expired.  I changed my password from a different machine and when I logged in to the Office 365 account with the new password from wavebox, that is when the counter got stuck at 1 again.  

It may be any time my password changes I have to "reauthenticate" which makes sense.

**Comment by Thomas101** [comment]
Thanks, I'll close this off for now then. Just as a side note, if you come up against this again there's now a reauthenticate option in the right-click menu. Just right-click on the affected account/tab and pick reauthenticate. It will let you re-login without needing to completely remove and add the account again :)
