### ISSUE TITLE
[RFE] Open Google Drive links with browser

### ISSUE THREAD

**Issue by tonyjames** [wavebox/waveboxapp#579]
Wavebox 3.10.0 (tar)
Fedora 27

There is an option to open Google Drive links with browser right now but it first opens the link in a browser window that is attached to Wavebox rather than my default web browser (Firefox).

**Comment by Thomas101** [comment]
Hi, it would be great to have a little more info...
1. Which page are you trying to open the link from (e.g. gmail, google inbox, google drive etc...)
2. Do you have an example link that's not opening correctly? Feel free to change some of the values in any ids if you don't want to make a link public

**Comment by tonyjames** [comment]
It's a link from an email in gmail.
The link is: https://docs.google.com/presentation/d/REMOVED/edit

**Comment by Thomas101** [comment]
Awesome thanks for that! There should be a fix in the beta next week :)

**Comment by darrendmiller** [comment]
Hey just popping in here to say I'm having the same issue with "any website" even when I have "open new windows in which browser" set to "default browser." Could be fixed with the same fix, but just thought I'd chime in in case that fix is specific to google drive.

I actually think it did work fine until this morning, if that doesn't sound completely crazy.

**Comment by Thomas101** [comment]
@darrendmiller would be good to know the page you're on and the link you're trying to open

**Comment by darrendmiller** [comment]
@Thomas101 I would, but it mysteriously stopped happening! I guess all is good for now but I'll keep a close eye on it and check back in with more details if I see it again. Unless there was a fix and an automatic update, in which case it looks like it worked.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by tonyjames** [comment]
@Thomas101 I just tested and the links are still being opened within Wavebox rather than my default browser.  Two links I just tested are:

https://docs.google.com/spreadsheets/REMOVED
https://drive.google.com/drive/folders/REMOVED

**Comment by tonyjames** [comment]
![image](https://user-images.githubusercontent.com/3128081/37215065-e61d3cba-2384-11e8-9206-5046118c0c1c.png)

**Comment by Thomas101** [comment]
Drats sorry! The target URL match wasn't quite lax enough

**Comment by Thomas101** [comment]
Hey, the fix for this has just gone out in Wavebox 3.10.5. Thank @tonyjames for the pull request :)

**Comment by khusmann** [comment]
Just upgraded to 3.10.5 and it halfway works: drive links in gmail open in browser, but drive links in a drive tab still open in the wavebox browser. Almost there, thanks for your work on this!

**Comment by Thomas101** [comment]
Yeah, I'm seeing the same. That one might be a bit more complicated to solve. I'll take a look

**Comment by Thomas101** [comment]
Going to remove the `in-beta` label as there's still more to do on this I think

**Comment by pcuellar** [comment]
Version 3.11.0
MacOS 10.13.3

Similar issue; I'm unable to open Google Drive files from within Wavebox with my default browser. Settings for the account are correctly setup.

**Comment by Thomas101** [comment]
@khusmann @pcuellar is it the link in the top toolbar that you're pressing to see this behaviour, e.g.
![screen shot 2018-04-05 at 16 15 43](https://user-images.githubusercontent.com/103586/38374869-bcd54442-38ec-11e8-9272-51ad26e2c4fd.png)

**Comment by khusmann** [comment]
@Thomas101 I don't see that toolbar, but everything is working on 3.13.0 now -- items open from the drive tab open in my browser now.

**Comment by pcuellar** [comment]
Just updated the app and everything is working well. Thanks guys!

**Comment by Thomas101** [comment]
Thanks!

There's a few link open options that weren't being captured (the toolbar being an example), but the current beta should grab these. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
