### ISSUE TITLE
Hide titlebar on Linux

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#58]
It would be really nice if we could hide the titlebar on Linux too. I've played around with Electron in the past and at least on Gnome-shell it worked without issues.

**Comment by Thomas101** [comment]
Looking at this for windows (#36) so we'll see what we can get working on linux too!

**Comment by MichaelTunnell** [comment]
@Naatan this is a built in feature of the Window Manager in some cases, such as KDE Plasma's KWin can hide the titlebar of any window you want it to including Wavebox.

**Comment by Naatan** [comment]
Can we make it a pref that's disabled by default? I don't want to have to pay the price for KDE users not having this capability.

**Comment by MichaelTunnell** [comment]
Wavebox having this as option would be best in terms of DE agnostic but if you wanted a solution right now KDE Plasma would be a option.

In terms of this feature of KDE Plasma, you can use as much as you want or as little as you want.

You can hide all titlebars, only hide titlebars of specific applications, or even only hide titlebars of specific windows of specific applications. The level of control in this feature is unmatched in any other DE or any other OS.

For example, I hide titlebars on about 6 applications automatically but everything else has titlebars. However, I also created a shortcut which hides the Titlebar and all window decorations so the application content can use as much screen space as possible. This way I can invoke the hiding of the titlebar whenever I want on any window I want even if I didn't set it up to be automated.

Tons of control is available for this feature. (I am working on a video that explains how this works)

**Comment by Naatan** [comment]
Gnome-shell has an equivalent feature (through extensions) but native support would be preferable.

**Comment by MichaelTunnell** [comment]
> Gnome-shell has an equivalent feature (through extensions)

Which extension? I searched https://extensions.gnome.org/ for "titlebar" but it doesn't list anything like that. (GNOME's extension search is terrible since I can't link to any search directly)

**Comment by Naatan** [comment]
@MichaelTunnell https://extensions.gnome.org/extension/844/maximus-two/

**Comment by MichaelTunnell** [comment]
@Naatan oh ok I know of that extension but that only applies to windows that are maximized. KDE Plasma's feature can be applied to any window of any size in any state.

**Comment by Naatan** [comment]
Ok, yeah I'm not aware of such a feature in Gnome. All the more reason to have this implemented :)

**Comment by Thomas101** [comment]
This has been added into 3.1.4 which is now live. It's still a little bit experimental, but you can enable it by going to settings and toggling `Show Titlebar` to off. Would be great to have some feedback on this, I think there's still a little bit more work to do on this feature

You can grab the latest version from https://wavebox.io/download
