### ISSUE TITLE
[Feature Request] Keyboard Shortcuts: Cycle through Accounts/Services simultaneously

### ISSUE THREAD

**Issue by tgrehawi** [wavebox/waveboxapp#581]
Windows 10, Wavebox v3.10.0

As it stands, you can only assign shortcuts to cycle either through all accounts, or all services within the currently selected account. Some users (such as myself) might prefer the option to cycle through both of these groups at the same time, rather than having to use two separate shortcuts to do both.

For example, here is my sidebar:
![](https://i.imgur.com/RcITDfh.png)
If I have Twitter selected, I can use my Next Account shortcut to switch, in sequence, through the accounts below it (which offer no additional services). However, once I get to my Google account at the bottom, using my Next Account shortcut sends me to Twitter! If I want to instead go to check Hangouts, Calendar, or Drive, I must use my Next Service shortcut instead.
Rather than alter either of these functionalities, I propose a new set of shortcuts be added: "Previous Account or Service" and "Next Account or Service", which would behave like Next/Previous Account if the current account has no additional services, and behave like Next/Previous Service if it does. If the current selected service is the last on its account's list of services, the next account will be selected.

**Comment by Thomas101** [comment]
I can see this being useful. I'll have a look to see if I can add it in. I think <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Left</kbd> and <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Right</kbd> might be a free combination, but will need to make sure they don't have any conflicts across platform

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
