### ISSUE TITLE
[RFE] Remember login status for Gmail accounts that use SAML

### ISSUE THREAD

**Issue by tonyjames** [wavebox/waveboxapp#584]
Wavebox 3.10.0
Fedora 27

My work Gmail account uses SAML auth to login.  This works fine with Wavebox except that I have to login every time I start the app.

**Comment by tonyjames** [comment]
I just tested with the 3.10.3 beta and I am still prompted to log in to my work Gmail account every time I launch Wavebox.

**Comment by Thomas101** [comment]
Have you tried using the `Artificially persist cookies` setting under account settings? This will normally force you stay logged in.

There's a bit more info under the [Accounts using Single Sign On](https://wavebox.io/kb/staying-logged-in) section here

**Comment by tonyjames** [comment]
I just tried the "Artificially persist cookies" settings and it still requires me to login every time Wavebox is restarted.

**Comment by Thomas101** [comment]
Do you know if sign in is handled by one of the third party providers such as onelogin or okta, or is it all done by your company?

**Comment by tonyjames** [comment]
It's a company specific solution based on Keycloak.  The interesting thing is for some reason today it seems to be remembering my login status after having checked the "persist cookies" option.  I guess we can close this out?

**Comment by Thomas101** [comment]
Glad you got it working! Out of curiosity did you restart Wavebox after changing the artificially persist cookies setting?

**Comment by tonyjames** [comment]
I did restart Wavebox, not sure what fixed it :)
