### ISSUE TITLE
Can I influence new plugin support?? :)

### ISSUE THREAD

**Issue by liquidonline** [wavebox/waveboxapp#585]
I'm on the latest release-version of Wavebox - 3.10.0, on Linux (Ubuntu 16.04 + KDE), and I use it for a couple of Gmail accounts, Trello, and Slack

Are there plans for adding support for additional extensions, and if so, can I convince you to consider Zoom in priority?  I saw there was a survey, but it's rather fragmented, and I'm not so sure it's still being used as a resource, so I thought I'd ask via a formal enhancement request.

My company has decided to move all voice/video communication to Zoom.  I can't blame them - it's much better/easier to just work than browser-based solution, AND they have a proper _native_ linux client.

There is what I consider a rather useful zoom browser extension that allows you to add/remove Zoom meetings as easy as you can with Google Meet in the Google Calendar app.  Look at it this way, when I discovered the extension, as much as I find my life has been made much better with Wavebox in spite of wonky notifications in KDE, I've got a calendar tab open in the browser again.  Nothing beats a single-click to schedule and add a meeting to an invite.  WIthout the extension, I have to manually create the invite + time/date and copy/paste into wavebox and add recipients - not to mention the extension seems to magically "just work" with Zoom url's.

**Comment by nmat** [comment]
If you are interested then please see:

https://github.com/wavebox/waveboxapp/issues/138
