### ISSUE TITLE
Make reddit native or allow for apps to use the upper bar

### ISSUE THREAD

**Issue by skyborgff** [wavebox/waveboxapp#586]
Would it be possible to allow any weblink to have other weblinks on the top, just like with google or office?
That way i would be able to have for example, reddit, and my favorite sub reddits on top, instead of an app for each.

**Comment by Thomas101** [comment]
Yeah, we've got some new stuff in the pipe that will give some better flexibility around arranging accounts

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account by right-clicking on one of the tabs and picking `Add another service`

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
