### ISSUE TITLE
Out-of-memory problem with stacked persistent notifications from Google Calendar

### ISSUE THREAD

**Issue by balloch** [wavebox/waveboxapp#588]
* Which version of Wavebox are you using? 3.10.0 (For this computer at least, but i don't always update all of my machines at the same time and i am using wavebox across 3, so they could be within a subversion or two of one another)

* Which Operating System are you using? Ubuntu 14.04

If I leave a machine locked with waveobx on for a long period of time, it seems as though all of th badge notifications from my calendar are popping up, persisting, never exiting, and so when I get back to my computer nothing is working and all of my memory is eaten up. This *could* be because i allowed my calendar to sleep, but even if it is, notifications should never stack like this. You should do something like...idk keep a pointer to the current notification, and use that to access and dismiss it if another notification pops up. or have persistence be timed (related feature requests:
 - https://github.com/wavebox/waveboxapp/issues/425
 - https://github.com/wavebox/waveboxapp/issues/463 )

does wavebox currently have a solve for this?

**Comment by Thomas101** [comment]
Hi, thanks for reporting. We are aware of this bug and have a fix for it. There's a couple of things you can try...
1. Change the notifications from interruptive alerts to browser notifications. You can do this through your Google Calendar Settings 
![screen shot 2018-02-21 at 12 41 58](https://user-images.githubusercontent.com/103586/36480568-ae0c5130-1704-11e8-83f2-bc5d288ebc51.png)

2. Try the beta channel of Wavebox which has a fix for the issue. You find out more about beta and how to switch in this [KB article](https://wavebox.io/kb/beta-channel)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
