### ISSUE TITLE
wavebox certificate error Windows 10

### ISSUE THREAD

**Issue by tbsnkwlsk1** [wavebox/waveboxapp#591]
Wavebox Version: 3.10.3 beta
Computer: Dell XPS 13
OS: Windows 10

Hi!
i've been using wavebox for about 8 months now. Lately i had an issue with one of my gmail accounts. It wasn't able to sync anymore, so i deleted the account from wavebox and tried to add it again. Problem was, that after selecting the apps, that i wanted to include in my account, the webpage to which i was forwarded wasn't loading (i think this was the page where I had to enter my gmail credentials in order to add the account to wavebox). So i tried to open this in chrome and chrome told me that the webpage is not safe due to an expired certificate. Same thing for Microsoft Internet Explorer and Mozilla Firefox.

I've uninstalled wavebox and re-installed the new version provided on github. In the update notes it says that certificate issues on windows had been fixed. Unfortunately it still doesnt work on my machine.
I've already reached out to the wavebox customer service, but they weren't able to help me, means although I've paid for it I can't use wavebox. 
Oddly enough, the homepage works on MacBooks as well as on my Android smartphone. Also, I've tested the validity of the certificate with a SSL checker and it says that everything should be valid.

Could you please help me here? Thank you!
Best, 
Tobias

![account login window](https://user-images.githubusercontent.com/36701310/36483584-dc83fcfe-1716-11e8-81aa-9e6aec0c6f7e.JPG)

![image](https://user-images.githubusercontent.com/36701310/36483687-20d3b7b4-1717-11e8-9158-71f2fde752f3.png)

![image](https://user-images.githubusercontent.com/36701310/36483726-394981fc-1717-11e8-9f26-0f12203f0dde.png)

![image](https://user-images.githubusercontent.com/36701310/36484228-d7f569e6-1718-11e8-9868-a91859c85335.png)

**Comment by nmat** [comment]
I just tested to go to wavebox.io and the cert seems fine there.

There is nothing on your computer that is caching a old cert or something?

**Comment by tbsnkwlsk1** [comment]
In the certification path it tells me that DST Root CA X3 and Let's encrypt authority X3 are valid, but not wavebox.io

![image](https://user-images.githubusercontent.com/36701310/36493251-743cc900-172f-11e8-8427-bdf51fa4aa1c.png)

![image](https://user-images.githubusercontent.com/36701310/36493177-4894988c-172f-11e8-9976-ce62f9a461c5.png)

I found this in my windows certificates. There it say the DST Root CA X3 is valid until 09/2021.
![image](https://user-images.githubusercontent.com/36701310/36493412-dc7787a8-172f-11e8-855e-55212a44d5ee.png)


I've also re-installed chrome and tested it with firefox portable but the same error occured. Any other ideas?

**Comment by Thomas101** [comment]
The cause of the Wavebox website and app not working is definitely down to the certificate problem. As to why you're machine thinks it's expired is harder to get to the bottom of. We've triple checked our end and everything seems to be as it should and even checked with some third parties (you tried SSL Shopper) and nothing gets flagged up.

What's interesting is the Validity section on your machine is the certificate is valid from October 2017 to January 2018 whereas it should be December 2017 to March 2018.

It would be good to know a little bit more about your machine setup, it might point us in the right direction...
1. Have you checked the date, time and timezone on your machine are correct?
2. Have you tried restarting?
3. Do you get the same result visiting `https://wavebox.pro` and `https://waveboxio.com`
4. Are you using any kind of VPN, proxy server etc to connect to the internet?
5. Is your pc managed by a business corporation or is just your pc at home?
6. What's the version of windows you're using? To find this out...
   * Hit <kbd>Windows</kbd>+<kbd>R</kbd> to bring up the run prompt
   * Type `winver` and click `ok`
   * In the popup that appears there will be some information about your version of windows. There should be a version string such as `Version 1709` what is it on your machine?
7. Are you running 32-bit or 64-bit windows?
   * Right click on `This PC` in any explorer window and then `Properties`
   * Under the System section it should say `64-bit Operating System` or `32-bit Operating System`
8. If you're comfortable using the command prompt, ping wavebox.io...
   * Open the command prompt app through Search or `Start > Windows System > Command prompt`
   * Type `ping wavebox.io`
   * Do you see `Reply from 18.220.213.159` or someting else?

**Comment by tbsnkwlsk1** [comment]
Hi Thomas, thank you very much for your respond.

1. I've checked my time and date in BIOS as well as in Windows. It's correct.
2. Since I have been dealing with this problem for 3 weeks now, I restarted my computer several times as well as uninstalled chrome and wavebox two times.
3. I have the same problems when visiting https://wavebox.pro and https://waveboxio.com
4. I don't use any VPN or proxy server. I am directly connected to the internet via my router.
5. It's my business and private laptop. I have full admin rights on this machine.
6. My Windows 10 version is:
![image](https://user-images.githubusercontent.com/36701310/36544236-44a03eea-17e6-11e8-80e8-be9f7020d2f4.png)

7.  I am running a 64-bit windows system.
8. Here are the results of the wavebox.io ping:
![image](https://user-images.githubusercontent.com/36701310/36544377-a11481a4-17e6-11e8-9b78-c2d8d03024d2.png)

Hopefully you can help me here. Thank you very much!

**Comment by Thomas101** [comment]
Thanks for the info. If you open `C:\Windows\System32\Drivers\etc\hosts` with notepad do you have a record for `wavebox.io` in there pointing to `88.99.194.99`?

**Comment by tbsnkwlsk1** [comment]
exactly, i have. i added this some time ago because the wavebox server were down and they told me to do this via twitter.

![image](https://user-images.githubusercontent.com/36701310/36548953-cda2db70-17f1-11e8-8a90-f5ddc07e1278.png)

**Comment by Thomas101** [comment]
Stick a `#` in front of that line or remove it completely and it should work again. You might need to restart after saving the file - depends how windows is caching it

**Comment by tbsnkwlsk1** [comment]
yes i removed it and also added an account to wavebox. works perfectly! thank you very much Thomas and have a nice rest of the week!
