### ISSUE TITLE
Instagram with Multiple Accounts

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#592]
Wavebox could be the perfect solution for Instagram Desktop usage. If it had the user agent option as I described in issue #185 and the ability to do Multiple Accounts in the services style that GMail accounts can do.

I created a quick&dirty screenshot of what I mean and attatched it below.

If you could make it so that Instagram would have 1 entry on the sidebar but access to switch between accounts in the top navbar like how you can with GMail that would make the service much more powerful than any other option.

The #185 part is needed as well because that is the only way to upload to Instagram from the desktop but add those together and you have a fantastic solution!

![instagram-multiple-accounts](https://user-images.githubusercontent.com/1056731/36494067-b10b4ae8-16f6-11e8-9367-07d6e8b4f2da.jpg)

**Comment by Thomas101** [comment]
#185 is in master ready to ship in the next beta. I guess we should probably look at auto spoofing the user-agent as android anyway.

As regards the grouping, we've got a little bit of redesign work to do to give more flexibility around arranging accounts. We're not sure how we're going to do it yet, but it will either be the ability to add accounts to an existing grouping, or just a free-for-all grouping type thing.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account by right-clicking on one of the tabs and picking `Add another service`

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by MichaelTunnell** [comment]
I just tested this and while this new feature is cool, it doesn't accomplish what is requested in this issue.

This would be good if a user wanted to have a single sandbox for a variety of different services but this request is for the reverse. If a user wanted a bunch of services all in the same sandbox for a single entity/company then this would work great.

I was wanting to have a single Instagram item on the sidebar and then multiple sub-services that I could use for various accounts. Due to the sub-services all using the same sandbox and thus the same login details, the multiple accounts approach is not possible with this implementation.

**Comment by Thomas101** [comment]
Okay, I follow you. This is the same underlying issue as #732 then.

We're trying to figure the best way to present this because there's definitely a use case for both but bubbling that up in an easy enough way that makes sense is a challenge.

Maybe just a simple checkbox to isolate a single service would work. There wouldn't be any sharing between services in an account, but it would let you for example, add multiple Instagrams into a single group.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!

**Comment by MichaelTunnell** [comment]
This works great! Thank you!
