### ISSUE TITLE
Is there a keyboard shortcut for "Copy current url".

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#595]
The ability to copy the current url would be awesome for scripting.  I have a personal automation script that adds urls to Google Inbox as a Reminder to read later. I'd love to be able to send a page I'm viewing in Wavebox the same way.  All I need is a keyboard shortcut. 😄 

Best!
Jeremy

**Comment by Thomas101** [comment]
There isn't at the moment, but it should be easy enough to add in!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.10.4. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Tests:

Windows 10 1709 (16299.251) - assigned Ctrl+Shift+C - Went to gmail inbox and copied url with keybinding and pasted inside atom editor. **OK!**

macOS High Sierra 10.13.3 - assigned Cmd+Shift+C - Went to gmail inbox and copied url with keybinding and pasted inside atom editor. **OK!**

**Comment by GollyJer** [comment]
I'm having a strange issue.  
Can't edit any of my keyboard shortcuts and `Copy Current Tab URL` doesn't have a default entry.
![2018-03-09_15h12_45](https://user-images.githubusercontent.com/689204/37227803-77a7762e-23ac-11e8-93dd-8dd538bed1a8.png)

**Comment by nmat** [comment]
@GollyJer by default the shortcut does not have a set item. You need to type in the keyboard shortcut you want to use with the keyboard. (for example you can't hit Ctrl+Shift+V instead you need to type it in by hand)

**Comment by GollyJer** [comment]
Ha! Funny.  I would have never tried that for some stupid reason.
Thanks @nmat 

@Thomas101 
It's working great thanks!

**Comment by nmat** [comment]
Just happy you got it working. :)

**Comment by Thomas101** [comment]
@GollyJer glad you got it working. We didn't assign a default shortcut as we're running out of key combos :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
