### ISSUE TITLE
Grammarly - disable for specific accounts

### ISSUE THREAD

**Issue by sdmullen** [wavebox/waveboxapp#596]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.10.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS 10.13.3

Hi, great app! 😄👌 I'd like to disable Grammarly for specific accounts, primarily chat accounts like Messenger. Is this possible, and if not, could this be implemented? Like an extensions settings tab/area.
Thanks!

**Comment by nmat** [comment]
aren't you able to do that in the extension toolbar?

**Comment by sdmullen** [comment]
Not that I can see? The extension toolbar just takes you to the Grammarly website.
In Chrome, you can set the extension to ignore websites.

**Comment by sdmullen** [comment]
Ah yes, it looks like there is a power off icon next to the Grammarly icon when you hover over it.
Thanks!
