### ISSUE TITLE
Feature request: In indexed services (right click -> delete) removed the complete account

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#598]
* Which version of Wavebox are you using?
3.10.0

* Which Operating System are you using?
Windows 10

* Description:
I wanted to remove the onenote indexed service in office365. Noticed that when right clicking and clicking delete on the indexed service it removed the whole office365 account.

Is this intentional?

**Comment by Thomas101** [comment]
It is at the moment. It's not very clear what it's doing though and we could add the option to have both

**Comment by nmat** [comment]
Interesting. Maybe it would be better to have some sort of "Remove" or Disable. Because the indexed service right click _I_ would consider should only affect the index service and not the whole account. hmmmm

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
