### ISSUE TITLE
Google Calendar Notifications

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#6]
Look to see if we can add support for Google Calendar notifications in the same way we have Gmail & Inbox notifications. [Tweet](https://twitter.com/madebyalexander/status/849306209970769920)

**Comment by twistedspur** [comment]
I don't think Google Drive notifications are working either. At least, I got a Google pop-up saying "enable notifications" but after clicking, it said "unable to ..." or something similar. Pretty sure that was in the Drive service (I might be mistaken - otherwise I was in Gmail).

**Comment by Rogant** [comment]
can i help?

**Comment by Thomas101** [comment]
Hi we've just added some improved support for Google Calendar to the latest beta (3.3.4). There's some information on how to switch to the beta channel and download the latest version [here].

If you'd like us to extend your trial so you can give it a try,
* Make sure you're signed into your Wavebox account by opening settings and then clicking the Wavebox tab. If you're signed in, your email address will be in the top right
* Send a message to [support](https://wavebox.io/support) with the email address you're signed in with and link to this issue.

Thanks
