### ISSUE TITLE
Feature Request: Add 'Hangouts Chat' as an account Service

### ISSUE THREAD

**Issue by dep** [wavebox/waveboxapp#600]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.10.3beta

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS v10.13.3

It would be nice to see the new 'Hangouts Chat' added as a Service that I can run in a tab, just like Google Keep, Calendar, etc.

http://chat.google.com/

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
