### ISSUE TITLE
Wavebox deletes emails automatically, without my consent.

### ISSUE THREAD

**Issue by Evertt** [wavebox/waveboxapp#601]
* Wavebox 3.10.0
* macOS 10.13.3

Sometimes Wavebox deletes an email automatically. I saw emails disappear a few times right before my eyes and I had no idea where they had gone. Just now I found them back in the trash. Please fix that, because I've missed a lot of emails because of this.

**Comment by Thomas101** [comment]
Hi, which account type did you see this with (e.g. Google, Microsoft etc). Do you have any extensions installed?

**Comment by Evertt** [comment]
Google Inbox. And I have the `Markdown Here` extension installed.

**Comment by Thomas101** [comment]
Do you see the same behaviour in chrome? Wavebox doesn't actually have write permission into your Google Inbox account it only requests and receives the read permission. (You can verify this through your Google Account settings, then `Apps with account access`).

Sometimes you can see the following behaviour...
1. Launch Wavebox
2. Disconnected from the internet/sleep computer
3. On a different device mark emails as done/move to trash
4. Reconnect to the internet with Wavebox. When Inbox reconnects to Google, it updates the UI which can make it appear that emails are disappearing, but is actually just updating to reflect the changes made on a different device

**Comment by Evertt** [comment]
> Do you see the same behaviour in chrome? Wavebox doesn't actually have write permission into your Google Inbox account it only requests and receives the read permission.

I don't fully understand this. Then how is it that I can perform actions on my mails in wavebox? And if I can perform actions on my mails in wavebox, isn't it then possible that wavebox performs those same actions?

> Sometimes you can see the following behaviour...
>
> 1. Launch Wavebox
> 2. Disconnected from the internet/sleep computer
> 3. On a different device mark emails as done/move to trash
> 4. Reconnect to the internet with Wavebox. When Inbox reconnects to Google, it updates the UI which can make it appear that emails are disappearing, but is actually just updating to reflect the changes made on a different device

I know what you mean, but this is surely not happening here. This happens immediately after the email enters my inbox. I haven't opened any other app on any of my devices. I also just checked if maybe I had set up some weird filter in gmail that would automatically delete certain emails, but that is also not the case.

**Comment by Thomas101** [comment]
Wavebox hosts Google Inbox in a similar way to how your web browser does. This is how it displays the content you see and gives you the ability to action your emails. The integration layer that Wavebox puts ontop of this uses the Gmail API which is how it displays additional information, notifications etc, which only asks for the read only permission.

There's a few things to try, that might help us get to the bottom of this...
1. Restart Wavebox
2. Open inbox.google.com in your web browser and see if the behaviour is the same there
3. In Wavebox, go to add a new account but add a "Any Weblink" account. Use https://inbox.google.com when it asks for the URL, sign in and see if the behaviour is the same

**Comment by Evertt** [comment]
Restarting wavebox doesn't make a difference. By the way, this thing only seems to happen with emails that I receive from github. Notifications on issues and pull requests and such.

I haven't had the time to try out the other 2 things unfortunately. I'm kinda swamped with work these days and I'm trying to grab any relaxation-time I can get. I hope you guys can figure something out with the info I've given so far. Again I'm sure it's not another app I have. It might be a gmail extension, but I haven't added any new gmail extensions in ages and this behavior is fairly new.

**Comment by Thomas101** [comment]
Thanks. Until there's more info about the behaviour in your web browser there's little to differentiate whether this is an issue with Wavebox or Google Inbox. I will close this off for now but feel free to follow up at anytime
