### ISSUE TITLE
popout goes fullscreen if main window is fullscreen (macOS)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#602]
* Which version of Wavebox are you using?
3.10.4 beta

* Which Operating System are you using? 
macOS

* Description:
If main wavebox window is fullscreen the new popout notification will go to fullscreen at some point also.

Tested to have wavebox in non fullscreen and then the popout works just fine. This seems to happen on macOS from what I can see but not tested on windows 10 properly.

**Comment by Thomas101** [comment]
I suspect it's only macOS but let me know if you see it on windows

**Comment by nmat** [comment]
Fullscreen on windows seems different in the sense of how the taskbar is being shown. I suspect the same as you. Tried to reproduce it here on: 1709 (16299.251) but it seems to work just fine here.

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this in Wavebox 3.10.5. Thanks

**Comment by nmat** [comment]
Verified working! thank you
