### ISSUE TITLE
Google - account setting (Open new windows in which Browser) not respected for quicklinks

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#603]
* Which version of Wavebox are you using?
3.10.4 beta

* Which Operating System are you using?
windows 10 and macOS

* Description:
In github mails you can get a "qucklink" to "View Issue" or "View Pull Request" which always opens in wavebox and not in default browser no matter how you change the setting.

![image](https://user-images.githubusercontent.com/383031/37228276-5aa4ed7a-23e0-11e8-8b30-466461e92d22.png)

Tested on both platforms and still it opens the link in wavebox browser.

Also tested to change between them and restart wavebox but still wavebox is being used as default browser for the quicklinks. Going inside the mail and clicking "View on github" does work though. Only the quick labeled links in the mail subject that does not work from gmail.

**Comment by pbecotte** [comment]
I am on 3.10 and seeing this for all slack links- they all open in wavebox regardless of the account setting (unless I manually right click and choose "Open in Browser"). Is it the same issue or should I create a separate ticket?

**Comment by Thomas101** [comment]
@nmat we’ve just released a fix for this in Wavebox 3.10.5. Thanks

@pbecotte can you open up a separate ticket? I'll take a look at it as I think it's probably something different to this issue

**Comment by nmat** [comment]
Verified and working on macOS and Windows 10 in 3.10.5beta. Thank you

**Comment by nmat** [comment]
verified on ubuntu 17.10 snap package also.
