### ISSUE TITLE
Version 3.10.4beta is crashing every ten or so minutes on MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#606]
* Which version of Wavebox are you using? [Version 3.10.4beta]

* Which Operating System are you using? [MacOS Sierra 10.12.6]

I just updated Wavebox this morning, and now it crashes periodically (every 10 or so minutes) without any input from me. The window just closes itself without any warning, and on relaunch no issue discovery notification is displayed. The previous version did not have this issue so it must have been introduced with the update

Pls have a look. 
BTW is it possible to downgrade Wavebox to the previous version?

**Comment by Thomas101** [comment]
Thanks for reporting...

To downgrade...
**Stay on the beta channel (3.10.3 beta)**
1. Start Wavebox
2. Go to Settings > Advanced
3. Disable `Check for Updates`
4. Download 3.10.3 beta from here https://github.com/wavebox/waveboxapp/releases/tag/v3.10.3
5. Replace the current version in applications with the downloaded one

When the next version gets released though, you'll need to re-enable `Check for Updates` to get the download

**Go back to Stable (3.10.0)**
1. Start Wavebox
2. Go to Settings > Advanced
3. Change the `Update Channel` from `beta` to `stable`
4. Download the latest stable from [wavebox.io/download](https://wavebox.io/download)
5. Replace the current version in applications with the downloaded one

As for the bug itself, it would be great to have a bit more info so we can try to get to the bottom of it.
1. How many accounts, and which ones do you have added? (e.g. 2 Gmail, a Google Inbox etc)
2. Does launching Wavebox, doing nothing with it but waiting 10 minutes produce the bug?

**Comment by russtaylor** [comment]
I'm encountering a very similar issue - I've noticed it specifically happens when I'm in a Slack window and someone shares some media. It causes WaveBox to crash & exit with no warning or error message.

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this in Wavebox 3.10.5. Thanks
