### ISSUE TITLE
Rollback button #feature #bug

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#608]
* Which version of Wavebox are you using? [e.g. 3.10.4beta]

* Which Operating System are you using? [Mac OSX 10.13]

Have no idea why, but on my Mac WaveBox latest beta release sometimes crashed, also freezy after sleep mode.

It will be really helpfull button to rollback to previous beta release with mark like ignore last release from which you roll back =)

**Comment by Thomas101** [comment]
Hi, we’ve just released a fix for this in Wavebox 3.10.5. I'll add some instructions on how to roll back to a previous release to the KB. Thanks
