### ISSUE TITLE
Slack accounts not respecting "browser" setting

### ISSUE THREAD

**Issue by pbecotte** [wavebox/waveboxapp#609]
* Which version of Wavebox are you using? 3.10.0

* Which Operating System are you using? Ubuntu 17.10 + KDE

Over the last couple days, all links that I click on in Slack are opening in the Wavebox browser, which is different than had been happening previously. I have tried changing the setting from "Default Browser" to "Wavebox Browser" and back again, reloading the account, and reloading the whole app with no changes. Right clicking on a link and choosing "Open in browser" does work correctly.

Interestingly, the "About" system shows 3.10.0 as "up to date" while I see other comments on here about 3.10.5...

**Comment by Thomas101** [comment]
Thanks for re-raising. I think this is a different issue to those seen with the beta channel. We've moved some code around there and it was those changes that made the break there.

It could be that slack has changed some of the url opening code their end so we're not picking it up correctly. Do you have an example link and where it's opened from? For example, just a link pasted into a conversation and `https://wavebox.io`? I'll see if I can reproduce the issue

![screen shot 2018-03-13 at 14 23 41](https://user-images.githubusercontent.com/103586/37347620-24c121aa-26ca-11e8-8097-feff1d27a26b.png)

**Comment by pbecotte** [comment]
Most of the links I click wind up being github links, but all the links I have tried have the same behavior, and it is every link posted in every slack conversation.

Hopefully just something broken on my end ;)

**Comment by Thomas101** [comment]
It's probably worth checking what you wire config is. If you go to Wavebox Settings right at the bottom there's a version number along with a `Wire Config Version`. Is that 1.3.5 or 1.4.0?

If you paste the link to this issue into a conversation as so....
![screen shot 2018-03-13 at 14 46 32](https://user-images.githubusercontent.com/103586/37349024-640f5e78-26cd-11e8-94d9-3c40229ab116.png)
...then click on either the link above or expanded link what happens?

**Comment by pbecotte** [comment]
Wire Config Version is 1.3.5

Clicking the link to this issue pops up a wavebox browser window instead of opening a tab in Chrome.

**Comment by Thomas101** [comment]
I'm struggling to reproduce this here. There must be something that I've got setup differently to you. 

- Do you have any extensions installed in Wavebox?
- If you right click the link and pick `Copy Link Address` does it come up with https://github.com/...etc or something different?

I've tried the behaviour with 3.10.0 (stable) and also the latest beta but see the same between the two. If you wanted to, you could try the beta channel to see if that makes any difference, although I can't think of any specific fixes for this. There are some instructions on [how to switch channel here](https://wavebox.io/kb/beta-channel).

**Comment by pbecotte** [comment]
No, I don't think I have any extensions installed (I didn't know that was a thing).
Copying the address with the context menu comes up exactly as you would expect.
I installed wavebox using snap.

So, if this doesn't seem to be a widespread thing... I guess I will try uninstall/reinstall.

**Comment by Thomas101** [comment]
It might be good to take a look at the settings that you've got configured in case there's an edge case we're not looking for. If you open up settings and then click the `Export Data` button, this will prompt you to save an export of your Wavebox config. (It should remove the auth keys from the config, but feel free to munge anything up that looks like a token). Then would you able to upload the file [here](https://goo.gl/hu1HMO) I'll take a deeper look into what's happening.

**Comment by pbecotte** [comment]
So, today I rebooted my computer and it is working normally again. I have no idea what I did, but it seems pretty clear that this isn't a problem with Wavebox in general lol. Sorry to take up your time!

**Comment by Thomas101** [comment]
Weird! Glad you got it working though - let me know if it crops up again!
