### ISSUE TITLE
Only notify for mentions in Slack

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#61]
At the moment Slack lights up anytime someone talks, it would be nice if it did this only when my name has been mentioned (when slack itself shows the red icon on a channel).

**Comment by jacksarick** [comment]
That's not a setting in Wavebox, it's a Slack setting. Top left corner, there is a little bell (🔔) that opens the notifications menu. Go to `🔔 > Your notification preferences > Send notifications for all...` and adjust the filter.

**Comment by Naatan** [comment]
I know, that's what I am talking about. I have it set to "Direct messages and highlight words", but in Wavebox the Slack icon gets a red circle anytime someone speaks in any channel I'm in.

**Comment by Thomas101** [comment]
I'm guessing this is as regards the dot change indicator? I'll add a setting in to turn this off :)

**Comment by Naatan** [comment]
Thank you!

**Comment by Thomas101** [comment]
This has been added into 3.1.4 which is now live. You can disable the unread activity by right clicking on the account in the left hand side, and then Account Settings. Under the Badges and Notifications section there are two options, so you can turn it off from the sidebar and also the app badge.

Wavebox should update automatically after a while, but if you want to hurry it up, just restart the app and it will re-check
