### ISSUE TITLE
Inbox link save support

### ISSUE THREAD

**Issue by mantzas** [wavebox/waveboxapp#610]
* Which version of Wavebox are you using? 3.10.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Macos high sierra, Windows 10 and Xubuntu

Inbox supports adding link from the clipboard as link and not reminders. Wavebox does not show this option when clicking the plus button in the bottom left corner.

**Comment by Thomas101** [comment]
Going to close this as Google are now [retiring Inbox](https://support.google.com/inbox/answer/9117840/?hl=en-GB)
