### ISSUE TITLE
wavebox memory leak

### ISSUE THREAD

**Issue by khusmann** [wavebox/waveboxapp#611]
I'm on wavebox 3.10.5, but I *think* this started happening when I upgraded from 3.10.0 to 3.10.3. I'm running Ubuntu 17.10

For unknown reasons, wavebox will suddenly start using all my memory, slowing the machine down and making it unusable in about 30 seconds. If I'm lucky, I can launch xkill and kill it before everything locks up, otherwise I have to hard reboot. This happens about once a week, although it just happened twice in 24 hours.

**Comment by Thomas101** [comment]
Hey, would be good to know a little bit more about your setup, so we can see if we can reproduce...
* How did you install (e.g. deb, tar, snap)?
* What's the size of the [Wavebox data folder](https://wavebox.io/kb/data-locations)?
* How many accounts do you have added, how many are sleeping?
* Do you have any extensions installed?
* Do you do anything noticeable before it happens, or does it just appear to happen randomly?
* If you open up your Wavebox Settings, then go to Advanced. Right at the bottom there's a `Write app metrics log` button which will dump your app metrics every hour or so. Would you be able to turn this on and then after the crash send us the log file?

**Comment by khusmann** [comment]
great, thanks!

1) Installed via deb
2) 1.6M
3) 8 accounts, 4 are usually sleeping
4) No extensions
5) Nothing noticeable -- except it usually happens when I'm not actively using wavebox
6) Just enabled it! I'll post when I get another crash.

**Comment by khusmann** [comment]
Ok it just died again... and I think we were lucky because the last line in the metrics.log is exactly when it crashed. This was the last line in metrics.log (I removed the number that looks like some kind of ID):

Thu Mar 15 2018 14:40:04 GMT-0400 (EDT) : <ID HERE> : [{"memory":{"workingSetSize":92652,"peakWorkingSetSize":95324,"privateBytes":48860,"sharedBytes":43792},"cpu":{"percentCPUUsage":0,"idleWakeupsPerSecond":0},"pid":28540,"type":"Browser"}]

Let me know if you need the whole thing, and if so what address I should send it to.

**Comment by khusmann** [comment]
Ok, crashed again -- I think it's happening when it's been unfocused for a while, and then I bring the focus back? I'll keep playing with it...

**Comment by Thomas101** [comment]
Thanks for sending those. It would be good to grab the whole file, I can take a look to see if there's any specific tab using more than it should be. Can you drop me a message through https://wavebox.io/support and I'll pick this up? Thanks!

**Comment by khusmann** [comment]
With help from Tom I discovered that my machine didn't have swap enabled -- during my last upgrade of Ubuntu the distro switched from swap partition to swapfile, but my machine somehow slipped through the cracks and I got neither. after uncommenting lines in /etc/fstab and /etc/crypto, it appears everything is fixed! Thanks Tom!
