### ISSUE TITLE
Confirmation account deletion dialog

### ISSUE THREAD

**Issue by khusmann** [wavebox/waveboxapp#612]
I wanted to change some settings on an account so I right-clicked on it and was going to click "settings", but I accidentally clicked "remove account" instead and it instantly deleted the profile so I had to set everything up for that account again. Could you add a "Are you sure?" sort of dialog there before it actually removes the account to prevent this sort of thing? Cheers!

**Comment by Thomas101** [comment]
Was this on the stable channel? The beta should have this already, and the upcoming beta has more info about deleting an account & 5 services etc, vs deleting a single service

#598 #534

These are the updated screens from master...

![screen shot 2018-03-16 at 08 48 08](https://user-images.githubusercontent.com/103586/37511468-cf0ba58a-28f6-11e8-8844-279b4ae89e54.png)
![screen shot 2018-03-16 at 08 48 15](https://user-images.githubusercontent.com/103586/37511469-d0cd0152-28f6-11e8-870d-a891a76eaa5b.png)
![screen shot 2018-03-16 at 08 48 21](https://user-images.githubusercontent.com/103586/37511472-d21c6994-28f6-11e8-8af8-457fe6956a82.png)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by khusmann** [comment]
Wonderful, thanks!
