### ISSUE TITLE
Trello PDF previews are broken

### ISSUE THREAD

**Issue by celina** [wavebox/waveboxapp#613]
* Which version of Wavebox are you using? 3.10.5beta

* Which Operating System are you using? MacOS 10.13.3

Trello has stopped displaying PDF previews with the recent updates this week. The preview box opens but the content never loads.

gif of the documented behavior attached below:
![wavebox-bug-trello-preview](https://user-images.githubusercontent.com/58040/37531126-406b0c54-2909-11e8-9841-e40b01dd44cc.gif)

**Comment by Thomas101** [comment]
Thanks, we managed to add this in during the current beta cycle (#169), but it's proved problematic. We've added some improved support for opening pdfs in the next beta, they're not in-situ at the moment but we're working on that

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
