### ISSUE TITLE
MacOS - taskbar right click changes desktop? 

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#614]
* Which version of Wavebox are you using?
3.10.5beta

* Which Operating System are you using?
macOS

* Descrption:
When wavebox is in fullscreen and you right click the taskbar icon to get options or similar...instead it will switch to another desktop.

It might be good to kill the process of right click or say it does not do anything instead of jumping the screen. (Taskbar I mean the top bar of macOS)

**Comment by nmat** [comment]
Hmm I actually in a way like how the behavior is but not sure if it is intentional?

**Comment by Thomas101** [comment]
That's the desired behaviour. It should focus or hide the app depending what state it's in. There are also some configuration options under settings if you just want to hide or show etc.
