### ISSUE TITLE
Keyboard shortcut to open wavebox mini (Linux)

### ISSUE THREAD

**Issue by rajalokan** [wavebox/waveboxapp#615]
* Which version of Wavebox are you using? [3.11.0]

* Which Operating System are you using? [Ubuntu 16.04]

Apologies if it is already there but I couldn't find how to configure a keyboard shortcut to open Wavebox mini. If not, this should be very handy feature.

Cheers

**Comment by Thomas101** [comment]
Added this in for the next release. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> once it goes out :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.13.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
