### ISSUE TITLE
fullscreen/maximize view of wavebox

### ISSUE THREAD

**Issue by lmckeen** [wavebox/waveboxapp#616]
* Which version of Wavebox are you using? 3.11.0
* Which Operating System are you using? Mac OSX 10.13.1

when in fullscreen/maximize view of wavebox you can still move the window around the screen causing issues like the one show below

<img width="1439" alt="screen shot 2018-03-20 at 1 30 17 pm" src="https://user-images.githubusercontent.com/11928027/37668421-3d058c00-2c43-11e8-86b0-df93d5a5ceb3.png">

**Comment by Thomas101** [comment]
Thanks, seeing the same here. I'll try and patch this!

**Comment by Thomas101** [comment]
Hi we've just pushed 3.12.0 out which has a fix for this. Thanks!
