### ISSUE TITLE
Detect network change (ie: laptop waking from sleep) and refresh

### ISSUE THREAD

**Issue by jpage4500** [wavebox/waveboxapp#617]
I'm using version 3.10.0 and just noticed there's a 3.11.0 so I'll update now.. assuming this wasn't added in the meantime though - can the app detect when the network connection changes and refresh the accounts?

I've noticed when opening my laptop I'll have to manually refresh to get my new gmail messages. I'll click on the Inbox link and I'll get new messages.

Can the app do this automatically? I assume you can't detect when a laptop is waking but I do think you can detect network connectivity changes. It seems like whenever the network connection changes though would be a good time to do a refresh anyway to get anything missed while offline. Does that make sense?

thanks
joe

**Comment by Thomas101** [comment]
It should normally detect the connection change - but does sometimes take a few moments to kick in.  It would be great to know a little bit more so I can try to reproduce the issues...
* Of the two networks that you're using, do you know if either of them are using a vpn or proxy?
* Does the Wavebox unread count update automatically (e.g. the count on top of the accounts in the left sidebar?)

**Comment by jpage4500** [comment]
Actually - just a single network (wifi). I just noticed that when I opened my laptop I didn't get any new messages and had to manually refresh.

If it does just take a few seconds to detect this that's fine - it just seemed like nothing was happening once the network came online

**Comment by Thomas101** [comment]
From testing here, it can sometimes be 10-30 seconds before everything wakes back up properly. It just depends on the timeouts and waits that gmail/google inbox etc, have for reconnecting. As a rule of thumb the longer the device has been offline the longer they throttle the reconnection retries.

Try waiting a little next time your re-open to see if it does reconnect successfully on its own. If it doesn't let me know and I'll take a deeper look into it

**Comment by jpage4500** [comment]
Hi @Thomas101 - I just tried this and I do think this is a valid issue IMO.

Here was my test.. 
- I opened my laptop (Macbook Air) after being closed all night. 
- I watched the wifi menu bar icon to make sure wifi connected
- I watched the Wavebox app to see how long it took to refresh my Gmail Inbox
- After over a minute I gave up and clicked on "Inbox" label - the inbox refreshed immediately

I think/believe Wavebox is using an embedded browser inside of the app -- and the browser itself isn't automatically detecting the connection change or if it is nothing is happening.

I would think the app itself could detect this connection change and do something like refresh the browser's page?

**Comment by Thomas101** [comment]
Thanks, I'll take another look at this to see what's happening under the hood

**Comment by Thomas101** [comment]
@jpage4500 are you still seeing this with the current version of the app?

**Comment by jpage4500** [comment]
This issue has been fixed as far as I can tell.. I haven't had to do a manual refresh in a long while

**Comment by Thomas101** [comment]
Awesome, thanks for the update!
