### ISSUE TITLE
3.10.4beta through 3.11.0 crashes/hangs

### ISSUE THREAD

**Issue by bbluemel** [wavebox/waveboxapp#618]
* Which version of Wavebox are you using? Any post 3.10.3beta

* Which Operating System are you using? Windows 10

3.10.4beta would crash entirely (closing wavebox), 3.10.5beta stopped the crash, however, instead of crashing the open window would hang (e.g. in gmail/slack etc)

3.11.0 stable still hangs for me soon after launching, so I've had to go back to 3.10.3beta as any past then are unusable.

Generally the hang will happen if I'm typing in the window (e.g. an email, or a messenger message).

I have 3 Inbox, 1 Gmail, 4 slack, 1 FB Messenger windows, and a few other (mostly inactive) web pages.

The only settings I can think of that I have different from the defaults are:
- Show titlebar off (have had this for months so don't believe it's the cause)
- Hardware acceleration off (I have this set because I use my GPU (GTX1080) for mining, and wavebox gets really unresponsive in slack when mining if this is turned on - laggy keyboard inputs etc), again this has been off for months without issue.

On (and up to) 3.10.3beta has been fine for a very long time.

**Comment by Thomas101** [comment]
Hey, thanks for reporting and for the info. I have a suspicion as to what the hang may be, would be good to have a little bit more info about your setup though so I can try to reproduce.
* If you disable the spellchecker under settings and restart the app does the hang no longer happen?
* Does it hang permanently or does it wake back up after a little time?
* If you try it without your gpu mining does it still hang?

**Comment by bbluemel** [comment]
Hi Thomas,

Thanks for your reply.

I have upgraded again, and have disabled the spell checker, and so far so good.  Will keep using it for the rest of the day and see if I get any hangs.

The hangs did seem permanent previously, however, I would generally quit wavebox (from the tray icon) fairly soon after - as I was often in the middle of typing something at the time that I wanted to finish.

When I was upgraded to 3.11, it was after a reboot and I got the hang very quickly, I hadn't started GPU Mining at that point, so doesn't seem affected by the Mining.

**Comment by Thomas101** [comment]
Thanks for the info. The spellcheck service works in two modes, out-of-process and in-process. When a page loads up it uses the out-of-process spellchecker - which is slower to check spelling and can sometimes cause laggy typing. Once you've typed your first few words the app initializes the in-process spellchecker which is faster at spell checking, but does take a few moments to warm up.

It sounds like during the warm up of the in-process spellchecker is when you're seeing the freeze.

I'll add an option in to only use the out-of-process spellchecker as a quick workaround, but it would be great to get to the bottom of the issue so we can solve it for real.
* Are you using 32-bit or 64-bit windows?
* Do you know if you installed the 32-bit or 64-bit version of Wavebox from the website?
* Would you be able to give the following a try
  * Re-enable spellchecking & restart Wavebox
  * Hit <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Delete</kbd> and then click on the performance tab
  * Type a few words until it hangs and then wait 15-30 seconds
  * Send a screenshot of the gpu, memory, and disk graphs from the task monitor

Thanks!

**Comment by bbluemel** [comment]
I'm using 64 bit windows, along with 64bit Wavebox.

Screenshots about 30s after hang
CPU:
![image](https://user-images.githubusercontent.com/482215/37706654-3b2d531c-2cf8-11e8-9a6f-9335333e1555.png)
Memory:
![image](https://user-images.githubusercontent.com/482215/37706683-46f8b452-2cf8-11e8-8339-d777d970620e.png)
GPU (not mining at the time):
![image](https://user-images.githubusercontent.com/482215/37706696-50333cd6-2cf8-11e8-98a0-e849672d40e0.png)

Whilst getting these screenshots sorted any typing this out the hang has not stopped (I used a FB Messenger window).

Thanks

Ben

**Comment by Thomas101** [comment]
Thanks, I've put a patch in to use out-of-process only and that should go out in a release shortly. Still struggling to find the root cause though. I can't see anything obvious from your activity monitor logs etc. All looks normal.

Can you send a screenshot fo your language configuration under settings? Maybe it's down to one of the dictionaries :-/

**Comment by bbluemel** [comment]
I considered that also after sending those screenshots, I'm using English UK, but also tried English US but still got the hang.

![image](https://user-images.githubusercontent.com/482215/37707319-a8d9de10-2cfa-11e8-84ed-f84160747a9b.png)

**Comment by Thomas101** [comment]
Thanks for all the info! Still working to get a reproducible case our end at the moment.

* When it freezes are you able to switch account using the buttons in the left sidebar or is it a complete full freeze?
* If you right click in the messenger frame, then pick `Inspect`, then click on the console tab and try typing again do you see any errors come up?

**Comment by bbluemel** [comment]
Yup, can switch accounts fine, the whole wavebox ui is still responsive, just the individual account locks up - typing in another account will also lock up.

Nothing new gets output to the console from starting typing to the hang (tried looking in the consoles from multiple accounts, along with the main wavebox console).

**Comment by bbluemel** [comment]
Hi Thomas,

I've tried the one you have provided. Unfortunately that one also hangs when typing.

**Comment by Thomas101** [comment]
Okay, thanks. I'll keep digging a bit deeper. We've added the setting in to disable in the in-process-spellchecking. Will push a release out tomorrow morning with that all being well.

**Comment by Thomas101** [comment]
Thanks for all the testing and info. We've just pushed 3.12.0 out. This has the option to disable the in-process spellchecking, which should mean that you can get up and running again. To disable, go to Settings > Advanced and then turn off `In process spellchecking` and restart the app.
![screen shot 2018-03-22 at 08 53 07](https://user-images.githubusercontent.com/103586/37760466-adfb63d2-2dae-11e8-9180-e24c7b8d9ceb.png)

We'll keep looking into this though to find the root cause though and hopefully have a full-blown fix shortly

**Comment by bbluemel** [comment]
Hi Thomas,

Just installed it, and seems to be working fine so far.  👍

**Comment by Thomas101** [comment]
@bbluemel we've pushed a permanent fix out for this in 3.14.3 which means you shouldn't see the crash with the `In process spellchecking` enabled. Thanks again for reporting!
