### ISSUE TITLE
Allow tabs on whitelist basis

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#62]
It would be amazing if I could open tabs for certain "apps" (what do you call them?). For example; I added GitHub in Wavebox and one of the first things I do every morning is open up my notifications and open each new one in a new tab, so I basically have a todo list of tabs. In Wavebox this isnt possible since an "app" is tied to a single window, but there's no reason it couldn't have tabs within an "app" that only open for whitelisted domains, and otherwise it would open them in your default browser as it does now.

**Comment by Thomas101** [comment]
I think I get what you mean. Perhaps I could do something to open them up as items in top services bar.

**Comment by Naatan** [comment]
That could work. If you do please allow closing them with middle mouse click.

**Comment by Thomas101** [comment]
Hi, we've been doing some work on some general tab controls in the latest versions of Wavebox. In the current version, you can...
* Add any tab to an account/group so it permanently remains there
* Use recents & pinned to quickly navigate within a tab
* Use tasks to queue up a number of items to read later

There's some more detailed info about these [here](https://blog.wavebox.io/pinned_recents_tasks/). I think with these, they should cover the use-case here and it would be great to know how they work for you.

I'm going to close this off for now, but if there's anything you feel that's missing or needs adding, feel free to recomment or open a new  issue :)
