### ISSUE TITLE
[Feature Request] Custom 'Services' / sub tabs

### ISSUE THREAD

**Issue by mrsafacon** [wavebox/waveboxapp#620]
I would be interested in an account/app type that allows for custom 'services'.
(Like a Google account has multiple service tabs)

For example:
Multiple weblinks available to access as service tabs(horizontal sub tabs) rather than individual apps(main side bar).

**Comment by agence104** [comment]
You guys have any eta for these upcoming features?

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account by right-clicking on one of the tabs and picking `Add another service`

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
