### ISSUE TITLE
Wavebox rpm package

### ISSUE THREAD

**Issue by robertalks** [wavebox/waveboxapp#622]
Hello, I create a small script which can generate rpm package for RPM based distros. I'm using this app, but always have to use the tarball as I'm running openSUSE, so this script, can do just that, generate an rpm package out of the tarball, so the installation looks more 'at home'. You can use the script as is or modify it where need it.

URL: https://github.com/robertalks/wavebox_rpm

If there is something unclear, just drop a comment.

**Comment by Thomas101** [comment]
Thanks very much @robertalks . RPM packages and a Yum repository are now available on our [download page](https://wavebox.io/download)
