### ISSUE TITLE
'Google Voice' service missing. 'Google Chat' service 500 error

### ISSUE THREAD

**Issue by mrsafacon** [wavebox/waveboxapp#624]
Hi, I am requesting support for 'Google Voice' g-suite service.

Also, 'Google Chat' is listed as a service, but the page returns a 500 error. I don't think 'Google Chat' is a g-suite app at all.

**Comment by Thomas101** [comment]
Google voice is on our list to add support for (https://github.com/wavebox/waveboxapp/issues/131).

Chat has been added recently by Google, but is only available on Gsuite accounts (https://chat.google.com/)
