### ISSUE TITLE
Allow slack screen sharing

### ISSUE THREAD

**Issue by silfreed** [wavebox/waveboxapp#625]
* Which version of Wavebox are you using? 3.13.0
* Which Operating System are you using? MacOS 10.13.3

When in a slack call I can do voice and video fine as well as see other people's shared screens, but the option for me to share my own screen is grayed out and says I must launch the slack native app to share my screen.

**Comment by Thomas101** [comment]
Thanks for taking the time to report, I'm merging this issue and a few others which report the same into #912 so we can track progress there and hopefully add support in. Thanks!
