### ISSUE TITLE
bambooHR - does not save domain

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#629]
* Which version of Wavebox are you using?
3.13.0

* Which Operating System are you using?
windows 10

* Description:
Used bamboohr to signin. However it does not save the actual domain for the sign in. The login is saved however. Forgot to mention it is when the application goes to sleep and you have to type in the domain again.

**Comment by Thomas101** [comment]
Thanks @nmat. Just pushed a fix for this. Probably the quickest way to get it, is delete the account, restart and add it again!

**Comment by nmat** [comment]
Worked perfectly! Thank you. Tested and verified.
