### ISSUE TITLE
add 'Refined Twitter' extension

### ISSUE THREAD

**Issue by aditiapratama** [wavebox/waveboxapp#631]
* Which version of Wavebox are you using? 
3.13.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 64 bit

---

Please check and integrate this extension for twitter in wavebox, https://github.com/sindresorhus/refined-twitter
 
Thank you

**Comment by nmat** [comment]
Hello,

There is a issue here on github for request on extensions. Please see:
https://github.com/wavebox/waveboxapp/issues/138

**Comment by aditiapratama** [comment]
hi @nmat thanks you, should I close this issue?

**Comment by nmat** [comment]
You can probably close it. Just add a comment about the extension in the other issue so that the wavebox team can look at it. :)
