### ISSUE TITLE
Wrong Telegram messenger URL

### ISSUE THREAD

**Issue by silver886** [wavebox/waveboxapp#632]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.13.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.13.3

The URL of Telegram messenger should be https://web.telegram.org

**Comment by rhys101** [comment]
Thanks - have updated the correct URL. You can either restart Wavebox for it to refresh quickly, or remove and add Telegram back in again.
