### ISSUE TITLE
Wrong DevDocs URL

### ISSUE THREAD

**Issue by silver886** [wavebox/waveboxapp#633]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.13.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
macOS 10.13.3

The URL of DevDocs should be https://devdocs.io/

**Comment by Thomas101** [comment]
Thanks for pointing this out! Just pushed a fix out. It will auto-update after a while, but if you want the update right away, restart Wavebox or remove & re-add the account
