### ISSUE TITLE
Wavebox mini behavior on Linux

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#635]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.13.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Linux openSUSE Tumbleweed (KDE Plasma 5)

Your presentation about Wavebox Mini shows that, on a Mac, clicking on the tray icon brings up the Wavebox mini window. On linux instead (at least here), clicking on the tray icon show the Wavebox main window. 
If you want to show the Wavebox Mini window you have to right-click the tray icon (which brings up the old menu) and then choose "Show Wavebox Mini". But this is not practical at all. 

Since the menu somehow duplicates the functionality on the Mini window, I think it would be better to eliminate it and instead adopt the same behavior as seen on the Mac.

**Comment by Thomas101** [comment]
In an ideal world, we would love to have the same behaviour across all platforms. The problem that we have is if the OS is using `libappindicator` to provide the tray icon, we don't get click events and are only able to display a context menu. This is why we kept the menu on linux and had it as a popout window. I think I remember reading somewhere that Gnome is trying to provide a consistent look and feel from the tray.

The good news though, is if the os uses `GtkStatusIcon` we can capture the click event and do something with it. This means we can have left click for opening Mini and right click for the current context menu. I suspect as you're using KDE it's going to be `GtkStatusIcon` that gets used.

I've added click support in for `GtkStatusIcon` in, so depending which libraries you're using gives you the best experience we can. We've also enabled pop-out mode on non-linux platforms, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> to toggle Mini and a global shortcut to toggle it even when the app isn't in focus (the keyboard shortcut will need to be set in advanced though)

**Comment by Cris70** [comment]
Thank you @Thomas101 , I'm eager to test this new development in the upcoming beta.
I'll let you know!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.13.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Cris70** [comment]
@Thomas101 thank you very much for this enhancement!
It is working _nearly_ as expected now on my openSUSE KDE box.

My only wish now is that the mini window should open next to the icon in the tray. Instead, it opens at the other side of the screen. I have my main panel (the one which contains the tray) put vertically at the left edge of the screen. When I click on the tray icon, the mini window opens at the bottom-right corner of the screen.

**Comment by Thomas101** [comment]
Unfortunately, we don't get the tray icon position on Linux so we can't auto-position it. We took a guess that most of the time it would be on the bottom right - but obviously it doesn't cover all cases!

You can change the position manually though. If you head over to settings and change the `Popout screen position` to `Bottom Left` it should appear where it needs to

![screen shot 2018-04-11 at 08 38 48](https://user-images.githubusercontent.com/103586/38602864-e776d92e-3d63-11e8-809e-772b9c0c5fbf.png)

**Comment by Cris70** [comment]
@Thomas101 thank you for your help.
I understand your point and I don't know how to solve the problem of getting the tray icon position, but I can tell you it CAN be done, since I am using Insync (a tool that replaces the Google Drive desktop client on linux/windows/mac) and it does a very similar thing: it has a tray icon that, when clicked, pops up a minified application window. Don't know if it is of any help, since Insync is not opensource :(

**Comment by Thomas101** [comment]
There's definitely some additional things to do around guessing where it is. For example, tracking the mouse position in the display and using that as a metric to estimate where the tray icon is.

I was just referring to the api support that electron gives out of the box. On windows and macOS it returns the bounds of the tray icon - which we can then use to work out where to place the tray, however, with GtkStatusIcon we just get bounds of `[0,0]`.

**Comment by Cris70** [comment]
Thank you @Thomas101 
I am quite satisfied with the present solution, so as I am the only one who requested the feature, if you want you can close this issue.
