### ISSUE TITLE
[feature request] - add manual sleep trigger (skip auto sleep but be able to force sleep on service)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#636]
* Which version of Wavebox are you using?
3.13.0

* Which Operating System are you using?
windows 10

* Description:
Sleep function has a 0 value that can be set. IMO that would indicate that sleep is enabled but you set it manually, however after unknown time it still goes to sleep. So the question is what 0 actually means and if so can it be set so that manual sleep/wake up can be set?

**Comment by Thomas101** [comment]
When it's set to 0 it should start sleeping as soon as you leave the tab.

There is the slightly confusing edge case though, that if you have sub-windows open we postpone sleep until these are closed. E.g. in Gmail, Ctrl+Click and compose to get a new window, then try to sleep the account. You'll see it refuses to go. In this case, we lazily retry sleep every 30 seconds. I think this may be the behaviour you're seeing.

There's argument for displaying some kind of message around this, but we thought it would be a bit confusing to try and explain/there's nowhere really intuitive to display the message.

**Comment by nmat** [comment]
interesting. It would be nice if it is possible to set it so that sleep is enabled but triggered manually. So can control it in a more well manual way also. Sometimes I find it would help since some connections you might want to not sleep auto but tell it to sleep on demand.

Or is this just a bad idea maybe?

**Comment by Thomas101** [comment]
Yeah that makes sense. I think it's something we can add in too!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Verified and working on macOS and windows 10

Closing issue.
