### ISSUE TITLE
Change current Url from toolbar in linked accounts: Medium.com Not Possible to sign in via email

### ISSUE THREAD

**Issue by MichaelTunnell** [wavebox/waveboxapp#637]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.13.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
KDE Neon (Ubuntu 16.04)

The way Medium is design, it is pretty much impossible to be used Wavebox via the "Add app" option. Alternatively, which I am doing, It is possible to use the "Add Website" method.

Medium does not use passwords but rather tokens emailed to you per login. You have to click a link in an email to activate a login. 

Due to this method, the Medium app in Wavebox is inaccessible to logins because you can't navigate to specific pages in Wavebox. The navigation bar doesn't seem to allow manual input of navigation.

----

It is possible to do it in the Weblink version because you can:
1. set medium.com as the URL
1. put it to sleep
1. change the URL to the token'd URL in the email
1. verify the account
1. put it to sleep
1. change back to regular medium.com (and done)

**Comment by Thomas101** [comment]
Yeah, you're right there. If you use the other methods (e.g. with Google, Facebook etc...) you should be able to sign in okay.

I think having a way to set the url would be the best fix here. Probably changing the toolbar to be more functional rather than just informational

**Comment by MichaelTunnell** [comment]
> If you use the other methods (e.g. with Google, Facebook etc...) you should be able to sign in okay.

That is probably true, yea. I don't ever use those sign in methods because Google and Facebook have enough information on everyone as it is . . . they don't also need to be the login portal too. (at least not for me. :smile:)

> I think having a way to set the url would be the best fix here. Probably changing the toolbar to be more functional rather than just informational

I agree. The toolbar being a navigation bar would solve that entirely.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
