### ISSUE TITLE
constant cpu usage while idle when using a Trello account

### ISSUE THREAD

**Issue by ni-ka** [wavebox/waveboxapp#639]
* Which version of Wavebox are you using? 3.13.0 installed via AUR package (https://aur.archlinux.org/packages/wavebox-bin/), i.e. not via snap

* Which Operating System are you using? arch Linux (4.15.14-1-ARCH, gnome 3.28, wayland)

Hi,

Wavebox is constantly using CPU while idle. I work on a laptop so battery life is key.

I'm using Wavebox Premium to manage 2 Google accounts (incl. mail, calendar, drive, contacts, hangouts). I use the Boomerang extension, but have tried deactivating it without any effect on the cpu usage.

 I used top to measure the usage:

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                              
28729 nils      20   0 1210612 176076  61920 S   5.3  1.1   0:30.52 Wavebox                              
28733 nils      20   0 1371864 282264  71548 S   4.3  1.7   0:27.66 Wavebox                              
28734 nils      20   0 1359368 275360  68920 S   3.0  1.7   0:24.33 Wavebox                              
28642 nils      20   0 1754756 167564  78504 S   1.3  1.0   0:18.60 Wavebox                              
28645 nils      20   0  336276  28320  24972 S   0.0  0.2   0:00.04 Wavebox                              
28671 nils      20   0  453132  69152  40760 S   0.0  0.4   0:03.66 Wavebox                              
28684 nils      20   0 1536748  71596  50332 S   0.0  0.4   0:00.21 Wavebox                              
28687 nils      20   0 1133392 124068  67436 S   0.0  0.8   0:06.98 Wavebox                              
28690 nils      20   0 1064612  89648  62068 S   0.0  0.6   0:02.77 Wavebox                              

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                              
30377 nils      20   0 1198064 173972  63336 S   6.3  1.1   0:14.27 Wavebox                              
30380 nils      20   0 1336548 244304  72316 S   1.0  1.5   0:09.97 Wavebox                              
30299 nils      20   0 1726868 165364  80048 S   0.7  1.0   0:09.62 Wavebox                              
30385 nils      20   0 1352724 238192  69896 S   0.7  1.5   0:09.06 Wavebox                              
30301 nils      20   0  336276  28536  25184 S   0.0  0.2   0:00.04 Wavebox                              
30326 nils      20   0  449808  67260  42112 S   0.0  0.4   0:01.69 Wavebox                              
30342 nils      20   0 1135956 123088  70344 S   0.0  0.8   0:05.60 Wavebox                              
30345 nils      20   0 1023664  97404  64332 S   0.0  0.6   0:01.21 Wavebox                              

The first process constantly uses 5-10% cpu. All others stay lower, mostly 0.3-2%, but occasionally go to 5% as well.

Any info on how to reduce cpu usage while idle?

Cheers

Nils

**Comment by Thomas101** [comment]
Some of the embedded pages can start churning away at things in the background. You can find a bit more info which tabs are using memory and CPU, by opening up settings and then clicking on the task monitor. What are the main culprits using cpu in that window?

It's worth noting that when the task monitor is open, you normally see the `Wavebox Main` process eat more cpu as it constantly polls the other processes for updates. On my current machine, it goes up from 0.5% to 20% for example.

**Comment by ni-ka** [comment]
Thanks @Thomas101 ! I had read about the task manager in another comment but could not find it in the menu, didn't think it would be on the preferences page.

So it seems that the culprit is Trello. If I add my account, consumption goes up by 5%. I tested with a standalone trello app or with trello open in Chromium and all of them seem to have that baseline cpu usage.

Thanks for the help though, will report this to trello!

**Comment by ni-ka** [comment]
Trello support answered that this is a known issue. 
However, having Wavebox treat the tab as "in background" would solve the issue for the Wavebox side.

**Comment by Thomas101** [comment]
Thanks, I've got a fix for this!

**Comment by ni-ka** [comment]
Awesome, thanks @Thomas101

**Comment by ni-ka** [comment]
Hi @Thomas101 I was able to update to the beta and check. The fix works, i.e. I see the higher Trello-related CPU usage only when its in the foreground. Thanks for the fix and hope they fix that issue on their end soon!

BTW, i do have the impression that Wavebox uses more CPU while idling than opening the same pages in a browser, but I'll open a separate issue for that!

**Comment by Thomas101** [comment]
As for the cpu usage, we share processes between certain tabs, which means CPU can appear higher if there are multiple tabs open in the same process. You can turn this off by enabling `Isolate Account Processes` under settings > advanced but this normally comes at the expense of more memory.

For the sleeping, there was a bug in 3.13.1beta which meant the tabs weren't sleeping correctly but this is fixed in 3.13.2, maybe you saw the tab restoring here (although not restoring, just becoming visible). When Trello usually restores it uses the `Home board` setting under account settings to pick which one to load up.

That said some of the accounts do restore to the last used page, so we could look at adding that in for trello too

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by ni-ka** [comment]
Thanks for the fix @Thomas101 !
