### ISSUE TITLE
Tray icon scaling issue in KDE 5.9.4

### ISSUE THREAD

**Issue by Tunous** [wavebox/waveboxapp#64]
* Wavebox version - 3.1.3

* Operating System - Arch Linux

___

![spectacle d30598](https://cloud.githubusercontent.com/assets/5156340/24967117/5a6bcaae-1fa9-11e7-8f60-9aab049d2c4f.png)

As you can see in the image above the icon is much bigger than the other icons and it looks like the right and bottom parts of it are cut. 

I've set the colors to transparent background and white border but the issue is the same with different colors too.

**Comment by Thomas101** [comment]
Ouch, that's not looking quite right! In the settings under the menu bar section there's a DPI Multiplier dropdown. What's it set to by default & does changing this make any difference?

**Comment by Tunous** [comment]
Not on PC right now but I think it was set to 1 by default. Changing it was just increasing the size of icon + more parts of it were getting cut.

**Comment by Tunous** [comment]
I checked on PC and can confirm that it was set to 1x by default. Here is how it looks with 3x:
![spectacle jd1988](https://cloud.githubusercontent.com/assets/5156340/24975890/99a70d64-1fc7-11e7-8bd9-7d9837673a3c.png)

**Comment by Thomas101** [comment]
Okay, looks like it's just getting bigger and not scaling back down. Thanks. I'll fire up a vm and see what it looks like our end!

**Comment by gusarg81** [comment]
Same is happening to me, using KDE Pasma 5.9.5

**Comment by Thomas101** [comment]
Hi, after looking into this, it looks like KDE uses a different icon size to gnome and unity. I've added an option in to change the icon size manually. When I tried it 28px worked well for the kubuntu instance I was running, but you may find a different size works best for you. Thanks!

 
![screen shot 2017-05-23 at 09 26 45](https://cloud.githubusercontent.com/assets/103586/26345178/fab12f9e-3f99-11e7-9c14-e1148172edbd.png)

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
