### ISSUE TITLE
office365 - mail and service unresponsive for longer times during edit

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#640]
* Which version of Wavebox are you using?
3.13.0

* Which Operating System are you using?
windows 10

* Description:
I was working around with wavebox during the evening yesterday where I just used the hidpi laptop with no extended monitor and noticed some very long repsonse times in office365 and other services.

For example:
Editing a mail in its own wavebox window and then switching to microsoft teams there is a long unresponsive time for the external mail window.

Also noticed the same behaviour in general for wavebox.

**Comment by Thomas101** [comment]
I wonder what this could be. Would you be able to change a few settings under advanced to see if it makes any difference?

First try disabling `Hardware acceleration`, so we can see if it's anything to do with hdpi display.

Then in a separate test give the following a try...
* `Isolate Account Processes` enable
* `Isolate Extension background Processes` enable
* `In process spellchecking` disable

**Comment by nmat** [comment]
Going to run some tests.

First test:
![image](https://user-images.githubusercontent.com/383031/38300743-ea7f3456-37fd-11e8-9735-9723ae7e1e84.png)

Will get back to you when tested properly.

**Comment by nmat** [comment]
With the above information set it seems that wavebox is responsing a bit better. However very early to tell. The reconnect and disconnect seems a lot better and so on. Not sure what the In process spellchecking really does maybe you can explain that or even better maybe have (i) for the items that are in the list there?

Seems like there is some information under Window opening engine but none of the others. I can create a feature report for adding information of each item if you like?

**Comment by nmat** [comment]
testing now with only having "in process spellchecking" disabled. will get back tomorrow about result

**Comment by Thomas101** [comment]
There's a little bit more info about [in-process spellchecking here](https://wavebox.io/kb/in-process-spellcheck). There shouldn't really be any need to turn it off, but there's a couple of instances where it's helped issues.

Just so I can check I've got the same setup running here...
* A microsoft account, with outlook (unsleeping) and teams (unsleeping)
* One popout compose window from the outlook account
* Any other accounts/services? What's the sleep status of those?

Then to reproduce...
* Focus the popout email window type some text.
* Click on the main window
* Click the teams tab

I know teams is quite cpu heavy, I wonder if https://github.com/wavebox/waveboxapp/commit/c0a67815186acdb9eb7a8f8f5e8592c5a8c12559 will help with this when it's out of focus

**Comment by nmat** [comment]
I will close this issue. I think that most of the problems is when going over to hidpi stuff. However will keep testing a bit more and have it in backlog on my mail.
