### ISSUE TITLE
Can't connect to network

### ISSUE THREAD

**Issue by kopechcr** [wavebox/waveboxapp#642]
Wavebox can't connect to my network; my network settings haven't changed since I last connected fewer than 72 hours ago. I have no active Firewall and no anti-virus. Other applications are not affected.

<img width="1427" alt="screen shot 2018-04-09 at 8 36 08 am" src="https://user-images.githubusercontent.com/20321690/38498208-a215da8a-3bd1-11e8-9241-b4744fe2c1c8.png">

* Which version of Wavebox are you using? [e.g. 3.0.0]
3.13.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Mac OS 10.13.3

**Comment by Thomas101** [comment]
Hi, if you press the `Test Connectivity` button what does that bring up? Are you able to visit https://wavebox.io in your web browser?

**Comment by kopechcr** [comment]
Yes to connections:
<img width="1392" alt="screen shot 2018-04-09 at 8 46 28 am" src="https://user-images.githubusercontent.com/20321690/38498471-8b26ce82-3bd2-11e8-9aa6-558136cf0f46.png">

Results from Test:
<img width="676" alt="screen shot 2018-04-09 at 8 46 37 am" src="https://user-images.githubusercontent.com/20321690/38498474-8d221ec6-3bd2-11e8-93b7-f59bbeba88dc.png">

**Comment by Thomas101** [comment]
What about if you try https://waveboxio.com in your web browser?

Are you using any firewall/antivirus applications on your mac? Does restarting the machine make any difference?

**Comment by kopechcr** [comment]
I don't have any firewalls on, or antivirus apps on, but I also couldn't open waveboxio.com in an incog window, so it's an IT thing here, methinks.......

**Comment by Thomas101** [comment]
What was the error that you saw when opening waveboxio.com?

Feel free to drop support@wavebox.io an email with any additional details

**Comment by kopechcr** [comment]
Nope, just the connection failure.

FWIW, I'm also running WMail on the same computer and connection, with no issues...

**Comment by Thomas101** [comment]
In chrome is there any additional error information such as "ERR_NAME_NOT_RESOLVED" or "ERR_PROXY_CONNECTION_FAILED"? Are you running through a proxy server or vpn to connect to the web?
