### ISSUE TITLE
[Bug][macOS] Clicking Dock Icon moves app to primary screen

### ISSUE THREAD

**Issue by lachieh** [wavebox/waveboxapp#643]
### Which version of Wavebox are you using?
3.13.1beta

### What Operating System are you using?
macOS 10.13.3 (17D102)

### Issue
When using wavebox on a device with two screens, wavebox will move back to the primary screen when clicking the dock icon.

### Expected behaviour
Wavebox stays on the screen it was placed, but comes to the foreground.

### Steps to reproduce
1. Have two screens
1. Move Wavebox to secondary screen
1. Make Wavebox fill screen
1. Open another app on the primary screen
1. Click the Wavebox icon in the dock
1. Wavebox will move back to the primary screen

#### Notes
This is not something that I'm able to test very thoroughly, because I'm the only one using this app with two screens. It has only started happening in the last few versions, and it does not happen with other electron apps (slack, vscode, atom, gitkraken) which to me suggests that there is some custom behaviour happening on focus/icon-click.

**Comment by Thomas101** [comment]
Think I'm seeing the same here, I'll take a look. Thanks!

**Comment by lachieh** [comment]
Thanks! I can work around the issue by sticking the app in fullscreen on my secondary screen.
