### ISSUE TITLE
Unable to open link from mail

### ISSUE THREAD

**Issue by kkankala** [wavebox/waveboxapp#644]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.13.0
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

When opening any link from emails(inbox), they are not opening in Firefox or Chrome. It works in IE.

Steps:
Chrome or FireFox:
1) set your default browser as chrome or firefox.
2) click on any link from one of your emails
Actual: 
Chrome: "google chrome is unresponse. Relaunch now?" window opens. click on yes or no, nothing further happens.
Firefox: no message. nothing happens.

Working Scenario.
IE:
1) set your default browser as IE
2) click on any link from one of your emails
Actual: links open in IE.

**Comment by Thomas101** [comment]
Thanks for reporting. Could you try the following...
* Set your default browser to chrome/firefox
* Restart your machine
* In Wavebox, open Settings, click on the support tab along the top
* Click on the `Blog` button to see if that launches correctly?

**Comment by kkankala** [comment]
@Thomas101 . Same issue, when clicking on blog. Output: "google chrome is unresponse. Relaunch now?" window opens. click on yes or no, nothing further happens.

**Comment by nmat** [comment]
@kkankala I tested this here now but it works on my windows 10 machine.

Can you provide if there is a specific service causing this? How many and what services are you using?

Can you also provide what the command: winver

gives you?

**Comment by Thomas101** [comment]
I've tried installing 1607 LTSB on a machine here, but it seems to work okay out the box. Do you know which version of Chrome/Firefox you have installed in case it's something to do with that? Do you know if you have administrative rights on your machine or are these restricted?

Do you use the Slack Desktop App by any chance? This uses a similar stack to Wavebox and I was wondering if you see the same issue with that too...

**Comment by kkankala** [comment]
looks like in my case, opening Wavebox with "Run as administrator" always fixed the issue. I'm admin on my system, but still not sure why I have to set each app separately. I'm doing same for few other apps to(obviously not related to Wavebox).

**Comment by Thomas101** [comment]
As regards the other apps, is it because you see similar issues or for another reason?

**Comment by kkankala** [comment]
I dont remember exact reason, but my routine apps like VSCode, Visual Studio etc will have default "Run as Administrator" option checked.

**Comment by kkankala** [comment]
I had to manually configure VSCode, chrome and firefox. 

> It could be that moving from an unprivileged runtime (Wavebox in this instance) to a privileged runtime (e.g. Chrome) causes this kind of problem.

you may be right, about interacting between apps with different privileges.

**Comment by Thomas101** [comment]
I'll close this off for now then as it's more down to a security/environmental factor on the machine config :)

**Comment by kkankala** [comment]
ok thanks
