### ISSUE TITLE
Since updating to 3.14.0 G Suite Gmail won't load

### ISSUE THREAD

**Issue by sdmullen** [wavebox/waveboxapp#647]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.14.0

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
MacOS 10.13.4

I was prompted to update to 3.14.0 yesterday and since then my G Suite Gmail (my company email) no longer loads. It knows how many notifications I have (currently 4) but the display is just a grey/empty/blank screen. I also have my personal Gmail in the app and that still works fine.

I tried Clearing all browsing data and Reauthenticate and neither seemed to help. I also closed and reopened Wavebox which didn't help either.

Any ideas? It was fine prior to the latest update.

**Comment by Thomas101** [comment]
Hi, we've just pushed 3.14.1 which fixes this. You can grab by going to the main Wavebox menu and then Check for updates. Thanks for reporting!

**Comment by sdmullen** [comment]
Thanks 😄
