### ISSUE TITLE
MixMax is prompting us to upgrade to the latest chrome

### ISSUE THREAD

**Issue by dchersey** [wavebox/waveboxapp#656]
* Which version of Wavebox are you using? [e.g. 3.14.3]

* Which Operating System are you using? [MacOS 10.12.6]

<img width="495" alt="image" src="https://user-images.githubusercontent.com/800393/39161468-d941ec2e-473e-11e8-9c83-50340ee7bf14.png">

Mixmax keeps prompting me to upgrade chrome; I presume this is due to the library used by Wavebox ?

**Comment by Thomas101** [comment]
Hey, thanks for bringing this to our attention. We've just pushed version 3.14.5 out which has a fix for this. You can get the update by going to Wavebox > Check for updates.

Thanks!
