### ISSUE TITLE
[Feature Request] Ability to change account from Inbox to Gmail (and back)

### ISSUE THREAD

**Issue by EvHaus** [wavebox/waveboxapp#657]
* Which version of Wavebox are you using? [e.g. 3.0.0]

v3.14.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Windows 10

* Request

At the moment, there is no way to change an Inbox account to be a Gmail account. There's also no way to add a Gmail account to an existing Inbox account.

It would be great if we could:

- Easily change an account from Gmail to Inbox to Gmail
- Have two separate apps (Inbox and Gmail) for the same account

There's a new version of Gmail out today and it would be nice to have this feature to be able to easily test between the two email apps.

Right now the only way to do this is to delete the current account and re-create it using the different service.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. You can now add another service into an existing account (including Gmail & Google Inbox) by right-clicking on one of the tabs and picking `Add another service`

![screen shot 2018-07-23 at 12 59 31](https://user-images.githubusercontent.com/103586/43075305-4a277c4e-8e78-11e8-94fe-26c993a1a0aa.png)

This will let you have Gmail & Google Inbox in the same account and switch between them.

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
