### ISSUE TITLE
Support Notification web API

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#66]
Currently it seems wavebox only supports notifications for sites that it has explicit support for. Custom sites that use the Notification web API do not seem to interact with Wavebox.

It would be great if Wavebox supported these.

Reference:

https://developer.mozilla.org/en/docs/Web/API/notification

**Comment by Thomas101** [comment]
It should be supported out the box. Which website is it not working with?

**Comment by Naatan** [comment]
I just tried it again and noticed that it does send me a desktop notification, but the icon in Wavebox does not receive a red notification icon. So there's no clear way to identify where it came from.

I used this to test:

https://jsfiddle.net/Lbvweo0y/1/

**Comment by Thomas101** [comment]
The integration on the any weblink is pretty loose at the moment. There's not any html spec on displaying unread counters so we are working on putting an API together for this which you can either use on your own webpage or add as an extension on top of an existing website.

**Comment by Naatan** [comment]
You could always hijack the Notification object:

https://jsfiddle.net/mk075cfz/1/

Bit crude, but you get the idea.

**Comment by masterSoti** [comment]
Also just to make sure, the notifications also do not work on the following custom websites:
messenger.com
goupme
mysms
skype

**Comment by Thomas101** [comment]
Also pushbullet

**Comment by Thomas101** [comment]
Hi, 3.1.8 has support for an unread indicator based on notifications appear. This is cleared when opening the account.

@masterSoti As regards some of the services not working, we've found that on some you need to tell it that you want desktop notifications.

![screen shot 2017-05-23 at 09 31 04](https://cloud.githubusercontent.com/assets/103586/26345360/94b677d4-3f9a-11e7-920d-e6f9c86b86c3.png)

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
