### ISSUE TITLE
Gdocs - can only switch and edit if clicked 2 times

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#660]
* Which version of Wavebox are you using?
3.14.5

* Which Operating System are you using?
Windows 10 1709 (OS Build 16299.371)

* Description:
I am having 2 gdoc windows open on the screen. When I mouse click to edit one or the other I have to click twice to get the editing going. Its hard to work efficiently when you always have to double or move the cursor in order to edit one or the other.

**Comment by nmat** [comment]
thank you for verifying @Thomas101 :)

**Comment by nmat** [comment]
**Tested on windows 10 (winver: 1803 (OS Build 17134.48):**

gdocs (writer) - works on both click and Ctrl+Tab switching the active window
gmail (compose) - works on both click and Ctrl+Tab switching the active window
slack (different teams) - works

I would consider this fixed in upcoming release for windows 10.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
