### ISSUE TITLE
azendoo app has wrong url (404)

### ISSUE THREAD

**Issue by gaambo** [wavebox/waveboxapp#661]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.14.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10 64

adding the azendoo service/app opens it with the wrong url: 
`https://www.azendoo.com//app.azendoo.com`  
but it should only be `https://app.azendoo.com/`

workaround is to add the azendoo as a normal website.

**Comment by Thomas101** [comment]
Thanks for bringing this to our attention. We've fix it and if you try to re-add the account the url will be correct!
