### ISSUE TITLE
Can't connect over VPN

### ISSUE THREAD

**Issue by gregeh552** [wavebox/waveboxapp#662]
Wavebox App Version 3.14.5 On Ubuntu Linux

I can't connect to any service as long as I am connected via VPN. I can still reach the website via web browser.

 
Testing connectivity...
Current Status: ?clientId=XXXXX&clientToken=XXXXX&error=CONNECTION_FAILURE
Testing https://waveboxio.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://waveboxio.com/connection_test_fail
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://google.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://microsoft.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Done

**Comment by nmat** [comment]
@gregeh552 I have no problems at all with wavebox through a VPN.

Now this seems more like a VPN setting problem. Not sure where the https://waveboxio.com comes from but the main url is: https://wavebox.io and no .com in the end.

If you are not on the VPN then you can connect just fine?

**Comment by Thomas101** [comment]
Wavebox should pick out the settings from the OS. If not, you may need to configure it from the command line. We implement the same [switches as chromium](https://www.chromium.org/developers/design-documents/network-settings).

Which browser did you use to test the connection? If you have chrome/chromium installed do you need to do any additional configuration to get that working?

**Comment by andrewj720** [comment]
I'm having the same problem (connectivity check fails) using Ubuntu 18.04 when connected to ExpressVPN.

> Testing connectivity...
> Current Status: ?clientId=d7b21339-435d-4fe0-abab-506c9ad1d4aa&clientToken=&error=CONNECTION_FAILURE
> Testing https://waveboxio.com
> -- DIRECT
> -- ERR:TypeError: Failed to fetch
> Testing https://waveboxio.com/connection_test_fail
> -- DIRECT
> -- ERR:TypeError: Failed to fetch
> Testing https://google.com
> -- DIRECT
> -- ERR:TypeError: Failed to fetch
> Testing https://microsoft.com
> -- DIRECT
> -- ERR:TypeError: Failed to fetch
> Done

**Comment by Thomas101** [comment]
I'll have a look to see if I can reproduce here.

@andrewj720 have you tried configuring Wavebox via the [command line](https://www.chromium.org/developers/design-documents/network-settings)

@gregeh552 which version of Ubuntu are you using? 18.04 too?

**Comment by andrewj720** [comment]
Yes, Ubuntu 18.04

Not tried the no-vpn argument when laucnhing chromium.

**Comment by Thomas101** [comment]
Hi, we've just released Wavebox 4.0.0 which includes a newer version of Chromium under the hood. It would be good to know if you're still seeing the same issue with that version. Thanks

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment, I'm happy to-open and I’ll take another look. Thanks

**Comment by mackmm145** [comment]
similar problem to the orginal. can't wavebox can't connect as soon as i connect my vpn and can reconnect after disconnecting from my vpn. i'm running 4.4.0 and ubuntu 18.04.

Testing connectivity...
Current Status: ?clientId=#####&clientToken=####&error=CONNECTION_FAILURE
Testing https://waveboxio.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://waveboxio.com/connection_test_fail
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://google.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://microsoft.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Done

**Comment by bedouintravels** [comment]
Is it possible to reopen this issue? 
I have the same problem.  When I run "Test Connectivity" in Wavebox after it reports it cannot connect, it spits back this:

Testing connectivity...
Current Status: ?clientId=db288b26-930a-4f1c-8ac7-1504e0c0a643&clientToken=ff498ec01f2a480c877d5f26005df0f7&error=CONNECTION_FAILURE
Testing https://waveboxio.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://waveboxio.com/connection_test_fail
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://google.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Testing https://microsoft.com
-- DIRECT
-- ERR:TypeError: Failed to fetch
Done

This is only an issue when I'm connected to ExpressVPN. Chrome and Firefox still function fine but Chromium and Wavebox cannot connect to anything. 

Running Ubuntu 18.04.2 LTS, Wavebox 4.10.1
