### ISSUE TITLE
[Feature Request] Receive Hangouts calls in browser

### ISSUE THREAD

**Issue by khusmann** [wavebox/waveboxapp#663]
If I start or receive a video chat with Hangouts while in Wavebox, I am unable to use the "share screen" feature. Instead, I have to go to hangouts in my browser and start/receive the call there.

If wavebox could make google hangouts popout windows open in the browser (Like the "following drive links in browser" setting) instead of in another Wavebox window, I think this could work well.

Thanks!

**Comment by nmat** [comment]
@khusmann 

Please see: https://github.com/wavebox/waveboxapp/issues/498

**Comment by nmat** [comment]
What you can do is also to see: https://github.com/wavebox/waveboxapp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+share+screen

and you will get a list of more information regarding share screen. :)

**Comment by khusmann** [comment]
Ah, thanks @nmat! I didn't see those before. Although I'm less interested in getting screen sharing to work in wavebox like the other issues request; I'd be happy if it just popped into a webbrowser for now.

**Comment by Thomas101** [comment]
Thanks for taking the time to report, I'm merging this issue and a few others which report the same into #912 so we can track progress there and hopefully add support in. Thanks!
