### ISSUE TITLE
Project links inside Freedcamp wouldn't work

### ISSUE THREAD

**Issue by wallace11** [wavebox/waveboxapp#664]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.14.5
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Manjaro 17.1.9 Hakoila (Also confirmed on Linux Mint 18.3 and Ubuntu 17.10)

While they used to work in the past, probably somewhere between version 3.10 and 3.13 _any_ project link inside freedcamp.com wouldn't work.

Steps to reproduce:

1. Add a custom website: www.freedcamp.com
2. Login into an active account
3. Click on an active project (from Home widget, Projects tab or Choose Project menu)

Expected result:
Move into that project's page
Actual result:
Return to the same page

Thanks!

**Comment by wallace11** [comment]
I can indeed confirm the same behavior.
Might be a good idea to mention that my default page is "Projects" (second tab on top menu) and links don't work from there as well.

**Comment by Thomas101** [comment]
I've given this a try with our test branch that has a new version of Electron. The behaviour appears to be correct there so it looks like it may be fixed upstream. We'll be moving our beta channel across to this shortly - I'll test & recomment once we're closer to a release with that

**Comment by wallace11** [comment]
Thanks for the always so great support.
Looking forward to testing the beta.

**Comment by Thomas101** [comment]
It looks like the issue still persists with the beta, so I'll take another look at what the underlying cause of this is

**Comment by Thomas101** [comment]
Hi, I've just given this a try with the latest version of Wavebox and it seems to work, so I'm going to close this off. If you're still seeing the problem though feel free to comment and I'll look back into it. Thanks!
