### ISSUE TITLE
Din't save time sleep & behaviour when changes

### ISSUE THREAD

**Issue by ricsdeol** [wavebox/waveboxapp#665]
* Which version of Wavebox are you using?  Snap  3.14.5 (106) 142MB

* Which Operating System are you using? Ubuntu 18.04

Hi, I cant save inactivity time in any account in wavebox, always change to 100 minutes automatically after closed

![image](https://user-images.githubusercontent.com/719970/39578647-1a15eb50-4ebb-11e8-99f9-6ff19dfaad42.png)

![peek 2018-05-03 10-22](https://user-images.githubusercontent.com/719970/39579045-2aad48ae-4ebc-11e8-82db-84ec7362884e.gif)

Thanks.

**Comment by Thomas101** [comment]
Thanks for reporting! Fix out shortly :)

**Comment by ricsdeol** [comment]
Hi @Thomas101, thanks to support.

So Why they have a max limit time?

**Comment by Thomas101** [comment]
no reason really - we just need to bound it a little so it makes sense in the ui. It should go all the way up to 240mins/4 hours. Do you have a use case where you want it longer?

**Comment by nmat** [comment]
I tested the save of 100 and 240 and it works in GIT.

For the upper limit there could maybe be 2 different settings. The bar to choose up to 240 or just fill in the value to use (that could grey out the bar that can be dragged?)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
