### ISSUE TITLE
Compose dialog empty when using MixMax.

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#666]
* Which version of Wavebox are you using?
![2018-05-03_10h35_07](https://user-images.githubusercontent.com/689204/39583242-a9fc1a58-4ebd-11e8-9da1-7ed0e4283289.png)

* Which Operating System are you using?
**Windows 10**

With MixMax enabled the compose window is empty.
![2018-05-03_10h33_17](https://user-images.githubusercontent.com/689204/39583314-d1aa21da-4ebd-11e8-9c67-da099a94b39e.png)

I checked in Chrome Browser itself and it works fine.

Just me?
Thanks!

**Comment by Thomas101** [comment]
Seeing the same here. I'll find out what's gone wrong. Thanks!

**Comment by Thomas101** [comment]
@GollyJer I think we've managed to fix this. Does require a couple of steps your end unfortunately. Can you give the following a try...

1. Open Settings, click on the extensions tab and remove Mixmax
2. Restart Wavebox
3. Open Settings & extensions again. Add Mixmax
4. Restart when the download is complete and prompted

Sorry about this! Let me know if it works your end though!

**Comment by GollyJer** [comment]
All good now... thanks! 🎉
