### ISSUE TITLE
Top Toolbar is transparent with new Gmail for G Suite account

### ISSUE THREAD

**Issue by cachrisman** [wavebox/waveboxapp#669]
* Which version of Wavebox are you using? 3.14.5

* Which Operating System are you using? macOS 10.13.4

I've got a personal google account where the services are in the top toolbar and a work google account where the services are in the left sidebar. When I click into my work gmail, part of the top toolbar is transparent. When I click into my work calendar, it isn't transparent. It only happens on my work google account. My personal account also uses new gmail and it is displayed correctly

![image](https://user-images.githubusercontent.com/6521666/39719513-42d45780-51ee-11e8-8903-d30fa97d79b9.png)

![image](https://user-images.githubusercontent.com/6521666/39719521-4faf7e62-51ee-11e8-87cd-24cd7f2300f6.png)

**Comment by Thomas101** [comment]
Thanks for reporting. I think this is an upstream bug that shows up when vibrancy is enabled. I think there may be a fix already available for this so I'll see if I can port it across!

**Comment by nmat** [comment]
This is the same as: https://github.com/wavebox/waveboxapp/issues/495

**Comment by cachrisman** [comment]
Changing the Translucent window backgrounds setting to None fixes this at the expense of not having the fancy translucent background...

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.7. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
