### ISSUE TITLE
Popup notification for new mail

### ISSUE THREAD

**Issue by jeffneedle** [wavebox/waveboxapp#67]
* Which version of Wavebox are you using?  3.1.3

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Linux

I thought the update would solve the popup notification problem.  I've got it turned off in preferences, and I've restarted Writebox.  They still pop up.  Will this be addressed?  Thanks.

Sorry, can't figure out how to delete this.  The problem seems to have gone away.  Many thanks!

**Comment by Thomas101** [comment]
No worries! I'll close the issue off :)

It should be fixed in 3.1.3, but do let me know if it does come back up.
