### ISSUE TITLE
New message window is now blank/not loading

### ISSUE THREAD

**Issue by dchersey** [wavebox/waveboxapp#670]
* Which version of Wavebox are you using? 3.14.5
* Which Operating System are you using?  Mac OSX 10.12.6

Suddenly I am unable to compose new messages ... the new message window in each of my accounts is blank.  To my knowledge nothing's been changed in my chrome, Wavebox or Mac software since it last worked on Friday ... was away for 3 days. 

I tried reloading, restarting .... no change. 

<img width="517" alt="image" src="https://user-images.githubusercontent.com/800393/39730066-68a2bc88-522d-11e8-90d5-f2df876493da.png">

**Comment by Thomas101** [comment]
Hi, I'm guessing you have Mixmax installed. There's a bug with this and our integration of it (https://github.com/wavebox/waveboxapp/issues/666). If you do the following, it should work again...

- Open Settings, click on the extensions tab and remove Mixmax
- Restart Wavebox
- Open Settings & extensions again. Add Mixmax
- Restart when the download is complete

**Comment by dchersey** [comment]
Yes indeed!  I’ll do that, thanks.
