### ISSUE TITLE
npm run install :all   something wrong 

### ISSUE THREAD

**Issue by hana0211** [wavebox/waveboxapp#671]
* Wavebox Version: [e.g. 3.14.5]
* Operating System & Version: [Windows 10]
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]

**Screenshots**
PS C:\Users\korea> cd C:\Users\korea\Documents\GitHub\waveboxapp
PS C:\Users\korea\Documents\GitHub\waveboxapp> npm run install:all

> wavebox@3.14.5 install:all C:\Users\korea\Documents\GitHub\waveboxapp
> node scripts/installAll.js

npm install: C:\Users\korea\Documents\GitHub\waveboxapp
npm ERR! path C:\Users\korea\Documents\GitHub\waveboxapp\node_modules\fsevents\node_modules\abbrev\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\korea\Documents\GitHub\waveboxapp\node_modules\fsevents
\node_modules\abbrev\package.json'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\korea\Documents\GitHub\waveboxapp\node_modules\fseve
nts\node_modules\abbrev\package.json'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\korea\\Documents\\GitHub\\waveboxapp\\node
_modules\\fsevents\\node_modules\\abbrev\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\korea\\Documents\\GitHub\\waveboxapp\\node_modules\\fsevents\\node_modules\\abbrev\\package
.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\korea\AppData\Roaming\npm-cache\_logs\2018-05-09T06_08_32_877Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! wavebox@3.14.5 install:all: `node scripts/installAll.js`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the wavebox@3.14.5 install:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\korea\AppData\Roaming\npm-cache\_logs\2018-05-09T06_08_38_443Z-debug.log

**Additional information**

**Comment by Thomas101** [comment]
I've seen this happen a few times on Windows. Try one of the following, it normally fixes it...
* Run `npm run install:all` again
* Delete `node_modules` and try `npm run install:all` again

**Comment by nmat** [comment]
Been testing on my windows 10 machine also and get the same error.

PS C:\git\waveboxapp> npm run install:all

> wavebox@3.14.6 install:all C:\git\waveboxapp
> node scripts/installAll.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\git\waveboxapp\scripts\Tools.js:2:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wavebox@3.14.6 install:all: `node scripts/installAll.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wavebox@3.14.6 install:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[hidden]\AppData\Roaming\npm-cache\_logs\2018-05-11T17_05_22_639Z-debug.log
PS C:\git\waveboxapp> npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-pre-gyp@^0.9.0 (node_modules\fsevents\node_modules\node-pre-gyp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, open 'C:\git\waveboxapp\node_modules\fsevents\node_modules\node-pre-gyp\npm-shrinkwrap.json'
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path C:\git\waveboxapp\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\git\waveboxapp\node_modules\.staging'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\git\waveboxapp\node_modules\.staging'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\git\\waveboxapp\\node_modules\\.staging\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\git\\waveboxapp\\node_modules\\.staging' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[hidden]\AppData\Roaming\npm-cache\_logs\2018-05-11T17_05_46_111Z-debug.log
PS C:\git\waveboxapp>

**Comment by nmat** [comment]
winver: 1803 (OS Build 17134.48)

**Comment by nmat** [comment]
@hana0211 can you test to re clone the repo and compile again?

**Comment by Thomas101** [comment]
I think there's been an upstream change in one of the libraries which means it's target compile lib is VSCode 2015 rather than 2013. Looking through the tree I think it's down to `electron-windows-notifications`. Give the following a try...
* Remove `electron-windows-notifications` from optionalDependencies in `src/app/package.json`
* Remove `src/app/node_modules`
* Run `npm run install:all` again

The app will handle that particular lib being available or not gracefully. Notifications still work just using the default electron provider. In all honesty, it's on my list to remove it completely in this beta cycle - the default electron notification provider has all the bells and whistles we need now

**Comment by nmat** [comment]
@hana0211 did you test what @Thomas101 mentioned? Curious to know the result

**Comment by Thomas101** [comment]
The lib has been removed in master now, so just doing a pull and install should fix this
