### ISSUE TITLE
Deb packaged wavebox auto update

### ISSUE THREAD

**Issue by niosus** [wavebox/waveboxapp#672]
* Wavebox Version: [e.g. 3.14.5]
* Operating System & Version: [e.g. Ubuntu 16.04]

**Is your feature request related to a problem? Please describe.**
Wavebox prompts me to update, but running
```bash
sudo apt update && sudo apt upgrade
```
does not update Wavebox.

**Describe the solution you'd like**
It would be cool if the deb package would set up update mechanism that would not require any manual actions.

Seems to be slightly related to #135 but I would expect that the deb installer adds this ppa automatically to the system and can update from packages in that ppa. Or did I get something wrong here?

**Comment by nmat** [comment]
Are you using the PPA from the website or the standard ubuntu repos?

https://wavebox.io/download/ The repo listed here?

**Comment by Thomas101** [comment]
Deb installs on their own don't have any built-in mechanism to auto-update. We could download and try to install off the command line but that comes with its own big set of security-related problems.

If you use the apt repository, then you should be able to just run update & upgrade - which is the easiest way to keep it up to date. You can install via...

```
sudo wget -qO - https://wavebox.io/dl/client/repo/archive.key | sudo apt-key add -
echo "deb https://wavebox.io/dl/client/repo/ x86_64/" | sudo tee --append /etc/apt/sources.list.d/repo.list
sudo apt update
sudo apt install wavebox
```

**Comment by niosus** [comment]
Ok, I will use this method from now on. I was under the impression that it is relatively easy to use deb to configure auto updates through a ppa. I am not an expert in packaging though, so I guess I will close this issue.

**Comment by MurzNN** [comment]
> echo "deb https://wavebox.io/dl/client/repo/ x86_64/" | sudo tee --append /etc/apt/sources.list.d/repo.list

Will be good to change name of file from `repo.list` to `wavebox.list`, like all other apps names it.

**Comment by Thomas101** [comment]
I agree @MurzNN changed to reflect that
