### ISSUE TITLE
Reload on double click on tray icon (strange reload)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#673]
* Wavebox Version: 3.14.5 and GIT master 2018-05-11
* Operating System & Version: Windows 10 (1803)

**Expected & actual behavior**
Reload/maximize behavior the same as clicking minimize and maximize in traybar.

**Steps to reproduce**
Click the icon in the main task bar (you will see the animation being soft going from minimized to maximized.

Then do the same using the same method on traybar icon. And you will see a glitch and some sort of rendering of screen. (NOTE the window has to be maximized to create the render glitch.

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
https://imgur.com/5S8VCgS

**Additional information**
Tested with non maximized window also but the effect only happens on maximized.

**Comment by Thomas101** [comment]
Thanks, it looks like it's something down to the restore code that the tray uses

**Comment by Thomas101** [comment]
@nmat are you still seeing this with the new beta?

**Comment by nmat** [comment]
On latest beta I do see the render glitch. I will test on git master also.

**Comment by Thomas101** [comment]
Is it just when the main window is maximized or when it's any size?

**Comment by nmat** [comment]
Only when main window is maximized. There might be some artifacts when its windowed but they are barely visible and noticable.

**Comment by Thomas101** [comment]
That should be fixed in master now

**Comment by nmat** [comment]
Will test when I get home. Thank you!

**Comment by nmat** [comment]
This works perfectly now. So much easier on the eyes without the jitter of reload of page.

Thank you!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Works in beta and in git. Closing issue. thank you.
