### ISSUE TITLE
200% zoom on wake for gmail on hidpi monitor

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#676]
* Wavebox Version: 3.14.6
* Operating System & Version: windows 10 (hidpi)

* Account type (if applicable): Gmail

**Expected & actual behavior**
Wake from sleep should show correct zoom from start. (or dim until woken up)

When the service is woken from sleep the zoom is something a long side 200%.

**Steps to reproduce**
But gmail to sleep and just wake it up when in the inbox (new theme)

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
Might be only for hidpi screen. Still the zoom gets a bit odd when you kind of expect it to only do some progress and then wake up with the zoom as intended. After the wake up it does go to correct zoom though. Very low priority but is a bet "design" flaud.

**Comment by Thomas101** [comment]
Cheers, I'll take a look!

**Comment by c-lawlz** [comment]
@nmat this sounds similar to my issue [here]( #667).  Are you using a dual monitor setup by chance?

**Comment by nmat** [comment]
@c-lawlz I am always using dual monitor. Might be related but I need to investigate a bit more.

Let me get back to you when I have checked it a bit

**Comment by nmat** [comment]
This does not seem to happen anymore. I am going to close it off as fixed. Will reopen if it occurs again.
