### ISSUE TITLE
Crash on drag Azure resource outside supported area

### ISSUE THREAD

**Issue by johnkazer** [wavebox/waveboxapp#677]
* Wavebox Version: 3.14.6
* Operating System & Version: Win10
* Account type (if applicable): Azure

**Expected & actual behavior**
Passively display Azure warning status but instead Wavebox failed to handle the exception and crashed

**Steps to reproduce**
I dragged a new resource from my Azure favourites list around outside the 'droppable' area (so the mouse icon changes to the stop sign as per screenshot below) and the Azure blade generated an error followed by Wavebox crashing.

**Is the bug persistent or intermittent?**
Seems consistent

**Screenshots**
Screenshots often help us narrow down a bug more easily.
![40108029-c44ef810-58f1-11e8-836f-b2e9821f06dc](https://user-images.githubusercontent.com/30650393/40108171-19205334-58f2-11e8-8aad-02d67e6a1496.png)

![40108034-c82225ca-58f1-11e8-87c2-1c5f2c10207c](https://user-images.githubusercontent.com/30650393/40108352-8bb3ff2c-58f2-11e8-9601-b142bfa12182.png)

**Comment by Thomas101** [comment]
Thanks, I'll take a look!

**Comment by johnkazer** [comment]
It appears not.
Current version info: 
![image](https://user-images.githubusercontent.com/30650393/51618807-d8524780-1f26-11e9-92c8-53b239665b23.png)

**Comment by Thomas101** [comment]
Awesome, thanks for the update!
