### ISSUE TITLE
Mark messages read when marking them done

### ISSUE THREAD

**Issue by dchersey** [wavebox/waveboxapp#678]
I'm not sure if this is possible in Wavebox or if this is a feature needed for Google Inbox, but it would be super-nice if when I marked messages "Done" it also cleared the unread status for them and the app as well as system tray unread badge.  

Currently I have to actually click on each message, which sort of defeats the point of being able to quickly dispose of groups of messages.

**Comment by nmat** [comment]
hmmm I am not following this correctly.

Do you mean that the unread badge is not updating? Did you follow: https://wavebox.io/kb/google-unread-counts

?

**Comment by Thomas101** [comment]
There's sometimes a short delay between marking them as done and Wavebox getting the update from Google too. If you mark them as done and wait a little while (30 seconds should be the absolute maximum) does the badge clear?

**Comment by dchersey** [comment]
Thanks -- I did check the settings per the article and I am on the default Unread Unbundled setting.  One of my accounts is actually working correctly and one is not.   

I now see that my unread badge is not changing for the bad account - it is stuck on 40 messages unread and neither reading nor marking messages as done is changing it.

**Comment by dchersey** [comment]
Also just tried deleting and re-adding the misbehaving account; still stuck at 40 :(

**Comment by Thomas101** [comment]
If you take a look at the tray it will show you which messages are being picked up as unread. If you go through those are you able to clear them?

**Comment by dchersey** [comment]
For some of them yes ... some of the items in the list are actually not found in Wavebox but appear in my tray unread list.  Some of them decrease the unread count, and most of them do not when I mark them as done.  Still working through them.  I haven't found a pattern yet.   Managed to get the count below 40 though, so maybe I just need to keep doing this..... is there any way to reset it?

**Comment by dchersey** [comment]
many of the items in the tray icon's unread list are already marked as done

**Comment by Thomas101** [comment]
If it's permanently stuck on the 40, it sounds like it may be failing to sync all-together. Try right clicking on the account in the left side bar and then picking `Reauthenticate`. It will take you through a couple of steps to get a new token from Google but should after that return to normal.

If that doesn't work, try pasting the following search term into the Google Inbox search bar `label:inbox label:unread -has:userlabels -category:promotions -category:forums -category:social` do you get a reasonable set of unread messages back or are you seeing the same faulty set that Wavebox is showing in the tray?

**Comment by dchersey** [comment]
Reauthenticating did not do anything but the search term you gave me did surface a list of the items that were buried in other threads in my inbox that were coming up as unread.  I marked all of them as done in the web version of inbox and my count is now down to 3.... all reasonable now. 

Thanks!
