### ISSUE TITLE
Wavebox not prefilling the TO address for mailto: links?

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#679]
![image](https://user-images.githubusercontent.com/689204/40141221-45107eb6-5923-11e8-8741-637770a60089.png)

If you go to my website [https://isjustawesome.com/](https://isjustawesome.com/), scroll to the bottom and click the Support link it opens Wavebox, asks which mail account, starts a new email, but doesn't fill out the **TO:** address.

Am I doing something wrong with my link or is it a Wavebox bug?

Thanks!

**Comment by Thomas101** [comment]
Are you using mixmax? If so at the moment were not able to prefill the info into the compose window.

Otherwise, is it Old Gmail/New Gmail/Google Inbox?

**Comment by GollyJer** [comment]
Uhg... another MixMax issue.  
Yup.  After uninstalling MixMax it works.  I had ran into this before but didn't care as much to look into it as it wasn't my own mailto link. 😄 

One suggestion... it would be nice to have the option to selectively disable extensions rather than uninstall.  Not a huge deal.  Just a thought.

Thanks @Thomas101
