### ISSUE TITLE
Settings Export

### ISSUE THREAD

**Issue by JohnOz66** [wavebox/waveboxapp#68]
* Which version of Wavebox are you using? [e.g. 3.0.0] 3.1.3

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04] Windows 10

I'm about to wipe my computer and reinstall windows. Is there any way for me to export the accounts, settings etc that I've already set up so I can import them in the new install ?

**Comment by Thomas101** [comment]
Hi, there's no automatic way to do this, but I think if you take a copy of `C:\Users\<User>\AppData\Local\wavebox\wavebox\` e.g. `C:\Users\John Doe\AppData\Local\wavebox\wavebox\` and replace it after re-install you should be okay. You will need to re-sign in to your accounts on your fresh install

**Comment by JohnOz66** [comment]
Hi Thomas

I gave that a try but it didn't work. No biggie as I was able to just recreate.

**Comment by Thomas101** [comment]
Sorry about that. I think you might have caught it just between releases. The location of the settings changed from `AppData\Local` to `AppData\Roaming` in the latest version. I've put together a more [detailed wiki article](https://github.com/wavebox/waveboxapp/wiki/KB:-Copying-Accounts) about how to do this in the meantime (in case you need to do this again)

**Comment by Thomas101** [comment]
Hi, we've added import & export tools to Wavebox 3.1.9. These can be found under settings. Thanks!
