### ISSUE TITLE
wavebox produces apparmor warnings on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by efwe** [wavebox/waveboxapp#680]
* Wavebox Version: 3.4.16
* Operating System & Version: Ubuntu 18.04 LTS
* (Linux only) Install method: Snap
* Account type (if applicable): several

reading the journal i see many entries of the form 

> May 18 17:43:11 osa audit[2252]: AVC apparmor="DENIED" operation="open" profile="snap.wavebox.wavebox" name="/proc/2561/sched" pid=2252 comm="Wavebox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
> May 18 17:43:11 osa kernel: audit: type=1400 audit(1526658191.618:44): apparmor="DENIED" operation="open" profile="snap.wavebox.wavebox" name="/proc/2561/sched" pid=2252 comm="Wavebox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000

and also

> May 18 17:55:11 osa audit[1008]: USER_AVC pid=1008 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/" interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" mask="send" name="org.bluez" pid=4884 label="snap.wavebox.wavebox" peer_pid=1035 peer_label="unconfined"
>                                   exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
> May 18 17:55:11 osa kernel: audit: type=1107 audit(1526658911.038:49): pid=1008 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/" interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" mask="send" name="org.bluez" pid=4884 label="snap.wavebox.wavebox" peer_pid=1035 peer_label="unconfined"
>                              exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'

I fear this is not a Wavebox but a Ubuntu 'problem' - but i wanted to let you know. I cannot see any
difference in behaviour to my windows installation - so I'm also not sure if this 'error' has negative effects on the UI. 

Keep up the good work
~fw

**Comment by Thomas101** [comment]
Thanks for reporting, we have seen the apparmor warnings before. I think for the most part electron is able to handle the warnings gracefully. We use the same framework as the  Github desktop app and the [snap recipe](https://github.com/snapcrafters/github-desktop) has similar warnings listed as known issues.

I think you may be right thinking it's an Ubuntu/snap problem, there are quite a few [snap related issues with this on](https://forum.snapcraft.io/search?q=org.freedesktop.DBus.ObjectManager) the forum so the team are aware of it :)
