### ISSUE TITLE
menu bar not appearing on windows 10

### ISSUE THREAD

**Issue by revant117** [wavebox/waveboxapp#682]
* Wavebox Version: [3.14.6]
* Operating System & Version: [Windows 10]

Expected: Menu bar to show up in the app allowing to open the dev tools through View->Developer option.
Actual Behavior: No menu bar is seen
I built the project from source using `npm run start`

Please refer the screenshot 

![no-menubar](https://user-images.githubusercontent.com/7831591/40360870-1ae391ac-5de5-11e8-86c6-6e84a8aaaecc.png)

**Comment by nmat** [comment]
Does the menubar appear if you go to settings on the left side and select: 
Show titlebar Menu

Or hit: Ctrl+\

If you are on a EU keyboard: Ctrl+§

**Comment by nmat** [comment]
Just tested this in GIT master 2018-05-22

The menu is by default hidden. To show the menu please use the steps I provided above.

**Comment by revant117** [comment]
Yes it's working perfectly. I had missed that option in the settings tab. Thanks a lot, @nmat .
Closing this issue.
