### ISSUE TITLE
[feature request] - Wavebox mini - Close popout on Esc

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#683]
* Wavebox Version: 3.14.6 and GIT master
* Operating System & Version: windows 10 and macOS

**Is your feature request related to a problem? Please describe.**
Wanted to close the wavebox mini with Esc like other apps using tray icon popout but could not

**Describe the solution you'd like**
Esc when wavebox mini popout is active should escape the popout.

If wavebox mini is open as a window. Then do not close window on escape. Treat as any other window.

**Additional info**
Tested on both GIT 2018-05-23 and wavebox beta/stable

This looks like a very standard way of treating popout menus from tray so would be nice to follow that standard.

**Comment by nmat** [comment]
Verfied working on windows 10.

Gonna test on macOS during the weekend also.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Tested in git and beta and it works as intended. Closing issue.
