### ISSUE TITLE
Wavebox mini - Windows 10 - resize on top bar does not work

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#684]
* Wavebox Version: 3.14.6 and GIT 2018-05-23
* Operating System & Version: windows 10 1803 (OS Build 17134.48)

**Expected & actual behavior**
All sides of wavebox mini should be able to be used for resize window. Top bar ignores resize of window.

See GIF below in Screenshots.  

**Steps to reproduce**
Open wavebox mini as window
Try resizing on all sides
Notice that top bar does not allow resize

**Is the bug persistent or intermittent?**
It is persistent.

**Screenshots**
![2018-05-23_20-03-08](https://user-images.githubusercontent.com/383031/40442633-81762724-5ec4-11e8-9fe4-7d0dca79c329.gif)

**Comment by Thomas101** [comment]
Probably down to the way we capture the drag events in the top toolbar. I'll take a look if this is fixed in electron 2.0

**Comment by nmat** [comment]
Sounds good. I did test it on macOS and it worked there with all the sides being able to resize window therefore expected the same behaviour on windows.

**Comment by nmat** [comment]
Verified working on latest git master.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Resize on top bar works now. Thank you closing issue.
