### ISSUE TITLE
opensuse repository not working

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#685]
* Wavebox Version: 3.14.6
* Operating System & Version: openSuse Tumbleweed
* (Linux only) Install method: zypper
* Account type (if applicable): Office 365

**Expected & actual behavior**
I would expect to update Wavebox by issuing "sudo zypper dup" on my system.
Instead, Wavebox repository is not refreshed because of this error:
```
cristiano@xmper8q3 [~]$ LANG=C sudo zypper ref
Repository 'repo-oss' is up to date.
(...)
Retrieving repository 'Wavebox - x86_64' metadata -------------------------------------------------------------------------------------------------------------------------------------[/]
File './repodata/2b6079ddb45c8c747042053351573b07e5535959bca7582c58feaedc6929602a-primary.xml.gz' not found on medium 'https://wavebox.io/dl/client/repo/yum/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a):
Abort, retry, ignore? [a/r/i/...? shows all options] (a):
Retrieving repository 'Wavebox - x86_64' metadata .................................................................................................................................[error]
Repository 'Wavebox - x86_64' is invalid.
[wavebox|https://wavebox.io/dl/client/repo/yum/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'Wavebox - x86_64' because of the above error.
Some of the repositories have not been refreshed because of an error.
```

**Steps to reproduce**
Simply issue "sudo zypper dup" or "sudo zypper refresh" at the CLI

**Is the bug persistent or intermittent?**
It is always happening since a few days

**Screenshots**
n/a

**Additional information**
n/a

**Comment by Thomas101** [comment]
Hi @Cris70 there's been a couple warnings with the repo & zypper which we've fixed now. Would you be able to give it another try to see if it works for you? If not can you check the version of zypper you're using `zypper --version`

**Comment by Cris70** [comment]
Hi @Thomas101 it is working now, thank you!
