### ISSUE TITLE
New setting to hide address bar

### ISSUE THREAD

**Issue by ocafebabe** [wavebox/waveboxapp#686]
* Wavebox Version: 3.14.6 Pro
* Operating System & Version: N/A

Hi,

Could you please add a new setting to let users hide the address bar and navigation buttons? This is useless in many contexts and without it Wavebox would feel even more like a native app!

Thanks,

**Comment by bitstrings** [comment]
I believe this shouldn't be difficult.

**Comment by ocafebabe** [comment]
Never mind, after looking around I found that the setting already exists under: Wavebox settings -> Accounts -> Show navigation toolbar. This setting should be off by default IMHO...
