### ISSUE TITLE
New gmail app hovering issue

### ISSUE THREAD

**Issue by tonybyng** [wavebox/waveboxapp#687]
* Wavebox Version: [e.g. 3.0.0] 3.14.6
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10] Linux Mint 18.3
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...] apt repo
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...] Gmail

**Expected & actual behavior**
Some information about what you expect to happen and what actually happens.

The new gmail app shows the delete/archive etc buttons when you hover over the right hand side of an email and disappear when you move away.  When you click onto delete/archive etc so that the email disappears and the one from below now takes its place, the standard gmail interface running in chrome refires the hover event so that the archive/delete etc are shown again for the new email

within wavebox i have to move my mouse slightly to refire the hover method. Because I always use wavebox I thought this was the behaviour of gmail itself until I just saw that it works in chrome!

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?
as above

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?
always

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**

**Comment by nmat** [comment]
Reproduced comparing gmail.com and also in gmail using wavebox beta

Tested in GIT master also and I see this effect on windows 10 and on macOS

**Comment by tonybyng** [comment]
@nmat well spotted. Yes, if I highlight multiple items, the hover system then works correctly. Weird ! Although I don't want to be selecting all inbox mails to do selective deleting just in case i accidentally delete all of them ;-)

**Comment by nmat** [comment]
Thank you for testing. Yes of course, I just wanted to check if you got the exact same effect. At least at that point there is a diff. :)

**Comment by Thomas101** [comment]
Thanks, I see the same here. After a little bit more testing, I think this is down to the version of WebKit that Wavebox is using. We see the same in the latest Safari on macOS and also on the same version of Chromium that Wavebox uses.

The current beta channel of Wavebox has a newer version of Chromium than 3.14.6, but this doesn't fix the issue either. I've tried with the version of Chromium that the next Electron will ship with and the problem does seem to be resolved there though!

**Comment by Thomas101** [comment]
Hi, I've just given this a try with 4.5.0 and it seems to be fixed! Let me know if you're still seeing it :)

**Comment by tonybyng** [comment]
Agreed - its working. Thanks.
