### ISSUE TITLE
Different default browser per appliation

### ISSUE THREAD

**Issue by efwe** [wavebox/waveboxapp#688]
* Wavebox Version: 3.14 
* Operating System & Version: Ubuntu 18.04

When I configure an application I want to be able to choose a browser where outgoing links are opened.
Say I have an application where I want to be authenticated  in the target browser, I want to be able to select that browser. Right now all outgoing links are opened by the default browser which should stay 'virgin' as in 'no persistent cookies'.

Keep up the good work,
~fw

**Comment by nmat** [comment]
You can chose this in the service when you right click and "Account Settings" -> Advanced -> Open new windows in which browser setting

Did you test this?

**Comment by efwe** [comment]
thanks for the fast response and sorry for not being clear enough. In this configuration menu i can choose between "Default Browser" and "Wavebox Browser". But what I want is, that I can choose between "Firefox, Chromium, Google Chrome, ..". I hope, that I did not make any obvious configuration error.

**Comment by nmat** [comment]
no problem

So "Default Browser" does indicate the OS default browser indeed. So if you have set Chrome as default browser or another one then that would be used.

Wavebox browser is the built in one.

Not sure how this would work in general I guess in this case you would want wavebox to read what browser that does exist in the system and then choose that and not just the OS default browser.

So its a feature request if that is the case. Correct?

**Comment by signe** [comment]
See also #286

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.5.12.

 I've added a more detailed explanation of what's been added and how to set up and get started [in this issue](https://github.com/wavebox/waveboxapp/issues/286#issuecomment-460594441) as it's really similar to this one.

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
