### ISSUE TITLE
opensuse repository signature invalid

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#690]
* Wavebox Version: 3.14.6
* Operating System & Version: linux openSUSE Tumbleweed
* (Linux only) Install method: zypper
* Account type (if applicable): Office 365

**Expected & actual behavior**
I would expect to be able to update Wavebox during the normal update cycle of my OS, i.e. issuing 'sudo zypper dup' at the cli.
Instead, when I issue 'sudo zypper dup' this is what I get:
```
cristiano@xmper8q3 [~]$ LANG=C sudo zypper dup
Warning: You are about to do a distribution upgrade with all enabled repositories. Make sure these repositories are compatible before you continue. See 'man zypper' for more information about this command.
Retrieving repository 'Wavebox - x86_64' metadata -------------------------------------------------------------------------------------------------------------------------------------[\]
Signature verification failed for file 'repomd.xml' from repository 'Wavebox - x86_64'.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: This file was modified after it has been signed. This may have been a malicious change,
    so it might not be trustworthy anymore! You should not continue unless you know it's safe.

Signature verification failed for file 'repomd.xml' from repository 'Wavebox - x86_64'. Continue? [yes/no] (no):
```

**Steps to reproduce**
Open a terminal and issue 'sudo zypper dup'

**Is the bug persistent or intermittent?**
Persistent since a few days

**Screenshots**
N/A

**Additional information**
N/A

**Comment by Thomas101** [comment]
hmmm that should have been fixed in #685. Which version of zypper are you using via `zypper --version`?

**Comment by Cris70** [comment]
Hi @Thomas101, it seems the problem is solved now. I don't know... maybe it was a network glitch?
Anyway, here is my zypper version:
```
cris@PolariSuse [~]$ zypper --version
zypper 1.14.5
```

Thank you
Cris

**Comment by Cris70** [comment]
A couple days have passed: no more problems. I'm closing this issue.
Thank you!
Cris

**Comment by Thomas101** [comment]
okay - I haven't had a chance to look into this properly yet, so whatever solved it is beyond me! If it happens again though, just re-open this I'll see if we can get to the bottom of it!!

**Comment by Cris70** [comment]
@Thomas101 unfortunately today the error is back:
```
cristiano@xmper8q3 [~]$ LANG=C sudo zypper ref 16
Retrieving repository 'Wavebox - x86_64' metadata -------------------------------------------------------------------------------------------------------------------------------------[\]
Signature verification failed for file 'repomd.xml' from repository 'Wavebox - x86_64'.

    Note: Signing data enables the recipient to verify that no modifications occurred after the data
    were signed. Accepting data with no, wrong or unknown signature can lead to a corrupted system
    and in extreme cases even to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures the integrity of the
    whole repo.

    Warning: This file was modified after it has been signed. This may have been a malicious change,
    so it might not be trustworthy anymore! You should not continue unless you know it's safe.

Signature verification failed for file 'repomd.xml' from repository 'Wavebox - x86_64'. Continue? [yes/no] (no):
Retrieving repository 'Wavebox - x86_64' metadata .................................................................................................................................[error]
Repository 'Wavebox - x86_64' is invalid.
[wavebox|https://wavebox.io/dl/client/repo/yum/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'Wavebox - x86_64' because of the above error.
Could not refresh the repositories because of errors.
```

**Comment by Cris70** [comment]
Hi  @Thomas101, any news on this?

**Comment by Thomas101** [comment]
Hi, sorry for not getting back on this. We're not seeing the problem on our box here, I wonder if it's some stale data or something.

First can you check a few things to make sure everything is setup correctly...
1. Check which version of Wavebox is installed. Do this by running `zypper search -s Wavebox` the installed version should have an `i` in the first column. Is it `3.14.6-1`?
2. Check that you have the public key installed by running `rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'` you should see the key from wavebox.io in the list

... then it may be worth removing the repo & re-adding it, in case there's some cached stale data or something. It may be worth taking a copy of `~/.local/share/wavebox/` just in case it gets removed, but it shouldn't. Try the following...

```bash
zypper rr wavebox
zypper clean -a # this will clean up any zypper caches, if you want to keep them feel free to skip this step
sudo wget -P /etc/zypp/repos.d/ https://wavebox.io/dl/client/repo/yum/wavebox.repo
```
Does that make any difference, or much the same?

**Comment by Cris70** [comment]
And here is the part where I reinstall the repo:

```
cristiano@xmper8q3 [~]$ sudo zypper rr wavebox
[sudo] password di root:
Rimozione del repository 'Wavebox - x86_64' ..............................................................................[fine]
Il repository 'Wavebox - x86_64' è stato rimosso.
cristiano@xmper8q3 [~]$ sudo zypper clean -a
Tutti i repository sono stati puliti.
cristiano@xmper8q3 [~]$ sudo wget -P /etc/zypp/repos.d/ https://wavebox.io/dl/client/repo/yum/wavebox.repo
--2018-06-21 16:32:19--  https://wavebox.io/dl/client/repo/yum/wavebox.repo
Connessione a 127.0.0.1:3128...connesso.
Richiesta Proxy inviata, in attesa di risposta... 301 Moved Permanently
Posizione: https://wavebox.pro/dl/client/repo/yum/wavebox.repo [segue]
--2018-06-21 16:32:20--  https://wavebox.pro/dl/client/repo/yum/wavebox.repo
Connessione a 127.0.0.1:3128...connesso.
Richiesta Proxy inviata, in attesa di risposta... 200 OK
Lunghezza: 158 [application/octet-stream]
Salvataggio in: "/etc/zypp/repos.d/wavebox.repo"

wavebox.repo                    100%[=======================================================>]     158  --.-KB/s    in 0s

2018-06-21 16:32:20 (11,9 MB/s) - "/etc/zypp/repos.d/wavebox.repo" salvato [158/158]
```
After doing this, I did a `sudo zypper ref` and everything was correct (no warning was raised on the Wavebox repo). 

This is weird though, I do not see how could the key get corrupted. BTW, the important thing is that it is correct now. Let's see if it sticks.

Thank you for your help!!

Cris

P.S. Sorry, forgot to export the LANG variable so output is in italian

**Comment by Thomas101** [comment]
No worries. If it does come up again, let me know I'll try to take another look. It is weird that it keeps coming up intermittently
