### ISSUE TITLE
Minor Menu Typo

### ISSUE THREAD

**Issue by thecjharries** [wavebox/waveboxapp#691]
* Wavebox Version: 3.14.6
* Operating System & Version: Fedora 28
* (Linux only) Install method: 90% sure it was via the RPM installer, but I can't remember.

**Expected & actual behavior**
"Sandbox" is misspelled under the Advanced settings tab.

**Steps to reproduce**
1. Open Wavebox.
2. Open Settings.
3. Go to the Advanced tab.
4. The item is fourth from the top on the lft.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![screenshot 1528017688](https://user-images.githubusercontent.com/6250642/40885158-afce1940-66e6-11e8-9ad9-771f6cdf07e9.png)

Thanks for the great product. This is such a small mistake that it's easy to miss. Have a wonderful day!

**Comment by Thomas101** [comment]
Thanks & thanks for the PR! We've just pushed this out in the beta

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!

**Comment by thecjharries** [comment]
Fantastic!
![screenshot 1536589944](https://user-images.githubusercontent.com/6250642/45303931-90350a00-b4dc-11e8-8bdf-0ff935b86d03.png)
