### ISSUE TITLE
Quick Switcher for Services

### ISSUE THREAD

**Issue by rawkode** [wavebox/waveboxapp#693]
* Wavebox Version: [e.g. 3.0.0]
3.14.6

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Linux

**Is your feature request related to a problem? Please describe.**
Quick Switcher, similar to what Slack offers with Control/Command-K

**Is your feature request related to an account type?**
No

**Describe the solution you'd like**
Ability to press Control/Command-P and be presented with a list of services on the current account. I should be able to type to filter, eventually hitting enter to select.

Perhaps Control/Command-Shift-P should allow this across all services on all accounts.

**Additional info**
The most recently used services should probably be at the top of the list

**Comment by mathieutu** [comment]
Duplicate of #244

**Comment by rawkode** [comment]
Good catch, @mathieutu
