### ISSUE TITLE
Option to move the titlebar buttons to the top-right

### ISSUE THREAD

**Issue by yochaigal** [wavebox/waveboxapp#694]
* Wavebox Version: [e.g. 3.0.0]
3.1.4.6 on Ubuntu 18.04.

**Is your feature request related to a problem? Please describe.**
Nope! 

**Is your feature request related to an account type?**
Nope!

**Describe the solution you'd like**
I'd love to be able to move or hide the titlebar buttons (close, maximize, minimize). I use Ubuntu with Gnome Shell, and every time I put my mouse in the Activities section (top left) I hit the close button! I'm not sure if this is an electron thing.   

**Additional info**
Any other information or screenshots that might help us.

**Comment by nmat** [comment]
Can you please provide what theme you are using in gnome shell?

**Comment by nmat** [comment]
Also are you using the snap version of wavebox or .deb variant?

**Comment by yochaigal** [comment]
CommunitiTheme, though it's the same with Ambiance (the default). I'm using the *.deb.

**Comment by Thomas101** [comment]
I don't think there's support for this in Electron at the moment, however we do have support for some non-standard titlebars. These still have the buttons in the top left, but we could look at adding some settings to move these around.

**Comment by yochaigal** [comment]
OK. It's just weird, since by default Ubuntu 18.04 puts everything in the top-right. I could change it all to the top left to match, but that'd be weird.

Thanks.
