### ISSUE TITLE
Slow response on focus for hidpi

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#695]
* Wavebox Version: 3.14.6
* Operating System & Version: windows 10
* Account type (if applicable): Teams (especially)

**Expected & actual behavior**
More responsive on focus inside the service.

**Steps to reproduce**
Not 100% sure. I only notice that there is a delay in focus for the reply, text etc on hidpi machine. It takes a while before you can actually see where the focus is at with the text cursor.

**Is the bug persistent or intermittent?**
Seems to happen a lot if you switch back and forth. In general going from connected monitor to not connected monitors. 

**Additional information**
As mentioned this seems to be mostly occurring using hidpi laptop. On my desktop machine all seems to work fine. But the laptop does have some quirks with focus of cursor inside the cloud app.

**Comment by Thomas101** [comment]
Hey, are you still seeing this with the beta channel?

**Comment by nmat** [comment]
I did test this using latest beta. Not sure why but wavebox from locked screen really locks it up sometimes. For a short while. It takes time for it to respond in a way.

**Comment by nmat** [comment]
I start to wonder....I do use wavebox through a vpn connection. Could this be affected also maybe?

**Comment by Thomas101** [comment]
I wouldn't think it's anything to do with the vpn unless you're changing connection. Lets see if we can get a reproducable case...

1. Are you sleeping the machine and opening it up again or just taking it to the lock screen without turning off (e.g <kbd>Win</kbd>+<kbd>L</kbd>)?
2. In between locking & unlocking are you changing connection at all?
3. Here's what I've just tried, is it the same pattern as what you're doing?
    * Open Wavebox, switch to teams
    * Type in reply
    * Plugin monitor
    * Continue typing
    * Unplug monitor
    * Continue typing
    * Lock the computer
    * Plugin monitor
    * Unlock the computer
    * Continue typing

I didn't see any focus issues though :-/

**Comment by nmat** [comment]
I believe that this is actually electron doing something strange on hidpi.

I got the same effect when disconnecting the computer from the external monitors (using USB-C connector to a dell docking station)

Once that was done. I then switch on the laptop a Dell XPS 13" laptop with hidpi between windows that uses electron in their base and notice that the window response is slow. So its not only in wavebox. Not sure why this happens.

Can this be something to do with the external monitors and then switching to hidpi on laptop?

**Comment by Thomas101** [comment]
It could be or it could be all the way up at chromium. I did notice some weird ui glitches with chrome whilst testing - I think part of it is down to the scaling of the native ui components.

What are the other electron apps that you saw it with? Is it exactly the same behaviour they exhibit or something slightly different?

**Comment by nmat** [comment]
I tested it using Atom 1.29.0 and noticed the same behaviour there. I guess that I need to test it more also. Seems odd that it takes such a long time for the response.

I did some coding using python and the UI response was so slow after disconnecting the computer and switching windows between chrome and atom when atom was behind the chrome window.

**Comment by nmat** [comment]
I am going to close this off. I have not noticed this behaviour on later versions of electron so will reopen if it occurs again. Keep testing this for you as much as I can.
