### ISSUE TITLE
Preferences text hard to read on long descriptions

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#697]
**Expected & actual behavior**
Just visual effect. Nothing big.

Text should probably be cut a little more before the setting for turning off and on setting.

**Steps to reproduce**
Check the Advanced dialog part.

**Is the bug persistent or intermittent?**
Persistant.

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/41041596-c909572e-699f-11e8-850b-7d7b6c8adb52.png)

**Comment by nmat** [comment]
Verified in master. Looks good! 👍

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
looks good. Closing as it is in beta.
