### ISSUE TITLE
Wavebox not picking up changed Ubuntu default font.

### ISSUE THREAD

**Issue by caschbre** [wavebox/waveboxapp#698]
* Wavebox Version: 3.14.6
* Operating System & Version: Ubuntu 17.04
* (Linux only) Install method: Snap Package
* Account type (if applicable): All affected

**Expected & actual behavior**
To be able to read the font.

**Steps to reproduce**
Install wavebox normally using snap. Using unity tweak tool change the default font to Roboto medium. Then perform an action in wavebox that requires opening a prompt like import/export.

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/326357/41194268-0931d500-6bd6-11e8-9614-a7b3dfcf00ce.png)

![image](https://user-images.githubusercontent.com/326357/41194270-0e8e896c-6bd6-11e8-9778-bfbeef6a97a9.png)

**Additional information**

**Comment by nmat** [comment]
I wonder if this is related to: https://github.com/wavebox/waveboxapp/issues/204 where font is read differently using snap packaging.

**Comment by caschbre** [comment]
Interesting... hadn't thought about snap causing the issue. Any reason to keep using snap instead of doing an apt install?

**Comment by caschbre** [comment]
I ended up re-installing with apt and the font issue has disappeared.

**Comment by nmat** [comment]
I do not know how snap works in general. All I know is that there is so much deps where it could go wrong on other things. Like the one above. IMO this sounds mostly like a snap package issue where snap does strange things to how window behaviour is. It also changes the mouse cursor which can be confusing to say the least.

**Comment by Thomas101** [comment]
This will be down to the snap packaging. Snaps run in their own sandboxed environment and have to bundle all the required libraries they need along with them. (See the file size, snaps are 120+mb whereas standard Wavebox is about 50mb). I suspect when you try to tweak the font the sandbox denies access to it which results in the lovely squares.

If you're happy using the apt repository then I'd continue using that, updates get pushed the same time as snaps and everything should work as you'd expect.

Just out of curiosity, was the font readable before tweaking the settings? If it wasn't I'll take a look at what might have gone wrong there, if they were I'll just close this off.

**Comment by Thomas101** [comment]
Thanks for taking the time to report this, I'm going to close this off for now as switching to the apt distribution fixed the problem and it looks like the source of the issue lays with the Snap packaging. If you have any more trouble though, feel free to comment or open up another issue. Thanks!
