### ISSUE TITLE
Resync (recently) active apps more aggressively

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#70]
It takes quite a while for the notification count to update on an app icon when I eg. delete emails. It would make sense to sync active apps more aggressively (eg. every 5 seconds, or even less).

**Comment by Thomas101** [comment]
Which type of account have you been seeing the delays on? Google or Microsoft?

On Google accounts and Slack accounts we subscribe to a notification channel so we should be getting those as soon as google announce them as ready. As for Microsoft and Trello these are polled on a 60 sec and 30 sec respectively.

In an ideal world we would poll as aggressively as possible but each of the cloud providers place quota limits and restrictions on the amount of requests we can make so we have to balance performance against these.

We have in the past looked at crawling the dom too, but this is fraught with so many problems that we eventually dismissed it as a lost cause.

**Comment by Naatan** [comment]
It's a google account (Inbox), is google just that slow then?

**Comment by Thomas101** [comment]
Google has been having quite a few latency spikes over the last week or so. I've seen it where it doesn't update for maybe 10 seconds or so. Within this time I've tried resyncing manually (Right click on the account and pick resync) but Google still reports all-up-to-date :(

**Comment by Naatan** [comment]
I think this ticket warrants reopening, I've had multiple occasions where Google Inbox just kept saying unread counts for a long time (minutes, not seconds) after I had gone through my emails. When I manually resync them the unread count goes away.

**Comment by Thomas101** [comment]
Yup. Also #108 & #170

**Comment by Thomas101** [comment]
Hi, we've added a fix into 3.1.8 that listens to the Gmail & Inbox UI for changes in the unread count and tries to re-sync based on this as well as what Google tells us. This should improve the responsiveness of unread counts in the majority of cases. Let us know if you have any more trouble

Wavebox should update automatically over the next few hours (or if you don't want to wait restart Wavebox and it will check immediately), or you can re-download from https://wavebox.io/download
