### ISSUE TITLE
[Bug] - Office 365 - Need to reauth every time application is restarted

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#702]
* Wavebox Version: 3.14.6
* Operating System & Version: windows 10
* Account type (if applicable): Office 365

**Expected & actual behavior**
Save the authentication after login.

Need to login everytime.

**Steps to reproduce**
Just to try and do a office 365 auth and restart application.

**Is the bug persistent or intermittent?**
Persistent.

**Additional information**
I think that office 365 is changing the way to authenticate. And there is no form of saved auth for the login. I have tried using the reauth but that still will not allow me to save the information for some reason. I still have to reauth on every start.

**Comment by Thomas101** [comment]
When you sign in, are you presented with a screen such as this one & do you stay signed in when using your normal browser?

![screen shot 2018-06-11 at 10 44 33](https://user-images.githubusercontent.com/103586/41224511-94ef542a-6d64-11e8-89bf-2c3f23e151d7.png)

Just as a side note, if you're testing Wavebox doesn't persist cookies & sessions to disk right away. So signing in and restarting the app right away can sometimes leave you at the login screen. Using the app for a little while wont have this behaviour

**Comment by Thomas101** [comment]
Are you still seeing this? I'm wondering if it could be related to changing your account security info as noted in https://github.com/wavebox/waveboxapp/issues/724

**Comment by Thomas101** [comment]
@nmat is this still an issue or can I close it off? Thanks :)

**Comment by nmat** [comment]
We can close this off. I will repopen if it occurs again. Thanks!
