### ISSUE TITLE
[Bug] - Wavebox mini - hidpi - popout moves to middle of screen if second monitor is default

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#703]
* Wavebox Version: 3.14.6
* Operating System & Version: windows 10

**Expected & actual behavior**
Wavebox mini should popout from tray not in middle of screen.

Goes to middle of screen almost like its open in a external window.

**Steps to reproduce**
Use 1 or 2 external monitors. Bind the keybinding to show the popout in wavebox mini.

Make one of the monitors primary and not the laptop with hidpi.

Now place wavebox on laptop screen and press shortcut to open wavebox. It will open in the middle of the screen and not from the tray.

Only seems to happen on first push of shortcut keys.

**Is the bug persistent or intermittent?**
Persistent.

**Comment by Thomas101** [comment]
Thanks, I see the same. Not totally centre for me, but almost positioned where it should be if the screen was the smaller laptop screen.

Looks like it's using the current wavebox window to determine which window to take the positioning from

**Comment by nmat** [comment]
oh..hmmm...however the tray should popout from where you tell the screen to be primary + screen resolution right?

**Comment by Thomas101** [comment]
Yeah it should appear wherever the tray icon is - regardless of which screen is primary or not. I had thought maybe we weren't fetching the tray bounds when using the keyboard shortcut, but we are.

Looks like it might not be updating the position on screen change or until you actually click on the icon. When I get a chance I'll have a dig through the electron code to see if I can find out what's going on

**Comment by Thomas101** [comment]
Turns out there's no problem with electron, it was the positioning library we're using. Closed via https://github.com/jenslind/electron-positioner/pull/12

**Comment by nmat** [comment]
I can't test this on the current hidpi machine...I am using stable there. :/ Maybe it possible that someone at wavebox can verify it using hidpi machine?

**Comment by Thomas101** [comment]
Yeah worked here with that setup. I don't think it was down to a hidpi screen though.

You can also create the bug with the following (hidpi or no hidpi)...
* 2 screens different sizes
* Make the larger screen the primary one
* Move the mouse onto the smaller screen
* Launch mini with the keyboard shortcut

**Comment by nmat** [comment]
Verified on windows 10 as ok and now shows the popout on primary monitor.

**Comment by nmat** [comment]
Tested in beta as broken

Tested on GIT master today as fixed.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
