### ISSUE TITLE
Open Link in XXX Tab

### ISSUE THREAD

**Issue by mathieutu** [wavebox/waveboxapp#704]
* Wavebox Version: 3.14.7beta
* Operating System & Version: Mac OSX 10.13.4

Hi,
Sometimes I'm on Slack, and my team mates share me a google drive link. I'm actually logged in this drive in another tab in wavebox. 

It could be cool to have an item in the contextual menu to "Open a Link in tab:" with a nested list of all tabs, or better, "Open a Link in tab XXX" a tab selected in the workspace settings.

One other option could be to be able to choose a default tab for link pattern, depending of the tab where are the links. (if a google drive is opened in _slack A_, open it in _google drive B_

What do you think about that?

Thanks!
Matt'

**Comment by Thomas101** [comment]
Adding it to the context menu should be pretty easy. There's a lot of boilerplate code to do most of this.

As for the pattern matching, we do some of that internally for deciding where to open certain windows, but it's pretty complex to map-out. I'll see if there's any way to simplify that so it could be exposed as a setting

**Comment by nmat** [comment]
Gonna test this on macOS and Windows 10.

Should the link open in new window or the indexed service? At the moment when I click on open in the gmail tab it opens the item in a new window.

**Comment by nmat** [comment]
Also noticed that open in gmail when inside gmail will overwrite the tab on gmail and open the file in the "so called gmail inbox tab" which was not able to go back to inbox.

Had to reload the inbox in order to get Gmail back.

**Comment by Thomas101** [comment]
Should open in a new window

For the Gmail/inbox tab, was this with the new window behaviour or just in general? Maybe hive it off to a new issue?

**Comment by nmat** [comment]
Yeah I think I can create a report for it. Will try to make it as descriptive as possible and create one tonight. :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by mathieutu** [comment]
Hi!
Thank you @Thomas101 for you work!
1st point, I've many accounts and so the list isn't really clear:

<img width="448" alt="screen shot 2018-07-23 at 14 30 44" src="https://user-images.githubusercontent.com/11351322/43076654-3089386a-8e85-11e8-8b6e-9a07350966ee.png">

**Comment by mathieutu** [comment]
But when you click in the good link, it works very well for me! Thanks !

**Comment by Thomas101** [comment]
Yeah, that's not great. We've changed the way that Accounts & Services work which means the account has its own identity. That said we should try to pull out some auth info (e.g. email address) up so we can give something more sensible.

On a side note now though, you can change the name of each account under settings now

**Comment by mathieutu** [comment]
Much better, Thanks! 👌 
<img width="454" alt="screen shot 2018-07-23 at 17 52 26" src="https://user-images.githubusercontent.com/11351322/43087900-392fbb94-8ea1-11e8-907c-d98027b0491a.png">

**Comment by Thomas101** [comment]
I know you've renamed them manually, but we've been trying to provide some more info when displaying the accounts. Would be good to get your feedback on it to know if think it's helpful.

We've propogated up any auth info we have within the account (e.g. email address or account name) and also the count of services. Some accounts don't have any extra info whereas others do.

Here are a few examples...

![screen shot 2018-07-24 at 11 32 48](https://user-images.githubusercontent.com/103586/43133079-946c8df4-8f35-11e8-8d23-9763818c03e7.png)
![screen shot 2018-07-24 at 11 32 59](https://user-images.githubusercontent.com/103586/43133080-94833d1a-8f35-11e8-97f4-b0b063f1a137.png)
![screen shot 2018-07-24 at 11 33 10](https://user-images.githubusercontent.com/103586/43133081-9499efe2-8f35-11e8-8315-ec1c8322492f.png)
![screen shot 2018-07-24 at 11 33 14](https://user-images.githubusercontent.com/103586/43133082-94b25712-8f35-11e8-965d-9b3c35bbc4b9.png)
![screen shot 2018-07-24 at 11 33 18](https://user-images.githubusercontent.com/103586/43133083-94c86c82-8f35-11e8-857c-ab2a69c45f8e.png)
![screen shot 2018-07-24 at 11 33 23](https://user-images.githubusercontent.com/103586/43133084-94e04820-8f35-11e8-96ec-a97519c4f922.png)

**Comment by mathieutu** [comment]
Yeah, could be cool, but in my opinion it should appear only if the name isn't customized, or with a on/off feature. Because on my side, as I've named all the services, I don't need theses extra info to recognize them, and it will just be visual pollution to me.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.9. I've also added an option in to disable the extended info if you're just happy with the name you've provided. You can find this under the account settings...
![screen shot 2018-07-26 at 10 23 31](https://user-images.githubusercontent.com/103586/43253938-15610168-90be-11e8-9a28-3fbba33a7677.png)

Thanks

**Comment by nmat** [comment]
Is it possible to have this open the service tab in itself instead of its own window?

At the moment when I use zendesk for example and click the link to open in the Tab for the service it does open a new window. Just wondering if it is possible in the future to open the actual service tab? Or be able to controll it?

**Comment by nmat** [comment]
I can open a new issue for this. In general it would mean that you have option to "open in current tab" or in a window. So it would be more straight to the point.

One example would be if you get the zendesk link in for example slack or other service where someone refers to the item. Right click OR have a option to decide to open in current Zendesk tab (that is running) will just choose that tab and open the item. If you are inside zendesk and click on a item it would open that item in a tab in zendesk already. So IMO there should be a call where you can tell a tab to launch a item for opening. This creates a more dynamic view. But I will open a new feature request based on this information.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
