### ISSUE TITLE
[Feature Request] - Wavebox mini - Services without unread support - disable > no unread

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#705]
* Wavebox Version: GIT master
* Operating System & Version: Windows 10

**Is your feature request related to a problem? Please describe.**
Certain services do not at the moment have support to show unread messages when entering > in the wavebox mini items.

This can be confusing that if there is items that is unread and you go to the list of unread message/items which only says "No Messages" it can be confusing. On availability of showing unread then the > item should be available and disable if it is not supported.

**Is your feature request related to an account type?**
All account types.

**Describe the solution you'd like**
Either disable the ability to enter the unread list. Or have something in there that gets you to say "Can't read unread list." or something that can be more descriptive. So its not considered a bug. Otherwise the option/list is a bit useless.

**Comment by Thomas101** [comment]
Do the changes that I've made in 4.0.0 help with this? It still displays the no unread but the badge is more prominent in the ui

**Comment by nmat** [comment]
Yes definitely...I will close this.

Thank you!
