### ISSUE TITLE
Open a url in a wavebox window

### ISSUE THREAD

**Issue by phuongnd08** [wavebox/waveboxapp#709]
* Wavebox Version: 3.14.6
* Operating System & Version: Mac

**Is your feature request related to a problem? Please describe.**
There are time we need to open a link to an item. For example, we are using intercom, and from time to time I need to navigate to a url like this: 
https://app.intercom.io/a/apps/abababa/inbox/inbox/1111111/conversations/22222222
to take advantage of the signed in session.
**Is your feature request related to an account type?**
Intercom

**Describe the solution you'd like**
press Cmd + Option + V => paste the url => enter => go

**Comment by mathieutu** [comment]
Hi. 
I found this one, because I have the same need. Not about intercom but with every service.

It's about the same than in #704 (Open Link in XXX Tab):
we could really simply have a context menu on a tab logo in the sidebar like "Open a window in this scope", which open a new window, with the url field editable, and... voilà ! 

@Thomas101 What do you think about that?

**Comment by phuongnd08** [comment]
The url may not always presented in Wavebox itself. For example we are using the official slack desktop app but want to open that in the intercom tab of Wavebox

**Comment by mathieutu** [comment]
yeah, the same for me, it's why I proposed this solution. 😅
It's not the same issue of #704, but a good companion of it.

Didn't I make me understood? (I'm not english native, so it's possible. Feel free to ask if you want a reformulation)

**Comment by mathieutu** [comment]
I've played with the devtool to show you what's in my mind:


<img width="318" alt="screen shot 2018-06-29 at 14 16 25" src="https://user-images.githubusercontent.com/11351322/42091921-6dae6814-7ba7-11e8-930d-c3f4af68f0f4.png">


<img width="885" alt="screen shot 2018-06-29 at 14 18 55" src="https://user-images.githubusercontent.com/11351322/42091960-8a038b0c-7ba7-11e8-81c1-b5f076952d8c.png">

**Comment by phuongnd08** [comment]
I'm not sure, perhaps just make the url bar editable?

**Comment by Thomas101** [comment]
Hi, this should now be possible with the latest beta of Wavebox version 4.5.11. If you head to Settings > Links and change on of the link opener behaviours to `Ask what to do each time` or `Open in Wavebox Window` you'll then be able to shift+click, ctrl+click or cmd+click to open urls in a signed in session.

![screenshot 2019-01-23 at 15 33 56](https://user-images.githubusercontent.com/103586/51617594-72fd5700-1f24-11e9-9333-0aaf7bab9a01.png)


If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel).

Let me know if this works for what you're trying to do, Thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by mathieutu** [comment]
Hi @Thomas101! 
Actually this is cool, but not what it is about here 😕.

The subject was open a new **empty** window in a scope, and paste directly an url, like a real browser!

I'll let you see the previous messages and images to understand 😉.

**Comment by Thomas101** [comment]
@mathieutu sorry, my bad!

**Comment by Thomas101** [comment]
@mathieutu lets try again :). The latest beta 4.7.12 has this, you can click in and edit any of the address bars and also I've added the context menu item to `Open a New Window in this service` which just opens up a blank window...

![screenshot 2019-03-07 at 09 55 38](https://user-images.githubusercontent.com/103586/53948253-532e8680-40bf-11e9-941b-4c80be2165c1.png)
![screenshot 2019-03-07 at 09 55 50](https://user-images.githubusercontent.com/103586/53948257-54f84a00-40bf-11e9-9429-455a5d796686.png)

**Comment by mathieutu** [comment]
This is perfect, and amazing, as usual! 🎉

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
