### ISSUE TITLE
Linux repository for betas

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#710]
I am in the beta channel, so I get a warning message everytime a new beta of Wavebox is out.
However, since I choose to use the repository to keep my Wavebox up to date, I only get an update when a new stable version is out.
Is there a repository that includes beta releases?
I am on linux openSUSE Tumbleweed.

Thank you in advance.
Cris

**Comment by nmat** [comment]
There are some instructions on the wavebox website if you check:

https://wavebox.io/kb/beta-channel

Go further down the page and there are some instructions on the beta channel using repos. Please check there and see if that helps to get you going with testing the beta channel.

**Comment by nmat** [comment]
To give you some quick reference:

Linux: Installed via yum repository
Add the archive Key
sudo rpm --import https://wavebox.io/dl/client/repo_beta/archive.key

Edit your repo sources in /etc/yum.repos.d/
2.1 Remove wavebox.repo
2.2 Add the beta repo sudo wget -P /etc/yum.repos.d/ https://wavebox.io/dl/client/repo_beta/yum/wavebox_beta.repo

Update and Install Wavebox
yum install Wavebox

**Comment by Cris70** [comment]
Thank you @nmat, this is great news!

**Comment by Cris70** [comment]
Yes, thank you!!
I just had to slightly adapt the instructions to work with zypper.

**Comment by nmat** [comment]
could you share what else you needed to do?

its always good to know if the instructions needs some more information :)

**Comment by Thomas101** [comment]
@Cris70 thanks for the feedback on that! I've added a separate Zypper section to the KB article with some updated instructions
