### ISSUE TITLE
[Bug] - Wavebox preferences - test notification not working in git master

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#711]
* Wavebox Version: GIT master [2018-06-22]
* Operating System & Version: windows 10

**Expected & actual behavior**
Notification test to show in ui

Nothing happens.

**Steps to reproduce**
Just try to click on test notification

**Is the bug persistent or intermittent?**
Persistant

**Additional information**
Works on macOS with git master
Works on windows 10 (wavebox 3.14.7beta)

Could this be related to build problems on windows 10?

**Comment by Thomas101** [comment]
I see the same here. If I check out the beta branch and run a build of that I also see the same, so it's not something that's changed in master but more of an enviornment thing.

Reading back through this electron issue https://github.com/electron/electron/issues/10864 it looks like a few other people have the same issue. Calling `app.setAppUserModelId` and adding a shortcut to the start menu with the same app id seems to work for others. Both of these things happen when Wavebox is installed via the installer, but obviously not with the dev build.

I've tried hacking around setting the userModelId manually but to no avail, so something else must be missing or I'm setting something incorrectly.

**Comment by nmat** [comment]
As long as it works in beta/stable the rest can wait. Just making sure it is tested before Beta -> Stable instead of testing it in master which seems odd if you consider release cycle. But its fine. :)

**Comment by Thomas101** [comment]
I've just tried this on a windows box in two ways
1. A proper build with installer etc that's come off our build boxes and it works correctly ✅
2. The same version built out of git just run with `npm start` and it doesn't work ❌

Looks like it is down to not having the shortcut with the AppUserModelId in the start menu. Going to close this off :)
