### ISSUE TITLE
Sidebar scrolling when mouse scrolling past page ends.

### ISSUE THREAD

**Issue by GreyCorbin** [wavebox/waveboxapp#712]
* Wavebox Version: 3.14.6
* Operating System & Version: Ubuntu 18.04 LTS
* (Linux only) Install method: Ubuntu Software App

**Expected & actual behavior**
If you scroll past the top or bottom of a page using the mouse scroll wheel the sidebar will scroll.  I wouldn't expect them to be tied together

**Steps to reproduce**
Have enough Icons that they don't fit all at once in the sidebars display area.  Scroll a web pages past the bottom using a mouse with a scroll wheel.

**Is the bug persistent or intermittent?**
Persistant.

**Screenshots**
Moot as it can't show movement

**Additional information**
None.

**Comment by Thomas101** [comment]
Thanks, I'll see if I can find out what's going on here

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.1.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
