### ISSUE TITLE
Auto-Scroll Sidebar when dragging Icons into position.

### ISSUE THREAD

**Issue by GreyCorbin** [wavebox/waveboxapp#713]
* Wavebox Version: 3.14.6
* Operating System & Version: Ubuntu 18.04 LTS

**Is your feature request related to a problem? Please describe.**
When you have more icons than the area currently viewable in the sidebar, and you want to drag an icon past the top or bottom, you can't.  You have to drag it the top/bottom of the area, scroll, drag to top/bottom, scroll...

**Is your feature request related to an account type?**
N/A

**Describe the solution you'd like**
It would be nice if the bar auto-scrolled to facilitate moving the icon to where you want it.

**Additional info**
None.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.1.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
