### ISSUE TITLE
Move Upgrade Countdown once the countdown has completed

### ISSUE THREAD

**Issue by petejodo** [wavebox/waveboxapp#714]
* Wavebox Version: 3.14.6
* Operating System & Version: Ubuntu 18.04

**Is your feature request related to a problem? Please describe.**
The distraction of the premium mode countdown, especially once the countdown has finished and is **`00`**. I get wanting to promote the premium version but it's current position is in a visual "hotspot", making it distracting. It doesn't provide any actual critical function of the application and therefore creates a negative experience for the user.

**Is your feature request related to an account type?**
No.

**Describe the solution you'd like**
So I understand wanting to promote the premium version. I think when the initial premium trial is occurring and the user is actually using the premium trial, it's fine as it is as well as its location. However, when that countdown is over, the countdown should disappear from that location.

**Additional info**
In order to still promote the premium version, a specifically designed icon (e.g. a dollar sign) can be added at the bottom, right above "Settings" and "Add Account", that, when hovering over it, it shows the pop out that currently shows when hovering over the countdown.

If you're going to provide a free version, don't purposely provide a sub-par experience. Users should be drawn to getting the premium version due to additional features and functionality, not to remove some eyesore.

I've thought about just installing Wavebox from source and changing `true` to `false` [here](https://github.com/wavebox/waveboxapp/blob/master/src/shared/Models/User.js#L39) with the hope that that would remove it. It's not that I don't want Premium or not, I just haven't decided that I need it yet since currently it feels like the free version does everything I want.

**Comment by Thomas101** [comment]
Thanks for the feedback, I'll pass this on to our design team, we've got some new stuff coming up with new layouts etc, so this may be something that changes in the future anyway.

**Comment by PeteJodo** [comment]
Thanks for the response, not sure why I was so aggressive in my comment. The product is great, I think I was just annoyed with that countdown haha
