### ISSUE TITLE
[Bug] - wavebox tooltip not removed on show/hide when moving mouse to fast away

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#718]
* Wavebox Version: GIT Master (2018-06-30)
* Operating System & Version: windows 10

**Expected & actual behavior**
Auto hide tooltip even if mouse is moved away to fast.

The tooltip is shown until mouse is moved back to the arrow line for hide/show.

**Steps to reproduce**
Hold mouse over tooltip
Hide and move the mouse away before it has done the process completely.

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**

![image](https://user-images.githubusercontent.com/383031/42124577-69b85f94-7c65-11e8-85e5-66beb27da7a2.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Thanks, I'll take a look. This has probably come back up because we dropped the old tooltip implementation and moved to a new one

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
