### ISSUE TITLE
Gmelius extension is unavailable

### ISSUE THREAD

**Issue by jlumbroso** [wavebox/waveboxapp#719]
* Wavebox Version: 3.14.7beta
* Operating System & Version: macOS 10.13.5
* Account type (if applicable): Gmail, with Gmelius

**Expected & actual behavior**
Gmelius stopped working suddenly, and since then Gmelius extension is no longer listed in the installable extensions.

**Steps to reproduce**
With the current version of Wavebox, opening the program, settings and going to the extension section will show that Gmelius is not listed.

**Is the bug persistent or intermittent?**
This seems persistent with the current version of Wavebox. (I tried restarting the client, rebooting the computer, and adding/removing my account. Although none of these steps sound like they would help, it seemed better to be exhaustive.)

**Additional information**
No announcements have been made about this, therefore I am assuming it is a bug rather than an intentional removal of Gmelius from the list of supported extensions (#138).

**Comment by nmat** [comment]
@jlumbroso could you let me know if you are using pro version or non pro version of wavebox?

When I look at the extension list it seems that it is marked for Pro accounts?

Did the time go out for the free pro version testing?

**Comment by jlumbroso** [comment]
@nmat Thanks for the follow-up. I indeed have an active Pro subscription that does not appear to have lapsed.

<img width="584" alt="screen shot 2018-07-01 at 10 32 06 am" src="https://user-images.githubusercontent.com/11770469/42132545-5aba24f4-7d1a-11e8-8a5a-9c672a3f8617.png">

Today surprisingly the extension is back in the list and is working again in Gmail (which it was not for the past couple days). I can't confirm whether its absence was real, or a combination of the renaming of the extension from "Gmelius" to "Shared Inbox & CRM for Gmail", and of Gmelius not loading properly in the Gmail frame.

<img width="514" alt="screen shot 2018-07-01 at 10 35 29 am" src="https://user-images.githubusercontent.com/11770469/42132566-b974e754-7d1a-11e8-9438-aba6e77f506d.png">

Either way, problem is gone, but I will keep an eye out for issues with Gmelius.

**Comment by Thomas101** [comment]
That's a weird one, nothing changed our end. Re-open this if you see this again and I'll take a closer look. Thanks!

**Comment by christiancl1** [comment]
Hi!

I'm newhere, just installed Wavebox and I just can't find Gmelius to install it. Any help?

Best regards,

**Comment by nmat** [comment]
@christiancl1 it is located under extensions in preferences. Also do you use pro or free version?
