### ISSUE TITLE
Slack Keyboard Shortcuts Intercepted

### ISSUE THREAD

**Issue by jeremymarx** [wavebox/waveboxapp#72]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.3
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Win 10

At least two key Slack keyboard shortcuts are being intercepted by wavebox.

Ctrl-T: Used by slack for fast channel switching.
In wavebox/slack: Does nothing.

Ctrl-F: Used by slack for context-aware search. One example of "context-aware":  In any channel, Ctrl-F will not only place the cursor in the search box, it will also insert the correct search tags to search only the current channel. 
In wavebox/slack: Opens a non-slack search box that appears to search the screen contents.

There are likely others.

**Comment by Thomas101** [comment]
I think these shortcuts are only in the slack desktop clients and not in the web version, so we'll need to look at adding these in to bring it up to parity. Thanks

**Comment by Thomas101** [comment]
Added <kbd>Ctrl</kbd>+<kbd>F</kbd> support in 3.1.6+

**Comment by oltreseba** [comment]
It would be really nice to have `ctrl`+`T` support also as for medium organization it's extremely fast to switch from a chat to an other like that.

**Comment by nmat** [comment]
Hello, You can always use the Ctrl+K keybinding instead or Ctrl+Shift+K to switch between them. I believe that slack desktop client also now uses Ctrl+K instead of Ctrl+T

**Comment by nmat** [comment]
If I am not wrong this one could be marked as fixed right?

Since the keybinding that does work now are:
Ctrl+K - Quick switch channel/conversation
Ctrl+F - Go to search in slack (3.6 here at least this works in)

**Comment by Thomas101** [comment]
<kbd>Ctrl</kbd>+<kbd>F</kbd> got fixed again in 3.6 (this was broken at some point by slack changes).

I'm seeing <kbd>Cmd</kbd>+<kbd>K</kbd> and <kbd>Ctrl</kbd>+<kbd>K</kbd> working now which is consistent with the Slack browser experience - however <kbd>Ctrl/Cmd</kbd>+<kbd>T</kbd> is still present in the app

**Comment by nmat** [comment]
But then, should slack connection use the webexperience or the desktop experience?

Because then you would have to overwrite the Ctrl+T right inside slack connection window if I am not wrong?

**Comment by Thomas101** [comment]
The desktop version supports both `K` and `T` so I think we can do that. They probably disalbed `T` in the browser as this is normally the shortcut for new tab

**Comment by nmat** [comment]
agreed. If that is the case then of course. Since wavebox does not use Ctrl+T for anything else in general right now. 👍

**Comment by Thomas101** [comment]
Hi, I’m going to close this off as you can use <kbd>Cmd / Ctrl</kbd>+<kbd>K</kbd> to access the jump list. The use of the `T` shortcut is normally reserved in a browser environment which is why Slack doesn't make the shortcut available and this is the same case with Wavebox. Thanks
