### ISSUE TITLE
CMD+N opens GMail when I'm using Outlook

### ISSUE THREAD

**Issue by ItalyPaleAle** [wavebox/waveboxapp#721]
* Wavebox Version: 3.14.6
* Operating System & Version: macOS 10.13.5

**Expected & actual behavior**
My main mail system is Office 365 (Outlook). When I press CMD+N to compose a new email, Wavebox automatically pulls up GMail in the compose view, rather than showing me the Outlook compose view.

**Steps to reproduce**
Press CMD+N

**Is the bug persistent or intermittent?**
Persistent 

**Additional information**
In general, it would be nice if I could set Outlook as my default email provider

**Comment by Thomas101** [comment]
This is down to the lack of support we have for hooking keyboard shortcuts into outlook at the moment. We've looked at hooking into the dom to trigger events previously, but Microsoft is keen to block this to prevent spam. 

On the other hand, I think we should be able to auto-trigger shortcuts (e.g. outlook online responds to <kbd>Ctrl</kbd>+<kbd>N</kbd>) which I think should get us most of the way there.

I'll take a look to see if this is feasible

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
