### ISSUE TITLE
Unread activity in tray

### ISSUE THREAD

**Issue by trollfred** [wavebox/waveboxapp#722]
Right now tray only shows unread count, which is awesome, but it would be even more awesome to also show if there is "uncounted" unread activity and unread counter is 0. like it happens with badges.

**Comment by Thomas101** [comment]
Yeah I see what you mean. Do you have a solid use-case with an account type? Might help us scope it out a bit more easily

**Comment by trollfred** [comment]
![image](https://user-images.githubusercontent.com/3583824/42443093-d44aefda-836c-11e8-8e7d-54d5705e88bc.png)
What I mean is, when there are only uncounted activities on badges, those white dots in red circles. In that case tray icon stays uncolored, you simply don't see that there are activities until you open the window. So it would be cool if tray icon also became red (custom-colored) with a dot.

**Comment by Thomas101** [comment]
That looks like a bug - it should be showing up, but I'm also seeing that it's not! I'll check what's happening

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, it should be colored the same as the color under tray settings rather than taking the color from the account. We chose not to pick the account color as there may be multiple items with unread activity. 

As for the icon placement, which OS are you using & can you send a screenshot?

**Comment by trollfred** [comment]
Sure, It's High Sierra 10.13.6
<img width="93" alt="screen shot 2018-07-24 at 13 45 25" src="https://user-images.githubusercontent.com/3583824/43136236-6223ff18-8f48-11e8-952e-1e7fc15ba5ac.png">
<img width="482" alt="screen shot 2018-07-24 at 13 48 06" src="https://user-images.githubusercontent.com/3583824/43136240-63f86108-8f48-11e8-8ce2-142a188c67e9.png">
and what I mean - I use white on red colors for unread icon, but that dot is still black on transparent, I think it's better when its red

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.9. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
