### ISSUE TITLE
Outlook account (with external verification) only shows sign in page

### ISSUE THREAD

**Issue by tomncooper** [wavebox/waveboxapp#723]
* Wavebox Version: 3.14.6
* Operating System & Version: Arch Linux (Kernel 4.17.4)
* (Linux only) Install method: AUR [wavebox-bin](https://aur.archlinux.org/packages/wavebox-bin/) via yaourt 
* Account type (if applicable): Office 365

**Expected & actual behaviour**
I was attempting to add my University Outlook/Office 365 account. This is authenticated by an external service (Shibboleth). The add account procedure works as expected and takes me to the external site to authenticate. This again works correctly and the account setup completes successfully. The unread count and new mail notifications work fine (as you can see in the screenshot below), however if I click on the email, calendar or contacts service it simply shows the sign in screen? 

Oddly I can successfully use the Office 365 elements (Word, Excel and PowerPoint etc) and they show the correct account information. Just the Outlook elements (email, calendar and contacts) show a sign-in page only? 

I have tried persisting cookies, deleting cookies, deleting the account and and even deleting and reinstalled wavebox and this issue persists.

**Steps to reproduce**
Add an externally authenticated Office 365 account.

**Is the bug persistent or intermittent?**
This is persistent and is replicated on other Arch based Linux and Windows 10 machines (with the same Office 365) account.

**Screenshots**
![screenshot_20180709_151951](https://user-images.githubusercontent.com/4671291/42456002-a4ce7f82-838b-11e8-842f-09a4ede1ab05.png)

**Additional Information**
Via the Word/Execl/Powerpoint tabs it is possible to check the Office 365 account information and Wavebox is approved to access the account (see screenshot below): 
![screenshot_20180709_152448](https://user-images.githubusercontent.com/4671291/42456299-635c03a2-838c-11e8-9098-d2ba6b2931b8.png)

**Comment by tomncooper** [comment]
I can access the outlook p

**Comment by tomncooper** [comment]
I can access the Outlook services by clicking through to the Account section via Word/Excel/Powerpoint an then selecting Outlook, I just cannot access them via the dedicated tabs in the Wavebox UI?

**Comment by nmat** [comment]
Hmmm I can access them. Not sure what is going on here with your connection. I use stable release on windows 10 and have no problems accessing them.

**Comment by Thomas101** [comment]
Just as a guess (based on the colour of the account in the sidebar) did you add the account using the `Outlook` button on the add screen? Instead, use the `Office 365` one, this should take you to the correct sign in pages etc

**Comment by tomncooper** [comment]
@Thomas101 That was the issue! A nice easy fix. Thanks for pointing that out.
