### ISSUE TITLE
Android Messages doesn't auto-refresh on launch

### ISSUE THREAD

**Issue by yochaigal** [wavebox/waveboxapp#726]
Wavebox 3.14.6 on Ubuntu 18.04 64bit.
Thinkpad X1 Carbon 4th gen.

**Expected & actual behavior**
Added Android Messages to app; works great! However, you have to click on Android Messages every time you either launch the app or wake up the machine. Sleep is disabled. 

**Steps to reproduce**
Launch wavebox; you have to click on the messages icon to wake it up. Suspend, then do the same.

**Is the bug persistent or intermittent?**
Persistent. 

**Additional information**
Other apps like Slack and Gmail don't need me to wake them up each time.

**Comment by nmat** [comment]
When I tested it I noticed some strangeness using either wifi or the phone network. It seems that sometimes it loses the connection.

Can you see if you can reproduce it using the android messages app directly in chrome for example? How the effect is there?

**Comment by yochaigal** [comment]
I can disable it here and use a pinned/app version in Chrome, sure. I bet
it will have the same issue, which tells me that the wavebox version
probably just needs to poll for refresh every once in a while.

**Comment by yochaigal** [comment]
OK, so I created a "shortcut" and ran it as an app in Chrome.

Then I suspended; woke the machine and sent a test message - I got it, and was notified (I was in a different workspace). 
One difference from wavebox: I wasn't prompted to "refresh" the chrome app. I'll test again when it's suspended for longer.

**Comment by yochaigal** [comment]
I wonder: would "restore last page on load" help here at all?

**Comment by nmat** [comment]
unfortunately I am not 100% sure. This test is to see how chrome handles the service also.

**Comment by Thomas101** [comment]
> I wonder: would "restore last page on load" help here at all?

Nah, that just reloads the last url you were at when waking from sleep.

Which install method are you using for Wavebox? I seem to remember the snap version could be a bit funny with sockets on certain ports - wonder if this could be related.

**Comment by yochaigal** [comment]
I'm using the repo one (not snap).

**Comment by Thomas101** [comment]
@yochaigal are you still seeing this with the current version of Wavebox?

**Comment by yochaigal** [comment]
No, it's been good for a while. Thanks for checking in!

Still waiting on the ability to right-click on an email and "copy email
address" though...

**Comment by Thomas101** [comment]
Did you raise the copy email address elsewhere? Sorry I'm missing it

**Comment by yochaigal** [comment]
I did, but using my work email:
![image](https://user-images.githubusercontent.com/817479/51621537-bd6ddc00-1f02-11e9-9e0b-a255d916e98b.png)

**Comment by Thomas101** [comment]
Yep, thanks got that. I made a change back in [October](https://github.com/wavebox/waveboxapp/commit/74af78a6f533f5abbd00f9c926a114703756d012#diff-58068e44e3d7e9489f07a7921dc34bd0) which should have changed the behaviour to copy the email address - it's just that the menu stayed as `Copy Link Address`.

I'll change it so that menu display 'Copy Email Address` in this intance :)

**Comment by Thomas101** [comment]
I'll close this off, as the original issue has been resolved. The `Copy Email Address` will ship out to the beta channel shortly :)
