### ISSUE TITLE
[bug] website - items links to # and nothing more

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#727]
**Expected & actual behavior**
Links can be set to be styled hover but should link to something at least. If they are not links then it should be changed. See screenshot

in CSS you could probably use p:hover {} instead of the link unless there actually should be a link.

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/42876421-e6b40f64-8a86-11e8-845d-e43a13d2b638.png)

**Comment by Thomas101** [comment]
Thanks, those should just be hovers ;-)

**Comment by nmat** [comment]
Here is another list of links that is linked to # so in my head from surfing the site they would be clickable.

![image](https://user-images.githubusercontent.com/383031/43354363-472d041a-924b-11e8-916c-207167ce808d.png)

**Comment by Thomas101** [comment]
I'll nudge the website team about this again :)
