### ISSUE TITLE
Integration with LastPass, feature request

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#728]
* Wavebox Version: [e.g. 3.xx.yy]
3.14.7beta

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows 10

**Is your feature request related to a problem? Please describe.**
Yes, A workability problem

Some information about what the problem is.
The main problem is that Lastpass is used to store all of my UIDS and PWs and site URL .  When a site is selected the appropriate URL is opened in whatever browser is being used at the time and the UID/PW is filled in.  Optionally LP will also simulate pressing the enter key to do the logon).   For the sites that I consider sensitive the LP Generate PW feature is used which can (depending on user setting) generate a very long and obfuscated PW which I would not want to have stored in WB.  For these sites I need to go to a browser, log into LP and copy ( after reconfirming my logon PW) , return to WB and paste the PW into the logon box.

**Is your feature request related to an account type?**
For example, a Gmail account or Trello account
No, This is for any site that requires a logon.

**Describe the solution you'd like**
Information about what you want to happen or like to see.
Integration with Lastpass. so it will logon to the site instead of having the UID/PW either stored in WB or entered manually.

**Additional info**
Any other information or screenshots that might help us.
Can be provide as requested.

**Comment by CheechGe** [comment]
Note:  In all likelihood this will probably require a joint effort with the lastpass vendor as it is an addon to the supported browsers.

**Comment by Thomas101** [comment]
We have got some chrome extension support, but we don't have complete coverage of the API as yet. Lastpass is high up on our list (I'm also an avid LP user) and we're hoping to put some work into extending the API and support during this beta cycle or the next!

**Comment by CheechGe** [comment]
Hi Thomas:

Thank you for your response.  Glad to hear that LP Is a priority for WB.  I
just sighed up for the full version and am liking it so far.  I am looking
forward to its availability and am on the beta channel and will most
definitely test it when it does becomes available there.

I do have another enhancement request that I really need and I think will
be useful to others too which I will submit through Github.

Regards,

Frank

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.14. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by CheechGe** [comment]
Installed the latest release, will test it out and report back. Thank you.

**Comment by CheechGe** [comment]
Attempted to install the LastPass extension but could not complete it.  See SS below.  Did I miss doing something first?

![image](https://user-images.githubusercontent.com/3653639/44225027-474a9980-a15a-11e8-882d-305013ae2a81.png)

**Comment by CheechGe** [comment]
The same site as in the previous post but directly with a browser.   All LP stored credentials were loaded and the login was automatic (as set).

![image](https://user-images.githubusercontent.com/3653639/44236221-3873df00-a17a-11e8-892a-bd823531e191.png)

**Comment by Thomas101** [comment]
Which site were you trying to login to? If you right click on one of the fields does the lastpass menu appear as one of the options and does autofill work from there?

**Comment by CheechGe** [comment]
The site shown above was my city's library site.

After I tested it the last time I removed it from Wavebox.  Just now I re-added it using the URL that was in Lastpass and it worked fine.  I think the last time the URL was to the main site and I had navigated to the logon page.  Also there was some reboots and a browser update since then so who knows.  It gets somewhat difficult to track moving targets these days.

In any event the LP feature is working on the site where it had failed before.  I'll do some testing with it.  

Thanks, nice job.

**Comment by CheechGe** [comment]
I was trying a few things and this particular situation returned some unexpected results.  I realize using LP this way might be beyond the intent of the feature but will report it anyway.

Using an account setup as a web page and the account is setup in LP not to do an auto logon if a different site is selected from say the "Recently Used" LP section the site is opened in a standalone window (which is fine).  However, even though the site is setup to auto logon the credentials are not filled in..   

The logon input password area has a key shaped icon in password input area but the icon cannot be activated.  Mousing over the password input area displays a "Right click" message which if done displays a context menu which contains an LP sub menu selection.  The selections in the sub-menu all default to the original site in Wavebox and not the one selected from Recently Used negating the ability to logon to the site using this method.   However, if on selects the item "Open Page in Browser" the page is brought up in the browser and LP does logon to it.  The widow that Wavebox opened remains open.

It is unclear what the intent is using WB/LP in the manner described but the way it works is a bit strange and cumbersome.

**Comment by cheey2003** [comment]
@Thomas101 Thanks for the extension, it is working great on my end 👍

**Comment by CheechGe** [comment]
After reading the post above I thought I missed something so I retested to see if the problem I had previously was still there, it was.

To be accurate though, the extension works correctly if using LP to logon to the site defined as the account site. where it seems to go astray is if in  the account site and LP is used to navigate to a different site, say one that is in the LP Recently Used section.  Things get a bit strange after that.  The  screenshots show what occurs.  Maybe this goes beyond the intent of the extension.

![wavebox_01](https://user-images.githubusercontent.com/3653639/45175431-709b9a00-b1db-11e8-8c93-f4f1ac918650.png)

![wavebox_02](https://user-images.githubusercontent.com/3653639/45175440-75604e00-b1db-11e8-935a-3968a2f714d7.png)

![wavebox_03](https://user-images.githubusercontent.com/3653639/45175448-78f3d500-b1db-11e8-9da7-2e7786393e3c.png)

![wavebox_04](https://user-images.githubusercontent.com/3653639/45175458-7ee9b600-b1db-11e8-9564-71dd6f592004.png)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!

**Comment by CheechGe** [comment]
Well maybe, but it still doesn't work the same as using LP in a browser.   See SS.  WB 4.0

![wavebox_lp_01](https://user-images.githubusercontent.com/3653639/45292976-d8e0c900-b4c4-11e8-9b0c-5957e9cbef50.png)

![wavebox_lp_00](https://user-images.githubusercontent.com/3653639/45292949-c797bc80-b4c4-11e8-94e6-d4dfc9adebe2.png)

**Comment by Thomas101** [comment]
@CheechGe at the moment we don't have the ability to bring up the in-page popup in the same as in your browser. We're looking into ways that we can add support for this for a future release.

It's still possible to autofill the fields from the popup that appears or from the right-click context menu

**Comment by CheechGe** [comment]
Yes, I realize that.  My comment that it doesn't work the same and
therefore requires more mouse clicks to logon.

The other thing I noticed was that I stay logged into LP overnight.  It
doesn't seem that the LP auto logoff feature based on a time interval is
working.  This creates an exposure especially since wavebox doesn't have
it's own security.

**Comment by CheechGe** [comment]
@Thomas101 

It seems that in wavebox that even after a reboot that one remains logged on to LP  while in a browser that's not the case.  The only thing that was done as shown in the screenshots was to reboot the PC and start wavebox and a browser. 

![wavebox_lp_02](https://user-images.githubusercontent.com/3653639/45320707-677b3780-b511-11e8-8dd8-c0a32b1e6dc7.png)
