### ISSUE TITLE
Can't join meeting (hangout) from google calendar

### ISSUE THREAD

**Issue by Naatan** [wavebox/waveboxapp#73]
Nothing happens when I click join meeting. I'm guessing there's some logic that opens this in the hangout tab that isnt working?

* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.3

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Tested on macOS (latest) and Arch linux

**Comment by Thomas101** [comment]
I'll take a look into this one and see why it's not being picked up

**Comment by Thomas101** [comment]
Hi, this should be fixed in the latest 3.2.0 release with the experimental window open enabled. There’s some instructions on [how to enable it here](https://blog.wavebox.io/testing-the-new-window-opener/)
