### ISSUE TITLE
Reloading slack returns to slack.com

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#731]
* Wavebox Version: 3.14.8beta
* Operating System & Version: all
* Account type (if applicable): Slack

Right-click reload returns to slack.com. Introduced in 3.14.8

**Comment by nmat** [comment]
Verified working in GIT master.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.9. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
