### ISSUE TITLE
[Bug] - slack service with slack team as second service - Sleep changes to original team on awake 

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#732]
* Wavebox Version: 3.14.8beta
* Operating System & Version: windows 10
* Account type (if applicable): Slack (inside slack service)

**Expected & actual behavior**
Awake underlying slack team with the same team. Not main service.

Awake goes to main service slack team on awake.

**Steps to reproduce**
1. Add a main slack service
2. Right click and add "Add another service"
3. Sign in to a different workspace
(at this point you have first slack team and second)
4. Try to wake the second service after sleep

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![2018-07-23_15-27-39](https://user-images.githubusercontent.com/383031/43079328-1a0f5922-8e8d-11e8-8135-4fc0428b87dd.gif)

**Additional information**
Ignore icons for now reporting in another issue.

**Comment by Thomas101** [comment]
This is because the integrated services share the same credentials, cookies, sessions and storage in the same account/group. This means when you add a second slack account Wavebox doesn't differentiate between them - you're just one user.

We've added the in-account warning about service sandboxing when adding two accounts that are the same, but there's no method to unlink these two at the moment.
![screen shot 2018-07-23 at 15 57 37](https://user-images.githubusercontent.com/103586/43084771-3c43b566-8e91-11e8-840e-2a2663386eff.png)

**Comment by Thomas101** [comment]
I've added the ability to Sandbox a service within the account. When you add a second slack into an account you'll get the same info popup and by selecting `Keep here and sandbox` it will move the service into its own sandbox. This means it won't share cookies or auth credentials. You'll then need to reauthenticate the account and sign back in, but you'll now be able to add slacks to the same account :)

![screen shot 2018-07-25 at 10 19 39](https://user-images.githubusercontent.com/103586/43194328-0056259c-8ffa-11e8-8191-9a8f1d8cb9c8.png)
![screen shot 2018-07-25 at 10 19 45](https://user-images.githubusercontent.com/103586/43194336-03df8852-8ffa-11e8-9981-6efb050e50ae.png)
![screen shot 2018-07-25 at 11 04 19](https://user-images.githubusercontent.com/103586/43194550-8a3b39b4-8ffa-11e8-8e09-c4bae3b6e509.png)

**Comment by nmat** [comment]
Tested it and seems to work just wonders! Awesome!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.9. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
