### ISSUE TITLE
Sidebar overhang in compact or tiny mode

### ISSUE THREAD

**Issue by jason0x43** [wavebox/waveboxapp#733]
* Wavebox Version: 3.14.8beta
* Operating System & Version: Mac OSX 10.13.6

**Expected & actual behavior**

Setting the sidebar mode to "compact" or "tiny" should shrink the entire sidebar width. Instead, there is an overhang at the top of the sidebar.

This overhang appears to be the width of the default sized sidebar, and stays the same width whether the sidebar is compact or tiny.

**Steps to reproduce**

Set the sidebar width to "compact" or "tiny".

**Is the bug persistent or intermittent?**

Persistent. I've tried refreshing the UI and restarting WaveBox.

**Screenshots**

<img width="73" alt="screen shot 2018-07-23 at 09 24 59" src="https://user-images.githubusercontent.com/1042866/43079363-eb69a190-8e5a-11e8-8f12-84eeec98678f.png">

**Additional information**

**Comment by nmat** [comment]
This seems to happen when the icons are all in the sidebar and the topbar is not used at all.

So if the topbar does not exist then this behaviour seems be triggered.

**Comment by jason0x43** [comment]
Ah, that could be it since I don't have the top bar enabled.

**Comment by nmat** [comment]
I am not 100% sure if this is intentional or if this is a bug. Keep it open to get feedback from devevelopers. :)

**Comment by Thomas101** [comment]
The notch has been put in to hold the macOS window controls when they're shown in-window...
![screen shot 2018-07-23 at 15 35 58](https://user-images.githubusercontent.com/103586/43083474-876f0110-8e8e-11e8-81d7-991ddae19056.png)

When you enable `Show Titlebar` in settings, the notch disappears as it's not needed anymore...
![screen shot 2018-07-23 at 15 38 16](https://user-images.githubusercontent.com/103586/43083541-ad8f61d2-8e8e-11e8-8db3-cd300b50f0f7.png)


I don't think we're taking account of the fullscreen status, so if you go fullscreen (via the green button), the notch remains but the window controls get hidden by macOS. Are you using the app in fullscreen mode?

**Comment by jason0x43** [comment]
I am running in fullscreen, yes.

**Comment by Thomas101** [comment]
That will be it!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.9. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
