### ISSUE TITLE
[Bug] - Slack in slack - Does not follow workspace icons and information but shows correct in main window

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#734]
* Wavebox Version: 3.14.8beta
* Operating System & Version: windows 10
* Account type (if applicable): Slack in slack

**Expected & actual behavior**
Follow icon from workspace group and not from main slack service.

Some information is copied over like:
icon and hover information from main service

**Steps to reproduce**
Add a different slack team inside another slack team

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/43079502-93231920-8e8d-11e8-891b-f932424d053b.png)

**Additional information**
Not all information is shown in screenshot but you should be able to see the result.

**Comment by Thomas101** [comment]
The root cause of this is the same as https://github.com/wavebox/waveboxapp/issues/732

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.9. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
