### ISSUE TITLE
Excessive Memory Usage When Computer Sleeps

### ISSUE THREAD

**Issue by drock** [wavebox/waveboxapp#735]
* Wavebox Version: [e.g. 3.0.0]
3.14.6
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
MacOS 10.13.6
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
Gmail Inbox (2 accounts)

**Expected & actual behavior**
After leaving the computer alone and sleeping for long periods of time (usually over the weekend when I am not working), I often come back to find that the WaveBox process is consuming excessive amounts of memory.  Last time it happened it was 40+GB.  Once I wake my computer, WaveBox begins to release the memory and eventually goes back to normal.  This can take a while though and is draining on the rest of the machine.  Wavebox is unusable until it frees everything.

The longer I leave the computer sleeping, the worst it is.  Leaving it over night is usually not a problem, weekends and vacations usually are though.

Screensave/Sleep settings
* Screensave on after 1 minute
* Require password immediately after sleep or screen saver
* Turn Display off after 1 hr
* Put hard disks to sleep when possible
* Power Nap enabled
* Wake for Wi-Fi network access

**Steps to reproduce**
* Open Wavebox
* Use computer for normal work activities throughout day
* Leave Wavebox and other apps open
* Leave computer alone, let screensave and sleep happen on its own
* wait 48 - 72 hours
* Wake computer, observe memory usage in Activity Monitor.

**Is the bug persistent or intermittent?**
Persisten based on length of time sleeping

**Screenshots**
![screenshot 2018-07-23 09 26 16](https://user-images.githubusercontent.com/164126/43080222-3e2d986c-8e5d-11e8-9c53-716a2540146d.png)

**Additional information**

**Comment by Thomas101** [comment]
Hi, thanks for reporting. We have seen a similar behaviour under certain conditions on macOS. In the previous cases we found memory seemed to grow when an alert was presented but not dismissed. Once the alert was dismissed, memory would return to normal, in a similar way to what you've seen.

A couple of questions,
* When you returned to the computer were there any alerts open?
* Do you have any extensions installed?

If it is down to the alert issue, there's a fix currently in the beta channel if you want to try this out. There's some info on how to [try the beta channel here](http://wavebox.io/kb/beta-channel)

**Comment by drock** [comment]
I do not have any extensions installed.

Regarding the alerts, I did not pay attention if there were any wavebox alerts open.  I did however have several MacOS notifications.  Not sure if you meant notifications specific to wavebox or any notification in MacOS.  I will check on that next time it happens and report back.

Thanks

**Comment by drock** [comment]
I do not have any services enabled in Wavebox.  I do use other Google services like Drive and Calendar but I don't use them in WaveBox.

I doesn't appear that the memory usage always grows.  I woke my machine this morning and promptly checked and the memory usage was not increased.  I will keep monitoring things more closely to try to help identify a pattern or trigger to the problem.

**Comment by Thomas101** [comment]
Thanks, would be good to know if you notice any pattern to it - would be really helpful in diagnosing!

**Comment by drock** [comment]
Monday morning after leaving my computer alone all weekend.  Problem re-appeared.  Something I noticed, but have no idea if its related or not is that upon waking, my laptop was requiring me to enter my password to enable touch id or unlocking with my apple watch.  I'll watch to see if this is a pattern or not.

**Comment by Thomas101** [comment]
How do you normally unlock your machine?

**Comment by drock** [comment]
With my Apple Watch

**Comment by Thomas101** [comment]
Thanks, I've got a test rig here set up in the same configuration as yours. I left it for 4 hours and nothing untoward, but I'll keep it running for a couple of days to see if it makes any difference

**Comment by drock** [comment]
Finally happened again this morning.  Oddly, this time my laptop had been closed up and disconnected from power all weekend.

![screenshot 2018-08-13 08 25 07](https://user-images.githubusercontent.com/164126/44031703-cecc9f6e-9ed2-11e8-855b-382ca5673197.png)

**Comment by Thomas101** [comment]
Thanks. Did you take laptop out of network connectivity too, or anything like that, or was it just that it wasn't connected to the power?

**Comment by Thomas101** [comment]
@drock we've just released [Wavebox 4.0.0](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) which includes some fixes for runaway memory on macOS. It would be good to know if you're still seeing this or not. Thanks

**Comment by drock** [comment]
I hadn't noticed it for a while but ironically I just noticed it again this morning right before you sent this accouncement.  I just upgraded and I'll watch to see if it happens again.  Thanks for the update!

**Comment by Thomas101** [comment]
@drock 4.5.0 has just been shipped with a newer version of Chromium. I was wondering if you're still seeing this issue and if I'm okay to close this off? Thanks

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
