### ISSUE TITLE
Feature request - support for files with the .chm extension

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#737]
* Wavebox Version: [e.g. 3.0.0]
3.14.8Beta
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows 10
**Is your feature request related to a problem? Please describe.**
Some information about what the problem is.
Consolidation of other types of windows

**Is your feature request related to an account type?**
For example, a Gmail account or Trello account.
This is for support of files having a .chm extension.

**Describe the solution you'd like**
Information about what you want to happen or like to see.
I would like to have WB be able to support (read only) files that have a .chm extension

**Additional info**
Any other information or screenshots that might help us.
The .chm extension was developed by Microsoft and contains compressed HTML and are used for Help files in various applications.  Help files built this way are opened in a separate local window and are managed as any other window (minimize, close, expand, ...).  

If WB were to be able to open these file it would allow the user to:
1. consolidate them in one place rather than have to manage several windows at the same time (for multiple Help files)
2. not have to be constantly have be opening and closing them to free up resources or remove clutter
3. have Help files open for frequently used application without concern for the above 2 issues.

The definition/use of the files with this extension could be found at:
 www/fileinfo.com/extension/chm

**Comment by nmat** [comment]
I don't understand the purpose of this feature on a application that is used for cloud based connections?

You want to use wavebox to open up helpfiles and read them in wavebox? IMO I think this is something completely different purpose then what wavebox is aimed for.

**Comment by CheechGe** [comment]
Yes, you are correct that it does go beyond that particular purpose of WB.  However, if part of the purpose of WB to consolidate multiple SaaS application in a single space so that they can be better managed and provide for easier use to the user is there a reason why that it could not be extended to provide that same functionality to some local applications and derive the same benefits?

WB supports Teamview and is that or isn't it a local application that happens to use the Inet to provide connectivity to others.  Is it truly an SaaS application or is it a local application, or a hybrid?  Maybe heading in this direction would dilute its purpose, but it might be nice if I could do the same thing with some local applications instead of having windows for each taking up resources or needing the user  to start and stop them to keep his local environment somewhat manageable.

But I do understand you objection.

**Comment by nmat** [comment]
Well wavebox is more for connections regarding cloud based services like slack, gsuite etc and not for local based applications. If you have a cloud based service that handles .chm presentation then it would make more sense.

**Comment by CheechGe** [comment]
Understood.  In my case the .chm files are local.  Can't blame me for
trying to clean up a local environment though.

Just curious, is the Teamviewer in the WB app list *(I haven't tried it
yet)  not considered a local/desktop app?  Using the "duck" analogy, it
looks like one, installs/uninstalls like one, and runs like one?

Or, is it not the full version that one adds into WB?  Aside from providing
connectivity is it truly a cloud based service?  I ask because I have other
apps that are installed locally but connect to other services.  Are these
candidates for WB?

I'll let this go here as it is clear that the intent is different but, what
is cloud based seems to get a bit fuzzy if the app is installed locally.

**Comment by nmat** [comment]
Teamviewer in wavebox uses the login page on: https://login.teamviewer.com/LogOn

So just as you would login there you would use the same in wavebox. Wavebox creates a better overview and connection with cloud based services so that you for example can use the browser to do other things. Then have the cloud based services inside wavebox instead.

Wavebox does also give you opportunity to detach windows so that you can concentrate on one service at the time also.

Wavebox also is based on the ui electron which you can read about here: https://electronjs.org/ which is a framework to create desktop apps. Its also based on flux and reactjs.

Lets for the sake of say you use: slack, messenger, gmail, whatsapp. Instead of either using the browser to connect to their online service OR use 1 app for each service. Wavebox can do this connection for you inside one application. As long as the service has a cloud connection.

**Comment by CheechGe** [comment]
OK, so it is not the desktop version of Teamviewer.  I think I tried the
service based one a long time ago but didn't like it or had problems with
it at the time.  I've been using the desktop version since then and will
stay with it.

I already use it for gmail, and some other web sites and the way it works
for those is just fine.  The only other cloud application I use is
Office365 and it's installed WB already

Thanks for the other info, .

**Comment by Thomas101** [comment]
Just to add a little bit more info here on the chm files and opening files in general. At the moment the only way to open files is through a 3rd-party service such as Google drive, we don't have any specific plans to support file reading/file opening at the moment.

I had a look around the web to see if there are any online services that host and display chm files, but couldn't find anything. That would have been the most feasible option for adding it to Wavebox as we can just add the site the webstore.

I had a quick look into libraries that can be used to render chm files, certainly, in our tech stack there isn't any open-source libraries at the moment (a couple to generate, but none to render). They are just compiled html files under the hood, but they're not a standardized format that browsers support.

**Comment by CheechGe** [comment]
I mostly knew that when I submitted this request that it would be outside the norm of the intent of the WB software as these were local apps/files and had nothing to do with cloud based/SaaS applications.  

So consider this as just "testing the water" on how far WB could be stretched.

I'm fine with the decisions and responses which is why I closed it.

TU, all.
