### ISSUE TITLE
Whatsapp QR Code does not apper

### ISSUE THREAD

**Issue by ralfi** [wavebox/waveboxapp#738]
* Wavebox Version: [3.14.8beta]
* Operating System & Version: [Debian]
* (Linux only) Install method: [Debian installer Wavebox Repo ]
* Account type (if applicable): [Whatsapp]

Added WA Web should be appear the QR code to authorize against phone app. But never and nothing appears. Android Messages (same way) works. Persistent bug after last update

**Screenshots**
Screenshots often help us narrow down a bug more easily.
![grafik](https://user-images.githubusercontent.com/294423/43199695-259f39d8-9013-11e8-9aad-f2d4026e9188.png)

**Comment by ralfi** [comment]
Sometimes the QR code appears for a very short time, 0.5 secs around and than disappears. Mmmh.

**Comment by ralfi** [comment]
Sorry, wrong *klick*, just open

**Comment by ralfi** [comment]
[vokoscreen-2018-07-25_14-15-34.gz](https://github.com/wavebox/waveboxapp/files/2227861/vokoscreen-2018-07-25_14-15-34.gz)

**Comment by Thomas101** [comment]
Have you tried removing the account and adding it again? If this doesn't work are you using a firewall? It could be that it's blocking the websocket that whatsapp uses to pull the qrcode

**Comment by ralfi** [comment]
Hi Thomas,

sorry to forget to tell you that remove / add do not work.

It works on the same machine (https://web.whatsapp.com) with google
Chrome Version
69.0.3493.3 (Offizieller Build) dev (64-Bit) and Version 68.0.3440.75
(Offizieller Build) (64-Bit).
Do you have a look at my vokoscreen video? Curios... But it works a long
time before, i think more than 2-3 months on the same machine.

Thx.


Am Mi., 25. Juli 2018 um 15:31 Uhr schrieb Thomas Beverley <
notifications@github.com>:

**Comment by Thomas101** [comment]
Sorry, I missed the video! It's weird that it works when you reload the page.

If you try the following steps what do you see...
1. Add the tab so it fails
2. Right click on the tab in the left and pick `Sleep`
3. Right click on the tab in the left and pick `Awaken`
4. Does the QR load correctly?

Can you also give the following a try...
1. Add the tab so it fails
2. Right click anywhere in the window and pick `Inspect Element`
3. In the window that appears click the `Console` tab
4. Are there any errors or warnings there?

**Comment by ralfi** [comment]
Hi Thomas,

inspection -> console tells me this:

[image: image.png]

Hope that help.
Regards, Ralf


Am Mi., 25. Juli 2018 um 16:54 Uhr schrieb Thomas Beverley <
notifications@github.com>:

**Comment by ralfi** [comment]
Mmmh, why does the uploades image above not appears... second try

![image](https://user-images.githubusercontent.com/294423/43254317-6a64196c-90c7-11e8-97b5-30599d7a2602.png)

**Comment by ralfi** [comment]
after a complete new installation and removing all previous settings i receive this...

![image](https://user-images.githubusercontent.com/294423/43254545-e8d61160-90c7-11e8-8b86-17bebfe5568a.png)

**Comment by Thomas101** [comment]
The `[violation]` warnings could be something to do with it, the App cache Error I don't think. It's hard to say.

I'm struggling to reproduce the same behaviour here - it seems work 100% reliably for me. If I can get it to fail for me then it makes a lot easier to diagnose. Can I have a little bit more info about your machine and Wavebox setup? Perhaps there's a clue there...
* 32bit of 64bit debian?
* How much RAM do you have?
* Are you connecting with any kind of VPN or proxy?
* How many awake tabs do you have in Wavebox. The ones that are sleeping shouldn't cause any problems they don't use any resources
* Do you have any extensions added to Wavebox?

**Comment by ralfi** [comment]
Hi Thomas, really curios solution.
I can reproduce this error by installing nvidia-driver set. If i use the xorg nouveau driver remove / add whatsapp works well. If i use nvidia driver (from debian repos) i have this symptom. 

On the way to this solution brings me a fresh installation on my alternative notebook with intel graphic chipset. On my main machine comes to this symptom because i never remove the whatsapp app a long time...

**Comment by Thomas101** [comment]
Oh wow, I was not expecting that to have any effect! If you go back to the nvidia drivers there's two setting in Wavebox that could be worth trying...

1. Settings > Advanced > Ignore GPU Blacklist (disable)
2. Settings > Advanced > Hardware acceleration (disable) - although you may see some performance degradation with this.

**Comment by ralfi** [comment]
Yeah, top solution, but onlay work when disable both... 
Thanks again, Thomas!

**Comment by ggalmazor** [comment]
Hi! I'm experiencing this issue on Ubuntu 18.04 64 bits. I'm also using the nvidia drivers.

In my case a QR briefly flashes and then it becomes blank. Here's a GIF showing that while I reload the tab:

![peek 15-08-2018 12-38](https://user-images.githubusercontent.com/205913/44144510-18fded3e-a088-11e8-8888-30ca0076818a.gif)

Inspecting the network I can see that the QR refreshes every ~10 seconds and that the `data:image/png` content is, indeed, a transparent 264 by 264 image, which is kind of weird. I've copied the base64 png content and I've loaded it with [this web app](http://freeonlinetools24.com/base64-image) using Chrome and I get the same image.

Although it works after changing the settings to ignore the GPU backlist and to disable hardware acceleration, I'm really intrigued why any of these settings should affect to the QR generation, which I've verified that it's done in both scenarios.

**Comment by Thomas101** [comment]
@ggalmazor it's not so much the QR generation, it's more down to the display of the image. It looks like the issue is something to do with chromium/display drivers/os but not 100% sure what as yet.

Which version of Wavebox are you using? Are you on the beta channel or stable channel?

**Comment by ggalmazor** [comment]
I'm on Wavebox 3.14.6, stable channel.

> it's not so much the QR generation, it's more down to the display of the image.

The thing that most confuses me is that there's an image being displayed and that the image is indeed a 264 by 264 transparent image both in the wavebox's web frame and Chrome.

**Comment by ggalmazor** [comment]
Ugh, that's a very old version... It seems like Ubuntu is offering the last snaps version from June. I'll upgrade and get back to you on this.

**Comment by Thomas101** [comment]
Is it entirely transparent? What length is the base64 string? I wonder if this is a different issue. Did you also use the debian installer or something else?

**Comment by ggalmazor** [comment]
I'll have that information in some hours (off for lunch now). I've used the instructions for the ppa.

**Comment by ggalmazor** [comment]
I'm back :)

The image is completely transparent. This is the base64 string:

```base64
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQgAAAEICAYAAACj9mr/AAAIB0lEQVR4Xu3WsQ3AMAwEsXj/pTOBiquf6VWIMg55n48AAQKHwCNDgACBS0AgvA0CBE4BgfA4CBAQCG+AAIEu4A+im5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRkBgZg5tUUJdAGB6GYmCMwICMTMqS1KoAsIRDczQWBGQCBmTm1RAl1AILqZCQIzAgIxc2qLEugCAtHNTBCYERCImVNblEAXEIhuZoLAjIBAzJzaogS6gEB0MxMEZgQEYubUFiXQBQSim5kgMCMgEDOntiiBLiAQ3cwEgRmBH5B0AQkKU6vBAAAAAElFTkSuQmCC```

**Comment by Thomas101** [comment]
It does look that way, although pretty big for a transparent image! How did you install Wavebox (e.g. deb installer, snap package etc...)

**Comment by marcusviniciuscosta** [comment]
This work for me:

Settings > Advanced > Ignore GPU Blacklist (disable)
Settings > Advanced > Hardware acceleration (disable) - although you may see some performance degradation with this.

After login i change again.

**Comment by ggalmazor** [comment]
> It does look that way, although pretty big for a transparent image! How did you install Wavebox (e.g. deb installer, snap package etc...)

I used the package manager (apt) instructions.
