### ISSUE TITLE
No sound with a notification

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#739]
* Wavebox Version: [e.g. 3.0.0]
3.14.8beta

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows10
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
No sound on any Notifications including the notification test
**Expected & actual behavior**
Some information about what you expect to happen and what actually happens.
Sound when a notification arrives

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?
whatever produces a notification

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?
Persistent
**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**
Speakers are external and work with webinars, pandora, ...   I added Pandora to WB and music play just fine.  The notification setup was correct,  Used the test feature and the message display but no sound was produced.

I've never heard any notification sound since the install (about 1 month ago) so it is not related to any recent beta changes.

**Comment by nmat** [comment]
When you run the test notification inside wavebox: Settings -> Notifications -> Test notification

Does that provide a sound for the notification. If it does, then check that the service you are using has been allowed to send notification through also. For example in facebook messenger you have to manually tell it to allow the notifications to be sent through.

**Comment by Thomas101** [comment]
Do you hear sounds for any other notifications that come up in the notification center? It's worth checking a couple of things - notification sounds can be disabled in a few ways...

1. In the Wavebox app under settings > notifications, check that `Play notification sounds` is enabled
![wavebox_2018-07-26_08-20-58](https://user-images.githubusercontent.com/103586/43248383-9700111e-90af-11e8-94a5-03d28969636b.png)

2. Under the windows settings, by opening the notifications panel (bottom right of screen), then `All Settings`. Search for `Notifications & action settings`. Scroll down to locate Wavebox and check that it's listed as `On: Banners, Sounds`
![applicationframehost_2018-07-26_08-21-46](https://user-images.githubusercontent.com/103586/43248490-ef7877f0-90af-11e8-8c5b-5480d8e4fff1.png)

3. Finally still in windows settings app search for `Audio`. Then click `Change the device or app volume`. Right at the bottom click `App volume and device preferences`. Ensure that system sounds is configured at 100% and to use the default output

**Comment by CheechGe** [comment]
Strange, I reopen this issue on the previous comment and it didn't reopen.

**Comment by nmat** [comment]
is this a specific service where sound is not sent through?

**Comment by nmat** [comment]
for example it might be important to check notification settings on the specific services:

like messenger (settings -> sound on)
whatsapp (settings -> notifications -> sound on)

is the service notification sound turned on?

**Comment by CheechGe** [comment]
Gmail notifications and at least one called Privacy Guardian which is part of the System Mechanic Pro Toolset.  I don't think I get a sound when there is a Vivaldi browers update notification either, but I'm not positive on that.  I'll pay closer attention to which notifications play sounds and which do not.

The main one I was most concerned about was the ones from GMail especially since if support is addedto WB to customize mail notification (as per an enhancement request I made) that that would probably not work until this issue is resolved


![wb_08](https://user-images.githubusercontent.com/3653639/43289692-bf819a8c-90f9-11e8-9294-af07a57095ec.png)

**Comment by nmat** [comment]
Is the below set:

![image](https://user-images.githubusercontent.com/383031/43289910-b4794d78-912c-11e8-9f0f-a06c5cec9329.png)

The notifications for gmail does go to desktop just that sound is not played?

**Comment by CheechGe** [comment]
I do not get sounds when an email from GMail arrives. and I do see a visual notification.  The same is true for the WB Test Nofication, visual but no sound.

Where does one find the setting you are referring to and I'll check.  I looked at all the places where there were notification settings that I was directed to check.

**Comment by Thomas101** [comment]
I wonder if it's because there's no default sound set in Windows. Try the following...

Navigate to `Control Panel` on your PC and search for `Sound`. In the Sound dialog, scroll down to `Notification`. Check there's a sound selected and try pressing `Test` to see if one plays

![notification-sound](https://user-images.githubusercontent.com/103586/43386543-d5cd2c2c-93db-11e8-88a3-eededfe8f45a.jpg)

**Comment by CheechGe** [comment]
You are correct, there wasn't a default sound set.  Once I set one and did
the test it played the sound.  I then tried the notification test in
wavebox and that worked too.

Next I sent an email to my primary email address which is setup in wavebox
from an alternate one on my other PC and hooray it worked.

Thank you for you persistence in finding out what the problem was. I never
had reason to paid any attention to the sound setting in the control panel
because other than the notifications not working which I didn't notice
until wavebox was installed, sound was fine so I doubt very much I  messed
with it.   Anyway, problem solved, that's one I'll remember.

Thank you again

Frank

**Comment by paco3346** [comment]
Sorry for the reopen but I'm having the same issue on Linux. Since the platform is quite a bit different where/how does WB choose what notification sound to play? Does it rely on the Desktop Environment somehow or does it ship with it's own set of notification sounds?

**Comment by Thomas101** [comment]
@paco3346 under Settings > Notifications, there's a `Notification Provider` setting. Depending on what this is set to, dictates how it decides which sound is played on Linux
1. `Default` - Wavebox uses `libnotify` under the hood and the desktop environment will dictate which sound is played
2. `Enhanced` - Wavebox uses a set of custom sounds. There will be a dropdown with a selection of sounds under the Notification section

Hope this helps :)

**Comment by paco3346** [comment]
Unfortunately neither of these work for me. I've tested audio from Wavebox and can play youtube videos just fine. I'm interested in using the Enhanced notification provider as it helps differentiate between other system notifications. I would think this would just be WB itself rendering the audio, right?

Are there any debug flags for launching WB with more output?
