### ISSUE TITLE
Folders in Menu Sidebar

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#740]
* Wavebox Version: [e.g. 3.0.0]
3.14.8beta

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows10

**Is your feature request related to a problem? Please describe.**
Some information about what the problem is.
Not a problem yet.  Hoeever, I am rapidly running out of space on the sidebar menu and although there is probably someway that this will be handled I can perceive some work-ability issues will arise.

**Is your feature request related to an account type?**
For example, a Gmail account or Trello account.
No

**Describe the solution you'd like**
Information about what you want to happen or like to see.
I would like the see the capability to put folders into the side bar where the actual application/websites could be added.  These folders shall have several features as follows:

1. the user shall be able to name and or rename the folders as desired.
2. the folders shall have user selected colors
3. the folders shall coexist with regular application icons on the sidebar
4. the folders shall be capable of being re-ordered on the sidebar
5. the folder entries shall be able to be  moved/copied to other folders or directly to the sidebar
6. entries in the side bar shall be able to moved/copied to folders
7. the folder entries shall be edited (ie. to correct typos on website entries, ...)  .  this should be a feature on the regular sidebar too.
8. folders shall be able to have subfolders
9. navigation between folders or back to the sidebar shall be available
10. a standard Folder Icon shall be used

**Additional info**
Any other information or screenshots that might help us.
for an example of this review the Speed dial add-ons (available in Vivaldi, and other browsers) 
SSs can be provided if desired.

**Comment by nmat** [comment]
In the coming release of wavebox there is a possibility to add a service inside a service. You can read more about it here: https://github.com/wavebox/waveboxapp/releases/tag/v3.14.8

Is this the kind of option you are looking for?

**Comment by Thomas101** [comment]
The beta channel does have quite a few new tools for arranging accounts and helping to handle lots of accounts. There's a blog post in the works for this, but just as an overview...

As @nmat said you can add services within other services via the right-click menu. Once added, if you head into the account settings each service and also the top-level account have the option of changing icons, names and colors.
![screen shot 2018-07-26 at 09 49 25](https://user-images.githubusercontent.com/103586/43251923-351a4492-90b9-11e8-991c-e178e022b0db.png)

For organizing services within an account there's options to move individual services to the sidebar or toolbar, also via the right-click menu. Here I've got Calendar in the sidebar and all the others along the toolbar.
![screen shot 2018-07-26 at 09 50 44](https://user-images.githubusercontent.com/103586/43252023-7729f85a-90b9-11e8-8163-0653eacdd64f.png)

If you have one account with lots of items in the sidebar, there's the option to collapse the sidebar services when it's not in use - also under account settings. This means there will just the single top level account entry in the sidebar...
![screen shot 2018-07-26 at 09 52 35](https://user-images.githubusercontent.com/103586/43252151-bda67362-90b9-11e8-8bea-9cd94225a273.png)

And finally if you've got lots in the sidebar you can change the size of it in the general settings under the UI section. Compact or tiny, will give you a more condensed look and help to keep things organized
![screen shot 2018-07-26 at 09 55 10](https://user-images.githubusercontent.com/103586/43252308-11f3dbd0-90ba-11e8-817b-eb516923202a.png)

An example of tiny mode
![screen shot 2018-07-26 at 09 55 20](https://user-images.githubusercontent.com/103586/43252332-1d01ae3a-90ba-11e8-9f48-aa6c33fa9c91.png)


Do these help?

**Comment by CheechGe** [comment]
Hi Thomas

I think I will need to digest that a bit more but from first glance I think it will accomplish what I was requesting.  I have to get used to the different terminology here because it wasn't clear (to me) what the differences were between a service and an account.  

To see if I understand this correctly I can have an account for say MIcrosoft and then have Word, Excel, PP, etc listed under the MS account?  Using the same process but with websites can I create an account for News and then put individual News sites as a service under the News Account?  Essentially that is how I organize websites using the browser add-on. 

Will the blog post contain more step by step detail on how to use set this up the way you described as it is a bit confusing to a WB newbe?  I was anxious to use the software so I just installed everything as a new account. Even though I saw the various items on the context menu for services I had no idea what they were for or how to use them. Anyway, in any event, I will look into this  deeper.

![wb_04](https://user-images.githubusercontent.com/3653639/43264690-cabce388-90b4-11e8-8b3b-700d2d6ac911.png)

**Comment by CheechGe** [comment]
closed by mistake, reopened until I can see if playing around with the services satisfies the request.

**Comment by CheechGe** [comment]
I did some testing with adding services to an account and understand it a bit more.   This seems to work well for real cloud services however for websites it isn't quite the same as my request, at least from what I can determine so far, and if what is stated below please correct me.

1. if an account is created from a weblink an entry is made on the sidebar.   Other  weblinks can then be added to the the account.  Clicking on the sidebar entry will bring up the page associated to the account and whatever services were connected to the account will appear on the top menu bar in addition to the one associated to the account.  Clicking on one of the service associated icons will cause that site to appear.  One can switch back an forth by just clicking on the desired icon, which is nice.

Using the folder analogy, a folder would just be a container for web links and would not bring up any web page when clicked but would just populate the menu with the services connected to it.  In other words going back to WB the account would just be a container for weblinks and would not have any web site associated to it and would simply populate the menu with the services defined to it.

One thing I noticed which may be a bug, if the same account icon was clicked again it resulted in the same service icon being populated in the menu bar (note that I only had one additional service defined for the account).  But, clicking on these 2 service icons produced different results, sometimes.   This may have occurred because of the way I set up the services and will need to be tested some more.

Overall this may work although my preference would be to have the Account simply be a container for the weblink services and populate the menu with the connected services rather than connect to a defined web site.

My next observation may be a little more difficult to resolve.  I have not tested how this would work at this time so the comments below are based upon my understanding of the documentation on how to setup services

2.  According to the documentation services that are connected to an account must have the same logon credentials.  The sites I tested with did not require a logon so they worked fine.  However, sites that do require a logon, at least in my case, rarely if ever have the same logon credentials.  Furthermore, if WB does put in the support for Lastpass it seems that in order to group websites under an account that this restriction would need to be handled differently.

All-in-all I believe that this mechanism could satisfy my enhancement request if some modifications could be made to handle things differently (optional of course).  

I need to do more testing especially on the aforementioned "problem" with the inconsistencies when a menu icon is clicked.  The results will be posted in this thread rather than start another issue.

**Comment by CheechGe** [comment]
Not sure why the issue keeps getting closed as I am not doing it intentionally

**Comment by nmat** [comment]
Hmmmm are you trying to make wavebox being your browser so to speak? Instead of using for example chrome or other browsers?

**Comment by CheechGe** [comment]
Yes, in certain cases   I am putting *frequently used* sites in WB because
they get consolidated and managed in one place and are much easier to
use..I do not use WB when I am navigating or searching the web.

Isn't that part of what WB *also* does, or, is it only for websites that
have applications that are strictly cloud based?  Am I misunderstanding the
what adding a website to WB means?

**Comment by CheechGe** [comment]
OK, let me see if I can address your comments:

1. What I was suggesting here is that something like an account be added that was a container for other services, in my example it was a folder.  Using Wavebox's terminology that this pseudo-account  would be a container that would contain services.  Clicking on the pseudo-account would cause a context menu to be displayed with the services set up in it, similar to what is placed in the menu bar when a real account is setup with multiple services.  This might be one way of accomplishing the "folder" request.

2. I misunderstood that the accounts were of the same type.

3. Great.

4. Hopefully something will appear as these are a real problem with adding "just websites", especially new sites

5.I have not been able to recreate this problem.  What had happened was the menu bar had 2 of the exact same icons.  It is possible that I added a service twice while attempting to understand what services were as part of an account.  Assuming this was the case one might ask why Wavebox should or if rt should allow the same site (where the URLs are exactly the same) to be added multiple times.

**Comment by nmat** [comment]
@CheechGe Can you please update to latest beta to see if it would cover what you are asking for above? IMO the sandboxing really should cover the part of "folders" as you mention.

Regarding the custom websites, IMO I think that a request to have the extension support for ad blocker in that case would be suggested. So it could go into the ticket for suggested extensions that wavebox might be able to support. 

(unfortunately, I am not sure how adblocker would be able to be implemented or if there is questions regarding the process of having the support for it in applications like wavebox and I guess this is the reason why there needs to be investigation on the support factor for a extension like that.)

Extension github issue number: https://github.com/wavebox/waveboxapp/issues/138

**Comment by CheechGe** [comment]
I had already installed the latest beta release, will test this again and report back.  

Concerning the ad-blocker, I had already put in a request for an ad-blocker support and Thomas did respond.   Apparently there are some issues with being able to do so.  There are a bunch of them around so even making a selection of which one to support might be a bit of a challenge.

**Comment by Thomas101** [comment]
@CheechGe do the new layout options give you enough tooling to arrange accounts? Thanks

**Comment by CheechGe** [comment]
Hello:

I will do do some more testing with web sites that I logon to using LP and
see how that works with the latest update.  It was a bit cumbersome the
last time I tried it so I remove the other accounts  Thanks

**Comment by nmat** [comment]
hello,

Was wondering about news about this? Can it be closed?

**Comment by CheechGe** [comment]
Hello:

Yes, it can be closed.
