### ISSUE TITLE
[Bug] wavebox mini -> wavebox - unread select to go to message for slack in slack gives error

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#742]
* Wavebox Version: GIT master 2018-07-27, 3.14.9beta
* Operating System & Version: windows 10, macOS 10.13.6
* Account type (if applicable): slack in slack

**Expected & actual behavior**
Go to account and open new message without errors.

Goes to the account but pops up a error about not being signed in to workspace.

**Steps to reproduce**
1. Get a new unread message in wavebox mini
2. Click on the slack account -> unread message to go to that specific message

*boom* error message.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/43308927-7b41dea6-9183-11e8-9995-a851f3fd8d7e.png)

**Additional information**
Only tested for slack with slack. It actually goes to the right place but this error pops up on every message. Only triggered from wavebox mini select of unread message (not from notifications)

**Comment by Thomas101** [comment]
Thanks - should be fixed in master :)

**Comment by nmat** [comment]
Verified on windows 10 as working. Thank you!

**Comment by Thomas101** [comment]
This has just gone out in the beta :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
