### ISSUE TITLE
[Bug] - Wavebox mini - Dock to tray, Open as window - tooltip sometimes is stuck and does not go away

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#743]
* Wavebox Version: 3.14.9beta, GIT master 2017-07-27
* Operating System & Version: Windows 10, macOS 10.13.6

**Expected & actual behavior**
Tooltip is sometimes stuck if you click on Open as window or Dock to tray. Also seems like the icons are being "selected" on first open.

**Steps to reproduce**
Just try to click on the various items. You will see after a while that the tooltip on next open of wavebox mini will keep the tooltip open.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/43310951-588b5dfa-9189-11e8-9873-0f46b3fc5e46.png)

![image](https://user-images.githubusercontent.com/383031/43311013-8374b7b4-9189-11e8-9792-66e038f1fb7c.png)

**Comment by Thomas101** [comment]
Yeah I see the same - I'll see if there's a way to dismiss on click

**Comment by Thomas101** [comment]
Just gone out in the beta :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
