### ISSUE TITLE
[Feature Request] - wavebox mini - More drill down services in unread

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#744]
* Wavebox Version: 3.14.9
* Operating System & Version: All (wavebox mini)

**Is your feature request related to a problem? Please describe.**
You have at the moment a summary of unread messages for the services. Since there is introduction to have more services in one service so to speak. It would be nice to be able to have a drill down.

At the moment it looks like this: Service (overview) -> Service overview + unread messages summary

It would be nice if you can add another layer to it where you can go even further down: Service (overview) -> Services overview + unread messages summary -> Specific service -> That service unread messages

This would be nice to have if the keyboard shortcuts from: https://github.com/wavebox/waveboxapp/issues/701 and therefore can navigate a whole lot more with just the keyboard and not use the mouse to much.

**Comment by Thomas101** [comment]
I've been thinking about splitting the list by subheading... (excuse my very poor mockup)
![screen shot 2018-07-30 at 10 07 42](https://user-images.githubusercontent.com/103586/43388220-7b60cd98-93e0-11e8-80be-ed4d9505a7a0.png)

I probably wouldn't be able to put keyboard shortcuts into that at the moment but would at least make it clearer....

**Comment by nmat** [comment]
That looks good. I do like having the summary of everything also first though and then drill down to service specific unread. Mostly because sometimes you might just want the summary and start working your way from the top to bottom.

Looks good. :)

**Comment by Thomas101** [comment]
The top-level summaries would still stay there. Would just be a case of splitting the existing items up by the service so it's a bit clearer who generated what...

**Comment by Thomas101** [comment]
So far so good....

![screen shot 2018-07-30 at 11 35 25](https://user-images.githubusercontent.com/103586/43392801-ae591604-93ec-11e8-9b5f-aa8c69c304aa.png)
![screen shot 2018-07-30 at 11 35 28](https://user-images.githubusercontent.com/103586/43392802-ae7059cc-93ec-11e8-8c6c-b0ca280bcd79.png)

**Comment by nmat** [comment]
Tested quickly on windows 10 and works. A lot easier to see what is unread now. :)

**Comment by Thomas101** [comment]
It's just gone out in the beta :). Thanks @nmat

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
