### ISSUE TITLE
Pen and Touch Support

### ISSUE THREAD

**Issue by aditiapratama** [wavebox/waveboxapp#745]
* Wavebox Version: 3.14.10beta
* Operating System & Version: Windows 10

**Expected & actual behavior**
While using pen mouse, in chrome browser I can easily scrolling using **click + drag**, but in wavebox if I try to do the same, what it does is selection instead scrolling.

**Steps to reproduce**
Just try to use pen tablet to do scrolling with click and drag in wavebox interface

**Is the bug persistent or intermittent?**
It always happen

**Comment by Thomas101** [comment]
Thanks for reporting. I'll see if I can find out why this isn't supported by default/what needs to be done to add support

**Comment by aditiapratama** [comment]
hi @Thomas101 I think this issue is related with this https://github.com/electron/electron/issues/7815

**Comment by Thomas101** [comment]
Hi, it looks like the upstream issue was fixed sometime after electron 1.8.x. Wavebox is using version 4.0.x now so this should also be fixed. If you're still seeing the problem with the latest version of Wavebox let me know and I'll take another look. Thanks!
