### ISSUE TITLE
Can't access settings.

### ISSUE THREAD

**Issue by Dark-Witcher** [wavebox/waveboxapp#75]
* Wavebox 3.1.14

*Windows 10
 
I was playing around with the app settings when I made it like this by accident and I can't get it back the way it was now.
How do I fix it?
![screenshot 42](https://cloud.githubusercontent.com/assets/22236684/25041286/f1a0e036-2106-11e7-9b78-f788f8abbaf9.png)

**Comment by Thomas101** [comment]
If you try restarting Wavebox does it re-appear again?

**Comment by Thomas101** [comment]
I'm going to close this issue off, but if you're still seeing this issue just re comment and I'll take another look. Thanks
