### ISSUE TITLE
MathJax Slack Integration

### ISSUE THREAD

**Issue by tobyfrancis** [wavebox/waveboxapp#752]
In my day-to-day usage of Slack, one of the features I've come to really enjoy is the usage of LaTeX-rendering of mathematics, using [https://github.com/fsavje/math-with-slack](https://github.com/fsavje/math-with-slack). Moving to Wavebox, I'm reluctant to get rid of my Slack app since I can't seem to get the injection working correctly. Adding support for this (small but significant) feature without having to go through additional work would attract many users!

**Comment by Thomas101** [comment]
With a little bit of adaptation, it's easy enough to bring that script across to Wavebox. Install is a little different though...

Right click on the account and go to settings. Under the Userscripts section (or advanced if you're on the beta channel) click on the `Custom JS` button. Paste the following and press done...

```js
// math-with-slack originally ported from https://github.com/fsavje/math-with-slack
var mathjax_config = document.createElement('script');
mathjax_config.type = 'text/x-mathjax-config';
mathjax_config.text = `
  MathJax.Hub.Config({
    messageStyle: 'none',
    extensions: ['tex2jax.js'],
    jax: ['input/TeX', 'output/HTML-CSS'],
    tex2jax: {
      displayMath: [['\$\$', '\$\$']],
      element: 'msgs_div',
      ignoreClass: 'ql-editor',
      inlineMath: [['\$', '\$']],
      processEscapes: true,
      skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
    },
    TeX: {
      extensions: ['AMSmath.js', 'AMSsymbols.js', 'noErrors.js', 'noUndefined.js']
    }
  });
`;
var mathjax_observer = document.createElement('script');
mathjax_observer.type = 'text/x-mathjax-config';
mathjax_observer.text = `
  var target = document.querySelector('#messages_container');
  var options = { attributes: false, childList: true, characterData: true, subtree: true };
  var observer = new MutationObserver(function (r, o) { MathJax.Hub.Queue(['Typeset', MathJax.Hub]); });
  observer.observe(target, options);
`;
var mathjax_script = document.createElement('script');
mathjax_script.type = 'text/javascript';
mathjax_script.src = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js';
document.head.appendChild(mathjax_config);
document.head.appendChild(mathjax_observer);
document.head.appendChild(mathjax_script);
```

I've also added it into our [user-scripts repo](https://github.com/wavebox/wavebox-user-scripts/tree/master/Thomas101/math-with-slack)

**Comment by tobyfrancis** [comment]
Wow, thank you for the quick response - I've got it up and running and it looks great!
