### ISSUE TITLE
wavebox crashing on Arch Linux - SEGV

### ISSUE THREAD

**Issue by jghodd** [wavebox/waveboxapp#754]
* Wavebox Version: 3.14.*
* Operating System & Version: Arch Linux
* (Linux only) Install method: AUR
* Account type (if applicable): Gmail

**Expected & actual behavior**
Version 3.14.7 was working until recently. Then it and version 3.14.7 are now showing the same problem. This is the output from strace:

stat("/etc/gnutls/default-priorities", 0x7fff32135040) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0xa48a30} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

**Steps to reproduce**
Just run it on the command line.

**Is the bug persistent or intermittent?**
Persistent

**Comment by jghodd** [comment]
[wavebox.strace.log](https://github.com/wavebox/waveboxapp/files/2279655/wavebox.strace.log)

Attached is the entire strace log.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. It looks like a bug with glibc-2.28-1 which is breaking all electron based apps (slack, vscode, etc...). (More info https://github.com/electron/electron/issues/13972).

The arch maintainers have patched it (https://github.com/felixonmars/archlinux-packages/commit/caa929b5a62f8e0b54d60b9f642f97519dc71a53) but as far as I can see it's not been released yet. There's some discussion around [hacky workarounds on reddit](https://www.reddit.com/r/archlinux/comments/957v3k/segfaults_at_startup_on_a_bunch_of_apps_after/) for mailspring and slack which involves re-linking the old glibc.

I'll have a look to see if there's anything we can do in the short term until the patch for glibc goes out

**Comment by jghodd** [comment]
Thanks, Thomas. No, arch is still on glibc-2.28-1, but v2.28-4 is currently in testing. The patch is included in the 2.28-4 build bundle, so the next release of glibc should fix it. I did discover that wavebox-3.14.6 is still working, so I'll stick with that version until glibc-2.28-4 is released.

Cheers

**Comment by jghodd** [comment]
I can confirm that glibc-2.28-4 does in fact resolve this issue. I went ahead and installed it from the arch testing repository and upgraded wavebox to 3.14.10 and everything came up as expected.

**Comment by Thomas101** [comment]
glibc-2.28-4 should be in the main repository now :)
