### ISSUE TITLE
Wavebox will not start after a DNS reconfiguration

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#755]
* Wavebox Version: [e.g. 3.0.0]
3..14.1Beta

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
Windows10
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
N/A

**Expected & actual behavior**
Wavebox does not start (spinning lWB icon only in splash screen)
Some information about what you expect to happen and what actually happens.

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?
See the description below

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?
Can be recreated

**Screenshots**
Screenshots often help us narrow down a bug more easily.
Only the WB spinning Icon appeared

**Additional information**
Occasionally my internet speed (Cox Cable BB) slows down and requires a modem reset   After doing that the PC will not connect to the internet.  This is because it is configured to use the Cloudflare (1.1.1.1) DNS services.  By changing it back to acquire a DNS automatically and then reconfiguring to use the Cloudflare DNS the PC will reconnect to the internet without an intervening reboot

However even though the internet is operational Wavebox will not start up. To get Wavebox up and running again requires that the PC be rebooted, still using the Cloudflare DNA setting and with no other setting changes.  

Seems like there are 2 problems the first being Cloudflare's in that it will not allow a reconnect to the internet after a modem reset..  The second seems to be something in Wavebox that will not allow it to start after a DNS reconfiguration unless there is an intervening reboot.  Given that there is a workaround and Wavebox is operational then I consider this issue an FYI maybe to be addressed at some point. 

One possible point.  It seems that Wavebox or the Wavebox accounts are somehow dependent or at least aware of the type of DNS service being used and that changing them may cause a problem especially if new accounts are added (and are aware of DNS services/swettings  possibly creating a mixed account environment) using a different DNS service.

**Comment by Thomas101** [comment]
Thanks looks like a bug there!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.14. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by CheechGe** [comment]
I'm on the beta channel and did the recent update already.  It's a bit disruptive to recreate the problem so I'll test this as soon as I can.

**Comment by CheechGe** [comment]
Just tested this using the latest beta and the same problem exists.  

Testing process.
1. reset modem (unplugged) 
2. Rebooted PC, could not connect to internet using 1,1.1.1 DNS service
3. Reconfigured adapter to acquire DNS services automatically, was able to connect to internet
4. Reconfigured adapter back to using the 1.1.1.1 DNS service, was able to connect to internet
5. Started Wavebox, but it would not start (spinning logon on splash page)
6. Rebooted PC (did not reconfigure adapter). 
7. Started Wavebox.  This time it started right up.

Summary: the original problem that in order to get Wavebox up and running after re configuring the DNS Service does require a reboot.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
