### ISSUE TITLE
Unable to find complementary code in the source

### ISSUE THREAD

**Issue by john89sab** [wavebox/waveboxapp#756]
* Wavebox Version: [3.14.6]
* Operating System & Version: [Windows 10]
* Account type (if applicable): [ Gmail]

In this file:
[Preload file](https://github.com/wavebox/waveboxapp/blob/master/src/scenes/content/src/Scenes/BrowserScene/BrowserScene.js#L202)
While going through the source code, I observed that the preload path for the webview is joined with the string `_wavebox_preload_split_`, but I couldn't find the split for this string. But, there should be some logic to split this string into paths array. I went through this entire repository, but couldn't find it anywhere. Is the 
 code being loaded from somewhere else as well, which is doing part of the logic ?

**Comment by Thomas101** [comment]
Hi, the `_wavebox_preload_split_` has been deprecated in master and in the beta channel and is no longer needed

**Comment by revant117** [comment]
Thanks a lot for the answer @Thomas101
