### ISSUE TITLE
Tray Icon missing on Ubuntu 17

### ISSUE THREAD

**Issue by ahmadabd** [wavebox/waveboxapp#76]
Hi, I upgrade my ubuntu from 16.10 to 17.04 but after running wave ,its icon dosent show on ubuntu menu bar

**Comment by Thomas101** [comment]
Thanks, I think this is related to https://github.com/electron/electron/issues/9046 and https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1629251 . Sounds like slack, skype and a few other electron apps are seeing similar things too

**Comment by Thomas101** [comment]
Hi we've just released this into the beta channel if you want to give a try. There's some instructions on how to [get the latest beta release here](https://wavebox.io/kb/beta-channel). Thanks!

**Comment by lilHermit** [comment]
Beta fixes the issues on Ubuntu 17.04 for me

**Comment by Thomas101** [comment]
Hi, this has just been released into the stable channel of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
