### ISSUE TITLE
Service Icons Cover Page Navigation Buttons.

### ISSUE THREAD

**Issue by GreyCorbin** [wavebox/waveboxapp#761]
* Wavebox Version:  3.14.6
* Operating System & Version:  Ubuntu 18.04
* (Linux only) Install method: Software Center
* Account type (if applicable):  Apps with service accounts (Gmail, Outlook.com, etc.)

**Expected & actual behavior**
I expect to be able to access the Home, Page Forward\Back, and Reload buttons.
I can't see them as tey are covered by the Service Icons.

**Steps to reproduce**
Add services to an app that has them available.

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/40442120/44164424-db453400-a07a-11e8-814a-72d48dbf097b.png)

**Additional information**
if there is a way to move these around, I don't readily see it.

**Comment by nmat** [comment]
Standard service like gmail does not use navigation bar instead it shows the indexed services AFAIK.

This is how wavebox works in general with supported services. If you right click you can go back, forward and copy current url as you want.

Is there a reason for this to be expected in main services for you?

**Comment by nmat** [comment]
on some certain services you can in wavebox say to show navigation bar. But I am not 100% sure if you can do this for these type of services.

**Comment by GreyCorbin** [comment]
Navigating using the browser navigation buttons comes in handy.

Examples:
1- I do a search in google play and click on a result that is farther down the page.  If I want to go back to the search results at the point I left it, I hit the back button.  As far as I can see, there is no way back without starting over.   

2- I'm in one of the drive services (one drive, google drive, etc.) and have navigated farther down in a list of files in a folder.  I click on another folder to reference what is in that folder and want to go back and forth comparing the files in the folders.  Page forward and page back maintain where i am in each folder where clicking the folder takes me back to the top of the folder.  At least in standard browsers thatis the way it works.

 In the image in my original post, the browser navigation is covered by the services.
See the below image of GitHub for reference. (Yes I know GitHub doesn't have services.  Sorta the point, i think.)
![image](https://user-images.githubusercontent.com/40442120/44219308-8e239980-a130-11e8-96cd-5fe242e4ea8b.png)

**Comment by nmat** [comment]
Did you try the back and forward in the right click menu?

![image](https://user-images.githubusercontent.com/383031/44223628-6d872e00-a188-11e8-8238-996e7bcc54a5.png)

![image](https://user-images.githubusercontent.com/383031/44223706-a921f800-a188-11e8-998f-34cc70514d1b.png)

**Comment by Thomas101** [comment]
I've added the option in to enable the toolbar on any service - will be out in the next beta

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
