### ISSUE TITLE
Using sidebar menu with ctrl+click on Mac results in draggable account circles.

### ISSUE THREAD

**Issue by chalisegrogan** [wavebox/waveboxapp#762]
* Wavebox Version: 3.14.6
* Operating System & Version: MacOS High Sierra 10.13.6 (17G65)
* Account type (if applicable): Inbox by Google

**Expected & actual behavior**
Expected: When I ctrl + click on an account, I can close the resulting menu without side-effects.

Actual: 
1. When I ctrl + click on an account, then close the resulting menu by clicking anywhere, my account is now draggable to change sort order (even though my mouse state is "up"/unclicked) and I have to click to get out of that state.
2. When I ctrl + click on an account, select an item on the menu (like Account Settings), when I close account settings my account is now draggable to change sort order (even though my mouse state is "up"/unclicked) and I have to click to get out of that state.

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?

First way:
1. ctrl + click on an account in the sidebar.
2. close the resulting menu by clicking anywhere outside of it.
3. now the account circle is draggable/sortable.

Second way:
1. ctrl + click on an account in the sidebar.
2. open the Account Settings menu.
3. close the account settings menu by pressing Close.
4. now the account circle is draggable/sortable.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
Here is a GIF of the behavior:
![aug-15-2018 15-01-11](https://user-images.githubusercontent.com/1843056/44176061-1ce6d680-a09d-11e8-8571-9b557657f3c0.gif)

**Comment by nmat** [comment]
Ok yes, I could reproduce this in latest beta using Ctrl+Click and there is some odd behaviour.

**Comment by Thomas101** [comment]
Thanks, put a patch in for this

**Comment by nmat** [comment]
Verified working on macOS 10.13.6

Also tested to see if it affected windows in anyway but all is good :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
