### ISSUE TITLE
wavebox - facebook messenger - Jumping text on typing (needs verification)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#763]
* Wavebox Version: 3.14.14 Beta
* Operating System & Version: Windows 10
* Account type (if applicable): Facebook messenger

**Expected & actual behavior**
Static size when text gets to go outside of the normal sized message area.

Text/window with text outside of box keeps jumping and its hard to keep focus.

**Steps to reproduce**
Normal typing message.
Type so much text that it creates a new line inside the message box.
You can see the window starts to jump/bump a bit all the time when typing text. Almost as if the font and window of text box are not aligned.

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
This could be a effect of something else. Therefore needs verification. I have _only_ noticed it in facebook messenger but it kind of hurts my eyes seeing the whole text area jump all the time when typing.

**Comment by Thomas101** [comment]
Seemed to work as expected on macOS and windows here.

Do you have your hidpi monitor attached to this machine (is it a mixture of hidpi and non-hidpi screens?). I wonder if it's something to do with that.

Are you able to send a screen recording?

**Comment by nmat** [comment]
I will try to make a recording when I have some time over this evening. Once I triggered the way I noticed the issue.

**Comment by nmat** [comment]
So I have narrowed it down a bit. 

This jumping seems to happen on my second screen at home using fullscreen + older monitor that is connected with a display port to my 27" monitor.

The second monitor is a widescreen monitor with the 1680x1050 resolution and 100% (recommended) size.

If I use wavebox without using fullscreen it does not jump. And using it on the 27" does not make it jump either. Could this be a rendering thing with the older monitor?

**Comment by Thomas101** [comment]
It's hard to say. Windows does seem to have some problems scaling ui components (e.g. scrollbars) across two monitors when they use different scaling - I wonder if it's down to this in someway. Does it happen everytime with this setup & are you able to take a short capture?

**Comment by nmat** [comment]
I can make a capture just need time to fix it.

Some more information is that the text jumps when hitting second line of text but not on third line or forth. Something magical is going on for second line of text.

**Comment by Thomas101** [comment]
Are you using zoom when this happens? I wonder if it's similar to https://github.com/wavebox/waveboxapp/issues/630

**Comment by nmat** [comment]
I have made a assumption here that this happens on old monitor that I have only. It does not happen on newer once and it only happens on second line of text.

The monitor I use is very old so I am going to close this off for now. The rendering on the monitor is probably wrong in general so closing it to be able to focus on more important stuff for wavebox. For now its fine.
