### ISSUE TITLE
Linux Segfault

### ISSUE THREAD

**Issue by Thomas101** [wavebox/waveboxapp#765]
* Wavebox Version: 3.14.6
* Operating System & Version: Ubuntu 18.04 64-bit
* (Linux only) Install method: Apt-repo

**Expected & actual behavior**
Consistently crashes with a segmentation fault (core dump) whenever I go to File -> move cursor down the file menu

**Steps to reproduce**
File -> Move cursor down the file menu

**Is the bug persistent or intermittent?**
Persistent

**Additional information**
Hived from https://github.com/wavebox/waveboxapp/issues/651#issuecomment-414872286

**Comment by Thomas101** [comment]
@srix55 I've re-opened this here as it's not related to #651. Can you provide the following info so we can try to reproduce the issue...

1. Does it crash every single time? For example you can launch the app, go to the file menu, move the mouse down it and it will crash immediately.
2. If you run the app from the terminal using `/opt/wavebox/Wavebox` and make it crash what error do you see?
3. You said the error has just started happening, have you updated any packages recently - one of these could give a clue.

**Comment by srix55** [comment]
@Thomas101 I found out what's causing the crash. Steps to reproduce:-

1. Install wavebox using official ubuntu package repository. My Ubuntu version 18.04.1 LTS. Wavebox version 3.14.6
2. Add http://e.ggtimer.com/27minutes as an account to wavebox
3. When the javascript timer is running, access the file menu and move the mouse pointer over the options.

This causes a segmentation fault every single time.

**Comment by Thomas101** [comment]
Thanks, was able to reproduce with that.

I've checked with the beta channel and it's fixed there. If you want to give it a try there are some instructions on how to switch channel [here](http://wavebox.io/kb/beta-channel). Alternatively the curent beta is scheduled to go out to stable next week so will be available for general update

**Comment by srix55** [comment]
@Thomas101 That's awesome. I'll wait for the stable release. Thanks for the update.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
