### ISSUE TITLE
Shortcut to another account, while in fullscreen mode, exits fullscreen mode in Ubuntu 18.04

### ISSUE THREAD

**Issue by srix55** [wavebox/waveboxapp#766]
* Wavebox Version: 3.14.6
* Operating System & Version: Ubuntu 18.04.1 LTS
* (Linux only) Install method: Atp-Repo
* Account type (if applicable): NA

**Expected & actual behavior**
When wavebox is in say workspace 1 of Ubuntu, in fullscreen mode (f11), if I configure the global shortcut to access an account in 3rd spot as say ctrl+3, the shortcut does take me to the third account, however, it exits fullscreen mode. The same thing happens with normal shortcuts too (not global ones) - that is, if you are in account 1, and you press ctrl+2 for account at 2nd position while in fullscreen, it exits fullscreen mode.

**Is the bug persistent or intermittent?**
persistent

**Comment by Thomas101** [comment]
Thanks, seeing the same here

**Comment by Thomas101** [comment]
Hi, I think this was fixed in affb95cbf4eec6e7e10fb641fbf806d3a7cf2d36 and is now available in Wavebox 4.0.0. Thanks
