### ISSUE TITLE
Chrome is out of date Warning 

### ISSUE THREAD

**Issue by chuckreynolds** [wavebox/waveboxapp#768]
* Wavebox Version: 3.14.6
* Operating System & Version: OSX 10.13.6 (17G65)
* Account type: Gmail

## Expected & actual behavior
One of the Gmail accounts I use is secured auth via Duo Security. While I can still log into that account by skipping the warning it's something you guys should be aware of that users are running into. Screengrab below.  

## Steps to reproduce
log into account that uses duo security for auth

## Is the bug persistent or intermittent?
every re-auth for that account

## Screenshots
![wavebox-duo-chrome-old](https://user-images.githubusercontent.com/46185/44547917-6bb1f300-a6d1-11e8-85f4-bff9b7542dcf.png)

**Comment by Thomas101** [comment]
Hi, thanks for bringing this to our attention. We do have a newer version of Chromium on the [beta channel](https://wavebox.io/kb/beta-channel). It may be worth switching across in the short term. We're hoping to bring this across to stable soon.

**Comment by chuckreynolds** [comment]
just switched to beta channel. cheers!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.0.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [releases page](https://github.com/wavebox/waveboxapp/releases/tag/v4.0.0) or [download page](https://wavebox.io/download). Thanks!
