### ISSUE TITLE
Feature Request: Allow user to specify a particular browser to open (Chrome, Firefox, etc) rather than just Wavebox browser or Default browser

### ISSUE THREAD

**Issue by OwenEdwards** [wavebox/waveboxapp#769]
* Wavebox Version: 3.14.6
* Operating System & Version: Windows 7

**Is your feature request related to a problem? Please describe.**
On my work laptop, I use Firefox as the Default browser, but usually use Chrome to check my Gmail etc, so that I can keep personal content separate from work content. Using Wavebox to access my Gmail, I can only specify that I want to open links in either the Wavebox browser or the Default browser. This means that Wavebox isn't a convenient replacement for opening Gmail (or Inbox) in my Chrome browser.

**Is your feature request related to an account type?**
Gmail account.

**Describe the solution you'd like**
Add menu options in the Gmail Account Settings, under "Open new windows in which Browser"; as well as "Default Browser" and "Wavebox Browser", allow "Chrome", "Firefox", "Safari" (on Mac), etc. Ideally the app should poll the platform/OS to find out which browsers are available, but this is not as important a feature.

**Additional info**
Screenshot:

![wavebox-pick-browser-feature-request-2](https://user-images.githubusercontent.com/2245205/44597661-41ba0880-a785-11e8-9b7e-9688235eabc9.png)

This is similar, but not identical, to #286. It would be much easier to implement that that one.

**Comment by nmat** [comment]
Also the same as: https://github.com/wavebox/waveboxapp/issues/688

**Comment by OwenEdwards** [comment]
Thanks @nmat; closing as a duplicate of #688, but I hope this can count as an "up-vote" for that feature request.
