### ISSUE TITLE
Feature: Chrome Extensions

### ISSUE THREAD

**Issue by solepixel** [wavebox/waveboxapp#77]
Is it possible to use Chrome Extensions in Wavebox? I know it uses Electron, but there are a lot of Gmail specific extensions available that work as Chrome Extensions. What are the chances of somehow integrating these or opening up Wavebox to allow them to work? (Sorry if this is like asking to install Windows apps on a Mac, but I thought since it's all mostly Javascript/HTML, integration might be possible)

* Which version of Wavebox are you using? 3.1.2
* Which Operating System are you using? OSX 10.12.4

**Comment by Thomas101** [comment]
Extension support is high up on our priority list. Like you said, there are loads of great gmail extensions already out there and we'd love to bring those into Wavebox. It's something I always wanted to add into WMail but never had the time or resources to do so... so watch this space :)

**Comment by thenitai** [comment]
Yep, those 2-3 extensions keep me from using Wavebox for now. Other than that, exactly the tool that I always wanted.

**Comment by themiguelamador** [comment]
Same case here. Any of this solutions is limited because I rely on extensions like Mixmax.

**Comment by antoniom13** [comment]
+1

**Comment by isaacito** [comment]
+1

**Comment by qlfwyyd** [comment]
+1

**Comment by gabepaez** [comment]
+1

**Comment by Thomas101** [comment]
Hi, we're tracking extension support for Extensions from issue #138. This includes a form to vote on the extensions you'd like to see in Wavebox, which will give us a guide on which ones to test with and ensure work. Thanks
