### ISSUE TITLE
Wavebox stuck in fullscreen mode

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#771]
* Wavebox Version: [e.g. 3.0.0]
Current Beta
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
windows 10
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
Problem occured after being in gmail

**Expected & actual behavior**
Could not get wavebox back to normal size.  The windows controls in the upper right corner were missing, Esc key did not work either.
Some information about what you expect to happen and what actually happens.

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?
The problem occurred while I was replying to an email and fat fingered a key that put wavebox in full screen mode.  even after sending the reply wavebox still remained in full screen mode.  The normal windows controls were not visible.  I tried enabling the menu but that didn't work either.  Shutting down and restart did not help.  Right now wavebox is stuck in full screen mode 

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?
don't know

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**
Maybe there is way of exiting out of full screen mode but it is not obvious.  I can minimize it but not get wavebox out of full screen mode.

**Comment by CheechGe** [comment]
Ok, I manged to get it restored to the normal size using the View menu item.   Something to consider.  Normally I do not have the "Show Titlebar Menu" enabled so the View option wasn't visible.    In that situation it would be nice if the Escape key would take Wavebox out of full screen mode, which BTW is the way many other applications do it.

**Comment by nmat** [comment]
Hmmm I do not really agree.....most applications use F11 just like wavebox do.

Can you bring a example of application that uses Esc as escape out of fullscreen on windows 10?

**Comment by nmat** [comment]
You can also change how this behaviour is suppose to be:

![image](https://user-images.githubusercontent.com/383031/44719513-caa5ac80-aac3-11e8-938a-7188af92a863.png)

**Comment by CheechGe** [comment]
Well, that's interesting.  Until you mentioned it I never even thought of using F11 and always used ESC.  I  don't normally use full screen mode (it's a bit much on a 26" monitor) except on video playbacks.  When I reported the "issue" I had no intention of going into full screen mode and couldn't get out using the way I normally have gotten out.  Until I found turned on the menu bar and saw that there was a way of exiting in under the View menu item, I was "stuck" in full screen mode.  By then I had opened the "problem".  I still didn't use the F11 to exit but clicked on the menu item. 

If you click on a video in a news site like  BBC.com and use the full screen icon in the bottom right to go into full screen mode Esc will take you out, as will F11.   If I recall the same is true for screen sharing software, webinar/meeting and playback software.  My experience has been that the ones that have the icon in the bottom right to into full screen mode allow one to exit via Esc key.

I suspect this goes back to the days when keyboards didn't have individual function keys and to use one was a 2 key operation (Fn + number).  Old habits die hard.  I suspect I will bang on the Esc key a few more times before I remember to use F11.

**Comment by CheechGe** [comment]
I'm ok with closing the request now that I know that F11 will exit.  As I
stated it's a habit that had always worked when I used full screen mode,
which is not often.  BTW what is the key after the CTL+ you mentioned to
toggle the menu?

**Comment by nmat** [comment]
§ is the key next to number 1, above tab and below esc on the keyboard.

so pressing Ctrl+§ will toogle menu. :)

**Comment by CheechGe** [comment]
Thanks

**Comment by CheechGe** [comment]
Well CTL+ and that key doesn't seem to work for me.  I also tried CTL+SHF+
key (I don't know how to put in the correct symbol for that key) and that
doesn't work either.  Right now the menu is displayed and should turn off.

**Comment by CheechGe** [comment]
Yes, it is English and CTL+\ worked, thanks.
