### ISSUE TITLE
[Feature] Periodically awaken sleeping accounts

### ISSUE THREAD

**Issue by phahulin** [wavebox/waveboxapp#772]
* Wavebox Version: 3.14.6
* Operating System & Version: Ubuntu 16.04

It would be nice to be able to awaken a sleeping account periodically, gather notifications and then fall back into sleep again.

My use-case: there are some not-fully-integrated applications like Gitter, where I'm not expecting to get any critical notifications, so I'm OK with it being asleep most of the time and save resources.
However, it would be nice to get those notifications periodically, without manually opening wavebox and checking the account. So for sleep management there will be two options, e.g.  "Go to sleep after - 5 minutes" and a new one "Awaken every - 30 minutes". In this case at *:30:00 every hour, wavebox would awake Gitter, receive notifications from it, display them and then fall back to sleep after 5 minutes, if I don't click on any of the notifications.

Sorry if this is already implemented, I haven't found it yet.

**Comment by nmat** [comment]
From what I know the notifications or unread should be handled in the background when a app is asleep.

Has there been issues where you have not recieved unread during the time its been asleep?

**Comment by Thomas101** [comment]
This is something we're looking at to see how well it might work! There's already an issue open for this here https://github.com/wavebox/waveboxapp/issues/550
