### ISSUE TITLE
Custom URL for Zabbix integration

### ISSUE THREAD

**Issue by tobias-kuendig** [wavebox/waveboxapp#773]
There is an integration for Zabbix available out-of-the-box. The default URL it loads is support.zabbix.com.

Is there a way to customize this and have it point to a custom zabbix server? If no, shouldn't there be an option for this? Will it even make a difference if I use this Zabbix integration or just add a custom website to Wavebox?

**Comment by nmat** [comment]
The main urls I believe is for the cloud based services that are available. If you want to add or change a custom url its better to add URL using a custom URL like you said.

**Comment by Thomas101** [comment]
At the moment the integrations are pretty similar. You're safe to add it in using the Any Weblink url 👍
