### ISSUE TITLE
Open current item in tab X - Ex: zendesk

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#775]
* Wavebox Version: 3.14.15beta

**Is your feature request related to a problem? Please describe.**
Currently there is a way to "Open Link in Account Profile". What happens with this option is that it uses the login information for that account and launches to show item.

For example zendesk can have tabbed items inside its option. Like clicking notifications it would be nice to have that you can open links in the same way.

"Open in tab xxx" where xxx would be the zendesk tab.
Tab is selected and opens the item.

Another example could be opening JIRA issues. Where you just want to select the tab en go to current item selected.

Therefore no extra window is opened. 

**Is your feature request related to an account type?**
Zendesk, Jira well anything where you can relate a item to a tabbed service.

**Comment by nmat** [comment]
Maybe this can be an option in preferences.

"Open link in account"
* Options: New Window, Account(service) tab

Or also like chrome does. Holding down for example Ctrl+Click link option to override how to open link.

So lets play with the thought that you have:

New window - Set (default)

But can override that by: 

Ctrl/Cmd + Click (open in account tab)
Ctrl(Cmd) + Shift/Alt + Click (open in new window using account service information like it does now)

Does this make sense in the way of how to make it dynamic based on user need?

**Comment by Thomas101** [comment]
The Ctrl/Cmd click is a real pain to pick out. The context menu handler doesn't get this information so it's a bit of guesswork as to what the state the keyboard & mouse are in at time of click.

My thought was to add another option into the context menu so you'd have...

* `Open Link in Account Profile` - the current behaviour
* `Open Link in Account Tab` - a menu with the list of tabs and on click, open in the actual tab (probably some better wording than this too)

**Comment by Thomas101** [comment]
Maybe it's something we should have as an advanced opt-in. It is getting a bit cluttered in there I have to admit

**Comment by Thomas101** [comment]
Hey, this has just gone into master - some changes to the context menu. We've added `Open Link in Service` which does this. It only displays the services that are running (e.g. not sleeping) partially because we thought the list would grow quite large, but it would be good to know if this would work for what you're trying to do. Also if the terminology is good - nobody here can agree so far.

You'll need to ignore my poorly named services too :-)

![screen shot 2018-10-03 at 08 49 25](https://user-images.githubusercontent.com/103586/46397114-44dfd700-c6e9-11e8-9587-7f4830b58163.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.3.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Going to close this off in favour of #828 now this is in stable. Thanks!
