### ISSUE TITLE
[bug] - Many services in tab, double click goes to first indexed service

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#777]
* Wavebox Version: GIT-2018-09-09
* Operating System & Version: windows 10

**Expected & actual behavior**
Double click from other service to new service should not select first sandboxed service. It should go to last known service. (its easy to miss click)

Example:
* I have 6 slack services using new sandboxed services
* I go from gmail -> slack and miss click 2 times

This will automatically go to service 1. 

**Is the bug persistent or intermittent?**
Persistent. 

**Additional information**
There has been a feature added where you can hide first service to the main service. Of course when this is "active" double click could switch. IMO if this is not active though then it should treat double click as null where it does not go to first indexed service.

**Comment by Thomas101** [comment]
This is kind of a bug-turned feature, that we left in on purpose. We've changed the behaviour of clicking on the sidebar between the current stable and beta channels. On 3.14.6 clicking on the account always takes you back to the first service. On the beta channel when you click on account in the sidebar it does a check to see what it should do, the behaviour that gets triggered is...

1. **Currently in a different account**: Switch to the last service
2. **Currently in the account but a different service**: Switch to the service in the first position

When you double-click it basically triggers 1 then 2 in order which means a double-click is shortcut into the account in the first position.

We left this in (as well as adding long-press to take you to the first item) as a way to shortcut into the first service.

Not sure what the best behaviour is here - on one hand I think it's useful to have the double click behaviour, but on the other hand I can see your use-case too with it being annoying.

**Comment by nmat** [comment]
Yes I agree to 100%. I have just noticed on working fast with switching it might switch to fast to the first service. So the best way to go around it is to use the keyboard shortcuts.

Not sure either how to work with this either.

**Comment by Thomas101** [comment]
After discussing this in the office we did wonder if the rapid switch between accounts made it look like a bug. For example when you double click you briefly see the service switched to in the first click before seeing the second one.

On the other side of that though, if we try to detect the difference between a click & double-click and action accordingly we have to put a short pause when detecting a single click. I wonder if this would make the app feel a bit more laggy.

This isn't an easy one to sway either way :-/

**Comment by Thomas101** [comment]
@nmat I think on review of this one, we're going to leave the double click behaviour in. For the most part it's something that's useful to switch into an account quickly. If you think it still looks buggy though, we're happy to take suggestions to make it feel less so :)
