### ISSUE TITLE
Trello integration requires manual refresh to clear notifications

### ISSUE THREAD

**Issue by tlockAOB** [wavebox/waveboxapp#778]
* Wavebox Version: 3.14.6
* Operating System & Version: Mac OSX 10.13.6
* Account type: Trello

**Expected & actual behavior**
Expected: Mark all notifications as read inside Trello, Wavebox sidebar notification jewel disappears
Expected: Clear one or more notifications inside Trello, Wavebox sidebar notification jewel updates accordingly
Actual: Nothing happens on Wavebox sidebar notification jewel, until manually right-clicking and selecting "re-sync"

**Steps to reproduce**
See Expected and Actual, steps are clear

**Is the bug persistent or intermittent?**
Always

**Comment by tlockAOB** [comment]
Not a huge deal, but I notice that trello doesn't update, while the other integrations I use work nicely. I believe Trello is probably one of the most popular integrations, so it would be good to take a bit of time to look into this.

Thanks & <3

**Comment by Thomas101** [comment]
At the moment there isn't a mechanism for Trello to tell us about notification changes, we just have to keep checking periodically. Currently, we check every 30 seconds so it would be good to check that if you clear the notification, the badge clears on Wavebox at some point.

There are a few more things we can do to try and detect when the notifications change. I'll have a look if that's something we can add in

**Comment by tlockAOB** [comment]
Ah, I see. Yes just tested and it was about 12 seconds. So I was probably 18 seconds into the cycle when I cleared my unread notifications within Trello.

Thanks for the reply. Keep up all the great work!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.1.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by tlockAOB** [comment]
awesome, thanks for the great work!
