### ISSUE TITLE
It's no longer possible to minimize Wavebox to tray on KDE

### ISSUE THREAD

**Issue by Tunous** [wavebox/waveboxapp#78]
* Wavebox 3.1.4
* Arch Linux
* KDE 5.9.4

I've just updated to version 3.1.4 and there is a really annoying change. Basically, it's no longer possible to minimize Wavebox to tray area. **Whenever I press the close button Wavebox is fully closed instead of getting hidden to the tray.** Using minimize is not an option as that leaves the application visible in the taskbar.

In version 3.1.3 it worked correctly and pressing close button minimized Wavebox to the tray.

**Comment by WebShapedBiz** [comment]
Same here with Wavebox 3.1.4 on ElementaryOS Loki. I hope that this is not a feature since it's very annoying. 

Cheers.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. I've just pushed 3.1.5 out with a fix for this!

**Comment by WebShapedBiz** [comment]
Thank you.
