### ISSUE TITLE
Main window freezes after internet drops and "coffee shop" style login required to restore internet

### ISSUE THREAD

**Issue by SteVwonder** [wavebox/waveboxapp#783]
* Wavebox Version: 4.0.0
* Operating System & Version: RHEL 7.5
* (Linux only) Install method: rpm
* Account type (if applicable): all

**Expected & actual behavior**
**Expected:** window is responsive
**Actual:** after being left alone for the night, when I come in to work in the morning, the main window of Wavebox is frozen.  While the long period of idleness might be the cause, I suspect the actual cause is the loss of internet and DNS shenanigans.  My employer cuts of internet access after ~12 hours and requires re-logging in via a "coffee shop" style login page (that uses DNS intercept to redirect all outbound internet activity to the page).  Clicking on the main window has no effect (although you might still be able to switch accounts, I need to double check).  The tray icon still responds to a right-click, but clicking on the menu items has no effect. I can close the main window via the close command of my window manager, but the application as a whole will not close.  I have to use `pkill` to close the whole app.

**Steps to reproduce**

Start up Wavebox, cut off internet and institute a DNS redirect to a login page before restoring internet. Admittedly, this is a bad reproducer.  I imagine this could be reproduced with a VM and a script running on the host.  In the meantime, I can replicate it locally every morning.

**Is the bug persistent or intermittent?**
Happens every morning when I go into work

**Additional information**

GDB Backtrace of running Wavebox processes on my machine while Wavebox is frozen and after I restarted Wavebox: https://gist.github.com/SteVwonder/adbb03dfc6d90c8de2e7d149742b1514

The main difference seems to be that in the restarted case, most everything is in a wait or a poll.  In the frozen case, one of the processes has `atom::api::SendSync` in the backtrace.

If anyone has any ideas on additional information I can gather after the freeze, I'd be more than happy to collect it.  Having more debugging symbols would probably be helpful.

**Comment by Thomas101** [comment]
Thanks, I'll see if I can get a similar setup running here and try to reproduce. It would be great to know a couple more things so I can try to narrow it down...

* As you mentioned, are you able to switch accounts or anything like that? (i.e. is it one tab that's frozen or the entire window)
* Is version 4 the first version you've seen this with or did you see the same on a previous version?
* Are you able to test if leaving it for a long time without the DNS redirect?
* Do you have an external monitor or anything that gets plugged in/unplugged overnight (wondering if it could be https://github.com/wavebox/waveboxapp/issues/748)

**Comment by SteVwonder** [comment]
Thanks for looking into this.

> As you mentioned, are you able to switch accounts or anything like that? (i.e. is it one tab that's frozen or the entire window)

I checked this morning and the entire main window is frozen.  I cannot switch accounts.

>    Is version 4 the first version you've seen this with or did you see the same on a previous version?

It was happening on a previous version too.

>    Are you able to test if leaving it for a long time without the DNS redirect?

Unfortunately, not with this machine.  I can try with my linux machine at home, but the setup is pretty different (ubuntu vs rhel)

>    Do you have an external monitor or anything that gets plugged in/unplugged overnight (wondering if it could be #748)

The machine is a desktop with a single monitor that is never detached or turned off.

>    Does turning off Hardware Acceleration in Settings > Advanced make any difference (just on the off-chance)

I will try changing that setting now and report back tomorrow morning.

**Comment by Thomas101** [comment]
Thanks for the extra info, that's really useful!

**Comment by SteVwonder** [comment]
@Thomas101: turning off hardware acceleration seems to have fixed it.  Came in this morning, and everything works.  My apologies for the causal red herring.

**Comment by Thomas101** [comment]
Have you got an nvidia gpu by any chance? Wonder if it's related to https://github.com/wavebox/waveboxapp/issues/748

**Comment by SteVwonder** [comment]
Yeah.  A Quadro K2000.  Maybe after long enough an idle timer fires, changing something about the display, and tickles the cause of #748.  I subscribed to that issue, if any activity happens there, I'll turn hardware acceleration back on and see if this hang goes away.  Since disabling hardware accel fixed this for me, feel free to close this issue in the meantime, if you think that is appropriate.

**Comment by Thomas101** [comment]
Thanks. We have seen a few of these on Linux which mainly seem to involve a Nvidia GPU - with HW Acceleration fixing it. I'm hoping the next chromium upgrade will help with some of these :).
