### ISSUE TITLE
zypper repo is no longer working

### ISSUE THREAD

**Issue by Cris70** [wavebox/waveboxapp#784]
* Wavebox Version: 4.0.0
* Operating System & Version: openSUSE Tumbleweed
* (Linux only) Install method: zypper repo
* Account type (if applicable): Gmail & Office365

**Expected & actual behavior**
Update Wavebox using the configured repository

**Steps to reproduce**
'zypper dup' at cli

**Is the bug persistent or intermittent?**
Always happens

**Additional information**
Starting today, every try to access the Wavebox repository yields an error:

```
cristiano@xmper8q3 [~]$ LANG=C sudo zypper ref
[sudo] password for root:
(...omitted...)
Retrieving repository 'Wavebox Beta - x86_64' metadata --------------------------------------------------------------------------------------------------------------------------------[|]
File './repodata/96806d5200975acf05acdd767782ed1c932cad9fe608a7e1b7fd32c771968b51-primary.xml.gz' not found on medium 'https://wavebox.io/dl/client/repo_beta/yum/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a):
Abort, retry, ignore? [a/r/i/...? shows all options] (a):
Retrieving repository 'Wavebox Beta - x86_64' metadata ............................................................................................................................[error]
Repository 'Wavebox Beta - x86_64' is invalid.
[wavebox_beta|https://wavebox.io/dl/client/repo_beta/yum/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'Wavebox Beta - x86_64' because of the above error.
Some of the repositories have not been refreshed because of an error.

```
Thank you in advance.
Cris

**Comment by Thomas101** [comment]
Thanks for reporting. Can you give it another try? You might have to do `zypper refresh wavebox_beta` first though

**Comment by Cris70** [comment]
Same as before, unfortunately:
```
cristiano@xmper8q3 [~]$ LANG=C sudo zypper ref wavebox_beta
Retrieving repository 'Wavebox Beta - x86_64' metadata --------------------------------------------------------------------------------------------------------------------------------[|]
File './repodata/96806d5200975acf05acdd767782ed1c932cad9fe608a7e1b7fd32c771968b51-primary.xml.gz' not found on medium 'https://wavebox.io/dl/client/repo_beta/yum/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a):
Abort, retry, ignore? [a/r/i/...? shows all options] (a):
Retrieving repository 'Wavebox Beta - x86_64' metadata ............................................................................................................................[error]
Repository 'Wavebox Beta - x86_64' is invalid.
[wavebox_beta|https://wavebox.io/dl/client/repo_beta/yum/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'Wavebox Beta - x86_64' because of the above error.
Could not refresh the repositories because of errors.
```

**Comment by Thomas101** [comment]
What's the output from `zypper refresh wavebox`? I can't see `96806d52...` in the repo so wondering if it's an old cache :-/

**Comment by Cris70** [comment]
@Thomas101 I do not have the Wavebox repository configured, only the Wavebox_beta.
Do you want me to configure that one too? Don't they conflict?

**Comment by Thomas101** [comment]
Sorry, typo my end. Yeah wavebox_beta (`zypper refresh wavebox_beta`)

**Comment by Cris70** [comment]
That's exactly the output I sent two messages ago :-)
"ref" is short for "refresh", so besides the "LANG=C" (needed to have messages in english, otherwise my zypper would speak italian) and the "sudo" (I guess you know what sudo is) the rest is exactly the command you want me to execute.

I do not know why it is looking for that 96806d5200975acf05acdd767782ed1c932cad9fe608a7e1b7fd32c771968b51-primary.xml.gz, it is not in the .repo file so it must be something that comes from the website.

Now that you say so, however, I am thinking that maybe our internal proxy may be caching something, so it may be that I'm not getting what is presently in the repo.

I do not know how to prove that, BTW. I'll check later at home, to see if I have the same problem there.

**Comment by Cris70** [comment]
@Thomas101 I do not have the problem at home. So I must assume the proxy here at work is giving me back old cached content :-(
If anybody reading this knows how to avoid it, I'd like to hear from you.
Sorry for the noise.
