### ISSUE TITLE
google drive - scaling is not automatic on windowed wavebox

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#785]
* Wavebox Version: 4.0.0
* Operating System & Version: windows 10
* Account type (if applicable): Google Drive

**Expected & actual behavior**
Google Drive should have some sort of scale based on the window position. At the moment google drive window does not scale and creates a scrollbar at the bottom.

A work around could be to zoom in the window. If this is intentional then close the issue.

**Steps to reproduce**
1. Keep the window with 0 zoom
2. Go to google drive when wavebox is in left position on monitor next to another window
3. If the zoom is 0 then the scaling becomes odd even on normal screens + if I upload a item to google drive then the window of the upload becomes hidden behind everything.

In general it does not seem the content is being scaled and proportion to the window.

**Is the bug persistent or intermittent?**
Persistent.

**Additional information**
Is this intentional?

**Comment by Thomas101** [comment]
Not sure I follow 100%. I didn't see anything odd, but have probably missed something out...

1. WB & Chrome side-by-side ![a](https://user-images.githubusercontent.com/103586/45482513-359ee680-b746-11e8-95e8-a58305124e61.PNG)
2. Open a Google Drive doc (opens atop other windows) ![b](https://user-images.githubusercontent.com/103586/45482532-45b6c600-b746-11e8-9880-91bff5288117.PNG)
3. Drag to the right ![c](https://user-images.githubusercontent.com/103586/45482550-51a28800-b746-11e8-86d7-a6d7cbb9c2a0.PNG)

**Comment by nmat** [comment]
What I mean is like in the first image.

You see the bottom scrollbar? If you upload a file to your google drive then you have to scroll to the right.

However like I said this can be _by design_ in order to use zoom to see it all?

**Comment by Thomas101** [comment]
I think I understand. I think it's by design.

Snapping the windows left and right really just resizes them and locks them into position. It doesn't try to scale the content of the windows at all. With drive, there's a min-width which is why it falls out to scrolling. I suspect the behaviour is the same with the browser too?

**Comment by nmat** [comment]
It does the exact same thing in browser. I will close this off since it is by design. Thank you for verifying.
