### ISSUE TITLE
wavebox not opening with windows10 beta (OS build 17754.1)

### ISSUE THREAD

**Issue by chad-bennett** [wavebox/waveboxapp#787]
Installed the new Windows10 beta for slow-ring (OS build 17754.1) and now Wavebox does not open. 

When clicking icon in taskbar or start menu, nothing happens. I cannot find anything about Wavebox in the task manager, it isn't running, there are no processes, nothing. It is like the launch icon does nothing at all.

**Comment by Thomas101** [comment]
Thanks for reporting! There's a couple of catch-all things that might be worth trying first before trying to debug further...

1. Restart the machine - any difference?
2. Remove Wavebox through the control panel, re-download the latest version from http://wavebox.io/download , install and give it another try

Thanks

**Comment by chad-bennett** [comment]
reinstalling did the trick.

thankfully i had wavebox installed on a different machine and was able to backup the profile for an easy reset. woo-hoo!

**Comment by Thomas101** [comment]
Awesome! Out of curiosity it would be good to know the update path you took before it broke. Was it that you updated Wavebox to version 4, or updated windows to the latest beta and it broke?
