### ISSUE TITLE
Don't recreate desktop shortcut on update (Windows)

### ISSUE THREAD

**Issue by ventaur** [wavebox/waveboxapp#79]
I like a clean desktop, so I typically delete any shortcuts applications automatically add without asking. I can live with that; no problem. However, it's very annoying when the desktop shortcut re-appears after every update.

It appears that [this can be accomplished with Squirrel](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-process.md#update-process). Use the `--createShortcut` option for new installations only. During updates, use the `--processStart` option instead.

[This appears to be the place where the updater is always creating the shortcut.](https://github.com/wavebox/waveboxapp/blob/master/src/app/src/app/AppUpdater/AppUpdater.js#L140) If so, I'd be glad to submit a PR with the change that _should_ correct it, but I have no easy way to test this (not sure how to force an 'update' in order to try it out).

* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.4

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

**Comment by Thomas101** [comment]
Hi, I can see how it can be annoying and you're right should probably do it only on first install.

Thanks for offering to open a PR, it's a real faff to get the update cycle working and tested though, binaries need to be signed and hosted etc for squirrel to work., I'll schedule this in for the next release and add it in.

3.1.5 has just been released so you'll probably get another desktop shortcut (sorry!), but I'll try to get it into 3.1.6

**Comment by ventaur** [comment]
Hi @Thomas101 

At least I don't rage out when it happens. :-P It's just one of those things.

I totally understand the testing on this would be a bear for a contributor but don't want to be one of those people who only ask for features instead of offering to help. We deal enough with those requests/demands in OSS as it is!

Thanks!

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which fixes this. When it autoupdates your desktop should remain shortcut free :). Thanks!
