### ISSUE TITLE
Octobox: Allow custom URL

### ISSUE THREAD

**Issue by rhuss** [wavebox/waveboxapp#791]
* Wavebox Version: 4.0.0
* Operating System & Version: macOS 10.13.6

**Is your feature request related to a problem? Please describe.**
I would like to set a custom URL for the Octobox Account

**Is your feature request related to an account type?**
Octobox

**Describe the solution you'd like**
As I'm running my custom Octobox instance it would be awesome to be able to configure the URL for that account. Currently, I'm using the generic Webapp account but misses the badges which are provided by the dedicated Octobox account type.

Also, the Octobox Icon has changed so it might be worth to update the icon, too.

![image](https://user-images.githubusercontent.com/99080/45546663-3efb8200-b81e-11e8-87e3-28b568668ed7.png)

**Comment by Thomas101** [comment]
I'll have a look what we can do! It may be possible for us to bring out some of the container functionality in the "any weblink" account too.

Thanks for the headsup on the logo too!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.8.5. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by rhuss** [comment]
Cool, thanks! Works like a charm, would report back issues if I find one.

Feel free to close this issue when the feature is released (or earlier)

**Comment by rhuss** [comment]
I found out one issue: The notification badge appears/disappears at random when I navigate within the app

![grafik](https://user-images.githubusercontent.com/99080/55070475-a2e0ec00-5086-11e9-874f-b4b9dbb9b305.png)

![grafik](https://user-images.githubusercontent.com/99080/55070519-bdb36080-5086-11e9-96df-7be9b95b855e.png)

The badge then also doesnt show up when I change to another app.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.9.0). I've also changed the way that we're getting the unread count, from the page title to reading it out the UI, so this should be displayed more consistently now!
