### ISSUE TITLE
office 365 - overbudget exception (required reboot) - (needs verification)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#793]
* Wavebox Version: 4.0.0
* Operating System & Version: windows 10
* Account type (if applicable): Office 365

**Expected & actual behavior**
Continue working according to throttling and budget policy.

Crashes and causes the office 365 system to not respond. (After reboot wavebox works) did test with chrome on the side and chrome did work. 

**Steps to reproduce**
Not sure...I was working in outlook and started to move files in hundreds. 

After some time working with files I get: X-OWA-Error Microsoft.Exchange.Data.Directory.SystemConfiguration.OverBudgetException

**Is the bug persistent or intermittent?**
Intermittent (due to not knowing exactly when this is triggered or how)

**Additional information**
I tried restarting wavebox - but exception was still there. (office 365 error of course not wavebox error)
Tested to access office365 and outlook without any problems in chrome (mostly I guess since that application did not overbudget the connection)

Reading up a bit I have seen others saying that applications should be set to follow policy on office365 to avoid the overbudget exception. However I am not 100% sure that wavebox can or even browsers for that matter can read the policy and follow it.

Therefore I am not sure its a bug in that sense. If not then close it off.

**Comment by nmat** [comment]
https://blogs.msdn.microsoft.com/exchangedev/2011/06/23/exchange-online-throttling-and-limits-faq/

**Comment by Thomas101** [comment]
Interesting one. Did you see the error come up in the main tab in Wavebox or was it somewhere else? The background sync that we do is separate to what you see in the tab so I can't imagine it's any of the sync stuff we're doing.

I wonder if it was a just a glitch somewhere? Have you seen it again since?

**Comment by Thomas101** [comment]
That is really odd. I'm inclined to say it could be a glitch on Microsoft's end or maybe the sysadmin was changing or updating things and your client has fallen into an undefined state of some kind.

If it comes up again I definitely think it's worth looking into further, but as far as actually displaying the Microsoft tabs we should be behaving exactly the same as a browser.

If you're not seeing it anymore am I okay to close off? Obviously feel free to just re-open if it does come up again

**Comment by Thomas101** [comment]
Maybe open up the dev-tools, hit the network tab and then reload the page. See what comes out from that.

**Comment by nmat** [comment]
I will do that....if it occurs again
