### ISSUE TITLE
Wavebox does not load after first run.

### ISSUE THREAD

**Issue by antiksink** [wavebox/waveboxapp#794]
* Wavebox Version: [4.0.0]
* Operating System & Version: [Solus OS - Current]
* (Linux only) Install method: [Snap Package]
* Account type (if applicable): [All]

**Expected & actual behavior**
Wavebox is expected to open and be visible after first run.
Wavebox does not load after first run. Works fine until close application and reboot computer.

**Steps to reproduce**
Install Snap, Run application, Restore Profile, Close Application, reboot computer or restart VM.
- Wavebox no longer opens.

**Is the bug persistent or intermittent?**
Seems to always happen now.

**Screenshots**
N/A

**Additional information**
Have reproduced on three machines, Two Solus OS Laptop and Desktop - 1 Solus OS VM on Windows Laptop - All same result.

**Comment by antiksink** [comment]
After another reboot Wavebox now opens on this instance without reinstall

**Comment by Thomas101** [comment]
Hi, it would be good to have some more info...

1. By doesn't open, do you just see nothing whatsoever? No windows etc? If you use `ps aux` is Wavebox listed as running?
2. If you try updating to Wavebox 4.1.0 does that make any difference?
3. If you try running it from the command line with `snap run wavebox`, then quit the app and try again does this produce the same behaviour?
4. Do you have to restore the profile each time? What's the behaviour if you don't restore the profile?

**Comment by antiksink** [comment]
Hi Thomas, 
By doesn't open = I see nothing, no windows no indication that anything has happened.
ps aux = Wavebox is not listed as running
Updated to 4.1.0 = Wavebox Opened on first run after update but not after reboot.

Running from command line =
@solus-vm ~ $ snap run wavebox
cannot change profile for the next exec call: No such file or directory
snap-update-ns failed with code 1: No such file or directory

**Comment by Thomas101** [comment]
Thanks. There are a few similar reports on the web as regards Snaps and Solus (not just Wavebox).

There's quite a bit of discussion in [this Reddit thread](https://www.reddit.com/r/SolusProject/comments/8j2tpv/problem_with_running_snaps/) with people checking that `snapd` is running and also re-installing snap, but no conclusive answer.

Also on the [snapcraft forum](https://forum.snapcraft.io/t/problem-with-snapd-and-snaps-on-solus-3-9999/5765/6) they point that it could be an issue with apparmour. It might be worth trying the snap with classic confinement, although I'm not sure if this will help. [Howto in this KB](https://wavebox.io/kb/installing-snap-with-classic-confinement).

Maybe @ikeydoherty can point us in the right direction with this?

Alternatively it might be worth giving the tar version of Wavebox a try from [the download page](https://wavebox.io/download) as a stop-gap

**Comment by antiksink** [comment]
Thanks - I just found this to work. Re-installed snapd and wavebox launches with profile accounts intact.

`sudo eopkg install snapd --reinstall`

**Comment by Thomas101** [comment]
Glad you got it working and thanks for the heads up on what worked :)
