### ISSUE TITLE
Command/Control + [ support in slack

### ISSUE THREAD

**Issue by greggb** [wavebox/waveboxapp#796]
#### Slack Integration

**Expected & actual behavior**
Expected: `command-[` and `command-]` navigate through the slack channel history

Actual: No action

**Steps to reproduce**
Visit a slack team and navigate to a few different channels. Use the `Command-[` shortcut to navigate back in history to see your previous channels.

**Is the bug persistent or intermittent?**
Persistent

**Comment by Thomas101** [comment]
Hi,

The <kbd>Cmd</kbd>+<kbd>[</kbd> and <kbd>Cmd</kbd>+<kbd>]</kbd> shortcuts are actually browser shortcuts to navigate back and forwards - which has the effect of switching back and forwards between channels in Slack.

By default, Wavebox uses <kbd>Cmd</kbd>+<kbd>Left Arrow</kbd> and <kbd>Cmd</kbd>+<kbd>Right Arrow</kbd> for navigating backwards and forwards. If you'd rather not change muscle memory, you can change the keyboard shortcuts in Wavebox instead :-). To do this...
1. Open Settings
2. Go to the Keyboard Shortcuts Section on the left
3. Open the View Section
4. Change `Navigate Back` to be `CmdOrCtrl+[` (either by pasting or editing)
5. Change `Navigate Forward` to be `CmdOrCtrl+]` (either by pasting or editing)

![screen shot 2018-09-19 at 10 15 36](https://user-images.githubusercontent.com/103586/45743924-17793080-bbf5-11e8-8cfe-fd21735ba058.png)

There's also a [blog about changing keyboard shortcuts here](https://blog.wavebox.io/be-a-keyboard-shortcut-master/) which might be helpful. The location of the settings have changed as per the blog - we haven't gotten around to updating it for the new 4.0 UI as yet.

Does this help?

**Comment by greggb** [comment]
Thanks @Thomas101 that does the trick - I had read the blog and looked in a few of the shortcut accordions, but hadn't thought to look under view.

Appreciate the help. `Pro Account++`
