### ISSUE TITLE
Ghost notification on Gmail

### ISSUE THREAD

**Issue by jsnowacki** [wavebox/waveboxapp#797]
* Wavebox Version: 4.1.0
* Operating System & Version: Windows 10
* Account type (if applicable): Gmail

**Expected & actual behavior**
I have notification about unread e-mail in Gmail, both on the main account and Gmail icon, but there are no unread e-mails. 

**Steps to reproduce**
Hard to tell but it mostly happens after either update or some abrupt application closing (like lid closing or run out of battery power).

**Is the bug persistent or intermittent?**
Intermittent and it often goes away after some time, but there is no clear method of cleaning this state. Refresh ctrl+shift+R doesn't help; nor shutting on and off.

**Screenshots**
The notification cleared during writing of this bug report but it just looks as a notification, mostly 1 e-mail (hence, red dot with 1 on both main and gmail icon).

**Additional information**
It seems account unrelated as I get it both on my work (Gsuite) as well as private account. Also happens to different accounts, but most often for the Gsuite ones. It doesn't happen very often though.

**Comment by nmat** [comment]
https://wavebox.io/kb/google-unread-counts can you check if this helps?

There has been some questions regarding this topic and I had issues also but after a while managed to sort it out with the help of this knowledgebase.

**Comment by Thomas101** [comment]
@jsnowacki at a guess, it sounds like your laptop is disconnecting from the web and Wavebox isn't resyncing correctly when it reconnects. To get notified about new emails Wavebox uses a push channel to be told by Google and watches the tab (if open) to see if the unread count changes.

Next time it happens, right click on the tab and then pick `Resync`. This will force a resync of the counts etc

![screen shot 2018-09-20 at 09 56 55](https://user-images.githubusercontent.com/103586/45807561-a05a9f80-bcbb-11e8-8923-ae3410ec1da9.png)


If this is the case then I'll take a look at the reconnect code to see if it's not triggering for some reason

**Comment by jsnowacki** [comment]
@nmat  @Thomas101 Thanks a lot! I'll try the suggested solution and let you know if there are some issues.

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
