### ISSUE TITLE
Dock icon is shown when "Always start minimised" and "Remove from dock when all windows are hidden" are selected.

### ISSUE THREAD

**Issue by jmfederico** [wavebox/waveboxapp#799]
* Wavebox Version: 4.1.0
* Operating System & Version: macOS 10.13.6

**Expected & actual behavior**
When launching Wavebox with "Always start minimised" and "Remove from dock when all windows are hidden" options set to True/Selected, the Dock icon should not be shown. Instead only the Menu bar icon should be present.

**Steps to reproduce**
Install
Open and activate "Always start minimised" and "Remove from dock when all windows are hidden"
Close
Open again

**Is the bug persistent or intermittent?**
Persistent

**Comment by Thomas101** [comment]
Nice find! I'll put out a patch for that.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
