### ISSUE TITLE
Ability to remove colored ring around account icon

### ISSUE THREAD

**Issue by TheOddler** [wavebox/waveboxapp#80]
It would be awesome if the colored rings around account icons could be hidden. Just the icon would them be shown, with the little selection-idicator dot next to it.

I find them rather ugly, especially if the icon for the added app isn't circular (such as Google Keep, and in lesser extend Facebook Messenger which has a little point on the side).

Note: I searched the settings but couldn't find an option for it. Did I miss it, or is this not an option yet?

* Which version of Wavebox are you using? [e.g. 3.0.0]

3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]

Windows 10

**Comment by Thomas101** [comment]
Hi, there's nothing there are the moment to do this, but it's something we can add in. You can change the colour of the ring around your account, by right clicking on it and going to `Account Settings` and then pressing the `Account Colour` button under the appearance section.

I was going to suggest changing the opacity down to zero but this isn't working at the moment. This would also have the side-effect of removing the indicator dot too, which isn't quite what you want.

**Comment by TheOddler** [comment]
Thanks! I already found the colour, and was able to make the icons look satisfactory. However it's still not great for non-round icons, so the ability to remove the circle altogether would still be a good enhancement I think.

Thanks!

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which fixes this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. The option is near the top of your account settings and called `Show Account Colour around Icon`. Turning this off will remove the ring. Thanks!
