### ISSUE TITLE
Scrolling does not work on second monitor

### ISSUE THREAD

**Issue by davidkingham** [wavebox/waveboxapp#800]
* Wavebox Version: 4.1.0
* Operating System & Version: Win 10

**Expected & actual behavior**
Scrolling with the middle mouse wheel should scroll

**Steps to reproduce**
Place wavebox on second monitor

**Is the bug persistent or intermittent?**
Both. It seems to happen when the window loses focus and then you come back to wavebox

**Additional information**
I have tried to reproduce this in other programs but it only happens in wavebox

**Comment by nmat** [comment]
I have 2 monitors here and scrolling has never been a problem for me ever.

Is there a specific case that where middle mouse button does not work with scrolling? You can scroll with the page up and page down its just the mouse that does not work?

Also can you:
* Open run
* type: winver

and give the version of windows you are using exactly?

**Comment by nmat** [comment]
@davidkingham do you have a update here? I was wondering if you continue to have this problem and also if you might be able to send more information?

**Comment by davidkingham** [comment]
I did some further testing and it seems to only affect gmail. If I switch to another program and come back to wavebox I can no longer scroll and it only happens on the second monitor.

![image](https://user-images.githubusercontent.com/35718296/46425971-63020300-c6fa-11e8-8096-b3554f8d1bab.png)

**Comment by Thomas101** [comment]
I've been trying to reproduce this here but not had any success. Is there anything else about your setup that might help me reproduce? Things I'm thinking of are...
* Are you using a touchscreen device on one of your monitors
* Does plugging the second monitor in/out trigger this behaviour
* Do the monitors have different screens resolutions/density settings

**Comment by davidkingham** [comment]
I am using a laptop which has a touch screen, the second monitor is not
touch.
Plugging/unplugging has no effect.
The monitors do have different resolutions (3200x1800 and 1680x1050)

I actually can't get scrolling to work at all in gmail now

**Comment by GreyCorbin** [comment]
How is the monitor connected to the laptop?  (i.e. what connection is being used, cable type/length, etc.

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
