### ISSUE TITLE
Add support for Cirkus App

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#801]
* Wavebox Version: [e.g. 4.1.0]
* Operating System & Version: [Mac OSX 10.3.6]

**Is your feature request related to a problem? Please describe.**
No

**Is your feature request related to an account type?**
Cirkus App Account

**Describe the solution you'd like**
Will be great to add Cirkus Web App support
[](https://cirkus.com/)
[](https://cirkus.com/app/login)

**Additional info**
No

**Comment by Thomas101** [comment]
I've added Cirkus to the app store - let me know if you have any problems with it
