### ISSUE TITLE
Have a "Go to Default URL' menu item on app context menu

### ISSUE THREAD

**Issue by tnaseem** [wavebox/waveboxapp#806]
* Wavebox Version: 4.2.0
* Operating System & Version: All

**Is your feature request related to a problem? Please describe.**
When you don't have the navigation toolbar open (my preference for a cleaner look), sometimes you can get 'stuck' on a page without the ability to go back (greyed out at times), or go to the default URL.

Of course, this is the case for when you have the setting 'Restore last page on load' selected in the settings (again, a preference to go back to where you left off the last time!).

**Is your feature request related to an account type?**
No

**Describe the solution you'd like**
Have an extra item on the context menu for the App to load the Home/Default URL for the app. Bonus: a keyboard shortcut (Alt-Home - like in Chrome).

**Comment by nmat** [comment]
Do you have the option if you right click on the service -> Account Settings -> [service] -> Appearance -> Show Navigation toolbar

This option should be available on all services.

**Comment by tnaseem** [comment]
Yes, I understand that, but I thought it would be a good option to have a 'Home' menu option if you'd prefer not to have the navigation bar open.

For instance, I prefer not to have the navigation bar to give a cleaner (non-browserly!) look.

So, in my case, when I got 'stuck' on a page, I had to bring up the navigation bar, hit the 'Home' button and remove it again.

**Comment by Thomas101** [comment]
I thought there was a `Home` option in the context menu, but it seems to have disappeared. I'll pop it back in. Might  be room to put home in the right-click menu on the account icon too

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.3.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Just right-click anywhere in the page and pick home. Thanks

**Comment by tnaseem** [comment]
Again, many thanks. All good now!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
