### ISSUE TITLE
Grammarly 'Installation is complete' keeps popping up on subsequent restarts

### ISSUE THREAD

**Issue by tnaseem** [wavebox/waveboxapp#807]
* Wavebox Version: 4.2.0
* Operating System & Version: Windows 10

**Expected & actual behavior**
Once Grammarly has been installed and Wavebox restarted, I'd expect to see this window popup just the once (ie. after the first restart after installing the plugin).

**Steps to reproduce**
Install the Grammarly plugin
Restart Wavebox (New window opens with Grammarly's "Your Installation is Complete").
Quit Wavebox.
Restart Wavebox (Grammarly window opens again).
... etc.

**Is the bug persistent or intermittent?**
Always happens.

**Screenshots**
The new window that opens:

![snag_779fa07](https://user-images.githubusercontent.com/1317345/46073345-c4950f80-c1d8-11e8-9a5b-8ec2807483ea.png)

**Additional information**
Only noticed this happening once I uninstalled the plugins to test the other 'Download' issue, and reinstalled.

**Comment by tnaseem** [comment]
Further info: Uninstalling, restarting, and reinstalling Grammarly didn't fix the issue.

**Comment by Thomas101** [comment]
When you initially went through the reproduction steps did you start the app up, see the window, then quit pretty quickly afterwards? Chromium doesn't write to disk right away and sometimes a quick restart like that won't persist cookie info.

After the app's been running a while, if you restart the app does it still come up?

**Comment by tnaseem** [comment]
I thought you were onto something then, so I gave it another shot, but it still comes up each time I restart Wavebox. Steps were:

- Uninstall Grammarly.
- Restart Wavebox.
- Install Grammarly.
- Wait a few seconds then restart Wavebox.
- Grammarly's "Installation is complete" window pops up.
- Wait about a minute and then close the window.
- Quit Wavebox.
- Restarting Wavebox each time after that still brings up the "Installation is complete" Grammarly window.

> After the app's been running a while, if you restart the app does it still come up?

Yes.

**Comment by tnaseem** [comment]
Also worth noting is that this keeps popping up on subsequent restarts of Wavebox, when composing an email in Gmail, for instance:

![snag_fd77f17](https://user-images.githubusercontent.com/1317345/46182270-e5677d00-c31e-11e8-82fa-900e7a9e5121.png)

So, it seems as if Grammarly thinks it's *just* been installed each time I restart Wavebox.

**Comment by tnaseem** [comment]
Another update... It's no longer happening!

I rebooted the machine (normally, I put it to sleep) and I'm assuming that cleared something.

**Comment by Thomas101** [comment]
I wonder if this could be somehow related to the download problems you were having in #803. It's almost like something is failing to write to disk. Do you remember if this fixed itself around the same time? I suspect it's nothing to do with this, but have you got plenty of free disk space left on the machine?

**Comment by tnaseem** [comment]
Possible. But it was continuing to do this after the download issue fixed itself. The only thing I can think of that changed to stop this one was a reboot. But, then again, it could still be a similar problem.

Plenty of disk space (300GB) on the system (SSD) drive where I install my apps. I did check the permissions on the various folders too (in AppData..., Program Files, etc) as I have had the odd issue on my development folders in past, assuming it was that. But they all did come up writable, etc at the time.

I guess close this one for now too. If it happens again, I'll do some more tests this end (permissions, etc).

Many thanks for your perseverance!

**Comment by Thomas101** [comment]
It's a bit of a head-scratcher. Thanks for the heads up on the free-space at least we can rule that out :).

I'll close for now, but like I said in the other issue if it comes up again feel free to re-open
