### ISSUE TITLE
Links in Google Plus opens in Wavebox browser despite setting Default Browser as default

### ISSUE THREAD

**Issue by jake404** [wavebox/waveboxapp#808]
* Wavebox Version: 1.5.11
* Operating System & Version: Windows 10
* Account type (if applicable): Google Plus

**Expected & actual behavior**
I have set the account to open windows in the default browser, but it still opens links in the Wavebox browser. I don't have this issue with any other account.

**Steps to reproduce**
Setup a Google Plus account and click on a link in the feed.

**Is the bug persistent or intermittent?**
It's persistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/12189899/46074340-99ce9b00-c187-11e8-8386-df217d2459d0.png)

**Comment by nmat** [comment]
1.5.11 seems old. Can you try upgrading to version 4 and try again?

**Comment by jake404** [comment]
Sorry, I wrote the 'Wire Config Version'... Wavebox version is 4.2.0.§

**Comment by jake404** [comment]
I tried changing back an forth between default browser and wavebox browser. It doesn't help.

**Comment by nmat** [comment]
interesting....is there a specific type of link where you have issues with?

I mean is it a link that is located in a specific place inside google+ that can be tested with?

I had this problem before but after a bit of changing around I manage to go around it.

Also can you:

Win+R 

Type: winver

and paste the version of windows 10 you have?

**Comment by Thomas101** [comment]
Thanks, I know what this. Will put a patch in shortly.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.5.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
