### ISSUE TITLE
New messages in Hangouts doesn't produce 'unread' red badge or notification

### ISSUE THREAD

**Issue by damonmaria** [wavebox/waveboxapp#81]
When a new message arrives in Hangouts I hear the standard Hangouts notification noise (if I have sound turned on) but Wavebox does not get the red 'unread' badge on the dock icon, the menu bar icon, or produce a MacOS notification. Hence, it's very easy for me to miss Hangouts messages. 

* Which version of Wavebox are you using: 3.1.5
* Which Operating System are you using: MacOS 10.12.4

**Comment by Thomas101** [comment]
Thanks, we need to add a bit more integration to hangouts to support this but will look at adding it in

**Comment by luisfpg** [comment]
Yes, this would be nice.
I was evaluating replacing the hangouts Chrome extension by Wavebox, but without being notified of new incoming messages, it is not really viable for full-time use.
Subscribing.

**Comment by danives3d** [comment]
I moved to using wavebox to try and contain all my work items together, but am finding the lack of hangout notification is hampering me and I might have to go back to another 3rd party service - so this would be amazing if it could be implemented.

**Comment by psywolf85** [comment]
Same here. Hangout is very important..

**Comment by nlenkowski** [comment]
+1 for this. No hangouts notifications have caused me to miss incoming messages a number of times!

**Comment by eitch** [comment]
Is there any news on this issue? I just installed wavebox after having used wmail for a while and this is really important for me too.

**Comment by dougborland** [comment]
I'm on the 14-day wavebox trial and I'm liking it. However, the lack of hangout notification is likely to prevent me adopting it full time. It would be great if this feature were added or a timeline shared as to when it's likely to be implemented

**Comment by eitch** [comment]
My 14-day trial is about to run out and i haven't had a comment on this issue. This feature is required for me to subscribe.

**Comment by danives3d** [comment]
Theres been no update on this, or any indication of them doing this, for 5 months now. I've stopped using it as such.

**Comment by Thomas101** [comment]
Hi we've just added some improved support for Google Hangouts to the latest beta (3.3.4). There's some information on how to switch to the beta channel and download the latest version [here].

If you'd like us to extend your trial so you can give it a try,
* Make sure you're signed into your Wavebox account by opening settings and then clicking the Wavebox tab. If you're signed in, your email address will be in the top right
* Send a message to [support](https://wavebox.io/support) with the email address you're signed in with and link to this issue.

Thanks

**Comment by damonmaria** [comment]
I tried the beta and tested it. The notification and badge correctly appeared, and the conversation was opened in Hangouts. However, I closed the conversation (without clicking within it) so in the list of conversations on the left it was still in bold. Now clicking on that conversation in the list will not open it. Clicking any other conversation does open them. Navigated elsewhere in the app and came back, still wouldn't open. Refreshed and then it did work. 

I know this isn't original issue (notifications are working). Should this move to a new one?

**Comment by Thomas101** [comment]
@damonmaria it could have been an issue with hangouts itself. If you try it again does it still happen? If so, open-up a new issue and we'll go from there

**Comment by damonmaria** [comment]
It didn't happen a second time.

**Comment by cainadai** [comment]
I'm finding this to still be an issue in the Hangouts app (Wavebox 3.7.0). Notification sounds will play (if enabled in Hangouts) but I'm not getting any desktop notifications or the red circle on the app icon or dock icon. (OS: High Sierra)
