### ISSUE TITLE
Log into LastPass by clicking the LastPass icon on the toolbar

### ISSUE THREAD

**Issue by tnaseem** [wavebox/waveboxapp#811]
* Wavebox Version: 4.2.0
* Operating System & Version: All

**Is your feature request related to a problem? Please describe.**
No

**Is your feature request related to an account type?**
No

**Describe the solution you'd like**
It would be a good idea to allow users to click the LastPass icon to log into and bring up the LastPass options. At the moment, to log into LastPass you have to go via the context menu on a page and to get to the Options, you have to back to Settings/Extensions.

Maybe just bring up the LastPass menu, like in Chrome? (see screenshots)...

**Additional info**

Click this...
![snag_d3c42c6](https://user-images.githubusercontent.com/1317345/46147481-b539c300-c2b9-11e8-8313-8e5fcb71952e.png)

to bring up this (if not logged in)...
![snag_d431154](https://user-images.githubusercontent.com/1317345/46147624-1e213b00-c2ba-11e8-8510-25848336a80e.png)

or this (if logged in)...
![snag_d3bad2d](https://user-images.githubusercontent.com/1317345/46147508-c387df00-c2b9-11e8-8180-54653c1ca108.png)

(You must be getting sick of all my 'issues' by now! sorry!)

**Comment by Thomas101** [comment]
It should bring up the popover as you screenshotted. I wonder if this is related to something else reported earlier.

Have you got "Show Titlebar" disabled under Settings > User Interface? When the Titlebar is hidden I think the drag handler is gobbling the click events.

**Comment by tnaseem** [comment]
Ah! yes I have. So, the button only responds to click events when the title bar is enabled. Grammarly button now works too.

The tooltips, showing the extension name, also come up now, which they didn't before (rollover event, I guess).

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.3.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by tnaseem** [comment]
Brilliant. It's clickable in Windows now. Many thanks :)
