### ISSUE TITLE
Please add the GitKraken Glo to appStore

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#814]
Please add web based app **GitGraken Glo** to AppStore.
https://app.gitkraken.com/glo/

TY :)
And have a good weekend ;)

**Comment by nmat** [comment]
Hello,

If possible you can add this request to: https://github.com/wavebox/waveboxapp/issues/130

All the requested services are sent there. :)

**Comment by Thomas101** [comment]
Whoops, sorry forgot to reply to this yesterday! It's been added to the store :-)
