### ISSUE TITLE
Wavebox not showing that it's running in Ubuntu 18.04

### ISSUE THREAD

**Issue by GreyCorbin** [wavebox/waveboxapp#815]
* Wavebox Version: Version 4.1.0
* Operating System & Version: Ubuntu 18.04.1 LTS
* (Linux only) Install method: Snap Package Refresh
* Account type (if applicable): NA

**Expected & actual behavior**
When a program is running with any windows open, there are dots (orange in my case) below the icon for each window open.  Wavebox is not doing this.

**Steps to reproduce**
Run Wavebox on Ubuntu 18.04.1 LTS.

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**

![image](https://user-images.githubusercontent.com/40442120/46229862-e054fe80-c31b-11e8-8319-a3c8325c4897.png)

**Additional information**
None.

**Comment by GreyCorbin** [comment]
NOT a bug.  After posting, it dawned on me that I was suppose to have been updated to 4.2.0.
I tried the refresh again and was told that no new version was available.  I right clicked on the icon and choose to quit.  Opened the program again and now it is showing the correct version and the window indicators are working as expected.

**Comment by tesquin** [comment]
@GreyCorbin : What do you mean by "tried the refresh again?" Is that a snap command or something else?

I'm having the same problem. (Observation: This seems to happen with a few apps I've installed via snapd, but it's chronic in this particular case.)
