### ISSUE TITLE
Checkbox disappears when clicked

### ISSUE THREAD

**Issue by rhuss** [wavebox/waveboxapp#817]
* Wavebox Version: 4.3.0
* Operating System & Version: macOS Mojave
* Account type (if applicable): Octobox but I suspect any webapp with checkboxes

Unchecked: 

![image](https://user-images.githubusercontent.com/99080/46294941-35507900-c597-11e8-83e1-a17aeb70f0cd.png)

Checking some boxes:

![image](https://user-images.githubusercontent.com/99080/46294964-41d4d180-c597-11e8-9dfe-6fb57b121867.png)

If used directly in Chrome or Firefox, the checkbox stays:

![image](https://user-images.githubusercontent.com/99080/46295016-62049080-c597-11e8-96a0-3b5304528c96.png)

**Expected & actual behavior**
When selecting a checkbox it should stay and show the checkbox as it does when used within a browser.

**Steps to reproduce**

Just use an Octobox account and use checkboxes

**Is the bug persistent or intermittent?**

Persistent bug

**Comment by Thomas101** [comment]
Thanks for reporting. There's a fix ready for the next version.

In the meantime, if you're finding it troublesome there are two that temporarily remidy it...
1. Zoom the tab in or out slightly via <kbd>cmd</kbd>+<kbd>+</kbd> or <kbd>cmd</kbd>+<kbd>-</kbd>
2. Go to Settings > Advanced, turn off `Enable Sandboxing` and restart

**Comment by rhuss** [comment]
Thanks for the heads up ! I can live with the workaround and looking forward to the next release.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.3.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by rhuss** [comment]
Yeah, thanks ! Works for me now like a charm (sorry for coming to so late)
