### ISSUE TITLE
Accents in dictionary "Español (Colombia)" handled incorrectly

### ISSUE THREAD

**Issue by jmfederico** [wavebox/waveboxapp#818]
* Wavebox Version: 4.3.0
* Operating System & Version: macOS 10.14

**Expected & actual behavior**
The spellchecker for "Español (Colombia)" is not working correctly with accented words.

**Steps to reproduce**
- Install dictionary "Español (Colombia)"
- Compose a new email with Gmail
- Write the word "Información" (note the accent on the o)
- It will mark is as an error
- Check for correct spelling

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
<img width="491" alt="screen shot 2018-10-01 at 09 53 03" src="https://user-images.githubusercontent.com/237977/46296587-4c27a900-c560-11e8-9c7a-f55158b8424f.png">

**Comment by Thomas101** [comment]
Hi, thanks for reporting. It looks like the en_CO dictionaries have an encoding issue on them. I've updated them to a newer version that fixes this, but unfortunately, you'll need to download them manually. To do that...
1. Quit Wavebox completely
2. Download both replacement dictionary files... [index.aff](https://waveboxio.com/dl/dictionaries/es_CO/index.aff) and [index.dic](https://waveboxio.com/dl/dictionaries/es_CO/index.aff)
3. Rename them to be the country code (en_CO)...
    * `index.aff` -> `en_CO.aff`
    * `index.dic` -> `en_CO.dic`
4. Open `~/Library/Application\ Support/wavebox/user_dictionaries/`
5. Replace the `es_CO.aff` and `es_CO.dic` with the two you've downloaded
6. Relaunch Wavebox and give "Información" another try

Is that any better?

**Comment by jmfederico** [comment]
Working now!

Thanks
