### ISSUE TITLE
Error connecting to OneDrive cloud file picker

### ISSUE THREAD

**Issue by phileasb** [wavebox/waveboxapp#819]
* Wavebox Version: 4.3.0
* Operating System & Version: Mac OSX 10.14 (French)
* Account type: Task & Project Management services (Azendoo, Asana, etc...)

**Expected & actual behavior**
When using the "OneDrive" option to attach a file, file picker popup ends on an error message "Too much authentication attempts. Try again later."

**Steps to reproduce**
Azendoo > Subject > Task > Attach file > OneDrive
Asana > Project > Task > Attach file > OneDrive

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
![capture d ecran 2018-10-01 a 17 25 11](https://user-images.githubusercontent.com/14050580/46298948-9fb9e700-c5a0-11e8-992f-4b22fbeb18e2.png)

**Additional information**
No problem to connect to Onedrive as an independant account.

**Comment by Thomas101** [comment]
Thanks I'll take a look at what's happening here

**Comment by Thomas101** [comment]
Hi, I've just given this a try with the latest version of Wavebox (4.8.0) and Asana and it seems to work, so I'll close this off. If you're still seeing the problem though, let me know and we'll take another look. Thanks!

**Comment by phileasb** [comment]
I confirm it works.
Thanks!
