### ISSUE TITLE
Mac - Accounts -> Next Service menu & shortcut do not work 

### ISSUE THREAD

**Issue by madorb** [wavebox/waveboxapp#820]
* Wavebox Version: 4.3.0
* Operating System & Version: macOS 10.13.6
* Account type (if applicable): Gmail

**Expected & actual behavior**
When I click Account->Next Service (or use keyboard shortcut) I expect it to change to the next service (in my case i have calendar, drive, sheets, docs, sheets services in my menu).

In actuality it does not do anything. If I click the menu button, nothing happens. If i type the keyboard shortcut the menu entry quickly flashes as if to indicate that it's been invoked, but it does not actually do anything. 

The Account->Previous Service and it's corresponding shortcut work as expected. 

**Steps to reproduce**
Attempt to use Account->Next Service

**Is the bug persistent or intermittent?**
Persistent - it never works

**Comment by nmat** [comment]
Are you having more then 1 service enabled in wavebox?

You have 2 different levels of services:
* Services
* Indexed services

So lets say you add gmail with all the underlaying apps in the same service. Then for example gmail inbox is in indexed service 1 and next in indexed service 2. So then you need to use a different type of command to change service for the indexed service.

Therefore I am wondering what more you have added since that command is for main services and not for indexed services.

**Comment by nmat** [comment]
![image](https://user-images.githubusercontent.com/383031/46472327-1e9b6380-c7dd-11e8-99d9-ff83216637b3.png)

Example image above shows where "Accounts" are located in interface and where "Indexed Services" are located.

So they are separated.

**Comment by nmat** [comment]
What happens if you change the keybinding for: *Keyboard Shortcuts - Account* -> Service at Index to lets say Cmd+Shift+1 or something. Does that make the change work with the shortcut?

**Comment by nmat** [comment]
Also please note that a service can overwrite the keyboard shortcuts so it might be something to that part also.

**Comment by madorb** [comment]
@nmat 

The `Service at Index` shortcut works as appropriate, and continues to work if i change it to `Cmd+Shift+Number` (at least Cmd+Shift+1 and 2 work, the rest are macos native shortcuts for screen capture :-) ). 


I did briefly think that it could possibly be that the keyboard shortcut were being overridden. Though the fact that the `Accounts` menu actively blinks when I type the shortcut - leads me to believe that it's being correctly identified by Wavebox, just not correctly executed

**Comment by madorb** [comment]
Hopefully this gif should explain the behaviour I'm seeing - though this uses the menu buttons directly and not the shortcut - but in any case, it doesn't work :-)

![2018-10-04 07 52 47](https://user-images.githubusercontent.com/823868/46475398-0ad70980-c7ab-11e8-970c-f84f3a50e3a5.gif)

**Comment by Thomas101** [comment]
That looks like a bug there. I'm guessing previous works ;-)

Fixed in https://github.com/wavebox/waveboxapp/commit/f6d52bff6a6844f22e810fa297d67748bcca772f 

Thanks!

**Comment by madorb** [comment]
Yep, previous is just fine :-) Thanks for the quick fix!

**Comment by Thomas101** [comment]
Fix should go into the beta channel at end of this week or beginning of next :)

**Comment by madorb** [comment]
Oops, i meant to write it here, but accidentally did it on the commit itself which may not give notification - but I have a question about the fix: https://github.com/wavebox/waveboxapp/commit/f6d52bff6a6844f22e810fa297d67748bcca772f

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.3.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by madorb** [comment]
Yep, works as expected! Thanks so much!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
