### ISSUE TITLE
Chrome Dark Reader extension for Wavebox

### ISSUE THREAD

**Issue by redfellow** [wavebox/waveboxapp#821]
**Describe the solution you'd like**
It would be awesome if Wavebox supported using https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en

This way we wouldn't necessarily have to apply custom CSS for each service in order to get them to support dark modes (for the ones that lack native support for it, that is).

**Comment by Ash258** [comment]
#138
