### ISSUE TITLE
UI freezes after suspending

### ISSUE THREAD

**Issue by sztomi** [wavebox/waveboxapp#823]
* Wavebox Version: 4.3.0
* Operating System & Version: Linux Mint 19
* (Linux only) Install method: Snap
* Account type (if applicable):  n.a.

**Expected & actual behavior**
Actual: When I suspend and resume my PC, the Wavebox window no longer updates. It seems to be still running: I get notification sounds etc. The system tray icon works. But the only way to recover is to close the window and exit via the system tray, then restart Wavebox.

Expected: After suspending and resuming my PC, Wavebox continues to function as before.

**Steps to reproduce**
1. Suspend my PC. 
2. Resume my PC.

**Is the bug persistent or intermittent?**

It's not 100%, but like 98% of the time. I think it has to do with the way my PC handles suspending.

**Screenshots**
There is nothing special, the UI just appears to be completely frozen.

**Comment by Thomas101** [comment]
Just as a hunch, I wonder if this could be down the snap packaging. It could be some of the snap apis failing with Mint for some reason.

Would you be able to give a quick test, with say the tar distribution from our [download page](https://wavebox.io/download)? Once extracted, quit your current install and run `sh wavebox.sh` to start the app and try suspeding & resuming to see if it crashes.

Just as a side note, your accounts wont be pulled across from the snap install because it sandboxes the data seperately.

**Comment by sztomi** [comment]
Sorry for the super late answer. I switched to the dpkg a couple of days ago, but I'm still experiencing the freeze. I'll try the test you suggested and let you know.

**Comment by Thomas101** [comment]
Thanks. I wonder if the upcoming chromium upgrade will help with this then. I'll drop you a note when the next beta comes out - will definitely be worth trying that

**Comment by logankoester** [comment]
I'm not sure yet whether it's related to suspend (it may be), but I am also experiencing long frozen UI incidents after Wavebox has been open for a few hours, since the last month or so. I measured my Wavebox uptime in days+ before this began occurring, and now I have to xkill it at least once a day.

**Comment by Thomas101** [comment]
@logankoester which linux dist and install method are you using?

**Comment by logankoester** [comment]
Thanks for getting back to me (and all your hard work) @Thomas101! I'm on Arch Linux using this package: https://aur.archlinux.org/packages/wavebox-bin/

This script explains the details: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wavebox-bin

**Comment by sztomi** [comment]
@Thomas101 I was able to make it freeze from the tarball package as well. Also, lately I'm having a similar issue with vscode and the devs are also hoping to resolve that via an electron upgrade: https://github.com/Microsoft/vscode/issues/60467

Holding out for a beta build then.

**Comment by Thomas101** [comment]
We should be shipping an updated electron upgrade this week on our beta channel. I'll pop a message on when this is released

**Comment by Thomas101** [comment]
Hi, we’ve just released an updated version of electron to the beta channel of Wavebox in version 4.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by logankoester** [comment]
Same, this feels way better so far. Haven't seen the freezing issue yet.
Will update if it occurs.

**Comment by sztomi** [comment]
I haven't experienced any freezing or slowdowns and overall everything seems much smoother and faster with the beta build. I specifically looked out for situations when earlier it would have frozen.

**Comment by logankoester** [comment]
Same here @sztomi, haven't had a freeze yet, and definitely would have hit it by now (several times) in the previous release. I think we're good here!

**Comment by Thomas101** [comment]
Thanks for the feedback everyone! Great to hear :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
