### ISSUE TITLE
Wavebox not processing links

### ISSUE THREAD

**Issue by CheechGe** [wavebox/waveboxapp#827]
* Wavebox Version: [e.g. 3.0.0]
4.3.1
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
WIndows 10
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]
Various

**Expected & actual behavior**
Some information about what you expect to happen and what actually happens.

The links in emails and the ones in the Wavebox Help functions (Github, Support, ...) are not handled.  Clicking on them does not open in a browser.  I tested the email using a different PC with Thunderbird and the same browser with the same email and the link worked.  I had to open this issue by going to Github directly from the browser instead of through the Wavebox Help.

**Steps to reproduce**
Are there any steps that we can take to reproduce the bug?
![wavebox_05](https://user-images.githubusercontent.com/3653639/46829588-2bcfc980-cd6c-11e8-8e0c-c24cb7f8f627.png)

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?
Reported this after the last update. Had rebooted the PC after the update.  Will try again after another reboot.

**Screenshots**
Screenshots often help us narrow down a bug more easily.

Attached

**Additional information**

**Comment by nmat** [comment]
Just tested to open the link and it works here.

What browser are you using as standrad browser?

**Comment by nmat** [comment]
I am using windows 10 and chrome and can't reproduce it right now.

**Comment by CheechGe** [comment]
I've been using Vivaldi for about a year now and was using it when I first
got Wavebox and it worked fine until this latest upgrade.   I just tested
it again and everything works fine now.  Can figure that one out although I
did do a reboot last night.  I'll close this out.  Thanks for testing.
