### ISSUE TITLE
Wavebox becomes slow over time to a point of not being usable.

### ISSUE THREAD

**Issue by corpetty** [wavebox/waveboxapp#832]
* Wavebox Version: 4.4.0
* Operating System & Version: Ubuntu 18.04.1 LTS (awesome window manager)
* (Linux only) Install method: Snap
* Account type (if applicable):Google Inbox and all services (x6), slack (x5), github, evernote, telegram, private email

**Expected behavior:**
regular performance over time

**Actual behavior:**
Severe degradation of app performance over time

**Steps to reproduce**
Start the app, wait

**Is the bug persistent or intermittent?**
Multiple times a day, every day. 

**Additional information**
I've tried every combination of advanced settings possible.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. Is this something new with a recent version or have you always seen this?

My suspicion is that memory could be growing somewhere, hence the reason it gets slow. If you go to `Settings` > `Debug` and click the `Task Manager` button it will bring up a window with some info about which process is using what resources. Would you be able to screenshot that shortly after launch (when performance is as expected) and then later on (when performance has degraded). Feel free to blank out any emails etc.

**Comment by GreyCorbin** [comment]
I couldn't leave it on over the weekend with 4.0.0 on Ubuntu or I would come back to a bricked machine.  I never reported it when I found it as you were about to do a release, so I figured that I would see if it went away and it did when I went to 4.3.0.  (I never tested it in the release before 4.3.0)

Hope that isn't back in 4.4.0.

**Comment by nmat** [comment]
I am a bit worried that snap package is the main cause here. Can you test to use the debian main package also to see if the same effects happens there?

**Comment by corpetty** [comment]
@nmat I have deleted the snap and installed the deb package as per the instructions on the website.  Seems fine for now, but I've also turned off all sleeping, as that is the only thing that seems to be making a difference. I'll slowly start to re-enable over time to see if I experience degraded performance.

**Comment by nmat** [comment]
Sounds good. Please come back with result since its easier to error search. I know there are options to debug snap packages also. That could help if you are indeed in 100% need to use snap packages.

**Comment by nmat** [comment]
@corpetty have you noticed any difference in the deb package compared to the snap package?

**Comment by corpetty** [comment]
So far it has worked smoothly, and I've slept a quite a few of the services I'm using within Wavebox.  Still curious why the snap misbehaves so much in comparison to .deb install.

**Comment by nmat** [comment]
@corpetty do you use any other snap package that is running fine? I mean if compared to wavebox?

**Comment by Thomas101** [comment]
It sounds like it could be down to the snap packaging then.

When you bundle an app up as a Snap package, you bundle all the dependencies it needs along with it (rather than using those installed on the system) and it sandboxes the install using app-armour. There are some edge cases that mean Snap integrations work less well with those install libraries on the machine.

Am I okay to close this as the deb version doesn't have the same problem?

**Comment by corpetty** [comment]
yeah, you can close this, I've had great performance since installing the deb.  I'll keep that in mind if I run into other performance issues across other snaps, but as for now, they all work as intended.  

Thanks for following up and asking.
