### ISSUE TITLE
Ctrl+N in office365 and gmail asks for new mail (continues loop) all the time (does not create compose window)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#833]
* Wavebox Version: 4.4.0
* Operating System & Version: windows 10
* Account type (if applicable): Office365

**Expected & actual behavior**
Only ask for new mail compose 1 time. if using gmail and office365 in the same client.

When clicking on Ctrl+N wavebox it continues asking for new mail select if you choose office365 account.

**Steps to reproduce**
1. Start office365 and also gmail in same wavebox window
2. Keybinding in office365 (gmail keybindings)
3. Ctrl+N (select the office365 account)

No new mail is created with compose window. Only infinite loop to ask for new mail and choose account.

**Is the bug persistent or intermittent?**
Persistent

**Comment by nmat** [comment]
This seems to be a case only when outlook is being set to use the gmail keybindings.

Compose from for example Wavebox mini does ask and create a new mail as intended for both instances of the services. So using wavebox mini and pressing -> compose -> [choose account] works fine.

Using outlook standard keybinding and pressing Ctrl+N in outlook does however not ask for account to compose mail in. So that explains a bit. Not sure what happens here really.

**Comment by Thomas101** [comment]
Thanks, I'll take a look. This could be because we're not accounting for the case where outlook uses the gmail keybindings

**Comment by nmat** [comment]
Testing this today. It seems that:

if you have office selected - New mail is created in background and Wavebox is also showing account to which to create new mail on. Does not close popup on creating the new mail.

if gmail is selected - Ctrl+N asks for account to create new mail, clicking on office365 account creates new mail in background but does not close the popup of new mail creation.

**Comment by Thomas101** [comment]
@nmat I've had a look at this, and you're right it gets itself into a loop. Looking at what we can do, there's now url support for composing messages which gets around different keyboard shortcut configs.

The downside to this is running the url is like opening a compose box in a new window - so it doesn't add most of the UI. It doesn't really make sense to open that up in the main window, so it's going to have to be in a popup window.

ba0ea8f adds this behaviour, give it a go and see what you think :)

**Comment by nmat** [comment]
I tested this function now and the loop is gone.

I believe though the thing you mentioned with the popup might confuse a bit. I got redirected to a microsoft site that only gave me information but the compose was also created directly in outlook.

So the result is now:
* No loop
* Popup window occurs with a microsoft url (for me at least that is only random information)
* New compose is auto created when inside outlook and no account is choosen before hand

The problem here I think it might be the api for outlook or office 365 how to handle this type of case. :/

**Comment by Thomas101** [comment]
> I got redirected to a microsoft site that only gave me information but the compose was also created directly in outlook.

Can you send some screenshots of these?

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nmat** [comment]
Feedback:

Outside of office 365 (outlook):
* Result: Opens a new window with a new compose message

Inside of office 365 (outlook):
* Result: Creates background new compose and also a new window compose message

So....result is...better and no loop in the create new message.

**Comment by Thomas101** [comment]
Awesome! Should I try to block the compose message command when in outlook so we always open in a new window? My gut feel is no as it's more convenient opening up in the running tab :-/

**Comment by nmat** [comment]
I think that the behavior should be same as gmail if applicable. If not then keep 1 and not the other.

having 2 compose windows does confuse things and you expect one or the other. This is basically up to what can be accomplished I think based on API and functionality for opening mail.

IMO if it is possible that Chrome can fetch Ctrl+N to start a compose without open a popup then I think it would be possible for wavebox also. (though it might be down to electron or nodejs more?) 

Or am I thinking wrong here?

**Comment by nmat** [comment]
Favorite would be:

* Open in tab - Choice to open in window

If that is not possible

open only in single window I guess.

**Comment by Thomas101** [comment]
After looking into this, it's a bit fraught trying to block and capture the Ctrl+N shortcut that Outlook listens to. Sometimes we can capture it correctly and other times not. For the best non-broken behaviour we're going to stick with the current behaviour - at least compose always opens something that allows you to compose :)

Thanks @nmat  :)
