### ISSUE TITLE
Wavebox - git master - cursor is not showing in electron3 (google keep)

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#835]
* Wavebox Version: git master 2018-10-25
* Operating System & Version: Windows 10 and MacOS Mojave
* Account type (if applicable): google keep (only place tested)

**Expected & actual behavior**
Show cursor like stable wavebox.

The cursor is invisible.

**Steps to reproduce**
Edit/Add a item in google keep. (there can be other places where same thing happens)
Try to navigate or type in the note. (looks like the cursor is there but invisible)

**Is the bug persistent or intermittent?**
Persistent. Tested on stable and works fine but master does not show it where it is electron3.

**Additional information**
This can be something in electron but I am not sure.

**Comment by Thomas101** [comment]
Thanks, I did see something one a machine here but could only reproduce on that. I'll have a look to see if I can get to the bottom of it

**Comment by nmat** [comment]
Tested on windows 10 and now the cursor is showing correctly. thank you!

**Comment by Thomas101** [comment]
That's just gone into beta. Thanks @nmat :)
