### ISSUE TITLE
Bug? Re-Authentication each 1-2 days for Inbox App 

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#836]
* Wavebox Version: [e.g. 4.4.0]
* Operating System & Version: [e.g. Mac OSX 10.14]
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Inbox by Gmail, etc...]

**Expected & actual behavior**
The Inbox App by Gmail ask reAuth every 1-2 days. Only on Mac(on Linux works well)

**Steps to reproduce**
Have no idea.. it hapened multiple times in week, and for some reason only on Inbox, the gDrive, gPhotos and other GoogleApps works ok in same time then Inbox ask reAuth account.

**Is the bug persistent or intermittent?**
each 1 or 2 days

**Screenshots**
<img width="680" alt="wavebox - inbox 2018-10-26 14-02-21" src="https://user-images.githubusercontent.com/9933516/47565480-ddecc100-d928-11e8-8277-005e55c48e17.png">

**Additional information**
Not sure perhaps cache issue of Wavebox?
Issue comes in last update.

**Comment by reatlat** [comment]
![screencast 2018-10-29 18-13-17](https://user-images.githubusercontent.com/9933516/47667568-98d5c280-dba6-11e8-8cb6-ba65539c16f5.gif)

Any chance to solve it from my side?
or issue related to InboxApp only?

**Comment by nmat** [comment]
I have never encountered this on my machines at home.

Are you using some kind of vpn or give a bit more information on the setup for communication?

**Comment by reatlat** [comment]
@nmat regular normal internet(home Fibra600 WiFi 5G) connection, all Google services works fine, only Inbox by gMail have auth problems

And this is weird, BCS when I add Inbox I automatically get all Google services, all connected ok, but the only InboxApp sometimes ask me to give Gmail permissions for WaveBox.

I think Issue on Inbox integration with WaveBox or maybe my cache...

**Comment by Thomas101** [comment]
Wavebox picks that state up if Google throws back an invalid_grant error.

If you're still seeing it, try going to Account Settings, then under Credentials remove the Google credentials. Once done, it will prompt you to sign back in, follow those steps and see if helps

**Comment by reatlat** [comment]
@Thomas101 your solution not helped :/
I just have this problem again,
In this time, to solve issue I tried another way, I remove WaveBox auth from my Google account to give fresh permissions for WaveBox, perhaps it help me :/

**Comment by Thomas101** [comment]
Thanks for the update - that will help us if other users have a similar issue.

Seeing that removing and re-adding worked, it sounds like some kind of issue on Google's end. We'll keep monitoring to see if this comes up again. If it breaks again for you, just recomment/reopen this issue and we'll try a few other things. Thanks!

**Comment by reatlat** [comment]
@Thomas101 Still happened for me,
I already tried to remove google accounts from Wavebox, remove wavebox from authorized apps from Google Accounts, add accounts to wavebox again. and it's still happened for me for all Inbox accounts :( 
and this happened only with Inbox Tab, the googleDrive, googlePhotos, etc works correct :/

**Comment by Thomas101** [comment]
Darn, I thought we had this then. Is this a personal account (e.g. @gmail.com) or a corporate account (e.g. @mycompany.com)?

I'd be hesitant to remove the working version on your Linux machine, but if you add the account a second time on that machine does it stay logged in or kick you out as it does on your Mac?

Probably the final thing to do, is see exactly which call is failing and what Google is throwing back. If you open the Wavebox developer tools with CMD+ALT+J, click on the console tab and keep that open. Once the account shows up as needing authentication, switch back to the console window and I imagine there would be a red failed http call towards Google, probably with a 401 or 403 status.

Clicking on this should give some more info, such as the URL it called out to and you should be able to grab the response details from there. Any info from this would be helpful in tracking it down.

**Comment by reatlat** [comment]
<img width="658" alt="wavebox noreplay_email gmail com inbox" src="https://user-images.githubusercontent.com/9933516/48445625-4a741680-e797-11e8-8366-a0cf00bdaec1.png">
Not sure it's releated to problem but console shown me this errors!

BTW: I already tried to remove all accounts from Wavebox and add it again, problems still come :(

I will keep monitoring console, and send error log then the problem comes again.
@Thomas101 do you need error log in txt file?

**Comment by reatlat** [comment]
So, I got error today :)
Looks like error come after deep sleep my mac(after more 5h closed laptop) 

The error comes only on Inbox accounts :(
Today I recive notification about Inbox project, Google close Inbox project in March 2019, in this case, I swipe to gMail, perhaps issue exactly with inbox.team :/

<img width="664" alt="wavebox xxxxxxx gmail com inbox xxxxxxx gmail com 2018-11-14 12-15-25" src="https://user-images.githubusercontent.com/9933516/48480583-3ff36480-e80b-11e8-940d-2e55266d1bc8.png">

<img width="739" alt="wavebox xxxxxxxxx gmail com inbox xxxxxxxxxx gmail com 2018-11-14 12-17-30" src="https://user-images.githubusercontent.com/9933516/48480636-63b6aa80-e80b-11e8-9281-5d25b189e499.png">

<img width="652" alt="wavebox xxxxxxxxxxx gmail com inbox xxxxxxxxxxxxx gmail com 2018-11-14 12-19-28" src="https://user-images.githubusercontent.com/9933516/48480653-6e713f80-e80b-11e8-9635-d08d528e468c.png">

<img width="743" alt="wavebox ssssssssslack gmail com inbox xxxxxxxxxxxxx gmail com 2018-11-14 12-20-34" src="https://user-images.githubusercontent.com/9933516/48480664-74ffb700-e80b-11e8-9f12-710dfcc7f7dc.png">

**Comment by reatlat** [comment]
Still same issue with GMail also :/

**Comment by reatlat** [comment]
@Thomas101 
This bug happened always after deep suspend on my MacBook (more 5h)

Already tried:
- totally remove WaveBox with all cache
- remove Wavebox from authorized apps from Google account
- switch from Inbox to classic GMail 

Not tried yet:
- deactivate extensions
  - Gemelius
  - Grammarly
  - Mardown

**Comment by Thomas101** [comment]
Thanks for sending those across.

The `webview.capturePage` calls just can be generated when suspending an account. These take a screenshot of the last page before suspending, so it can be shown when the tab is woken back up. When a machine is under load or there' a particularly complex page to capture these can take longer than we like, so there's a bit of code in there to make sure we don't take forever.

From the http responses you've sent, it does look like Google is rejecting the auth token, so from our side the need to re-authenticate the account is valid, so the thing to look at is why it's rejecting the token.

I can't see it being anything with extensions or anything like that as it's happening outside of the actual tab, in our sync code. After a little bit of discussion here, we're starting to think it could be something to do with the connection that's causing Google to reject a token for some reason...

* You said it works fine on your linux machine, is this on the same network or a different one?
* Are you using anything like a proxy server or VPN?
* You also mentioned a cache futher up too, are you using any kind of caching server or just wondering if it's a cache of something?

**Comment by Thomas101** [comment]
Great! Thanks for the update. If you start to see the issue again, just re-open this and we can see if there's anything else we can do :-)
