### ISSUE TITLE
Microsoft Teams – unread icon is hiding

### ISSUE THREAD

**Issue by NullpointerForever** [wavebox/waveboxapp#837]
* Wavebox Version: 4.4.0
* Operating System & Version: Windows 10
* Account type (if applicable): Office 365

**Expected & actual behavior**
Unread red mini icon on Teams tab is hiding without switching to Teams services.

**Steps to reproduce**

1. I have in my account two services – MS Teams and Outlook (Office 365). 
2. Click on MS Teams tab to switch view. 
3. Write in chat to someone. 
4. Click on Outlook tab to switch view. 
5. There is a new message to me in MS Teams tab. On the Teams tab icon there is a red mini icon with counter of unread messages. I'm still on Outlook tab. 
6. Click on close icon. Wavebox is minimized to tray. 
7. Double click on tray icon to showing up Wavebox. Red mini icon from MS Teams is gone.

**Is the bug persistent or intermittent?**
Always happen

**Comment by Thomas101** [comment]
Hi, do you have the Teams tabs setup to sleep or is it always running? When you click the close icon have you got Wavebox setup to quit immediately, or does it continue to run in the tray? (For example, if it's setup to quit completely it will take a little bit of time to start back up).

**Comment by NullpointerForever** [comment]
Teams is always running. Close icon does not close Wavebox - it continue to run in the tray.

**Comment by Thomas101** [comment]
@NullpointerForever I'm struggling to reproduce this, are you still seeing it? If so, would you be able to send some screenshots along with the steps - just in case I'm missing something when reproducing here

**Comment by NullpointerForever** [comment]
Sure. I'm on Outlook tab:
![wavebox_02](https://user-images.githubusercontent.com/16589346/48762898-576b9b00-ecac-11e8-9b25-d6c2b21f94f0.png)
Some message from MS Teams has arrive:
![wavebox_01](https://user-images.githubusercontent.com/16589346/48762972-83871c00-ecac-11e8-85d2-f8dbb1a66ba6.png)
Now, I'm click on close button:
![wavebox_04](https://user-images.githubusercontent.com/16589346/48763035-a1ed1780-ecac-11e8-8964-82663ec76d2d.png)
Wavebox is hiding to a tray (is not on a taskbar - only in a tray):
![wavebox_03](https://user-images.githubusercontent.com/16589346/48763114-c943e480-ecac-11e8-838e-d5719287208f.png)
After click on a tray icon:
![wavebox_02](https://user-images.githubusercontent.com/16589346/48762898-576b9b00-ecac-11e8-9b25-d6c2b21f94f0.png)

**Comment by Thomas101** [comment]
Thanks, still having some trouble reproducing this here.

* Do you have teams open anywhere else?
* Do you have teams installed on your mobile device?
* After clicking on the tray icon to restore the window, does this stay at `1` or revert to the tick?
* If you click on the teams tab, does the number ever return or is it permanently gone?

**Comment by NullpointerForever** [comment]
> * Do you have teams open anywhere else?

No. Only in Wavebox.
> * Do you have teams installed on your mobile device?

Yes, on my Windows Phone. But after uninstalling it there is still a problem.
> * After clicking on the tray icon to restore the window, does this stay at `1` or revert to the tick?

I see 1 but after about 1-2 seconds it is gone.
> * If you click on the teams tab, does the number ever return or is it permanently gone?

Permanently gone.

I noticed that after minimizing Wavebox to taskbar (insted to tray) that unread icon is stay - it's working correctly. And that problem exists when message from Teams arrive from person that is current selected. For example:
1. On Teams chat there is Person 1 and Person 2. 
2. Selected is Person 1. Message arrive from Person 1 - problem exists.
3. Selected is Person 2. Message arrive from Person 1 - there is no problem.

**Comment by Thomas101** [comment]
It sounds like there's a specific configuration that causes this, I suspect with the tray behaviour.

* If you go Settings, would you be able to send me a screenshot of the tray section?
* Then if you right click on the running Wavebox Window in the taskbar, does it say `Pin to taskbar` or `Unpin from taskbar`?

Thanks

**Comment by NullpointerForever** [comment]
> * If you go Settings, would you be able to send me a screenshot of the tray section?

![wavebox_01](https://user-images.githubusercontent.com/16589346/48995434-1f4ed700-f148-11e8-8141-94ff755f1ca3.png)

> * Then if you right click on the running Wavebox Window in the taskbar, does it say `Pin to taskbar` or `Unpin from taskbar`?

`Pin to taskbar`

**Comment by NullpointerForever** [comment]
After installing a newest version 4.4.2beta I didn't noticed my problem. Thanks for help.

**Comment by Thomas101** [comment]
I haven't put a fix in for it on beta - but could be down the chromium upgrade etc.

Let me know if it comes up again. I've still been having trouble reproducing it on 4.4.0 to get to the bottom of it.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
