### ISSUE TITLE
Feature request: Support Flowdock

### ISSUE THREAD

**Issue by TomBaxter** [wavebox/waveboxapp#84]
Unified notifications for Gmail, Slack, and Flowdock would have me living the dream. I understand this isn't very likely, but never hurts to ask. Enjoying Wavebox, thanks.

**Comment by Thomas101** [comment]
Thanks, we'll take a look!

**Comment by Thomas101** [comment]
Hi, we're collapsing all the new Account/Service requests into a single issue so we can keep track of them more closely. You can find and continue tracking progress from #130. Thanks
