### ISSUE TITLE
When Mojave turns to Dark Mode, the menubar icon doesn't automatically invert its colors

### ISSUE THREAD

**Issue by Evertt** [wavebox/waveboxapp#840]
* Wavebox Version: 4.4.0
* Operating System & Version: macOS 10.14

**Expected behavior**
When I turn on dark mode in Mojave, all the icons in the menubar invert their colors. I would expect Wavebox to do the same.

**Actual behavior**
Wavebox's icon stays black with a transparent background, which essentially makes it invisible.

**Steps to reproduce**
Just turn on Dark Mode

**Is the bug persistent or intermittent?**
Always

**Screenshots**
![image](https://user-images.githubusercontent.com/1267282/47845221-bd0eea80-ddc4-11e8-8223-a949ec9de7fa.png)
![image](https://user-images.githubusercontent.com/1267282/47845277-e2035d80-ddc4-11e8-8175-14e04ab35b9c.png)

**Comment by Thomas101** [comment]
Thanks, the next beta release has some additional fixes for Mojave, but this one is still to be resolved.

**Comment by Evertt** [comment]
To me it's not a feature, because I have an app running that automatically changes my OS from light mode to dark mode and back twice a day. And I don't want to have to manually change the icon twice a day...

**Comment by reatlat** [comment]
> To me it's not a feature, because I have an app running that automatically changes my OS from light mode to dark mode and back twice a day. And I don't want to have to manually change the icon twice a day...

temporary solution: use neutral color like grey #CCCCCC

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
If you have changed the tray icon colors, you will need to reset them back to their defaults for the app to auto change them. To do this head into `Settings` > `Tray` and under the colorpicker click the reset buttons.

![screenshot 2018-11-23 at 10 14 23](https://user-images.githubusercontent.com/103586/48938284-b0d00600-ef08-11e8-8122-bf446a3fad7a.png)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
