### ISSUE TITLE
No print option on right click on filled form on web

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#842]
* Wavebox Version: 4.4.0
* Operating System & Version: OSX 10.14

**Expected & actual behavior**
Right click should present an option to print a page. However none was given.

**Additional information**
I dont know if I got unlucky with the form I filled but there was no way to print the filled form as there was no option available to do it. Opening the page with the browser resulted in the empty form to be opened in the browser, which meant I would have had to refill all the info once again. I ended up taking  a screenshot and printing that one, which is kind of ridiculous. Pls fix it. After years we're still having troubles printing stuff, I find it ridiculous. 
The link is here but I am not sure it helps: https://crm.ttlry.fi/ttlkotisivupalvelut/tutkintotilaisuus_tuloste.aspx?id=753

**Comment by nmat** [comment]
Are you trying to send a page "with forms filled in" to the default browser like chrome?

Or what exactly is the problem here so I can test it.

**Comment by Tahini-123** [comment]
Well I tried to send the filled-in form to Chrome just as a workaround, since no print option was available in the right-click menu in the Wavebox window. 
I see you have made a commit about it, so this is supposedly fixed by now?

**Comment by nmat** [comment]
The fix to show the print option in the right click menu is in GIT. I tested it yesterday and got the options to be able for printing to a printer, pdf etc.

So the option will be available in the next beta release for you to test. This will however not send the form data from wavebox -> default browser if that is what you are looking for. Does the print dialog fill the need you are looking for?

**Comment by Tahini-123** [comment]
No, sending data to the browser is not was I was looking for. I want to be able to handle the pages in Wavebox, without having to have to send them to the browser. The print dialog is 100% what I needed, thanks for taking action about it.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
