### ISSUE TITLE
Always start minimized not working

### ISSUE THREAD

**Issue by Jonatino** [wavebox/waveboxapp#843]
* Wavebox Version: [e.g. 3.0.0] 4.4.0
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10] Windows 10
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...]

**Expected & actual behavior**
Expected: Should not see wavebox window during startup
Actual: Wavebox window shows up on startup and never minimizes 

**Steps to reproduce**
Turn on always start minimized, restart computer on windows 10.

**Is the bug persistent or intermittent?**
Happens every time

**Screenshots**
As you can see, its passing the --hidden parameter but its still showing the window
https://dl.dropboxusercontent.com/s/56shj5omqp3nrvg/explorer_2018-11-02_02-53-13.png

video of the issue happening

https://dl.dropboxusercontent.com/s/zw7si9nnrifz1aw/2018-11-02_02-55-48.mp4

**Comment by Jonatino** [comment]
Update: It seems like it only happens if the last time you close the wavebox window it was maximized

https://dl.dropboxusercontent.com/s/9afhy3cadio7t0b/2018-11-02_02-57-53.mp4

**Comment by Thomas101** [comment]
Nice find on the maximized-case. I'll take a look to see why hidden is ignored in this case!

**Comment by sudoyang** [comment]
Same issue happens to me too.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
