### ISSUE TITLE
Mail attachments are not moved to Google Drive

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#844]
Wavebox Version: 4.4.0
Operating System & Version: OSX 10.14

**Expected & actual behavior**
Expected: Attachments get moved to Google Drive. 
Actual behaviour: upload indicator keeps on turning forever. Nothing gets moved 

**Steps to reproduce**
Any attachment would produce the same result.

**Is the bug persistent or intermittent?**
Persistent, 100% repro

**Additional information**
It has to do with Gapps Gmail (the one I am using in at my workplace), my private one is working ok.

**Comment by nmat** [comment]
Could you let me know how you are trying to save the attachments? Can try to reproduce it here.

**Comment by Tahini-123** [comment]
Hi,
by clicking the small drive icon that is next to the attachment in the email. 

I have to specify the following:

1) It is actually Google Drive File Stream, not 'simple' Google Drive
2) the issues started to appear when IT department in my workplace implemented a spam check in our GApps' Gmail. However the save-attachment-to-Drive feature works normally in Chrome, so I am inclined to think it has something to do with Wavebox. 
I will post here some documentation as soon as I get it from IT.

**Comment by Tahini-123** [comment]
Hey guess what, now it is working again. Not sure if something has changed or it was just a temporary issue on Google's side. I will close this bug report.

**Comment by Tahini-123** [comment]
Cannot repro anymore. Closing.
