### ISSUE TITLE
Links in Android Messages Always Open in Wavebox Browser

### ISSUE THREAD

**Issue by Jonatino** [wavebox/waveboxapp#845]
* Wavebox Version: [e.g. 3.0.0] 4.4.0
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10] Windows 10
* (Linux only) Install method: [e.g. Debian installer, Snap Package, Tar, Apt-Repo, etc...]
* Account type (if applicable): [e.g. Gmail, Office 365, Trello, etc...] Android Messages

**Expected & actual behavior**
Expected: Wavebox will open in default browser if that's the setting, or wavebox browser if that's the setting

Actual: Wavebox will always open in wavebox browser for links inside of android messages

**Steps to reproduce**
Receive link in Android Messages and click on it. It will open in wavebox browser

**Is the bug persistent or intermittent?**
Always happens

**Comment by Jonatino** [comment]
Think you're missing window opening rules for `http(s)\\://messages.android.com(/*)` to be `DEFAULT`

Right now its falling back to the about\\:blank rule in fallbackConfig.js ({ url: 'about\\:blank', mode: 'POPUP_CONTENT' },`

**Comment by Thomas101** [comment]
Thanks. It looks like it needs the `window.open` call patching in a similar way to what we do with gmail too. I'll have a look to see if I can get this into the next release

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.5.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
