### ISSUE TITLE
Search Google for ... Always Opens System Default Browser

### ISSUE THREAD

**Issue by animally** [wavebox/waveboxapp#848]
* Wavebox Version: 4.4.0
* Operating System & Version: Mac OSX 10.14.1
* Account type (if applicable): Any, but Gmail for this example

**Expected & actual behavior**
I have my gmail account setup to use the wavebox browser for links, which works fine.  When I select some text in the body of the email, right-click and select Search Google it always opens in the system default browser.  My expectation is it should honor the selected browser set for the account, which in my case is the wavebox browser.

**Steps to reproduce**
Setup an account in wavebox to use the wavebox browser for links.  In that same account, view an item like normal (e.g., email message) and in the content viewer select some text, then right-click on the selection and do Search Google for.

**Is the bug persistent or intermittent?**
Always

**Screenshots**
N/A

**Additional information**
N/A

**Comment by Thomas101** [comment]
That's an interesting one that's not come up before. It makes sense though. I'll see if I can add it into the next beta!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Once updated, head to `Settings` > `Advanced` and change the `Search Provider` to `Google - Opens in Wavebox`

![screenshot 2018-11-23 at 10 12 26](https://user-images.githubusercontent.com/103586/48938187-5fc01200-ef08-11e8-87ed-40c5ebeff0e6.png)

Thanks

**Comment by animally** [comment]
Works as expected now, but the beta has broken the Lastpass extension.  When the extension is trying to fill a field, the OS pinwheels on my mac and then wavebox crashes.

**Comment by Thomas101** [comment]
@animally can you give a bit more info? For example which site/url you're trying to autofill. How have you triggered the autofill (e.g. just automatically on load, or by clicking the button in the form field, etc...)

**Comment by animally** [comment]
This is totally strange as it was working fine when you made the request for more information 2 days ago.  Now this morning, it is happening again.  I simply login to Lastpass, go to one of the accounts I've setup (in this case it is a zimbra email account) in Wavebox, click on the Lastpass icon, go to Show Matching Sites, and select the appropriate entry for fill.  Nothing happens in the fields, then I get the pinwheel, and eventually Wavebox crashes.

Should I open a different issue or continue in this one?

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
