### ISSUE TITLE
Feature: Allow other Google services to be the "default service" instead of Inbox.

### ISSUE THREAD

**Issue by AustP** [wavebox/waveboxapp#85]
* Which version of Wavebox are you using? [e.g. 3.0.0]
3.1.5

* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Ubuntu 16.04

I use Google Hangouts way more than I use Google Inbox. I have multiple accounts in Wavebox so when I get a new Hangouts message, I hit Ctrl+1 to switch to my Google account and then Ctrl+Alt+2 (very awkward) to switch to Hangouts. It would be nice if I could make Hangouts my default google account service since 99% of the time I'm going to my Google account is to access Hangouts. That way a simple Ctrl+1 would take me straight to hangouts and when I'm done, I hit Ctrl+2 to switch back to Slack.

**Comment by Thomas101** [comment]
Thanks, I think a few users have requested something similar, so we're going to look at shifting these around a bit

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 3.14.8. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks
