### ISSUE TITLE
Screen sharing doesn't work in meet.google.com

### ISSUE THREAD

**Issue by zaro** [wavebox/waveboxapp#850]
* Wavebox Version:4.4.0
* Operating System & Version: Ubuntu 18.10
* (Linux only) Install method: deb package
* Account type (if applicable): GSuite

**Expected & actual behavior**
When joining a meeting via meet.google.com I expect to be able to share my screen. 

**Steps to reproduce**
Join any meeting on meet.google.com , and click Present button. Instead of sharing the screen as it would in Chrome or Firefox it just pops up a message 'Your browser can't share your screen'.

**Is the bug persistent or intermittent?**
Persistent.

**Comment by Thomas101** [comment]
Thanks for taking the time to report, I'm merging this issue and a few others which report the same into #912 so we can track progress there and hopefully add support in. Thanks!
