### ISSUE TITLE
[Feature Request]  Password security for shared computers

### ISSUE THREAD

**Issue by 97watt** [wavebox/waveboxapp#852]
Wavebox provides full access to many accounts in one place. In cases where you have shared computers, close work environments or just general privacy concerns its important that there is some security. Adding a optional password, PIN, windows hello on launch, when maximized, when system comes out of standby/sleep would prevent unwanted access.

I've noticed that other similar apps (although limited in other ways compared to Wavebox) have implemented one or more of the above.  This would be an important security feature to add.

**Comment by nmat** [comment]
Same as? https://github.com/wavebox/waveboxapp/issues/716

**Comment by 97watt** [comment]
#716 - same request. I hope this will be added soon. Thanks
