### ISSUE TITLE
Huge cache size

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#853]
* Wavebox Version: [e.g. 4.4.0]
* Operating System & Version: [Mac OSX 10.14.1]

**Expected & actual behavior**
Huge cache size, almost 4Gb is ok?

**Screenshots**
<img width="1018" alt="app uninstaller 2018-11-15 19-43-36" src="https://user-images.githubusercontent.com/9933516/48574373-4cf97c00-e90f-11e8-98dc-81e57af31e2a.png">

**Comment by Thomas101** [comment]
4GB does seem on the large size. Try going to Settings, then `Data & Sync`. Double click `Clean expired accounts`. Wait a few minutes and then re-check the folder size in Application Support.

What's the size of it after that? If it's still around 4GB, how many accounts do you have down the sidebar in Wavebox?

**Comment by reatlat** [comment]
@Thomas101 I think it's solved.. but cache grow... for half month I already have 1.2Gb

**Comment by reatlat** [comment]
22 App (7 slack teams)

**Comment by Thomas101** [comment]
I'm going to close this off for now, but if you're seeing the cache directory growing again, feel free to re-comment or open another issue I'll take another look :)

Thanks!
