### ISSUE TITLE
Notification sounds not coming in for Gmail, chat, or Calendar

### ISSUE THREAD

**Issue by kcinman11358** [wavebox/waveboxapp#856]
* Wavebox Version: 4.4.4
* Operating System & Version: Windows 10

* Account type (if applicable): Work Gmail and Work Calendar (if that matters)

**Expected & actual behavior**
I am trying to get notifications to show. My company moved to gmail, so having a desktop client like this would be awesome. But I need to get the desktop notifications working. The general --> test notifications works
![image](https://user-images.githubusercontent.com/7409848/48792255-6a389c80-ecb9-11e8-8e23-94652c68a82a.png)

The test notification under the accounts also works
![image](https://user-images.githubusercontent.com/7409848/48792328-96541d80-ecb9-11e8-9d9a-5c3d51968c67.png)

However, I am still not getting any actual notifications. I am seeing this in this in the gmail desktop notifications
![image](https://user-images.githubusercontent.com/7409848/48792371-b7b50980-ecb9-11e8-9933-6fa8556afd93.png)

**Steps to reproduce**
I enabled everything i could find and still not working

**Is the bug persistent or intermittent?**
It happens always with real notifications from gmail and calendar

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**

**Comment by kcinman11358** [comment]
After more testing, I was able to use my personal account fine on the same computer. This appears to be impacting my work account only.

**Comment by Thomas101** [comment]
Are you seeing the unread badge next to your account icon in the sidebar?

It could be that the unread mode that's set in Wavebox doesn't match that of what you're using in Gmail. There are some [steps here to try that might help](https://wavebox.io/kb/google-unread-counts).

**Comment by kcinman11358** [comment]
This article solved it
https://wavebox.io/kb/google-unread-counts--

Setting it to match what i have configured was the issue!

Can't wait to tell my coworkers about this! Thank you

**Comment by kcinman11358** [comment]
Closing
