### ISSUE TITLE
Translate option in the context menu doesn't work

### ISSUE THREAD

**Issue by zaro** [wavebox/waveboxapp#857]
* Wavebox Version: 4.4.0
* Operating System & Version: Ubuntu 18.10
* (Linux only) Install method: .deb
* Account type (if applicable): any

**Expected & actual behavior**
I expect when selecting text on any app, right click and then select the option 'Translate ...', to see translation of the text. What opens is empty google translate page, with no text inside.

**Steps to reproduce**
Select some text in any app, right click and choose translate option.

**Is the bug persistent or intermittent?**
Happens every time.

**Screenshots**
Screenshots often help us narrow down a bug more easily.
![screenshot from 2018-11-21 09-49-24](https://user-images.githubusercontent.com/135646/48826620-784af380-ed73-11e8-919a-b7001a698435.png)
![screenshot from 2018-11-21 09-53-47](https://user-images.githubusercontent.com/135646/48826628-7c771100-ed73-11e8-9802-48967767f53b.png)

**Additional information**

**Comment by Thomas101** [comment]
Thanks, fix will be out shortly

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.4.2. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
