### ISSUE TITLE
Small issues with Todoist web app

### ISSUE THREAD

**Issue by rfgamaral** [wavebox/waveboxapp#864]
* Wavebox Version: 4.4.0
* Operating System & Version: Windows 10
* Account type (if applicable): Todoist

I've found two issues related to Todoist service in Wavebox:

**1)**
![image](https://user-images.githubusercontent.com/96476/49296924-6115af80-f4b1-11e8-9d0d-c5e42b9fd9bb.png)
![image](https://user-images.githubusercontent.com/96476/49296958-71c62580-f4b1-11e8-8106-2dcd56a28768.png)

Can you spot the difference? The "plus" icon does not show properly on the top screenshot (Wavebox) compared to the bottom screenshot (Chrome Canary).

The button still works, it's a minor issue.

**2)**
![image](https://user-images.githubusercontent.com/96476/49297010-9f12d380-f4b1-11e8-9779-d2e725366855.png)

Opening the "Settings" option opens the settings page (https://todoist.com/prefs/account) and then tere's a "Close" button available which should return the user to the default page (https://todoist.com/app#start) but what happens is that the current page (the settings) is refreshed. Force reloading Todoist service, gets me back to the start app page (but this is a workaround).

**Comment by Thomas101** [comment]
Looks like a rendering glitch with Chromium. I've just given it a try with the beta channel of Wavebox which uses an updated version of Chromium and it appears to render fine there. There should be a fix out to stable shortly :)

Thanks

**Comment by rfgamaral** [comment]
Great, I'll wait for the stable version then :)

Thanks.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by rfgamaral** [comment]
You're working fast, I just updated to the latest beta because of the CSS changes and now I'm updating to the latest stable 😆 

Thanks :)
