### ISSUE TITLE
Feature Request: Add timer setting of when tooltip popout should occur

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#869]
* Wavebox Version: 4.4.3beta
* Operating System & Version: windows 10

**Describe the solution you'd like**
Tooltip with the new features that are released in this beta is really nice. The ability to set how long until the popout should show would also be good to make it more specific for the user. However default can be what is being set now.

Is this possible?

**Comment by Thomas101** [comment]
We did discuss and play about with this quite a bit but weren't sure on the best thing to do. Originally we had no timeout but they got in the way of day-to-day use. This is what we settled on for this beta...

* Show after 750ms unless I was open in the last 1500ms
* Show on click if I'm already the active service/tab
* Hide on click if I'm already open
* Hide as soon as I leave the tooltip

...adding a configurable wait is easy, but I wonder if the current defaults that we have are okay or a bit wonky?

**Comment by nmat** [comment]
That actually makes sense. I did not know of the click and click actions. Might be that I have to play around with it a bit more. Maybe its because I always look at _other_ services to determine quick switch of task and therefore feel that the time might be off a bit?

Also need to think a little extra here I believe.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
