### ISSUE TITLE
Windows 32bit binary missing

### ISSUE THREAD

**Issue by Ash258** [wavebox/waveboxapp#871]
Since Wavebox 4.4.2 beta, there are no binaries for 32bit version.

Do you plan to add them or only support 64bit version for future releases?

![Proof](https://i.imgur.com/pMqSy73.png)

**Comment by Thomas101** [comment]
We're hoping to move over to just 64-bit having seen quite a big drop in 32-bit users over the last year.  Are you using 64-bit Windows and running the 32-bit version of Wavebox? If you still need a 32-bit version drop support [at] wavebox.io a message and we'll try and help

**Comment by Ash258** [comment]
I use 64bit version, but i maintain custom [package for command line installing](https://github.com/Ash258/scoop-Ash258/blob/master/Wavebox.json), where I keep both versions, and just want to know, if i's bug or intended behavior.

Thank you.

**Comment by Ash258** [comment]
I got response from all users / developers, who use Wavebox, and they use only 64bit versions. So going with only 64bit version is fine (at least for me) 🙂. 

Keep up the good work 🎉
