### ISSUE TITLE
App Copy/Paste functionality not working

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#872]
* Wavebox Version: [e.g. 4.5.0]
* Operating System & Version: [MacOS 10.14.1]

**Expected & actual behavior**
Key chain copy/paste function not working

**Steps to reproduce**
Open Kaychain > Add new password > try to paste password

**Screenshots**
<img width="921" alt="wavebox keychain 2018-12-05 03-34-37" src="https://user-images.githubusercontent.com/9933516/49486526-18f2e600-f83f-11e8-9d53-6cc598697810.png">

**Comment by reatlat** [comment]
Just found... all Copy/Paste functionality (in App)  not working.
Looks like App no have access to the clipboard. (MacOSX Mojave)

**Comment by Thomas101** [comment]
👍 I'm seeing the same behaviour in the keychain window - I'll get a fix in for that.

It seems to be working everywhere else for me though. I must be doing something differently...
* How are you trying to toggle copy/paste - keyboard shortcut, right click, or top edit menu?
* Do you just have the main Wavebox window open, or are there other Wavebox windows (e.g. keychain) in the background?
* Sounds daft, but does a restart make it work?

**Comment by Thomas101** [comment]
Awesome that's a great help! Should be a fresh release with a few bug fixes over the next couple of days :)

**Comment by bessonette** [comment]
Same issue here as well. For now I'm just typing something like "test" in the Wavebox Keychain window and then using Mac's Keychain Access app to replace it with the longer and more complex passwords.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.3). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by reatlat** [comment]
@Thomas101 TY
*release 4.5.3* shortcuts works
But the right click for open context menu still not working

**Comment by Thomas101** [comment]
@reatlat I've added that into 4.5.4 :)
