### ISSUE TITLE
Increase "custom CSS" window width and height

### ISSUE THREAD

**Issue by rfgamaral** [wavebox/waveboxapp#873]
Simple feature request to make the custom CSS window larger, both in width and height. I'm making some heavy tweaks to my Wavebox look and feel and that tiny window is getting in the way 😆 

As a bonus: https://github.com/JedWatson/react-codemirror 😄

**Comment by rfgamaral** [comment]
![image](https://user-images.githubusercontent.com/96476/49526862-9f8fdd80-f8a8-11e8-88f1-94f1b056097f.png)

This is sooooooo much better. A thousand thanks :)

Found one slight bug though... Opening the CSS/JS editor, typing something, clicking `Cancel` and then reopening the editor again, shows the previous content (it shouldn't since I pressed `Cancel` and not `Save`). It's a slight but because if you click `Cancel` and then close the settings dialog window and go back to the same CSS/JS editor, the content will be gone (it's only there when you cancel and reopen the window immediately).

**Comment by Thomas101** [comment]
Thanks - fixed that :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.5.3). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
