### ISSUE TITLE
Zoom Extension Does Not Allow Company in Link

### ISSUE THREAD

**Issue by collinjlesko** [wavebox/waveboxapp#875]
* Wavebox Version: 4.5.0
* Operating System & Version: Windows 10

**Is your feature request related to a problem? Please describe.**
Zoom link does not allow editing, therefore we cannot add my company name such as "company.zoom.us"

**Is your feature request related to an account type?**
Zoom

**Describe the solution you'd like**
edit link in extension. Will look to edit it myself and update.

**Additional info**
Any other information or screenshots that might help us.
<img width="665" alt="waveboxzoom" src="https://user-images.githubusercontent.com/24938979/49525909-c20c0180-f87c-11e8-91ed-d92a7efba5ab.png">

**Comment by Thomas101** [comment]
If you've got a zoom account with a custom domain, have you tried adding it using the `Add any website` button on the add screen? This will allow you to set the url :)

**Comment by collinjlesko** [comment]
I did, and I totally understand your solution. I guess I was under the impression that the app would help me get chats into WaveBox, however Zoom doesn't have a web interface for that.

Thanks again.
