### ISSUE TITLE
[Bug] - Zendesk - Does not keep the [team] in the url saved on page load

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#876]
* Wavebox Version: 4.5.0
* Operating System & Version: windows 10
* Account type (if applicable): Zendesk

**Expected & actual behavior**
Load last known page or at least the team that has been added for the url. 

Right now I have to fill in the team everytime on wavebox start. (opening url for the team does however load the url + login just fine. Its the first url that is not saved on first start)

**Is the bug persistent or intermittent?**
Persistent.

**Additional information**
Only tested in zendesk. Like I said some form of cache is being done since I do not have to login but I have to tell the service what team to use.

**Comment by Thomas101** [comment]
Thanks @nmat. I've updated the store entry to require the subdomain. You'll need to remove the account you've currently added and create a new one though.
