### ISSUE TITLE
Services Menu Not Functioning Correctly and Not in Right Order

### ISSUE THREAD

**Issue by zyigo** [wavebox/waveboxapp#877]
Version 4.5.0
Windows 10
Todoist, Gmail, Google Inbox etc.

**Expected & actual behavior**
Clicking on the services menu currently does nothing. It does not take the user to the services section of the account settings. It is also in the wrong order (seen in the screenshot - Services is not between Appearance and Credentials.)

**Steps to reproduce**
Open account settings and scroll around and attempt to click the services button.

**Is the bug persistent or intermittent?**
Persistant bug.

**Currently**
![inkedannotation 2018-12-07 154329_li](https://user-images.githubusercontent.com/2831291/49628550-dac11680-fa38-11e8-89f8-ece5032bed27.jpg)

**Possibly Improved**
![inkedbetter_li](https://user-images.githubusercontent.com/2831291/49628575-0217e380-fa39-11e8-867b-198e5a803189.jpg)

**Additional information**
The moving of the services header should probably scroll to the add new service section and also act as a heading for the sub-services in the menu, as shown above in the possible improved image.

**Note**
This possibly links to issue #173, but it is still an issue as of 4.5.0

**Comment by Thomas101** [comment]
Thanks, I've just released a fix for this to 4.5.3. Thanks!
