### ISSUE TITLE
Can't set secondary spell-checker language

### ISSUE THREAD

**Issue by oleynikandrey** [wavebox/waveboxapp#88]
I'm trying to set secondary spell-checker language in Wavebox 1.3.5, but it is disabled.
OS: Windows 10 x64

![image](https://cloud.githubusercontent.com/assets/1157958/25119763/1d0e356e-2424-11e7-9be0-28f7d235d4bb.png)

**Comment by nipnull** [comment]
Yeah, i found this problem in WMail some time before. @Thomas101, is it possible to get 2 dfifferent languages in spell-checker?

Versions: a lot of WMail and Wavebox, include last stable.
OS: Win7x64, Debian Stretch (9)

**Comment by Thomas101** [comment]
Hi, unfortunately this is down to a limitation in chromium. Both languages need to use the same character sets and as English uses Latin and Russian uses Cyrillic it means they're not compatible. You can mix, for example English & French or Russian & Bulgarian.

I will add some explanation in on the settings screen as it's not clear at the moment

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which has some explanation about why some languages are incompatible with others. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks for the feedback!
