### ISSUE TITLE
Wavebox UI completely fubar on Macbook Pro 2013

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#881]
* Wavebox Version: [e.g. 4.5.3]
* Operating System & Version: [Mac OSX 10.11.6]

Graphic chipset: Intel Iris Pro 1536 MB

Wavebox is completely unusable in this state. Reinstalling doesn't help. 

Notice that on OSX Mojave on a newer Mac (late 2016) it works fine. 

<img width="1387" alt="screen shot 2018-12-10 at 09 14 58" src="https://user-images.githubusercontent.com/26086997/49716473-88603f80-fc5c-11e8-87c5-2f214cce2b4b.png">

**Comment by Thomas101** [comment]
Hi, it looks a compatibility issue with the version of newer version of chromium that Wavebox uses and that version of macOS alongside the mac setup. Can you give the following a try...
1. Quit Wavebox
2. Open Terminal.app
3. Type or paste the following `open -b io.wavebox.wavebox --args --disable-gpu` to start Wavebox without GPU acceleration
4. The app should launch without the graphical glitches.
5. If this does launch the app go to Settings > Advanced and disable the `Hardware Acceleration` Setting
6. Restart the app once more

Hopefully this should remove the glitching. We're working on a more permanent fix

**Comment by Tahini-123** [comment]
Worked like a charm! 
Thanks a lot :)

**Comment by Tahini-123** [comment]
Should I close this bug or leave it as it is?

**Comment by Thomas101** [comment]
Thanks, I'll keep this open for now and see if there's anything we can do to fix this without needing to disable hw acceleration

**Comment by Thomas101** [comment]
Hi @Tahini-123 we've just released a new beta version (4.7.11) of Wavebox which includes an updated version of Chromium. It would be good to know if this fixes the issue for you without needing to disable hardware acceleration. If you're happy to give it a try there's some more info on how to use [beta channel here](https://wavebox.io/kb/beta-channel). Thanks!

**Comment by Thomas101** [comment]
This should be properly fixed in the latest version of Wavebox 4.8.0 with hardware acceleration enabled. Thanks for reporting!
