### ISSUE TITLE
Cmd-Q does not work on Wavebox 4.5.4 (Mac)

### ISSUE THREAD

**Issue by jdickey** [wavebox/waveboxapp#882]
* Wavebox Version: **4.5.4**
* Operating System & Version: **Mac OS X 10.13.6**
* (Linux only) Install method: **N/A**
* Account type (if applicable): **N/A**

**Expected & actual behavior**

*Actual behaviour:* When WaveBox is open as the current app (as shown by the app name in the menu bar), pressing the **Cmd + Q** key combination does not close the application, regardless of which account is in view (WhatsApp, Messenger, Gitter, Skype, Slack). The Dock must be used to close the app.

*Expected behaviour:* Pressing the **Cmd + Q** key combination closes the app. This was the actual behaviour prior to Wavebox Version 4.5.4.

**Steps to reproduce**

1. Open the app and wait for the default/first account window to display properly.
2. Hold down the **Command** key and press the **Q** key.
3. Notice that the _Wavebox_ menu in the menu bar flashes, indicating that the command shortcut was recognised, but no other change is visible. The app and account window are unaffected.

**Is the bug persistent or intermittent?**
Absolutely consistent.

**Screenshots**
Should not be necessaruy.

**Additional information**
Again, this was not observed before installing Version 4.5.4 in place of 4.5.3. Reinstalling the app, even after completely blowing the existing installation away with [AppCleaner](https://freemacsoft.net/appcleaner/) has no effect.

**Comment by Thomas101** [comment]
Thanks for reporting. I've just put a fix out for this in version 4.5.5 which you can get by going to the  menu, `Wavebox` > `Check for Update`
