### ISSUE TITLE
Office365: Outlook notification & badge icon are not showing anything when a new email comes.

### ISSUE THREAD

**Issue by gecharita** [wavebox/waveboxapp#883]
* Wavebox Version: [4.5.5-1]
* Operating System & Version: [Linux Mint  18.3, Cinnamon 3.6.7, 64-bit]
* Install method: [Apt-Repo]
* Account type : [Office 365]

**Expected & actual behavior**
When a new email comes, a notification must be shown & badge icon should display the number of unread items. Currently, nothing happens

**Steps to reproduce**
Reproducable every time a new email comes.

**Is the bug persistent or intermittent?**
Always

**Comment by Thomas101** [comment]
Hi, thanks for reporting. The first thing to check is what the `Unread Mode` is set to in Wavebox. Can you give the following a try... https://wavebox.io/kb/microsoft-unread-counts

If that doesn't help, does right clicking on the account in the sidebar and then picking `Resync` show an unread dot or still nothing?

**Comment by gecharita** [comment]
Hi there,
I have tried both the *Unread Mode* and *Unread Focused Mode *and I have
*resynced* the account too.
Unfortunately, no notifications or change to the badge icons occurs.

**Comment by Thomas101** [comment]
Thanks, has your icon been synced into the sidebar etc? I'm wondering if sync has failed for some reason.

There might be some additional logging info in the console. Can you give the following a try...
* Restart the app
* Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> to open the Dev tools and then click the console tab
* Right click on the account and press resync

Do you get any errors or warnings come up?

**Comment by gecharita** [comment]
I am getting **400** error (Bad Request) 
`mailboxes.js:12 POST https://login.microsoftonline.com/common/oauth2/v2.0/token`

Please, see the attached log file.
[-1545039504267.log](https://github.com/wavebox/waveboxapp/files/2685358/-1545039504267.log)

**Comment by gecharita** [comment]
I **deleted** the account & added it again. The same happens. There is also another error that has to do with CORS filter I suppose.

Please, see the log file/request.
[console-log-cors-17-12-2018.txt](https://github.com/wavebox/waveboxapp/files/2685861/console-log-cors-17-12-2018.txt)

**Comment by Thomas101** [comment]
Thanks. It’s weird I can’t seem to reproduce this in any which way here. Both on office365 accounts and personal accounts. As it’s coming back with a CORS error though, we’ve been thinking that running the web requests from the main thread may help rather than the renderer thread as we’re doing now.

I’ve just pushed a beta out (v4.5.6) which has an option to change this behaviour. If you want to give it a try…

1. Switch the beta-channel if you're not using it already. [More info](https://wavebox.io/kb/beta-channel)
2. Go to Settings > Advanced, and enable `Experimental Microsoft Account HTTP stack`
3. Restart the app & re-add the account to see if that works

**Comment by gecharita** [comment]
Now, notifications seem to work, although I am getting the same errors in the console.
Thank you for your time! :)

**Comment by Thomas101** [comment]
That's really great to know! We'll do some more testing and look at making this the default stack if it seems to help.

As for the errors in the console, all http errors are logged out, but the code can chose to handle these or not. At a guess, is it the `https://graph.microsoft.com/v1.0/me/drive` call that still fails?

**Comment by gecharita** [comment]
Indeed, you are right. ` https://graph.microsoft.com/v1.0/me/drive` fails.
