### ISSUE TITLE
Unable to use phone for 2-step Verification

### ISSUE THREAD

**Issue by aksh1618** [wavebox/waveboxapp#887]
* Wavebox Version: 4.5.5 (Shouldn't this be in Help -> About ?)
* Operating System & Version: Arch Linux
* Install method: AUR
* Account type (if applicable): Gmail

**Expected & actual behavior**
I want to sign into a google account with 2-step Verificationusing my phone, but the option doesn't seem to be working with Wavebox.

**Steps to reproduce**
Enable 2-step Verification for your Google account and choose the "pressing 'Yes' on your phone" option.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![deepinscreenshot_select-area_20181217232921](https://user-images.githubusercontent.com/26065812/50105745-a24ce400-0253-11e9-95a0-cb3e5055664e.png)

**Additional information**
Both the options are available if I try signing in from Chrome. I tried setting the user agent to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36`, but that didn't work.

**Comment by aksh1618** [comment]
Ok, just realized the user agent was wrong, tried just `Chrome/60.0.3112.113` and it works! Should this be closed?

**Comment by Thomas101** [comment]
Hey, I've just given it a try signing into a Gmail account and it seems to work fine my end. Also tried changing the UserAgent on account to the one you provided and it worked with that too.

If you try it again does it work? I'm wondering if it was just a glitch on Googles end and resolved itself in the time it took you to change the UserAgent :-/

**Comment by aksh1618** [comment]
Maybe? (I _was_ able to successfully login at the same time in an incognito tab) I'm unable to test this as I enabled skipping the second step while logging in, and google doesn't provide an option to revoke that on a specific device (which is really frustrating). Maybe don't bother about this unless someone else reports something similar 😅
