### ISSUE TITLE
Add Open in Browser to context menu

### ISSUE THREAD

**Issue by caldwed** [wavebox/waveboxapp#889]
* Wavebox Version: 4.5.6beta
* Operating System & Version: Ubuntu 16.04

**Is your feature request related to a problem? Please describe.**
Add an "Open in Browser" option to the right-click context menu for web url accounts or services on the toolbar.

**Is your feature request related to an account type?**
Only asking for web accounts, but it could be useful for any account or service.

**Describe the solution you'd like**
Add an "Open in Browser" option to the right-click context menu.

**Additional info**
I have been trying to side-load stylus and get a css to work with Google Tasks unsuccessfully, but it *does* work in my browser, so this is an alternate plan. Right now, I often use the context menu to open in a new window, and then use the icon to open in the default browser. This would save me a step.

The open in browser icon only appears when you open a new wavebox window. It would be useful for me all the time, or available by right clicking the navigation bar

Maybe this is sort-of related to #878?

**Comment by Thomas101** [comment]
There is an option to do this from the right-click menu in page already...
![screenshot 2018-12-18 at 12 04 42](https://user-images.githubusercontent.com/103586/50153033-22f3fa80-02bd-11e9-838e-ea5ad07daafe.png)
...but nothing from the right click menu on the account icon.

As for #878 that's around clicking on a link to open a page. For example clicking on a link with <kbd>Ctrl</kbd> opens the page in a Wavebox window. These can be changed under Settings > Links, if for example you want to use the default browser.

**Comment by caldwed** [comment]
This is close enough for me. I had missed the context menu on the page for some reason.
