### ISSUE TITLE
Multiple switchers for showing wavebox icon in the tray

### ISSUE THREAD

**Issue by oleynikandrey** [wavebox/waveboxapp#89]
Wavebox 3.1.5
Windows 10 x64

I have several switchers for showing wavebox icon in the tray.

![image](https://cloud.githubusercontent.com/assets/1157958/25119935/d83756fe-2424-11e7-8384-83bb491ea6a6.png)

**Comment by Thomas101** [comment]
Do you ever seen more than one icon in the tray at one time or is it just in the taskbar settings? If you switch all of them off until you have just the one still turned on that controls the one that you're currently seeing does the setting stick with that one, or does it hide after a while/restart etc?

**Comment by Thomas101** [comment]
Hi, this should be fixed in Wavebox 3.1.9. Thanks!
