### ISSUE TITLE
GTKStatusIcon click behaviour for Linux Mint users is missing from latest release

### ISSUE THREAD

**Issue by yermulnik** [wavebox/waveboxapp#890]
* Wavebox Version: 4.5.8
* Operating System & Version: Linux Mint (Ubuntu 14.04)
* (Linux only) Install method: Apt-Repo
* Account type (if applicable): not applicable

**Expected & actual behavior**
Expected: clicking on tray icon should toggle app window based on settings in preferences.
Actual: clicking on tray icon brings up tray menu with toggle action which doesn't toggle app window as well.

**Steps to reproduce**
Run app and left-click tray icon

**Is the bug persistent or intermittent?**
Always happen

**Additional information**
Since v4.5.3 this was fixed by bringing back need behavior:
`Add option to force the use of GTKStatusIcon for tray rendering to restore the previous click behaviour for Linux Mint users`
But after updating to latest v4.5.8 this is again missing so left-clicking on tray icon only brings up tray menu but never toggle app window =(

**Comment by Thomas101** [comment]
Thanks for that! I'll get a patch out for this shortly

**Comment by Thomas101** [comment]
Hi, a fix for this has just gone out in 4.5.9

**Comment by yermulnik** [comment]
Thanks a lot. Can confirm this is fixed in 4.5.9.
