### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by jpage4500** [wavebox/waveboxapp#893]
I've seen this error across 2 laptops (macbook's) for a while now. I've been updating manually each time but it seems like when ever a new release is available I'll get this dialog again.

Any ideas why? The mac I'm working on now is running OSX 10.14.1

![image](https://user-images.githubusercontent.com/1895553/50349131-c8e77500-0508-11e9-8bbd-78a9b08e460d.png)

**Comment by Thomas101** [comment]
It could be failing to connect out to the web for some reason. How are you connected to the web? Are you using a proxy server etc?

The other thing I can think of, is are you an Administrator on the machine and is the app installed in `/Applications`?

**Comment by jpage4500** [comment]
Definitely connected to the Internet - no proxy or any unusual setup. I am an admin and the app is in /Applications

Update.. I did do a little more research and I found this post -- http://support.cocoatech.com/discussions/problems/104448-cant-install-updates#comment_45451719

sure enough, running this command returns quarantine:
```
/Applications$ xattr Wavebox.app/
com.apple.quarantine
```

I am using Path Finder instead of Finder and I feel like this is a known Path Finder issue -- when moving an application into the /Applications folder, somehow it doesn't get full permissions and can't auto-update

I ran the command suggested in the link above and sure enough that fixed it:
```
/Applications$ xattr -d com.apple.quarantine Wavebox.app/
```

Anyway - I'll close this issue but maybe there's a chance it will help someone else down the road

thanks,
joe
