### ISSUE TITLE
Ctrl Tab Additions

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [wavebox/waveboxapp#894]
Love the new feature but I would prefer if you could add what I have in the screenshot? Excuse the bad Photoshop. 
![screenshot_3](https://user-images.githubusercontent.com/44755101/50353489-5d20fe80-0540-11e9-804c-e789860504ab.png)

Thank you

**Comment by nmat** [comment]
The feature is about showing last used services. So in that case it is 1-8 in used apps.

So once you open a new service or go to another service it will show up in the Ctrl+Tab. Not that it will show everything. 

Unfortunately I am really not following the photoshop image. Can you explain a bit more on what it is that you are looking for to do here?

**Comment by Thomas101** [comment]
I'm struggling to follow the photoshop image too I'm afraid.

The Ctrl+Tab is supposed to be just switching quickly backwards and forwards between the last few apps you've been using. We're working on something else for quickly moving into a random app :)

**Comment by Thomas101** [comment]
@My-Name-Is-Adam have you given the quick search a try in the latest beta (v4.5.11)? I think this might help with what you're trying to do.

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel) and you can access the quick search via <kbd>Ctrl</kbd>+<kbd>T</kbd>.

**Comment by My-Name-Is-Adam** [comment]
Hey
Sorry for lack of response 
Been very busy lately 
I'll update it later and check it out
Thank you :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
