### ISSUE TITLE
application interface is glitch borked

### ISSUE THREAD

**Issue by datadub** [wavebox/waveboxapp#895]
* Wavebox Version: Wavebox_4_5_9_osx
* Operating System & Version: Mac OSX 10.11.6 (El Capitan)

After recent update, application interface is glitch borked (see attachments)
![screen shot 2018-12-22 at 20 31 50](https://user-images.githubusercontent.com/16956430/50374121-a0589b80-062c-11e9-8ba1-64e225bd3bd2.png)

**Comment by Thomas101** [comment]
Hey it looks like a conflict with the house drivers in 10.11.6.

The easiest way to get around this is...
1. Launch the app
2. Use the help menu along the top to go to Help > `Restart in Safe Mode`
3. Once the app restarts, go to settings, advanced and disable Hardware Acceleration
4. Restart the app and it should work now

**Comment by Thomas101** [comment]
Hi, I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment and I’ll take another look. Thanks
