### ISSUE TITLE
Unable to modify events in Google Calendar

### ISSUE THREAD

**Issue by m1small** [wavebox/waveboxapp#896]
This seems possibly related to https://github.com/wavebox/waveboxapp/issues/834 however I'm not logging anything in the Javascript console and this is a more recent version, so I'm creating a new issue.

* Wavebox Version: 4.5.9
* Operating System & Version: MacOS 10.14.2
* Account type (if applicable): Google, Calendar

**Expected & actual behavior**
Buttons work and I don't get stuck in the edit.

**Steps to reproduce**
In a Corporate Google Apps account, attempt to edit the event details either by the quick edit as shown in the gif below, or by entering into the event (only double click works to get there, the edit button does not).  None of the buttons work to save, cancel, edit, etc.

**Is the bug persistent or intermittent?**
Persistent.
Attempted fixes include Wavebox refreshes/reloads, Wavebox safemode, and computer restart.
Tested on a personal Gcal and this issue does not seem to impact personal accounts.

**Screenshots**
![1caleventfail-edit](https://user-images.githubusercontent.com/35241491/50652554-b115e500-0f3b-11e9-9d85-e79c79e4dd91.gif)

**Additional information**
This began occurring about 2 weeks ago.  Current workaround is to just use Chrome for managing Gcal events.

**Comment by m1small** [comment]
Thanks @Thomas101.

`Clear all browsing data` from Wavebox worked to fix the issue.

FWIW - I'm using Gmelius and Clearbit with this account.

**Comment by Thomas101** [comment]
Thanks! My suspicion is it's a bug on Google's end :)
