### ISSUE TITLE
White screen when restoring from minimizing by clicking taskbar app button or closing main window

### ISSUE THREAD

**Issue by Ymetro** [wavebox/waveboxapp#898]
* Wavebox Version: 4.5.10
* Operating System & Version: Windows 10, build 17758.1, 64-bit
* Account type (if applicable): not applicable

**Expected & actual behavior**
Expect to show contents of maximized window when clicking the task bar button or the fysical "Mail" button on my keyboard, no matter what app is upfront in Wavebox. 

**Steps to reproduce**
Clicking the program button in the taskbar to minimize main window and closing the main window with clicking the minimize button in upper right corner of the window, like other Windows apps. 
Content is being drawn/shown again when the mouse cursor is reaching interactive parts, like the sidebar and the plugins, located at the top-right corner. 

**Is the bug persistent or intermittent?**
persistent from the previous version 

**Screenshots**
Screenshot from issue: 
![schermopname 141](https://user-images.githubusercontent.com/30724400/51016511-e2606780-1570-11e9-9a69-89abcf58e36e.png)

Screenshot from debug console:
![wavebox debug console errors](https://user-images.githubusercontent.com/30724400/51016817-fc4e7a00-1571-11e9-88d9-714d27273399.jpg)

**Additional information**
Experiencing two other bugs: 
- Simplenote account is not being saved, so I have to log-in it's account every time Wavebox is loaded for the first time, and; 
- Links no longer open the default browser (Google Chrome in this case), not even with Ctrl+Click; there is no response when clicking a link 
I will report these bugs separately.

**Comment by Thomas101** [comment]
Thanks for reporting @Ymetro. Do you know which type of graphics card you have in your machine?

There's a couple of things that are worth trying which may help with this, it would be good to know if either of them work for you...
1. Enable force repaint, by going to Settings > Advanced, and enabling `Force window repaint on restore`
2. Disable hardware acceleration, by going to Settings > Advanced and disabling `Hardware acceleration`

**Comment by Ymetro** [comment]
Hello @Thomas101.

I having a NVIDIA GeForce GTX TITAN (the first one of the series) in my system running Wavebox. 
If I remember correctly, it is from ASUS. 

I applied your settings: 
    1. Having force repaint enabled makes no difference - same behaviour as before change; 
    2. Having only hardeware acceleration disabled makes no difference as well;
    3. Having force repaint enabled and hardware acceleration disabled makes no difference as well; 

Behaviour is same for normal window as well as maximazed window. 
In the Windows system settings the window animations are disabled. 
Maybe this won't trigger a redraw of the window contents.

**Comment by Ymetro** [comment]
Now it seems that opening the main Wavebox window does draw its contents after closing its window, but minimizing it and clicking the taskbar app button or double-clicking its systray icon or pressing the hardware Mail button on my keyboard, it still shows the empty white screen.

**Comment by Ymetro** [comment]
> @Ymetro just been trying to get to the bottom of this...
> 
> * When the window shows up blank, does resizing  it make it show anything?
Resizing it with the `Win+Down` buttons does redraw its contents. 
> * Above you said that pressing the hardware mail button caused the behaviour. Can you give the following a try...
>   
>   * Click the Wavebox icon in the task manager (bottom right of the screen) which will bring up Wavebox Mini
>   * Press `Show main window` along the bottom
>     ![screenshot 2019-01-23 at 16 09 00](https://user-images.githubusercontent.com/103586/51619972-57487f80-1f29-11e9-8836-955a520ca04f.png)
> 
> Does that still have the broken behaviour?
It still shows the same behaviour. I am not sure if I mention this clearly enough: it occures when clicking the main window button on the taskbar, which minimizes it to the taskbar. Then when it is clicked again or restored with opening the way you mentioned or pressing the hardware mail button it shows the white screen. When closing the main window and restoring it with a double click on the systray icon or pressing the hardware button it shows its contents like it's supposed to. It's very specific behaviour. 
So it shows white after restoring minimization by clicking the taskbar button of the program, shown below:
![taskbar with wavebox main window button](https://user-images.githubusercontent.com/30724400/51624253-b4006600-1f3a-11e9-9b65-8aa77742f640.jpg)

I hope this helps.

**Comment by Thomas101** [comment]
Thanks @Ymetro. I'm struggling to reproduce the same behaviour here which is frustrating. My gut feeling was that it could be something to do with the GPU or graphics drivers, but disabling hardware acceleration would have solved this in that case.

The other thing I think may help, is the upcoming chromium upgrade we're working on

**Comment by Thomas101** [comment]
Just a thought from the team here, can you try the following...

* Right click the shortcut you normally use to launch Wavebox and go to properties
* Under the shortcut tab, change the target so it has `--disable-renderer-backgrounding`on the end. For example `"C:\...\Wavebox.exe" --disable-renderer-backgrounding`
* Click OK, Quit Wavebox and use the shortcut to launch it

![t2](https://user-images.githubusercontent.com/103586/51837621-d52ad300-22fb-11e9-850a-7c7e7a5f4c27.png)

Does that make any difference?

**Comment by Ymetro** [comment]
Alas, this does not make a difference. 
Had a bit of trouble editing the shortcut: Edited the shortcut in Start Menu Programs, and when it started to the systray and I double clicked the icon, the properties of the taskbar button did not reflect my shortcut edit (did not say `--disable-renderer-backgrounding`). So I edited it as well (had to remove the target location, because it was not the right one). Made me wonder if the command was used at starting Wavebox, and in this screenshot of the taskmanager, I suppose it does: 
![partial taskmanager screenshot wavebox](https://user-images.githubusercontent.com/30724400/51850298-c0f9cc80-2321-11e9-9138-b448cb8106f3.jpg)

**Comment by Thomas101** [comment]
Okay thanks - it was a just a thought here. We're hoping to get a beta ready soon with an updated Chromium, hopefully, this won't exhibit the same problem.

**Comment by Thomas101** [comment]
Hi @Ymetro we've had some other users report that this is fixed in the latest stable version (4.7.3). It would be great to know if it's fixed for you too!

If this hasn't worked, our latest version (4.7.11) in the [beta channel](https://wavebox.io/kb/beta-channel) has an updated version of Chromium which may fix issues like this. It may be worth giving this a try. Thanks

**Comment by Ymetro** [comment]
Hi @Thomas101, 
Got the latest version (4.7.3) and it seems to be better now: once I experienced 1 long flash and after rebooting Wavebox and switching around, there is only a white flash for a couple of milliseconds, making it a lot less annoying than before. Thank you.

**Comment by Thomas101** [comment]
Awesome, that's great to hear :)
