### ISSUE TITLE
Simplenote account is not being saved, need to log in every time Wavebox loads for the first time

### ISSUE THREAD

**Issue by Ymetro** [wavebox/waveboxapp#899]
* Wavebox Version: 4.5.10
* Operating System & Version: Windows 10, build 17758.1, 64-bit 
* Account type (if applicable): Simplenote

**Expected & actual behavior**
When Simplenote app icon is clicked in the Sidebare, the app opens and user is logged in, when logged in from previous session

**Steps to reproduce**
Unload Wavebox, start Wavebox and click on Simplenote icon in Sidebar
Simplenote asks user for account information to log in. 

**Is the bug persistent or intermittent?**
Persistent. Occured from updating to version 4.5.10

**Screenshots**
Screenshot:
![schermopname 142](https://user-images.githubusercontent.com/30724400/51017034-d5447800-1572-11e9-8c7a-03c8d0e4e840.png)

**Additional information**
Getting "Too many attempts" message in Simplenote app when trying to log in. 
Seems to log in with correct name and password, but still gives error before "Too many logins" - message.

**Comment by Thomas101** [comment]
Thanks! I've put a fix in for this. The client should update automatically in the background, but if you want to make sure you've got the latest version, remove your Simplenote account and re-add it again

**Comment by Ymetro** [comment]
After working on the "white screen" issue, and thus restarting Wavebox with different advanced settings, and undoing those settings after no effect, the issue still is present after removing and adding the Simplenote account and Simplenote will not remember the login and asks me to log in after a Wavebox restart each time. 

Tried several times closing Wavebox with `Ctrl+Q` and started it with my keyboards Mail button. 

I seem to fail a lot of times to log in into my Simplenote account, so that it gives me a time-out, but for me it seems that I input my credentials correctly. 
This time-out is a hindrance to this troubleshooting workflow and when I want to access my quick notes. 

The container is version 3. 

I noticed that in the Simplenote account settings under Credentials, that there are "no credentials attached to this account". Is this the reason it won't stick?

**Comment by Thomas101** [comment]
Yeah, I'm seeing the same. It looks although the behaviour is also the same in the browser - once you quit the browser you're completely signed out.

I've sent a support request across to Simplenote to see if they can shed any light on the problem

**Comment by Thomas101** [comment]
It looks like the Simplenote team have fixed this, so it should be working now. Thanks for taking the time to report!

**Comment by Ymetro** [comment]
It is working again. Thank you!
