### ISSUE TITLE
Not possible to copy URL from pop-up windows

### ISSUE THREAD

**Issue by Tahini-123** [wavebox/waveboxapp#90]
* Which version of Wavebox are you using? [3.1.5]

* Which Operating System are you using? [Ubuntu 17.04]

It would be nice to be able to be able to select and copy the URL of the pages opened from Wavebox. 
At the moment the URL can be highlighted but it can't be copied.

**Comment by Thomas101** [comment]
Hi, which popup windows are you having trouble with?

**Comment by Tahini-123** [comment]
Nevermind, it's either solved or I was doing something wrong. 
Feel free to close as Cant Repro or Invalid.

**Comment by Thomas101** [comment]
Thanks! In 3.1.8 there will be an option to right-click copy the current url if this is helpful too :)
