### ISSUE TITLE
Pinch to zoom. Menu tweaks

### ISSUE THREAD

**Issue by heffneil** [wavebox/waveboxapp#901]
* Wavebox Version: [e.g. 3.0.0]
Latest
* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]
OSx
Two suggestions here:
1. Implement integration for 1password.  It is very powerful and I use it within chrome and safari along with my iphone so it would be useful to have access to those password and not have to maintain another repository.
2. Muscle memory in Chrome has be right click and the top option is back.  Would be nice if we had that at the tope of the pop up menu.  I don't think the three finger swipe is working on my laptop (Macbook Pro 2016) to go back a page in appls like Twitter or Instragram.
3. Just thought about this UI change but in Wavebox after zooming (and as I get older I zoom more :( ) You have to choose the option 'reset zoom' Thats confusing again perhaps comfort with Chrome but Actual Size makes a bit more sense?

**Comment by heffneil** [comment]
Thanks for the response and the reception of my suggestions.  Much appreciated! Love the product and I am telling everyone to get it!

**Comment by heffneil** [comment]
Thanks the pinch and zoom works wonderfully in my initial testing!  Thank you for being so response and open to recommendations!  Very happy with Wavebox!

**Comment by Thomas101** [comment]
Yep, you're right there! I've put a fix in which should go shortly :)

**Comment by Thomas101** [comment]
@heffneil a fix that has just gone out in 4.5.12. Thanks!

**Comment by heffneil** [comment]
Works beautifully! Thanks!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
