### ISSUE TITLE
Improved Authenticated Proxy support

### ISSUE THREAD

**Issue by abejenaru** [wavebox/waveboxapp#904]
* Wavebox Version: 4.5.0
* Operating System & Version: Windows 7

**Is your feature request related to a problem? Please describe.**
Currently, authenticated proxy support works by prompting each time for user credentials.

**Describe the solution you'd like**
Remember entered credentials or manage proxy-related options in Settings.

**Additional info**
![2019-01-14 14_34_01-wavebox _ ifttt](https://user-images.githubusercontent.com/1703377/51115857-aeec3a00-1809-11e9-9083-f4e1f68241d5.jpg)

**Comment by Thomas101** [comment]
I'll take a look to see if we can add something in!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.5.11. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by abejenaru** [comment]
I did, and it works fine for me. Kudos for your speedy intervention!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
