### ISSUE TITLE
Skype links opened in Wavebox browser instead of default one

### ISSUE THREAD

**Issue by nicolafarina** [wavebox/waveboxapp#908]
* Wavebox Version: 4.5.10
* Operating System & Version: Windows 10
* Account type (if applicable): Skype

Links are opened in Wavebox browser popup window instead of system's default one (Chrome for me).

**Comment by Thomas101** [comment]
Thanks, we're seeing the same here. I'll try to get a fix in so it respects the setting!

**Comment by nicolafarina** [comment]
Many thanks Thomas. Keep coding!!!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.5.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by nicolafarina** [comment]
Thanks Thomas but, maintaining the stable release on Chocolatey, I would not want to ruin my environment.

**Comment by Thomas101** [comment]
No problem, it shouldn't be too long before it heads out into stable :)

**Comment by nicolafarina** [comment]
Very good news!

Cheers!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by nicolafarina** [comment]
Thanks Thomas, just uploaded on Chocolatey and waiting for approval.

**Comment by Thomas101** [comment]
Thanks :)

**Comment by nicolafarina** [comment]
Thomas, I'm on 4.7.0 but nothing changed. Every option I set in Skype account link section don't change the wrong behavior: links are opened in a Wavebox browser window instead of system default browser (Chrome in my case).

**Comment by Thomas101** [comment]
Looks like I might have half fixed it, the top link for me works but the bottom preview doesn't

![screenshot 2019-02-13 at 12 16 37](https://user-images.githubusercontent.com/103586/52711294-60a59480-2f89-11e9-8a5c-a65eebd558b9.png)

I'll take another look to see if we can get them both them same :)

**Comment by nicolafarina** [comment]
Confirmed. Preview link box is working bad, textual links works as expected.

**Comment by Thomas101** [comment]
I've just pushed 4.7.1 out which should handle these a bit better :). Thanks!

**Comment by nicolafarina** [comment]
With 4.7.1 preview links boxes are fixed but simple text links are opened twice in external browser!

**Comment by Thomas101** [comment]
Whoops - that's the original fix in there. I've removed this from the wire config, so your client should grab the latest version in the background at some point. If you want to force it just restart the app.

You can check you've got the latest version (1.9.2) under Settings > About > Wire Config Version

**Comment by nicolafarina** [comment]
Boom! Finally fixed!

Many thanks.
