### ISSUE TITLE
Duplicate Slack Notifications across devices

### ISSUE THREAD

**Issue by jedashford** [wavebox/waveboxapp#909]
* Wavebox Version: 4.5.10
* Operating System & Version: Mac 10.14.2
* Account type (if applicable): Slack

**Expected & actual behavior**
When I get a slack notification with the client open on my desktop (in wavebox), I don't expect to also get that notification on my mobile device. When using the mac slack app, I don't get notification to both devices. The desktop gets the notifications and its not duplicated across my other devices.

**Steps to reproduce**
NA

**Is the bug persistent or intermittent?**
Do you only see it sometimes or does it always happen?

**Screenshots**
NA

**Additional information**
First time wavebox user here. I've unchecked the 'sleep & behavior' > 'sleep tab after minutes of inactivity'.

**Comment by jedashford** [comment]
I just found a setting for "When I'm not active on desktop, send notifications to my mobile devices". Is there a way that wavebox can keep the page active like the native app? So my screen is active, Im looking at it, but slack thinks my session is inactive. Others must have faced this issue.

**Comment by Thomas101** [comment]
Thanks for reporting! I've got a fix together which will be out in the next release shortly

**Comment by jedashford** [comment]
Thank you! This is an excellent product. I've spread word around the office. Instead of having multiple tabs open, on chrome, plus multiple native apps open, I get to just have them all contained in wavebox. The world needs this.

**Comment by Nicabus** [comment]
My team actually needs the opposite.  As we are frequently away from our desks for short amounts of time, 10-20 minutes.  This means that if we have a production alert go off right after walking away, my phone will not go off at all.  I believe that previously both my mobile and my desktop would alert and we would like to have this option available.

**Comment by jedashford** [comment]
The PR shows that this is an option that you can add or remove.

**Comment by Thomas101** [comment]
Hey, I had some email notifications about conversation on this - but it looks like the messages have been removed.

It revolved around the current behaviour (with duplicate notifications) being more useful in some instances. The PR does include a switch to turn the new behaviour off, the plan is to deprecate this on the next major release and use only the new behaviour.

If there's a use-case for keeping the current behaviour and duplicate notifications, we'd love to know, because we can keep the switch in. In addition to this, we would probably look at having the option configurable per each Slack team, but I'm just second guessing the conversation at the moment.

Would be good to know!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.5.11. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel).

If there is demand for maintaining the old behaviour, we'll add a more permanent option in during this beta cycle.

Thanks

**Comment by jedashford** [comment]
Yeah I deleted my comment since I sent it by email and the comment I was referencing was deleted by the user.

I think your solution fixes both of the issues mentioned since it keeps the connection alive. So I can actually change the web setting I mentioned above to send me messages to my phone immediatly after the socket is closed instead of waiting the standard 2 minutes and possibly missing those 2 minutes of messages. I'll test it today in the beta.

**Comment by Thomas101** [comment]
Thanks @jedashford , I've added it in to be per account on the basis that is the right assumption anways :)

**Comment by jedashford** [comment]
I've been using this for a few days and changed slack's settings to show me notifications after 1m of inactivity and I'm no longer getting duplication notifications while having wavebox running and an active session of slack. You are awesome, thank you!

**Comment by Thomas101** [comment]
Just as an update to this, the `Keep Slack WebSockets in active mode` setting has been moved from Advanced to be under Account Settings > Advanced and can be changed for each account :)

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by jedashford** [comment]
This fixed all concerns I had, its perfectly responsive. When I close my
laptop, I get notifications to my phone immediately. Thanks for the support
and I wish you all the best.
