### ISSUE TITLE
JetBrains account error

### ISSUE THREAD

**Issue by AlfonsoGangemi** [wavebox/waveboxapp#910]
* Wavebox Version: 4.5.10-1
* Operating System & Version: Ubuntu 18.04.1
* (Linux only) Install method: Apt-Repo
* Account type (if applicable): JetBrains

**Expected & actual behavior**
On add JetBrains account no page is loaded (about:blank)

**Steps to reproduce**
1. add JetBrains to accounts and confirm with finish button. 

**Is the bug persistent or intermittent?**
Everytime I try

**Screenshots**
![image](https://user-images.githubusercontent.com/40163703/51470716-0001ae00-1d75-11e9-85ae-fb3173e403a1.png)

**Comment by Thomas101** [comment]
Which JetBrains service are you trying to add? Is it a YouTrack account?

**Comment by Thomas101** [comment]
I’m going to close this due to inactivity. If you’re still seeing the issue, feel free to re-comment with some additional info and we'll try to reproduce here and take another look. Thanks!
