### ISSUE TITLE
intermittent slowness 

### ISSUE THREAD

**Issue by lkortebe** [wavebox/waveboxapp#911]
* Wavebox Version: 4.5.10
* Operating System & Version: Windows 7 Professional
* Account type: Trello, weblink to Airtable, Gmail (2 services), Office 365 (1 service)

**Expected & actual behavior**
Experiencing waits of 1-3 minutes to open Outlook emails, switch Trello boards, etc. All services do open, but then are slow to load.

**Steps to reproduce**
Not sure - it happens during general usage.

**Is the bug persistent or intermittent?**
Intermittent. It will often happen when Wavebox has been left running for some time. More recently, it also happens after a computer reboot.  It sometimes resolves itself after about 15 minutes of waiting and clicking around, sometimes after deleting and re-adding services, and sometimes after a complete computer reboot.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. Do you have VirtualBox or VMWare installed on your Windows 7 machine by any chance?

**Comment by lkortebe** [comment]
Hm, not sure - on my work network. I know we have a virtual machine running on a remote server.

**Comment by Thomas101** [comment]
Can you give the following a try to see if it helps..

1. Right click on the Wavebox shortcut you normally use then going to properties
2. Click on the shortcut tab and add the following to the Target field `--no-proxy-server` so it looks more like this... `"C:\...\Wavebox.exe" --no-proxy-server`

![t1](https://user-images.githubusercontent.com/103586/51837702-1ae79b80-22fc-11e9-8c61-90fe7092587c.png)

3. Click OK, and relaunch the app using the shortcut

Does that make any difference?

**Comment by lkortebe** [comment]
So far, haven't experienced further issues.

**Comment by Thomas101** [comment]
Thanks for the update! I'll close this off, but let me know if it comes up again :)
