### ISSUE TITLE
Lots of crashes/freezes

### ISSUE THREAD

**Issue by johnhydroware** [wavebox/waveboxapp#914]
* Wavebox Version: 4.5.10
* Operating System & Version: Ubuntu 18.04
* (Linux only) Install method: Apt-Repo
* Account type (if applicable):Gmail, Office 365, Evernote, Slack, Gitter

Wavebox crashed quite alot. Not sure that it is exacly the same every time. But I thing I get a lot of `(electron) 'memory' is deprecated and will be removed` and`Failed to generate minidump` every time it freezes/crashes.

This is the error I got the last time:

``` (electron) 'memory' is deprecated and will be removed.
[3133:0100/000000.801062:FATAL:memory.cc(22)] Out of memory. size=262144
ExceptionHandler::GenerateDump sys_pipe failed:Too many open files
ExceptionHandler::SendContinueSignalToChild sys_write failed:Bad file descriptor
ExceptionHandler::WaitForContinueSignal sys_read failed:Bad file descriptor
Failed to generate minidump

**Comment by Thomas101** [comment]
Hi, thanks for reporting. The `memory is deprecated` isn't anything to worry about, the `Failed to generate minidump` is probably where the problem lays. Can you check the following...
* After how long would you say the app crashes? If you launch it and leave it running does it crash without intervention or is it only with use?
* What file descriptor limit do you have configured? `ulimit -n`
* After running for a while, can you check how many file descriptors Wavebox has open. You should be able to do this with...
```bash
ls /proc/`ps -eF | grep "[/]opt/wavebox/Wavebox --mailto" | awk '{ print $2 }'`/fd | wc -l
```

Thanks!

**Comment by johnhydroware** [comment]
My limit is 1024.

None of my processes have "--mailto", but I tried the process without any arguments which I assume is the interesting one?

So far I have 353 FD:s. Will get back to you regarding the other questions.

**Comment by johnhydroware** [comment]
Now it stopped responding to any mouse clicks, both in the app and the wavebox buttons. I got nothing on stdout/stderr. I have 264 file descriptors.
I had outlook 365 mail app open. It did update the GUI when I got a mail, but I still could not click anywhere.

And if it makes any differens: I'm using XMonad as the window manager.

**Comment by johnhydroware** [comment]
Now I got first type of error again (except that size=81920). The window became white. After the crash the process had 188 file descriptors.

I think it was open on Slack. Might have been an hour since I used it the last time. It have been running a couple of days with some laptop sleep in between.

**Comment by Thomas101** [comment]
Thanks @johnhydroware how much memory and swap do you have on your machine?

**Comment by johnhydroware** [comment]
I have 16GB memory and 32GB swap. But the swap isn't really used(47MB according to htop).

I will try to take a look at memory usage when it happens. But I don't have any problem with it in any other apps.

**Comment by johnhydroware** [comment]
Regarding memory usage: This time it crashed without me having VMWare running, which means that I had at least 6GB free memory(I verified with htop).

**Comment by Thomas101** [comment]
Thanks, with 16/32GB configured I doubt running out of memory is the problem. We're still looking into this and trying to get to the bottom of it

**Comment by Thomas101** [comment]
@johnhydroware  we've just released a new version (4.7.11) of Wavebox to [beta channel](https://wavebox.io/kb/beta-channel) with an updated version of Chromium. We're hoping this will fix the issue you've been seeing. It would be great if you could give this a try and see if it's fixed for you. Thanks :)

**Comment by Thomas101** [comment]
Version 4.8.0 of Wavebox has just been released, which should fix this. If you're still seeing the problem on the latest version, feel free to re-comment and we'll take another look. Thanks for reporting!

**Comment by johnhydroware** [comment]
@Thomas101 Sorry for not getting back to you. Have been busy. Have tried the new version and the counter for number of e-mails in outlook started to work and it have been running smoothly so far. Thanks!
