### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by nicolafarina** [wavebox/waveboxapp#915]
Just for your knowledge,

I maintain a Chocolatey package for Wavebox since some months. You can find here: https://chocolatey.org/packages/wavebox.

Cheers.

**Comment by Thomas101** [comment]
That's awesome @nicolafarina! Can you drop support [at] wavebox.io an email :)

**Comment by nicolafarina** [comment]
Thomas I need a confirmation about Wavebox future development to choose the way Chocolatey package had to be updated about Wavebox 10.x.

If "Classic 4.x" will be considered a legacy version that will not be updated in future, I simply consider to publish 10.x within the "wavebox" package (like a 5.x version), otherwise, I have to create a new package for having both, but renaming is not possible (and "wavebox" will be the classic, not the new lineup for which a new a name had to be forged).

Thanks.

**Comment by Thomas101** [comment]
Our eventual goal is to move everyone across to Wavebox 10. Ideally, it would be great to rename chocolatey wavebox to be wavebox_classic and continue to keep wavebox as the most up to date version, however as this is not possible it might be best to update the current package to version 10.

If you need any info on fixed download urls and/or a feed for updates etc drop me a line at https://wavebox.io/support

**Comment by nicolafarina** [comment]
Exactly what i thought.

Thanks!

**Comment by nicolafarina** [comment]
I definitely need a fixed download URL for the package. Already wrote weeks ago to support but no response yet. I try again if you can check.

Many thanks.

**Comment by Thomas101** [comment]
Sorry about that! Got your message and replied :)

**Comment by nicolafarina** [comment]
Got it, thanks.
