### ISSUE TITLE
[Feature Request] submenus

### ISSUE THREAD

**Issue by EnorMOZ** [wavebox/waveboxapp#917]
* Wavebox Version: 4.5.10
* Operating System & Version: Mac OSX 10.14.3

**Is your feature request related to a problem? Please describe.**
Once you start adding various "Accounts" it starts to get overwhelming.

**Describe the solution you'd like**
Have the ability for submenus; Work, Emails, Chat etc. Then have accounts within those submenus. With that solution you would group accounts by a main category vs having to scroll through tons of accounts to find the one you are looking for.

**Comment by RXWatcher1** [comment]
I completely agree on this. I'm a recent convert to Wavebox and purchased it. I love it but it is overwhelming when you get more than say 10 custom urls. I really think this app could be the app I've been missing from my life but not having submenus really hinders its use.

Thanks for all of the hard work!
-RX

**Comment by TheSpyder** [comment]
Something I've been considering along these lines is a kind of "profile" feature request. Set up groups of accounts and be able to switch the sidebar between them easily.

Of the many accounts I use, I only need at most 5 at a time - for example I have a collection of work accounts, a collection of personal accounts, and the remainder could shift into a third collection without getting too annoying.

**Comment by TheSpyder** [comment]
Pinning out-of-app URLs as services within an account might work, I hadn't thought of that, although I kind of like the way each account is sandboxed (so I don't have google ads tracking me quite as easily outside of the google services).

Profile windows would be perfect! I haven't used Chrome profiles in a while, but I'm assuming I would be able to close a window to turn off the profile apps (not just sleep them) and then hit a menu option somewhere to reopen that profile later.

I imagine it might make the unread counter on the app icon or menubar more confusing - specifically finding _where_ the service is that has an unread item - but that can perhaps be worked out after we have been using the feature for a bit.

**Comment by Thomas101** [comment]
> I imagine it might make the unread counter on the app icon or menubar more confusing

@TheSpyder Yeah, we haven't quite figured out how to do this yet, or how the whole profile thing will work as a whole :). We have issue #139 open if you want to open up some discussion on how profiles could work, but we don't really have a specific timeframe we're working to with that feature at the moment.

As regards the original issue for submenus, am I okay to close this off, or is there anything else we need to add?

**Comment by TheSpyder** [comment]
Of course, sorry for dragging this one off topic!

**Comment by Thomas101** [comment]
I’ll close this off then, but there's anything else feel free to reopen the discussion we can look at other ways of organising accounts
