### ISSUE TITLE
Beta feedback: option to go back to quit immediately

### ISSUE THREAD

**Issue by TheSpyder** [wavebox/waveboxapp#918]
* Wavebox Version: [e.g. 3.0.0]

4.5.11 beta

* Operating System & Version: [e.g. Windows 10, Mac OSX 10.3.4, Ubuntu 17.10]

macOS 10.14.3

**Is your feature request related to a problem? Please describe.**
I didn't read the changelog after I downloaded, so the new `Don't automatically quit on CmdOrCtrl+Q but prompt first` feature was quite jarring.

**Describe the solution you'd like**
I've disabled the "warn before quitting" feature in chrome, I'd like to disable it here as well please :)

The advanced section of the options is getting quite full, I hate to ask for yet another setting to go in there, but it does seem like the best place 🤔 although chrome put it in the main menu above the quit option 🤔

**Comment by Thomas101** [comment]
Yep, we should make this an option :)

**Comment by Thomas101** [comment]
> The advanced section of the options is getting quite full

We should probably look at splitting out at some point. There's 4 settings in there on our deprecation list too :)

**Comment by Thomas101** [comment]
> The advanced section of the options is getting quite full

Decided the UI section would be best for this :)

![screenshot 2019-01-30 at 12 33 59](https://user-images.githubusercontent.com/103586/51981558-56fd3680-248b-11e9-96fe-a927169ad2dc.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.5.12. Thanks :)

**Comment by TheSpyder** [comment]
Looks great 😁

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
