### ISSUE TITLE
Mac OS shortcuts conflict

### ISSUE THREAD

**Issue by Bardyl** [wavebox/waveboxapp#92]
Hello,

I'm using Wavebox 1.3.5 on MacOS 10.12.4.
There is a conflict between shortcuts we use on MacOS with « option + shift + number » and the way to change the tab in Wavebox account if we use Inbox, Hangouts or Google Keep for example).

Thanks for resolving this.

**Comment by Thomas101** [comment]
Thanks. I'll look at adding in some customization for shortcuts so you can turn them on or off depending on how you use the same key-combos with osx

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which removes some of the conflicting keyboards shortcuts and also has support for setting your own. If you do find any that conflict or that you want to change, open up the Settings and then go to Advanced. From there you can change or disable keyboard shortcuts

You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!
