### ISSUE TITLE
Whatsapp web account slows down wavebox considerably

### ISSUE THREAD

**Issue by arjovanramshorst** [wavebox/waveboxapp#920]
* Wavebox Version: 4.5.10
* Operating System & Version: POP!_OS 18.10 (Ubuntu 18.10)
* (Linux only) Install method: Snap
* Account type (if applicable): whatsapp

**Expected & actual behavior**
Since I did a clean install of my operating system and reinstalled Wavebox, Wavebox suddenly becomes very laggy when the web whatsapp account is opened. Any other account (e.g. slack, gmail) doesn't have any issues, and the lag immediately stops when selecting another account. The lag is not only in the whatsapp window, but if it's opened and I go to the wavebox settings or even the file/edit/view menu it's very noticeably slow. 

**Steps to reproduce**
Install wavebox using snap, add a whatsapp web account, on a 4K display scroll through messages or type anything.

**Is the bug persistent or intermittent?**
Since today it is persistent (didn't have the issue before reinstalling OS), however I do use wavebox fullscreen on a 4K monitor (no hidpi config), and the lagging problem is a little bit reduced when resizing the window to 1080P, 4k shouldn't necessarily be the issue though, because running whatsapp web fullscreen in chrome has no issues at all. (and before reinstalling my OS it didn't run this slow either)

**Screenshots**
Screenshots often help us narrow down a bug more easily.
![image](https://user-images.githubusercontent.com/2796541/52215453-59e59600-2894-11e9-9390-1f90240f0d8b.png)
Task manager when on the inbox account

![image](https://user-images.githubusercontent.com/2796541/52215524-80a3cc80-2894-11e9-97a1-1681b6a6a794.png)
Task manager when scrolling in a whatsapp chat

**Additional information**
PC has an i7 8550U cpu, uhd620 graphics and 16GB ram

**Comment by arjovanramshorst** [comment]
1. If you restart the app and launch WhatsApp does it exhibit this right away, or is it something that happens after a while?
*Yes, also after a reboot, when Wavebox is the only app running it immediately starts lagging and using cpu when selecting the whatsapp account, and immediately stops when selecting a different account (slack/inbox)*
2. Does switching between any of the WhatsApp conversations make any difference to cpu consumption?
*No, even selecting and scrolling through a chat with only a couple of messages has the same effect*
3. Do you have any extensions installed in Wavebox under Settings > Extensions?
*No extensions installed*

Would you be able to try the following in turn to see if it changes the behaviour at all?

1. Remove the WhatsApp account and then add it again
*Did not have any effect, however, I noticed that the 'add new account' screen also appeared to respond slowly (similar to how whatsapp responds laggy) while re adding whatsapp, not sure if that can have something to do with it?*
2. Go to Settings > Advanced, disabled Hardware Acceleration and restart the app.
*Disabling hardware acceleration doesn't seem to have any noticeable effect on both lagginess and cpu usage*

**Comment by arjovanramshorst** [comment]
Followup: I've started to notice some things regarding the performance of Snaps, so I've tried reinstalling wavebox using apt, and while the CPU usage is still high (comparable to the screenshots of the task monitor I've posted, the lagginess is completely gone. I've noticed a similar performance impact in the snap vs apt version of Spotify,

**Comment by Thomas101** [comment]
Thanks for the update! It's good to know that it's working better without snap. I'll see if I can reproduce it here. We're also working on a Chromium upgrade which we think might help with this issue

**Comment by Thomas101** [comment]
@arjovanramshorst  we've just released a new version (4.7.11) of Wavebox to [beta channel](https://wavebox.io/kb/beta-channel) with an updated version of Chromium. We're hoping this will fix the issue you've been seeing. It would be great if you could give this a try and see if it's fixed for you. Thanks :)

**Comment by Thomas101** [comment]
Hi, version 4.8.0 has just been released which we think should fix this. If you're still seeing the problem on the latest version, feel free to re-comment and we'll take another look. Thanks for reporting!
