### ISSUE TITLE
Counter unread message, counts spam messages

### ISSUE THREAD

**Issue by reatlat** [wavebox/waveboxapp#921]
* Wavebox Version: 4.5.10
* Operating System & Version: Mac OSX 10.14.2
* Account type (if applicable): GMail

**Expected & actual behavior**
For some reason the notify counter shown if I have spam in the junk folder.

**Steps to reproduce**
Get some spam 😂 the red icons with counter disappear only if you read the spam or delete it.

**Is the bug persistent or intermittent?**
always

**Screenshots**
<img width="1451" alt="wavebox 5 spam 5 - gmail 2019-02-04 22-41-56" src="https://user-images.githubusercontent.com/9933516/52241289-8b318680-28d3-11e9-82d9-e4c8bc598b61.png">

**Additional information**
Not sure its a bug a great feature to remind me to check spam folder 🤔

**Comment by Thomas101** [comment]
That's an interesting feature, which has also reminded me to check my spam 😂. Unfortunately, I'm not able to reproduce it here :-/.

Maybe try right clicking on the Gmail account in Wavebox and then going to `Reauthenticate`. It might just be a bug on Google's end and fetching a new access token fixes it. If it doesn't, 
* In Gmail, if you click the Settings cog (top-right), go to `Settings`, then the `Inbox` tab, which `Inbox type` is selected?
* In Wavebox, if you right click on your Gmail account, and go to `Account Settings`, can you send a screenshot of your `Unread & Sync` section?

I'll see if switching my settings to

**Comment by Thomas101** [comment]
There has been some odd behaviour from Google over the last week - especially after the outage last week. I wonder if it's somehow related.

> for example, right now I have 2 spam emails but the counter is empty.

Does this mean it's fixed itself? I'm tempted to say it was just a glitch :-/

**Comment by reatlat** [comment]
@Thomas101 Almost sure it was a glitch, it never happened again in the new release, perhaps issue related to Inbox migration
