### ISSUE TITLE
Can't login to LastPass after 4.5.12beta update

### ISSUE THREAD

**Issue by bkazdan** [wavebox/waveboxapp#922]
* Wavebox Version: 4.5.12beta
* Operating System & Version: Windows 10
* Account type (if applicable): LastPass

**Expected & actual behavior**
Expect LastPass login prompt for the extension when clicking on the LastPass logo
Clicking on the LastPass logo results in no login prompt

**Steps to reproduce**
1. Upgraded WaveBox through the automated method
2. Clicked on LastPass icon on the top toolbar

**Is the bug persistent or intermittent?**
The bug is persistent

**Screenshots**
![extension_icons](https://user-images.githubusercontent.com/7254391/52280568-310fe000-292a-11e9-8b38-8b2f23b53963.PNG)

**Additional information**
Troubleshooting steps:
1. Rebooted the computer
2. Uninstalled LastPass extension
3. Restarted WaveBox
4. Reinstalled LastPass extension
5. Restarted Wavebox

The issue persists

**Comment by Thomas101** [comment]
Thanks for reporting, I've just pushed 4.5.14 beta out which fixes this 👍
