### ISSUE TITLE
Switching to 'Account' tab causes 'Advanced Unread Options' to auto-appear

### ISSUE THREAD

**Issue by dep** [wavebox/waveboxapp#924]
* Wavebox Version: 4.5.14 beta
* Operating System & Version: Mac Mojave
* Account type (if applicable): Gmail

**Expected & actual behavior**
Expected:
When I view the Accounts tab in settings, I get the Account settings and no modal.

Actual:
When I view the Accounts tab in settings, the "Advanced Unread Options" modal auto-opens.

**Steps to reproduce**
1. Open settings
2. Go to the Account tab

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![](http://dl.dpeck.net/2jmUcQ+)

**Comment by Thomas101** [comment]
I'd like to say it's a feature but it really isn't!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.6.1. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by dep** [comment]
I've confirmed this is fixed for me on the beta channel. Thank you for the fast turn-around. Truly excellent software.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
