### ISSUE TITLE
No files show in Google Drive

### ISSUE THREAD

**Issue by laureng2** [wavebox/waveboxapp#925]
* Wavebox Version: 4.5.10
* Operating System & Version: MacOS Mojave 10.14
* Account type (if applicable): Google Drive

I just downloaded WaveBox today and everything is working perfectly except Google Drive. When i open up the Google Drive account, it's blank and none of my files appear on the page. i click around in different folders, refresh, and no files are anywhere to be found. It's really strange because the Google Docs and Google Sheets accounts are working fine, files appear and are accessible!

I've tried deleting Google Drive and the whole Google account, and also restarting WaveBox, and none of that worked.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. This was because of a change in Google Drive. We've pushed a fix out with version 4.6.0. If you check for updates via the top `Wavebox` Menu then `Check for updates` it will download. Thanks :)
