### ISSUE TITLE
Whoops! There seems to be no internet connection.

### ISSUE THREAD

**Issue by pioneer** [wavebox/waveboxapp#926]
* Wavebox Version: 4.6.0
* Operating System & Version: freshly installed Linux Mint 19.1 Cinnamon
* (Linux only) Install method: Apt-Repo
* Internet connection: available, works perfectly using Firefox

**Expected & actual behavior**
Expected: Wavebox starts properly and I'm able to start adding accounts.
Actual: I see a message (also on the screenshot attached) "Whoops! There seems to be no internet connection. Here's some thing you can try:
- Try reconnecting to the network
- Test that you can access the internet using your web browser
- Check your antivirus and firewall aren't blocking internet access for Wavebox
UNAUTHORIZED"

**Steps to reproduce**
- Install Linux Mint 19.1
- Install Wavebox using either a deb package or via the apt repo
- Run Wavebox

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![_001](https://user-images.githubusercontent.com/200538/52530770-d2c07400-2d12-11e9-81ff-a181464770e0.png)

**Additional information**
After pressing "Test connectivity", I see the following log:

Testing connectivity...
Current Status: ?clientId=0cd900a8-1b2e-448e-803f-1c0e87bfd6a3&clientToken=&error=UNAUTHORIZED
Testing https://waveboxio.com
-- DIRECT
-- OK:true STATUS:200
Testing https://waveboxio.com/connection_test_fail
-- DIRECT
-- OK:false STATUS:404
Testing https://google.com
-- DIRECT
-- OK:true STATUS:200
Testing https://microsoft.com
-- DIRECT
-- OK:true STATUS:200
Done

**Comment by nmat** [comment]
It did not help to restart wavebox? it continues to come up?

**Comment by pioneer** [comment]
I've just removed Wavebox, then removed everything related to it in ~/.config and ~/.local/share, then reinstalled it and it works now. Weird, but now the issue is fixed.

**Comment by Thomas101** [comment]
Hi, this isn't a case that should ever come up, so I've put an extra check in to guard against it.

To get back up and running though, quit the app, open up `~/.local/share/wavebox/` and remove `user_db.json`. Then start the app again. Does that get it running for you?

**Comment by Thomas101** [comment]
@pioneer sorry I missed that you'd removed the config files and fixed.

I've put a fix in that will go into the next version that should fix this :)

**Comment by pioneer** [comment]
Thanks.

**Comment by Thomas101** [comment]
The fix mentioned above has just gone into 4.7.0 so this shouldn't be an issue again. Thanks for reporting!
