### ISSUE TITLE
Account tooltip disappears before you can click on any service

### ISSUE THREAD

**Issue by lots0logs** [wavebox/waveboxapp#927]
* Wavebox Version: 4.6.0
* Operating System & Version: Arch Linux w/ Cinnamon Desktop
* (Linux only) Install method: [AUR package](https://aur.archlinux.org/packages/wavebox-bin)
* Account type (if applicable): N/A

**Expected & actual behavior**
After tweaking some of the settings its now impossible to use the tool tip menus as they disappear as soon as your cursor is no longer on the account icon. I tried changing the settings back but it didn't fix the issue. 

**Steps to reproduce**
I'm not sure which setting combination triggered the bug. I was tweaking all the settings at the time, seeing what they all did. 

**Is the bug persistent or intermittent?**
Its persistent after occuring once it never goes away.

**Screenshots**
![peek 2019-02-10 01-49](https://user-images.githubusercontent.com/4675662/52531130-5b6cef00-2cd6-11e9-89d8-34ca73d3ae60.gif)

**Additional information**
* Possibly related: #880

**Comment by Thomas101** [comment]
Thanks for reporting. I've managed to reproduce this by setting `Account tooltip show delay` to `0` under Settings > User Interface.

With the default 750 it works as expected, but I'll see why it's failing with 0

**Comment by lots0logs** [comment]
Thanks, that was indeed the problem :+1:

**Comment by Thomas101** [comment]
I've put a fix in for this, so they should work even with a delay of 0. That's just been released in the latest version of Wavebox (4.7.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
