### ISSUE TITLE
GitHub Notifications Badge Not Working

### ISSUE THREAD

**Issue by lots0logs** [wavebox/waveboxapp#928]
* Wavebox Version: 4.6.0
* Operating System & Version: Arch Linux w/ Cinnamon Desktop
* (Linux only) Install method: [AUR package](https://aur.archlinux.org/packages/wavebox-bin)
* Account type (if applicable): N/A

**Expected & actual behavior**
Expect to see badge on GitHub icon with number of unread notifications.

**Steps to reproduce**
Simply add GitHub log in and wait til you have a notification.

**Is the bug persistent or intermittent?**
Its persistent.

**Comment by Thomas101** [comment]
Thanks, I've added this in for the next release

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by lots0logs** [comment]
@Thomas101 Its still not working :thinking: 

![2019-02-14_11-20](https://user-images.githubusercontent.com/4675662/52804809-c73eb700-304a-11e9-94cf-02ef6c70bc1a.png)

**Comment by Thomas101** [comment]
I was just going to say it's only the badge we're supporting at the moment as that's all that's available in the dom. If we add this in as a full integration we might be able to pull the count from the api :-)
