### ISSUE TITLE
Web app keyboard focus after cmd-tab

### ISSUE THREAD

**Issue by takeo** [wavebox/waveboxapp#93]
* Which version of Wavebox are you using? 3.1.3
* Which Operating System are you using? macOS Sierra

After switching to Wavebox after cmd-tabbing (or opening with e.g. LaunchBar), I usually need to click on the window with the trackpad in order to start using Google Inbox keyboard shortcuts. The Wavebox level shortcuts work, but not the wrapped app ones. I've noticed this in other Electron apps, seems like there's something required to give the wrapped app focus after activating without the mouse.

**Comment by Thomas101** [comment]
Thanks, I'll take a look to see if I can re-focus the Google WebView automatically when the main window gets focused

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which fixes this. You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!
