### ISSUE TITLE
Gmail counter doesn't update after "Send and Archive" if the counter is set to "Show all messages"

### ISSUE THREAD

**Issue by gabriel-r** [wavebox/waveboxapp#930]
* Wavebox Version: 4.6.1
* Operating System & Version: macOS 10.14.3 (18D42)
* Account type (if applicable): Gmail

**Expected & actual behavior**
My counter is set to show all mails, not just unread. The counter is often not updated after archiving the last messages in the Inbox.

**Steps to reproduce**
1. Set the counter to show all messages in Inbox.
2. Get some new mails.
3. (NEW) "Send and Archive" one or multiple messages
4. Archive any remaining Inbox messages, until Inbox zero.
EXPECTED: The counter is cleared.
ACTUAL: The counter still reads `2` or some other number 

**Is the bug persistent or intermittent?**
~It used to happen very rarely before last update. For the past two days, it seems to happen multiple times a day, every time I reach inbox zero.~
_UPDATED: The issue can be reproduced always when using the Send and Archive option._

**Comment by Thomas101** [comment]
Hi thanks for reporting. Syncing the unread count can normally be a little slower when using the `All messages` setting.

When using the other methods the app uses a couple of different metrics to decide when to sync..
* A push channel from Google - Google notifies the app when there is a new email or one gets archived etc. Depending on the responsiveness of Google this can be anywhere from almost instant, to upto a couple of minutes
* The app watches the unread count in the Gmail window for changes, and if this changes we manually trigger a sync - this normally changes as soon as the count changes.

With the `All messages` setting, watching the unread count in the Gmail window is a little unreliable, so for example, if you archive a read email it doesn't trigger a change and we have to wait for Google to tell us about the change down the push channel. I think this is probably the behaviour you're seeing and hence the delay.

Next time it happens, does the count eventually update, or if you right-click on the account and pick `Resync` does it update correctly?

It's probably that Google has been a little slower for whatever reason over the last couple of days - hence the slowdown. Setting the Inbox Type, under settings to one of `Default`, `Important`, `Unread first`, `Starred first`, or `Priority Inbox` and matching to what you're using in Gmail [as per this](https://wavebox.io/kb/gmail-inbox-type) will give the best responsiveness, with the `All messages` setting we have to wait for what Google sends down the wire

**Comment by gabriel-r** [comment]
Hi Thomas,
- Yes, the counter is correctly reset after using the Resync option.
- There's no Inbox Type option like as described in the article, just an
Unread Mode, where I can select my beloved All Messages option.
Thanks!

[image: image.png]

**Comment by Thomas101** [comment]
Thanks, it sounds like it could just be Gmail having a slow few days in notifying the client. It's probably worth leaving it a couple of days and seeing if it improves. If not, I'll take a look this side to see if there's anything we can do to magically detect when the count might change

**Comment by gabriel-r** [comment]
Indeed, things got a lot better today. I'll close this.

**Comment by gabriel-r** [comment]
Found repro streps, updating.

**Comment by Thomas101** [comment]
Thanks for the update,

I've just tried this here and it appears to update for me within less than 3 or 4 seconds. The longest time I had to wait, was still less than the black `Message sent and archived` message
![screenshot 2019-02-28 at 12 12 39](https://user-images.githubusercontent.com/103586/53565756-325fb180-3b52-11e9-9243-59808d50e6f7.png)

I've double checked what Google sends down the pipe and it's sending that the `INBOX` label changed which causes a sync event to fire off.

Could it just be Google being a bit slow again? If you try it again is it still slow?

**Comment by gabriel-r** [comment]
You are right, it was a slow Google day. But it happens a lot more often
recently.

**Comment by Thomas101** [comment]
I've put a patch in - it tries to watch the http messages going out for an archive command. Once seen it prompts the app to resync. I think this should make it a bit more reliable :)

**Comment by gabriel-r** [comment]
Sounds amazing! I don't have the dev tools set up, but I'd be happy to test
if you make a build.

**Comment by Thomas101** [comment]
Thanks @gabriel-r . The latest beta version 4.7.12 has this included. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel)

Let me know how it works :)

**Comment by gabriel-r** [comment]
This seems to work a lot better. It takes a couple of seconds for the counter to update. 
Thank you!

**Comment by Thomas101** [comment]
That's great to hear! The same fix has just gone out into the stable channel in 4.8.0. Thanks!
