### ISSUE TITLE
[v4.7.0] relocation error on additional MFA

### ISSUE THREAD

**Issue by yermulnik** [wavebox/waveboxapp#931]
* Wavebox Version: 4.7.0
* Operating System & Version: Linux Mint 17.3 Rosa (Ubuntu 14.04)
* Install method: Apt-Repo
* Account type: Office 365

**Expected & actual behavior**
Worked in previous version but starting from 4.7.0 crashes on authentication attempt.
Our Org uses Okta as an additional MFA and when Wavebox tries to load Okta auth page it crashes with this error message:
`/opt/wavebox/Wavebox: relocation error: /tmp/.org.chromium.Chromium.3Jpnhp: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

**Steps to reproduce**
Open Wavebox, switch to Office 365 account with Okta MFA enabled and proceed with authentication.

**Is the bug persistent or intermittent?**
Persistent. Cannot log in.

**Additional information**
I've got another Office 365 account set w/o Okta MFA and it works fine.

**Comment by yermulnik** [comment]
This seem to be related to an outdated Ubuntu version I have to use. Upgrade to newer Ubuntu version may help, but at the time being I cannot upgrade. Would it be possible to add Ubuntu 14.04 backward compatibility?

**Comment by yermulnik** [comment]
Not sure which lib Wavebox attempts to use though:
```
> strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | fgrep -wc GLIBCXX_3.4.21
1
```

**Comment by yermulnik** [comment]
JFYI: v4.6.1 crashes too.

**Comment by yermulnik** [comment]
v4.6.0 works just fine.

**Comment by Thomas101** [comment]
Hi, thanks for reporting. It looks like the break is due to an updated electron dependency between 4.6.0 and 4.7.0. Probably [this change](https://bit.ly/2Gm1nXu) upstream is the one that's causing it.

Ubuntu 14 is coming to the end of LTS lifespan in April, so it may be better sticking with 4.6.0 until you get a chance to update to a later version of Ubuntu

**Comment by yermulnik** [comment]
@Thomas101 Thanks for quick update. It seem to me it would be a better idea to maintain support for older OS versions before their EOL at least (bearing in mind that users pay for your app).

Would it be possible to build v4.7.0 with support for Ubuntu 14? This version brings lots of useful updates and I'm not really keen to go through all bureaucracy steps to get my workstation updated because of only one third-party app =(
Thanks in advance.

**Comment by yermulnik** [comment]
Looking into https://github.com/wavebox/waveboxapp/commit/7071ab18c3671ced792c44bd394d0c68bd763759#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 it doesn't seem to be a major versions upgrade and can be reverted to support Ubuntu 14 and postponed to future Wavebox version which can drop Ubuntu 14 support with well-timed announce about dropping support for older OS versions so that users who pay for the app can consider what to do.

**Comment by yermulnik** [comment]
If you could build stand-alone v4.7.0 for Ubuntu 14 I'd be more than happy =)

**Comment by Thomas101** [comment]
The minimum version that Wavebox officially supports has been Ubuntu 16 for a while now. It might be worth trying the snap version of Wavebox as this bundles a bunch of dependencies along with it, but your mileage may vary. If you do try that, you will need to copy your data across [more info](https://wavebox.io/kb/data-when-reinstalling-wavebox).

I've put a tar version of 4.7.0 with the older electron which you can download [here](http://wavebox.io/dl/builds/Wavebox_4_7_0_linux_x86_64_el3_0_13.tar.gz). This isn't supported at all, but may help you for the next few weeks until you get a chance to upgrade Ubuntu. You may want to disable the update check under settings as this will nag you next time there's a new version.

**Comment by yermulnik** [comment]
@Thomas101 Thanks for your time and effort. Unluckily tar-gzip'ed version you've put crashes with all the same error =( Is there a way I can play with deps versions myself? E.g. edit some files and/or build something?

Will see whether Snap way would be feasible for me anyways.

Thanks again.

**Comment by Thomas101** [comment]
@yermulnik did the Snap version work for you? Am I okay to close this off?

**Comment by yermulnik** [comment]
@Thomas101 nope, Snap just doesn't work on my kind of legacy installation =( Anyways please go ahead and close this issue since Wavebox is not going to support 14.04 if I got things right.
