### ISSUE TITLE
Right click menu: "Copy" for images

### ISSUE THREAD

**Issue by redfellow** [wavebox/waveboxapp#934]
**Is your feature request related to a problem? Please describe.**
In order to copy an image from wavebox to the clipboard, I need to first open the image in browser by right clicking and selecting `Open Image in Browser`, and then I can right click to `Copy` in my Browser to get the image on my clipboard.

**Describe the solution you'd like**
It would be neat if I could do this without the extra step, would make sharing images directly (without urls) from a Wavebox tab much easier.

**Comment by Thomas101** [comment]
Added this, not sure why it was missing!

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.7.1). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!

**Comment by redfellow** [comment]
Works great, nice! 👍
