### ISSUE TITLE
Add ability to edit url in address bar

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [wavebox/waveboxapp#936]
This will enable to use Wavebox like a browser.

**Comment by apidevlab** [comment]
Just about to post the same. I understood that's exactly what it meant if you needed to interact with some sites, twitter is one example. Say to copy the URL to a tweet. That's you cannot utilise the browser URL is rather strange IMHO but would suggest there IS probably a logic behind it.

**Comment by Thomas101** [comment]
Also related #709 #637

**Comment by Thomas101** [comment]
I'll see if we can get this in during the next beta cycle :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
