### ISSUE TITLE
Conflict between link rule "open in service tab" and weblink "restore last page on load"

### ISSUE THREAD

**Issue by TheSpyder** [wavebox/waveboxapp#937]
* Wavebox Version: 4.7.0
* Operating System & Version: macOS 10.14.4 beta

**Expected & actual behavior**

When using the new ability to open a link in a service tab, the link should open regardless of other settings. What I'm seeing is if a weblink tab is asleep, it opens the last URL instead of the link I clicked on.

**Steps to reproduce**

1. Create a service tab from a weblink
2. Turn on "restore last page on load" for this service
3. Sleep the service tab
4. Create a link rule to open something in this service tab (or use a modifier key to open the "ask" prompt and target the service tab)
5. Click a link that matches the rule

I have a weblink service tab in my google account pointing to a CI server which I use a lot for clicking on code review links in my email.

If the tab goes to sleep the next link I click on doesn't open. Instead the tab restores the URL it had before it went to sleep. This can be quite disconcerting.

**Is the bug persistent or intermittent?**

Persistent

**Additional information**

Opening links from a different account _does_ wake up the tab and navigate correctly (e.g. a slack link to the CI server). It only seems to happen when opening links within an account. It also doesn't seem to effect default service tabs - if I target a random link from my gmail to the sleeping google drive tab it works - just web link tabs.

I can't show you my exact replication case due to the private nature of the content, but if you can't reproduce it I'll find a more open setup that I can take a video of.

**Comment by Thomas101** [comment]
Thanks, it looks like a timing issue that is made worse when the picker automatically opens the url. At the moment if the target tab isn't ready within 500ms it just fails silently. I've changed it to retry every 200ms for the first 4 seconds. If the tab isn't ready within that time something's wrong!

**Comment by Thomas101** [comment]
I've just pushed 4.7.1 with a fix in :). Thanks again

**Comment by TheSpyder** [comment]
Working well for me, thank you 👌

I'm in Australia, it's not unusual for websites to take a few seconds to load 🤣
