### ISSUE TITLE
Strange One Fonts Changed

### ISSUE THREAD

**Issue by ChaeRiley** [wavebox/waveboxapp#94]
* Which version of Wavebox are you using? [e.g. 3.1.5 Pro Version]

* Which Operating System are you using? [e.g. Windows]

Upgraded to Pro last night on my PC at home, came into the office today and Wavebox looked as normal, logged into Waveboxpro, chose my email account that activated Pro, that went fine but the problem is when I go back to the main UI all the gmail inbox headers/font has changed

![capture1](https://cloud.githubusercontent.com/assets/25952222/25156349/188b476e-24ee-11e7-8c18-0430370e3d1f.JPG)
![capture2](https://cloud.githubusercontent.com/assets/25952222/25156350/188ba93e-24ee-11e7-878f-7a94eaa63afb.JPG)
![capture3](https://cloud.githubusercontent.com/assets/25952222/25156351/18906cbc-24ee-11e7-9575-c3a036ed42bf.JPG)
![capture4](https://cloud.githubusercontent.com/assets/25952222/25156352/18920482-24ee-11e7-95dc-57cbb9a0aa0d.JPG)

**Comment by ChaeRiley** [comment]
Problem solved...prior to me updating Wavebox to Pro version on works PC - Some of the design/graphics software that we used had updated and had loaded the following font on...

helvetica-neue-bold

This was the problem as somewhere in Wavebox CSS somewhere there must be that font called up...once I removed it Wavebox UI/Fonts looked fine again.

**Comment by Thomas101** [comment]
Glad you managed to fix the problem. Will close this issue off :)
