### ISSUE TITLE
Some services eg Trello and Slack use their 'own' notification/icons base

### ISSUE THREAD

**Issue by apidevlab** [wavebox/waveboxapp#940]
* Wavebox Version: 4.7.2
* Operating System & Version: Windows 10

**Is your feature request related to a problem? Please describe.**
Some services eg Trello and Slack use their 'own' notification/icons bases on your url of their services

**Is your feature request related to an account type?**
Trello, Slack mabe others

**Describe the solution you'd like**
The ability to 'override' their default icon with the standard custom icons e.g. Trello Icon with the unread notification. I know I can upload my own but thats not an ideal solution to what should possibly be easy to 'fix' so to speak.

**Additional info**
Any other information or screenshots that might help us.

**Comment by Thomas101** [comment]
Just to double check, is that you want to be able to upload a separate icon for the account in the sidebar and for the notification icon?

**Comment by apidevlab** [comment]
Exactly that... I like the site logos over the 'service' ones and while the option is there to use a custom logo a: I don't know where (or indeed if you store logos you use in the app) and b: It means hunting for a logo otherwise. A switch to use default 'brand' logo rather than 'service' would be great IMHO

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. The appearance section under services now has an option to set as default...

![screenshot 2019-03-07 at 10 07 19](https://user-images.githubusercontent.com/103586/53948922-d3a1b700-40c0-11e9-88d7-f967daae7ffe.png)

If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by apidevlab** [comment]
Hi @Thomas101 absolutely superb addition, very niche but has made my day, another reason to use WaveBox as my now daily driver. Many thanks for implementing this.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
