### ISSUE TITLE
Mac keyboard shortcuts not clear

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#941]
* Wavebox Version: 4.7.2
* Operating System & Version: macOS 10.11 & 10.12

Looking at https://blog.wavebox.io/be-a-keyboard-shortcut-master/

<kbd>Command <</kbd> and <kbd>></kbd> to switch does not work. 
I assume this means <kbd>Shift Cmd ,</kbd> which opens Wavebox preferences.
Or does `< >` mean arrow keys? Not clear!

![image](https://user-images.githubusercontent.com/466557/52910504-18e07f00-32a1-11e9-96a4-dd18cc29c462.png)
![image](https://user-images.githubusercontent.com/466557/52910508-2f86d600-32a1-11e9-845a-6ff298e1113b.png)

How do I switch to next/prev account?
How do I switch to next/prev service?
How do I switch to next/prev tab?

**Comment by Thomas101** [comment]
<kbd>></kbd> and <kbd><</kbd> refer to the chevron/greater than/less than keyboard keys. On a mac keyboard, you'd normally need to use <kbd>Shift</kbd> to access these.

That said, it looks like there's some kind of problem with <kbd>Cmd</kbd>+<kbd><</kbd> in that it's triggering settings for some reason. I'll see if I can get to the bottom of this

**Comment by Thomas101** [comment]
Hey a fix for this has just gone out in 4.7.3. Thanks!
