### ISSUE TITLE
Separate window not "active" (doesn't have focus) when switching to it by keyboard

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#942]
* Wavebox Version: 4.7.2
* Operating System & Version: macOS 10.11 & 10.12
* Account type (if applicable): Gmail/gDocs

**Expected & actual behavior**
When I open a Google Doc in a "new window", then switch away from it and then back using keyboard, I expect to be able to start typing without having to click in the window with the mouse.

**Steps to reproduce**
Open Google doc in new window, switch back to main window, or to another app, then switch back via keyboard (cmd-tab or cmd-`)

**Is the bug persistent or intermittent?**
persistent

Maybe related to https://github.com/wavebox/waveboxapp/issues/477

**Comment by Thomas101** [comment]
Thanks. I've only managed to reproduce this with Google drive docs. There's also the odd instance in which it seems to work but maybe 1 in 20. I'll see what's going on!

**Comment by dzg** [comment]
Thanks! 
I noticed this also with Evernote ... even when not separate window. Just switch away and back with cmd-tab, and it doesn't have focus.
I suspect most "live writing" sites will have this ...

**Comment by Thomas101** [comment]
Thanks for reporting with Evernote too. Managed to find a fix for both and we'll be pushing a new release out in the next couple of days :)

**Comment by Thomas101** [comment]
Hey a fix for this has just gone out in 4.7.3. Thanks!
