### ISSUE TITLE
Option to set (or remember) size of popup browser window

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#945]
* Wavebox Version: 4.7.3
* Operating System & Version: Mac

When opening a link in a popup WB window, it seems to always open at 800x600.

Would be nice to be able to change this size, or at least remember how I resized it.

Thanks

**Comment by Thomas101** [comment]
I agree, I think there is some more work to do here. I'll have a look at where it's getting the current settings from.

I was thinking it would be good to grab the size from the parent window and match that (the same way chrome does when opening a new window). What do you think?

**Comment by dzg** [comment]
> grab the size from the parent window

I think that would be a great start.

For me the ideal thing would be for it to remember my "most recent resize" per account or service. So once I resize, say, an Evernote popup, all future Evernote popups will be the same size.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
