### ISSUE TITLE
Version 4.7.10beta not running on 10.11.6

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#946]
* Wavebox Version: Version 4.7.10beta
* Operating System & Version: macOS 10.11.6

Doesn't run on 10.11.6 ... am I stuck on 4.7.3?

![image](https://user-images.githubusercontent.com/466557/53178406-7571d000-35fa-11e9-9cd0-1f0a7d48bfc0.png)

**Comment by Thomas101** [comment]
Thanks. Managed to reproduce here and think we have a fix :)

**Comment by Thomas101** [comment]
I've pushed a fix out in 4.7.11. You will probably need to [re-download the dmg for the release](https://github.com/wavebox/waveboxapp/releases/tag/v4.7.11) and drag it over the previous version :)
