### ISSUE TITLE
How to set up Proxy Server?

### ISSUE THREAD

**Issue by remmina** [wavebox/waveboxapp#947]
As we all know, Gmail cannot be logged in in China, so proxy servers need to be set up.

But I didn't find any settings for proxy servers.

Network settings like Socks5 and HTTPS.

Maybe I didn't see it?

Thanks.

**Comment by Thomas101** [comment]
Hi, it should pick the proxy settings up from your operating system and use those automatically. Which OS and version are you using?

**Comment by remmina** [comment]
Ubuntu 18.04 64 bit

Setting up a proxy server for the entire system is a hassle

Because if you modify the proxy server of the entire system, other software will also be affected, such as the browser.

I just want to make the wavebox use a proxy server.

I remember that telegram has this feature, like this:

![image](https://user-images.githubusercontent.com/47842757/53239990-67927c80-36d8-11e9-8251-f6f23a13e305.png)

**Comment by Xeonacid** [comment]
Would [ProxyChains](http://proxychains.sourceforge.net/) work?

**Comment by remmina** [comment]
@Xeonacid It should be working properly.
But that needs to be started from the terminal, I think it is not very convenient.
I remember that wavebox can be started with parameters.
The parameter format is the same as chrome.
Proxy server can also be set with parameters.
But this is still not very convenient.

**Comment by Thomas101** [comment]
I agree the command line isn't a great way to do it. I'll have a look to see if we can add something into the next beta :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. You can find the proxy settings under `Settings` > `Network`

![screenshot 2019-03-07 at 10 04 55](https://user-images.githubusercontent.com/103586/53948787-83c2f000-40c0-11e9-98d5-750c621d51de.png)

Alternatively, if you find yourself locked out of the app on-launch you can change the proxy settings from the connection screen too.


If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by remmina** [comment]
It works well.
Thanks very much.
I wish you a happy life.

**Comment by MurzNN** [comment]
Thanks, for implementation, does it allow to set per-service proxy, or only one for all services?

**Comment by Thomas101** [comment]
@MurzNN only for all services at the moment
