### ISSUE TITLE
Trello links in Google Calendar (in Dutch: Agenda) gives empty about:blank in Trello app 

### ISSUE THREAD

**Issue by Ymetro** [wavebox/waveboxapp#948]
* Wavebox Version: 4.7.3
* Operating System & Version: Windows 10
* Account type (if applicable): Google account, especially Google Calendar, and Trello

**Expected & actual behavior**

Expected behavior:
That if I click a link of a Trello board it will go there in the installed Trello app tab window (not a new Wavebox window or a Chrome tab) 

Actual behavior:
Made a rule for all the links opening in the default browser (in my case Chrome) and the Trello board links in the Google Calendar also open in the default browser, because Google adds a `"google.com"` before the `"trello.com"` part of the link in Google Calendar appointment popup like: `"https://www.google.com/url?q=https%3A%2F%2Ftrello.com%2Fb%2F...(etc)"` 

Not sure if this is a bug or a feature request, but it would be nice to see that the links system can be fine tuned to add the `"https://www.google.com/url?q=..."` part with the Trello part `"https%3A%2F%2Ftrello.com..."` to be a seperate rule or exeption. Otherwise when adding a rule with Google.com q=Trello would open an empty `about:blank` page in the Trello app tab. As what I have experienced. 

Is there a way for the user to set this up already, which I might have missed, or is it something to develop on in future versions of Wavebox? 

The point is that I would like to see Trello links in Google Calendars appointment popup (one click on the appointment) to open in the Trello tab and still open Gmail links in the external Chrome browser.

**Comment by Thomas101** [comment]
Thanks for the detailed description - I've got a fix together which will be out next beta :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Ymetro** [comment]
Hi. Tested the 4.7.12beta release and added the rule. Works great! Thank you.

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
