### ISSUE TITLE
Slowness in Trello boards and Wavebox Settings?

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#949]
* Wavebox Version
  4.7.11beta **_(always on the Beta update channel)_**
* Operating System & Version
  Windows 10
* Account type
  Trello and Wavebox Settings

I am experiencing super slow response to user input (mouse clicks and scrolling) in **Trello**. It's been at least 3 weeks but I've been to busy to report the issue, sorry. 😃

For now, I've switched over to my browser for Trello interactions but I'm hoping to help troubleshoot so this can get fixed.

Interestingly, I hadn't experienced slowness anywhere else until I opened the **Wavebox Settings** section to get the version number. It also behaves very slowly, exactly like Trello boards.

Just me? Let me know if I can help troubleshoot in any way.

Thanks! 👍
Jeremy

**Comment by Thomas101** [comment]
Thanks for reporting. It would be good to get some more info.

Would you be able to open up Settings > Debug > Task manager and take a screenshot in two instances...
1. When trello is active in the main window
2. When something else (e.g. gmail) is active in the main window

Also a few other things...
* Is it slow straight after launching Wavebox or is it only slow after it's been running for some time?
* Do you have any extensions installed?
* Does adding a second trello exhibit the same behaviour?
* Does going to Settings > Advanced and disabling hardware acceleration make any difference?

Thanks!

**Comment by GollyJer** [comment]
OK, this is super weird... and probably typical... 🤪

Yesterday, when I went to provide you information Trello was working perfectly... no issues.  It hadn't worked for at least 3 weeks. The only thing I messed around with was toggling Hardware Acceleration. But now, whether it's on or off, Trello works as expected.

My version of Wavebox hasn't changed so the only thing I can think of is the extensions I use might have been causing an issue and got updated?  Here's the ones I use in case it's helpful.

![image](https://user-images.githubusercontent.com/689204/53515901-e5aba600-3a7f-11e9-97ac-7677a0d1c085.png)


👇 **Other Issue** 👇
As for the Wavebox Settings page being slow... it is 100% tied to Hardware Acceleration being turned OFF. It is brutally slow when OFF. It works as expected when ON.

**Comment by Thomas101** [comment]
> Yesterday, when I went into troubleshooting mode Trello was working perfectly...

This could be a couple of things then...
1. Trello updated something
2. Windows update ran and updated a graphics driver maybe?

> As for the Wavebox Settings page being slow... it is 100% tied to Hardware Acceleration being turned OFF. It is brutally slow when OFF. It works as expected when ON.

When Trello was causing slowness, this would have also affected the settings ui as it's overlayed atop of Trello. When you switch to another tab, the Trello tab would have been put into low power mode, hence the settings ui would have sped up. With Hardware Acceleration off, more of the rendering is pushed onto the cpu, which means things like settings screen can slowdown.

If it's fixed itself, am I okay to close this off? I would be interested in which CPU, RAM and Graphics card you have in the machine - we can see if we can reproduce the slowness and improve on it at all.

**Comment by GollyJer** [comment]
Here's a copy/paste out of CPUZ.
Not the best format but at least it gets you the info. and might help.

Feel free to close this issue. 

Cheers,
Jeremy


Processors Information
-------------------------------------------------------------------------
Socket 1			ID = 0
	Number of cores		2 (max 2)
	Number of threads	4 (max 4)
	Name			Intel Core i7
	Codename		Kaby Lake-U/Y
	Specification		Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
	Package (platform ID)	Socket 1356 FCBGA (0x7)
	CPUID			6.E.9
	Extended CPUID		6.8E
	Core Stepping		B0
	Technology		14 nm
	TDP Limit		15.0 Watts
	Tjmax			100.0 °C
	Core Speed		1496.3 MHz
	Multiplier x Bus Speed	15.0 x 99.8 MHz
	Base frequency (cores)	99.8 MHz
	Base frequency (ext.)	99.8 MHz
	Stock frequency		0 MHz
	Max frequency		0 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, AES, AVX, AVX2, FMA3
	Microcode Revision	0x8E
	L1 Data cache		2 x 32 KBytes, 8-way set associative, 64-byte line size
	L1 Instruction cache	2 x 32 KBytes, 8-way set associative, 64-byte line size
	L2 cache		2 x 256 KBytes, 4-way set associative, 64-byte line size
	L3 cache		4 MBytes, 16-way set associative, 64-byte line size
	Max CPUID level		00000016h
	Max CPUID ext. level	80000008h
	Cache descriptor	Level 1, D, 32 KB, 2 thread(s)
	Cache descriptor	Level 1, I, 32 KB, 2 thread(s)
	Cache descriptor	Level 2, U, 256 KB, 2 thread(s)
	Cache descriptor	Level 3, U, 4 MB, 16 thread(s)
	FID/VID Control		yes

Chipset
-------------------------------------------------------------------------

Northbridge			Intel Kaby Lake rev. 02
Southbridge			Intel Kaby Lake-Y PCH rev. 21
Graphic Interface		PCI-Express
Memory Type			DDR4
Memory Size			16 GBytes
Channels			Dual
Memory Frequency		1064.1 MHz (1:16)
CAS# latency (CL)		15.0
RAS# to CAS# delay (tRCD)	15
RAS# Precharge (tRP)		15
Cycle Time (tRAS)		35
Row Refresh Cycle Time (tRFC)	374
Command Rate (CR)		1T
Uncore Frequency		698.3 MHz
Host Bridge			0x5904

Memory SPD
-------------------------------------------------------------------------

DIMM #				1
	SMBus address		0x50
	Memory type		DDR4
	Module format		SO-DIMM
	Manufacturer (ID)	A-Data Technology (7F7F7F7FCB000000000000)
	Size			8192 MBytes
	Max bandwidth		DDR4-2400 (1200 MHz)
	Part number		AO1P24HC8T1-BQXS  
	Serial number		2E730100
	Manufacturing date	Week 08/Year 17
	Nominal Voltage		1.20 Volts
	EPP			no
	XMP			no
	AMP			no

Display Adapters
-------------------------------------------------------------------------

Display adapter 0	
	ID			0x4000000
	Name			Intel(R) HD Graphics 620
	Board Manufacturer	Hewlett-Packard
	PCI device		bus 0 (0x0), device 2 (0x2), function 0 (0x0)
	Vendor ID		0x8086 (0x103C)
	Model ID		0x5916 (0x82C1)
	Revision ID		0x2
	Performance Level	0

Display adapter 1	
	Name			LuminonCore IDDCX Adapter
	Board Manufacturer	0x0000 (0x0000)
	Performance Level	0

Display adapter 2	
	ID			0x1000000
	Name			NVIDIA GeForce 940MX
	Board Manufacturer	Hewlett-Packard
	Memory size		2 GB
	Memory type		GDDR5
	Memory vendor		Samsung
	PCI device		bus 1 (0x1), device 0 (0x0), function 0 (0x0)
	Vendor ID		0x10DE (0x103C)
	Model ID		0x134D (0x82C1)
	Revision ID		0xA2
	Performance Level	0

**Comment by Thomas101** [comment]
Thanks for the info, that's really great!

Let me know if it comes up again :)
