### ISSUE TITLE
Canceling download doesn't remove it from active downloads

### ISSUE THREAD

**Issue by dzg** [wavebox/waveboxapp#950]
* Wavebox Version: 4.7.11
* Operating System & Version: macos 10.11.6

Sometimes clicking "X" to cancel a download in download list doesn't work. Not sure how to reproduce. Seems like download stops, but 

1. Icon continues to show progress bar
![image](https://user-images.githubusercontent.com/466557/53397159-0eb03600-39af-11e9-8ccd-4786dda88a12.png)

2. Shows "0%"
![image](https://user-images.githubusercontent.com/466557/53397222-3f906b00-39af-11e9-92ef-8a7564bd00f1.png)

3. Task remains in download list, usually until restart Wavebox.

**Comment by Thomas101** [comment]
I'm struggling to reproduce here - do you remember where or what you tried downloading?

**Comment by dzg** [comment]
Last time it was something from google drive ... 
I will try to gather more info on what causes this.

**Comment by Thomas101** [comment]
I think I've found it...
* Start download
* When prompted where to save, click cancel
:)

**Comment by dzg** [comment]
Ha, that sounds like something I would do.

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
