### ISSUE TITLE
Gmail shift pop-out message doesn't work

### ISSUE THREAD

**Issue by caldwed** [wavebox/waveboxapp#953]
* Wavebox Version: 4.7.11 (beta)
* Operating System & Version: Ubuntu 18.04 (xfce)
* (Linux only) Install method: deb
* Account type (if applicable): Gmail

After starting a new message in Gmail from the Compose button, the shift-click on the arrow to pop out the message into a new window does not work. I expected it to pop out into a new Wavebox window, but it instead creates a new tab in my default browser... that is unfortunately blank.

**Comment by Thomas101** [comment]
Have you changed the Link opener settings under Settings > Links?

If you change Shift+Click to open in the default browser it will break the Gmail popout window

**Comment by caldwed** [comment]
Ah... That was it. I was playing with the setting for the account to see if I could fix it.

I guess it would be nice to have the best of both worlds. I had wanted to have links opened in my browser.

As a side-note, the pop-out editor window still worked correctly in O365, which is why I didn't think to look at any more global settings.

**Comment by Thomas101** [comment]
> I guess it would be nice to have the best of both worlds. I had wanted to have links opened in my browser.

We do know it's going to break though, so I've put a change in that will disallow shift+click on this link :)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
