### ISSUE TITLE
Allow access to Wavebox when using external login pages

### ISSUE THREAD

**Issue by Ash258** [wavebox/waveboxapp#955]
* Wavebox Version: 4.7.11Beta other versions aswell I guess
* Operating System & Version: Windows 10 1809, 17763.316
* Account type (if applicable): Gmail, Outlook

**Expected & actual behavior**
When you are trying to sign into Outlook, you are probably prompted to enter security code, which is sent to your email you used for registering (corporate, gmail, ...). I have all my mails inside Wavebox and when i was prompted to enter code, i cannot retrieve it, since whole Wavebox was covered with white window with something like "Sign in to account in new window" (Screenshot 2) and cannot access main window and gmail account inside Wavebox have to go to browser and open google mail and copy code from there.

This could be "intentional" to not loose some session / context / state, but it's uncomfortable for user to sign into browser to mail and retrieve code.

**Steps to reproduce**

1. Add Outlook Account
    1. Or in my case sync profile and reauthenticate
1. Sign In
1. Try to access gmail within wavebox

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
In second screenshot you could see window, which blocks main window interactions.

![ScreenShot](https://i.imgur.com/lDXY1ts.jpg)

![Main window](https://user-images.githubusercontent.com/13260377/53549135-b9e9f800-3b33-11e9-9550-16a2e73dee55.png)

**Comment by Thomas101** [comment]
It's mostly there to stop people getting confused and keep them going through the add process. On the flip side of that, this is a completely valid use case :).

I've added a minimize button and also enabled clicking on the backdrop to minimize :)

![screenshot 2019-02-28 at 14 14 00](https://user-images.githubusercontent.com/103586/53572726-d56cf700-3b63-11e9-827e-d6cebe8fec84.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.7.12. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
