### ISSUE TITLE
Skype error

### ISSUE THREAD

**Issue by nicolafarina** [wavebox/waveboxapp#956]
* Wavebox Version: 4.7.3
* Operating System & Version: Windows 10
* Account type (if applicable): Skype

Since some days, Skype crash and reload 
![image](https://user-images.githubusercontent.com/16633188/53574888-cb9dc080-3b70-11e9-8ec2-c5c9f2dce2e1.png)

**Comment by Thomas101** [comment]
Does this happen on launch or after you've done something (e.g. start video call)?

Just as a catch-all, if you go to the account settings and under advanced double click `Clear all browsing data` does this make any difference?

**Comment by nicolafarina** [comment]
Using it (not at start/login), seems total unpredictable.

Just happened simply getting focus on Skype window clicking on the chat.

I can try clear the browsing data.

**Comment by Thomas101** [comment]
I think they normally bind to `window.onerror` so it's just like a catch-all and reload. Did clearing browser data work?

If not, I'll see if I can reproduce here. Just so I've got a similar environment, 
* Are you on a pretty stable connection or have you been switching networks with it open etc?
* Do you have any extensions installed?

**Comment by nicolafarina** [comment]
Well, let me test some days. Maybe resetting is getting good.

Totally stable connection anyway (tested more) and no extensions at all.

Thanks for support as usual.

**Comment by Thomas101** [comment]
No problem, keep me up to date :)

**Comment by nicolafarina** [comment]
Seems all works fine now. Thanks.

**Comment by Thomas101** [comment]
Awesome, thanks I'll close off. Let me know if it comes back up! :)
