### ISSUE TITLE
Provide a way to scale the ui

### ISSUE THREAD

**Issue by iocanel** [wavebox/waveboxapp#958]
* Wavebox Version: 4.7.x
* Operating System & Version: all

**Is your feature request related to a problem? Please describe.**
Some information about what the problem is.
For some apps the fonts are two small to read.

**Is your feature request related to an account type?**
No

**Describe the solution you'd like**
I'd like to be able to scale up/down the ui in a similar way I can do it in chrome.

**Additional info**

**Comment by nmat** [comment]
There is a possibility to zoom the page in and out using Ctrl++, Ctrl+- and Ctrl+0

To change icon sizes in wavebox and so on you can change:

Sidebar Size:

and much more

![image](https://user-images.githubusercontent.com/383031/53682281-59ee7f80-3cf4-11e9-9eae-d533c8666b0d.png)

In this case I wonder what type of scale you want to change. You also have the view menu where you can change the size of various items:

![image](https://user-images.githubusercontent.com/383031/53682297-94f0b300-3cf4-11e9-8d17-7a7fe48062b2.png)

**Comment by nmat** [comment]
There is also the possibility to change even more.

You can read about it here: 
https://wavebox.io/kb/change-theme
https://wavebox.io/kb/lock-sidebar
https://wavebox.io/kb/resize-sidebar

And many more. Most of which are located in the knowledge base. As mentioned before I am not sure which sort of size change you want to change. I myself use Ctrl+-, Ctrl++ and Ctrl+0 to change sizes for the content.

**Comment by iocanel** [comment]
@nmat: Thank you so much! Ctrl + and Ctrl - does the trick for me. Even better seems that my settings persist restarts too.

I am covered and thus closing the issue.

**Comment by nmat** [comment]
@iocanel thats perfect! You are most welcome
