### ISSUE TITLE
Cannot Create Second zoho mail account

### ISSUE THREAD

**Issue by 2635599** [wavebox/waveboxapp#960]
i'm on the latest wavebox version installed via terminal on linux mint cinnamon 19.1 64 bit. i installed wavebox 8 days ago to give it a run and have been very impressed with it. have several gmail accounts, youtube, vineo, facebook, twitter, and plex media server. the time it saves with gmail alone is simple incredible. my issue is with zoho mail. i added a zoho.com account and it works great, however i have a second zoho account ay zoho.eu. when i added if i click it's icon and i was last in the .com account that is what opens instead of the .eu account. how do i make each icon strictly open with the domain i set them for and the the other? thanks

**Comment by nmat** [comment]
not sure what you mean really. However you can try to add:

1. With the Service Zoho (.com)
2. Add a "Add any Website" (.eu)

That would make one with the built in standard information go to the .com and the other to .eu.

**Comment by 2635599** [comment]
i did it that way cause zoho.eu isn't listed and if i was just in zoho.com clicking either icon would open .com 

yea by accident i added .eu to plex and .eu loads fine from there, so yea once i fix the plex one to only be plex i'll add the .eo to the .com zoho. thanks for the help

**Comment by nmat** [comment]
Hope it works out. :)

**Comment by Thomas101** [comment]
Am I okay to close this, or do you still need some help?
