### ISSUE TITLE
Provide a command pallete.

### ISSUE THREAD

**Issue by iocanel** [wavebox/waveboxapp#961]
* Wavebox Version: future
* Operating System & Version: all

**Describe the solution you'd like**
As a software developer I'd like to be able to create custom scripts/commands similar to `compose email` (e.g. `create new jira issue`, `tweet` etc) that I would be able to call from a command pallete (similar to the one provided by vscode or emacs) or just assign a shortcut.

**Comment by nmat** [comment]
Similar to: https://github.com/wavebox/waveboxapp/issues/244 ?

**Comment by iocanel** [comment]
Hmmm, the way I see it, its more like a superset of #244 which is more about switching between acounts. 

I'd like to take it one step further and automating things by integrating custom scripts (if thats possible and makes sense).

**Comment by nmat** [comment]
Well in that case I think that a API for calls would be "better" and use that to get things done.

Having the API calls in a command palette might be cluttering to a normal user. But then again. Its something that the main developers need to decide I think.

**Comment by Thomas101** [comment]
We're looking to add support for more functionality into the quick switch, and this is definitely one feature we want to add in.

There's scope for built-in commands, compose already being one that's there on some accounts, just not exposed to the quick switch. Tweet, Jira etc are other great examples.

@iocanel We're working on a service api which would let you run custom scripts in services that have been added. Would you be interested in hooking up some custom scripts?

**Comment by iocanel** [comment]
@Thomas101: I'd love to be able to hook up custom scripts! And I'd love to contribute in any way possible.

**Comment by Thomas101** [comment]
@iocanel that's just gone out in the latest beta 4.7.12. We've added `/tweet` `?twitter` `@twitter` and `/email` in this run. Our [wavebox-service-api](https://github.com/wavebox/wavebox-service-api) repo has docs on how to create your own. Let us know what you think!

Also, if you're not on the beta channel - [instructions here](https://wavebox.io/kb/beta-channel)

**Comment by Thomas101** [comment]
This has just gone out on the stable channel in version 4.8.0. Thanks!

**Comment by iocanel** [comment]
That looks fantastic. I'll play with it ASAP.
