### ISSUE TITLE
[Bug] - Moving service icon outside of borders locks it to mouse

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#962]
* Wavebox Version: git master 2019-03-04
* Operating System & Version: windows 10
* Account type (if applicable): any

**Expected & actual behavior**
Should not lock it to mouse on release but just move it back to original position. (just like Esc)

Locks to mouse when releasing left button click. 

**Steps to reproduce**
1. Take any service in the left menu
2. Move it outside of border to the right and release left mouse button when moving

Now moves with mouse without you holding the button.

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/53756029-68859400-3eb8-11e9-9546-725b52ed654a.png)

**Additional information**
Only tested on windows 10.

**Comment by Thomas101** [comment]
Thanks, I see the same on macOS

**Comment by nmat** [comment]
awesome! I think there was a work around for it before but I can't remember the commit. :/

**Comment by Thomas101** [comment]
It looks like a change in electron4. The webview gobbles the mouse events when you drag over it which means the icon gets stuck until you return to the sidebar.

https://github.com/wavebox/waveboxapp/commit/b6d75ad1e387262a1c0170881aa304b208b2019e should fix this :)

**Comment by nmat** [comment]
works perfectly!

**Comment by Thomas101** [comment]
That's just gone out in the latest beta, thanks! :)
