### ISSUE TITLE
Custom link openers not working in Ubuntu Linux

### ISSUE THREAD

**Issue by JorgeRdg** [wavebox/waveboxapp#965]
* Wavebox Version: 4.7.3
* Operating System & Version: Ubuntu 18.04
* (Linux only) Install method: Snap package
* Account type (if applicable): Happens with every account

**Expected behavior**
When defining a custom link opener, using it should open the link using the command specified.

**Actual behavior**
Nothing happens when I open a link using the custom opener. I've tried using both the global command in the path and the full path and the same issue is produced. I opened Wavebox in a terminal to look at the output and I could see the following error:
```
➜  ~ wavebox 
[uncaughtException] spawn firefox ENOENT Error: spawn firefox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[uncaughtException] spawn /usr/bin/firefox ENOENT Error: spawn /usr/bin/firefox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Seems like an issue in the way the application is running the command in the shell.

**Steps to reproduce**
Set custom link opener to open a link with any other app (e.g. Firefox or Chrome).

**Is the bug persistent or intermittent?**
It always happens.

**Screenshots**
![Wavebox configuration](https://user-images.githubusercontent.com/1122277/53877493-9a5a4000-4009-11e9-925c-b52040683f27.png)
![Output in terminal](https://user-images.githubusercontent.com/1122277/53877501-9d553080-4009-11e9-8869-67cbd9d3433f.png)

**Additional information**
The exact same thing happens also with Chrome, so I'd bet it's not related to the command used, but rather something off in the code in charge of running it. Not a NodeJS expert, but wondering if the solution might be somewhere in here: https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

Let me know if you need anything else! Thanks for the awesome app :)

**Comment by nmat** [comment]
Do you get the same error when using .deb package from original source?

I am wondering if it might be up to the snap package?

**Comment by Thomas101** [comment]
This will be down to the confinement that snap uses. This probably isn't something we're going to be able to support with the snap version of Wavebox as it doesn't use the standard xdg-open protocol, so I'll disable it an upcoming release.

If you want to use it, I'd recommend using one of the other install methods (https://wavebox.io/download). The apt repository gives the best for features and easy updates. If you do decide to switch, you'll need to re-setup your accounts when switching. The profile sync will get you most of the way https://wavebox.io/kb/profile-sync

**Comment by JorgeRdg** [comment]
You're both right, it worked perfectly with the `.deb` package. Didn't know snaps included such limitations! Maybe it's worth it adding some notes here in the repo and/or when downloading.

Anyway, thank you so much for the help. The app's great! :smiley:

**Comment by Thomas101** [comment]
> Didn't know snaps included such limitations!

There are quite a few hoops you have to jump through!

In-app I've added an info message and disabled the add button on Snap. Did you download the Snap through the Ubuntu App Store or find it through our website?

> Anyway, thank you so much for the help. The app's great! 😃

Great to hear you're enjoying it :)

**Comment by JorgeRdg** [comment]
> Did you download the Snap through the Ubuntu App Store or find it through our website?

Through the website IIRC

**Comment by Thomas101** [comment]
Hi, the disabled message on snap has just gone out in the latest version of Wavebox (4.8.0). Thanks!
