### ISSUE TITLE
Special paste (ctrl-V) pastes double on Linux

### ISSUE THREAD

**Issue by udl** [wavebox/waveboxapp#967]
* Wavebox Version: 4.7.3
* Operating System & Version: Ubuntu 18.10
* (Linux only) Install method: Debian installer
* Account type (if applicable): all [tried for Slack, Google hangouts chat, whatsapp]

**Expected & actual behavior**
When I paste something with special paste (ctrl+V), the text from the clipboard is inserted double. It should be inserted just once.
Example:
Clipboard has: "Interesting text"
ctrl+v pastes: "Interesting text"
ctrl+V pastes: "Interesting textInteresting text"

**Steps to reproduce**
* Copy a text from somewhere
* ctrl+V paste to whatsapp/slack input field

**Is the bug persistent or intermittent?**
Always

**Additional information**
Maybe https://github.com/atom/atom/issues/1945 is related?

**Comment by Thomas101** [comment]
Thanks!

**Comment by Thomas101** [comment]
Hi, a fix for this has just been released in the latest version of Wavebox (4.8.0). You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
