### ISSUE TITLE
Macbook with external graphics card issue

### ISSUE THREAD

**Issue by chrisblossom** [wavebox/waveboxapp#968]
* Wavebox Version: `4.7.3`
* Operating System & Version: `Mac OSX 10.14.3`

**Expected & actual behavior**
External graphics card is not forced to be used

**Steps to reproduce**
On a Macbook Pro with an external graphics card:
1. Close all programs.
2. Verify onboard graphics card is in use.
3. Open Wavebox
4. Onboard graphics card should still be in use

**Is the bug persistent or intermittent?**
persistent

**Screenshots**
Screenshots often help us narrow down a bug more easily.

Wavebox closed:
<img width="582" alt="Screen Shot 2019-03-09 at 2 46 42 PM" src="https://user-images.githubusercontent.com/1595871/54078275-4bffa800-427a-11e9-9905-a7f1180b82eb.png">

Wavebox open:
<img width="581" alt="Screen Shot 2019-03-09 at 2 46 53 PM" src="https://user-images.githubusercontent.com/1595871/54078270-4013e600-427a-11e9-9890-f74f9683f41e.png">

**Comment by Thomas101** [comment]
Thanks for reporting. There's a new version of Wavebox (4.8.0) just shipped with a new version of Chromium inside, can you try updating to that first. Then under Settings > Advanced disable `Ignore GPU Blacklist` and restart the app.

I think this will make it stick more towards the integrated GPU.

**Comment by chrisblossom** [comment]
Looks like `4.8.0` solved the issue without having to disable `Ignore GPU Blacklist`. Is it recommended to turn this feature off regardless?

Thanks for the quick response!

**Comment by Thomas101** [comment]
> Is it recommended to turn this feature off regardless?

Normally best to leave it on. It tweaks the gpu settings based on a predefined compatibility list which gives the best compatibility :)

Great to hear that sorted it :)
