### ISSUE TITLE
Unable to change account icon in sidebar.

### ISSUE THREAD

**Issue by GollyJer** [wavebox/waveboxapp#970]
This feels like a really stupid question... for some reason I can't figure out how to get the sidebar to reflect my Wavebox account icon.

I did it in the past but I'm stuck with this new account.

Here is the sidebar.
![2019-03-11_12h07_01](https://user-images.githubusercontent.com/689204/54150980-ff8da700-43f6-11e9-9ff7-a3c41a746bde.png)

And here is the account settings.
![2019-03-11_12h11_02](https://user-images.githubusercontent.com/689204/54150996-0d432c80-43f7-11e9-8278-b89b655de9ae.png)

The two below the `JG` in the sidebar are also Trello accounts but the custom image is applied.

Recent bug? Or am I doing something wrong?

Thanks!
Jeremy

**Comment by nmat** [comment]
Does the icon change after a restart of the app?

**Comment by Thomas101** [comment]
There are two sets of icons for an account, these only really appear on-screen side-by-side when you have multiple services in an account. These are
1. The icon for the actual service - this is the one you've tried changing
2. The icon for the whole account

If the account only has one service (which I think might be the case here), one that's set on the account will overwrite the service one. Try scrolling to the top of that settings tab and see if anything has been set there.

![Screenshot 2019-03-12 at 09 20 45](https://user-images.githubusercontent.com/103586/54188737-3ff92d80-44a8-11e9-9312-d787775f4626.png)

**Comment by GollyJer** [comment]
Yes. The account only had one service.  I'm not even sure how multiple services would work with Trello.🤪
Anyway.. it's working now by change the Appearance icon.

![image](https://user-images.githubusercontent.com/689204/54247164-1e726300-44f5-11e9-965f-cf53b1ead85c.png)

**Comment by Thomas101** [comment]
>  I'm not even sure how multiple services would work with Trello.

You could pin anything into there via right-click `Add another service`😄
