### ISSUE TITLE
office 365 - compose does not close the popup after send

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#971]
* Wavebox Version: 4.8.0
* Operating System & Version: Windows 10
* Account type (if applicable): Office 365

**Expected & actual behavior**
Close the popup window after mail has been sent.

Keeps it open and asks for more commands.

**Steps to reproduce**
1. Create a new mail using Ctrl+N
2. Send the email from the popup

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**
Screenshots often help us narrow down a bug more easily.

**Additional information**
This is probably due to the workaround from issue:
https://github.com/wavebox/waveboxapp/issues/833

**Comment by Thomas101** [comment]
Thanks! I think that commit should do it :)

**Comment by nmat** [comment]
Awesome! thanks. I can test it in next beta :)

**Comment by Thomas101** [comment]
> Awesome! thanks. I can test it in next beta :)

Skipped beta and went straight to stable. 4.8.3 has this :)
