### ISSUE TITLE
Windows notifications click is not working

### ISSUE THREAD

**Issue by nicolafarina** [wavebox/waveboxapp#972]
* Wavebox Version: 4.8.1
* Operating System & Version: Windows 10

Seems that clicking on Windows notifications, Wavebox relative window is not focused anymore.

**Comment by nmat** [comment]
Which service are we talking about here?

Is it a any website notification or a standard service? Is also wavebox allowed to send notifications though so you can see them?

**Comment by Thomas101** [comment]
Thank, I've managed to reproduce this here, the click event doesn't fire.

When you go from 4.7.3 -> 4.8.2 via the autoupdate click events still fire
When you install 4.8.2 manually the click events don't

Still trying to figure out why...

**Comment by Thomas101** [comment]
I think I've got a fix for this. Unfortunately, it will need another release, so will push 4.8.3 tomorrow with this.

**Comment by Thomas101** [comment]
@nicolafarina thanks for reporting - this has just gone out in 4.8.3 :)

**Comment by nicolafarina** [comment]
Is definitely a pleasure to support this project helping with bug fixes. At the same time, you are my incubus with this release cycle, having to update Chocolatey package each time :-D

**Comment by Thomas101** [comment]
> you are my incubus with this release cycle

Sorry! I'm hoping this is the last one on stable for a while 🤞

**Comment by nicolafarina** [comment]
> Sorry! I'm hoping this is the last one on stable for a while 🤞

Totally unbelievable :-DDDD

**Comment by Thomas101** [comment]
Well time will tell :)

**Comment by Thomas101** [comment]
@nicolafarina [sorry...](https://github.com/wavebox/waveboxapp/releases/tag/v4.8.4) I'll cross my fingers again 🤞

**Comment by nicolafarina** [comment]
> @nicolafarina [sorry...](https://github.com/wavebox/waveboxapp/releases/tag/v4.8.4) I'll cross my fingers again 🤞

:-x
