### ISSUE TITLE
"Win" keyboard button in shortcuts

### ISSUE THREAD

**Issue by nicolafarina** [wavebox/waveboxapp#973]
Can be possible to use WIN keyboard button in shortcuts? I wish to use it for some global ones but I can use CTRL or ALT only.

Thanks.

**Comment by nmat** [comment]
At the moment I do not believe it is possible. There is a project called: https://github.com/wavebox/waveboxapp/projects/7

Which is for the keybinding part. But I am not sure of the status or progress

**Comment by Thomas101** [comment]
For the just global shortcuts, you can use the `Super` modifier. It's worth noting that if Windows maps the key combination in some way already it will use it and not pass through to Wavebox. For example...

* `Super+Q` opens cortana search - doesn't work
* `Ctrl+Super+Q` can be used to toggle the app

It's a bit of trial and error as to what's bound and what isn't :)

**Comment by nicolafarina** [comment]
Thanks for the tip anyway.

**Comment by Thomas101** [comment]
Sorry, I forgot to say that `Super` is the WIN key - just if that wasn't clear 🤦‍♂️

Am I okay to close?

**Comment by nicolafarina** [comment]
Sure thanks.
