### ISSUE TITLE
Youtube will not Maximize within Wavebox

### ISSUE THREAD

**Issue by 97watt** [wavebox/waveboxapp#976]
Wavebox Version: 4.8.2
Operating System: Windows 10

Youtube does not maximize within wavebox. This worked in previous versions.

![Annotation 2019-03-13 094142](https://user-images.githubusercontent.com/45032943/54285236-f841d700-4577-11e9-8ea6-6d1847e4df23.jpg)

**Comment by Thomas101** [comment]
Thanks for reporting - we already have an issue open for this https://github.com/wavebox/waveboxapp/issues/969
