### ISSUE TITLE
Wavebox crashes Cinnamon desktop

### ISSUE THREAD

**Issue by gecharita** [wavebox/waveboxapp#977]
* Wavebox Version: [4.8.3 and some versions before]
* Operating System & Version: 
      [**Linux Mint 19.1**, Cinnamon 4.0.9, 64-bit)
      [**Linux Mint 18.3**, Cinnamon 3.6.7, 64-bit):
* (Linux only) Install method: [Apt-Repo]

**Expected & actual behavior**
Every time I update Wavebox (**apt-get**) my Cinnamon desktop freezes & after a while it prompts to restart.

**Comment by nmat** [comment]
Do you have any other electron applications that is updated in the same way?

Can you also provide the apt source you use for upgrading?

**Comment by gecharita** [comment]
The apt source is: **https://wavebox.io/dl/client/repo/ x86_64/**.
I am using some other electron applications with no such problem.

**Comment by Thomas101** [comment]
When you run apt-get is Wavebox one of the apps that gets updated and is Wavebox running at the time?

**Comment by gecharita** [comment]
When I run apt-get Wavebox is one of the apps that get updated. I have tried all the following combinations:

- update only Wavebox while running
- update only Wavebox while not running
- update many apps & Wavebox while running
- update many apps & Wavebox while not running
 
The problem occurs in all circumstances.

**Comment by Thomas101** [comment]
I've given this a try on a fresh 19.1 VM but everything seems to work fine.

It's probably worth trying to remove the Wavebox repo and trying an update without it, just to isolate if it's the actual repo entry that's causing it. To do this, just open `/etc/apt/sources.list.d/repo.list` and remove the `deb https://wavebox.io/dl/client/repo/ x86_64/` line from it.

**Comment by gecharita** [comment]
I have done it & I am waiting for the next update.

**Comment by gecharita** [comment]
It seems that with the new version (**4.9.0**) the issue has been fixed. Thank you!

**Comment by Thomas101** [comment]
Awesome, let me know if it comes up again!
