### ISSUE TITLE
Need sharp small icon on Windows 10

### ISSUE THREAD

**Issue by ToLive** [wavebox/waveboxapp#979]
![Ticket20190315_1342_2611](https://user-images.githubusercontent.com/2019736/54413579-c6bc3d80-4728-11e9-9537-9b303399d797.png)

Please, make small icon in the task bar a bit cleaner, without sharp edges.

**Comment by Thomas101** [comment]
Looks like the drop-shadow was carried through to the small icon - which causes the black edge on lighter backgrounds. Updated it for the next release, thanks!

![Screenshot 2019-03-15 at 16 01 02](https://user-images.githubusercontent.com/103586/54444909-9d58dd00-473b-11e9-92c1-8d59cc218d0e.png)

**Comment by ToLive** [comment]
Thank you!

**Comment by Thomas101** [comment]
Hey, that's just gone out in the latest update (4.8.4).
