### ISSUE TITLE
Conflicting keyboard shortcuts on Azerty (Belgian) keyboard

### ISSUE THREAD

**Issue by Timmmy** [wavebox/waveboxapp#98]
On a Azerty keyboard (Belgian - period) the AltGr + 2 shortcut is used for the <at> symbol.
In Wavebox, this is however also mapped to moving to another "tab".

This makes it impossible to type the <at> symbol in Google Inbox without copy-pasting it from another program. A switch to disable the switching tab behavior would be nice. (Maybe it is already in there, but I wasn't able to find it).

Thanks for making a great desktop mail client!

Tim 

Encountered in Wavebox 3.1.5 on Windows 10

**Comment by Thomas101** [comment]
Thanks for reporting. I think there's a couple of conflicting shortcuts on osx too. Will look at adding some keyboard mapping tools into Wavebox to avoid this.

Also related https://github.com/wavebox/waveboxapp/issues/92

**Comment by Thomas101** [comment]
Hi, I've just pushed 3.1.6 out which removes some of the conflicting keyboards shortcuts and also has support for setting your own. If you do find any that conflict or that you want to change, open up the Settings and then go to Advanced. From there you can change or disable keyboard shortcuts

You can download it from [wavebox.io/download](https://wavebox.io/download) or Wavebox should update itself over the next day or so. Thanks!

**Comment by Timmmy** [comment]
Hi Thomas,

Thank you for tackling this issue and adding this functionality so quickly!
Works like a charm :)
You guys rock!

Tim
