### ISSUE TITLE
Add vimium extension

### ISSUE THREAD

**Issue by iocanel** [wavebox/waveboxapp#981]
* Wavebox Version: all
* Operating System & Version: all

**Describe the solution you'd like**
It would be nice to have vimium as an extension, so power users can use keyboard to search, navigate etc. 

**Additional info**
https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb

**Comment by nmat** [comment]
Hello,

There is a thread for extensions: https://github.com/wavebox/waveboxapp/issues/138

You can add the request there so its easier to keep track of the requests.

**Comment by Thomas101** [comment]
We are planning a push on extensions over the next 2-3 months, so I'll add this one to the list and track from #138
