### ISSUE TITLE
Feature Request: Add possibility to chose your own tray icons

### ISSUE THREAD

**Issue by Chinney** [wavebox/waveboxapp#984]
* Wavebox Version: 4.7.3
* Operating System & Version: Ubuntu 16.04

**Is your feature request related to a problem? Please describe.**
No.

**Is your feature request related to an account type?**
No.

**Describe the solution you'd like**
Currently it is possible to customize the tray icon by colors. I'd be quite grateful to be provided with the possibility to chose your own private tray icon as svg or png file. 

**Additional info**
I do this with every program on my computer that has a tray icon to make them match perfectly one another and fit in with my personal theme. Usually you can just exchange the files in some sub folder of the program but this is not possible with wavebox (or at least I havn't found the folder yet).

**Comment by Thomas101** [comment]
The icon is generated on the fly at the moment so we can support 0-99, dots etc. Is it just a static icon that you'd want to set (e.g. the same one regardless of the unread count?)

**Comment by Chinney** [comment]
Yes exactly. Either I have new messages to check or not. Doesn't matter how many.

**Comment by Thomas101** [comment]
Going out in the next release :)

![Screenshot 2019-03-22 at 15 19 04](https://user-images.githubusercontent.com/103586/54833371-de11a280-4cb5-11e9-9d6e-211329d36c17.png)

**Comment by nmat** [comment]
Quickly tested on master and seems to work fine.

svg icons with transparent background has a interesting effect though so might be good to advice on using non transparent icons.

**Comment by Chinney** [comment]
Thank You!

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.8.5. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
