### ISSUE TITLE
Muted Whatsapp chats show as notification

### ISSUE THREAD

**Issue by zbhoy** [wavebox/waveboxapp#986]
* Wavebox Version: [4.8]
* Operating System & Version: [Win 10]
* Account type (if applicable): [Whatsapp]

**Expected & actual behavior**

Expect muted chats in whatsapp to not show as a notification in whatsapp
Actual behavior is they are shown

**Steps to reproduce**
Use whatsapp with a muted chat

**Is the bug persistent or intermittent?**
Always

**Comment by nmat** [comment]
Can you provide the settings you are using for the notifications on both wavebox and whatsapp?

**Comment by zbhoy** [comment]
![Annotation 2019-03-21 104021](https://user-images.githubusercontent.com/1595366/54764627-26ea2e00-4bc6-11e9-9891-b97a1540c010.jpg)
![Annotation 2019-03-21 103956](https://user-images.githubusercontent.com/1595366/54764629-26ea2e00-4bc6-11e9-9194-fe5ee95f1d1b.jpg)

**Comment by Thomas101** [comment]
I think I have an idea on how to fix this 👍

**Comment by Thomas101** [comment]
Ref: https://github.com/wavebox/wavebox-service-api/commit/ab957060f772ed46f6174669b003bde6e42e551c

I've put a fix out for this. Your client will grab it automatically, but if you want to force it to grab the update, quitting the app and starting it again should work.

I've also added in the unread message info into Wavebox Mini. The current version of Wavebox just shows the sender, the next beta will have support for the message content too.

**Current**
![Screenshot 2019-03-22 at 10 21 16](https://user-images.githubusercontent.com/103586/54817177-2a48ec80-4c8e-11e9-985c-c82c5f8b9656.png)

**4.8.5 when released**
![Screenshot 2019-03-22 at 10 20 17](https://user-images.githubusercontent.com/103586/54817155-2026ee00-4c8e-11e9-97f9-ffc62723e580.png)

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.8.5. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
