### ISSUE TITLE
Allow set custom URL of Riot instance host

### ISSUE THREAD

**Issue by MurzNN** [wavebox/waveboxapp#987]
Riot.im is opensource and very often used as self-hosted service on user domains. So client urls may be different.
Also official Riot instance have three versions:
http://riot.im/app/
http://riot.im/staging/
http://riot.im/develop/

So, please add field to fill custom url (host) for Riot instance in service settings.

**Comment by nmat** [comment]
At the moment this would be considered a "Add any website" because the main service is based on the cloud based service.

Not sure if there are plans to do a URL change in the service that is bound for cloud based login.

however you can still add the service the way you want just by using "Add any website"

**Comment by MurzNN** [comment]
Riot cloud based service suggests to use own hosts with Riot, instead of using it at riot.im website. So most of Matrix.org users use Riot on own domains, not the default one. Via "Add any website" I can add custom host, but I will lost notification counts and other integration features :(

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.8.5. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
