### ISSUE TITLE
Load custom Account Icon from external url instead of local file

### ISSUE THREAD

**Issue by MurzNN** [wavebox/waveboxapp#988]
At now users can only use custom Account Icons from local files. Most of services provide favicons and Apple Touch icons at static urls, that can be used as Account Icon without manually downloading to computer.

So please add feature for load custom Account Icons, loaded from external url, that user enter manually in current account settings.

**Comment by Thomas101** [comment]
At the moment, this isn't something we're looking at adding. The majority of users are comfortable with uploading an icon from their machine - whether this has been downloaded beforehand or found specifically. When this isn't the case, the app picks out any favicon's or uses default icons wherever possible to reduce the need to upload icons etc.
