### ISSUE TITLE
Use current page favicon as Account Icon in interface

### ISSUE THREAD

**Issue by MurzNN** [wavebox/waveboxapp#989]
At now all manually added services have standard "Cloud" Account Icon. Users can upload manual icon from local files, but they must find them, save to computer, upload to Wavebox.

But why not to use as default - favicon of current page, opened in this service? Can you add option to use current page favicon as Account Icon of custom service?

**Comment by Thomas101** [comment]
The favicon should be automatically used when there's no icon set. For example adding `google.com` or `facebook.com` uses those icons automatically...

![Screenshot 2019-03-22 at 15 45 37](https://user-images.githubusercontent.com/103586/54835273-b1f82080-4cb9-11e9-9dc7-a3afd40baad6.png)

**Comment by MurzNN** [comment]
I add yougile.com and vk.com websites, but see in list only clouds:
![изображение](https://user-images.githubusercontent.com/336662/54861792-8ff5b100-4d40-11e9-8e54-2f68837d9f65.png)

**Comment by Thomas101** [comment]
Thanks, looks like the parsing rules for valid favicons are a bit too strict...

**Comment by MurzNN** [comment]
Also will be good to check `<link rel="apple-touch-icon">` sources of page, in most cases they contain favicon with better resolution, that `<link rel="shortcut icon">`.

**Comment by Thomas101** [comment]
We use the icons that chromium provides, which normally provides all the icons including the apple-touch ones, but I've just noticed in the case of `vk.com` it only provides the `.ico` version. I'll have a look at why that is

**Comment by Thomas101** [comment]
Hi, we’ve just released this to the beta channel of Wavebox in version 4.9.5. If you want to give it a try there are some instructions on [how to use the beta channel here](https://wavebox.io/kb/beta-channel). Thanks

**Comment by Thomas101** [comment]
Hi, this has just been released in the latest version of Wavebox. You can get the update by using the Application/File menu and clicking `Check for Update` or by downloading the latest version from our [download page](https://wavebox.io/download). Thanks!
