### ISSUE TITLE
Move all cache files (Cache, GPUCache) from .config to .cache folder in Linux

### ISSUE THREAD

**Issue by MurzNN** [wavebox/waveboxapp#990]
At now Wavebox stores huge amount of cache files on Linux in same folder, as config files, in `~/.config` folder of home location, instead of use standard `~/.cache` folder, here is cache files locations:
```
~/.config/wavebox/Cache
~/.config/wavebox/GPUCache
~/.config/wavebox/Partitions/*/Cache
~/.config/wavebox/Partitions/*/GPUCache
```
Those folders in my instance contains more than 1000 files with total size more than 500 Mb. 
I can successfully remove those files on each Wavebox restart, and they will be restored without losing any settings or cookies.

All other Linux apps use `.config` folder only for store settings, that many users sync and backups. So total size of `.config` folder is not too large, and files changes not frequently. And `.cache` folder often moved to quick non-backuped storage.

So, please move all cache files from `.config` to `.cache` folder, for make `.config` folder lighter.

**Comment by Thomas101** [comment]
This is down to electron and previously chromium storing cache data under `.config`. There's some lengthy discussion here https://github.com/electron/electron/issues/8124 about how best to move or migrate this data, but at the moment there's no way to configure the `.cache` folder for electron
