### ISSUE TITLE
Per-Service RAM memory usage report

### ISSUE THREAD

**Issue by MurzNN** [wavebox/waveboxapp#991]
Sometimes Wavebox use too much RAM, and often the source of this memory problem is some Service webpage. So will be good to have per-service memory report page in Wavebox to analyze huge memory usage and leaks problems. Is this hard to implement?

**Comment by Ash258** [comment]
Settings > Advanced > Debug > Task Monitor

**Comment by MurzNN** [comment]
Wow! Thanks!
