### ISSUE TITLE
Extend Wavebox Basic free subscription plan features 

### ISSUE THREAD

**Issue by MurzNN** [wavebox/waveboxapp#992]
Wavebox Basic subscription plan provide only 2 Gmail accounts and that's all? So no other services allowed? Those limits make use of free version useless for most users!

All alternatives (eg Rambox, Franz) provide unlimited services list in free plans, so users will select those solutions as free messengers aggregator, instead of Wavebox.

So please compare free plans features with competitors and consider expanding the functionality of free version.

**Comment by nmat** [comment]
If you have questions regarding this I would suggest to send the request through: https://wavebox.io/support

This github is mostly for issues with the application itself. So its better to send the questions for that to the support I think.
