### ISSUE TITLE
Adblocking don't work on Youtube

### ISSUE THREAD

**Issue by VarunAgw** [wavebox/waveboxapp#993]
* Wavebox Version: Latest
* Operating System & Version: Windows 10 1809 x64

Adblocker shipped with it fails on youtube.com and I think also on https://music.youtube.com/

**Comment by nmat** [comment]
I am thinking it can be related to: https://github.com/wavebox/waveboxapp/issues/933

**Comment by VarunAgw** [comment]
Always

**Comment by nmat** [comment]
yes verified here also. I can see the ads being shown. hmmmm

**Comment by Thomas101** [comment]
We've got more to do on this - at the moment the ad-blocker just blacklists domains whereas YouTube needs something a bit more intelligent.

Going to continue tracking on #933 thanks!
