### ISSUE TITLE
Zendesk components no longer load

### ISSUE THREAD

**Issue by lherlitz** [wavebox/waveboxapp#995]
* Wavebox Version: 4.8.4
* Operating System & Version: macOS 10.14.3
* Account type (if applicable): Zendesk

**Expected & actual behavior**
Components of the Zendesk interface that were working last week are not working this week.

**Steps to reproduce**
Open Zendesk and try to use the Knowledge search

**Is the bug persistent or intermittent?**
always

**Screenshots**
[![Clean-Shot-2019-03-27-at-08-39-50-2x.png](https://i.postimg.cc/J44vHr76/Clean-Shot-2019-03-27-at-08-39-50-2x.png)](https://postimg.cc/Sj3DwpMC)

**Additional information**
In the console, the components failing read `ERR_CONTENT_DECODING_FAILED`

**Comment by nmat** [comment]
I can't reproduce this. Can you give some more information of exactly where you are clicking to get the error?

**Comment by Thomas101** [comment]
It might just be that Zendesk was having a bad day and sent some mungled responses - then you're machine has cached those :-/.

Try deleting the account and adding it again. This will clear out any cached responses etc and you might find it works from there

**Comment by lherlitz** [comment]
It’s working now. :D
