### ISSUE TITLE
Okta / Duo - Chrome is out of date

### ISSUE THREAD

**Issue by Fuzzwah** [wavebox/waveboxapp#998]
* Wavebox Version: 4.9.0
* Operating System & Version: Windows 10 & Mac OSX 10.14.3
* Account type (if applicable): Gmail

**Expected & actual behavior**
Successful Duo login

**Steps to reproduce**
Attempt to log into Duo secured account

**Is the bug persistent or intermittent?**
Persistent

**Screenshots**

![image](https://user-images.githubusercontent.com/658935/55294843-6b8d8900-5452-11e9-891d-8265fe8ab220.png)

**Comment by Thomas101** [comment]
Hey thanks for reporting, we've just pushed a new version (4.9.1) which should fix this!

The app will update itself shortly, or if you want to grab it right away you can go to `Wavebox` > `Check for Update` on macOS or `Settings` > `Update` > `Check for update now` on Windows
