### ISSUE TITLE
Set default icon does not work on main service but works on sub service

### ISSUE THREAD

**Issue by nmat** [wavebox/waveboxapp#999]
* Wavebox Version: 4.9.1
* Operating System & Version: Windows 10
* Account type (if applicable): Slack

**Expected & actual behavior**
Be able to change to Default icon on main service when there are subservices.

Sub services can change icon but the main service does not have the option available.

**Steps to reproduce**
1. Create a new slack main service
2. Login to a account somewhere
3. Add a new service which is also slack

See different in Slack account settings and for each service.

**Is the bug persistent or intermittent?**
Persistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/383031/55378458-5891bc00-5519-11e9-9c69-84fd2f080db2.png)

![image](https://user-images.githubusercontent.com/383031/55378505-8545d380-5519-11e9-8341-73c27235dea9.png)

**Additional information**
The only place I actually change the icon is on the main service but never really on the sub service of the main one.

**Comment by Thomas101** [comment]
Fair point, I've bubbled it up for accounts with just a single service :)

**Comment by nmat** [comment]
Not sure if I am doing something wrong here but in latest git I still can't see the option to use default icon:

![image](https://user-images.githubusercontent.com/383031/55421229-113b1800-5579-11e9-85ad-e2ae58d93d3b.png)

**Comment by Thomas101** [comment]
I was only showing it when the account had just one service. Changed it to always use the first service regardless of how many there are.

Also released in 4.9.2 :)

**Comment by nmat** [comment]
Verified and working thank you!
